// Currículos completos para preparación de exámenes oficiales
// Basado en especificaciones de exámenes internacionales (MCER)

export interface CurriculumLevel {
  level: string;
  name: string;
  duration: string;
  description: string;
  grammarTopics: string[];
  vocabularyAreas: string[];
  skills: {
    reading: string[];
    writing: string[];
    listening: string[];
    speaking: string[];
  };
  examFormat: {
    parts: number;
    duration: string;
    passing: string;
  };
}

export const EXAM_CURRICULUM: Record<string, CurriculumLevel> = {
  a1: {
    level: 'A1',
    name: 'Principiante',
    duration: '8-10 semanas',
    description: 'Nivel inicial para quienes comienzan desde cero. Aprenderás a comunicarte en situaciones básicas y cotidianas.',
    grammarTopics: [
      'Verbo "to be" (presente simple)',
      'Pronombres personales (I, you, he, she, it, we, they)',
      'Artículos (a, an, the)',
      'Presente simple (afirmativo, negativo, interrogativo)',
      'Adjetivos posesivos (my, your, his, her, etc.)',
      'Plurales regulares e irregulares',
      'Preposiciones de lugar (in, on, at, under, next to)',
      'Preposiciones de tiempo (at, on, in)',
      'Números cardinales y ordinales',
      'There is / There are',
      'Can / Can\'t para habilidades',
      'Imperativo (órdenes y direcciones)',
      'Presente continuo (acciones en progreso)',
      'Adjetivos básicos (big, small, nice, etc.)',
      'Conectores básicos (and, but, or)',
    ],
    vocabularyAreas: [
      'Saludos y presentaciones personales',
      'Familia y relaciones',
      'Números del 1 al 100',
      'Colores',
      'Días de la semana y meses del año',
      'La hora y rutinas diarias',
      'Comida y bebida básica',
      'Animales domésticos comunes',
      'Partes del cuerpo básicas',
      'Ropa y accesorios básicos',
      'La casa y habitaciones',
      'Objetos del hogar',
      'El tiempo atmosférico',
      'Países y nacionalidades básicas',
      'Profesiones comunes',
      'Deportes populares',
      'Hobbies y tiempo libre básicos',
      'Transportes comunes',
      'La escuela y el aula',
      'Tiendas y lugares en la ciudad',
    ],
    skills: {
      reading: [
        'Comprender textos muy breves y sencillos',
        'Leer nombres familiares, palabras y frases',
        'Entender mensajes cortos en tarjetas postales',
        'Comprender letreros y carteles simples',
        'Encontrar información específica en material simple',
      ],
      writing: [
        'Escribir postales cortas y simples',
        'Rellenar formularios con datos personales',
        'Escribir frases simples sobre ti y tu familia',
        'Hacer listas de compras o tareas',
        'Escribir mensajes cortos y notas simples',
      ],
      listening: [
        'Reconocer palabras y expresiones básicas',
        'Entender números, precios y horarios',
        'Comprender instrucciones simples',
        'Identificar información personal en conversaciones',
        'Entender preguntas y respuestas básicas',
      ],
      speaking: [
        'Presentarte a ti mismo y a otros',
        'Hacer y responder preguntas personales básicas',
        'Describir tu casa, familia y posesiones',
        'Pedir y dar direcciones simples',
        'Expresar gustos y disgustos básicos',
        'Hablar sobre actividades cotidianas',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '60-70 minutos',
      passing: 'Certificado sin nota de corte',
    },
  },

  a2: {
    level: 'A2',
    name: 'Elemental',
    duration: '10-12 semanas',
    description: 'Nivel elemental para desenvolverse en situaciones cotidianas predecibles. Ideal para viajes y conversaciones básicas.',
    grammarTopics: [
      'Pasado simple (verbos regulares e irregulares)',
      'Was / Were',
      'Futuro con "going to"',
      'Futuro con "will"',
      'Presente perfecto simple (introducción)',
      'Comparativos y superlativos',
      'Adverbios de frecuencia',
      'Cuantificadores (some, any, much, many, a lot of)',
      'Pronombres objeto (me, you, him, her, etc.)',
      'Genitivo sajón',
      'Preguntas con wh- (what, where, when, why, how)',
      'Must / Have to para obligación',
      'Should para consejos',
      'Like + -ing',
      'Would like',
      'Conectores (because, so, but, and)',
      'Adjetivos posesivos vs pronombres posesivos',
    ],
    vocabularyAreas: [
      'Descripciones físicas y de personalidad',
      'Actividades de ocio y deportes',
      'Comida, restaurantes y recetas básicas',
      'Compras y precios',
      'Salud y partes del cuerpo',
      'Viajes y vacaciones',
      'El tiempo libre y hobbies',
      'Trabajo y profesiones',
      'Educación y estudios',
      'Tecnología básica',
      'Medios de transporte',
      'Direcciones en la ciudad',
      'Alojamiento (hoteles, casas)',
      'Eventos y celebraciones',
      'El medio ambiente básico',
      'Experiencias personales',
      'Planes futuros',
      'Descripción de lugares',
      'Comunicación (teléfono, email)',
      'Sentimientos y emociones básicas',
    ],
    skills: {
      reading: [
        'Leer textos cortos y simples',
        'Encontrar información específica en folletos y anuncios',
        'Comprender descripciones simples de eventos',
        'Entender cartas personales breves',
        'Leer instrucciones sencillas',
      ],
      writing: [
        'Escribir notas y mensajes cortos',
        'Redactar emails informales simples',
        'Describir eventos pasados',
        'Escribir sobre planes futuros',
        'Expresar opiniones simples',
      ],
      listening: [
        'Comprender conversaciones cotidianas',
        'Entender información en tiendas y restaurantes',
        'Seguir direcciones e instrucciones',
        'Captar información en anuncios públicos',
        'Entender descripciones simples',
      ],
      speaking: [
        'Describir experiencias y eventos',
        'Hacer planes y sugerencias',
        'Expresar opiniones básicas',
        'Dar razones y explicaciones simples',
        'Describir personas y lugares',
        'Contar historias simples sobre el pasado',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '90-100 minutos',
      passing: 'Certificado con calificación (shields)',
    },
  },

  b1: {
    level: 'B1',
    name: 'Intermedio',
    duration: '12-14 semanas',
    description: 'Nivel intermedio para comunicarse con confianza en situaciones familiares. Podrás trabajar y viajar de manera independiente.',
    grammarTopics: [
      'Presente perfecto vs pasado simple',
      'Presente perfecto continuo',
      'Pasado continuo',
      'Used to / Would (hábitos pasados)',
      'Pasado perfecto simple',
      'Futuro continuo',
      'Primer condicional (real)',
      'Segundo condicional (hipotético)',
      'Voz pasiva (presente y pasado simple)',
      'Modales de posibilidad (may, might, could)',
      'Modales de obligación y prohibición',
      'Estilo indirecto (reported speech básico)',
      'Oraciones de relativo (who, which, that, where)',
      'Conjunciones (although, however, despite)',
      'So / Such',
      'Too / Enough',
      'Phrasal verbs comunes',
      'Gerundios e infinitivos',
    ],
    vocabularyAreas: [
      'Trabajo y vida profesional',
      'Educación y formación',
      'Viajes y turismo avanzado',
      'Tecnología y medios de comunicación',
      'Salud y bienestar',
      'Medio ambiente y naturaleza',
      'Cultura y entretenimiento',
      'Relaciones personales',
      'Sentimientos y emociones complejas',
      'Opiniones y argumentos',
      'Problemas sociales básicos',
      'Dinero y administracion personales',
      'Comida y nutrición',
      'Moda y apariencia',
      'Deportes y fitness',
      'Crimen y justicia básica',
      'Ciencia y descubrimientos',
      'Historia y eventos',
      'Geografía y países',
      'Arte y música',
    ],
    skills: {
      reading: [
        'Comprender textos sobre temas cotidianos y laborales',
        'Leer artículos y reportajes con opiniones',
        'Entender instrucciones detalladas',
        'Comprender correspondencia personal y laboral',
        'Seguir argumentos en textos sobre temas familiares',
      ],
      writing: [
        'Escribir textos coherentes sobre temas familiares',
        'Redactar cartas personales expresando experiencias',
        'Escribir emails formales básicos',
        'Componer ensayos cortos con opinión',
        'Describir eventos, sentimientos y reacciones',
      ],
      listening: [
        'Comprender conversaciones sobre temas cotidianos',
        'Seguir los puntos principales en noticias',
        'Entender charlas sobre temas familiares',
        'Captar información en programas de TV/radio',
        'Seguir direcciones e instrucciones complejas',
      ],
      speaking: [
        'Participar en conversaciones sin preparación',
        'Expresar opiniones y justificarlas',
        'Describir experiencias y ambiciones',
        'Dar razones y explicaciones',
        'Narrar historias con detalles',
        'Discutir ventajas y desventajas',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '140 minutos',
      passing: 'Grado A, B, C (140-159 puntos)',
    },
  },

  b2: {
    level: 'B2',
    name: 'Intermedio Alto',
    duration: '14-16 semanas',
    description: 'Nivel intermedio-alto para trabajar en inglés con confianza. Podrás comunicarte fluidamente en contextos académicos y profesionales.',
    grammarTopics: [
      'Todos los tiempos verbales (revisión avanzada)',
      'Voz pasiva completa (todos los tiempos)',
      'Estilo indirecto avanzado (reporting verbs)',
      'Condicionales mixtos',
      'Tercer condicional (irreal pasado)',
      'Wish / If only',
      'Modales en pasado (must have, should have, etc.)',
      'Oraciones de relativo con preposiciones',
      'Inversión (Rarely, Never, Only)',
      'Énfasis con cleft sentences',
      'Phrasal verbs avanzados',
      'Colocaciones avanzadas',
      'Linking words avanzados',
      'Subjuntivo (I suggest that he be...)',
      'Expresiones idiomáticas',
      'Estructuras causativas (have/get something done)',
      'Elipsis y sustitución',
    ],
    vocabularyAreas: [
      'Negocios y economía',
      'Medio ambiente y sostenibilidad',
      'Tecnología e innovación',
      'Ciencia y descubrimientos científicos',
      'Salud y medicina',
      'Educación superior y formación',
      'Política y sociedad',
      'Crimen y ley',
      'Medios de comunicación y periodismo',
      'Arte, literatura y cultura',
      'Psicología y comportamiento humano',
      'Globalización e interculturalidad',
      'Ética y valores',
      'Historia contemporánea',
      'Turismo sostenible',
      'Marketing y publicidad',
      'Recursos humanos',
      'Emprendimiento',
      'Investigación académica',
      'Desarrollo personal y profesional',
    ],
    skills: {
      reading: [
        'Leer artículos y reportajes sobre temas actuales',
        'Comprender prosa literaria contemporánea',
        'Entender textos académicos y técnicos',
        'Analizar argumentos complejos',
        'Captar actitudes y opiniones implícitas',
      ],
      writing: [
        'Escribir textos claros y detallados sobre diversos temas',
        'Redactar ensayos o informes con argumentos',
        'Componer cartas formales complejas',
        'Escribir reviews y críticas',
        'Desarrollar ideas con estructura lógica',
      ],
      listening: [
        'Seguir charlas extensas y argumentaciones complejas',
        'Comprender programas de TV y películas',
        'Entender la mayoría de noticias y programas actuales',
        'Seguir conversaciones técnicas en tu área',
        'Captar detalles y matices en conversaciones',
      ],
      speaking: [
        'Conversar con fluidez y espontaneidad',
        'Participar activamente en discusiones formales',
        'Presentar descripciones claras y detalladas',
        'Argumentar un punto de vista con pros y contras',
        'Especular sobre causas y consecuencias',
        'Manejar situaciones imprevistas',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '210 minutos',
      passing: 'Grado A, B, C (160-179 puntos)',
    },
  },

  c1: {
    level: 'C1',
    name: 'Avanzado',
    duration: '16-18 semanas',
    description: 'Nivel avanzado para usar el inglés de manera efectiva en contextos académicos y profesionales exigentes.',
    grammarTopics: [
      'Estructuras avanzadas complejas',
      'Inversión completa (formal y enfática)',
      'Subjuntivo completo',
      'Estructuras elípticas avanzadas',
      'Nominalization (convertir verbos en sustantivos)',
      'Fronting (énfasis mediante cambio de orden)',
      'Discourse markers sofisticados',
      'Hedging language (lenguaje de matización)',
      'Participle clauses',
      'Split infinitives',
      'Doble comparativos',
      'Reduced relative clauses',
      'Adverbios de manera y posición avanzados',
      'Verbos estativos y dinámicos (usos avanzados)',
      'Aspectos gramaticales sutiles',
      'Estilo formal vs informal avanzado',
      'Expresiones idiomáticas avanzadas',
    ],
    vocabularyAreas: [
      'Lenguaje académico formal',
      'Terminología técnica especializada',
      'Discurso político y diplomático',
      'Finanzas y economía avanzada',
      'Derecho y jurisprudencia',
      'Medicina y biotecnología',
      'Filosofía y ética',
      'Literatura y crítica literaria',
      'Arquitectura y urbanismo',
      'Ingeniería y tecnología avanzada',
      'Investigación científica',
      'Análisis de datos y estadística',
      'Gestión empresarial estratégica',
      'Relaciones internacionales',
      'Antropología y sociología',
      'Psicología clínica y social',
      'Medio ambiente y políticas públicas',
      'Industrias creativas',
      'Lenguaje metafórico y figurativo',
      'Colocaciones y expresiones idiomáticas avanzadas',
    ],
    skills: {
      reading: [
        'Comprender textos largos y complejos',
        'Entender textos literarios con apreciación de estilo',
        'Analizar artículos especializados fuera de tu campo',
        'Captar significados implícitos',
        'Distinguir diferentes estilos de escritura',
      ],
      writing: [
        'Escribir textos claros y bien estructurados',
        'Expresar puntos de vista con estructura compleja',
        'Escribir cartas, ensayos o informes complejos',
        'Usar estilo apropiado para diferentes audiencias',
        'Desarrollar argumentos sistemáticamente',
      ],
      listening: [
        'Seguir charlas extensas incluso sin estructura clara',
        'Comprender programas de TV y películas sin esfuerzo',
        'Entender discursos extensos y seguir argumentos complejos',
        'Captar referencias culturales',
        'Entender acentos y variedades del inglés',
      ],
      speaking: [
        'Expresarte con fluidez y espontaneidad',
        'Usar el lenguaje de forma flexible y efectiva',
        'Presentar descripciones y argumentos complejos',
        'Desarrollar puntos de vista con subtemas',
        'Concluir apropiadamente',
        'Adaptar tu discurso a diferentes contextos',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '236 minutos',
      passing: 'Grado A, B, C (180-199 puntos)',
    },
  },

  c2: {
    level: 'C2',
    name: 'Maestría',
    duration: '18-20 semanas',
    description: 'Nivel de maestría cercano al nativo. Dominio excepcional del inglés en cualquier contexto, incluyendo situaciones académicas y profesionales de alto nivel.',
    grammarTopics: [
      'Dominio completo de todas las estructuras',
      'Uso sofisticado de la inversión',
      'Matices sutiles del subjuntivo',
      'Estructuras retóricas complejas',
      'Registro lingüístico muy variado',
      'Elipsis avanzada y sustitución',
      'Construcciones arcaicas y literarias',
      'Uso enfático mediante estructuras complejas',
      'Manipulación del orden de palabras para efectos',
      'Uso de estructuras paralelas',
      'Subordinación múltiple y compleja',
      'Uso idiomático de partículas',
      'Colocaciones altamente especializadas',
      'Metáforas gramaticalizadas',
      'Estructuras de cohesión complejas',
      'Variación estilística sofisticada',
      'Nominalización compleja',
    ],
    vocabularyAreas: [
      'Vocabulario extremadamente amplio y preciso',
      'Terminología altamente especializada multidisciplinar',
      'Lenguaje literario y poético',
      'Jerga profesional avanzada',
      'Expresiones idiomáticas complejas',
      'Vocabulario arcaico y literario',
      'Neologismos y términos emergentes',
      'Lenguaje académico de nivel doctoral',
      'Retórica y argumentación avanzada',
      'Crítica literaria y cultural',
      'Filosofía y teoría compleja',
      'Ciencia de vanguardia',
      'Derecho internacional y comparado',
      'Economía y administracion especializadas',
      'Medicina especializada',
      'Tecnología cutting-edge',
      'Arte y estética avanzada',
      'Lingüística aplicada',
      'Metáforas conceptuales complejas',
      'Registro formal extremadamente elevado',
    ],
    skills: {
      reading: [
        'Comprender con facilidad prácticamente cualquier texto',
        'Entender textos abstractos complejos (manuales, artículos especializados)',
        'Apreciar distinciones sutiles de estilo',
        'Captar humor, ironía y referencias culturales',
        'Leer literatura clásica con plena comprensión',
      ],
      writing: [
        'Escribir textos claros y fluidos en estilo apropiado',
        'Redactar cartas, informes o artículos complejos',
        'Presentar casos complejos con estructura efectiva',
        'Escribir resúmenes y reseñas de obras especializadas',
        'Usar vocabulario preciso y variado',
      ],
      listening: [
        'Comprender cualquier tipo de lengua hablada',
        'Entender sin esfuerzo habla rápida de nativos',
        'Seguir debates técnicos fuera de tu especialidad',
        'Captar matices sutiles de significado',
        'Entender coloquialismos y referencias culturales',
      ],
      speaking: [
        'Participar sin esfuerzo en cualquier conversación',
        'Presentar argumentos complejos de forma persuasiva',
        'Usar expresiones idiomáticas con naturalidad',
        'Ajustar el registro según el contexto',
        'Transmitir sutilezas de significado con precisión',
        'Hablar con fluidez similar a un nativo educado',
      ],
    },
    examFormat: {
      parts: 4,
      duration: '236 minutos',
      passing: 'Grado A, B, C (200+ puntos)',
    },
  },
};

// Función para obtener curriculum por nivel
export function getCurriculumByLevel(level: string): CurriculumLevel | null {
  return EXAM_CURRICULUM[level.toLowerCase()] || null;
}

// Función para obtener todos los niveles
export function getAllCurriculumLevels(): CurriculumLevel[] {
  return Object.values(EXAM_CURRICULUM);
}
