BEGIN;

-- Cleanup existing content for ingles-c1
DELETE FROM public.course_exercises WHERE lesson_id IN (SELECT id FROM public.course_lessons WHERE module_id = 'ingles-c1');
DELETE FROM public.course_lessons WHERE module_id = 'ingles-c1';
DELETE FROM public.course_modules WHERE id = 'ingles-c1';

INSERT INTO public.course_modules (id, course_level, course_goal, order_index, title)
VALUES ('ingles-c1', 'C1', 'generic', 5, 'English C1 - Advanced')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, course_level = EXCLUDED.course_level;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-unit1', 'ingles-c1', 1, 'Advanced Emphasis and Focus', 60)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B1_I1', 'ingles-c1-unit1', 1, 'transformation', 'Reescribe la frase comenzando con la expresión negativa para dar énfasis (Inversion):', '{"prompt_es":"Reescribe la frase comenzando con la expresión negativa para dar énfasis (Inversion):","stimulus_en":"I have never seen such a beautiful sunset. (NEVER)","correct_answer":"Never have I seen such a beautiful sunset.","explanation":"When we start a sentence with a negative adverb like ''never'', we use question word order (auxiliary before subject).","concept_tags":["grammar","inversion","emphasis"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B1_I2', 'ingles-c1-unit1', 2, 'multiple_choice', 'Selecciona la opción gramaticalmente correcta:', '{"prompt_es":"Selecciona la opción gramaticalmente correcta:","options":[{"id":"o1","text":"Little he knew about the surprise waiting for him."},{"id":"o2","text":"Little did he know about the surprise waiting for him."},{"id":"o3","text":"Little he did know about the surprise waiting for him."}],"correct_answer":"o2","explanation":"''Little'' at the beginning of a sentence requires inversion of the auxiliary ''did''.","concept_tags":["grammar","inversion"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B2_I1', 'ingles-c1-unit1', 3, 'transformation', 'Transforma esta frase en una ''It-cleft'' para enfatizar al sujeto (John):', '{"prompt_es":"Transforma esta frase en una ''It-cleft'' para enfatizar al sujeto (John):","stimulus_en":"John broke the window.","correct_answer":"It was John who broke the window.","explanation":"An ''It-cleft'' structure is ''It + is/was + emphasized part + relative clause''.","concept_tags":["grammar","cleft-sentences","focus"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B2_I2', 'ingles-c1-unit1', 4, 'fill_blanks', 'Completa la ''What-cleft'' para enfatizar la acción:', '{"prompt_es":"Completa la ''What-cleft'' para enfatizar la acción:","stimulus_en":"I need a long holiday. -> ________ I need is a long holiday.","correct_answer":"What","explanation":"A ''What-cleft'' (pseudo-cleft) uses a nominal relative clause to focus on a specific part of the sentence.","concept_tags":["grammar","cleft-sentences"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U2', 'ingles-c1', 2, 'Advanced Inversion', 60)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B1_I1', 'ingles-c1-U2', 1, 'fill_blanks', 'Fill in the blanks with the appropriate words to complete the sentences related to understanding implicit meanings in audio materials.', '{"prompt_es":"Fill in the blanks with the appropriate words to complete the sentences related to understanding implicit meanings in audio materials.","mastery_tag":"listening:c1-complex-audio","main_text":"Listeners must be able to (1)_____ the subtle cues in the speaker''s tone.\n\nInferences drawn from a complex audio can often lead to a deeper (2)_____ of the topic.\n\nThe ability to recognize (3)_____ in speech is crucial for effective communication.\n\nTo fully grasp the message, one must listen without (4)_____ to preconceived notions.\n\nEffective listening requires the ability to (5)_____ between the lines of the conversation.","correct_answer":["interpret","understanding","nuances","bias","read"],"explanation":"(1) La respuesta correcta es ''interpretar'', que se refiere a comprender o deducir algo a partir de pistas sutiles.\n(2) La respuesta correcta es ''comprensión'', que se refiere a la capacidad de captar matices complejos en la información.\n(3) La respuesta correcta es ''matices'', que se refiere a las diferencias sutiles que pueden cambiar el significado.\n(4) La respuesta correcta es ''sesgo'', que indica la necesidad de una mente abierta durante la escucha.\n(5) La respuesta correcta es ''leer'', que en este contexto significa interpretar significados no explícitos."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I1', 'ingles-c1-U2', 2, 'multiple_choice', 'What is considered crucial for effective leadership according to the audio?', '{"prompt_es":"What is considered crucial for effective leadership according to the audio?","mastery_tag":"listening:c1-complex-audio","explanation":"La inteligencia emocional se menciona como fundamental para la conexión con los equipos y la toma de decisiones efectivas.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Technical skills"},{"id":"o2","text":"Emotional intelligence"},{"id":"o3","text":"Experience"},{"id":"o4","text":"Authority"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I2', 'ingles-c1-U2', 3, 'multiple_choice', 'How should leaders adapt their styles according to the context discussed?', '{"prompt_es":"How should leaders adapt their styles according to the context discussed?","mastery_tag":"listening:c1-complex-audio","explanation":"Los líderes deben ser capaces de ajustar su estilo de liderazgo según las necesidades del equipo y el entorno.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Rigidly"},{"id":"o2","text":"Inflexibly"},{"id":"o3","text":"Dynamically"},{"id":"o4","text":"Casually"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I3', 'ingles-c1-U2', 4, 'multiple_choice', 'What impact does ethical decision-making have on a leader’s credibility?', '{"prompt_es":"What impact does ethical decision-making have on a leader’s credibility?","mastery_tag":"listening:c1-complex-audio","explanation":"La toma de decisiones éticas aumenta la credibilidad de un líder en los ojos de sus empleados.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"It diminishes it"},{"id":"o2","text":"It has no impact"},{"id":"o3","text":"It enhances it"},{"id":"o4","text":"It complicates it"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I4', 'ingles-c1-U2', 5, 'multiple_choice', 'Which of the following is implied as a disadvantage of authoritarian leadership?', '{"prompt_es":"Which of the following is implied as a disadvantage of authoritarian leadership?","mastery_tag":"listening:c1-complex-audio","explanation":"Se insinúa que el liderazgo autoritario puede llevar a una baja moral del equipo, ya que no fomenta la participación.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Clear communication"},{"id":"o2","text":"High respect"},{"id":"o3","text":"Low team morale"},{"id":"o4","text":"Fast decision-making"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I5', 'ingles-c1-U2', 6, 'multiple_choice', 'According to the audio, what is a major reason leaders fail?', '{"prompt_es":"According to the audio, what is a major reason leaders fail?","mastery_tag":"listening:c1-complex-audio","explanation":"El audio sugiere que todos estos factores contribuyen al fracaso de los líderes en un entorno corporativo.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Lack of vision"},{"id":"o2","text":"Poor communication skills"},{"id":"o3","text":"Inability to listen"},{"id":"o4","text":"All of the above"}],"correct_answer":"o4"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B3_I1', 'ingles-c1-U2', 7, 'fill_blanks', 'Complete the sentences with the correct words related to public speaking.', '{"prompt_es":"Complete the sentences with the correct words related to public speaking.","mastery_tag":"speaking:c1-public-speaking","main_text":"Effective public speaking requires a clear (1)________ to guide the audience.\n\nUsing (2)________ can enhance your speech and engage your audience emotionally.\n\nTo manage speaking anxiety, practice (3)________ in front of an audience.\n\nA successful presentation often includes (4)________ to illustrate key points.\n\nTo connect with your audience, establish a sense of (5)________ at the beginning of your speech.","correct_answer":["structure","rhetoric","rehearsing","visuals","rapport"],"explanation":"(1) La ''estructura'' es esencial para que la presentación sea clara y fácil de seguir.\n(2) El ''rhetoric'' se refiere a los dispositivos de lenguaje que hacen que una presentación sea más persuasiva.\n(3) ''Rehearsing'' implica practicar tu discurso varias veces antes de la presentación real.\n(4) Los ''visuals'' como gráficos y diapositivas ayudan a clarificar y reforzar la información presentada.\n(5) El ''rapport'' se refiere a la relación de confianza y empatía que construyes con tu audiencia."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U3', 'ingles-c1', 3, 'Unit 3', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I1', 'ingles-c1-U3', 1, 'multiple_choice', 'What is the primary purpose of a thesis statement in an academic essay?', '{"prompt_es":"What is the primary purpose of a thesis statement in an academic essay?","mastery_tag":"writing:c1-academic-writing","explanation":"El propósito principal de una declaración de tesis es presentar la idea central que se argumentará en el ensayo.","stimulus_en":"","options":[{"id":"o1","text":"To summarize the essay"},{"id":"o2","text":"To introduce the topic"},{"id":"o3","text":"To present the main argument"},{"id":"o4","text":"To conclude the essay"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I2', 'ingles-c1-U3', 2, 'multiple_choice', 'Choose the correct answer for each question related to academic writing.', '{"prompt_es":"Choose the correct answer for each question related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"El lenguaje formal aporta credibilidad a la escritura académica, lo que es esencial en contextos académicos.","stimulus_en":"In academic writing, formal language is preferred over informal language because it...","options":[{"id":"o1","text":"is more entertaining"},{"id":"o2","text":"is easier to understand"},{"id":"o3","text":"adds credibility"},{"id":"o4","text":"is more concise"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I3', 'ingles-c1-U3', 3, 'multiple_choice', 'Which of the following is NOT a typical component of an academic report?', '{"prompt_es":"Which of the following is NOT a typical component of an academic report?","mastery_tag":"writing:c1-academic-writing","explanation":"Las opiniones personales no son componentes típicos de un informe académico ya que se basa en la evidencia y la investigación objetiva.","stimulus_en":"","options":[{"id":"o1","text":"Introduction"},{"id":"o2","text":"Methodology"},{"id":"o3","text":"Personal opinion"},{"id":"o4","text":"Conclusion"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I4', 'ingles-c1-U3', 4, 'multiple_choice', 'What is the use of citations in academic writing?', '{"prompt_es":"What is the use of citations in academic writing?","mastery_tag":"writing:c1-academic-writing","explanation":"Las citas se utilizan para respaldar afirmaciones con evidencia y para dar crédito a las fuentes originales.","stimulus_en":"","options":[{"id":"o1","text":"To provide personal experiences"},{"id":"o2","text":"To support claims with evidence"},{"id":"o3","text":"To make the text longer"},{"id":"o4","text":"To express personal views"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I5', 'ingles-c1-U3', 5, 'multiple_choice', 'Why is it important to have a clear structure in an academic essay?', '{"prompt_es":"Why is it important to have a clear structure in an academic essay?","mastery_tag":"writing:c1-academic-writing","explanation":"Una estructura clara facilita la comprensión del argumento y la lógica del ensayo, lo cual es crucial en la escritura académica.","stimulus_en":"","options":[{"id":"o1","text":"It makes it more interesting"},{"id":"o2","text":"It helps the reader understand the argument"},{"id":"o3","text":"It allows for more personal expression"},{"id":"o4","text":"It can increase word count"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B2_I1', 'ingles-c1-U3', 6, 'fill_blanks', 'Fill in the blanks with the correct words to complete the sentences about proposals and evaluations.', '{"prompt_es":"Fill in the blanks with the correct words to complete the sentences about proposals and evaluations.","mastery_tag":"writing:c1-proposals","main_text":"1. When writing a proposal, it is essential to clearly define the (1)___ of the project, outlining its objectives and expected outcomes.\n2. A strong proposal often includes a detailed budget that justifies the (2)___ necessary to achieve the proposed goals.\n3. Evaluations should provide (3)___ feedback that highlights both strengths and weaknesses in the implementation of the project.\n4. It is advisable to use relevant data to support your (4)___, making your argument more persuasive.\n5. A well-crafted executive summary can significantly enhance a proposal by providing a concise (5)___ of the entire document.","correct_answer":["scope","resources","constructive","arguments","overview"],"explanation":"(1) La ''scope'' se refiere al alcance del proyecto, que es fundamental al redactar una propuesta.\n(2) Los ''resources'' son los recursos necesarios y deben estar claramente justificados en una propuesta sólida.\n(3) El feedback ''constructive'' es crucial para que las evaluaciones sean efectivas, ayudando a mejorar en el futuro.\n(4) Los ''arguments'' son fundamentales para una propuesta convincente, respaldados por datos relevantes.\n(5) Un ''overview'' es un resumen que permite comprender rápidamente el contenido del documento completo."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B3_I1', 'ingles-c1-U3', 7, 'word_formation', 'Complete the sentences by transforming the base words into the correct forms.', '{"prompt_es":"Complete the sentences by transforming the base words into the correct forms.","mastery_tag":"vocabulary:c1-academic","main_text":"In academic writing, it is essential to maintain a high level of professionalism and (1)___ (ACCURATE) while presenting your findings. A thorough (2)___ (ANALYZE) of the data can lead to significant (3)___ (IMPROVE) in your research quality. Many scholars argue that a strong theoretical (4)___ (FOUND) is necessary for any (5)___ (DISCUSS) in the field.","correct_answer":["ACCURACY","ANALYSIS","IMPROVEMENTS","FOUNDATION","DISCUSSION"],"example":"ACCURATE, ANALYZE, IMPROVE, FOUND, DISCUSS","explanation":"(1) La palabra ''exactitud'' es el sustantivo que se forma a partir del adjetivo ''preciso''.\n(2) Aquí, ''análisis'' es el sustantivo correspondiente al verbo ''analizar''.\n(3) Se necesita el sustantivo plural ''mejoras'', derivado del verbo ''mejorar''.\n(4) El sustantivo ''fundación'' se forma a partir del verbo ''fundar''.\n(5) Aquí, ''discusión'' es el sustantivo relacionado con el verbo ''discutir''."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U4', 'ingles-c1', 4, 'Unit 4', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B1_I1', 'ingles-c1-U4', 1, 'word_formation', 'Fill in the blanks with the correct form of the word provided.', '{"prompt_es":"Fill in the blanks with the correct form of the word provided.","mastery_tag":"vocabulary:c1-academic","main_text":"The (1)___ of the study showed significant results. The researchers conducted a thorough (2)___ to support their (3)___ about the effects of climate change. This (4)___ helps to understand the complex relationships in environmental science. Future (5)___ will focus on expanding this research.","correct_answer":["ANALYSIS","INVESTIGATION","THEORY","CONTRIBUTION","STUDIES"],"example":"ANALYZE, INVESTIGATE, THEORIZE, CONTRIBUTE, STUDY","explanation":"(1) undefined\n(2) undefined\n(3) undefined\n(4) undefined\n(5) undefined"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B2_I1', 'ingles-c1-U4', 2, 'word_formation', 'Fill in the gaps with the correct form of the word provided in parentheses.', '{"prompt_es":"Fill in the gaps with the correct form of the word provided in parentheses.","mastery_tag":"vocabulary:c1-nuanced","main_text":"Effective communication often requires a deep understanding of (1)___ (NUANCE) in language. To express (2)___ (PRECISE) thoughts, one must choose words with care. A word’s (3)___ (CONNOTATE) can change its meaning entirely, making it essential to grasp subtleties. Moreover, (4)___ (SOPHISTICATE) language can enhance the (5)___ (EFFECT) of a message when used appropriately.","correct_answer":["NUANCES","PRECISION","CONNOTATION","SOPHISTICATION","EFFECTIVENESS"],"example":"NUANCE, PRECISE, CONNOTATE, SOPHISTICATE, EFFECT","explanation":"(1) undefined\n(2) undefined\n(3) undefined\n(4) undefined\n(5) undefined"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I1', 'ingles-c1-U4', 3, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Es importante que las conversaciones tengan un flujo natural para involucrar al oyente.","stimulus_en":"It''s important to maintain a sense of ___ during conversations to engage your listener.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"flow"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I2', 'ingles-c1-U4', 4, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Usar expresiones idiomáticas y coloquialismos hace que suene más natural.","stimulus_en":"To sound more ___, try using idiomatic expressions and colloquialisms.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"natural"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I3', 'ingles-c1-U4', 5, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"El feedback verbal ayuda a mostrar que estás atento y comprometido en la conversación.","stimulus_en":"Active listening involves providing ___ feedback to your conversation partner.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"verbal"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I4', 'ingles-c1-U4', 6, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Los gestos apropiados ayudan a ilustrar tus puntos y mantener la atención del oyente.","stimulus_en":"Using appropriate ___ can help clarify your points and maintain engagement.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"gestures"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I5', 'ingles-c1-U4', 7, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Una pausa puede ser útil para que pienses en lo que quieres decir a continuación.","stimulus_en":"A pause in conversation can be a powerful ___ to reflect on your thoughts.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"tool"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U5', 'ingles-c1', 5, 'Unit 5', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I1', 'ingles-c1-U5', 1, 'multiple_choice', 'What does ''to walk on eggshells'' mean?', '{"prompt_es":"What does ''to walk on eggshells'' mean?","mastery_tag":"vocabulary:c1-nuanced","explanation":"La expresión significa ser muy cuidadoso en una situación delicada.","stimulus_en":"","options":[{"id":"o1","text":"To be careful"},{"id":"o2","text":"To change direction"},{"id":"o3","text":"To act quickly"},{"id":"o4","text":"To be energetic"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I2', 'ingles-c1-U5', 2, 'multiple_choice', 'What does ''the elephant in the room'' refer to?', '{"prompt_es":"What does ''the elephant in the room'' refer to?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Se refiere a un problema obvio que todos evitan discutir.","stimulus_en":"","options":[{"id":"o1","text":"A big distraction"},{"id":"o2","text":"An obvious problem"},{"id":"o3","text":"A surprising idea"},{"id":"o4","text":"A heavy topic"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I3', 'ingles-c1-U5', 3, 'multiple_choice', 'What does ''to throw someone under the bus'' imply?', '{"prompt_es":"What does ''to throw someone under the bus'' imply?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Significa traicionar a alguien, generalmente para salvarse a sí mismo.","stimulus_en":"","options":[{"id":"o1","text":"To help someone"},{"id":"o2","text":"To betray someone"},{"id":"o3","text":"To support someone"},{"id":"o4","text":"To confuse someone"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I4', 'ingles-c1-U5', 4, 'multiple_choice', 'What does ''to read between the lines'' suggest?', '{"prompt_es":"What does ''to read between the lines'' suggest?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Se refiere a captar significados que no son explícitos.","stimulus_en":"","options":[{"id":"o1","text":"To read carefully"},{"id":"o2","text":"To understand the hidden meaning"},{"id":"o3","text":"To read fast"},{"id":"o4","text":"To ignore details"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I5', 'ingles-c1-U5', 5, 'multiple_choice', 'What does ''to beat around the bush'' mean?', '{"prompt_es":"What does ''to beat around the bush'' mean?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Implica no abordar el tema principal de manera directa.","stimulus_en":"","options":[{"id":"o1","text":"To be direct"},{"id":"o2","text":"To avoid getting to the point"},{"id":"o3","text":"To speak quickly"},{"id":"o4","text":"To explain clearly"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B2_I1', 'ingles-c1-U5', 6, 'word_formation', 'Complete the sentences by forming the correct word from the base provided.', '{"prompt_es":"Complete the sentences by forming the correct word from the base provided.","mastery_tag":"vocabulary:c1-culture-arts","main_text":"The study of culture and the arts encompasses various fields, each rich in (1)___ (SIGNIFY). Understanding the significance of (2)___ (CRITIC) is essential for appreciating art. The (3)___ (EXPRESS) of emotions through different mediums can lead to profound experiences. (4)___ (INFLUENCE) from historical context often shapes artistic movements. Finally, the (5)___ (CREATE) process is at the heart of artistic innovation.","correct_answer":["SIGNIFICANCE","CRITICISM","EXPRESSION","INFLUENCES","CREATIVE"],"example":"SIGNIFY, CRITIC, EXPRESS, INFLUENCE, CREATE","explanation":"(1) La palabra ''significance'' se refiere a la importancia o el significado de algo, especialmente en el contexto de la cultura.\n(2) El término ''criticism'' se utiliza para hablar de la evaluación o juicio de una obra de arte.\n(3) La palabra ''expression'' se refiere a la manifestación de emociones o ideas a través del arte.\n(4) La forma plural ''influences'' se refiere a los diversos factores que afectan el desarrollo artístico.\n(5) El término ''creative'' describe la capacidad de generar nuevas ideas o conceptos, esencial en el arte."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B3_I1', 'ingles-c1-U5', 7, 'fill_blanks', 'Complete the sentences with the most appropriate word or phrase.', '{"prompt_es":"Complete the sentences with the most appropriate word or phrase.","mastery_tag":"speaking:c1-fluent-interaction","main_text":"In conversations, it is essential to express ideas clearly and (1)___. Good communication involves not just speaking, but also (2)___. When engaging in dialogue, be attentive to the other person''s (3)___ and adjust your responses accordingly. Spontaneous reactions often add (4)___ to discussions, making them more engaging. In a fluent interaction, both parties should feel (5)___ to share their opinions openly.","correct_answer":["coherently","listening","body language","dynamism","comfortable"],"explanation":"(1) Es importante que las ideas se expresen de manera clara y coherente para una buena comunicación.\n(2) La buena comunicación no se trata solo de hablar, sino también de escuchar a los demás.\n(3) El lenguaje corporal de la otra persona puede ayudar a entender mejor la conversación.\n(4) Las reacciones espontáneas pueden dar energía y dinamismo a las discusiones.\n(5) Es fundamental que ambas partes se sientan cómodas para poder intercambiar opiniones."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

COMMIT;