/**
 * Unidad 29 — Lección 4: Comprensión auditiva (Clothes)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Clothes';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[What|Qué]] [[are|estás]] [[you|tú]] [[wearing|llevando]] [[today|hoy]]? [[B|B]]: [[I|Yo]] [[am|estoy]] [[wearing|llevando]] [[a|una]] [[white|blanca]] [[shirt|camisa]] [[and|y]] [[blue|azules]] [[trousers|pantalones]]. [[A|A]]: [[Nice|Bien]]. [[Is|Está]] [[your|tu]] [[sister|hermana]] [[wearing|llevando]] [[a|un]] [[dress|vestido]]? [[B|B]]: [[Yes|Sí]], [[she|ella]] [[is|está]] [[wearing|llevando]] [[a|un]] [[red|rojo]] [[dress|vestido]] [[and|y]] [[black|negros]] [[shoes|zapatos]]. [[A|A]]: [[What|Qué]] [[about|]] [[your|tu]] [[brother|hermano]]? [[B|B]]: [[He|Él]] [[is|está]] [[wearing|llevando]] [[a|una]] [[jacket|chaqueta]] [[and|y]] [[a|un]] [[hat|sombrero]]. [[He|Él]] [[is|está]] [[wearing|llevando]] [[brown|marrones]] [[shoes|zapatos]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_29_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u29-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[B|B]] [[wearing|llevando]]?', options: ['[[A white shirt and blue trousers|Una camisa blanca y pantalones azules]]', '[[A red dress|Un vestido rojo]]', '[[A jacket|Una chaqueta]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is|Está]] [[B\'s|la hermana de B]] [[sister|hermana]] [[wearing|llevando]] [[a|un]] [[dress|vestido]]?', options: ['[[Yes, a red dress|Sí, un vestido rojo]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[colour|color]] [[are|son]] [[the|los]] [[sister\'s|zapatos de la hermana]] [[shoes|zapatos]]?', options: ['[[Black|Negros]]', '[[White|Blancos]]', '[[Brown|Marrones]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[the|el]] [[brother|hermano]] [[wearing|llevando]]?', options: ['[[A jacket and a hat|Una chaqueta y un sombrero]]', '[[A dress|Un vestido]]', '[[A shirt only|Solo una camisa]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[colour|color]] [[are|son]] [[the|los]] [[brother\'s|zapatos del hermano]] [[shoes|zapatos]]?', options: ['[[Brown|Marrones]]', '[[Black|Negros]]', '[[Blue|Azules]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|pregunta]] [[A|A]] [[ask|pregunta]] [[first|primero]]?', options: ['[[What are you wearing today?|¿Qué llevas hoy?]]', '[[Where is your sister?|¿Dónde está tu hermana?]]', '[[What colour is the jacket?|¿De qué color es la chaqueta?]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[tense|tiempo]] [[do|usa]] [[they|ellos]] [[use|usan]] [[for|para]] [[clothes|ropa]]?', options: ['[[Present Continuous (am/is/are wearing)|Present Continuous]]', '[[Present Simple|Present Simple]]', '[[Past|Pasado]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[says|dice]] [[I|yo]] ____ [[wearing|llevando]] [[a|una]] [[white|blanca]] [[shirt|camisa]].', options: ['[[am|estoy]]', '[[is|está]]', '[[are|están]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[dialogue|diálogo]] [[is|es]] ____.', options: ['[[about what people are wearing|sobre qué llevan puesto]]', '[[about food|sobre comida]]', '[[about animals|sobre animales]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[vestido|vestido]]"?', options: ['[[Dress|Dress]]', '[[Shirt|Shirt]]', '[[Jacket|Jacket]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[wearing|llevando]] [[a|un]] [[red|rojo]] [[dress|vestido]].', options: ['[[is|está]]', '[[am|estoy]]', '[[are|están]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[wearing|llevando]] [[a|una]] [[jacket|chaqueta]].', options: ['[[is|está]]', '[[are|están]]', '[[am|estoy]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B\'s|Los pantalones de B]] [[trousers|pantalones]] [[are|son]] ____.', options: ['[[blue|azules]]', '[[white|blancos]]', '[[black|negros]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[brother|hermano]] [[is|está]] [[wearing|llevando]] ____ [[and|y]] [[a|un]] [[hat|sombrero]].', options: ['[[a jacket|una chaqueta]]', '[[a dress|un vestido]]', '[[a shirt|una camisa]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u29-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Wearing|Wearing]] [[means|significa]] ____.', options: ['[[llevar puesto|wearing]]', '[[comprar|to buy]]', '[[lavar|to wash]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
