/**
 * Unidad 45 — Lección 3: Comprensión lectora (Seasons)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Seasons';
const READING_TRANSCRIPT = `[[I|Yo]] [[love|me encanta]] [[all|todas]] [[the|las]] [[four|cuatro]] [[seasons|estaciones]]. [[In|En]] [[spring|primavera]] [[the|las]] [[flowers|flores]] [[bloom|florecen]] [[and|y]] [[the|la]] [[weather|tiempo]] [[is|está]] [[warm|cálido]]. [[In|En]] [[summer|verano]] [[it is|está]] [[hot|caluroso]] [[and|y]] [[sunny|soleado]]; [[I|yo]] [[go|voy]] [[to|a]] [[the|la]] [[beach|playa]]. [[In|En]] [[autumn|otoño]] [[the|las]] [[leaves|hojas]] [[fall|caen]] [[and|y]] [[the|los]] [[trees|árboles]] [[are|están]] [[orange|naranjas]] [[and|y]] [[yellow|amarillos]]. [[In|En]] [[winter|invierno]] [[it is|está]] [[cold|frío]] [[and|y]] [[sometimes|a veces]] [[it is|está]] [[snowing|nevando]]. [[I|Yo]] [[like|me gusta]] [[nature|naturaleza]] [[in|en]] [[every|cada]] [[season|estación]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_45_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u45-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How many|Cuántas]] [[seasons|estaciones]] [[does the writer love|ama el autor]]?', options: ['[[All four|Las cuatro]]', '[[One|Una]]', '[[Two|Dos]]'], correctAnswer: 0, explanation: 'I love all the four seasons.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[happens|pasa]] [[in spring|en primavera]]?', options: ['[[Flowers bloom, weather is warm|Florecen las flores, hace buen tiempo]]', '[[It snows|Nieva]]', '[[Leaves fall|Caen las hojas]]'], correctAnswer: 0, explanation: 'In spring the flowers bloom and the weather is warm.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[does he/she go|va]] [[in summer|en verano]]?', options: ['[[To the beach|A la playa]]', '[[To the mountains|A la montaña]]', '[[To school|Al colegio]]'], correctAnswer: 0, explanation: 'In summer I go to the beach.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[happens|pasa]] [[in autumn|en otoño]]?', options: ['[[Leaves fall, trees are orange and yellow|Caen las hojas, árboles naranjas y amarillos]]', '[[Flowers bloom|Florecen las flores]]', '[[It snows|Nieva]]'], correctAnswer: 0, explanation: 'In autumn the leaves fall and the trees are orange and yellow.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is the weather|es el tiempo]] [[in winter|en invierno]]?', options: ['[[Cold and sometimes snowy|Frío y a veces nevado]]', '[[Hot|Caluroso]]', '[[Warm|Cálido]]'], correctAnswer: 0, explanation: 'In winter it is cold and sometimes it is snowing.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does the writer like|le gusta al autor]] [[in every season|en cada estación]]?', options: ['[[Nature|La naturaleza]]', '[[The beach|La playa]]', '[[Snow|La nieve]]'], correctAnswer: 0, explanation: 'I like nature in every season.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In summer|En verano]] [[it is|está]] ____.', options: ['[[hot and sunny|caluroso y soleado]]', '[[cold|frío]]', '[[snowy|nevado]]'], correctAnswer: 0, explanation: 'In summer it is hot and sunny.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In spring|En primavera]] = ____.', options: ['[[flowers bloom|florecen las flores]]', '[[snow|nieve]]', '[[leaves fall|caen las hojas]]'], correctAnswer: 0, explanation: 'In spring the flowers bloom.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Autumn|Otoño]] = ____.', options: ['[[leaves fall|caen las hojas]]', '[[flowers bloom|florecen las flores]]', '[[snow|nieve]]'], correctAnswer: 0, explanation: 'Autumn: leaves fall.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Winter|Invierno]] = ____.', options: ['[[cold, snow|frío, nieve]]', '[[hot|calor]]', '[[flowers|flores]]'], correctAnswer: 0, explanation: 'Winter: cold, snow.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[the four seasons and nature|las cuatro estaciones y la naturaleza]]', '[[food|comida]]', '[[transport|transporte]]'], correctAnswer: 0, explanation: 'Seasons: spring, summer, autumn, winter; nature.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Nature|Naturaleza]] = ____.', options: ['[[trees, flowers, animals, not made by people|árboles, flores, animales]]', '[[cars|coches]]', '[[buildings|edificios]]'], correctAnswer: 0, explanation: 'Nature = naturaleza.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We use|Usamos]] ____ [[before|antes de]] [[seasons|estaciones]].', options: ['[[in|in]]', '[[on|on]]', '[[at|at]]'], correctAnswer: 0, explanation: 'In spring, in summer.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Summer|Verano]] = ____.', options: ['[[hot season|estación calurosa]]', '[[cold season|estación fría]]', '[[leaves fall|caen las hojas]]'], correctAnswer: 0, explanation: 'Summer = verano, hot.' }] }, topicName: 'Reading' },
  { id: 'a1-u45-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is the main topic|es el tema principal]]?', options: ['[[Seasons and nature|Estaciones y naturaleza]]', '[[Weather only|Solo tiempo]]', '[[Travel|Viajes]]'], correctAnswer: 0, explanation: 'Four seasons, nature in every season.' }] }, topicName: 'Reading' },
];
