/**
 * Unidad 45 — Lección 1: Gramática (Seasons)
 * Preposition in with seasons (in summer).
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Preposición in con estaciones';
const TOPIC = 'Seasons';

export const UNIT_45_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u45-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[like|me gusta]] [[the|el]] [[flowers|flores]] ____ [[spring|primavera]].', options: ['[[in|en]]', '[[on|en]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It is|Está]] [[hot|caluroso]] ____ [[summer|verano]].', options: ['[[in|en]]', '[[on|en]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|Las]] [[leaves|hojas]] [[fall|caen]] ____ [[autumn|otoño]].', options: ['[[in|en]]', '[[on|en]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It is|Está]] [[cold|frío]] ____ [[winter|invierno]].', options: ['[[in|en]]', '[[on|en]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] [[go|vamos]] [[on|de]] [[holiday|vacaciones]] ____ [[summer|verano]].', options: ['[[in|en]]', '[[on|en]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[With seasons|Con estaciones]] [[we use|usamos]] ____.', options: ['[[in (in summer, in winter)|in]]', '[[on (on summer)|incorrecto]]', '[[at (at winter)|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Correct|Correcto]]: ____.', options: ['[[in spring|en primavera]]', '[[on spring|incorrecto]]', '[[at spring|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[In autumn|En otoño]] = ____.', options: ['[[during autumn|durante el otoño]]', '[[on top of autumn|encima del otoño]]', '[[at autumn|a otoño]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[The four seasons|Las cuatro estaciones]] [[are|son]] ____.', options: ['[[spring, summer, autumn, winter|primavera, verano, otoño, invierno]]', '[[Monday, Tuesday...|lunes, martes...]]', '[[January, February...|enero, febrero...]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We say|Decimos]] ____ [[before the season|antes de la estación]].', options: ['[[in|in]]', '[[on|on]]', '[[at|at]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It is|Está]] [[hot|caluroso]] [[in|en]] [[summer|verano]].', words: ['[[It is|Está]]', '[[hot|caluroso]]', '[[in|en]]', '[[summer|verano]].'] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[The|Las]] [[flowers|flores]] [[bloom|florecen]] [[in|en]] [[spring|primavera]].', words: ['[[The|Las]]', '[[flowers|flores]]', '[[bloom|florecen]]', '[[in|en]]', '[[spring|primavera]].'] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It is|Está]] [[cold|frío]] [[in|en]] [[winter|invierno]].', words: ['[[It is|Está]]', '[[cold|frío]]', '[[in|en]]', '[[winter|invierno]].'] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We use|Usamos]] [[in|in]] [[with|con]] [[seasons|estaciones]]: [[in spring|in spring]], [[in summer|in summer]], [[in autumn|in autumn]], [[in winter|in winter]].', correctAnswer: true, explanation: 'In + season.' }] }, topicName: 'Grammar' },
  { id: 'a1-u45-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We do not say|No decimos]] [[on summer|on summer]] [[or|o]] [[at winter|at winter]]; [[we say|decimos]] [[in summer|in summer]], [[in winter|in winter]].', correctAnswer: true, explanation: 'Only in + season.' }] }, topicName: 'Grammar' },
];
