/**
 * Unidad 44 — Lección 1: Gramática (The Weather)
 * It is + weather adjective (It is sunny, It is raining).
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'It is + adjetivo de tiempo';
const TOPIC = 'The Weather';

export const UNIT_44_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u44-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|(El tiempo)]] ____ [[sunny|soleado]] [[today|hoy]].', options: ['[[is|está]]', '[[are|están]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|(El tiempo)]] ____ [[raining|lloviendo]] [[now|ahora]].', options: ['[[is|está]]', '[[are|están]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|(El tiempo)]] ____ [[cloudy|nublado]] [[this|esta]] [[morning|mañana]].', options: ['[[is|está]]', '[[are|están]]', '[[am|estoy]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|(El tiempo)]] ____ [[snowing|nevando]] [[in|en]] [[winter|invierno]].', options: ['[[is|está]]', '[[are|están]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|(El tiempo)]] ____ [[hot|caluroso]] [[in|en]] [[summer|verano]].', options: ['[[is|está]]', '[[are|están]]', '[[am|estoy]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[For weather|Para el tiempo]] [[we use|usamos]] ____.', options: ['[[It is + adjective (It is sunny)|It is + adjetivo]]', '[[I is|incorrecto]]', '[[They is|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[It is raining|Está lloviendo]] = ____.', options: ['[[weather: rain now|tiempo: llueve ahora]]', '[[I am raining|incorrecto]]', '[[sunny|soleado]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Correct|Correcto]]: ____.', options: ['[[It is cold|Hace frío / Está frío]]', '[[It are cold|incorrecto]]', '[[They is cold|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[It is sunny|Está soleado]] = ____.', options: ['[[the sun is shining|el sol brilla]]', '[[it is raining|está lloviendo]]', '[[it is snowing|está nevando]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[It is snowing|Está nevando]] = ____.', options: ['[[snow falls|nieva]]', '[[rain falls|llueve]]', '[[sun shines|brilla el sol]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It|(El tiempo)]] [[is|está]] [[sunny|soleado]] [[today|hoy]].', words: ['[[It|(El tiempo)]]', '[[is|está]]', '[[sunny|soleado]]', '[[today|hoy]].'] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It|(El tiempo)]] [[is|está]] [[raining|lloviendo]] [[now|ahora]].', words: ['[[It|(El tiempo)]]', '[[is|está]]', '[[raining|lloviendo]]', '[[now|ahora]].'] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It|(El tiempo)]] [[is|está]] [[cold|frío]] [[in|en]] [[winter|invierno]].', words: ['[[It|(El tiempo)]]', '[[is|está]]', '[[cold|frío]]', '[[in|en]]', '[[winter|invierno]].'] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We say|Decimos]] [[It is sunny|It is sunny]], [[It is raining|It is raining]], [[not|no]] [[I is|I is]] [[or|o]] [[They is|They is]].', correctAnswer: true, explanation: 'Weather: always It is.' }] }, topicName: 'Grammar' },
  { id: 'a1-u44-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[It is hot|It is hot]] [[means|significa]] [[the temperature is high|la temperatura es alta]].', correctAnswer: true, explanation: 'Hot = caluroso.' }] }, topicName: 'Grammar' },
];
