/**
 * Unidad 19 — Lección 6: Expresión escrita (Months & Dates)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Months & Dates';

export const UNIT_19_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u19-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[My|Mi]] [[birthday|cumpleaños]] [[is|es]] ____ [[January|enero]].', options: ['[[in|en]]', '[[on|el]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It\'s|Es]] ____ [[the|el]] [[5th|5]] [[of|de]] [[April|abril]].', options: ['[[on|el]]', '[[in|en]]', '[[at|a]]'], correctAnswer: 'on', acceptableAnswers: ['on'] }] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '____ [[is|es]] [[your|tu]] [[birthday|cumpleaños]]?', options: ['[[When|Cuándo]]', '[[What|Qué]]', '[[Where|Dónde]]'], correctAnswer: 'When', acceptableAnswers: ['When'] }] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[was born|nací]] ____ [[the|el]] [[12th|12]] [[of|de]] [[June|junio]].', options: ['[[on|el]]', '[[in|en]]', '[[at|a]]'], correctAnswer: 'on', acceptableAnswers: ['on'] }] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Christmas|Navidad]] [[is|es]] ____ [[December|diciembre]].', options: ['[[in|en]]', '[[on|el]]', '[[at|a]]'], correctAnswer: 'in', acceptableAnswers: ['in'] }] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[When|Cuándo]] [[is|es]] [[your|tu]] [[birthday|cumpleaños]]?', words: ['[[When|Cuándo]]', '[[is|es]]', '[[your|tu]]', '[[birthday|cumpleaños]]?'] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[My|Mi]] [[birthday|cumpleaños]] [[is|es]] [[on|el]] [[the|el]] [[10th|10]] [[of|de]] [[May|mayo]].', words: ['[[My|Mi]]', '[[birthday|cumpleaños]]', '[[is|es]]', '[[on|el]]', '[[the|el]]', '[[10th|10]]', '[[of|de]]', '[[May|mayo]].'] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[was born|nací]] [[in|en]] [[February|febrero]].', words: ['[[I|Yo]]', '[[was born|nací]]', '[[in|en]]', '[[February|febrero]].'] }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe cuándo es tu cumpleaños (fecha y mes).', prompt: '____.', minWords: 5, maxWords: 15, modelExample: 'My birthday is on the 10th of May.' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: When is your birthday? y tu respuesta.', prompt: '____? ____.', minWords: 6, maxWords: 18, modelExample: 'When is your birthday? My birthday is on the 22nd of June.' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe tres fechas importantes: una con in (mes) y dos con on (fecha).', prompt: '____. ____. ____.', minWords: 12, maxWords: 30, modelExample: 'Christmas is in December. My birthday is on the 5th of April. The meeting is on the 20th of March.' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la frase: Mi cumpleaños es el 3 de julio.', prompt: '____.', minWords: 6, maxWords: 12, modelExample: 'My birthday is on the 3rd of July.' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4 frases): tu cumpleaños, el de un familiar o amigo, y una fiesta en un mes.', prompt: '____.', minWords: 25, maxWords: 50, modelExample: 'My birthday is on the 15th of March. My brother\'s birthday is in July. We have a party in August. Christmas is in December.' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe los ordinales: 1st, 2nd, 3rd, 21st en palabras.', prompt: '____.', minWords: 4, maxWords: 12, modelExample: 'first, second, third, twenty-first' }, topicName: 'Writing' },
  { id: 'a1-u19-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: Navidad es en diciembre. Año Nuevo es el 1 de enero.', prompt: '____. ____.', minWords: 10, maxWords: 20, modelExample: 'Christmas is in December. New Year is on the 1st of January.' }, topicName: 'Writing' },
];
