/**
 * Unidad 35 — Lección 1: Gramática (Free Time Activities)
 * go for a walk, go shopping; watching TV, video games, walking.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Actividades de tiempo libre';
const TOPIC = 'Free Time Activities';

export const UNIT_35_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u35-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. "Ir a pasear" es ____.', questions: [{ question: '[[I|Yo]] ____ [[for a walk|de paseo]] [[every|cada]] [[evening|tarde]].', options: ['[[go|voy]]', '[[goes|va]]', '[[going|yendo]]'], correctAnswer: 'go', acceptableAnswers: ['go'], explanation: 'Go for a walk.' }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] ____ [[shopping|de compras]] [[on|los]] [[Saturdays|sábados]].', options: ['[[goes|va]]', '[[go|ir]]', '[[going|yendo]]'], correctAnswer: 'goes', acceptableAnswers: ['goes'] }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Con like usamos -ing para actividades.', questions: [{ question: '[[I|Yo]] [[like|me gusta]] ____ [[TV|la tele]].', options: ['[[watching|ver]]', '[[watch|ver]]', '[[watches|ve]]'], correctAnswer: 'watching', acceptableAnswers: ['watching'] }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] [[likes|le gusta]] ____ [[video games|videojuegos]].', options: ['[[playing|jugar a]]', '[[play|jugar]]', '[[plays|juega]]'], correctAnswer: 'playing', acceptableAnswers: ['playing'] }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] [[enjoy|disfrutamos]] ____ [[in the park|en el parque]].', options: ['[[walking|pasear]]', '[[walk|pasear]]', '[[walks|pasea]]'], correctAnswer: 'walking', acceptableAnswers: ['walking'] }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Go for a walk|Ir de paseo]] = ____.', options: ['[[go + for a walk|go + for a walk]]', '[[go + walk|go + walk]]', '[[going + walk|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[After|Después de]] [[like/enjoy|like/enjoy]] [[we use|usamos]] ____.', options: ['[[verb + -ing|verbo + -ing]]', '[[base verb|verbo base]]', '[[to + verb|to + verbo]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Go shopping|Ir de compras]] = ____.', options: ['[[go + shopping|go + shopping]]', '[[go + shop|go + shop]]', '[[going + shop|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[I like ____ TV.|I like ____ TV.]]', options: ['[[watching|watching]]', '[[watch|watch]]', '[[watches|watches]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[She|Ella]] ____ [[for a walk|de paseo]] [[every day|cada día]].', options: ['[[goes|va]]', '[[go|ir]]', '[[going|yendo]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[go|voy]] [[for a walk|de paseo]] [[every|cada]] [[evening|tarde]].', words: ['[[I|Yo]]', '[[go|voy]]', '[[for a walk|de paseo]]', '[[every|cada]]', '[[evening|tarde]].'] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[likes|le gusta]] [[watching|ver]] [[TV|la tele]].', words: ['[[She|Ella]]', '[[likes|le gusta]]', '[[watching|ver]]', '[[TV|la tele]].'] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[We|Nosotros]] [[go|vamos]] [[shopping|de compras]] [[at weekends|los fines de semana]].', words: ['[[We|Nosotros]]', '[[go|vamos]]', '[[shopping|de compras]]', '[[at weekends|los fines de semana]].'] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Like + -ing|Like + -ing]]: [[I like watching TV|I like watching TV]], [[I like playing video games|I like playing video games]].', correctAnswer: true }] }, topicName: 'Grammar' },
  { id: 'a1-u35-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Go for a walk|Go for a walk]] [[and|y]] [[go shopping|go shopping]] [[use|usan]] [[go + phrase|go + frase]].', correctAnswer: true }] }, topicName: 'Grammar' },
];
