/**
 * Unidad 37 — Lección 2: Vocabulario (Talent & Skills)
 * creative, hardworking, fast, etc.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Vocabulario: talentos y habilidades';
const TOPIC = 'Talent & Skills';

export const UNIT_37_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u37-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Creative|Creativo]] = ____.', options: ['[[has new ideas|tiene ideas nuevas]]', '[[works a lot|trabaja mucho]]', '[[is quick|es rápido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Hardworking|Trabajador]] = ____.', options: ['[[works a lot|trabaja mucho]]', '[[is slow|es lento]]', '[[is creative|es creativo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Fast|Rápido]] = ____.', options: ['[[quick|rápido]]', '[[slow|lento]]', '[[creative|creativo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Skill|Habilidad]] = ____.', options: ['[[something you can do well|algo que sabes hacer bien]]', '[[a sport|un deporte]]', '[[a job|un trabajo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Talent|Talento]] = ____.', options: ['[[natural ability|capacidad natural]]', '[[work|trabajo]]', '[[luck|suerte]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[very well|muy bien]]', right: '[[high level|nivel alto]]' }, { id: 'p2', left: '[[quite well|bastante bien]]', right: '[[medium level|nivel medio]]' }, { id: 'p3', left: '[[not at all|nada]]', right: '[[no ability|sin habilidad]]' }, { id: 'p4', left: '[[creative|creativo]]', right: '[[new ideas|ideas nuevas]]' }, { id: 'p5', left: '[[hardworking|trabajador]]', right: '[[works hard|trabaja duro]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona verbo con habilidad.', pairs: [{ id: 'p1', left: '[[sing|cantar]]', right: '[[music|música]]' }, { id: 'p2', left: '[[draw|dibujar]]', right: '[[art|arte]]' }, { id: 'p3', left: '[[cook|cocinar]]', right: '[[food|comida]]' }, { id: 'p4', left: '[[drive|conducir]]', right: '[[car|coche]]' }, { id: 'p5', left: '[[swim|nadar]]', right: '[[water|agua]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[is|es]] ____ — [[she|ella]] [[paints|pinta]] [[beautifully|muy bien]].', options: ['[[creative|creativa]]', '[[fast|rápida]]', '[[slow|lenta]]'], correctAnswer: 'creative', acceptableAnswers: ['creative'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] [[works|trabaja]] ____ [[(hard)|(duro)]].', options: ['[[hard|duro]]', '[[fast|rápido]]', '[[well|bien]]'], correctAnswer: 'hard', acceptableAnswers: ['hard'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[can\'t|no puedo]] ____ [[at all|nada]].', options: ['[[dance|bailar]]', '[[dances|baila]]', '[[dancing|bailando]]'], correctAnswer: 'dance', acceptableAnswers: ['dance'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Slow|Lento]] = ____.', options: ['[[not fast|no rápido]]', '[[very fast|muy rápido]]', '[[creative|creativo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Good at|Bueno en]] = ____.', options: ['[[can do well|sabe hacer bien]]', '[[can\'t do|no sabe hacer]]', '[[never does|nunca hace]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Bad at|Malo en]] = ____.', options: ['[[can\'t do well|no hace bien]]', '[[very good|muy bueno]]', '[[fast|rápido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v14', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[is|es]] [[good at|buena en]] [[drawing|dibujar]].', words: ['[[She|Ella]]', '[[is|es]]', '[[good at|buena en]]', '[[drawing|dibujar]].'] }, topicName: 'Vocabulary' },
  { id: 'a1-u37-l2-v15', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[He|Él]] [[can|puede]] [[run|correr]] [[very fast|muy rápido]].', words: ['[[He|Él]]', '[[can|puede]]', '[[run|correr]]', '[[very fast|muy rápido]].'] }, topicName: 'Vocabulary' },
];
