/**
 * Unidad 40 — Lección 6: Expresión escrita (Module 4 Review)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Module 4 Review';

export const UNIT_40_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u40-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[swim|nadar]] [[well|bien]].', options: ['[[can|puedo]]', '[[cans|incorrecto]]', '[[to can|incorrecto]]'], correctAnswer: 'can', acceptableAnswers: ['can'] }] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] ____ [[tennis|tenis]] [[every Saturday|cada sábado]].', options: ['[[plays|juega a]]', '[[play|jugar]]', '[[go|ir]]'], correctAnswer: 'plays', acceptableAnswers: ['plays'] }] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[They|Ellos]] ____ [[swimming|a nadar]] [[on Fridays|los viernes]].', options: ['[[go|van]]', '[[play|juegan]]', '[[do|hacen]]'], correctAnswer: 'go', acceptableAnswers: ['go'] }] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[always|siempre]] [[have|tomo]] [[breakfast|desayuno]] [[at 8|a las 8]].', options: ['[[always|siempre]]', '[[never|nunca]]', '[[yesterday|ayer]]'], correctAnswer: 'always', acceptableAnswers: ['always'] }] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I like tea|Me gusta el té]] ____ [[I don\'t like coffee|no me gusta el café]].', options: ['[[but|pero]]', '[[and|y]]', '[[because|porque]]'], correctAnswer: 'but', acceptableAnswers: ['but'] }] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: "[[I|Yo]] [['m|estoy]] [[going|camino]] [[camping|camping]] [[next week|la próxima semana]]." , words: ["[[I|Yo]]", "[['m|estoy]]", '[[going|camino]]', '[[camping|camping]]', '[[next week|la próxima semana]].'] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Can|¿Puedo]] [[I|yo]] [[borrow|pedir prestado]] [[your|tu]] [[pen|bolígrafo]] [[please|por favor]]?', words: ['[[Can|¿Puedo]]', '[[I|yo]]', '[[borrow|pedir prestado]]', '[[your|tu]]', '[[pen|bolígrafo]]', '[[please|por favor]]?'] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[do|hago]] [[yoga|yoga]] [[in the morning|por la mañana]] [[because|porque]] [[I|yo]] [[like|me gusta]] [[it|me gusta]].', words: ['[[I|Yo]]', '[[do|hago]]', '[[yoga|yoga]]', '[[in the morning|por la mañana]]', '[[because|porque]]', '[[I|yo]]', '[[like|me gusta]]', '[[it|me gusta]].'] }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: algo que sepas hacer bien (can + very well / quite well).', prompt: '____.', minWords: 5, maxWords: 12, modelExample: '[[I|Yo]] [[can|puedo]] [[cook|cocinar]] [[very well|muy bien]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: un deporte o actividad con play, go o do + frecuencia.', prompt: '____.', minWords: 6, maxWords: 14, modelExample: '[[I|Yo]] [[play|juego]] [[football|fútbol]] [[every Saturday|cada sábado]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con and y otra con but.', prompt: '____. ____.', minWords: 10, maxWords: 22, modelExample: '[[I|Yo]] [[like|me gusta]] [[tea|té]] [[and|y]] [[coffee|café]]. [[I|Yo]] [[play|juego]] [[tennis|tenis]] [[but|pero]] [[I|yo]] [[don\'t|no]] [[like|me gusta]] [[football|fútbol]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: un plan para la próxima semana (I\'m going… next week).', prompt: '____.', minWords: 6, maxWords: 14, modelExample: '[[I|Yo]] [[\'m|estoy]] [[going|yendo]] [[camping|camping]] [[next week|la próxima semana]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–5 frases): repasa can, una actividad (play/go/do), frecuencia, because, y un plan futuro.', prompt: '____.', minWords: 30, maxWords: 60, modelExample: '[[I|Yo]] [[can|puedo]] [[swim|nadar]] [[well|bien]]. [[I|Yo]] [[always|siempre]] [[go|voy]] [[swimming|a nadar]] [[on Mondays|los lunes]] [[because|porque]] [[I|yo]] [[love|amo]] [[it|me gusta]]. [[Next weekend|El próximo fin de semana]] [[I|yo]] [[\'m|estoy]] [[going|yendo]] [[hiking|senderismo]]. [[Can I|¿Puedo]] [[use|usar]] [[the|el]] [[bathroom|baño]]? [[Yes|Sí]], [[of course|por supuesto]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: una petición educada (Can I…? o May I…?) y la respuesta.', prompt: '____. ____.', minWords: 8, maxWords: 18, modelExample: '[[Can|¿Puedo]] [[I|yo]] [[borrow|pedir prestado]] [[your|tu]] [[book|libro]]? [[Yes|Sí]], [[of course|por supuesto]]. [[Here|Aquí]] [[you|tú]] [[are|estás]].' }, topicName: 'Writing' },
  { id: 'a1-u40-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: I do yoga because… (da una razón).', prompt: '____.', minWords: 6, maxWords: 15, modelExample: '[[I|Yo]] [[do|hago]] [[yoga|yoga]] [[because|porque]] [[I|yo]] [[like|me gusta]] [[it|me gusta]] [[and|y]] [[it|me]] [[is|es]] [[relaxing|relajante]].' }, topicName: 'Writing' },
];
