/**
 * Unidad 15 — Lección 6: Expresión escrita
 * 15 ejercicios: doesn't, Does he/she…?; 4–5 frases sobre la rutina de alguien.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Present Simple: He, She, It';

export const UNIT_15_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u15-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Con he/she/it la negativa es ____.', questions: [{ question: '[[He|Él]] ____ [[like|le gusta]] [[coffee|café]].', options: ['[[don\'t|no]]', '[[doesn\'t|no]]', '[[not|no]]'], correctAnswer: "doesn't", acceptableAnswers: ["doesn't"], explanation: 'He doesn\'t like.' }] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Con she el verbo lleva -s.', questions: [{ question: '[[She|Ella]] ____ [[to|a]] [[work|trabajo]] [[at|a]] [[nine|nueve]].', options: ['[[go|ir]]', '[[goes|va]]', '[[going|yendo]]'], correctAnswer: 'goes', acceptableAnswers: ['goes'], explanation: 'She goes.' }] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la pregunta.', questions: [{ question: '____ [[she|ella]] [[work|trabaja]] [[on|los]] [[Sundays|domingos]]?', options: ['[[Does|¿]]', '[[Do|¿]]', '[[Is|¿]]'], correctAnswer: 'Does', acceptableAnswers: ['Does'], explanation: 'Does she work...?' }] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la respuesta corta.', questions: [{ question: '[[Does|¿]] [[he|él]] [[play|juega]] [[football|fútbol]]? [[Yes|Sí]], [[he|él]] ____.', options: ['[[does|sí]]', '[[don\'t|no]]', '[[doesn\'t|no]]'], correctAnswer: 'does', acceptableAnswers: ['does'], explanation: 'Yes, he does.' }] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Tras Does el verbo va en infinitivo (sin -s).', questions: [{ question: '[[Does|¿]] [[the|el]] [[cat|gato]] ____ [[like|le gusta]] [[milk|leche]]?', options: ['[[like|gustar]]', '[[likes|gusta]]', '[[liking|gustando]]'], correctAnswer: 'like', acceptableAnswers: ['like'], explanation: 'Does the cat like? No "likes".' }] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[He|Él]] [[doesn\'t|no]] [[like|le gusta]] [[getting up early|levantarse temprano]].', words: ['[[He|Él]]', '[[doesn\'t|no]]', '[[like|le gusta]]', '[[getting up early|levantarse temprano]].'] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[Does|¿]] [[she|ella]] [[work|trabaja]] [[on|los]] [[Saturdays|sábados]]?', words: ['[[Does|¿]]', '[[she|ella]]', '[[work|trabaja]]', '[[on|los]]', '[[Saturdays|sábados]]?'] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[My|Mi]] [[brother|hermano]] [[goes|va]] [[to bed|a la cama]] [[at|a]] [[ten|diez]].', words: ['[[My|Mi]]', '[[brother|hermano]]', '[[goes|va]]', '[[to bed|a la cama]]', '[[at|a]]', '[[ten|diez]].'] }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases sobre la rutina de un familiar (él/ella). Usa he/she + verbo con -s.', prompt: '____. ____.', minWords: 8, maxWords: 20, modelExample: 'My sister gets up at seven. She has breakfast at half past seven.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la pregunta "Does your mother work?" y tu respuesta (Yes, she does / No, she doesn\'t).', prompt: '____? ____.', minWords: 4, maxWords: 10, modelExample: 'Does your mother work? Yes, she does.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe tres frases: qué hace y qué no hace él/ella (usa doesn\'t en una).', prompt: '____. ____. ____.', minWords: 12, maxWords: 28, modelExample: 'He gets up at six. He has coffee for breakfast. He doesn\'t like tea.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: Does he get up early? y responde (Yes/No, he does/d doesn\'t).', prompt: '____? ____.', minWords: 4, maxWords: 10, modelExample: 'Does he get up early? No, he doesn\'t.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe 4–5 frases sobre la rutina de alguien (familiar o personaje). Usa he/she, gets up, has breakfast, works, goes to bed. Incluye una negativa (doesn\'t).', prompt: '[[Someone\'s routine|La rutina de alguien]]: ____.', minWords: 28, maxWords: 60, modelExample: 'My brother gets up at seven. He has breakfast at half past seven. He goes to work at nine. He has dinner at eight. He doesn\'t like getting up early.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4 frases) describiendo a un animal: qué hace y qué no hace (it + 3.ª persona).', prompt: '[[An animal\'s habits|Los hábitos de un animal]]: ____.', minWords: 18, maxWords: 45, modelExample: 'The cat sleeps all day. It eats in the morning. It doesn\'t like dogs. It plays with a ball.' }, topicName: 'Writing' },
  { id: 'a1-u15-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos preguntas Does he/she...? con sus respuestas (sí y no).', prompt: '____? ____. ____? ____.', minWords: 12, maxWords: 28, modelExample: 'Does she like coffee? Yes, she does. Does he work on Sundays? No, he doesn\'t.' }, topicName: 'Writing' },
];
