/**
 * Unidad 44 — Lección 3: Comprensión lectora (The Weather)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'The Weather';
const READING_TRANSCRIPT = `[[Today|Hoy]] [[it is|está]] [[sunny|soleado]] [[and|y]] [[hot|caluroso]]. [[I|Yo]] [[like|me gusta]] [[this|este]] [[weather|tiempo]]. [[Yesterday|Ayer]] [[it was|estuvo]] [[cloudy|nublado]] [[and|y]] [[rainy|lluvioso]]. [[It was|Estuvo]] [[raining|lloviendo]] [[in the afternoon|por la tarde]]. [[In|En]] [[winter|invierno]] [[it is|está]] [[cold|frío]] [[and|y]] [[sometimes|a veces]] [[it is|está]] [[snowing|nevando]]. [[In|En]] [[summer|verano]] [[it is|está]] [[hot|caluroso]] [[and|y]] [[sunny|soleado]]. [[I|Yo]] [[prefer|prefiero]] [[sunny|soleado]] [[weather|tiempo]] [[because|porque]] [[I|yo]] [[can|puedo]] [[go|ir]] [[outside|fuera]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_44_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u44-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is the weather|es el tiempo]] [[today|hoy]]?', options: ['[[Sunny and hot|Soleado y caluroso]]', '[[Cloudy and rainy|Nublado y lluvioso]]', '[[Cold and snowy|Frío y nevado]]'], correctAnswer: 0, explanation: 'Today it is sunny and hot.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[was the weather|fue el tiempo]] [[yesterday|ayer]]?', options: ['[[Cloudy and rainy|Nublado y lluvioso]]', '[[Sunny|Soleado]]', '[[Snowy|Nevado]]'], correctAnswer: 0, explanation: 'Yesterday it was cloudy and rainy.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[was it raining|estuvo lloviendo]] [[yesterday|ayer]]?', options: ['[[In the afternoon|Por la tarde]]', '[[In the morning|Por la mañana]]', '[[At night|Por la noche]]'], correctAnswer: 0, explanation: 'It was raining in the afternoon.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is the weather|es el tiempo]] [[in winter|en invierno]]?', options: ['[[Cold and sometimes snowy|Frío y a veces nevado]]', '[[Hot and sunny|Caluroso y soleado]]', '[[Rainy|Lluvioso]]'], correctAnswer: 0, explanation: 'In winter it is cold and sometimes it is snowing.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is the weather|es el tiempo]] [[in summer|en verano]]?', options: ['[[Hot and sunny|Caluroso y soleado]]', '[[Cold|Frío]]', '[[Snowy|Nevado]]'], correctAnswer: 0, explanation: 'In summer it is hot and sunny.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What weather|Qué tiempo]] [[does the writer prefer|prefiere el autor]]?', options: ['[[Sunny|Soleado]]', '[[Rainy|Lluvioso]]', '[[Snowy|Nevado]]'], correctAnswer: 0, explanation: 'I prefer sunny weather.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Why|Por qué]] [[does he/she prefer|prefiere]] [[sunny weather|tiempo soleado]]?', options: ['[[Because he/she can go outside|Porque puede salir fuera]]', '[[Because it is cold|Porque hace frío]]', '[[Because it rains|Porque llueve]]'], correctAnswer: 0, explanation: 'Because I can go outside.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It is raining|Está lloviendo]] = ____.', options: ['[[rain falls|llueve]]', '[[snow falls|nieva]]', '[[sun shines|brilla el sol]]'], correctAnswer: 0, explanation: 'Raining = lloviendo.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Sunny|Soleado]] = ____.', options: ['[[sun shines|el sol brilla]]', '[[rain|lluvia]]', '[[snow|nieve]]'], correctAnswer: 0, explanation: 'Sunny = soleado.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cloudy|Nublado]] = ____.', options: ['[[clouds in the sky|nubes en el cielo]]', '[[no clouds|sin nubes]]', '[[rain|lluvia]]'], correctAnswer: 0, explanation: 'Cloudy = nublado.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[weather in different times|tiempo en diferentes momentos]]', '[[food|comida]]', '[[transport|transporte]]'], correctAnswer: 0, explanation: 'Weather: today, yesterday, winter, summer.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Hot|Caluroso]] = ____.', options: ['[[high temperature|temperatura alta]]', '[[cold|frío]]', '[[rain|lluvia]]'], correctAnswer: 0, explanation: 'Hot = caluroso.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cold|Frío]] = ____.', options: ['[[low temperature|temperatura baja]]', '[[hot|calor]]', '[[sunny|soleado]]'], correctAnswer: 0, explanation: 'Cold = frío.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Snowing|Nevando]] = ____.', options: ['[[snow falls|nieva]]', '[[rain falls|llueve]]', '[[sun|sol]]'], correctAnswer: 0, explanation: 'Snowing = nevando.' }] }, topicName: 'Reading' },
  { id: 'a1-u44-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is the main topic|es el tema principal]]?', options: ['[[Weather: sunny, rainy, cloudy, hot, cold|El tiempo]]', '[[Seasons|Estaciones]]', '[[Travel|Viajes]]'], correctAnswer: 0, explanation: 'Weather vocabulary and preferences.' }] }, topicName: 'Reading' },
];
