/**
 * Unidad 36 — Lección 1: Gramática (Musical Instruments)
 * play the + instrument (the).
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Play the + instrumento';
const TOPIC = 'Musical Instruments';

export const UNIT_36_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u36-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Con instrumentos usamos ____.', questions: [{ question: '[[I|Yo]] [[play|toco]] ____ [[piano|piano]].', options: ['[[the|el]]', '[[a|un]]', '[[(nothing)|(nada)]]'], correctAnswer: 'the', acceptableAnswers: ['the'], explanation: 'Play the piano, the guitar.' }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[plays|toca]] ____ [[guitar|guitarra]].', options: ['[[the|la]]', '[[a|una]]', '[[(nothing)|(nada)]]'], correctAnswer: 'the', acceptableAnswers: ['the'] }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] [[plays|toca]] ____ [[drums|batería]].', options: ['[[the|la]]', '[[a|una]]', '[[(nothing)|(nada)]]'], correctAnswer: 'the', acceptableAnswers: ['the'] }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] ____ [[the|el]] [[violin|violín]].', options: ['[[play|tocamos]]', '[[plays|toca]]', '[[playing|tocando]]'], correctAnswer: 'play', acceptableAnswers: ['play'] }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[They|Ellos]] [[play|tocan]] ____ [[flute|flauta]].', options: ['[[the|la]]', '[[a|una]]', '[[(nothing)|(nada)]]'], correctAnswer: 'the', acceptableAnswers: ['the'] }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[With|Con]] [[musical instruments|instrumentos musicales]] [[we use|usamos]] ____.', options: ['[[play the + instrument|play the + instrumento]]', '[[play + instrument|play + instrumento]]', '[[play a + instrument|play a + instrumento]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Correct|Correcta]]: ____.', options: ['[[I play the piano|I play the piano]]', '[[I play piano|I play piano]]', '[[I play a piano|I play a piano]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[She|Ella]] ____ ____ [[guitar|guitarra]].', options: ['[[plays the|toca la]]', '[[play the|tocar la]]', '[[playing the|tocando la]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Can you ____ the violin?|Can you ____ the violin?]]', options: ['[[play|play]]', '[[plays|plays]]', '[[playing|playing]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Drums|Batería]]: [[we say|decimos]] ____.', options: ['[[the drums|the drums]]', '[[the drum|the drum]]', '[[a drums|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[play|toco]] [[the|el]] [[piano|piano]].', words: ['[[I|Yo]]', '[[play|toco]]', '[[the|el]]', '[[piano|piano]].'] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[plays|toca]] [[the|la]] [[guitar|guitarra]].', words: ['[[She|Ella]]', '[[plays|toca]]', '[[the|la]]', '[[guitar|guitarra]].'] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[He|Él]] [[can|puede]] [[play|tocar]] [[the|la]] [[flute|flauta]].', words: ['[[He|Él]]', '[[can|puede]]', '[[play|tocar]]', '[[the|la]]', '[[flute|flauta]].'] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We|Se]] [[always|siempre]] [[use|usa]] [[the|the]] [[with|con]] [[instruments|instrumentos]]: [[play the piano|play the piano]], [[play the guitar|play the guitar]].', correctAnswer: true }] }, topicName: 'Grammar' },
  { id: 'a1-u36-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Drums|Drums]] [[is|se usa]] [[plural|en plural]]: [[play the drums|play the drums]].', correctAnswer: true }] }, topicName: 'Grammar' },
];
