/**
 * Unidad 51 — Lección 1: Gramática (At the Supermarket)
 * Plurales regulares e irregulares básicos.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Plurales regulares e irregulares';
const TOPIC = 'At the Supermarket';

export const UNIT_51_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u51-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I need|Necesito]] [[two|dos]] ____ [[for|para]] [[the salad|la ensalada]].', options: ['[[tomatoes|tomates]]', '[[tomatos|incorrecto]]', '[[tomatoes|incorrecto]]'], correctAnswer: 'tomatoes', acceptableAnswers: ['tomatoes'], explanation: 'Tomato → tomatoes (regular -es).' }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We have|Tenemos]] [[three|tres]] ____ [[in|en]] [[the fridge|la nevera]].', options: ['[[potatoes|patatas]]', '[[potatos|incorrecto]]', '[[potato|patata]]'], correctAnswer: 'potatoes', acceptableAnswers: ['potatoes'] }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[There are|Hay]] [[many|muchas]] ____ [[in|en]] [[the fruit section|la sección de fruta]].', options: ['[[apples|manzanas]]', '[[apple|manzana]]', '[[appls|incorrecto]]'], correctAnswer: 'apples', acceptableAnswers: ['apples'] }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I want|Quiero]] [[two|dos]] ____ [[of|de]] [[fish|pescado]].', options: ['[[pieces|piezas]]', '[[piece|pieza]]', '[[fishs|incorrecto]]'], correctAnswer: 'pieces', acceptableAnswers: ['pieces'] }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[How many|Cuántos]] ____ [[do you need|necesitas]]?', options: ['[[eggs|huevos]]', '[[egg|huevo]]', '[[egges|incorrecto]]'], correctAnswer: 'eggs', acceptableAnswers: ['eggs'] }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Plural of|Plural de]] [[child|niño]] = ____.', options: ['[[children|children]]', '[[childs|incorrecto]]', '[[childes|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Correct plural|Plural correcto]] [[of|de]] [[person|persona]]:', options: ['[[people|people]]', '[[persons|incorrecto]]', '[[persones|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We add|Añadimos]] [[-es|es]] [[for plural when|para plural cuando]] ____.', options: ['[[word ends in -s, -ch, -sh, -x|palabra termina en -s, -ch, -sh, -x]]', '[[word is short|palabra es corta]]', '[[always|siempre]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Fish|Pescado]] [[as food|como comida]] [[plural|plural]] = ____.', options: ['[[fish (same)|fish (igual)]]', '[[fishs|incorrecto]]', '[[fishes (only for animals)|fishes (solo animales)]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Vegetable|Verdura]] [[plural|plural]] = ____.', options: ['[[vegetables|vegetables]]', '[[vegetable|igual]]', '[[vegetabls|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[The|Las]] [[apples|manzanas]] [[are|están]] [[in|en]] [[aisle|pasillo]] [[five|cinco]].', words: ['[[The|Las]]', '[[apples|manzanas]]', '[[are|están]]', '[[in|en]]', '[[aisle|pasillo]]', '[[five|cinco]].'] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I need|Necesito]] [[some|algo de]] [[meat|carne]] [[and|y]] [[fish|pescado]].', words: ['[[I need|Necesito]]', '[[some|algo de]]', '[[meat|carne]]', '[[and|y]]', '[[fish|pescado]].'] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Where are|Dónde están]] [[the|las]] [[vegetables|verduras]]?', words: ['[[Where are|Dónde están]]', '[[the|las]]', '[[vegetables|verduras]]?'] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Tomato|Tomato]] [[and|y]] [[potato|potato]] [[add -es|añaden -es]] [[for plural|para plural]].', correctAnswer: true, explanation: 'Tomatoes, potatoes.' }] }, topicName: 'Grammar' },
  { id: 'a1-u51-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We say|Decimos]] [[two fish|two fish]] [[for two pieces of fish|para dos porciones de pescado]].', correctAnswer: true, explanation: 'Fish is unchanged for food.' }] }, topicName: 'Grammar' },
];
