/**
 * Unidad 45 — Lección 4: Comprensión auditiva (Seasons)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Seasons';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[What|Cuál]] [[is your favourite|es tu favorita]] [[season|estación]]? [[B|B]]: [[I|Yo]] [[like|me gusta]] [[summer|verano]]. [[It is|Está]] [[hot|caluroso]] [[and|y]] [[sunny|soleado]] [[in|en]] [[summer|verano]]. [[A|A]]: [[I|Yo]] [[prefer|prefiero]] [[spring|primavera]]. [[The|Las]] [[flowers|flores]] [[bloom|florecen]] [[in|en]] [[spring|primavera]]. [[B|B]]: [[In|En]] [[autumn|otoño]] [[the|las]] [[leaves|hojas]] [[fall|caen]]. [[In|En]] [[winter|invierno]] [[it is|está]] [[cold|frío]] [[and|y]] [[snowy|nevado]]. [[A|A]]: [[I|Yo]] [[love|me encanta]] [[nature|naturaleza]] [[in|en]] [[all|todas]] [[the|las]] [[seasons|estaciones]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_45_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u45-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is B\'s favourite season|es la estación favorita de B]]?', options: ['[[Summer|Verano]]', '[[Spring|Primavera]]', '[[Winter|Invierno]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is the weather|es el tiempo]] [[in summer|en verano]] [[according to B|según B]]?', options: ['[[Hot and sunny|Caluroso y soleado]]', '[[Cold|Frío]]', '[[Rainy|Lluvioso]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[season|estación]] [[does A prefer|prefiere A]]?', options: ['[[Spring|Primavera]]', '[[Summer|Verano]]', '[[Autumn|Otoño]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[happens|pasa]] [[in spring|en primavera]] [[according to A|según A]]?', options: ['[[Flowers bloom|Florecen las flores]]', '[[Leaves fall|Caen las hojas]]', '[[It snows|Nieva]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[happens|pasa]] [[in autumn|en otoño]]?', options: ['[[Leaves fall|Caen las hojas]]', '[[Flowers bloom|Florecen las flores]]', '[[It is hot|Hace calor]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is the weather|es el tiempo]] [[in winter|en invierno]]?', options: ['[[Cold and snowy|Frío y nevado]]', '[[Hot|Caluroso]]', '[[Warm|Cálido]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does A love|ama A]]?', options: ['[[Nature in all seasons|La naturaleza en todas las estaciones]]', '[[Only summer|Solo verano]]', '[[Only winter|Solo invierno]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In summer|En verano]] = ____.', options: ['[[we use in before summer|usamos in antes de summer]]', '[[we use on|usamos on]]', '[[we use at|usamos at]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[is about|trata de]] ____.', options: ['[[seasons and nature|estaciones y naturaleza]]', '[[food|comida]]', '[[transport|transporte]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Spring|Primavera]] = ____.', options: ['[[flowers bloom|florecen las flores]]', '[[snow|nieve]]', '[[leaves fall|caen las hojas]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Winter|Invierno]] = ____.', options: ['[[cold, snow|frío, nieve]]', '[[hot|calor]]', '[[flowers|flores]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Nature|Naturaleza]] = ____.', options: ['[[trees, flowers, animals|árboles, flores, animales]]', '[[cars|coches]]', '[[buildings|edificios]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A asks|A pregunta]] ____.', options: ['[[what is your favourite season|cuál es tu estación favorita]]', '[[about food|sobre comida]]', '[[about transport|sobre transporte]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Autumn|Otoño]] = ____.', options: ['[[leaves fall|caen las hojas]]', '[[flowers bloom|florecen las flores]]', '[[snow|nieve]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u45-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The main topic|El tema principal]] [[is|es]] ____.', options: ['[[the four seasons and nature|las cuatro estaciones y naturaleza]]', '[[weather only|solo tiempo]]', '[[travel|viajes]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
