/**
 * Unidad 37 — Lección 4: Comprensión auditiva (Talent & Skills)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Talent & Skills';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[Can|¿Puedes]] [[you|tú]] [[sing|cantar]]? [[B|B]]: [[Yes|Sí]], [[I|yo]] [[can|puedo]]. [[I|Yo]] [[sing|canto]] [[very well|muy bien]]. [[A|A]]: [[What|Qué]] [[about|tal]] [[cooking|cocinar]]? [[B|B]]: [[I|Yo]] [[cook|cocino]] [[quite well|bastante bien]]. [[My|Mi]] [[brother|hermano]] [[can't|no puede]] [[dance|bailar]] [[at all|nada]]. [[He|Él]] [[is|es]] [[good at|bueno en]] [[drawing|dibujar]] [[though|aunque]]. [[A|A]]: [[Are|¿Sois]] [[you|vosotros]] [[creative|creativos]]? [[B|B]]: [[Yes|Sí]], [[we|nosotros]] [[are|somos]]. [[We|Nosotros]] [[all|todos]] [[have|tenemos]] [[different|diferentes]] [[skills|habilidades]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_37_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u37-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B|B]] [[sing|cantar]]?', options: ['[[Yes, very well|Sí, muy bien]]', '[[No|No]]', '[[Quite well|Bastante bien]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[well|bien]] [[does|cocina]] [[B|B]] [[cook|cocina]]?', options: ['[[Quite well|Bastante bien]]', '[[Very well|Muy bien]]', '[[Not at all|Nada]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B\'s|del]] [[brother|hermano de B]] [[dance|bailar]]?', options: ['[[No, not at all|No, nada]]', '[[Yes|Sí]]', '[[Quite well|Bastante bien]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|En qué]] [[is|es]] [[the|el]] [[brother|hermano]] [[good at|bueno]]?', options: ['[[Drawing|Dibujar]]', '[[Dancing|Bailar]]', '[[Cooking|Cocinar]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Dice]] [[B|B]] [[say|dice]] [[they|que]] [[are|son]] [[creative|creativos]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[all|todos]] ____ [[different|diferentes]] [[skills|habilidades]].', options: ['[[have|tenemos]]', '[[has|tiene]]', '[[having|teniendo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[dialogue|diálogo]] [[is|es]] ____.', options: ['[[about skills and abilities|sobre habilidades y capacidades]]', '[[about food|sobre comida]]', '[[about work|sobre trabajo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[phrase|frase]] [[does|usa]] [[B|B]] [[use|usa]] [[for|para]] "[[muy bien|muy bien]]"?', options: ['[[Very well|Very well]]', '[[Quite well|Quite well]]', '[[Not at all|Not at all]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A|A]] ____ [[about|sobre]] [[singing|cantar]], [[cooking|cocinar]] [[and|y]] [[B\'s family|la familia de B]].', options: ['[[asks|pregunta]]', '[[ask|preguntar]]', '[[asking|preguntando]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Good at|Bueno en]] + ____.', options: ['[[drawing (-ing)|drawing (-ing)]]', '[[draw|draw]]', '[[draws|draws]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[says|dice]] "[[I cook|Yo cocino]]" ____.', options: ['[[quite well|bastante bien]]', '[[very well|muy bien]]', '[[not at all|nada]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[brother|hermano]] [[can\'t|no puede]] ____ [[at all|nada]].', options: ['[[dance|bailar]]', '[[draw|dibujar]]', '[[cook|cocinar]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[aunque|aunque]]"?', options: ['[[Though|Though]]', '[[Well|Well]]', '[[All|All]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[answers|responde]] ____ [[about|sobre]] [[singing|cantar]] [[and|y]] [[cooking|cocinar]].', options: ['[[yes and gives level (very well, quite well)|sí y da el nivel]]', '[[no|no]]', '[[only about brother|solo sobre el hermano]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u37-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Different|Diferentes]] ____ = [[skills|habilidades]].', options: ['[[skills|skills]]', '[[people|people]]', '[[brothers|brothers]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
