/**
 * Unidad 40 — Lección 4: Comprensión auditiva (Module 4 Review)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Module 4 Review';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[Can|¿Puedes]] [[you|tú]] [[swim|nadar]]? [[B|B]]: [[Yes|Sí]], [[I|yo]] [[can|puedo]]. [[I|Yo]] [[go|voy]] [[swimming|a nadar]] [[every week|cada semana]]. [[A|A]]: [[I|Yo]] [[always|siempre]] [[play|juego]] [[tennis|tennis]] [[on Saturdays|los sábados]] [[but|pero]] [[I|yo]] [[don't|no]] [[like|me gusta]] [[football|fútbol]]. [[B|B]]: [[I|Yo]] [['m|estoy]] [[going|yendo]] [[camping|camping]] [[next weekend|el próximo fin de semana]] [[because|porque]] [[I|yo]] [[love|amo]] [[nature|naturaleza]]. [[May I|¿Puedo]] [[borrow|pedir prestado]] [[your|tu]] [[torch|linterna]]? [[A|A]]: [[Of course|Por supuesto]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_40_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u40-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B|B]] [[swim|nadar]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How often|Con qué frecuencia]] [[does|va]] [[B|B]] [[go swimming|ir a nadar]]?', options: ['[[Every week|Cada semana]]', '[[Every day|Cada día]]', '[[Never|Nunca]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|juega]] [[A|A]] [[play|juega]] [[on Saturdays|los sábados]]?', options: ['[[Tennis|Tenis]]', '[[Football|Fútbol]]', '[[Swimming|Natación]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Le]] [[A|A]] [[like|gusta]] [[football|fútbol]]?', options: ['[[No|No]]', '[[Yes|Sí]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[shows|muestra]] [[contrast|contraste]] [[between|entre]] [[tennis and football|tenis y fútbol]]?', options: ['[[But|But]]', '[[And|And]]', '[[Because|Because]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[B|B]] [[going|yendo]] [[to do|a hacer]] [[next weekend|el próximo fin de semana]]?', options: ['[[Going camping|Ir de camping]]', '[[Going swimming|Ir a nadar]]', '[[Playing tennis|Jugar al tenis]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Why|Por qué]] [[is|va]] [[B|B]] [[going|camino]] [[camping|camping]]?', options: ['[[Because he/she loves nature|Porque ama la naturaleza]]', '[[Because of work|Por trabajo]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|pide]] [[B|B]] [[borrow|pedir prestado]]?', options: ['[[A torch|Una linterna]]', '[[A pen|Un bolígrafo]]', '[[A tent|Una tienda]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Cuál]] [[phrase|frase]] [[does|usa]] [[B|B]] [[use|usa]] [[to ask|para pedir]]?', options: ['[[May I borrow…?|May I borrow…?]]', '[[Give me|Dame]]', '[[I want|Quiero]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A\'s answer|La respuesta de A]] [[to|a]] [[borrow|pedir prestado]] [[is|es]] ____.', options: ['[[Of course|Por supuesto]]', '[[No|No]]', '[[Maybe|Quizás]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Go swimming|Ir a nadar]] = ____ [[go|go]] + ____.', options: ['[[we use|usamos]] [[swimming (-ing)|swimming]]', '[[play|play]]', '[[do|do]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Always|Siempre]] [[play|juega]] [[tennis|tenis]] = ____.', options: ['[[adverb of frequency|adverbio de frecuencia]]', '[[past|pasado]]', '[[future plan|plan futuro]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Torch|Linterna]] = ____.', options: ['[[light for camping/dark|luz para camping/oscuro]]', '[[phone|teléfono]]', '[[tent|tienda]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[reviews|repasa]] ____.', options: ['[[can, play/go, frequency, but/because, plans, permission|can, play/go, frecuencia, but/because, planes, permiso]]', '[[only swimming|solo natación]]', '[[only camping|camping solo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u40-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I\'m going camping|Voy de camping]] = ____.', options: ['[[Present Continuous for future|Presente continuo para futuro]]', '[[Past Simple|Pasado simple]]', '[[Infinitive|Infinitivo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
