/**
 * Unidad 50 — Lección 4: Comprensión auditiva (Module 5 Review)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Module 5 Review';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[How|Cómo]] [[did you|fuiste]] [[go|ir]] [[to|a]] [[the airport|el aeropuerto]]? [[B|B]]: [[I|Yo]] [[took the|tomé el]] [[bus|autobús]]. [[The|El]] [[weather|tiempo]] [[was|estuvo]] [[rainy|lluvioso]] [[yesterday|ayer]]. [[A|A]]: [[Were you|¿Estuviste]] [[at|en]] [[the hotel|el hotel]] [[last week|la semana pasada]]? [[B|B]]: [[Yes|Sí]]. [[I|Yo]] [[was|estuve]] [[there|allí]]. [[I|Yo]] [[visited|visité]] [[the|el]] [[most famous|más famoso]] [[museum|museo]]. [[I|Yo]] [[need to|necesito]] [[pack|hacer la maleta]] [[my|mi]] [[suitcase|maleta]] [[tonight|esta noche]]. [[A|A]]: [[Don\'t forget|No olvides]] [[your|tu]] [[passport|pasaporte]]. [[B|B]]: [[I won\'t|No lo haré]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_50_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u50-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[did B go|fue B]] [[to the airport|al aeropuerto]]?', options: ['[[By bus (took the bus)|En autobús]]', '[[By train|En tren]]', '[[By car|En coche]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[was|estuvo]] [[the weather|el tiempo]] [[yesterday|ayer]]?', options: ['[[Rainy|Lluvioso]]', '[[Sunny|Soleado]]', '[[Cold|Frío]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Was B|Estuvo B]] [[at the hotel|en el hotel]] [[last week|la semana pasada]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The dialogue does not say|No lo dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[did B visit|visitó B]]?', options: ['[[The most famous museum|El museo más famoso]]', '[[The beach|La playa]]', '[[The mountains|Las montañas]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[does B need to pack|necesita B hacer la maleta]]?', options: ['[[Tonight|Esta noche]]', '[[Tomorrow|Mañana]]', '[[Last week|La semana pasada]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does A say not to forget|dice A que no olvide]]?', options: ['[[Passport|Pasaporte]]', '[[Suitcase|Maleta]]', '[[Ticket|Billete]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Took the bus|Tomó el autobús]] = ____.', options: ['[[went by bus|fue en autobús]]', '[[went by train|fue en tren]]', '[[went by car|fue en coche]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Was|Estuvo]] = ____.', options: ['[[past of is/am|pasado de is/am]]', '[[present|presente]]', '[[future|futuro]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The most famous|El más famoso]] = ____.', options: ['[[superlative|superlativo]]', '[[comparative|comparativo]]', '[[present|presente]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Need to pack|Necesitar hacer la maleta]] = ____.', options: ['[[necessity to put things in suitcase|necesidad de meter cosas en maleta]]', '[[past|pasado]]', '[[advice|consejo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[covers|incluye]] ____.', options: ['[[transport, weather, hotel, sightseeing, packing|transporte, tiempo, hotel, turismo, equipaje]]', '[[only airport|solo aeropuerto]]', '[[only hotel|solo hotel]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I won\'t forget|No olvidaré]] = ____.', options: ['[[I will not forget|no olvidaré]]', '[[I forgot|olvidé]]', '[[I forget|olvido]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Were you|¿Estuviste]] = ____.', options: ['[[past question with you|pregunta en pasado con you]]', '[[present|presente]]', '[[future|futuro]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Weather was rainy|El tiempo estuvo lluvioso]] = ____.', options: ['[[It was rainy|estuvo lluvioso]]', '[[It is rainy|está lluvioso]]', '[[It will be rainy|estará lluvioso]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u50-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|es]] [[Module 5 review|el repaso del Módulo 5]]?', options: ['[[Travel: airport, transport, weather, hotel, holidays, sightseeing, packing|Viajes: aeropuerto, transporte, tiempo, hotel, vacaciones, turismo, equipaje]]', '[[Only grammar|solo gramática]]', '[[Only vocabulary|solo vocabulario]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
