/**
 * Unidad 28 — Lección 5: Expresión oral (Body Parts)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión oral';
const TOPIC = 'Body Parts';

export const UNIT_28_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a1-u28-l5-s1', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite.', targetText: '[[I|Yo]] [[have|tengo]] [[got|]] [[a|una]] [[head| cabeza]] [[and|y]] [[a|una]] [[face|cara]].', expectedResponse: 'I have got a head and a face.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s2', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[She|Ella]] [[has|tiene]] [[got|]] [[two|dos]] [[arms|brazos]] [[and|y]] [[two|dos]] [[hands|manos]].', expectedResponse: 'She has got two arms and two hands.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s3', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[This|Esta]] [[is|es]] [[my|mi]] [[hand|mano]]. [[These|Estas]] [[are|son]] [[my|mis]] [[feet|pies]].', expectedResponse: 'This is my hand. These are my feet.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s4', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[I|Yo]] [[have|tengo]] [[got|]] [[two|dos]] [[legs|piernas]] [[and|y]] [[two|dos]] [[feet|pies]].', expectedResponse: 'I have got two legs and two feet.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s5', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué tienes en la cara (eyes, nose, mouth).', targetText: '____.', expectedResponse: 'I have got two eyes, a nose and a mouth.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s6', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Señala una parte de tu cuerpo y di: This is my… o These are my…', targetText: '____.', expectedResponse: 'This is my hand. These are my arms.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s7', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[He|Él]] [[has|tiene]] [[got|]] [[blue|azules]] [[eyes|ojos]] [[and|y]] [[a|una]] [[big|grande]] [[nose|nariz]].', expectedResponse: 'He has got blue eyes and a big nose.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s8', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[My|Mi]] [[sister|hermana]] [[has|tiene]] [[got|]] [[long|largas]] [[legs|piernas]].', expectedResponse: 'My sister has got long legs.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s9', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Pregunta en voz alta: ¿Qué tienes en la cara?', targetText: '____?', expectedResponse: 'What do you have got on your face?' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s10', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[These|Estas]] [[are|son]] [[my|mis]] [[arms|brazos]] [[and|y]] [[these|estas]] [[are|son]] [[my|mis]] [[hands|manos]].', expectedResponse: 'These are my arms and these are my hands.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s11', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: Has she got long legs? (Sí)', targetText: '____.', expectedResponse: 'Yes, she has.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s12', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[I|Yo]] [[wash|lavo]] [[my|mis]] [[hands|manos]] [[and|y]] [[my|mi]] [[face|cara]].', expectedResponse: 'I wash my hands and my face.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s13', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Describe en voz alta a una persona: 2–3 partes del cuerpo con have/has got.', targetText: '____.', expectedResponse: 'He/She has got… long arms, big eyes…' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s14', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[This|Esta]] [[is|es]] [[my|mi]] [[head| cabeza]]. [[I|Yo]] [[have|tengo]] [[got|]] [[hair|pelo]] [[on|en]] [[my|mi]] [[head| cabeza]].', expectedResponse: 'This is my head. I have got hair on my head.' }, topicName: 'Speaking' },
  { id: 'a1-u28-l5-s15', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Pregunta en voz alta: ¿Tiene ella ojos azules?', targetText: '____?', expectedResponse: 'Has she got blue eyes?' }, topicName: 'Speaking' },
];
