/**
 * Unidad 55 — Lección 1: Gramática (Clothing Store)
 * too vs enough (too big, not big enough).
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Too y Enough';
const TOPIC = 'Clothing Store';

export const UNIT_55_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u55-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This|Esta]] [[shirt|camisa]] [[is|es]] ____ [[big|grande]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[to|para]]'], correctAnswer: 'too', acceptableAnswers: ['too'], explanation: 'Too + adjetivo = demasiado.' }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It isn\'t|No es]] ____ [[big|grande]] [[enough|suficiente]].', options: ['[[big|grande]]', '[[too|demasiado]]', '[[enough|suficiente]]'], correctAnswer: 'big', acceptableAnswers: ['big'] }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|Los]] [[trousers|pantalones]] [[are|son]] ____ [[small|pequeños]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[not|no]]'], correctAnswer: 'too', acceptableAnswers: ['too'] }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Is it|Es]] ____ [[long|larga]] [[enough|suficiente]]?', options: ['[[long|larga]]', '[[too|demasiado]]', '[[enough|suficiente]]'], correctAnswer: 'long', acceptableAnswers: ['long'] }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This|Este]] [[jacket|chaqueta]] [[is|es]] ____ [[expensive|caro]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[cheap|barato]]'], correctAnswer: 'too', acceptableAnswers: ['too'] }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Too big|Too big]] = ____.', options: ['[[more than needed, doesn\'t fit|más de lo necesario, no queda bien]]', '[[just right|justo bien]]', '[[not enough|no suficiente]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Big enough|Big enough]] = ____.', options: ['[[sufficient size, it fits|talla suficiente, queda bien]]', '[[too big|demasiado grande]]', '[[too small|demasiado pequeño]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Not big enough|Not big enough]] = ____.', options: ['[[too small|demasiado pequeño]]', '[[too big|demasiado grande]]', '[[just right|justo bien]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Word order|Orden]]: [[enough|enough]] ____.', options: ['[[comes after adjective (big enough)|va después del adjetivo]]', '[[comes before adjective|va antes del adjetivo]]', '[[same as too|igual que too]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Word order|Orden]]: [[too|too]] ____.', options: ['[[comes before adjective (too big)|va antes del adjetivo]]', '[[comes after adjective|va después]]', '[[same as enough|igual que enough]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[This|Esta]] [[shirt|camisa]] [[is|es]] [[too|demasiado]] [[big|grande]].', words: ['[[This|Esta]]', '[[shirt|camisa]]', '[[is|es]]', '[[too|demasiado]]', '[[big|grande]].'] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It isn\'t|No es]] [[big|grande]] [[enough|suficiente]].', words: ['[[It isn\'t|No es]]', '[[big|grande]]', '[[enough|suficiente]].'] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Where is|Dónde está]] [[the|el]] [[changing room|probador]]?', words: ['[[Where is|Dónde está]]', '[[the|el]]', '[[changing room|probador]]?'] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Too|Too]] [[+ adjective|+ adjetivo]] = [[demasiado|demasiado]]; [[adjective + enough|adjetivo + enough]] = [[suficientemente|suficientemente]].', correctAnswer: true, explanation: 'Too big, big enough.' }] }, topicName: 'Grammar' },
  { id: 'a1-u55-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Not big enough|Not big enough]] [[means|significa]] [[too small|demasiado pequeño]].', correctAnswer: true, explanation: 'It doesn\'t fit.' }] }, topicName: 'Grammar' },
];
