/**
 * Unidad 13 — Lección 6: Expresión escrita
 * 15 ejercicios: fill-blank, sentence-building, writing (rutina en 5–6 frases ordenadas).
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Daily Routine';

export const UNIT_13_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u13-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Para empezar una secuencia usamos ____.', questions: [{ question: '____ [[I|yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]].', options: ['[[First|Primero]]', '[[Then|Luego]]', '[[After that|Después]]'], correctAnswer: 'First', acceptableAnswers: ['First'], explanation: 'First = primero.' }] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Para el siguiente paso usamos ____.', questions: [{ question: '[[First|Primero]] [[I|yo]] [[brush|me]] [[my|lavo los]] [[teeth|dientes]]. ____ [[I|yo]] [[have|tomo]] [[breakfast|desayuno]].', options: ['[[Then|Luego]]', '[[First|Primero]]', '[[Last|Último]]'], correctAnswer: 'Then', acceptableAnswers: ['Then'], explanation: 'Then = luego.' }] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: '[[I|Yo]] ____ [[up|me]] [[at|a]] [[six|seis]] [[o\'clock|en punto]].', options: ['[[wake|levanto]]', '[[wakes|levanta]]', '[[waking|levantando]]'], correctAnswer: 'wake', acceptableAnswers: ['wake'], explanation: 'I wake up.' }] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. "Irse a la cama" en inglés es go to bed.', questions: [{ question: '[[I|Yo]] ____ [[to bed|a la cama]] [[at|a]] [[ten|diez]].', options: ['[[go|voy]]', '[[wake|me levanto]]', '[[have|tomo]]'], correctAnswer: 'go', acceptableAnswers: ['go'], explanation: 'I go to bed = me acuesto.' }] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. "Desayunar" en inglés es ____.', questions: [{ question: '[[I|Yo]] ____ [[breakfast|desayuno]] [[at|a]] [[eight|ocho]].', options: ['[[have|tomo]]', '[[has|toma]]', '[[having|tomando]]'], correctAnswer: 'have', acceptableAnswers: ['have'], explanation: 'Have breakfast = desayunar.' }] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[First|Primero]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]].', words: ['[[First|Primero]]', '[[I|yo]]', '[[wake up|me levanto]]', '[[at|a]]', '[[seven|siete]].'] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[Then|Luego]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]].', words: ['[[Then|Luego]]', '[[I|yo]]', '[[have|tomo]]', '[[breakfast|desayuno]].'] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[She|Ella]] [[goes|va]] [[to bed|a la cama]] [[at|a]] [[ten|diez]].', words: ['[[She|Ella]]', '[[goes|va]]', '[[to bed|a la cama]]', '[[at|a]]', '[[ten|diez]].'] }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: qué haces primero y qué haces luego por la mañana. Usa First y Then.', prompt: '[[First|Primero]] ____. [[Then|Luego]] ____.', minWords: 8, maxWords: 18, modelExample: '[[First|Primero]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]]. [[Then|Luego]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase diciendo a qué hora te levantas y una diciendo a qué hora te acuestas.', prompt: '____. ____.', minWords: 8, maxWords: 20, modelExample: '[[I|Yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]] [[o\'clock|en punto]]. [[I|Yo]] [[go|voy]] [[to bed|a la cama]] [[at|a]] [[ten|diez]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe tres frases: tu rutina de la mañana (First, Then, After that).', prompt: '____. ____. ____.', minWords: 12, maxWords: 28, modelExample: '[[First|Primero]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[six|seis]]. [[Then|Luego]] [[I|yo]] [[brush|me lavo]] [[my|mis]] [[teeth|dientes]]. [[After that|Después]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la frase "I brush my teeth every morning" y añade qué haces después.', prompt: '____. ____.', minWords: 6, maxWords: 16, modelExample: '[[I|Yo]] [[brush|me lavo]] [[my|mis]] [[teeth|dientes]] [[every|cada]] [[morning|mañana]]. [[Then|Luego]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe tu rutina diaria en 5–6 frases ordenadas. Usa First, Then, After that. Incluye: levantarse, aseo, desayuno, trabajo o estudios, cena, acostarse.', prompt: '[[Describe your day|Describe tu día]]: ____.', minWords: 30, maxWords: 65, modelExample: '[[First|Primero]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]]. [[Then|Luego]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]]. [[After that|Después]] [[I|yo]] [[go|voy]] [[to|a]] [[work|trabajo]]. [[I|Yo]] [[have|como]] [[lunch|comida]] [[at|a]] [[one|la una]]. [[I|Yo]] [[have|ceno]] [[dinner|cena]] [[at|a]] [[eight|las ocho]]. [[I|Yo]] [[go|voy]] [[to bed|a la cama]] [[at|a]] [[ten|diez]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe 4–6 frases: tu rutina desde que te levantas hasta que sales de casa (o hasta el desayuno).', prompt: '[[Morning routine|Rutina de mañana]]: ____.', minWords: 22, maxWords: 50, modelExample: '[[First|Primero]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[six thirty|las seis y media]]. [[Then|Luego]] [[I|yo]] [[brush|me lavo]] [[my|mis]] [[teeth|dientes]] [[and|y]] [[have|me ducho]] [[a|una]] [[shower|ducha]]. [[After that|Después]] [[I|yo]] [[have|tomo]] [[breakfast|desayuno]]. [[I|Yo]] [[have|tomo]] [[coffee|café]] [[and|y]] [[toast|tostadas]]. [[Then|Luego]] [[I|yo]] [[go|voy]] [[to|a]] [[work|trabajo]].' }, topicName: 'Writing' },
  { id: 'a1-u13-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (5–6 frases) comparando tu mañana y tu noche (qué haces en cada momento).', prompt: '[[Morning and night|Mañana y noche]]: ____.', minWords: 28, maxWords: 60, modelExample: '[[In|Por]] [[the|la]] [[morning|mañana]] [[I|yo]] [[wake up|me levanto]] [[at|a]] [[seven|siete]]. [[I|Yo]] [[have|tomo]] [[breakfast|desayuno]] [[and|y]] [[go|voy]] [[to|a]] [[work|trabajo]]. [[In|Por]] [[the|la]] [[evening|tarde]] [[I|yo]] [[have|ceno]] [[dinner|cena]] [[at|a]] [[eight|las ocho]]. [[I|Yo]] [[watch|veo]] [[TV|la tele]]. [[I|Yo]] [[go|voy]] [[to bed|a la cama]] [[at|a]] [[ten|diez]]. [[The|La]] [[morning|mañana]] [[is|es]] [[busy|ocupada]] [[but|pero]] [[the|la]] [[evening|tarde]] [[is|es]] [[quiet|tranquila]].' }, topicName: 'Writing' },
];
