/**
 * Unidad 12 — Lección 6: Expresión escrita
 * 15 ejercicios: fill-blank, sentence-building, writing (días de la semana, qué haces cada día).
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Days of the Week';

export const UNIT_12_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u12-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Con días usamos la preposición ____.', questions: [{ question: '[[I|Yo]] [[work|trabajo]] ____ [[Monday|lunes]].', options: ['[[on|el]]', '[[at|a]]', '[[in|en]]'], correctAnswer: 'on', acceptableAnswers: ['on'], explanation: 'On Monday = el lunes.' }] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. Tercera persona añade -s.', questions: [{ question: '[[She|Ella]] ____ [[class|clase]] [[on|los]] [[Wednesdays|miércoles]].', options: ['[[have|tener]]', '[[has|tiene]]', '[[having|teniendo]]'], correctAnswer: 'has', acceptableAnswers: ['has'], explanation: 'She has class.' }] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: '[[I|Yo]] ____ [[work|trabajo]] [[on|el]] [[weekend|fin de semana]].', options: ['[[don\'t|no]]', '[[doesn\'t|no]]', '[[not|no]]'], correctAnswer: 'don\'t', acceptableAnswers: ["don't"], explanation: 'I don\'t work on the weekend.' }] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. "Fin de semana" en inglés es ____.', questions: [{ question: '[[On|El]] ____ [[I|yo]] [[rest|descanso]].', options: ['[[weekend|fin de semana]]', '[[weekdays|días entre semana]]', '[[week|semana]]'], correctAnswer: 'weekend', acceptableAnswers: ['weekend'], explanation: 'On the weekend = el fin de semana.' }] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa. "De lunes a viernes" en inglés es ____.', questions: [{ question: '[[From|De]] [[Monday|lunes]] ____ [[Friday|viernes]] [[I|yo]] [[work|trabajo]].', options: ['[[to|a]]', '[[at|a]]', '[[on|en]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: 'From Monday to Friday.' }] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras y escribe la oración correcta.', correctSentence: '[[I|Yo]] [[work|trabajo]] [[on|los]] [[Mondays|lunes]].', words: ['[[I|Yo]]', '[[work|trabajo]]', '[[on|los]]', '[[Mondays|lunes]].'] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[What|Qué]] [[do|(auxiliar)]] [[you|tú]] [[do|haces]] [[on|el]] [[Sunday|domingo]]?', words: ['[[What|Qué]]', '[[do|(auxiliar)]]', '[[you|tú]]', '[[do|haces]]', '[[on|el]]', '[[Sunday|domingo]]?'] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[On|El]] [[Saturday|sábado]] [[I|yo]] [[go|voy]] [[shopping|de compras]].', words: ['[[On|El]]', '[[Saturday|sábado]]', '[[I|yo]]', '[[go|voy]]', '[[shopping|de compras]].'] }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase diciendo qué haces un día de la semana (por ejemplo los lunes). Usa: I work/study on...', prompt: '[[On|Los]] ____ ____ ____.', minWords: 5, maxWords: 12, modelExample: '[[On|Los]] [[Monday|lunes]] [[I|yo]] [[work|trabajo]]. [[On|Los]] [[Tuesdays|martes]] [[I|yo]] [[have|tengo]] [[English|inglés]] [[class|clase]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase diciendo qué haces el fin de semana. Usa: On the weekend I...', prompt: '____ ____ ____.', minWords: 5, maxWords: 14, modelExample: '[[On|El]] [[the|(fin de)]] [[weekend|semana]] [[I|yo]] [[rest|descanso]]. [[I|Yo]] [[meet|quedo con]] [[my|mis]] [[friends|amigos]] [[on|el]] [[Saturday|sábado]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: qué haces entre semana y qué haces el domingo.', prompt: '____. ____.', minWords: 8, maxWords: 22, modelExample: '[[From|De]] [[Monday|lunes]] [[to|a]] [[Friday|viernes]] [[I|yo]] [[work|trabajo]]. [[On|El]] [[Sunday|domingo]] [[I|yo]] [[stay|me quedo]] [[at|en]] [[home|casa]] [[and|y]] [[read|leo]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la pregunta "What do you do on Saturday?" y una respuesta.', prompt: '____? ____.', minWords: 6, maxWords: 14, modelExample: '[[What|Qué]] [[do|(auxiliar)]] [[you|tú]] [[do|haces]] [[on|el]] [[Saturday|sábado]]? [[I|Yo]] [[go|voy]] [[shopping|de compras]] [[and|y]] [[I|yo]] [[meet|quedo con]] [[my|mi]] [[family|familia]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–6 frases) sobre tu semana: qué haces cada día o en weekdays y en el weekend. Usa on Monday, on the weekend, etc.', prompt: '[[Describe your week|Describe tu semana]]: ____.', minWords: 25, maxWords: 55, modelExample: '[[On|Los]] [[Monday|lunes]] [[and|y]] [[Wednesday|miércoles]] [[I|yo]] [[work|trabajo]]. [[On|El]] [[Tuesday|martes]] [[I|yo]] [[have|tengo]] [[class|clase]]. [[On|El]] [[the|(fin de)]] [[weekend|semana]] [[I|yo]] [[don\'t|no]] [[work|trabajo]]. [[I|Yo]] [[go|voy]] [[shopping|de compras]] [[on|el]] [[Saturday|sábado]]. [[On|El]] [[Sunday|domingo]] [[I|yo]] [[rest|descanso]] [[at|en]] [[home|casa]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe 4–6 frases: qué haces de lunes a viernes y qué haces el sábado y el domingo.', prompt: '[[Weekdays and weekend|Entre semana y fin de semana]]: ____.', minWords: 18, maxWords: 45, modelExample: '[[From|De]] [[Monday|lunes]] [[to|a]] [[Friday|viernes]] [[I|yo]] [[get up|me levanto]] [[early|temprano]] [[and|y]] [[work|trabajo]]. [[On|El]] [[Saturday|sábado]] [[I|yo]] [[get up|me levanto]] [[late|tarde]]. [[I|Yo]] [[go|voy]] [[to|al]] [[the|(el)]] [[park|parque]]. [[On|El]] [[Sunday|domingo]] [[I|yo]] [[have|como]] [[lunch|comida]] [[with|con]] [[my|mi]] [[family|familia]].' }, topicName: 'Writing' },
  { id: 'a1-u12-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–6 frases) comparando un día entre semana y el sábado o domingo.', prompt: '[[Compare a weekday and the weekend|Compara un día entre semana y el fin de semana]]: ____.', minWords: 28, maxWords: 60, modelExample: '[[On|El]] [[Monday|lunes]] [[I|yo]] [[get up|me levanto]] [[at|a]] [[seven|siete]] [[and|y]] [[go|voy]] [[to|a]] [[work|trabajo]]. [[I|Yo]] [[have|como]] [[lunch|comida]] [[at|a]] [[one|la una]]. [[On|El]] [[Saturday|sábado]] [[I|yo]] [[get up|me levanto]] [[at|a]] [[ten|las diez]]. [[I|Yo]] [[don\'t|no]] [[work|trabajo]]. [[I|Yo]] [[go|voy]] [[shopping|de compras]] [[and|y]] [[meet|quedo con]] [[my|mis]] [[friends|amigos]]. [[Sunday|El domingo]] [[is|es]] [[quiet|tranquilo]]. [[I|Yo]] [[stay|me quedo]] [[at|en]] [[home|casa]].' }, topicName: 'Writing' },
];
