/**
 * Unidad 33 — Lección 3: Comprensión lectora (Adverbs of Frequency)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Adverbs of Frequency';
const READING_TRANSCRIPT = `[[My|Mi]] [[name|nombre]] [[is|es]] [[Emma|Emma]]. [[I|Yo]] [[always|siempre]] [[get up|me levanto]] [[at 7|a las 7]] [[in the morning|por la mañana]]. [[I|Yo]] [[usually|normalmente]] [[have|tomo]] [[breakfast|café]] [[with|con]] [[my|mi]] [[family|familia]]. [[I|Yo]] [[often|a menudo]] [[go|voy]] [[running|a correr]] [[before|antes de]] [[work|trabajo]]. [[I|Yo]] [[sometimes|a veces]] [[meet|quedo]] [[friends|con amigos]] [[for|para]] [[lunch|comer]]. [[I|Yo]] [[never|nunca]] [[eat|como]] [[late|tarde]] [[at night|por la noche]] [[because|porque]] [[I|yo]] [[like|me gusta]] [[to sleep|dormir]] [[early|temprano]]. [[At|Los]] [[weekends|fines de semana]] [[I|yo]] [[always|siempre]] [[relax|me relajo]] [[and|y]] [[read|leo]] [[books|libros]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_33_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u33-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[writer\'s|de la autora]] [[name|nombre]]?', options: ['[[Emma|Emma]]', '[[Eva|Eva]]', '[[Ella|Ella]]'], correctAnswer: 0, explanation: 'My name is Emma.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|A qué hora]] [[does|se]] [[she|ella]] [[get up|levanta]]?', options: ['[[At 7|A las 7]]', '[[At 8|A las 8]]', '[[At 6|A las 6]]'], correctAnswer: 0, explanation: 'I always get up at 7.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Toma]] [[she|ella]] [[have|toma]] [[breakfast|café]] [[with|con]] [[family|familia]]?', options: ['[[Usually yes|Normalmente sí]]', '[[Never|Nunca]]', '[[Sometimes|A veces]]'], correctAnswer: 0, explanation: 'I usually have breakfast with my family.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|hace]] [[she|ella]] [[do|hace]] [[often|a menudo]] [[before work|antes de trabajar]]?', options: ['[[Go running|Ir a correr]]', '[[Have breakfast|Desayunar]]', '[[Meet friends|Quedar con amigos]]'], correctAnswer: 0, explanation: 'I often go running before work.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Queda]] [[she|ella]] [[meet|queda]] [[friends|con amigos]] [[for lunch|para comer]]?', options: ['[[Sometimes|A veces]]', '[[Always|Siempre]]', '[[Never|Nunca]]'], correctAnswer: 0, explanation: 'I sometimes meet friends for lunch.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Come]] [[she|ella]] [[eat|come]] [[late|tarde]] [[at night|por la noche]]?', options: ['[[Never|Nunca]]', '[[Always|Siempre]]', '[[Often|A menudo]]'], correctAnswer: 0, explanation: 'I never eat late at night.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Why|Por]] [[doesn\'t|qué no]] [[she|ella]] [[eat|come]] [[late|tarde]]?', options: ['[[She likes to sleep early|Le gusta dormir temprano]]', '[[She is busy|Está ocupada]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0, explanation: 'Because I like to sleep early.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|hace]] [[she|ella]] [[do|hace]] [[at weekends|los fines de semana]]?', options: ['[[Relax and read books|Relajarse y leer]]', '[[Go running|Ir a correr]]', '[[Meet friends|Quedar con amigos]]'], correctAnswer: 0, explanation: 'I always relax and read books.' }] },
  { id: 'a1-u33-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[At weekends|Los fines de semana]] [[she|ella]] ____ [[relax|relajarse]].', options: ['[[always|siempre]]', '[[sometimes|a veces]]', '[[never|nunca]]'], correctAnswer: 0, explanation: 'I always relax at weekends.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[adverb|adverbio]] [[does|usa]] [[she|ella]] [[use|usa]] [[for|para]] [[get up|levantarse]]?', options: ['[[Always|Always]]', '[[Sometimes|Sometimes]]', '[[Never|Never]]'], correctAnswer: 0, explanation: 'I always get up at 7.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[text|texto]] [[is|es]] ____.', options: ['[[about daily habits and frequency|sobre hábitos y frecuencia]]', '[[about work|sobre trabajo]]', '[[about family|sobre familia]]'], correctAnswer: 0, explanation: 'Habits with adverbs of frequency.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[nunca|nunca]]"?', options: ['[[Never|Never]]', '[[Always|Always]]', '[[Sometimes|Sometimes]]'], correctAnswer: 0, explanation: 'Never = nunca.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[a menudo|a menudo]]"?', options: ['[[Often|Often]]', '[[Always|Always]]', '[[Never|Never]]'], correctAnswer: 0, explanation: 'Often = a menudo.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[has|toma]] [[breakfast|desayuno]] [[with family|con la familia]].', options: ['[[usually|normalmente]]', '[[never|nunca]]', '[[always|siempre]]'], correctAnswer: 0, explanation: 'I usually have breakfast with my family.' }] }, topicName: 'Reading' },
  { id: 'a1-u33-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]]?', options: ['[[Emma\'s daily routine and how often she does things|Rutina de Emma y con qué frecuencia hace las cosas]]', '[[Emma\'s job|El trabajo de Emma]]', '[[Emma\'s family|La familia de Emma]]'], correctAnswer: 0, explanation: 'Habits and frequency.' }] }, topicName: 'Reading' },
];
