/**
 * Unidad 46 — Lección 6: Expresión escrita (At the Hotel)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'At the Hotel';

export const UNIT_46_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u46-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Can|Puedo]] [[I|yo]] ____ [[have|tener]] [[a|una]] [[key|llave]]?', options: ['[[have|tener]]', '[[having|teniendo]]', '[[to have|tener]]'], correctAnswer: 'have', acceptableAnswers: ['have'] }] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '____ [[there|hay]] [[a|una]] [[restaurant|restaurante]] [[in|en]] [[the|el]] [[hotel|hotel]]?', options: ['[[Is|¿Hay]]', '[[Are|¿Son]]', '[[Do|¿Hace]]'], correctAnswer: 'Is', acceptableAnswers: ['Is'] }] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[would|me]] ____ [[like|gustaría]] [[room service|servicio de habitaciones]].', options: ['[[like|gustaría]]', '[[to like|gustar]]', '[[liking|gustando]]'], correctAnswer: 'like', acceptableAnswers: ['like'] }] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Go|Ve]] ____ [[reception|recepción]] [[to|para]] [[check in|hacer check-in]].', options: ['[[to|a]]', '[[at|en]]', '[[in|en]]'], correctAnswer: 'to', acceptableAnswers: ['to'] }] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[need|necesito]] [[a|una]] ____ [[for|para]] [[room|habitación]] [[twelve|doce]].', options: ['[[key|llave]]', '[[reception|recepción]]', '[[room service|servicio de habitaciones]]'], correctAnswer: 'key', acceptableAnswers: ['key'] }] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Can|Puedo]] [[I|yo]] [[have|tener]] [[a|una]] [[key|llave]] [[for|para]] [[room|habitación]] [[five|cinco]]?', words: ['[[Can|Puedo]]', '[[I|yo]]', '[[have|tener]]', '[[a|una]]', '[[key|llave]]', '[[for|para]]', '[[room|habitación]]', '[[five|cinco]]?'] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Is|¿Hay]] [[there|allí]] [[a|una]] [[double room|habitación doble]] [[available|disponible]]?', words: ['[[Is|¿Hay]]', '[[there|allí]]', '[[a|una]]', '[[double room|habitación doble]]', '[[available|disponible]]?'] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[go|voy]] [[to|a]] [[reception|recepción]] [[to|para]] [[check in|hacer check-in]].', words: ['[[I|Yo]]', '[[go|voy]]', '[[to|a]]', '[[reception|recepción]]', '[[to|para]]', '[[check in|hacer check-in]].'] }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: pide una llave para tu habitación (Can I have…?).', prompt: '____.', minWords: 5, maxWords: 12, modelExample: '[[Can|Puedo]] [[I|yo]] [[have|tener]] [[a|una]] [[key|llave]] [[for|para]] [[room|habitación]] [[ten|diez]]?' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una pregunta: ¿Hay Wi-Fi en el hotel? (Is there…?).', prompt: '____?', minWords: 5, maxWords: 10, modelExample: '[[Is|¿Hay]] [[there|allí]] [[Wi-Fi|Wi-Fi]] [[in|en]] [[the|el]] [[hotel|hotel]]?' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: que tienes una reserva y que quieres una habitación doble.', prompt: '____. ____.', minWords: 10, maxWords: 20, modelExample: '[[I|Yo]] [[have|tengo]] [[a|una]] [[booking|reserva]]. [[I|Yo]] [[would|me]] [[like|gustaría]] [[a|una]] [[double room|habitación doble]].' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: pregunta Can I have room service? y respuesta breve (Yes, call reception).', prompt: '____? ____.', minWords: 5, maxWords: 12, modelExample: '[[Can|Puedo]] [[I|yo]] [[have|tener]] [[room service|servicio de habitaciones]]? [[Yes|Sí]], [[call|llama]] [[reception|recepción]].' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3–4 frases): llegas al hotel, vas a recepción, pides llave y preguntas si hay restaurante.', prompt: '____.', minWords: 20, maxWords: 50, modelExample: '[[I|Yo]] [[go|voy]] [[to|a]] [[reception|recepción]] [[to|para]] [[check in|hacer check-in]]. [[Can|Puedo]] [[I|yo]] [[have|tener]] [[a|una]] [[key|llave]] [[for|para]] [[room|habitación]] [[eight|ocho]]? [[Is|¿Hay]] [[there|allí]] [[a|un]] [[restaurant|restaurante]]? [[Yes|Sí]], [[there is|hay]].' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 peticiones que harías en un hotel (Can I have…?, Is there…?).', prompt: '____.', minWords: 10, maxWords: 25, modelExample: '[[Can|Puedo]] [[I|yo]] [[have|tener]] [[a|una]] [[key|llave]]? [[Is|¿Hay]] [[there|allí]] [[Wi-Fi|Wi-Fi]]? [[I|Yo]] [[would|me]] [[like|gustaría]] [[room service|servicio de habitaciones]].' }, topicName: 'Writing' },
  { id: 'a1-u46-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe: qué tipo de habitación quieres (single/double) y una pregunta con Is there.', prompt: '____.', minWords: 8, maxWords: 18, modelExample: '[[I|Yo]] [[would|me]] [[like|gustaría]] [[a|una]] [[single room|habitación individual]]. [[Is|¿Hay]] [[there|allí]] [[a|una]] [[bathroom|baño]] [[in|en]] [[the|la]] [[room|habitación]]?' }, topicName: 'Writing' },
];
