/**
 * Unidad 40 — Lección 2: Vocabulario (Module 4 Review)
 * Repaso: deportes, actividades, frecuencia, permisos, planes.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Repaso vocabulario: deportes, actividades, planes';
const TOPIC = 'Module 4 Review';

export const UNIT_40_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u40-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Play|Jugar]] ____ [[football, tennis|fútbol, tenis]].', options: ['[[sports with ball|deportes con pelota]]', '[[swimming|natación]]', '[[yoga|yoga]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Go|Ir]] ____ [[swimming, cycling|nadar, ciclismo]].', options: ['[[activities in -ing|actividades en -ing]]', '[[football|fútbol]]', '[[yoga|yoga]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Do|Hacer]] ____ [[yoga, gymnastics|yoga, gimnasia]].', options: ['[[sports/activities (no ball, no -ing)|deportes/actividades]]', '[[football|fútbol]]', '[[swimming|natación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Always|Siempre]] = ____.', options: ['[[100% of the time|100% del tiempo]]', '[[0%|0%]]', '[[50%|50%]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[May I…?|¿Puedo…?]] = ____ [[than|que]] [[Can I…?|Can I…?]].', options: ['[[more formal|más formal]]', '[[less formal|menos formal]]', '[[same|igual]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[play|jugar]]', right: '[[football, tennis|fútbol, tenis]]' }, { id: 'p2', left: '[[go|ir]]', right: '[[swimming, camping|nadar, camping]]' }, { id: 'p3', left: '[[do|hacer]]', right: '[[yoga, gymnastics|yoga, gimnasia]]' }, { id: 'p4', left: '[[can|puedo]]', right: '[[ability|capacidad]]' }, { id: 'p5', left: '[[going|yendo]]', right: '[[future plan|plan futuro]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[and|y]]', right: '[[addition|adición]]' }, { id: 'p2', left: '[[but|pero]]', right: '[[contrast|contraste]]' }, { id: 'p3', left: '[[because|porque]]', right: '[[reason|razón]]' }, { id: 'p4', left: '[[very well|muy bien]]', right: '[[high level|nivel alto]]' }, { id: 'p5', left: '[[of course|por supuesto]]', right: '[[yes, sure|sí, claro]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[play|juego]] [[tennis|tenis]] [[on Sundays|los domingos]].', options: ['[[always|siempre]]', '[[never|nunca]]', '[[yesterday|ayer]]'], correctAnswer: 'always', acceptableAnswers: ['always', 'sometimes', 'usually'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Can|¿Puedo]] [[I|yo]] ____ [[your|tu]] [[pen|bolígrafo]]?', options: ['[[borrow|pedir prestado]]', '[[borrows|pide prestado]]', '[[borrowing|pidiendo prestado]]'], correctAnswer: 'borrow', acceptableAnswers: ['borrow'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[is|está]] ____ [[hiking|senderismo]] [[next week|la próxima semana]].', options: ['[[going|yendo]]', '[[go|ir]]', '[[goes|va]]'], correctAnswer: 'going', acceptableAnswers: ['going'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Never|Nunca]] = ____.', options: ['[[0%|0%]]', '[[100%|100%]]', '[[sometimes|a veces]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Excuse me|Con permiso]] = ____.', options: ['[[polite way to start request|forma educada de empezar petición]]', '[[thank you|gracias]]', '[[goodbye|adiós]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Outdoor activities|Actividades al aire libre]] = ____.', options: ['[[hiking, camping, fishing|senderismo, camping, pesca]]', '[[chess|ajedrez]]', '[[TV|televisión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v14', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[usually|normalmente]] [[go|voy]] [[swimming|a nadar]] [[on Fridays|los viernes]].', words: ['[[I|Yo]]', '[[usually|normalmente]]', '[[go|voy]]', '[[swimming|a nadar]]', '[[on Fridays|los viernes]].'] }, topicName: 'Vocabulary' },
  { id: 'a1-u40-l2-v15', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[We|Nosotros]] [[are|estamos]] [[going|yendo]] [[camping|camping]] [[because|porque]] [[we|nosotros]] [[love|amamos]] [[nature|naturaleza]].', words: ['[[We|Nosotros]]', '[[are|estamos]]', '[[going|yendo]]', '[[camping|camping]]', '[[because|porque]]', '[[we|nosotros]]', '[[love|amamos]]', '[[nature|naturaleza]].'] }, topicName: 'Vocabulary' },
];
