/**
 * Unidad 24 — Lección 6: Expresión escrita (Prepositions of Place)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Prepositions of Place';

export const UNIT_24_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u24-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|La]] [[pharmacy|farmacia]] ____ [[next to|al lado de]] [[the|la]] [[bank|banco]].', options: ['[[is|está]]', '[[are|están]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: 'The pharmacy is next to the bank.' }] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|El]] [[supermarket|supermercado]] [[is|está]] ____ [[the|la]] [[bank|banco]] [[and|y]] [[the|la]] [[library|biblioteca]].', options: ['[[between|entre]]', '[[next to|al lado de]]', '[[opposite|enfrente de]]'], correctAnswer: 'between', acceptableAnswers: ['between'] }] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[There|Hay]] [[is|(sing)]] [[a|un]] [[park|parque]] ____ [[the|la]] [[library|biblioteca]].', options: ['[[in front of|delante de]]', '[[behind|detrás de]]', '[[between|entre]]'], correctAnswer: 'in front of', acceptableAnswers: ['in front of'] }] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|El]] ____ [[is|está]] [[opposite|enfrente de]] [[the|la]] [[park|parque]].', options: ['[[cinema|cine]]', '[[bank|banco]]', '[[pharmacy|farmacia]]'], correctAnswer: 'cinema', acceptableAnswers: ['cinema'] }] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[There|Hay]] ____ [[a|una]] [[bus stop|parada]] [[in front of|delante de]] [[the|la]] [[school|escuela]].', options: ['[[is|(sing)]]', '[[are|(pl)]]', '[[have|tener]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[There|Hay]] [[is|(sing)]] [[a|un]] [[cafe|café]] [[next to|al lado de]] [[the|el]] [[supermarket|supermercado]].', words: ['[[There|Hay]]', '[[is|(sing)]]', '[[a|un]]', '[[cafe|café]]', '[[next to|al lado de]]', '[[the|el]]', '[[supermarket|supermercado]].'] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[The|La]] [[library|biblioteca]] [[is|está]] [[between|entre]] [[the|la]] [[pharmacy|farmacia]] [[and|y]] [[the|el]] [[cinema|cine]].', words: ['[[The|La]]', '[[library|biblioteca]]', '[[is|está]]', '[[between|entre]]', '[[the|la]]', '[[pharmacy|farmacia]]', '[[and|y]]', '[[the|el]]', '[[cinema|cine]].'] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[The|El]] [[bus stop|parada]] [[is|está]] [[in front of|delante de]] [[the|la]] [[library|biblioteca]].', words: ['[[The|El]]', '[[bus stop|parada]]', '[[is|está]]', '[[in front of|delante de]]', '[[the|la]]', '[[library|biblioteca]].'] }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: dónde está un lugar (next to, between, in front of u opposite).', prompt: '____.', minWords: 6, maxWords: 14, modelExample: '[[The|La]] [[pharmacy|farmacia]] [[is|está]] [[next to|al lado de]] [[the|la]] [[bank|banco]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe: There is… next to / between / in front of / opposite… (un lugar de tu barrio).', prompt: '____.', minWords: 8, maxWords: 18, modelExample: '[[There|Hay]] [[is|(sing)]] [[a|un]] [[park|parque]] [[in front of|delante de]] [[the|la]] [[library|biblioteca]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: posición de dos lugares (ej. farmacia al lado del banco; cine enfrente del parque).', prompt: '____. ____.', minWords: 12, maxWords: 28, modelExample: '[[The|La]] [[pharmacy|farmacia]] [[is|está]] [[next to|al lado de]] [[the|la]] [[bank|banco]]. [[The|El]] [[cinema|cine]] [[is|está]] [[opposite|enfrente de]] [[the|la]] [[park|parque]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la pregunta Where is the…? y una respuesta con next to, between, opposite o in front of.', prompt: '____? ____.', minWords: 6, maxWords: 16, modelExample: '[[Where|Dónde]] [[is|está]] [[the|la]] [[pharmacy|farmacia]]? [[It|Está]] [[is|(está)]] [[next to|al lado de]] [[the|la]] [[bank|banco]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–5 frases): lugares en tu barrio y su posición (next to, between, in front of, opposite).', prompt: '____.', minWords: 28, maxWords: 55, modelExample: '[[There|Hay]] [[is|(sing)]] [[a|un]] [[supermarket|supermercado]] [[next to|al lado de]] [[the|la]] [[bank|banco]]. [[There|Hay]] [[is|(sing)]] [[a|una]] [[pharmacy|farmacia]] [[between|entre]] [[the|la]] [[bank|banco]] [[and|y]] [[the|el]] [[supermarket|supermercado]]. [[The|El]] [[cinema|cine]] [[is|está]] [[opposite|enfrente de]] [[the|la]] [[park|parque]]. [[The|La]] [[bus stop|parada]] [[is|está]] [[in front of|delante de]] [[the|la]] [[library|biblioteca]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 frases: dónde están la farmacia, el supermercado y el cine (usando next to, between, opposite).', prompt: '____.', minWords: 18, maxWords: 40, modelExample: '[[The|La]] [[pharmacy|farmacia]] [[is|está]] [[next to|al lado de]] [[the|la]] [[bank|banco]]. [[The|El]] [[supermarket|supermercado]] [[is|está]] [[between|entre]] [[the|la]] [[pharmacy|farmacia]] [[and|y]] [[the|la]] [[library|biblioteca]]. [[The|El]] [[cinema|cine]] [[is|está]] [[opposite|enfrente de]] [[the|la]] [[park|parque]].' }, topicName: 'Writing' },
  { id: 'a1-u24-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe: Where is the bus stop? y tu respuesta con in front of.', prompt: '____? ____.', minWords: 6, maxWords: 14, modelExample: '[[Where|Dónde]] [[is|está]] [[the|la]] [[bus stop|parada]]? [[It|Está]] [[is|(está)]] [[in front of|delante de]] [[the|la]] [[library|biblioteca]].' }, topicName: 'Writing' },
];
