/**
 * Unidad 25 — Lección 1: Gramática (My Neighborhood)
 * the vs a/an; some/any intro; park, supermarket, cinema, library, pharmacy.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'The vs a/an; some/any';
const TOPIC = 'My Neighborhood';

export const UNIT_25_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u25-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Referencia específica.', questions: [{ question: '[[I|Yo]] [[go|voy]] [[to|a]] ____ [[park|parque]] [[every|todos los]] [[day|días]].', options: ['[[the|el (específico)]]', '[[a|un]]', '[[an|un]]'], correctAnswer: 'the', acceptableAnswers: ['the'], explanation: 'The = el/la que conocemos.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Primera mención, consonante.', questions: [{ question: '[[There|Hay]] [[is|(sing)]] ____ [[supermarket|supermercado]] [[near|cerca de]] [[my|mi]] [[house|casa]].', options: ['[[a|un]]', '[[an|un]]', '[[the|el]]'], correctAnswer: 'a', acceptableAnswers: ['a'], explanation: 'A + consonante.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Primera mención, vocal.', questions: [{ question: '[[There|Hay]] [[is|(sing)]] ____ [[apple|manzana]] [[on|en]] [[the|la]] [[table|mesa]].', options: ['[[an|un/una]]', '[[a|un]]', '[[the|el/la]]'], correctAnswer: 'an', acceptableAnswers: ['an'], explanation: 'An + vocal.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Afirmativa, cantidad indefinida.', questions: [{ question: '[[There|Hay]] [[are|(pl)]] ____ [[shops|tiendas]] [[in|en]] [[my|mi]] [[street|calle]].', options: ['[[some|algunos/algunas]]', '[[any|ninguno (neg/interr)]]', '[[the|los/las]]'], correctAnswer: 'some', acceptableAnswers: ['some'], explanation: 'Some en afirmativa.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa. Pregunta.', questions: [{ question: '[[Are|¿Hay]] [[there|]] ____ [[cafes|cafés]] [[near|cerca]] [[here|aquí]]?', options: ['[[any|algún/alguna]]', '[[some|algunos]]', '[[the|el/la]]'], correctAnswer: 'any', acceptableAnswers: ['any'], explanation: 'Any en preguntas.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We|Se]] [[use|usa]] ____ [[for|para]] [[specific|específico]] [[or|o]] [[known|conocido]] [[things|cosas]].', options: ['[[the|the]]', '[[a|a]]', '[[some|some]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[There|No]] [[aren\'t|no hay]] ____ [[pharmacies|farmacias]] [[here|aquí]].', options: ['[[any|ninguna]]', '[[some|algunas]]', '[[the|las]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[I|Yo]] [[want|quiero]] ____ [[go|ir]] [[to|a]] ____ [[cinema|cine]].', options: ['[[to|a]], [[the|el]]', '[[to|a]], [[a|un]]', '[[at|en]], [[the|el]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[There|Hay]] [[is|(sing)]] ____ [[library|biblioteca]] [[in|en]] [[the|el]] [[centre|centro]].', options: ['[[a|una]]', '[[an|una]]', '[[the|la]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Do|¿Tienes]] [[you|tú]] [[have|tienes]] ____ [[bread|pan]]?', options: ['[[any|algo de]]', '[[some|algo de]]', '[[the|el]]'], correctAnswer: 0, explanation: 'Any en preguntas.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[There|Hay]] [[is|(sing)]] [[a|un]] [[supermarket|supermercado]] [[near|cerca de]] [[the|la]] [[park|parque]].', words: ['[[There|Hay]]', '[[is|(sing)]]', '[[a|un]]', '[[supermarket|supermercado]]', '[[near|cerca de]]', '[[the|la]]', '[[park|parque]].'] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[need|necesito]] [[some|algo de]] [[milk|leche]] [[from|de]] [[the|la]] [[supermarket|supermercado]].', words: ['[[I|Yo]]', '[[need|necesito]]', '[[some|algo de]]', '[[milk|leche]]', '[[from|de]]', '[[the|la]]', '[[supermarket|supermercado]].'] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[There|No]] [[aren\'t|no hay]] [[any|ningún]] [[cafes|cafés]] [[in|en]] [[this|esta]] [[street|calle]].', words: ['[[There|No]]', "[[aren't|no hay]]", '[[any|ningún]]', '[[cafes|cafés]]', '[[in|en]]', '[[this|esta]]', '[[street|calle]].'] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We|Se]] [[use|usa]] [[some|some]] [[in|en]] [[affirmative|afirmativas]] [[and|y]] [[any|any]] [[in|en]] [[negative|negativas]] [[and|y]] [[questions|preguntas]].', correctAnswer: true, explanation: 'Some: afirmativa. Any: negativa y preguntas.' }] }, topicName: 'Grammar' },
  { id: 'a1-u25-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[A|A]] [[before|antes de]] [[consonant|consonante]]; [[an|an]] [[before|antes de]] [[vowel sound|sonido vocálico]].', correctAnswer: true, explanation: 'A book, an apple.' }] }, topicName: 'Grammar' },
];
