/**
 * Unidad 43 — Lección 3: Comprensión lectora (Travel Verbs)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Travel Verbs';
const READING_TRANSCRIPT = `[[I|Yo]] [[am|estoy]] [[going|yendo]] [[to|a]] [[London|Londres]] [[next|el próximo]] [[week|semana]]. [[My|Mi]] [[train|tren]] [[leaves|sale]] [[at|a]] [[eight|ocho]] [[o\'clock|en punto]] [[in the morning|por la mañana]]. [[It|Él]] [[arrives|llega]] [[in|a]] [[London|Londres]] [[at|a]] [[half past ten|las diez y media]]. [[I|Yo]] [[stay|me quedo]] [[at|en]] [[a|un]] [[hotel|hotel]] [[for|por]] [[three|tres]] [[nights|noches]]. [[I|Yo]] [[want|quiero]] [[to|a]] [[visit|visitar]] [[the|los]] [[museums|museos]] [[and|y]] [[explore|explorar]] [[the|la]] [[city|ciudad]]. [[My|Mi]] [[flight|vuelo]] [[departs|sale]] [[on|el]] [[Sunday|domingo]] [[at|a]] [[five|cinco]] [[o\'clock|en punto]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_43_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u43-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[is the writer going|va el autor]] [[next week|la próxima semana]]?', options: ['[[To London|A Londres]]', '[[To Paris|A París]]', '[[To Madrid|A Madrid]]'], correctAnswer: 0, explanation: 'I am going to London next week.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What time|A qué hora]] [[does the train leave|sale el tren]]?', options: ['[[At eight o\'clock|A las ocho]]', '[[At ten|A las diez]]', '[[At five|A las cinco]]'], correctAnswer: 0, explanation: 'My train leaves at eight o\'clock in the morning.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[does the train arrive|llega el tren]] [[in London|a Londres]]?', options: ['[[At half past ten|A las diez y media]]', '[[At eight|A las ocho]]', '[[At five|A las cinco]]'], correctAnswer: 0, explanation: 'It arrives in London at half past ten.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[does the writer stay|se queda el autor]]?', options: ['[[At a hotel|En un hotel]]', '[[At home|En casa]]', '[[On the train|En el tren]]'], correctAnswer: 0, explanation: 'I stay at a hotel for three nights.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How many|Cuántas]] [[nights|noches]] [[does he/she stay|se queda]]?', options: ['[[Three|Tres]]', '[[One|Una]]', '[[Five|Cinco]]'], correctAnswer: 0, explanation: 'I stay at a hotel for three nights.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does he/she want to do|quiere hacer]]?', options: ['[[Visit museums and explore the city|Visitar museos y explorar la ciudad]]', '[[Stay at home|Quedarse en casa]]', '[[Depart early|Salir temprano]]'], correctAnswer: 0, explanation: 'I want to visit the museums and explore the city.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[does the flight depart|sale el vuelo]]?', options: ['[[On Sunday at five|El domingo a las cinco]]', '[[On Monday|El lunes]]', '[[At eight|A las ocho]]'], correctAnswer: 0, explanation: 'My flight departs on Sunday at five o\'clock.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Leaves|Sale]] = ____.', options: ['[[departs|parte]]', '[[arrives|llega]]', '[[stays|se queda]]'], correctAnswer: 0, explanation: 'Leaves = departs.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Explore|Explorar]] = ____.', options: ['[[discover, look around|descubrir, mirar alrededor]]', '[[leave|salir]]', '[[sleep|dormir]]'], correctAnswer: 0, explanation: 'Explore = explorar.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Stay at a hotel|Quedarse en un hotel]] = ____.', options: ['[[sleep there for some days|dormir allí unos días]]', '[[visit for one hour|visitar una hora]]', '[[depart|salir]]'], correctAnswer: 0, explanation: 'Stay = quedarse.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[a trip to London|un viaje a Londres]]', '[[work|trabajo]]', '[[food|comida]]'], correctAnswer: 0, explanation: 'Trip, train, hotel, visit, explore.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Arrives|Llega]] = ____.', options: ['[[reaches a place|llega a un lugar]]', '[[departs|sale]]', '[[visits|visita]]'], correctAnswer: 0, explanation: 'Arrives = llega.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Visit|Visitar]] = ____.', options: ['[[go to see|ir a ver]]', '[[leave|salir]]', '[[stay|quedarse]]'], correctAnswer: 0, explanation: 'Visit = visitar.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Departs|Sale]] = ____.', options: ['[[leaves|parte]]', '[[arrives|llega]]', '[[stays|se queda]]'], correctAnswer: 0, explanation: 'Departs = sale.' }] }, topicName: 'Reading' },
  { id: 'a1-u43-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is the main topic|es el tema principal]]?', options: ['[[Travel plans: leave, arrive, stay, visit, explore|Planes de viaje]]', '[[Shopping|Compras]]', '[[School|Colegio]]'], correctAnswer: 0, explanation: 'Travel verbs and schedule.' }] }, topicName: 'Reading' },
];
