/**
 * Unidad 58 — Lección 1: Gramática (Health & Illness)
 * should/shouldn't para consejos.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Should / Shouldn\'t para consejos';
const TOPIC = 'Health & Illness';

export const UNIT_58_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u58-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[see|ver]] [[a|un]] [[doctor|médico]] [[if|si]] [[you have|tienes]] [[a fever|fiebre]].', options: ['[[should|deberías]]', '[[should to|incorrecto]]', '[[shoulds|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'], explanation: 'Should + verbo base para consejo.' }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[take|tomar]] [[medicine|medicina]] [[for|para]] [[a headache|dolor de cabeza]].', options: ['[[should|deberías]]', '[[should to|incorrecto]]', '[[to should|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'] }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] ____ [[go|ir]] [[to|a]] [[the|la]] [[pharmacy|farmacia]] [[for|para]] [[medicine|medicina]].', options: ['[[should|debería]]', '[[shoulds|incorrecto]]', '[[to should|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'] }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[drink|beber]] [[a lot of|mucha]] [[water|agua]] [[when|cuando]] [[you have|tienes]] [[a cold|resfriado]].', options: ['[[should|deberías]]', '[[shouldn\'t|no deberías]]', '[[should to|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'] }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[go|ir]] [[to work|a trabajar]] [[if|si]] [[you are|estás]] [[very ill|muy enfermo]].', options: ['[[shouldn\'t|no deberías]]', '[[should|deberías]]', '[[should not to|incorrecto]]'], correctAnswer: "shouldn't", acceptableAnswers: ["shouldn't", 'should not'] }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Should|Should]] [[is used for|se usa para]] ____.', options: ['[[advice or recommendation|consejo o recomendación]]', '[[obligation|obligación]]', '[[past|pasado]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[After|Después de]] [[should|should]] [[we use|usamos]] ____.', options: ['[[base verb (see, take, go)|verbo base]]', '[[to + verb|to + verbo]]', '[[-ing|gerundio]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Shouldn\'t|Shouldn\'t]] = ____.', options: ['[[should not|should not]]', '[[should to not|incorrecto]]', '[[do not should|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[For a headache|Para dolor de cabeza]] [[you|tú]] ____.', options: ['[[should take medicine or rest|deberías tomar medicina o descansar]]', '[[should go to work|deberías ir a trabajar]]', '[[shouldn\'t drink water|no deberías beber agua]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Pharmacy|Farmacia]] = ____.', options: ['[[place to buy medicine|lugar para comprar medicina]]', '[[hospital|hospital]]', '[[doctor|médico]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[You|Tú]] [[should|deberías]] [[see|ver]] [[a|un]] [[doctor|médico]] [[if|si]] [[you have|tienes]] [[a fever|fiebre]].', words: ['[[You|Tú]]', '[[should|deberías]]', '[[see|ver]]', '[[a|un]]', '[[doctor|médico]]', '[[if|si]]', '[[you have|tienes]]', '[[a fever|fiebre]].'] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[You|Tú]] [[shouldn\'t|no deberías]] [[go|ir]] [[to work|a trabajar]] [[when|cuando]] [[you are ill|estás enfermo]].', words: ['[[You|Tú]]', '[[shouldn\'t|no deberías]]', '[[go|ir]]', '[[to work|a trabajar]]', '[[when|cuando]]', '[[you are ill|estás enfermo]].'] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Go|Ve]] [[to|a]] [[the|la]] [[pharmacy|farmacia]] [[for|para]] [[medicine|medicina]].', words: ['[[Go|Ve]]', '[[to|a]]', '[[the|la]]', '[[pharmacy|farmacia]]', '[[for|para]]', '[[medicine|medicina]].'] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Should|Should]] [[and|y]] [[shouldn\'t|shouldn\'t]] [[are followed by|van seguidos de]] [[base verb|verbo base]].', correctAnswer: true, explanation: 'You should see. You shouldn\'t go.' }] }, topicName: 'Grammar' },
  { id: 'a1-u58-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We use should|Usamos should]] [[to give|para dar]] [[health advice|consejos de salud]].', correctAnswer: true, explanation: 'You should rest. You shouldn\'t go out.' }] }, topicName: 'Grammar' },
];
