/**
 * Unidad 27 — Lección 2: Vocabulario (Pets, farm, wild animals)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Vocabulario: pets, farm, wild animals';
const TOPIC = 'Pets & Animals';

export const UNIT_27_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u27-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige. Animal de compañía.', questions: [{ question: '[[A|Un]] ____ [[lives|vive]] [[in|en]] [[your|tu]] [[house|casa]].', options: ['[[pet|mascota]]', '[[farm|granja]]', '[[wild|salvaje]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Dog|Perro]], [[cat|gato]], [[fish|pez]] [[are|son]] ____.', options: ['[[pets|mascotas]]', '[[farm animals|animales de granja]]', '[[wild animals|animales salvajes]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Cow|Vaca]], [[horse|caballo]], [[sheep|oveja]] [[live|viven]] [[on|en]] a ____.', options: ['[[farm|granja]]', '[[house|casa]]', '[[forest|bosque]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Lion|León]], [[tiger|tigre]], [[bear|oso]] [[are|son]] ____ [[animals|animales]].', options: ['[[wild|salvajes]]', '[[pets|mascotas]]', '[[farm|de granja]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige el adjetivo correcto.', questions: [{ question: '[[A|Un]] ____ [[animal|animal]] [[can|puede]] [[hurt|hacer daño]] [[you|te]].', options: ['[[dangerous|peligroso]]', '[[friendly|amigable]]', '[[cute|mono]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona palabra con significado.', pairs: [{ id: 'p1', left: '[[pet|mascota]]', right: '[[animal that lives with people|animal que vive con personas]]' }, { id: 'p2', left: '[[farm|granja]]', right: '[[place with cows, pigs, chickens|lugar con vacas, cerdos, gallinas]]' }, { id: 'p3', left: '[[wild|salvaje]]', right: '[[lives in nature|vive en la naturaleza]]' }, { id: 'p4', left: '[[cute|mono]]', right: '[[nice to look at|bonito de ver]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona animal con tipo.', pairs: [{ id: 'p1', left: '[[dog|perro]]', right: '[[pet|mascota]]' }, { id: 'p2', left: '[[pig|cerdo]]', right: '[[farm|granja]]' }, { id: 'p3', left: '[[wolf|lobo]]', right: '[[wild|salvaje]]' }, { id: 'p4', left: '[[rabbit|conejo]]', right: '[[pet or wild|mascota o salvaje]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|El]] [[zoo|zoo]] [[has|tiene]] ____ [[animals|animales]].', options: ['[[wild|salvajes]]', '[[pets|mascotas]]', '[[farm|de granja]]'], correctAnswer: 'wild', acceptableAnswers: ['wild'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[have|tengo]] [[a|un]] ____ [[cat|gato]]. [[It|Es]] [[is|muy]] [[very|]] [[friendly|amigable]].', options: ['[[pet|mascota]]', '[[wild|salvaje]]', '[[farm|granja]]'], correctAnswer: 'pet', acceptableAnswers: ['pet'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Chickens|Las gallinas]] [[and|y]] [[ducks|patos]] [[are|son]] ____ [[animals|animales]].', options: ['[[farm|de granja]]', '[[wild|salvajes]]', '[[pet|mascotas]]'], correctAnswer: 'farm', acceptableAnswers: ['farm'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Friendly|Amigable]] [[means|significa]] ____.', options: ['[[nice, kind|amable, simpático]]', '[[scary|asustadizo]]', '[[big|grande]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Dangerous|Peligroso]] [[means|significa]] ____.', options: ['[[can hurt you|puede hacerte daño]]', '[[very small|muy pequeño]]', '[[funny|gracioso]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Where|Dónde]] [[do|viven]] [[wild|salvajes]] [[animals|animales]] [[live|viven]]?', options: ['[[In the forest or jungle|En el bosque o la selva]]', '[[In a house|En una casa]]', '[[On a farm|En una granja]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v14', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[My|Mi]] [[pet|mascota]] [[is|es]] [[a|un]] [[friendly|amigable]] [[dog|perro]].', words: ['[[My|Mi]]', '[[pet|mascota]]', '[[is|es]]', '[[a|un]]', '[[friendly|amigable]]', '[[dog|perro]].'] }, topicName: 'Vocabulary' },
  { id: 'a1-u27-l2-v15', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Lions|Los leones]] [[are|son]] [[wild|salvajes]] [[and|y]] [[dangerous|peligrosos]].', words: ['[[Lions|Los leones]]', '[[are|son]]', '[[wild|salvajes]]', '[[and|y]]', '[[dangerous|peligrosos]].'] }, topicName: 'Vocabulary' },
];
