/**
 * Unidad 60 — Lección 2: Vocabulario (Module 6 Review)
 * Mix: supermarket, countable/uncountable, restaurant, cooking, health, money.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Repaso vocabulario Módulo 6';
const TOPIC = 'Module 6 Review';

export const UNIT_60_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u60-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Menu|Carta]] = ____.', options: ['[[list of food in restaurant|lista de comida en restaurante]]', '[[bill|cuenta]]', '[[starter|entrante]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Starter|Entrante]] = ____.', options: ['[[first course|primer plato]]', '[[main course|plato principal]]', '[[dessert|postre]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Cut|Cortar]] = ____.', options: ['[[use knife to divide|usar cuchillo para dividir]]', '[[mix|mezclar]]', '[[bake|hornear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Pharmacy|Farmacia]] = ____.', options: ['[[place to buy medicine|lugar para comprar medicina]]', '[[hospital|hospital]]', '[[doctor|médico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Receipt|Recibo]] = ____.', options: ['[[paper that shows what you paid|papel que muestra lo que pagaste]]', '[[change|cambio]]', '[[cash|efectivo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[main course|plato principal]]', right: '[[main dish|plato principal]]' }, { id: 'p2', left: '[[fry|freír]]', right: '[[cook in oil|cocinar en aceite]]' }, { id: 'p3', left: '[[headache|dolor de cabeza]]', right: '[[pain in head|dolor en cabeza]]' }, { id: 'p4', left: '[[pay for|pagar por]]', right: '[[give money for|dar dinero por]]' }, { id: 'p5', left: '[[change|cambio]]', right: '[[money back|dinero de vuelta]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[First, Then, Finally|First, Then, Finally]]', right: '[[order in recipe|orden en receta]]' }, { id: 'p2', left: '[[should|debería]]', right: '[[advice|consejo]]' }, { id: 'p3', left: '[[some/any|alguno/ninguno]]', right: '[[quantity|cantidad]]' }, { id: 'p4', left: '[[too/enough|demasiado/suficiente]]', right: '[[size or amount|talla o cantidad]]' }, { id: 'p5', left: '[[credit card|tarjeta de crédito]]', right: '[[pay without cash|pagar sin efectivo]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[For|Para]] ____ [[I would like|quisiera]] [[soup|sopa]].', options: ['[[starter|entrante]]', '[[main course|plato principal]]', '[[dessert|postre]]'], correctAnswer: 'starter', acceptableAnswers: ['starter'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You should|Deberías]] ____ [[medicine|medicina]] [[from|de]] [[the|la]] [[pharmacy|farmacia]].', options: ['[[take|tomar]]', '[[go|ir]]', '[[see|ver]]'], correctAnswer: 'take', acceptableAnswers: ['take'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I paid|Pagué]] ____ [[the|la]] [[bill|cuenta]] [[with|con]] [[cash|efectivo]].', options: ['[[for|por]]', '[[on|en]]', '[[at|en]]'], correctAnswer: 'for', acceptableAnswers: ['for'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Countable noun|Sustantivo contable]] = ____.', options: ['[[has plural (eggs, apples)|tiene plural]]', '[[no plural (milk, water)|sin plural]]', '[[always singular|siempre singular]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Bill|Cuenta]] = ____.', options: ['[[what you must pay|lo que debes pagar]]', '[[menu|carta]]', '[[receipt|recibo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Fever|Fiebre]] = ____.', options: ['[[high body temperature|temperatura corporal alta]]', '[[headache|dolor de cabeza]]', '[[cold|resfriado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Module 6|Módulo 6]] [[covers|incluye]] [[shopping|compras]], [[food|comida]], [[restaurant|restaurante]], [[cooking|recetas]], [[health|salud]], [[money|dinero]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
  { id: 'a1-u60-l2-v15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Spend on|Spend on]] [[means|significa]] [[use money on something|usar dinero en algo]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
];
