/**
 * Unidad 39 — Lección 3: Comprensión lectora (Outdoor Activities)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Outdoor Activities';
const READING_TRANSCRIPT = `[[I|Yo]] [['m|estoy]] [[going|camino]] [[camping|camping]] [[next week|la próxima semana]] [[with|con]] [[my|mi]] [[family|familia]]. [[We|Nosotros]] [[love|amamos]] [[outdoor|al aire libre]] [[activities|actividades]]. [[My|Mi]] [[brother|hermano]] [[is|está]] [[going|yendo]] [[hiking|senderismo]] [[on Saturday|el sábado]] [[and|y]] [[my|mi]] [[sister|hermana]] [[is|está]] [[going|yendo]] [[cycling|en bici]] [[on Sunday|el domingo]]. [[My|Mi]] [[dad|padre]] [[is|está]] [[going|yendo]] [[fishing|pesca]] [[tomorrow|mañana]]. [[We|Nosotros]] [[have|tenemos]] [[a|una]] [[tent|tienda]] [[and|y]] [[backpacks|mochilas]]. [[Next weekend|El próximo fin de semana]] [[we|nosotros]] [[are|estamos]] [[all|todos]] [[going|yendo]] [[to the mountains|a la montaña]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_39_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u39-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[the writer|el autor]] [[going|yendo]] [[to do|a hacer]] [[next week|la próxima semana]]?', options: ['[[Going camping|Ir de camping]]', '[[Going hiking|Ir de senderismo]]', '[[Going fishing|Ir a pescar]]'], correctAnswer: 0, explanation: "I'm going camping next week." }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Who|Con quién]] [[is|va]] [[he/she|va]] [[going|camino]] [[camping|camping]]?', options: ['[[With family|Con la familia]]', '[[Alone|Solo]]', '[[With friends|Con amigos]]'], correctAnswer: 0, explanation: 'With my family.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[the brother|el hermano]] [[going|yendo]] [[to do|a hacer]] [[on Saturday|el sábado]]?', options: ['[[Going hiking|Ir de senderismo]]', '[[Going cycling|Ir en bici]]', '[[Going fishing|Ir a pescar]]'], correctAnswer: 0, explanation: 'My brother is going hiking on Saturday.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|está]] [[the sister|la hermana]] [[going|yendo]] [[to do|a hacer]] [[on Sunday|el domingo]]?', options: ['[[Going cycling|Ir en bici]]', '[[Going hiking|Ir de senderismo]]', '[[Going camping|Ir de camping]]'], correctAnswer: 0, explanation: 'My sister is going cycling on Sunday.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[is|está]] [[dad|el padre]] [[going|yendo]] [[fishing|pesca]]?', options: ['[[Tomorrow|Mañana]]', '[[Next week|La próxima semana]]', '[[On Sunday|El domingo]]'], correctAnswer: 0, explanation: 'My dad is going fishing tomorrow.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[do they have|tienen]] [[for camping|para camping]]?', options: ['[[A tent and backpacks|Una tienda y mochilas]]', '[[A car only|Solo un coche]]', '[[Nothing|Nada]]'], correctAnswer: 0, explanation: 'We have a tent and backpacks.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[are they going|van]] [[next weekend|el próximo fin de semana]]?', options: ['[[To the mountains|A la montaña]]', '[[To the beach|A la playa]]', '[[To the city|A la ciudad]]'], correctAnswer: 0, explanation: 'We are all going to the mountains.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]]?', options: ['[[Outdoor activities and future plans|Actividades al aire libre y planes futuros]]', '[[School|Colegio]]', '[[Work|Trabajo]]'], correctAnswer: 0, explanation: 'Camping, hiking, cycling, fishing.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[senderismo|senderismo]]"?', options: ['[[Hiking|Hiking]]', '[[Camping|Camping]]', '[[Fishing|Fishing]]'], correctAnswer: 0, explanation: 'Hiking = senderismo.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[outdoor|al aire libre]] [[activities|actividades]].', options: ['[[love|aman]]', '[[loves|ama]]', '[[loving|amando]]'], correctAnswer: 0, explanation: 'We love outdoor activities.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Backpack|Mochila]] = ____.', options: ['[[bag for carrying on back|bolsa para llevar a la espalda]]', '[[tent|tienda]]', '[[bike|bici]]'], correctAnswer: 0, explanation: 'Backpack = mochila.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text uses|El texto usa]] ____ [[for future plans|para planes futuros]].', options: ["[[I'm going / He is going|I'm going / He is going]]", '[[I go / He goes|I go / He goes]]', '[[I went|I went]]'], correctAnswer: 0, explanation: 'Present continuous for plans.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[phrase|frase]] [[means|significa]] "[[el próximo fin de semana|el próximo fin de semana]]"?', options: ['[[Next weekend|Next weekend]]', '[[Next week|Next week]]', '[[Tomorrow|Tomorrow]]'], correctAnswer: 0, explanation: 'Next weekend = próximo fin de semana.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How many|Cuántas]] [[outdoor activities|actividades al aire libre]] [[are mentioned|se mencionan]]?', options: ['[[Four (camping, hiking, cycling, fishing)|Cuatro]]', '[[Two|Dos]]', '[[Three|Tres]]'], correctAnswer: 0, explanation: 'Camping, hiking, cycling, fishing.' }] }, topicName: 'Reading' },
  { id: 'a1-u39-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Outdoor|Al aire libre]] = ____.', options: ['[[outside, in nature|fuera, en la naturaleza]]', '[[inside|dentro]]', '[[in the city|en la ciudad]]'], correctAnswer: 0, explanation: 'Outdoor = al aire libre.' }] }, topicName: 'Reading' },
];
