/**
 * Unidad 32 — Lección 6: Expresión escrita (Sports & Hobbies)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Sports & Hobbies';

export const UNIT_32_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u32-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[football|fútbol]] [[on|los]] [[Saturdays|sábados]].', options: ['[[play|juego a]]', '[[go|voy]]', '[[do|hago]]'], correctAnswer: 'play', acceptableAnswers: ['play'] }] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] ____ [[swimming|a nadar]] [[every|cada]] [[week|semana]].', options: ['[[goes|va]]', '[[plays|juega]]', '[[does|hace]]'], correctAnswer: 'goes', acceptableAnswers: ['goes'] }] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] ____ [[yoga|yoga]] [[in the morning|por la mañana]].', options: ['[[do|hacemos]]', '[[play|jugamos]]', '[[go|vamos]]'], correctAnswer: 'do', acceptableAnswers: ['do'] }] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] ____ [[tennis|tenis]] [[twice|dos]] [[a week|veces a la semana]].', options: ['[[plays|juega al]]', '[[goes|va]]', '[[does|hace]]'], correctAnswer: 'plays', acceptableAnswers: ['plays'] }] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[reading|leer]] [[and|y]] [[painting|pintar]].', options: ['[[like|me gusta]]', '[[play|juego]]', '[[go|voy]]'], correctAnswer: 'like', acceptableAnswers: ['like', 'enjoy'] }] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[I|Yo]] [[play|juego a]] [[football|fútbol]] [[and|y]] [[go|voy]] [[swimming|a nadar]].', words: ['[[I|Yo]]', '[[play|juego a]]', '[[football|fútbol]]', '[[and|y]]', '[[go|voy]]', '[[swimming|a nadar]].'] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[does|hace]] [[yoga|yoga]] [[every|cada]] [[morning|mañana]].', words: ['[[She|Ella]]', '[[does|hace]]', '[[yoga|yoga]]', '[[every|cada]]', '[[morning|mañana]].'] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[They|Ellos]] [[like|les gusta]] [[reading|leer]] [[and|y]] [[painting|pintar]].', words: ['[[They|Ellos]]', '[[like|les gusta]]', '[[reading|leer]]', '[[and|y]]', '[[painting|pintar]].'] }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: qué deporte practicas (play, go o do).', prompt: '____.', minWords: 5, maxWords: 15, modelExample: '[[I|Yo]] [[play|juego a]] [[football|fútbol]] [[every|cada]] [[Saturday|sábado]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: un hobby que te guste (reading, painting, etc.).', prompt: '____.', minWords: 4, maxWords: 12, modelExample: '[[I|Yo]] [[like|me gusta]] [[reading|leer]] [[and|y]] [[painting|pintar]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: un deporte con play, otro con go o do.', prompt: '____. ____.', minWords: 8, maxWords: 22, modelExample: '[[I|Yo]] [[play|juego a]] [[tennis|tenis]]. [[I|Yo]] [[go|voy]] [[swimming|a nadar]] [[once|una]] [[a week|vez a la semana]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe: What do you do in your free time? y tu respuesta.', prompt: '____? ____.', minWords: 6, maxWords: 20, modelExample: '[[What|Qué]] [[do|haces]] [[you|tú]] [[do|haces]] [[in your free time|en tu tiempo libre]]? [[I|Yo]] [[play|juego a]] [[football|fútbol]] [[and|y]] [[go|voy]] [[swimming|a nadar]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–5 frases): deportes y hobbies que practicas o te gustan.', prompt: '____.', minWords: 22, maxWords: 55, modelExample: '[[I|Yo]] [[play|juego a]] [[football|fútbol]] [[on|los]] [[Saturdays|sábados]]. [[I|Yo]] [[go|voy]] [[swimming|a nadar]] [[once|una]] [[a week|vez a la semana]]. [[I|Yo]] [[do|hago]] [[yoga|yoga]] [[sometimes|a veces]]. [[I|Yo]] [[like|me gusta]] [[reading|leer]] [[before|antes de]] [[bed|dormir]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 frases: play…, go…, do… (deportes o actividades).', prompt: '____. ____. ____.', minWords: 10, maxWords: 28, modelExample: '[[I|Yo]] [[play|juego a]] [[tennis|tenis]]. [[I|Yo]] [[go|voy]] [[swimming|a nadar]]. [[I|Yo]] [[do|hago]] [[yoga|yoga]].' }, topicName: 'Writing' },
  { id: 'a1-u32-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase sobre qué deporte o hobby hace alguien de tu familia.', prompt: '____.', minWords: 6, maxWords: 18, modelExample: '[[My|Mi]] [[sister|hermana]] [[does|hace]] [[yoga|yoga]] [[and|y]] [[likes|le gusta]] [[reading|leer]].' }, topicName: 'Writing' },
];
