/**
 * Unidad 54 — Lección 3: Comprensión lectora (How Much & How Many)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'How Much & How Many';
const READING_TRANSCRIPT = `[[I|Yo]] [[am|estoy]] [[at|en]] [[the|el]] [[market|mercado]]. [[I|Yo]] [[want|quiero]] [[to buy|comprar]] [[some|algo de]] [[fruit|fruta]] [[and|y]] [[vegetables|verduras]]. [[How much|Cuánto]] [[is|es]] [[the|la]] [[bread|pan]]? [[It|Eso]] [[costs|cuesta]] [[two|dos]] [[pounds|libras]]. [[How many|Cuántas]] [[oranges|naranjas]] [[do I need|necesito]]? [[Maybe|Quizás]] [[six|seis]]. [[How much|Cuánto]] [[water|agua]] [[do we have|tenemos]]? [[We have|Tenemos]] [[a lot|mucha]]. [[The|El]] [[total|total]] [[for|por]] [[my|mi]] [[shopping|compra]] [[is|es]] [[fifteen|quince]] [[pounds|libras]]. [[That is|Eso es]] [[not|no]] [[expensive|caro]]. [[The|La]] [[milk|leche]] [[costs|cuesta]] [[one|una]] [[pound|libra]] [[fifty|con cincuenta]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_54_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u54-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[is|está]] [[the writer|el autor]]?', options: ['[[At the market|En el mercado]]', '[[At home|En casa]]', '[[At a restaurant|En un restaurante]]'], correctAnswer: 0, explanation: 'I am at the market.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What does he/she want to buy|Qué quiere comprar]]?', options: ['[[Some fruit and vegetables|Algo de fruta y verduras]]', '[[Only bread|Solo pan]]', '[[Only milk|Solo leche]]'], correctAnswer: 0, explanation: 'I want to buy some fruit and vegetables.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much is the bread|Cuánto cuesta el pan]]?', options: ['[[Two pounds|Dos libras]]', '[[One pound|Una libra]]', '[[Fifteen pounds|Quince libras]]'], correctAnswer: 0, explanation: 'It costs two pounds.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How many oranges does he/she need|Cuántas naranjas necesita]]?', options: ['[[Maybe six|Quizás seis]]', '[[Two|Dos]]', '[[Fifteen|Quince]]'], correctAnswer: 0, explanation: 'Maybe six.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What is the total for the shopping|Cuál es el total de la compra]]?', options: ['[[Fifteen pounds|Quince libras]]', '[[Six pounds|Seis libras]]', '[[Two pounds|Dos libras]]'], correctAnswer: 0, explanation: 'The total for my shopping is fifteen pounds.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is the total expensive|Es caro el total]]?', options: ['[[No|No]]', '[[Yes|Sí]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0, explanation: 'That is not expensive.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much does the milk cost|Cuánto cuesta la leche]]?', options: ['[[One pound fifty|Una libra cincuenta]]', '[[One pound|Una libra]]', '[[Fifty pounds|Cincuenta libras]]'], correctAnswer: 0, explanation: 'The milk costs one pound fifty.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Do they have much water|Tienen mucha agua]]?', options: ['[[Yes, a lot|Sí, mucha]]', '[[No|No]]', '[[A little|Un poco]]'], correctAnswer: 0, explanation: 'We have a lot.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which question asks for price|Qué pregunta pide el precio]]?', options: ['[[How much is the bread?|How much is the bread?]]', '[[How many oranges?|How many oranges?]]', '[[How much water?|How much water?]]'], correctAnswer: 0, explanation: 'How much is… = precio.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Pound|Libra]] = ____.', options: ['[[British currency|moneda británica]]', '[[dollar|dólar]]', '[[euro|euro]]'], correctAnswer: 0, explanation: 'Pounds = libras.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[shopping, prices, how much/many|compras, precios, how much/many]]', '[[cooking|coser]]', '[[restaurant|restaurante]]'], correctAnswer: 0, explanation: 'Market, buy, how much, how many, total, costs.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Total|Total]] = ____.', options: ['[[all together, full amount|todo junto, cantidad total]]', '[[cheap|barato]]', '[[how many|cuántos]]'], correctAnswer: 0, explanation: 'Total = total.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expensive|Caro]] = ____.', options: ['[[costs a lot|cuesta mucho]]', '[[cheap|barato]]', '[[free|gratis]]'], correctAnswer: 0, explanation: 'Expensive = caro.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How many|How many]] [[is for|es para]] ____.', options: ['[[countable (oranges)|contables (naranjas)]]', '[[price|precio]]', '[[uncountable|incontables]]'], correctAnswer: 0, explanation: 'How many oranges.' }] }, topicName: 'Reading' },
  { id: 'a1-u54-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]]?', options: ['[[Shopping at market, prices, how much/many|Comprar en mercado, precios, how much/many]]', '[[Cooking|Cocinar]]', '[[At home|En casa]]'], correctAnswer: 0, explanation: 'Market, buy, how much, how many, total, costs.' }] }, topicName: 'Reading' },
];
