/**
 * Unidad 28 — Lección 3: Comprensión lectora (Body Parts)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Body Parts';
const READING_TRANSCRIPT = `[[My|Mi]] [[name|nombre]] [[is|es]] [[Tom|Tom]]. [[I|Yo]] [[have|tengo]] [[got|]] [[a|una]] [[head| cabeza]] [[and|y]] [[a|una]] [[face|cara]]. [[On|En]] [[my|mi]] [[face|cara]] [[I|tengo]] [[have|]] [[got|]] [[two|dos]] [[eyes|ojos]], [[a|una]] [[nose|nariz]] [[and|y]] [[a|una]] [[mouth|boca]]. [[I|Yo]] [[have|tengo]] [[got|]] [[two|dos]] [[arms|brazos]] [[and|y]] [[two|dos]] [[hands|manos]]. [[This|Esta]] [[is|es]] [[my|mi]] [[left|izquierda]] [[hand|mano]]. [[These|Estas]] [[are|son]] [[my|mis]] [[fingers|dedos]]. [[I|Yo]] [[have|tengo]] [[got|]] [[two|dos]] [[legs|piernas]] [[and|y]] [[two|dos]] [[feet|pies]]. [[My|Mi]] [[sister|hermana]] [[has|tiene]] [[got|]] [[long|largas]] [[legs|piernas]] [[and|y]] [[big|grandes]] [[blue|azules]] [[eyes|ojos]]. [[She|Ella]] [[is|es]] [[tall|alta]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_28_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u28-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[name|nombre]] [[of|del]] [[the|el]] [[writer|autor]]?', options: ['[[Tom|Tom]]', '[[Sister|Hermana]]', '[[Face|Cara]]'], correctAnswer: 0, explanation: 'My name is Tom.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[has|tiene]] [[Tom|Tom]] [[got|]] [[on|en]] [[his|su]] [[face|cara]]?', options: ['[[Two eyes, a nose, a mouth|Dos ojos, una nariz, una boca]]', '[[Two arms|Dos brazos]]', '[[Two feet|Dos pies]]'], correctAnswer: 0, explanation: 'On my face I have got two eyes, a nose and a mouth.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántos]] [[many|]] [[arms|brazos]] [[does|tiene]] [[Tom|Tom]] [[have|tiene]] [[got|]]?', options: ['[[Two|Dos]]', '[[One|Uno]]', '[[Three|Tres]]'], correctAnswer: 0, explanation: 'I have got two arms.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|significa]] [["This is my left hand"|"Esta es mi mano izquierda"]] [[mean|significa]]?', options: ['[[Esta es mi mano izquierda|This is my left hand]]', '[[Estas son mis piernas|These are my legs]]', '[[Tengo dos pies|I have got two feet]]'], correctAnswer: 0, explanation: 'This = esta (singular).' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[are|son]] [["These"|"Estas"]] [[in|en]] [[the|el]] [[text|texto]]?', options: ['[[My fingers|Mis dedos]]', '[[My legs|Mis piernas]]', '[[My eyes|Mis ojos]]'], correctAnswer: 0, explanation: 'These are my fingers.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántas]] [[many|]] [[legs|piernas]] [[and|y]] [[feet|pies]] [[does|tiene]] [[Tom|Tom]] [[have|tiene]] [[got|]]?', options: ['[[Two legs and two feet|Dos piernas y dos pies]]', '[[One leg and one foot|Una pierna y un pie]]', '[[Three legs|Tres piernas]]'], correctAnswer: 0, explanation: 'Two legs and two feet.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[has|tiene]] [[Tom\'s|la hermana de Tom]] [[sister|hermana]] [[got|]]?', options: ['[[Long legs and big blue eyes|Piernas largas y ojos azules grandes]]', '[[Short arms|Brazos cortos]]', '[[Small feet|Pies pequeños]]'], correctAnswer: 0, explanation: 'She has got long legs and big blue eyes.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is|Es]] [[Tom\'s|la hermana de Tom]] [[sister|hermana]] [[tall|alta]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0, explanation: 'She is tall.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[cabeza|cabeza]]"?', options: ['[[Head|Head]]', '[[Face|Face]]', '[[Hand|Hand]]'], correctAnswer: 0, explanation: 'Head = cabeza.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[pies|pies]]"?', options: ['[[Feet|Feet]]', '[[Legs|Legs]]', '[[Hands|Hands]]'], correctAnswer: 0, explanation: 'Feet = pies (plural de foot).' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Se]] [[use|usa]] ____ [[for|para]] [[singular|singular]] [[and|y]] ____ [[for|para]] [[plural|plural]] [[(body)|(cuerpo)]].', options: ['[[This / These|This / These]]', '[[That / Those|That / Those]]', '[[I / We|I / We]]'], correctAnswer: 0, explanation: 'This = este/esta, these = estos/estas.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Tom|Tom]] [[has|tiene]] [[got|]] ____ [[hands|manos]].', options: ['[[two|dos]]', '[[one|una]]', '[[three|tres]]'], correctAnswer: 0, explanation: 'Two hands.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[main|principal]] [[topic|tema]] [[is|es]] ____.', options: ['[[body parts and have got|partes del cuerpo y have got]]', '[[family|familia]]', '[[animals|animales]]'], correctAnswer: 0, explanation: 'Body parts with have/has got.' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[part|parte]] [[of|del]] [[the|el]] [[body|cuerpo]] [[has|tiene]] [[fingers|dedos]]?', options: ['[[Hands|Manos]]', '[[Feet|Pies]]', '[[Head|Cabeza]]'], correctAnswer: 0, explanation: 'These are my fingers (on hands).' }] }, topicName: 'Reading' },
  { id: 'a1-u28-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Se]] [[have got|usa have got]] [[for|para]] ____ [[possession|posesión]] [[and|y]] [[description|descripción]] [[of|del]] [[body|cuerpo]].', options: ['[[describing|describir]]', '[[eating|comer]]', '[[running|correr]]'], correctAnswer: 0, explanation: 'Have got for body description.' }] }, topicName: 'Reading' },
];
