/**
 * Unidad 48 — Lección 1: Gramática (Sightseeing)
 * Basic superlatives (the most famous, the oldest).
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Superlativos básicos';
const TOPIC = 'Sightseeing';

export const UNIT_48_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u48-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This is|Este es]] ____ [[famous|famoso]] [[monument|monumento]] [[in|en]] [[the|la]] [[city|ciudad]].', options: ['[[the most|el más]]', '[[the more|más]]', '[[most|más]]'], correctAnswer: 'the most', acceptableAnswers: ['the most'], explanation: 'Superlative: the most + adjective.' }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It is|Es]] ____ [[old|antiguo]] [[church|iglesia]] [[in|en]] [[town|el pueblo]].', options: ['[[the oldest|la más antigua]]', '[[the older|más antigua]]', '[[oldest|más antigua]]'], correctAnswer: 'the oldest', acceptableAnswers: ['the oldest'] }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[That|Ese]] [[is|es]] ____ [[big|grande]] [[museum|museo]] [[here|aquí]].', options: ['[[the biggest|el más grande]]', '[[the bigger|más grande]]', '[[biggest|más grande]]'], correctAnswer: 'the biggest', acceptableAnswers: ['the biggest'] }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We saw|Vimos]] ____ [[tall|alta]] [[statue|estatua]] [[in|en]] [[the square|la plaza]].', options: ['[[the tallest|la más alta]]', '[[the taller|más alta]]', '[[tallest|más alta]]'], correctAnswer: 'the tallest', acceptableAnswers: ['the tallest'] }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This|Esta]] [[is|es]] ____ [[beautiful|hermosa]] [[building|edificio]] [[in|en]] [[the|la]] [[city|ciudad]].', options: ['[[the most beautiful|la más hermosa]]', '[[the more beautiful|más hermosa]]', '[[most beautiful|más hermosa]]'], correctAnswer: 'the most beautiful', acceptableAnswers: ['the most beautiful'] }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Superlative|Superlativo]] = ____.', options: ['[[the most / the -est (the best)|el más / el -est]]', '[[more / -er|más / -er]]', '[[present|presente]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Famous|Famoso]] → [[superlative|superlativo]] = ____.', options: ['[[the most famous|el más famoso]]', '[[the famousest|incorrecto]]', '[[the more famous|más famoso]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Old|Antiguo]] → [[superlative|superlativo]] = ____.', options: ['[[the oldest|el más antiguo]]', '[[the most old|incorrecto]]', '[[the older|más antiguo]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We use|Usamos]] ____ [[before|antes de]] [[superlative adjectives|adjetivos en superlativo]].', options: ['[[the|the]]', '[[a|a]]', '[[no article|sin artículo]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[The most famous|El más famoso]] [[monument|monumento]] = ____.', options: ['[[the monument that is most famous|el monumento que es más famoso]]', '[[a monument|un monumento]]', '[[the only monument|el único monumento]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[This is|Este es]] [[the|el]] [[most|más]] [[famous|famoso]] [[monument|monumento]] [[in|en]] [[the city|la ciudad]].', words: ['[[This is|Este es]]', '[[the|el]]', '[[most|más]]', '[[famous|famoso]]', '[[monument|monumento]]', '[[in|en]]', '[[the city|la ciudad]].'] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It is|Es]] [[the|la]] [[oldest|más antigua]] [[church|iglesia]] [[in|en]] [[town|el pueblo]].', words: ['[[It is|Es]]', '[[the|la]]', '[[oldest|más antigua]]', '[[church|iglesia]]', '[[in|en]]', '[[town|el pueblo]].'] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[We|Nosotros]] [[did|hicimos]] [[a|una]] [[guided tour|visita guiada]] [[of|de]] [[the museum|el museo]].', words: ['[[We|Nosotros]]', '[[did|hicimos]]', '[[a|una]]', '[[guided tour|visita guiada]]', '[[of|de]]', '[[the museum|el museo]].'] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Superlatives|Superlativos]] [[compare|comparan]] [[one thing|una cosa]] [[with all others|con todas las demás]] ([[the most famous|el más famoso]], [[the oldest|el más antiguo]]).', correctAnswer: true, explanation: 'The most, the -est.' }] }, topicName: 'Grammar' },
  { id: 'a1-u48-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Long adjectives|Adjetivos largos]] [[use|usan]] [[the most|the most]] ([[the most beautiful|el más hermoso]]); [[short adjectives|adjetivos cortos]] [[use|usan]] [[the -est|the -est]] ([[the oldest|el más antiguo]]).', correctAnswer: true, explanation: 'Most + long adjective; -est for short.' }] }, topicName: 'Grammar' },
];
