/**
 * Unidad 12 — Lección 3: Comprensión lectora
 * 15 ejercicios: texto sobre agenda / qué haces cada día de la semana.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Days of the Week';

const READING_TRANSCRIPT = `[[My|Mi]] [[name|nombre]] [[is|es]] [[Paul|Paul]]. [[On|Los]] [[Monday|lunes]] [[and|y]] [[Wednesday|miércoles]] [[I|yo]] [[work|trabajo]] [[from|de]] [[nine|nueve]] [[to|a]] [[five|cinco]]. [[On|Los]] [[Tuesday|martes]] [[and|y]] [[Thursday|jueves]] [[I|yo]] [[have|tengo]] [[English|inglés]] [[class|clase]] [[in|por]] [[the|la]] [[evening|tarde]]. [[On|El]] [[Friday|viernes]] [[I|yo]] [[finish|termino]] [[early|pronto]] [[and|y]] [[meet|quedo]] [[my|con mis]] [[friends|amigos]]. [[On|El]] [[weekend|fin de semana]] [[I|yo]] [[don't|no]] [[work|trabajo]]. [[On|El]] [[Saturday|sábado]] [[I|yo]] [[go|voy]] [[shopping|de compras]] [[or|o]] [[run|corro]]. [[On|El]] [[Sunday|domingo]] [[I|yo]] [[rest|descanso]] [[at|en]] [[home|casa]]. [[I|Yo]] [[like|me gusta]] [[my|mi]] [[week|semana]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_12_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u12-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[writer\'s|del autor]] [[name|nombre]]?', options: ['[[Paul|Paul]]', '[[Peter|Peter]]', '[[John|John]]'], correctAnswer: 0, explanation: 'My name is Paul.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|Los]] ____ [[does|trabaja]] [[he|él]] [[work|trabajar]] [[from|de]] [[nine|nueve]] [[to|a]] [[five|cinco]]?', options: ['[[Monday and Wednesday|Lunes y miércoles]]', '[[Tuesday and Thursday|Martes y jueves]]', '[[Friday|Viernes]]'], correctAnswer: 0, explanation: 'On Monday and Wednesday I work from nine to five.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[does|tiene]] [[he|él]] [[have|clase]] [[English|de inglés]] [[class|clase]]?', options: ['[[Monday and Wednesday|Lunes y miércoles]]', '[[Tuesday and Thursday|Martes y jueves]]', '[[On the weekend|El fin de semana]]'], correctAnswer: 1, explanation: 'On Tuesday and Thursday I have English class.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|El]] [[Friday|viernes]] [[he|él]] ____.', options: ['[[works late|trabaja hasta tarde]]', '[[finishes early and meets friends|termina pronto y queda con amigos]]', '[[has class|tiene clase]]'], correctAnswer: 1, explanation: 'On Friday I finish early and meet my friends.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|Trabaja]] [[he|él]] [[work|Paul]] [[on|el]] [[weekend|fin de semana]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The text doesn\'t say|El texto no lo dice]]'], correctAnswer: 1, explanation: 'On the weekend I don\'t work.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|El]] [[Saturday|sábado]] [[he|él]] [[goes|va]] [[shopping|de compras]] [[or|o]] [[runs|corre]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: 'On Saturday I go shopping or run.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|El]] [[Sunday|domingo]] [[he|él]] [[works|trabaja]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'False', explanation: 'On Sunday I rest at home.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] [[likes|le gusta]] [[his|su]] [[week|semana]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: 'I like my week.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[English|Inglés]] [[class|clase]] [[is|es]] [[in|por]] ____.', options: ['[[the morning|la mañana]]', '[[the evening|la tarde]]', '[[the night|la noche]]'], correctAnswer: 1, explanation: 'I have English class in the evening.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]] [[of|del]] [[text|texto]]?', options: ['[[What the writer does each day of the week|Qué hace el autor cada día de la semana]]', '[[A job|Un trabajo]]', '[[Food|Comida]]'], correctAnswer: 0, explanation: 'Habla de su agenda por días.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[does|descansa]] [[he|él]] [[rest|Paul]] [[on|el]] [[Sunday|domingo]]?', options: ['[[At home|En casa]]', '[[At work|En el trabajo]]', '[[In the gym|En el gimnasio]]'], correctAnswer: 0, explanation: 'On Sunday I rest at home.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántos]] [[many|días]] [[days|trabaja]] [[does|él]] [[he|trabajar]] [[work|(al trabajo)]]?', options: ['[[Two|Dos]]', '[[Four|Cuatro]]', '[[Seven|Siete]]'], correctAnswer: 0, explanation: 'On Monday and Wednesday I work. So two days.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|El]] [[Friday|viernes]] [[he|él]] ____ [[his|con sus]] [[friends|amigos]].', options: ['[[meets|queda]]', '[[meet|quedar]]', '[[meeting|quedando]]'], correctAnswer: 0, explanation: 'He meets his friends. Third person -s.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|hace]] [[Paul|Paul]] [[do|hace]] [[on|el]] [[Tuesday|martes]]?', options: ['[[He has English class.|Tiene clase de inglés.]]', '[[He works.|Trabaja.]]', '[[He goes shopping.|Va de compras.]]'], correctAnswer: 0, explanation: 'On Tuesday I have English class.' }] }, topicName: 'Reading' },
  { id: 'a1-u12-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[On|El]] [[Saturday|sábado]] [[he|él]] [[doesn\'t|no]] ____.', options: ['[[rest|descansar]]', '[[work|trabajar]]', '[[go shopping|ir de compras]]'], correctAnswer: 1, explanation: 'On the weekend I don\'t work. So on Saturday he doesn\'t work.' }] }, topicName: 'Reading' },
];
