/**
 * Unidad 50 — Lección 1: Gramática (Module 5 Review)
 * Review: by/take the, It is (weather), was/were, superlatives, need to.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Repaso gramática Módulo 5';
const TOPIC = 'Module 5 Review';

export const UNIT_50_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u50-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[train|tren]] [[to|a]] [[London|Londres]].', options: ['[[take the|cojo el]]', '[[by the|por el]]', '[[take|cojo]]'], correctAnswer: 'take the', acceptableAnswers: ['take the'], explanation: 'Take the + transport.' }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] ____ [[bus|autobús]] [[to|a]] [[the airport|el aeropuerto]].', options: ['[[go by|vamos en]]', '[[go by the|vamos en el]]', '[[take|tomamos]]'], correctAnswer: 'go by', acceptableAnswers: ['go by'] }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It|Está]] ____ [[sunny|soleado]] [[today|hoy]].', options: ['[[is|está]]', '[[are|están]]', '[[was|estuvo]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[on|en]] [[the|la]] [[beach|playa]] [[last week|la semana pasada]].', options: ['[[was|estuve]]', '[[were|estuvieron]]', '[[am|estoy]]'], correctAnswer: 'was', acceptableAnswers: ['was'] }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This is|Este es]] ____ [[most famous|más famoso]] [[monument|monumento]] [[in|en]] [[the city|la ciudad]].', options: ['[[the|el]]', '[[a|un]]', '[[this|este]]'], correctAnswer: 'the', acceptableAnswers: ['the'] }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g6', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[pack|hacer la maleta]] [[my|mi]] [[suitcase|maleta]] [[tonight|esta noche]].', options: ['[[need to|necesito]]', '[[need|necesito]]', '[[needs to|necesita]]'], correctAnswer: 'need to', acceptableAnswers: ['need to'] }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Correct|Correcto]]: ____.', options: ['[[I go by bus|voy en autobús]]', '[[I go by the bus|incorrecto]]', '[[I take bus|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Weather|Tiempo]]: ____ [[sunny|soleado]].', options: ['[[It is|Está]]', '[[There is|Hay]]', '[[Is it|¿Está]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Past of|Pasado de]] [[is/am|is/am]] = ____.', options: ['[[was|was]]', '[[were|were]]', '[[is|is]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Superlative|Superlativo]]: ____ [[famous|famoso]].', options: ['[[the most|el más]]', '[[more|más]]', '[[most|más]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[take the|cojo el]] [[train|tren]] [[to|a]] [[work|trabajo]].', words: ['[[I|Yo]]', '[[take the|cojo el]]', '[[train|tren]]', '[[to|a]]', '[[work|trabajo]].'] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It is|Está]] [[hot|caluroso]] [[in|en]] [[summer|verano]].', words: ['[[It is|Está]]', '[[hot|caluroso]]', '[[in|en]]', '[[summer|verano]].'] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[We|Nosotros]] [[were|estuvimos]] [[in|en]] [[the mountains|las montañas]] [[last year|el año pasado]].', words: ['[[We|Nosotros]]', '[[were|estuvimos]]', '[[in|en]]', '[[the mountains|las montañas]]', '[[last year|el año pasado]].'] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[We say|Decimos]] [[take the train|take the train]], [[take the bus|take the bus]]; [[we say|decimos]] [[go by car|go by car]], [[go by plane|go by plane]].', correctAnswer: true, explanation: 'Take the + train/bus; go by + car/plane.' }] }, topicName: 'Grammar' },
  { id: 'a1-u50-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Need to|Need to]] [[and|y]] [[don\'t need to|don\'t need to]] [[are followed by|van seguidos de]] [[base verb|verbo base]].', correctAnswer: true, explanation: 'I need to pack. You don\'t need to take.' }] }, topicName: 'Grammar' },
];
