/**
 * Unidad 15 — Lección 5: Expresión oral
 * 15 ejercicios: Does he/she/it…? Yes he does / No she doesn't; describir rutina de alguien.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión oral';
const TOPIC = 'Present Simple: He, She, It';

export const UNIT_15_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a1-u15-l5-s1', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[Does|¿]] [[he|él]] [[get up|se levanta]] [[early|temprano]]? [[Yes|Sí]], [[he|él]] [[does|sí]].', expectedResponse: 'Does he get up early? Yes, he does.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s2', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[doesn\'t|no]] [[like|le gusta]] [[cooking|cocinar]].', expectedResponse: 'She doesn\'t like cooking.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s3', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Does|¿]] [[she|ella]] [[work|trabaja]] [[on|los]] [[Saturdays|sábados]]? [[No|No]], [[she|ella]] [[doesn\'t|no]].', expectedResponse: 'Does she work on Saturdays? No, she doesn\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s4', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[brother|hermano]] [[goes|va]] [[to bed|a la cama]] [[at|a]] [[ten|diez]].', expectedResponse: 'My brother goes to bed at ten.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s5', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[The|El]] [[dog|perro]] [[barks|ladra]] [[when|cuando]] [[it|él]] [[sees|ve]] [[a|un]] [[stranger|desconocido]].', expectedResponse: 'The dog barks when it sees a stranger.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s6', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[Does|¿]] [[your|tu]] [[mother|madre]] [[work|trabaja]]? [[Yes|Sí]], [[she|ella]] [[does|sí]].', expectedResponse: 'Does your mother work? Yes, she does.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s7', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[He|Él]] [[doesn\'t|no]] [[watch|ve]] [[TV|la tele]] [[in|por]] [[the|la]] [[morning|mañana]].', expectedResponse: 'He doesn\'t watch TV in the morning.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s8', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta. ¿Tu hermana cocina? (sí o no).', targetText: '[[Does|¿]] [[your|tu]] ____ ____? ____.', expectedResponse: 'Does your sister cook? Yes, she does. / No, she doesn\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s9', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta dos frases sobre la rutina de un familiar (él/ella + verbo con -s).', targetText: '____ ____. ____ ____.', expectedResponse: 'He/She gets up at... He/She works...' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s10', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Haz la pregunta "Does he work on Sunday?" y responde (No, he doesn\'t).', targetText: '____? ____.', expectedResponse: 'Does he work on Sunday? No, he doesn\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s11', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Describe en voz alta la rutina de una persona (3–4 frases: he/she + verbo con -s).', targetText: '____. ____. ____.', expectedResponse: 'She gets up at seven. She has breakfast. She goes to work.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s12', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta la descripción modelo.', targetText: '[[My|Mi]] [[sister|hermana]] [[gets up|se levanta]] [[at|a]] [[seven|siete]]. [[She|Ella]] [[has|toma]] [[breakfast|desayuno]] [[and|y]] [[goes|va]] [[to|a]] [[work|trabajo]] [[at|a]] [[eight|ocho]].', expectedResponse: 'My sister gets up at seven. She has breakfast and goes to work at eight.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s13', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The|El]] [[cat|gato]] [[likes|le gusta]] [[milk|leche]]. [[It|Él]] [[drinks|bebe]] [[it|la]] [[every|todas las]] [[day|días]].', expectedResponse: 'The cat likes milk. It drinks it every day.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s14', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Pregunta en voz alta si él/ella trabaja los domingos y responde.', targetText: '____? ____.', expectedResponse: 'Does he/she work on Sundays? No, he/she doesn\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u15-l5-s15', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe la rutina de alguien en 4–5 frases (he/she, gets up, has breakfast, works, goes to bed).', targetText: '____. ____. ____. ____.', expectedResponse: 'He/She gets up at... He/She has breakfast... He/She works... He/She goes to bed at...' }, topicName: 'Speaking' },
];
