/**
 * Unidad 55 — Lección 4: Comprensión auditiva (Clothing Store)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Clothing Store';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[Do you have|Tienen]] [[this|esta]] [[in|en]] [[size|talla]] [[L|L]]? [[B|B]]: [[Yes|Sí]], [[here you are|aquí tiene]]. [[A|A]]: [[Where is|Dónde está]] [[the|el]] [[changing room|probador]]? [[B|B]]: [[Over there|Por allí]]. [[A|A]]: [[This|Esta]] [[is|es]] [[too|demasiado]] [[small|pequeña]]. [[Do you have|Tienen]] [[it|la]] [[in|en]] [[XL|XL]]? [[B|B]]: [[Yes|Sí]]. [[Try this|Pruebe esta]]. [[A|A]]: [[It\'s|Es]] [[big|grande]] [[enough|suficiente]] [[now|ahora]]. [[I\'ll take|Me llevo]] [[it|la]]. [[Is it|Está]] [[on|en]] [[sale|rebajas]]? [[B|B]]: [[Yes|Sí]], [[twenty|veinte]] [[pounds|libras]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_55_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u55-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What size does A ask for first|Qué talla pide A primero]]?', options: ['[[Size L|Talla L]]', '[[Size M|Talla M]]', '[[Size XL|Talla XL]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where is the changing room|Dónde está el probador]]?', options: ['[[Over there|Por allí]]', '[[Here|Aquí]]', '[[At the back|Al fondo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is size L too big or too small|La talla L es demasiado grande o pequeña]]?', options: ['[[Too small|Demasiado pequeña]]', '[[Too big|Demasiado grande]]', '[[Just right|Perfecta]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What size does A try next|Qué talla prueba después]]?', options: ['[[XL|XL]]', '[[L|L]]', '[[M|M]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is XL big enough|La XL es suficientemente grande]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does A buy it|La compra A]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[Maybe|Quizás]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is it on sale|Está en rebajas]]?', options: ['[[Yes, twenty pounds|Sí, veinte libras]]', '[[No|No]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[is at|está en]] ____.', options: ['[[a clothing store|una tienda de ropa]]', '[[a supermarket|un supermercado]]', '[[a restaurant|un restaurante]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Too small|Demasiado pequeña]] = ____.', options: ['[[not big enough|no suficientemente grande]]', '[[too big|demasiado grande]]', '[[just right|perfecta]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Big enough|Suficientemente grande]] = ____.', options: ['[[it fits|queda bien]]', '[[too small|demasiado pequeña]]', '[[too big|demasiado grande]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Changing room|Probador]] = ____.', options: ['[[place to try on clothes|lugar para probarse ropa]]', '[[sale|rebajas]]', '[[cash desk|caja]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I\'ll take it|Me llevo]] = ____.', options: ['[[I will buy it|la compro]]', '[[I don\'t want it|no la quiero]]', '[[I need another size|necesito otra talla]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Sale|Rebajas]] = ____.', options: ['[[reduced prices|precios reducidos]]', '[[closed|cerrado]]', '[[new|nuevo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Size L, XL|Talla L, XL]] = ____.', options: ['[[large, extra large|grande, extra grande]]', '[[small|pequeña]]', '[[medium|mediana]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u55-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[is about|trata de]] ____.', options: ['[[trying clothes, sizes, too/enough, buying|probar ropa, tallas, too/enough, comprar]]', '[[cooking|coser]]', '[[eating|comer]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
