/**
 * Unidad 46 — Lección 2: Vocabulario (At the Hotel)
 * reception, room service, single/double room, key.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Vocabulario: hotel';
const TOPIC = 'At the Hotel';

export const UNIT_46_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u46-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Reception|Recepción]] = ____.', options: ['[[desk where you check in|mostrador donde haces check-in]]', '[[your room|tu habitación]]', '[[the key|la llave]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Room service|Servicio de habitaciones]] = ____.', options: ['[[food or help to your room|comida o ayuda a tu habitación]]', '[[reception|recepción]]', '[[the lobby|el vestíbulo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Single room|Habitación individual]] = ____.', options: ['[[room for one person|habitación para una persona]]', '[[room for two|habitación para dos]]', '[[key|llave]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Double room|Habitación doble]] = ____.', options: ['[[room for two people, often one bed|habitación para dos, a menudo una cama]]', '[[single room|habitación individual]]', '[[reception|recepción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Key|Llave]] = ____.', options: ['[[you use it to open your room|la usas para abrir tu habitación]]', '[[room service|servicio de habitaciones]]', '[[reception|recepción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[reception|recepción]]', right: '[[check in, get key|hacer check-in, obtener llave]]' }, { id: 'p2', left: '[[room service|servicio de habitaciones]]', right: '[[order food to room|pedir comida a la habitación]]' }, { id: 'p3', left: '[[single room|habitación individual]]', right: '[[one person|una persona]]' }, { id: 'p4', left: '[[double room|habitación doble]]', right: '[[two people|dos personas]]' }, { id: 'p5', left: '[[key|llave]]', right: '[[open the room|abrir la habitación]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[hotel|hotel]]', right: '[[place to stay|lugar para quedarse]]' }, { id: 'p2', left: '[[available|disponible]]', right: '[[free, free to use|libre]]' }, { id: 'p3', left: '[[check in|registrarse]]', right: '[[arrive at hotel|llegar al hotel]]' }, { id: 'p4', left: '[[booking|reserva]]', right: '[[reservation|reservación]]' }, { id: 'p5', left: '[[lobby|vestíbulo]]', right: '[[entrance area|área de entrada]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[need|necesito]] [[a|una]] ____ [[for|para]] [[room|habitación]] [[seven|siete]].', options: ['[[key|llave]]', '[[reception|recepción]]', '[[room service|servicio de habitaciones]]'], correctAnswer: 'key', acceptableAnswers: ['key'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Go|Ve]] [[to|a]] ____ [[to|para]] [[check in|hacer check-in]].', options: ['[[reception|recepción]]', '[[key|llave]]', '[[double room|habitación doble]]'], correctAnswer: 'reception', acceptableAnswers: ['reception'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Can|Puedo]] [[I|yo]] [[have|tener]] [[a|una]] ____ [[room|habitación]] [[for|para]] [[two|dos]] [[people|personas]]?', options: ['[[double|doble]]', '[[single|individual]]', '[[key|llave]]'], correctAnswer: 'double', acceptableAnswers: ['double'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Available|Disponible]] = ____.', options: ['[[free, you can use it|libre, puedes usarlo]]', '[[closed|cerrado]]', '[[full|lleno]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Check in|Registrarse]] = ____.', options: ['[[register when you arrive at hotel|registrarte al llegar al hotel]]', '[[leave the hotel|salir del hotel]]', '[[order food|pedir comida]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Where|Dónde]] [[do you get|obtienes]] [[your key|tu llave]]?', options: ['[[At reception|En recepción]]', '[[In your room|En tu habitación]]', '[[At room service|En servicio de habitaciones]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Room service|Room service]] [[brings|trae]] [[food or drinks|comida o bebidas]] [[to|a]] [[your room|tu habitación]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
  { id: 'a1-u46-l2-v15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[A single room|Una habitación individual]] [[is for|es para]] [[one person|una persona]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
];
