/**
 * Unidad 55 — Lección 6: Expresión escrita (Clothing Store)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Clothing Store';

export const UNIT_55_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u55-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This|Esta]] [[shirt|camisa]] [[is|es]] ____ [[big|grande]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[not|no]]'], correctAnswer: 'too', acceptableAnswers: ['too'] }] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[It isn\'t|No es]] ____ [[enough|suficiente]].', options: ['[[big|grande]]', '[[too|demasiado]]', '[[small|pequeño]]'], correctAnswer: 'big', acceptableAnswers: ['big'] }] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Do you have|Tienen]] [[this|esta]] [[in|en]] ____ [[M|M]]?', options: ['[[size|talla]]', '[[sale|rebajas]]', '[[changing room|probador]]'], correctAnswer: 'size', acceptableAnswers: ['size'] }] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Where is|Dónde está]] [[the|el]] ____ [[room|probador]]?', options: ['[[changing|probador]]', '[[sale|rebajas]]', '[[big|grande]]'], correctAnswer: 'changing', acceptableAnswers: ['changing'] }] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|Los]] [[trousers|pantalones]] [[are|son]] ____ [[small|pequeños]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[size|talla]]'], correctAnswer: 'too', acceptableAnswers: ['too'] }] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[This|Esta]] [[shirt|camisa]] [[is|es]] [[too|demasiado]] [[big|grande]].', words: ['[[This|Esta]]', '[[shirt|camisa]]', '[[is|es]]', '[[too|demasiado]]', '[[big|grande]].'] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[It isn\'t|No es]] [[big|grande]] [[enough|suficiente]].', words: ['[[It isn\'t|No es]]', '[[big|grande]]', '[[enough|suficiente]].'] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Where is|Dónde está]] [[the|el]] [[changing room|probador]]?', words: ['[[Where is|Dónde está]]', '[[the|el]]', '[[changing room|probador]]?'] }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: esta camisa es demasiado grande (too big).', prompt: '____.', minWords: 5, maxWords: 8, modelExample: '[[This|Esta]] [[shirt|camisa]] [[is|es]] [[too|demasiado]] [[big|grande]].' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: no es suficientemente grande (not big enough).', prompt: '____.', minWords: 4, maxWords: 6, modelExample: '[[It isn\'t|No es]] [[big|grande]] [[enough|suficiente]].' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: preguntar si tienen talla M y dónde está el probador.', prompt: '____? ____?', minWords: 10, maxWords: 18, modelExample: '[[Do you have|Tienen]] [[this|esta]] [[in|en]] [[size|talla]] [[M|M]]? [[Where is|Dónde está]] [[the|el]] [[changing room|probador]]?' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe: decir que es demasiado pequeña y pedir talla L.', prompt: '____. ____.', minWords: 8, maxWords: 16, modelExample: '[[This|Esta]] [[is|es]] [[too|demasiado]] [[small|pequeña]]. [[Do you have|Tienen]] [[it|la]] [[in|en]] [[size|talla]] [[L|L]]?' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3–4 frases): en una tienda de ropa, probarte algo, too big / not big enough, talla, probador, comprar.', prompt: '____.', minWords: 25, maxWords: 55, modelExample: '[[I|Yo]] [[am|estoy]] [[at|en]] [[the|la]] [[clothing store|tienda de ropa]]. [[I try|Pruebo]] [[a|una]] [[shirt|camisa]] [[in|en]] [[size|talla]] [[M|M]]. [[It is|Es]] [[too|demasiado]] [[big|grande]]. [[I need|Necesito]] [[size|talla]] [[S|S]]. [[It is|Es]] [[big|grande]] [[enough|suficiente]] [[now|ahora]]. [[I buy|Compro]] [[it|la]].' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases: diferencia too big y not big enough con ejemplos.', prompt: '____.', minWords: 12, maxWords: 28, modelExample: '[[This|Esta]] [[shirt|camisa]] [[is|es]] [[too|demasiado]] [[big|grande]]. [[That one|Esa]] [[isn\'t|no es]] [[big|grande]] [[enough|suficiente]].' }, topicName: 'Writing' },
  { id: 'a1-u55-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe: preguntar talla (S, M, L, XL), probador y si está en rebajas.', prompt: '____.', minWords: 12, maxWords: 25, modelExample: '[[Do you have|Tienen]] [[this|esta]] [[in|en]] [[size|talla]] [[L|L]]? [[Where is|Dónde está]] [[the|el]] [[changing room|probador]]? [[Is it|Está]] [[on|en]] [[sale|rebajas]]?' }, topicName: 'Writing' },
];
