/**
 * Unidad 60 — Lección 4: Comprensión auditiva (Module 6 Review)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Module 6 Review';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[I would like|Quisiera]] [[the|la]] [[chicken|pollo]] [[for|para]] [[main course|plato principal]] [[please|por favor]]. [[B|B]]: [[Anything else?|¿Algo más?]] [[A|A]]: [[Can I have|Puedo tener]] [[the|la]] [[bill|cuenta]] [[please|por favor]]? [[I paid|Pagué]] [[for|por]] [[dinner|la cena]] [[with|con]] [[cash|efectivo]] [[yesterday|ayer]] [[but|pero]] [[today|hoy]] [[I only have|solo tengo]] [[credit card|tarjeta de crédito]]. [[B|B]]: [[No problem|Sin problema]]. [[Here is|Aquí está]] [[your|tu]] [[receipt|recibo]]. [[A|A]]: [[I feel|Me siento]] [[a bit|un poco]] [[ill|enfermo]] [[–|–]] [[headache|dolor de cabeza]]. [[B|B]]: [[You should|Deberías]] [[rest|descansar]] [[and|y]] [[take|tomar]] [[medicine|medicina]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_60_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u60-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does A order?|pide A?]]', options: ['[[Chicken for main course|Pollo de plato principal]]', '[[Soup|Sopa]]', '[[Dessert|Postre]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does A ask for?|pide A?]]', options: ['[[The bill|La cuenta]]', '[[The menu|La carta]]', '[[More food|Más comida]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[did A pay yesterday?|pagó A ayer?]]', options: ['[[With cash|Con efectivo]]', '[[With credit card|Con tarjeta]]', '[[The dialogue doesn\'t say|No lo dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does A have today?|tiene A hoy?]]', options: ['[[Only credit card|Solo tarjeta de crédito]]', '[[Only cash|Solo efectivo]]', '[[Both|Ambos]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does B give A?|da B a A?]]', options: ['[[Receipt|Recibo]]', '[[Change|cambio]]', '[[Menu|carta]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[does A feel?|se siente A?]]', options: ['[[A bit ill|Un poco enfermo]]', '[[Very well|Muy bien]]', '[[Happy|Feliz]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[symptom?|síntoma?]]', options: ['[[Headache|Dolor de cabeza]]', '[[Fever|Fiebre]]', '[[Cold|Resfriado]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[advice does B give?|consejo da B?]]', options: ['[[Rest and take medicine|Descansar y tomar medicina]]', '[[Go to work|Ir a trabajar]]', '[[Eat more|Comer más]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I would like|Quisiera]] = ____.', options: ['[[polite way to order|forma educada de pedir]]', '[[I want now|quiero ahora]]', '[[give me|dame]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Pay for|Pagar por]] = ____.', options: ['[[give money for|dar dinero por]]', '[[receive|recibir]]', '[[spend on|gastar en]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[is at|está en]] ____.', options: ['[[a restaurant|un restaurante]]', '[[a pharmacy|una farmacia]]', '[[a shop|una tienda]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You should rest|Deberías descansar]] = ____.', options: ['[[advice|consejo]]', '[[obligation|obligación]]', '[[past|pasado]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Receipt|Recibo]] = ____.', options: ['[[paper proof of payment|comprobante de pago]]', '[[change|cambio]]', '[[cash|efectivo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Main course|Plato principal]] = ____.', options: ['[[main dish|plato principal]]', '[[starter|entrante]]', '[[dessert|postre]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u60-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[combines|combina]] ____.', options: ['[[restaurant, payment, health|restaurante, pago, salud]]', '[[only food|solo comida]]', '[[only health|solo salud]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
