/**
 * Unidad 58 — Lección 3: Comprensión lectora (Health & Illness)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Health & Illness';
const READING_TRANSCRIPT = `[[I|Yo]] [[feel|me siento]] [[ill|enfermo]] [[today|hoy]]. [[I have|Tengo]] [[a|un]] [[headache|dolor de cabeza]] [[and|y]] [[a|un]] [[slight|leve]] [[fever|fiebre]]. [[I think|Creo]] [[I have|tengo]] [[a|un]] [[cold|resfriado]]. [[I should|Debería]] [[rest|descansar]] [[at home|en casa]] [[and|y]] [[drink|beber]] [[a lot of|mucha]] [[water|agua]]. [[I should|Debería]] [[take|tomar]] [[some|algo de]] [[medicine|medicina]] [[from|de]] [[the|la]] [[pharmacy|farmacia]]. [[I shouldn\'t|No debería]] [[go|ir]] [[to work|a trabajar]] [[today|hoy]]. [[If|Si]] [[the fever|la fiebre]] [[gets worse|empeora]] [[I should|debería]] [[see|ver]] [[a|un]] [[doctor|médico]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_58_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u58-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[does the writer feel|se siente el autor]] [[today|hoy]]?', options: ['[[Ill|Enfermo]]', '[[Well|Bien]]', '[[Happy|Feliz]]'], correctAnswer: 0, explanation: 'I feel ill today.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[symptoms|síntomas]] [[does he/she have|tiene]]?', options: ['[[Headache and fever|Dolor de cabeza y fiebre]]', '[[Only cough|Solo tos]]', '[[Nothing|Nada]]'], correctAnswer: 0, explanation: 'I have a headache and a slight fever.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does he/she think|cree que tiene]]?', options: ['[[A cold|Un resfriado]]', '[[A headache only|Solo dolor de cabeza]]', '[[Fever only|Solo fiebre]]'], correctAnswer: 0, explanation: 'I think I have a cold.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[should he/she do|debería hacer]]?', options: ['[[Rest and drink water|Descansar y beber agua]]', '[[Go to work|Ir a trabajar]]', '[[Nothing|Nada]]'], correctAnswer: 0, explanation: 'I should rest and drink a lot of water.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[can he/she get|puede conseguir]] [[medicine|medicina]]?', options: ['[[At the pharmacy|En la farmacia]]', '[[At work|En el trabajo]]', '[[At home|En casa]]'], correctAnswer: 0, explanation: 'Take medicine from the pharmacy.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Should he/she go to work?|¿Debería ir a trabajar?]]', options: ['[[No|No]]', '[[Yes|Sí]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0, explanation: 'I shouldn\'t go to work today.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[should he/she see a doctor?|debería ver a un médico?]]', options: ['[[If the fever gets worse|Si la fiebre empeora]]', '[[Now|Ahora]]', '[[Never|Nunca]]'], correctAnswer: 0, explanation: 'If the fever gets worse I should see a doctor.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Headache|Dolor de cabeza]] = ____.', options: ['[[pain in head|dolor en cabeza]]', '[[fever|fiebre]]', '[[cold|resfriado]]'], correctAnswer: 0, explanation: 'Headache = dolor de cabeza.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Pharmacy|Farmacia]] = ____.', options: ['[[place to buy medicine|lugar para comprar medicina]]', '[[hospital|hospital]]', '[[doctor|médico]]'], correctAnswer: 0, explanation: 'Pharmacy = farmacia.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Should|Debería]] [[is used for|se usa para]] ____.', options: ['[[advice|consejo]]', '[[obligation|obligación]]', '[[past|pasado]]'], correctAnswer: 0, explanation: 'Should = consejo.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[being ill and what to do|estar enfermo y qué hacer]]', '[[going to work|ir a trabajar]]', '[[cooking| cocinar]]'], correctAnswer: 0, explanation: 'Ill, headache, fever, cold, should rest, medicine.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fever|Fiebre]] = ____.', options: ['[[high body temperature|temperatura alta]]', '[[headache|dolor de cabeza]]', '[[cold|resfriado]]'], correctAnswer: 0, explanation: 'Fever = fiebre.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Shouldn\'t|No debería]] = ____.', options: ['[[should not|should not]]', '[[should|debería]]', '[[must not|no debe]]'], correctAnswer: 0, explanation: 'Shouldn\'t = should not.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cold|Resfriado]] = ____.', options: ['[[illness with cough, runny nose|enfermedad con tos, mocos]]', '[[headache|dolor de cabeza]]', '[[fever|fiebre]]'], correctAnswer: 0, explanation: 'Cold = resfriado.' }] }, topicName: 'Reading' },
  { id: 'a1-u58-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the main advice|el consejo principal]]?', options: ['[[Rest, drink water, take medicine|Descansar, beber agua, tomar medicina]]', '[[Go to work|Ir a trabajar]]', '[[See doctor now|Ver médico ahora]]'], correctAnswer: 0, explanation: 'Should rest, drink water, take medicine; shouldn\'t go to work.' }] }, topicName: 'Reading' },
];
