/**
 * Unidad 31 — Lección 4: Comprensión auditiva (Can for Ability)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Can for Ability';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[Can|¿Puedes]] [[you|tú]] [[swim|nadar]]? [[B|B]]: [[Yes|Sí]], [[I|yo]] [[can|puedo]]. [[I|Yo]] [[go|voy]] [[to|a]] [[the|la]] [[pool|piscina]] [[every|cada]] [[Saturday|sábado]]. [[A|A]]: [[Can|¿Puede]] [[your|tu]] [[sister|hermana]] [[cook|cocinar]]? [[B|B]]: [[No|No]], [[she|ella]] [[can\'t|no puede]]. [[But|Pero]] [[she|ella]] [[can|puede]] [[speak|hablar]] [[Spanish|español]] [[and|y]] [[English|inglés]]. [[A|A]]: [[Can|¿Puedes]] [[you|tú]] [[drive|conducir]]? [[B|B]]: [[No|No]], [[not yet|aún no]]. [[I|Yo]] [[am|tengo]] [[seventeen|diecisiete]] [[next|el próximo]] [[month|mes]]. [[Then|Entonces]] [[I|yo]] [[can|podré]] [[start|empezar]] [[driving lessons|las clases de conducir]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_31_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u31-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B|B]] [[swim|nadar]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[does|va]] [[B|B]] [[go|va]] [[to the pool|a la piscina]]?', options: ['[[Every Saturday|Cada sábado]]', '[[Every Sunday|Cada domingo]]', '[[Every week|Cada semana]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B\'s|de B]] [[sister|hermana]] [[cook|cocinar]]?', options: ['[[No|No]]', '[[Yes|Sí]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[can|puede]] [[the|la]] [[sister|hermana]] [[do|hacer]]?', options: ['[[Speak Spanish and English|Hablar español e inglés]]', '[[Cook|Cocinar]]', '[[Drive|Conducir]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|¿Puede]] [[B|B]] [[drive|conducir]]?', options: ['[[No, not yet|No, aún no]]', '[[Yes|Sí]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuándo]] [[can|podrá]] [[B|B]] [[start|empezar]] [[driving lessons|las clases de conducir]]?', options: ['[[When he is seventeen|Cuando tenga diecisiete]]', '[[Next week|La próxima semana]]', '[[Next year|El próximo año]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántos]] [[many|]] [[languages|idiomas]] [[can|puede]] [[the|la]] [[sister|hermana]] [[speak|hablar]]?', options: ['[[Two|Dos]]', '[[One|Uno]]', '[[Three|Tres]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[dialogue|diálogo]] [[is|es]] ____.', options: ['[[about abilities (can/can\'t)|sobre capacidades]]', '[[about family|sobre familia]]', '[[about food|sobre comida]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A|A]] ____ [[B|B]] [[about|sobre]] [[swimming|nadar]], [[cooking|cocinar]] [[and|y]] [[driving|conducir]].', options: ['[[asks|pregunta]]', '[[ask|preguntar]]', '[[asking|preguntando]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[says|dice]] "[[not yet|aún no]]" [[for|para]] ____.', options: ['[[driving|conducir]]', '[[swimming|nadar]]', '[[cooking|cocinar]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Correct|Correcta]] [[short|respuesta]] [[answer|breve]]: [[Can you swim?|¿Puedes nadar?]] ____.', options: ['[[Yes, I can|Sí, puedo]]', '[[Yes, I do|Sí, hago]]', '[[Yes, I am|Sí, soy]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[aún no|aún no]]"?', options: ['[[Not yet|Not yet]]', '[[No|No]]', '[[Yes|Sí]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B\'s|De B]] [[sister|hermana]] ____ [[cook|cocinar]].', options: ["[[can't|no puede]]", '[[can|puede]]', '[[cans|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[is|tiene]] [[seventeen|diecisiete]] ____.', options: ['[[next month|el próximo mes]]', '[[now|ahora]]', '[[last year|el año pasado]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u31-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|hará]] [[B|B]] [[do|hará]] [[after|después de]] [[he is seventeen|tener diecisiete]]?', options: ['[[Start driving lessons|Empezar las clases de conducir]]', '[[Go to the pool|Ir a la piscina]]', '[[Cook|Cocinar]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
