/**
 * Unidad 56 — Lección 3: Comprensión lectora (At the Restaurant)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'At the Restaurant';
const READING_TRANSCRIPT = `[[We|Nosotros]] [[are|estamos]] [[at|en]] [[a|un]] [[restaurant|restaurante]] [[tonight|esta noche]]. [[The|El]] [[waiter|camarero]] [[brings|trae]] [[the|la]] [[menu|carta]]. [[I|Yo]] [[would like|quisiera]] [[a|una]] [[soup|sopa]] [[for|para]] [[starter|entrante]]. [[My|Mi]] [[friend|amigo]] [[wants|quiere]] [[salad|ensalada]]. [[For|Para]] [[main course|plato principal]] [[I|yo]] [[order|pido]] [[chicken|pollo]] [[and|y]] [[rice|arroz]]. [[We|Nosotros]] [[have|tomamos]] [[water|agua]] [[to drink|para beber]]. [[After|Después]] [[dinner|cena]] [[we|nosotros]] [[would like|quisiéramos]] [[dessert|postre]]. [[I|Yo]] [[have|pido]] [[ice cream|helado]]. [[Then|Luego]] [[we|nosotros]] [[ask for|pedimos]] [[the|la]] [[bill|cuenta]] [[and|y]] [[pay|pagamos]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_56_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u56-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[are|están]] [[they|ellos]] [[tonight|esta noche]]?', options: ['[[At a restaurant|En un restaurante]]', '[[At home|En casa]]', '[[At a cafe|En una cafetería]]'], correctAnswer: 0, explanation: 'We are at a restaurant tonight.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does the waiter bring|trae el camarero]]?', options: ['[[The menu|La carta]]', '[[The bill|La cuenta]]', '[[The food|La comida]]'], correctAnswer: 0, explanation: 'The waiter brings the menu.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[starter|entrante]] [[does the writer want|quiere el autor]]?', options: ['[[Soup|Sopa]]', '[[Salad|Ensalada]]', '[[Chicken|Pollo]]'], correctAnswer: 0, explanation: 'I would like a soup for starter.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[main course|plato principal]] [[does he/she order|pide]]?', options: ['[[Chicken and rice|Pollo y arroz]]', '[[Soup|Sopa]]', '[[Ice cream|Helado]]'], correctAnswer: 0, explanation: 'For main course I order chicken and rice.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[do they drink|beben]]?', options: ['[[Water|Agua]]', '[[Coffee|Café]]', '[[Juice|Zumo]]'], correctAnswer: 0, explanation: 'We have water to drink.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[dessert|postre]] [[does the writer have|pide el autor]]?', options: ['[[Ice cream|Helado]]', '[[Salad|Ensalada]]', '[[Soup|Sopa]]'], correctAnswer: 0, explanation: 'I have ice cream.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[After|Después]] [[dessert|postre]] [[they|ellos]] ____.', options: ['[[ask for the bill and pay|piden la cuenta y pagan]]', '[[order more food|piden más comida]]', '[[leave without paying|se van sin pagar]]'], correctAnswer: 0, explanation: 'Then we ask for the bill and pay.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Starter|Entrante]] = ____.', options: ['[[first course|primer plato]]', '[[main dish|plato principal]]', '[[dessert|postre]]'], correctAnswer: 0, explanation: 'Starter = primer plato.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Bill|Cuenta]] = ____.', options: ['[[what you pay|lo que pagas]]', '[[menu|carta]]', '[[starter|entrante]]'], correctAnswer: 0, explanation: 'Bill = cuenta.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I would like|Quisiera]] = ____.', options: ['[[polite way to order|forma educada de pedir]]', '[[I want now|quiero ahora]]', '[[give me|dame]]'], correctAnswer: 0, explanation: 'I would like = forma educada.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[a meal at a restaurant|una comida en restaurante]]', '[[cooking at home|cocinar en casa]]', '[[a supermarket|un supermercado]]'], correctAnswer: 0, explanation: 'Restaurant, menu, starter, main, dessert, bill.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Main course|Plato principal]] = ____.', options: ['[[main dish|plato principal]]', '[[starter|entrante]]', '[[dessert|postre]]'], correctAnswer: 0, explanation: 'Main course = plato principal.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Who|Quién]] [[wants|quiere]] [[salad|ensalada]] [[for starter|de entrante]]?', options: ['[[The friend|El amigo]]', '[[The writer|El autor]]', '[[The waiter|El camarero]]'], correctAnswer: 0, explanation: 'My friend wants salad.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Dessert|Postre]] = ____.', options: ['[[sweet at end of meal|dulce al final de la comida]]', '[[starter|entrante]]', '[[drink|bebida]]'], correctAnswer: 0, explanation: 'Dessert = postre.' }] }, topicName: 'Reading' },
  { id: 'a1-u56-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the order of the meal|el orden de la comida]]?', options: ['[[Starter, main course, dessert|Entrante, principal, postre]]', '[[Dessert, main, starter|Postre, principal, entrante]]', '[[Main, bill, dessert|Principal, cuenta, postre]]'], correctAnswer: 0, explanation: 'Starter, then main, then dessert, then bill.' }] }, topicName: 'Reading' },
];
