/**
 * Unidad 57 — Lección 4: Comprensión auditiva (Cooking & Recipes)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Cooking & Recipes';
const LISTENING_TRANSCRIPT = `[[How to make|Cómo hacer]] [[scrambled eggs|huevos revueltos]]. [[First|Primero]] [[break|rompe]] [[the|los]] [[eggs|huevos]] [[into|en]] [[a|un]] [[bowl|bol]]. [[Then|Luego]] [[add|añade]] [[a little|un poco de]] [[milk|leche]] [[and|y]] [[salt|sal]]. [[Mix|Mezcla]] [[well|bien]]. [[Then|Luego]] [[put|pon]] [[butter|mantequilla]] [[in|en]] [[a|una]] [[pan|sartén]] [[and|y]] [[fry|fríe]] [[the|la]] [[mixture|mezcla]] [[for|durante]] [[two minutes|dos minutos]]. [[Finally|Finalmente]] [[serve|sirve]] [[on|en]] [[a|un]] [[plate|plato]] [[with|con]] [[toast|tostadas]]. [[Enjoy|Disfruta]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_57_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u57-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[recipe|receta]] [[is this|es esta]]?', options: ['[[Scrambled eggs|Huevos revueltos]]', '[[Pasta|Pasta]]', '[[Cake|Tarta]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[do you do first|haces primero]]?', options: ['[[Break eggs into a bowl|Romper huevos en un bol]]', '[[Add milk|Añadir leche]]', '[[Fry|Freír]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[do you add|añades]] [[to the eggs|a los huevos]]?', options: ['[[Milk and salt|Leche y sal]]', '[[Butter|Mantequilla]]', '[[Toast|Tostadas]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How do you cook|Cómo cocinas]] [[the mixture|la mezcla]]?', options: ['[[Fry in a pan|Freír en sartén]]', '[[Boil|Hervir]]', '[[Bake|Hornear]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How long|Cuánto tiempo]] [[do you fry|fríes]]?', options: ['[[Two minutes|Dos minutos]]', '[[Five minutes|Cinco minutos]]', '[[Ten minutes|Diez minutos]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Finally|Finalmente]] [[you|tú]] ____.', options: ['[[serve on a plate with toast|sirves en plato con tostadas]]', '[[break eggs|rompes huevos]]', '[[add milk|añades leche]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Mix|Mezclar]] = ____.', options: ['[[combine together|combinar]]', '[[cut|cortar]]', '[[fry|freír]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fry|Freír]] = ____.', options: ['[[cook in oil in pan|cocinar en aceite en sartén]]', '[[boil|hervir]]', '[[bake|hornear]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[First, Then, Finally|First, Then, Finally]] [[show|muestran]] ____.', options: ['[[order of steps|orden de pasos]]', '[[ingredients|ingredientes]]', '[[time|tiempo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Bowl|Bol]] = ____.', options: ['[[container for mixing|recipiente para mezclar]]', '[[pan|sartén]]', '[[plate|plato]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Butter|Mantequilla]] [[goes|va]] ____.', options: ['[[in the pan first|en la sartén primero]]', '[[in the eggs|en los huevos]]', '[[on the toast|en las tostadas]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Mixture|Mezcla]] = ____.', options: ['[[what you mix together|lo que mezclas]]', '[[pan|sartén]]', '[[egg|huevo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dialogue|El diálogo]] [[is about|trata de]] ____.', options: ['[[a cooking recipe|una receta de cocina]]', '[[a restaurant|un restaurante]]', '[[shopping|compras]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Serve|Servir]] = ____.', options: ['[[give food to someone|dar comida a alguien]]', '[[cook|cocinar]]', '[[mix|mezclar]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u57-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the last word|la última palabra]]?', options: ['[[Enjoy|Disfruta]]', '[[Toast|Tostadas]]', '[[Finally|Finalmente]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
