/**
 * Unidad 48 — Lección 5: Expresión oral (Sightseeing)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión oral';
const TOPIC = 'Sightseeing';

export const UNIT_48_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a1-u48-l5-s1', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite.', targetText: '[[This is|Este es]] [[the|el]] [[most|más]] [[famous|famoso]] [[monument|monumento]] [[in|en]] [[the city|la ciudad]].', expectedResponse: 'This is the most famous monument in the city.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s2', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[It is|Es]] [[the|la]] [[oldest|más antigua]] [[church|iglesia]] [[in|en]] [[town|el pueblo]].', expectedResponse: 'It is the oldest church in town.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s3', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[We|Nosotros]] [[visited|visitamos]] [[the|el]] [[museum|museo]] [[yesterday|ayer]].', expectedResponse: 'We visited the museum yesterday.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s4', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[There is|Hay]] [[a|una]] [[tall|alta]] [[statue|estatua]] [[in|en]] [[the square|la plaza]].', expectedResponse: 'There is a tall statue in the square.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s5', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Pregunta en voz alta: ¿Hiciste una visita guiada?', targetText: '____?', expectedResponse: 'Did you do a guided tour?' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s6', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[We|Nosotros]] [[did|hicimos]] [[a|una]] [[guided tour|visita guiada]] [[of|de]] [[the monument|el monumento]].', expectedResponse: 'We did a guided tour of the monument.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s7', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: "[[The|El]] [[guide|guía]] [[explained|explicó]] [[the history|la historia]]. [[It was|Fue]] [[very interesting|muy interesante]].", expectedResponse: "The guide explained the history. It was very interesting." }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s8', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: ese es el museo más grande de la ciudad.', targetText: '____.', expectedResponse: 'That is the biggest museum in the city.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s9', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[That|Esa]] [[is|es]] [[the|la]] [[tallest|más alta]] [[statue|estatua]] [[here|aquí]].', expectedResponse: 'That is the tallest statue here.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s10', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[We|Nosotros]] [[took|sacamos]] [[photos|fotos]] [[of|de]] [[the monument|el monumento]].', expectedResponse: 'We took photos of the monument.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s11', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: visitamos el monumento más famoso.', targetText: '____.', expectedResponse: 'We visited the most famous monument.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s12', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[Yesterday|Ayer]] [[we|nosotros]] [[did|hicimos]] [[sightseeing|turismo]] [[in|en]] [[the city|la ciudad]].', expectedResponse: 'Yesterday we did sightseeing in the city.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s13', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[This|Esta]] [[is|es]] [[the|la]] [[most beautiful|más hermosa]] [[building|edificio]] [[in|en]] [[town|el pueblo]].', expectedResponse: 'This is the most beautiful building in town.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s14', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Repite.', targetText: '[[I|Yo]] [[want|quiero]] [[to do|hacer]] [[a|una]] [[guided tour|visita guiada]] [[tomorrow|mañana]].', expectedResponse: 'I want to do a guided tour tomorrow.' }, topicName: 'Speaking' },
  { id: 'a1-u48-l5-s15', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Describe en voz alta: el lugar más famoso o más antiguo que visitaste (2–3 frases con the most / the oldest).', targetText: '____. ____.', expectedResponse: 'I visited the most famous museum. It is the oldest building in the city.' }, topicName: 'Speaking' },
];
