/**
 * Unidad 53 — Lección 3: Comprensión lectora (Some & Any)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Some & Any';
const READING_TRANSCRIPT = `[[I|Yo]] [[open|abro]] [[the|la]] [[fridge|nevera]]. [[There is|Hay]] [[some|algo de]] [[milk|leche]] [[and|y]] [[some|algo de]] [[water|agua]] [[in|en]] [[bottles|botellas]]. [[There isn\'t|No hay]] [[any|nada de]] [[bread|pan]] [[left|restante]]. [[In|En]] [[the|la]] [[cupboard|despensa]] [[I have|tengo]] [[some|algo de]] [[rice|arroz]] [[in|en]] [[a|una]] [[box|caja]] [[and|y]] [[some|algunas]] [[cans|latas]] [[of|de]] [[beans|judías]]. [[Do we have|Tenemos]] [[any|alguna]] [[fruit|fruta]]? [[Yes|Sí]], [[there are|hay]] [[some|algunas]] [[apples|manzanas]] [[in|en]] [[the|la]] [[bag|bolsa]]. [[I need|Necesito]] [[to buy|comprar]] [[some|algo de]] [[bread|pan]] [[and|y]] [[any|alguna]] [[eggs|huevos]] [[if|si]] [[they have|tienen]] [[some|algunos]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_53_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u53-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[is|está]] [[the writer|el autor]] [[at the start|al principio]]?', options: ['[[Opening the fridge|Abriendo la nevera]]', '[[In the shop|En la tienda]]', '[[In the cupboard|En la despensa]]'], correctAnswer: 0, explanation: 'I open the fridge.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is there any milk|Hay algo de leche]]?', options: ['[[Yes, some|Sí, algo]]', '[[No|No]]', '[[The text doesn\'t say|No lo dice]]'], correctAnswer: 0, explanation: 'There is some milk.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is there any bread left|Queda pan]]?', options: ['[[No|No]]', '[[Yes|Sí]]', '[[Some|Algo]]'], correctAnswer: 0, explanation: 'There isn\'t any bread left.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where is the rice|Dónde está el arroz]]?', options: ['[[In a box in the cupboard|En una caja en la despensa]]', '[[In the fridge|En la nevera]]', '[[In a bag|En una bolsa]]'], correctAnswer: 0, explanation: 'Some rice in a box in the cupboard.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What is in cans|Qué hay en latas]]?', options: ['[[Beans|Judías]]', '[[Milk|Leche]]', '[[Rice|Arroz]]'], correctAnswer: 0, explanation: 'Some cans of beans.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Do they have any fruit|Tienen fruta]]?', options: ['[[Yes, some apples|Sí, algunas manzanas]]', '[[No|No]]', '[[Only rice|Solo arroz]]'], correctAnswer: 0, explanation: 'There are some apples in the bag.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where are the apples|Dónde están las manzanas]]?', options: ['[[In the bag|En la bolsa]]', '[[In the fridge|En la nevera]]', '[[In the box|En la caja]]'], correctAnswer: 0, explanation: 'Some apples in the bag.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What does he/she need to buy|Qué necesita comprar]]?', options: ['[[Some bread and eggs|Algo de pan y huevos]]', '[[Milk and water|Leche y agua]]', '[[Rice and beans|Arroz y judías]]'], correctAnswer: 0, explanation: 'I need to buy some bread and any eggs.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word|Qué palabra]] [[means|significa]] [[ninguno/nada|ninguno/nada]] [[in negatives|en negativas]]?', options: ['[[Any|Any]]', '[[Some|Some]]', '[[Many|Many]]'], correctAnswer: 0, explanation: 'There isn\'t any bread = no hay pan.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Bottle|Botella]] = ____.', options: ['[[container for milk, water|recipiente para leche, agua]]', '[[box|caja]]', '[[bag|bolsa]]'], correctAnswer: 0, explanation: 'Milk and water in bottles.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[what is in fridge/cupboard, some/any|qué hay en nevera/despensa, some/any]]', '[[cooking recipe|receta]]', '[[restaurant|restaurante]]'], correctAnswer: 0, explanation: 'Fridge, cupboard, some, any, containers.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Some|Some]] [[in affirmatives|en afirmativas]] = ____.', options: ['[[algo/algunos|algo/algunos]]', '[[nada|nada]]', '[[siempre en preguntas|solo en preguntas]]'], correctAnswer: 0, explanation: 'There is some milk.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cupboard|Despensa]] = ____.', options: ['[[place for food storage|lugar para guardar comida]]', '[[fridge|nevera]]', '[[bag|bolsa]]'], correctAnswer: 0, explanation: 'Cupboard = despensa.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Left|Restante]] = ____.', options: ['[[remaining|que queda]]', '[[left side|lado izquierdo]]', '[[bought|comprado]]'], correctAnswer: 0, explanation: 'Left = restante.' }] }, topicName: 'Reading' },
  { id: 'a1-u53-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'hard', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]]?', options: ['[[Food at home, some/any, containers|Comida en casa, some/any, contenedores]]', '[[Shopping list|Lista de compra]]', '[[Recipe|Receta]]'], correctAnswer: 0, explanation: 'Fridge, cupboard, some, any, bottle, box, can, bag.' }] }, topicName: 'Reading' },
];
