/**
 * Unidad 21 — Lección 6: Expresión escrita (Rooms in a House)
 * Descripción breve de una casa.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Rooms in a House';

export const UNIT_21_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u21-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] [[have|tenemos]] ____ [[bedrooms|dormitorios]].', options: ['[[three|tres]]', '[[bedroom|dormitorio]]', '[[room|habitación]]'], correctAnswer: 'three', acceptableAnswers: ['three'], explanation: 'Three bedrooms.' }] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|La]] ____ [[is|es]] [[bright|luminosa]].', options: ['[[kitchen|cocina]]', '[[garden|jardín]]', '[[bathroom|baño]]'], correctAnswer: 'kitchen', acceptableAnswers: ['kitchen'] }] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[My|Mi]] ____ [[room|habitación]] [[is|es]] [[the|el]] [[living room|salón]].', options: ['[[favourite|favorita]]', '[[small|pequeña]]', '[[big|grande]]'], correctAnswer: 'favourite', acceptableAnswers: ['favourite'] }] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] [[have|tenemos]] [[a|un]] ____ [[at the back|detrás]].', options: ['[[garden|jardín]]', '[[bedroom|dormitorio]]', '[[kitchen|cocina]]'], correctAnswer: 'garden', acceptableAnswers: ['garden'] }] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[The|El]] [[bathroom|baño]] ____ [[small|pequeño]] [[but|pero]] [[clean|limpio]].', options: ['[[is|es]]', '[[are|son]]', '[[have|tiene]]'], correctAnswer: 'is', acceptableAnswers: ['is'] }] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[We|Nosotros]] [[have|tenemos]] [[a|una]] [[living room|salón]] [[and|y]] [[a|una]] [[kitchen|cocina]].', words: ['[[We|Nosotros]]', '[[have|tenemos]]', '[[a|una]]', '[[living room|salón]]', '[[and|y]]', '[[a|una]]', '[[kitchen|cocina]].'] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[The|El]] [[living room|salón]] [[is|es]] [[very|muy]] [[cozy|acogedor]].', words: ['[[The|El]]', '[[living room|salón]]', '[[is|es]]', '[[very|muy]]', '[[cozy|acogedor]].'] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[My|Mi]] [[house|casa]] [[has|tiene]] [[three|tres]] [[bedrooms|dormitorios]].', words: ['[[My|Mi]]', '[[house|casa]]', '[[has|tiene]]', '[[three|tres]]', '[[bedrooms|dormitorios]].'] }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase diciendo cuántas habitaciones tiene tu casa o piso.', prompt: '____.', minWords: 5, maxWords: 15, modelExample: '[[We|Nosotros]] [[have|tenemos]] [[three|tres]] [[bedrooms|dormitorios]] [[and|y]] [[two|dos]] [[bathrooms|baños]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase describiendo la cocina o el salón (bright, cozy, small, big).', prompt: '____.', minWords: 6, maxWords: 15, modelExample: '[[The|La]] [[kitchen|cocina]] [[is|es]] [[bright|luminosa]] [[and|y]] [[modern|moderna]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: qué habitaciones tienes y cuál es tu favorita.', prompt: '____. ____.', minWords: 10, maxWords: 25, modelExample: '[[We|Nosotros]] [[have|tenemos]] [[a|un]] [[living room|salón]], [[a|una]] [[kitchen|cocina]] [[and|y]] [[two|dos]] [[bedrooms|dormitorios]]. [[My|Mi]] [[favourite|favorita]] [[room|habitación]] [[is|es]] [[the|el]] [[living room|salón]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe: Do you have a garden? y tu respuesta.', prompt: '____? ____.', minWords: 4, maxWords: 12, modelExample: '[[Do|¿]] [[you|tú]] [[have|tienes]] [[a|un]] [[garden|jardín]]? [[Yes|Sí]], [[I|yo]] [[do|sí]]. [[No|No]], [[I|yo]] [[don\'t|no]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–5 frases) describiendo tu casa o piso: habitaciones y cómo son.', prompt: '____.', minWords: 25, maxWords: 55, modelExample: '[[I|Yo]] [[live|vivo]] [[in|en]] [[a|un]] [[flat|piso]]. [[We|Nosotros]] [[have|tenemos]] [[two|dos]] [[bedrooms|dormitorios]], [[a|una]] [[kitchen|cocina]] [[and|y]] [[a|un]] [[living room|salón]]. [[The|La]] [[kitchen|cocina]] [[is|es]] [[small|pequeña]] [[but|pero]] [[bright|luminosa]]. [[The|El]] [[living room|salón]] [[is|es]] [[cozy|acogedor]]. [[We|Nosotros]] [[don\'t|no]] [[have|tenemos]] [[a|un]] [[garden|jardín]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases: qué habitaciones hay en tu casa y una cualidad de cada una.', prompt: '____.', minWords: 18, maxWords: 40, modelExample: '[[We|Nosotros]] [[have|tenemos]] [[a|una]] [[kitchen|cocina]] — [[it is|es]] [[bright|luminosa]]. [[We|Nosotros]] [[have|tenemos]] [[a|un]] [[living room|salón]] — [[it is|es]] [[cozy|acogedor]]. [[We|Nosotros]] [[have|tenemos]] [[two|dos]] [[bedrooms|dormitorios]].' }, topicName: 'Writing' },
  { id: 'a1-u21-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la pregunta How many rooms does your house have? y tu respuesta.', prompt: '____? ____.', minWords: 6, maxWords: 18, modelExample: '[[How|Cuántas]] [[many|]] [[rooms|habitaciones]] [[does|tiene]] [[your|tu]] [[house|casa]] [[have|tiene]]? [[We|Nosotros]] [[have|tenemos]] [[four|cuatro]] [[rooms|habitaciones]].' }, topicName: 'Writing' },
];
