/**
 * Unidad 20 — Lección 3: Comprensión lectora
 * 15 ejercicios: texto sobre trabajo y profesiones.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Jobs & Work';

const READING_TRANSCRIPT = `[[My|Mi]] [[name|nombre]] [[is|es]] [[Lisa|Lisa]]. [[I|Yo]] [[am|soy]] [[a|una]] [[teacher|profesora]]. [[I|Yo]] [[work|trabajo]] [[in|en]] [[a|un]] [[school|colegio]] [[in|en]] [[Barcelona|Barcelona]]. [[I|Yo]] [[teach|enseño]] [[English|inglés]]. [[I|Yo]] [[get|me]] [[up|levanto]] [[at|a]] [[seven|siete]] [[o\'clock|en punto]] [[and|y]] [[I|yo]] [[go|voy]] [[to|a]] [[work|trabajo]] [[at|a]] [[half|y]] [[past|media]] [[eight|ocho]]. [[I|Yo]] [[have|tomo]] [[lunch|comida]] [[at|a]] [[the|en]] [[school|colegio]] [[at|a]] [[one|la una]]. [[I|Yo]] [[finish|termino]] [[work|trabajo]] [[at|a]] [[four|cuatro]] [[o\'clock|en punto]]. [[I|Yo]] [[love|me encanta]] [[my|mi]] [[job|trabajo]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_20_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u20-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[Lisa\'s|el nombre de Lisa]] [[name|nombre]]?', options: ['[[Lisa|Lisa]]', '[[Barcelona|Barcelona]]', '[[English|English]]'], correctAnswer: 0, explanation: 'My name is Lisa.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] ____ [[does|es]] [[Lisa|Lisa]] [[do|(profesión)]]?', options: ['[[She is a teacher|Es profesora]]', '[[She is a doctor|Es médica]]', '[[She is a nurse|Es enfermera]]'], correctAnswer: 0, explanation: 'I am a teacher.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[does|trabaja]] [[she|ella]] [[work|trabajar]]?', options: ['[[In a hospital|En un hospital]]', '[[In a school|En un colegio]]', '[[In an office|En una oficina]]'], correctAnswer: 1, explanation: 'I work in a school.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|enseña]] [[she|ella]] [[teach|enseñar]]?', options: ['[[Math|Matemáticas]]', '[[English|Inglés]]', '[[Spanish|Español]]'], correctAnswer: 1, explanation: 'I teach English.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|A]] [[time|qué]] [[does|se]] [[she|ella]] [[get|levanta]] [[up|levantar]]?', options: ['[[At six o\'clock|A las seis]]', '[[At seven o\'clock|A las siete]]', '[[At eight o\'clock|A las ocho]]'], correctAnswer: 1, explanation: 'I get up at seven o\'clock.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Lisa|Lisa]] [[goes|va]] [[to|a]] [[work|trabajo]] [[at|a]] [[half|y]] [[past|media]] [[eight|ocho]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: 'I go to work at half past eight.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[has|toma]] [[lunch|comida]] [[at|a]] [[twelve|doce]] [[o\'clock|en punto]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'False', explanation: 'I have lunch at one o\'clock.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[finishes|termina]] [[work|trabajo]] [[at|a]] [[four|cuatro]] [[o\'clock|en punto]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: 'I finish work at four o\'clock.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Lisa|Lisa]] [[works|trabaja]] [[in|en]] [[Madrid|Madrid]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'False', explanation: 'I work in Barcelona.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]] [[of|del]] [[text|texto]]?', options: ['[[Lisa\'s job and routine|El trabajo y la rutina de Lisa]]', '[[A school|Un colegio]]', '[[Food|Comida]]'], correctAnswer: 0, explanation: 'Habla de su trabajo y su rutina.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[does|toma]] [[she|ella]] [[have|comida]] [[lunch|comida]]?', options: ['[[At home|En casa]]', '[[At the school|En el colegio]]', '[[In a restaurant|En un restaurante]]'], correctAnswer: 1, explanation: 'I have lunch at the school.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|Le]] [[Lisa|Lisa]] [[love|gusta]] [[her|su]] [[job|trabajo]]?', options: ['[[Yes, she loves it|Sí, le encanta]]', '[[No, she doesn\'t|No]]', '[[The text doesn\'t say|El texto no lo dice]]'], correctAnswer: 0, explanation: 'I love my job.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|enseña]] [[she|ella]] [[teach|enseñar]] [[at|en]] [[school|el colegio]]?', options: ['[[Spanish|Español]]', '[[English|Inglés]]', '[[Math|Matemáticas]]'], correctAnswer: 1, explanation: 'I teach English.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[subject|asignatura]] [[does|enseña]] [[Lisa|Lisa]] [[teach|enseña]]?', options: ['[[English.|Inglés.]]', '[[Science.|Ciencias.]]', '[[Maths.|Matemáticas.]]'], correctAnswer: 0, explanation: 'She teaches English.' }] }, topicName: 'Reading' },
  { id: 'a1-u20-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[At|A]] [[what|qué]] [[time|hora]] [[does|termina]] [[she|ella]] [[finish|trabajo]] [[work|trabajo]]?', options: ['[[At three o\'clock|A las tres]]', '[[At four o\'clock|A las cuatro]]', '[[At five o\'clock|A las cinco]]'], correctAnswer: 1, explanation: 'I finish work at four o\'clock.' }] }, topicName: 'Reading' },
];
