/**
 * Unidad 37 — Lección 1: Gramática (Talent & Skills)
 * very well, quite well, not at all para nivel de habilidad.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Habilidad: very well, quite well, not at all';
const TOPIC = 'Talent & Skills';

export const UNIT_37_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'a1-u37-l1-g1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[can|puedo]] [[speak|hablar]] [[English|inglés]] ____.', options: ['[[very well|muy bien]]', '[[quite well|bastante bien]]', '[[not at all|nada]]'], correctAnswer: 'very well', acceptableAnswers: ['very well'], explanation: 'Very well = muy bien.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[cooks|cocina]] ____.', options: ['[[quite well|bastante bien]]', '[[very well|muy bien]]', '[[not at all|nada]]'], correctAnswer: 'quite well', acceptableAnswers: ['quite well'], explanation: 'Quite well = bastante bien.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] [[can\'t|no puede]] [[dance|bailar]] ____.', options: ['[[at all|nada]]', '[[very well|muy bien]]', '[[quite well|bastante bien]]'], correctAnswer: 'at all', acceptableAnswers: ['at all'], explanation: 'Not at all = nada en absoluto.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[play|toco]] [[the|la]] [[guitar|guitarra]] ____.', options: ['[[quite well|bastante bien]]', '[[well very|incorrecto]]', '[[at all|nada]]'], correctAnswer: 'quite well', acceptableAnswers: ['quite well'], explanation: 'Quite well after the verb.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[They|Ellos]] [[don\'t|no]] [[sing|cantan]] ____.', options: ['[[well|bien]]', '[[at all|nada]]', '[[very|muy]]'], correctAnswer: 'well', acceptableAnswers: ['well'], explanation: 'Don\'t sing well.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Which|Cuál]] [[means|significa]] "[[muy bien|muy bien]]"?', options: ['[[very well|very well]]', '[[quite well|quite well]]', '[[not at all|not at all]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g7', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We|Se]] [[put|pone]] ____ [[after|después de]] [[the|el]] [[verb|verbo]].', options: ['[[very well / quite well|very well / quite well]]', '[[before the verb|antes del verbo]]', '[[at the start|al inicio]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g8', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[She|Ella]] ____ [[draws|dibuja]] [[very well|muy bien]].', options: ['[[draws|dibuja]]', '[[can draw|puede dibujar]]', '[[draw|dibujar]]'], correctAnswer: 1 }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g9', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[["Not at all"|"Not at all"]] [[means|significa]] ____.', options: ['[[nada / en absoluto|nada]]', '[[muy bien|muy bien]]', '[[bastante|bastante]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g10', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[I|Yo]] [[can|puedo]] ____ [[Spanish|español]].', options: ['[[speak|hablar]]', '[[speaks|habla]]', '[[speaking|hablando]]'], correctAnswer: 0 }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g11', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[can|puedo]] [[sing|cantar]] [[very well|muy bien]].', words: ['[[I|Yo]]', '[[can|puedo]]', '[[sing|cantar]]', '[[very well|muy bien]].'] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g12', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[cooks|cocina]] [[quite well|bastante bien]].', words: ['[[She|Ella]]', '[[cooks|cocina]]', '[[quite well|bastante bien]].'] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g13', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[He|Él]] [[can\'t|no puede]] [[dance|bailar]] [[at all|nada]].', words: ['[[He|Él]]', '[[can\'t|no puede]]', '[[dance|bailar]]', '[[at all|nada]].'] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Very well|Very well]] [[and|y]] [[quite well|quite well]] [[go|van]] [[after|después de]] [[the|el]] [[verb|verbo]].', correctAnswer: true, explanation: 'I sing very well. She cooks quite well.' }] }, topicName: 'Grammar' },
  { id: 'a1-u37-l1-g15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Not at all|Not at all]] [[means|significa]] [[no|no]] [[ability|capacidad]] [[or|o]] [[skill|habilidad]].', correctAnswer: true, explanation: 'I can\'t swim at all.' }] }, topicName: 'Grammar' },
];
