/**
 * Unidad 33 — Lección 6: Expresión escrita (Adverbs of Frequency)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Adverbs of Frequency';

export const UNIT_33_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u33-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] ____ [[get up|me levanto]] [[at 7|a las 7]].', options: ['[[always|siempre]]', '[[never|nunca]]', '[[sometimes|a veces]]'], correctAnswer: 'always', acceptableAnswers: ['always'] }] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[is|es]] ____ [[late|tarde]].', options: ['[[never|nunca]]', '[[always|siempre]]', '[[often|a menudo]]'], correctAnswer: 'never', acceptableAnswers: ['never'] }] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[We|Nosotros]] ____ [[have|tomamos]] [[lunch|comida]] [[together|juntos]].', options: ['[[usually|normalmente]]', '[[never|nunca]]', '[[always always|incorrecto]]'], correctAnswer: 'usually', acceptableAnswers: ['usually'] }] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] ____ [[goes|va]] [[to the gym|al gimnasio]] [[three|tres]] [[times|veces]] [[a week|a la semana]].', options: ['[[often|a menudo]]', '[[never|nunca]]', '[[always|siempre]]'], correctAnswer: 'often', acceptableAnswers: ['often'] }] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[They|Ellos]] ____ [[eat|comen]] [[fish|pescado]]. (algunas veces)', options: ['[[sometimes|a veces]]', '[[always|siempre]]', '[[never|nunca]]'], correctAnswer: 'sometimes', acceptableAnswers: ['sometimes'] }] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena las palabras.', correctSentence: '[[I|Yo]] [[always|siempre]] [[have|tomo]] [[breakfast|café]] [[at 8|a las 8]].', words: ['[[I|Yo]]', '[[always|siempre]]', '[[have|tomo]]', '[[breakfast|café]]', '[[at 8|a las 8]].'] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[is|es]] [[never|nunca]] [[late|tarde]].', words: ['[[She|Ella]]', '[[is|es]]', '[[never|nunca]]', '[[late|tarde]].'] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[We|Nosotros]] [[sometimes|a veces]] [[go|vamos]] [[to the cinema|al cine]].', words: ['[[We|Nosotros]]', '[[sometimes|a veces]]', '[[go|vamos]]', '[[to the cinema|al cine]].'] }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: algo que siempre haces (I always…).', prompt: '____.', minWords: 4, maxWords: 12, modelExample: '[[I|Yo]] [[always|siempre]] [[have|tomo]] [[breakfast|café]] [[in the morning|por la mañana]].' }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: algo que nunca haces (I never…).', prompt: '____.', minWords: 4, maxWords: 12, modelExample: "[[I|Yo]] [[never|nunca]] [[skip|me salto]] [[breakfast|café]]." }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: algo que usually y algo que sometimes haces.', prompt: '____. ____.', minWords: 8, maxWords: 22, modelExample: '[[I|Yo]] [[usually|normalmente]] [[get up|me levanto]] [[at 7|a las 7]]. [[I|Yo]] [[sometimes|a veces]] [[go|voy]] [[to the cinema|al cine]].' }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe: How often do you…? y tu respuesta con un adverbio de frecuencia.', prompt: '____? ____.', minWords: 6, maxWords: 18, modelExample: '[[How|Con qué]] [[often|frecuencia]] [[do|vas]] [[you|tú]] [[go|vas]] [[to the gym|al gimnasio]]? [[I|Yo]] [[often|a menudo]] [[go|voy]] [[there|allí]].' }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (4–5 frases) sobre tu rutina usando always, usually, often, sometimes, never.', prompt: '____.', minWords: 22, maxWords: 55, modelExample: '[[I|Yo]] [[always|siempre]] [[get up|me levanto]] [[early|temprano]]. [[I|Yo]] [[usually|normalmente]] [[have|tomo]] [[breakfast|café]] [[at 8|a las 8]]. [[I|Yo]] [[often|a menudo]] [[go|voy]] [[running|a correr]]. [[I|Yo]] [[sometimes|a veces]] [[meet|quedo]] [[friends|con amigos]]. [[I|Yo]] [[never|nunca]] [[go|voy]] [[to bed|a la cama]] [[very late|muy tarde]].' }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 frases: una con always, una con usually, una con never.', prompt: '____. ____. ____.', minWords: 12, maxWords: 30, modelExample: '[[I|Yo]] [[always|siempre]] [[brush|me cepillo]] [[my teeth|los dientes]]. [[I|Yo]] [[usually|normalmente]] [[have|tomo]] [[lunch|cena]] [[at home|en casa]]. [[I|Yo]] [[never|nunca]] [[forget|olvido]] [[my keys|mis llaves]].' }, topicName: 'Writing' },
  { id: 'a1-u33-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con He/She is + adverbio + adjetivo (ej. never late).', prompt: '____.', minWords: 5, maxWords: 12, modelExample: '[[He|Él]] [[is|es]] [[never|nunca]] [[late|tarde]].' }, topicName: 'Writing' },
];
