/**
 * Unidad 37 — Lección 3: Comprensión lectora (Talent & Skills)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Talent & Skills';
const READING_TRANSCRIPT = `[[My|Mi]] [[name|nombre]] [[is|es]] [[Lisa|Lisa]]. [[I|Yo]] [[can|puedo]] [[sing|cantar]] [[very well|muy bien]] [[and|y]] [[I|yo]] [[play|toco]] [[the|la]] [[piano|piano]] [[quite well|bastante bien]]. [[My|Mi]] [[brother|hermano]] [[can|puede]] [[cook|cocinar]] [[very well|muy bien]] — [[he|él]] [[is|es]] [[creative|creativo]]. [[I|Yo]] [[can't|no puedo]] [[draw|dibujar]] [[at all|nada]]. [[My|Mi]] [[sister|hermana]] [[is|es]] [[hardworking|trabajadora]] [[and|y]] [[she|ella]] [[speaks|habla]] [[English|inglés]] [[very well|muy bien]]. [[We|Nosotros]] [[all|todos]] [[have|tenemos]] [[different|diferentes]] [[skills|habilidades]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_37_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u37-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[writer\'s|de la autora]] [[name|nombre]]?', options: ['[[Lisa|Lisa]]', '[[Lina|Lina]]', '[[Laura|Laura]]'], correctAnswer: 0, explanation: 'My name is Lisa.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|Puede]] [[Lisa|Lisa]] [[sing|cantar]]?', options: ['[[Yes, very well|Sí, muy bien]]', '[[No|No]]', '[[Quite well|Bastante bien]]'], correctAnswer: 0, explanation: 'I can sing very well.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[well|bien]] [[does|toca]] [[she|ella]] [[play|toca]] [[the|el]] [[piano|piano]]?', options: ['[[Quite well|Bastante bien]]', '[[Very well|Muy bien]]', '[[Not at all|Nada]]'], correctAnswer: 0, explanation: 'I play the piano quite well.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Who|Quién]] [[can|puede]] [[cook|cocinar]] [[very well|muy bien]]?', options: ['[[Her brother|Su hermano]]', '[[Lisa|Lisa]]', '[[Her sister|Su hermana]]'], correctAnswer: 0, explanation: 'My brother can cook very well.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can|Puede]] [[Lisa|Lisa]] [[draw|dibujar]]?', options: ['[[No, not at all|No, nada]]', '[[Yes, very well|Sí, muy bien]]', '[[Quite well|Bastante bien]]'], correctAnswer: 0, explanation: 'I can\'t draw at all.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[is|es]] [[the|la]] [[sister|hermana]] [[described|descrita]]?', options: ['[[Hardworking|Trabajadora]]', '[[Creative|Creativa]]', '[[Fast|Rápida]]'], correctAnswer: 0, explanation: 'My sister is hardworking.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|Habla]] [[the|la]] [[sister|hermana]] [[speak|habla]] [[English|inglés]] [[well|bien]]?', options: ['[[Yes, very well|Sí, muy bien]]', '[[No|No]]', '[[Not at all|Nada]]'], correctAnswer: 0, explanation: 'She speaks English very well.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]]?', options: ['[[Different skills in a family|Diferentes habilidades en una familia]]', '[[Food|Comida]]', '[[School|Colegio]]'], correctAnswer: 0, explanation: 'Skills and abilities.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[creativo|creativo]]"?', options: ['[[Creative|Creative]]', '[[Hardworking|Hardworking]]', '[[Fast|Fast]]'], correctAnswer: 0, explanation: 'Creative = creativo.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[brother|hermano]] [[is|es]] ____.', options: ['[[creative|creativo]]', '[[slow|lento]]', '[[bad at cooking|malo cocinando]]'], correctAnswer: 0, explanation: 'He is creative.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[all|todos]] ____ [[different|diferentes]] [[skills|habilidades]].', options: ['[[have|tenemos]]', '[[has|tiene]]', '[[having|teniendo]]'], correctAnswer: 0, explanation: 'We all have different skills.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Lisa|Lisa]] ____ [[draw|dibujar]].', options: ['[[can\'t|no puede]]', '[[can|puede]]', '[[cans|incorrecto]]'], correctAnswer: 0, explanation: 'I can\'t draw at all.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[phrase|frase]] [[means|significa]] "[[muy bien|muy bien]]"?', options: ['[[Very well|Very well]]', '[[Quite well|Quite well]]', '[[Not at all|Not at all]]'], correctAnswer: 0, explanation: 'Very well = muy bien.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántas]] [[people|personas]] [[are|son]] [[mentioned|mencionadas]]?', options: ['[[Three (Lisa, brother, sister)|Tres]]', '[[Two|Dos]]', '[[Four|Cuatro]]'], correctAnswer: 0, explanation: 'Lisa, brother, sister.' }] }, topicName: 'Reading' },
  { id: 'a1-u37-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Skills|Habilidades]] = ____.', options: ['[[things you can do well|cosas que sabes hacer bien]]', '[[family|familia]]', '[[food|comida]]'], correctAnswer: 0, explanation: 'Skills = habilidades.' }] }, topicName: 'Reading' },
];
