/**
 * Unidad 27 — Lección 4: Comprensión auditiva (Pets & Animals)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión auditiva';
const TOPIC = 'Pets & Animals';
const LISTENING_TRANSCRIPT = `[[A|A]]: [[Do|¿Tienes]] [[you|]] [[have|tienes]] [[a|una]] [[pet|mascota]]? [[B|B]]: [[Yes|Sí]], [[I|yo]] [[have|tengo]] [[a|un]] [[dog|perro]]. [[He|Es]] [[is|muy]] [[very|]] [[friendly|amigable]]. [[A|A]]: [[What|Qué]] [[about|]] [[your|tu]] [[sister|hermana]]? [[B|B]]: [[She|Ella]] [[has|tiene]] [[a|un]] [[cat|gato]]. [[It|Es]] [[is|muy]] [[very|]] [[cute|mono]]. [[A|A]]: [[I|Yo]] [[like|me gustan]] [[farm|los animales de granja]] [[animals|animales]]. [[My|Mi]] [[uncle|tío]] [[has|tiene]] [[a|una]] [[farm|granja]] [[with|con]] [[cows|vacas]] [[and|y]] [[chickens|gallinas]]. [[B|B]]: [[Wild|Los animales salvajes]] [[animals|animales]] [[are|son]] [[dangerous|peligrosos]]. [[We|No]] [[don\'t|]] [[have|tenemos]] [[them|ellos]] [[at|en]] [[home|casa]].`;

const INSTRUCTIONS = 'Escucha el audio. Después contesta cada pregunta.';

export const UNIT_27_LESSON_4_LISTENING: Exercise[] = [
  { id: 'a1-u27-l4-l1', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Does|¿Tiene]] [[B|B]] [[have|tiene]] [[a|una]] [[pet|mascota]]?', options: ['[[Yes, a dog|Sí, un perro]]', '[[No|No]]', '[[A cat|Un gato]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l2', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Is|Es]] [[B\'s|el perro de B]] [[dog|perro]] [[friendly|amigable]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l3', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[pet|mascota]] [[does|tiene]] [[B\'s|la hermana de B]] [[sister|hermana]] [[have|tiene]]?', options: ['[[A cat|Un gato]]', '[[A dog|Un perro]]', '[[A rabbit|Un conejo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l4', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cómo]] [[is|es]] [[the|el]] [[sister\'s|gato de la hermana]] [[cat|gato]] [[described|descrito]]?', options: ['[[Very cute|Muy mono]]', '[[Dangerous|Peligroso]]', '[[Wild|Salvaje]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l5', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Who|Quién]] [[has|tiene]] [[a|una]] [[farm|granja]]?', options: ['[[A\'s uncle|El tío de A]]', '[[B|B]]', '[[B\'s sister|La hermana de B]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l6', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[animals|animales]] [[are|hay]] [[on|en]] [[the|la]] [[uncle\'s|granja del tío]] [[farm|granja]]?', options: ['[[Cows and chickens|Vacas y gallinas]]', '[[Dogs and cats|Perros y gatos]]', '[[Lions|Leones]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l7', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Are|Son]] [[wild|los animales salvajes]] [[animals|animales]] [[dangerous|peligrosos]]?', options: ['[[Yes|Sí]]', '[[No|No]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l8', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Do|¿Tenemos]] [[we|]] [[have|tenemos]] [[wild|salvajes]] [[animals|animales]] [[at|en]] [[home|casa]]?', options: ['[[No|No]]', '[[Yes|Sí]]', '[[The audio doesn\'t say|No se dice]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l9', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[dialogue|diálogo]] [[is|es]] ____.', options: ['[[about pets and animals|sobre mascotas y animales]]', '[[about food|sobre comida]]', '[[about work|sobre trabajo]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l10', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Qué]] [[word|palabra]] [[means|significa]] "[[amigable|amigable]]"?', options: ['[[Friendly|Friendly]]', '[[Dangerous|Dangerous]]', '[[Cute|Cute]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l11', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A|A]] ____ [[farm|granja]] [[animals|animales]].', options: ['[[likes|le gustan los]]', '[[like|gustar]]', '[[liking|gustando]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l12', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[B|B]] [[says|dice]] [[wild|salvajes]] [[animals|animales]] ____ [[dangerous|peligrosos]].', options: ['[[are|son]]', '[[is|es]]', '[[be|ser]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l13', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[cat|gato]] [[is|es]] ____.', options: ['[[very cute|muy mono]]', '[[very dangerous|muy peligroso]]', '[[very big|muy grande]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l14', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[does|pregunta]] [[A|A]] [[ask|pregunta]] [[first|primero]]?', options: ['[[Do you have a pet?|¿Tienes una mascota?]]', '[[Where is the farm?|¿Dónde está la granja?]]', '[[Are lions dangerous?|¿Son los leones peligrosos?]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
  { id: 'a1-u27-l4-l15', type: 'listening', level: 'A1', topic: TOPIC, difficulty: 'medium', transcript: LISTENING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Farm|Granja]] [[animals|animales]] [[include|incluyen]] ____.', options: ['[[cows and chickens|vacas y gallinas]]', '[[lions and tigers|leones y tigres]]', '[[dogs and cats|perros y gatos]]'], correctAnswer: 0 }] }, topicName: 'Listening' },
];
