/**
 * Unidad 58 — Lección 6: Expresión escrita (Health & Illness)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión escrita';
const TOPIC = 'Health & Illness';

export const UNIT_58_LESSON_6_WRITING: Exercise[] = [
  { id: 'a1-u58-l6-w1', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[see|ver]] [[a|un]] [[doctor|médico]] [[if|si]] [[you have|tienes]] [[a fever|fiebre]].', options: ['[[should|deberías]]', '[[should to|incorrecto]]', '[[shoulds|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'] }] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w2', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[take|tomar]] [[medicine|medicina]] [[for|para]] [[a headache|dolor de cabeza]].', options: ['[[should|deberías]]', '[[should to|incorrecto]]', '[[to should|incorrecto]]'], correctAnswer: 'should', acceptableAnswers: ['should'] }] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w3', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[You|Tú]] ____ [[go|ir]] [[to work|a trabajar]] [[when|cuando]] [[you are|estás]] [[ill|enfermo]].', options: ["[[shouldn't|no deberías]]", '[[should|deberías]]', '[[should to|incorrecto]]'], correctAnswer: "shouldn't", acceptableAnswers: ["shouldn't", 'should not'] }] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w4', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I have|Tengo]] ____ [[–|–]] [[I need|necesito]] [[medicine|medicina]].', options: ['[[a headache|dolor de cabeza]]', '[[a pharmacy|una farmacia]]', '[[a doctor|un médico]]'], correctAnswer: 'a headache', acceptableAnswers: ['a headache'] }] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w5', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Buy|Compra]] [[your|tu]] ____ [[at|en]] [[the|la]] [[pharmacy|farmacia]].', options: ['[[medicine|medicina]]', '[[doctor|médico]]', '[[fever|fiebre]]'], correctAnswer: 'medicine', acceptableAnswers: ['medicine'] }] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w6', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[You|Tú]] [[should|deberías]] [[see|ver]] [[a|un]] [[doctor|médico]] [[if|si]] [[you have|tienes]] [[a fever|fiebre]].', words: ['[[You|Tú]]', '[[should|deberías]]', '[[see|ver]]', '[[a|un]]', '[[doctor|médico]]', '[[if|si]]', '[[you have|tienes]]', '[[a fever|fiebre]].'] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w7', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[Go|Ve]] [[to|a]] [[the|la]] [[pharmacy|farmacia]] [[for|para]] [[medicine|medicina]].', words: ['[[Go|Ve]]', '[[to|a]]', '[[the|la]]', '[[pharmacy|farmacia]]', '[[for|para]]', '[[medicine|medicina]].'] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w8', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[You|Tú]] [[shouldn\'t|no deberías]] [[go|ir]] [[to work|a trabajar]] [[when|cuando]] [[you are ill|estás enfermo]].', words: ['[[You|Tú]]', '[[shouldn\'t|no deberías]]', '[[go|ir]]', '[[to work|a trabajar]]', '[[when|cuando]]', '[[you are ill|estás enfermo]].'] }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w9', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: consejo para alguien con dolor de cabeza (should + take medicine o rest).', prompt: '____.', minWords: 6, maxWords: 14, modelExample: '[[You|Tú]] [[should|deberías]] [[take|tomar]] [[medicine|medicina]] [[or|o]] [[rest|descansar]] [[for|para]] [[a|un]] [[headache|dolor de cabeza]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w10', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe una frase: dónde comprar medicina.', prompt: '____.', minWords: 5, maxWords: 12, modelExample: '[[You|Tú]] [[can|puedes]] [[buy|comprar]] [[medicine|medicina]] [[at|en]] [[the|la]] [[pharmacy|farmacia]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w11', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: qué deberías hacer si tienes resfriado (should) y qué no (shouldn\'t).', prompt: '____. ____.', minWords: 12, maxWords: 28, modelExample: '[[You|Tú]] [[should|deberías]] [[rest|descansar]] [[and|y]] [[drink|beber]] [[water|agua]]. [[You|Tú]] [[shouldn\'t|no deberías]] [[go|ir]] [[to work|a trabajar]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w12', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe: cuándo deberías ver a un médico.', prompt: '____.', minWords: 6, maxWords: 16, modelExample: '[[You|Tú]] [[should|deberías]] [[see|ver]] [[a|un]] [[doctor|médico]] [[if|si]] [[you have|tienes]] [[a fever|fiebre]] [[or|o]] [[feel very ill|te sientes muy enfermo]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w13', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3–4 frases): estás enfermo, tienes dolor de cabeza, qué haces (rest, medicine, pharmacy).', prompt: '____.', minWords: 22, maxWords: 50, modelExample: '[[I|Yo]] [[feel|me siento]] [[ill|enfermo]] [[today|hoy]]. [[I have|Tengo]] [[a|un]] [[headache|dolor de cabeza]]. [[I should|Debería]] [[rest|descansar]] [[and|y]] [[take|tomar]] [[medicine|medicina]] [[from|de]] [[the|la]] [[pharmacy|farmacia]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w14', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 consejos de salud con should y shouldn\'t.', prompt: '____.', minWords: 12, maxWords: 30, modelExample: '[[You|Tú]] [[should|deberías]] [[drink|beber]] [[water|agua]] [[when|cuando]] [[you have|tienes]] [[a cold|resfriado]]. [[You|Tú]] [[shouldn\'t|no deberías]] [[work|trabajar]] [[when|cuando]] [[you are|estás]] [[ill|enfermo]].' }, topicName: 'Writing' },
  { id: 'a1-u58-l6-w15', type: 'writing', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Escribe: diferencia entre headache, fever y cold en una frase cada una.', prompt: '____.', minWords: 15, maxWords: 35, modelExample: '[[A headache|Un dolor de cabeza]] [[is|es]] [[pain in your head|dolor en la cabeza]]. [[A fever|Una fiebre]] [[is|es]] [[high temperature|temperatura alta]]. [[A cold|Un resfriado]] [[is|es]] [[illness with cough|enfermedad con tos]] [[and|y]] [[runny nose|mocos]].' }, topicName: 'Writing' },
];
