/**
 * Unidad 48 — Lección 3: Comprensión lectora (Sightseeing)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Comprensión lectora';
const TOPIC = 'Sightseeing';
const READING_TRANSCRIPT = `[[Yesterday|Ayer]] [[we|nosotros]] [[did|hicimos]] [[sightseeing|turismo]] [[in|en]] [[the city|la ciudad]]. [[We|Nosotros]] [[visited|visitamos]] [[the|el]] [[most famous|más famoso]] [[museum|museo]]. [[It is|Es]] [[the oldest|el más antiguo]] [[building|edificio]] [[in|en]] [[town|el pueblo]]. [[In|En]] [[the square|la plaza]] [[there is|hay]] [[a|una]] [[tall|alta]] [[statue|estatua]]. [[We|Nosotros]] [[did|hicimos]] [[a|una]] [[guided tour|visita guiada]] [[of|de]] [[the monument|el monumento]]. [[The|El]] [[guide|guía]] [[explained|explicó]] [[the history|la historia]]. [[It was|Fue]] [[very|muy]] [[interesting|interesante]]. [[We|Nosotros]] [[took|sacamos]] [[photos|fotos]].`;

const INSTRUCTIONS = 'Lee el texto. Después contesta cada pregunta.';

export const UNIT_48_LESSON_3_READING: Exercise[] = [
  { id: 'a1-u48-l3-r1', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[did they do|hicieron]] [[yesterday|ayer]]?', options: ['[[Sightseeing in the city|Turismo en la ciudad]]', '[[Stay at hotel|Quedarse en hotel]]', '[[Go to the beach|Ir a la playa]]'], correctAnswer: 0, explanation: 'Yesterday we did sightseeing in the city.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r2', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[museum|museo]] [[did they visit|visitaron]]?', options: ['[[The most famous|El más famoso]]', '[[The smallest|El más pequeño]]', '[[The newest|El más nuevo]]'], correctAnswer: 0, explanation: 'We visited the most famous museum.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r3', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[is|es]] [[the building|el edificio]]?', options: ['[[The oldest in town|El más antiguo del pueblo]]', '[[The newest|El más nuevo]]', '[[The biggest|El más grande]]'], correctAnswer: 0, explanation: 'It is the oldest building in town.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r4', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where|Dónde]] [[is|está]] [[the statue|la estatua]]?', options: ['[[In the square|En la plaza]]', '[[In the museum|En el museo]]', '[[At home|En casa]]'], correctAnswer: 0, explanation: 'In the square there is a tall statue.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r5', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[did they do|hicieron]] [[at the monument|en el monumento]]?', options: ['[[A guided tour|Una visita guiada]]', '[[Shopping|Compras]]', '[[Swimming|Natación]]'], correctAnswer: 0, explanation: 'We did a guided tour of the monument.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r6', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Qué]] [[did the guide explain|explicó el guía]]?', options: ['[[The history|La historia]]', '[[The price|El precio]]', '[[The food|La comida]]'], correctAnswer: 0, explanation: 'The guide explained the history.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r7', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Was it|Fue]] [[interesting|interesante]]?', options: ['[[Yes, very interesting|Sí, muy interesante]]', '[[No|No]]', '[[The text does not say|No lo dice]]'], correctAnswer: 0, explanation: 'It was very interesting.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r8', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Guided tour|Visita guiada]] = ____.', options: ['[[tour with a guide who explains|visita con guía que explica]]', '[[museum only|solo museo]]', '[[statue|estatua]]'], correctAnswer: 0, explanation: 'Guided tour = visita con guía.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r9', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The most famous|El más famoso]] = ____.', options: ['[[superlative: no other is more famous|superlativo: ninguno es más famoso]]', '[[comparative|comparativo]]', '[[present|presente]]'], correctAnswer: 0, explanation: 'Superlative form.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r10', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Statue|Estatua]] = ____.', options: ['[[figure in stone or metal|figura en piedra o metal]]', '[[museum|museo]]', '[[monument|monumento]]'], correctAnswer: 0, explanation: 'Statue = estatua.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r11', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The text|El texto]] [[is about|trata de]] ____.', options: ['[[sightseeing: museum, monument, guided tour|turismo: museo, monumento, visita guiada]]', '[[hotel|hotel]]', '[[beach|playa]]'], correctAnswer: 0, explanation: 'Sightseeing, museum, statue, guided tour.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r12', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The oldest|El más antiguo]] = ____.', options: ['[[superlative of old|superlativo de old]]', '[[comparative|comparativo]]', '[[present|presente]]'], correctAnswer: 0, explanation: 'Old → oldest.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r13', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Square|Plaza]] = ____.', options: ['[[open place in town|lugar abierto en ciudad]]', '[[museum|museo]]', '[[monument|monumento]]'], correctAnswer: 0, explanation: 'Square = plaza.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r14', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They took photos|Sacaron fotos]] = ____.', options: ['[[they made photographs|hicieron fotografías]]', '[[they bought photos|compraron fotos]]', '[[they lost photos|perdieron fotos]]'], correctAnswer: 0, explanation: 'Take photos = sacar fotos.' }] }, topicName: 'Reading' },
  { id: 'a1-u48-l3-r15', type: 'reading', level: 'A1', topic: TOPIC, difficulty: 'easy', transcript: READING_TRANSCRIPT, content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]]?', options: ['[[Sightseeing: museum, statue, guided tour|Turismo: museo, estatua, visita guiada]]', '[[Shopping|Compras]]', '[[Hotel|Hotel]]'], correctAnswer: 0, explanation: 'Sightseeing, museum, monument, guided tour.' }] }, topicName: 'Reading' },
];
