/**
 * Unidad 55 — Lección 2: Vocabulario (Clothing Store)
 * S, M, L, XL, changing room, sale.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Vocabulario: tienda de ropa';
const TOPIC = 'Clothing Store';

export const UNIT_55_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u55-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[S|S]] = ____.', options: ['[[small size|talla pequeña]]', '[[medium|mediana]]', '[[large|grande]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[M|M]] = ____.', options: ['[[medium size|talla mediana]]', '[[small|pequeña]]', '[[large|grande]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[L|L]] = ____.', options: ['[[large size|talla grande]]', '[[small|pequeña]]', '[[medium|mediana]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[XL|XL]] = ____.', options: ['[[extra large|extra grande]]', '[[small|pequeña]]', '[[medium|mediana]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Changing room|Probador]] = ____.', options: ['[[place to try on clothes|lugar para probarse ropa]]', '[[shop entrance|entrada tienda]]', '[[cash desk|caja]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v6', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Sale|Rebajas]] = ____.', options: ['[[reduced prices|precios reducidos]]', '[[closed|cerrado]]', '[[new collection|nueva colección]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[S|S]]', right: '[[small|pequeña]]' }, { id: 'p2', left: '[[M|M]]', right: '[[medium|mediana]]' }, { id: 'p3', left: '[[L|L]]', right: '[[large|grande]]' }, { id: 'p4', left: '[[XL|XL]]', right: '[[extra large|extra grande]]' }, { id: 'p5', left: '[[changing room|probador]]', right: '[[try on clothes|probarse ropa]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v8', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Relaciona.', pairs: [{ id: 'p1', left: '[[sale|rebajas]]', right: '[[cheaper prices|precios más bajos]]' }, { id: 'p2', left: '[[too big|demasiado grande]]', right: '[[doesn\'t fit|no queda bien]]' }, { id: 'p3', left: '[[big enough|suficientemente grande]]', right: '[[it fits|queda bien]]' }, { id: 'p4', left: '[[size|talla]]', right: '[[S, M, L, XL|S, M, L, XL]]' }, { id: 'p5', left: '[[fit|quedar]]', right: '[[right size|talla correcta]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Do you have|Tienen]] [[this|esta]] [[in|en]] ____ [[M|M]]?', options: ['[[size|talla]]', '[[sale|rebajas]]', '[[changing room|probador]]'], correctAnswer: 'size', acceptableAnswers: ['size'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[Where is|Dónde está]] [[the|el]] ____ [[room|probador]]?', options: ['[[changing|probador]]', '[[sale|rebajas]]', '[[size|talla]]'], correctAnswer: 'changing', acceptableAnswers: ['changing'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v11', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[This|Esta]] [[is|está]] ____ [[too|demasiado]] [[small|pequeña]].', options: ['[[too|demasiado]]', '[[enough|suficiente]]', '[[size|talla]]'], correctAnswer: 'too', acceptableAnswers: ['too'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Size|Talla]] = ____.', options: ['[[S, M, L, XL|S, M, L, XL]]', '[[price|precio]]', '[[colour|color]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[It doesn\'t fit|No queda bien]] = ____.', options: ['[[wrong size (too big or too small)|talla incorrecta]]', '[[it\'s perfect|es perfecto]]', '[[it\'s on sale|está en rebajas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v14', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[S, M, L, XL|S, M, L, XL]] [[are|son]] [[clothing sizes|tallas de ropa]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
  { id: 'a1-u55-l2-v15', type: 'true-false', level: 'A1', topic: TOPIC, difficulty: 'hard', content: { title: LESSON_TITLE, instructions: 'Verdadero o falso.', questions: [{ question: '[[Sale|Sale]] [[means|significa]] [[lower prices|precios más bajos]].', correctAnswer: true }] }, topicName: 'Vocabulary' },
];
