/**
 * Unidad 28 — Lección 2: Vocabulario (Partes del cuerpo)
 * head, arms, legs, hands, feet, face.
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Vocabulario: head, arms, legs, hands, feet, face';
const TOPIC = 'Body Parts';

export const UNIT_28_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a1-u28-l2-v1', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige. "Cabeza" en inglés.', questions: [{ question: '[[I|Yo]] [[have|tengo]] [[got|]] [[a|una]] ____.', options: ['[[head|cabeza]]', '[[arm|brazo]]', '[[leg|pierna]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v2', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[We|Tenemos]] [[have|tenemos]] [[got|]] [[two|dos]] ____.', options: ['[[arms|brazos]]', '[[heads|cabezas]]', '[[faces|caras]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v3', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[She|Ella]] [[has|tiene]] [[got|]] [[long|largas]] ____.', options: ['[[legs|piernas]]', '[[hands|manos]]', '[[feet|pies]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v4', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[I|Yo]] [[wash|lavo]] [[my|mis]] ____ [[every|cada]] [[day|día]].', options: ['[[hands|manos]]', '[[legs|piernas]]', '[[arms|brazos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v5', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[My|Mis]] ____ [[are|son]] [[big|grandes]]. [[I|Yo]] [[wear|uso]] [[size|talla]] [[42|42]].', options: ['[[feet|pies]]', '[[hands|manos]]', '[[face|cara]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v6', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona palabra con significado.', pairs: [{ id: 'p1', left: '[[head|cabeza]]', right: '[[part of body with brain|parte del cuerpo con el cerebro]]' }, { id: 'p2', left: '[[face|cara]]', right: '[[front of head with eyes, nose, mouth|frente de la cabeza con ojos, nariz, boca]]' }, { id: 'p3', left: '[[arm|brazo]]', right: '[[from shoulder to hand|del hombro a la mano]]' }, { id: 'p4', left: '[[leg|pierna]]', right: '[[from hip to foot|de la cadera al pie]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v7', type: 'matching', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona con la parte del cuerpo.', pairs: [{ id: 'p1', left: '[[I have two|Tengo dos]]', right: '[[arms and two legs|brazos y dos piernas]]' }, { id: 'p2', left: '[[I have five fingers on each|Tengo cinco dedos en cada]]', right: '[[hand|mano]]' }, { id: 'p3', left: '[[My|Mi]]', right: '[[face has eyes, nose, mouth|cara tiene ojos, nariz, boca]]' }, { id: 'p4', left: '[[I stand on my two|Me apoyo en mis dos]]', right: '[[feet|pies]]' }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v8', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[He|Él]] [[has|tiene]] [[got|]] [[a|una]] ____ [[and|y]] [[two|dos]] [[eyes|ojos]].', options: ['[[face|cara]]', '[[head|cabeza]]', '[[hand|mano]]'], correctAnswer: 'face', acceptableAnswers: ['face'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v9', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[She|Ella]] [[has|tiene]] [[got|]] [[small|pequeñas]] ____.', options: ['[[hands|manos]]', '[[legs|piernas]]', '[[arms|brazos]]'], correctAnswer: 'hands', acceptableAnswers: ['hands'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v10', type: 'fill-blank', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa.', questions: [{ question: '[[I|Yo]] [[have|tengo]] [[got|]] [[two|dos]] ____ [[and|y]] [[two|dos]] [[feet|pies]].', options: ['[[legs|piernas]]', '[[arms|brazos]]', '[[hands|manos]]'], correctAnswer: 'legs', acceptableAnswers: ['legs'] }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v11', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Hand|Mano]] [[–|–]] [[plural|plural]] [[is|es]] ____.', options: ['[[hands|hands]]', '[[handes|handes]]', '[[feets|feets]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v12', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[Foot|Pie]] [[–|–]] [[plural|plural]] [[is|es]] ____.', options: ['[[feet|feet]]', '[[foots|foots]]', '[[footes|footes]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v13', type: 'multiple-choice', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Elige.', questions: [{ question: '[[On|En]] [[my|mi]] ____ [[I|tengo]] [[have|]] [[got|]] [[eyes|ojos]], [[a|una]] [[nose|nariz]] [[and|y]] [[a|una]] [[mouth|boca]].', options: ['[[face|cara]]', '[[head|cabeza]]', '[[hand|mano]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v14', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[I|Yo]] [[have|tengo]] [[got|]] [[two|dos]] [[arms|brazos]] [[and|y]] [[two|dos]] [[legs|piernas]].', words: ['[[I|Yo]]', '[[have|tengo]]', '[[got|]]', '[[two|dos]]', '[[arms|brazos]]', '[[and|y]]', '[[two|dos]]', '[[legs|piernas]].'] }, topicName: 'Vocabulary' },
  { id: 'a1-u28-l2-v15', type: 'sentence-building', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Ordena.', correctSentence: '[[She|Ella]] [[has|tiene]] [[got|]] [[a|una]] [[beautiful|hermosa]] [[face|cara]].', words: ['[[She|Ella]]', '[[has|tiene]]', '[[got|]]', '[[a|una]]', '[[beautiful|hermosa]]', '[[face|cara]].'] }, topicName: 'Vocabulary' },
];
