/**
 * Unidad 14 — Lección 5: Expresión oral
 * 15 ejercicios: Do you…? Yes I do / No I don't; hábitos.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = 'Expresión oral';
const TOPIC = 'Present Simple: I, You, We, They';

export const UNIT_14_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a1-u14-l5-s1', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[Do|¿]] [[you|tú]] [[like|te gusta]] [[coffee|café]]? [[Yes|Sí]], [[I|yo]] [[do|sí]].', expectedResponse: 'Do you like coffee? Yes, I do.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s2', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[No|No]], [[I|yo]] [[don\'t|no]] [[watch|veo]] [[TV|la tele]] [[in|por]] [[the|la]] [[morning|mañana]].', expectedResponse: 'No, I don\'t watch TV in the morning.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s3', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Do|¿]] [[you|tú]] [[cook|cocinas]]? [[No|No]], [[I|yo]] [[don\'t|no]].', expectedResponse: 'Do you cook? No, I don\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s4', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[don\'t|no]] [[play|jugamos]] [[football|fútbol]].', expectedResponse: 'We don\'t play football.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s5', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[Do|¿]] [[they|ellos]] [[do|hacen]] [[the|las]] [[housework|tareas]]? [[Yes|Sí]], [[they|ellos]] [[do|sí]].', expectedResponse: 'Do they do the housework? Yes, they do.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s6', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[I|Yo]] [[don\'t|no]] [[like|me gusta]] [[getting up early|levantarme temprano]].', expectedResponse: 'I don\'t like getting up early.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s7', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[Do|¿]] [[you|tú]] [[read|lees]] [[books|libros]]? [[Yes|Sí]], [[I|yo]] [[do|sí]].', expectedResponse: 'Do you read books? Yes, I do.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s8', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta. ¿Te gusta la música?', targetText: '[[Do|¿]] [[you|tú]] [[like|te gusta]] [[music|la música]]? ____.', expectedResponse: 'Yes, I do. / No, I don\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s9', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta. ¿Cocinas?', targetText: '[[Do|¿]] [[you|tú]] ____? ____.', expectedResponse: 'Do you cook? Yes, I do. / No, I don\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s10', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta una cosa que no haces (por ejemplo: I don\'t watch TV).', targetText: '[[I|Yo]] ____ ____.', expectedResponse: 'I don\'t [verb]...' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s11', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Haz la pregunta "Do you do the housework?" y responde (sí o no).', targetText: '____? ____.', expectedResponse: 'Do you do the housework? Yes, I do. / No, I don\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s12', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta la pregunta y respuesta modelo.', targetText: '[[Do|¿]] [[you|tú]] [[play|juegas]] [[tennis|tenis]]? [[No|No]], [[I|yo]] [[don\'t|no]]. [[I|Yo]] [[prefer|prefiero]] [[football|fútbol]].', expectedResponse: 'Do you play tennis? No, I don\'t. I prefer football.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s13', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They|Ellos]] [[don\'t|no]] [[eat|comen]] [[meat|carne]]. [[They|Ellos]] [[are|son]] [[vegetarian|vegetarianos]].', expectedResponse: 'They don\'t eat meat. They are vegetarian.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s14', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Pregunta en voz alta si alguien ve la tele por la tarde y responde tú.', targetText: '____? ____.', expectedResponse: 'Do you watch TV in the evening? Yes, I do. / No, I don\'t.' }, topicName: 'Speaking' },
  { id: 'a1-u14-l5-s15', type: 'pronunciation', level: 'A1', topic: TOPIC, difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: di dos cosas que haces y dos que no haces (hábitos).', targetText: '____. ____. ____. ____.', expectedResponse: 'I [verb]... I [verb]... I don\'t [verb]... I don\'t [verb]...' }, topicName: 'Speaking' },
];
