name: focusonenglish
region: nyc
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: u7934364978-maker/focusonenglish
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 180
      period_seconds: 30
      timeout_seconds: 20
      success_threshold: 1
      failure_threshold: 10
