BEGIN;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U26', 'ingles-b2', 26, 'Unit 26', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B1_I1', 'ingles-b2-U26', 1, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"En inglés, cuando usamos ''seldom'' al inicio de una oración, se requiere inversión de sujeto y verbo, formando ''Seldom do we...''.","stimulus_en":"Seldom ___ we see such talented individuals in our field.","options":[{"id":"o1","text":"do"},{"id":"o2","text":"does"},{"id":"o3","text":"are"},{"id":"o4","text":"is"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B1_I2', 'ingles-b2-U26', 2, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La inversión se utiliza aquí porque ''rarely'' introduce la oración, requiriendo que usemos ''do'' para la forma correcta.","stimulus_en":"Rarely ___ we receive feedback that is this constructive.","options":[{"id":"o1","text":"have"},{"id":"o2","text":"do"},{"id":"o3","text":"are"},{"id":"o4","text":"has"}],"correct_answer":"o2","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B1_I3', 'ingles-b2-U26', 3, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"En la frase con ''never before'', usamos ''had'' para indicar que es una experiencia pasada que no ha ocurrido antes.","stimulus_en":"Never before ___ I encountered such a challenging project.","options":[{"id":"o1","text":"had"},{"id":"o2","text":"have"},{"id":"o3","text":"did"},{"id":"o4","text":"does"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B1_I4', 'ingles-b2-U26', 4, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La estructura ''Only after'' causa que invirtamos el sujeto y el verbo, aquí ''did'' se usa correctamente.","stimulus_en":"Only after the meeting ___ we understand the new strategy.","options":[{"id":"o1","text":"did"},{"id":"o2","text":"have"},{"id":"o3","text":"do"},{"id":"o4","text":"are"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B1_I5', 'ingles-b2-U26', 5, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La inversión se aplica después de ''hardly'' y debemos usar ''was'' para mantener la concordancia temporal de la oración.","stimulus_en":"Hardly ___ the report finalized when we received new data.","options":[{"id":"o1","text":"was"},{"id":"o2","text":"is"},{"id":"o3","text":"were"},{"id":"o4","text":"has"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B2_I1', 'ingles-b2-U26', 6, 'multiple_choice', 'What is the main purpose of a lecture?', '{"prompt_es":"What is the main purpose of a lecture?","mastery_tag":"listening:b2-lectures","explanation":"El objetivo principal de una conferencia es compartir información con la audiencia sobre un tema específico.","stimulus_en":"","options":[{"id":"o1","text":"To entertain the audience"},{"id":"o2","text":"To share information"},{"id":"o3","text":"To sell products"},{"id":"o4","text":"To conduct interviews"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B2_I2', 'ingles-b2-U26', 7, 'multiple_choice', 'Which of the following is a key feature of effective presentations?', '{"prompt_es":"Which of the following is a key feature of effective presentations?","mastery_tag":"listening:b2-lectures","explanation":"Las ayudas visuales son fundamentales en presentaciones efectivas, ya que ayudan a captar la atención y a entender mejor el contenido.","stimulus_en":"","options":[{"id":"o1","text":"Long and complex sentences"},{"id":"o2","text":"Visual aids"},{"id":"o3","text":"Silent moments"},{"id":"o4","text":"No interaction"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B2_I3', 'ingles-b2-U26', 8, 'multiple_choice', 'How should a speaker engage their audience during a lecture?', '{"prompt_es":"How should a speaker engage their audience during a lecture?","mastery_tag":"listening:b2-lectures","explanation":"Hacer preguntas retóricas puede involucrar a la audiencia y fomentar la reflexión sobre el tema presentado.","stimulus_en":"","options":[{"id":"o1","text":"By reading directly from notes"},{"id":"o2","text":"By asking rhetorical questions"},{"id":"o3","text":"By avoiding eye contact"},{"id":"o4","text":"By speaking monotonously"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B2_I4', 'ingles-b2-U26', 9, 'multiple_choice', 'What is often used to summarize a lecture at the end?', '{"prompt_es":"What is often used to summarize a lecture at the end?","mastery_tag":"listening:b2-lectures","explanation":"Una buena conclusión es esencial para resumir los puntos clave y dejar una impresión duradera en la audiencia.","stimulus_en":"","options":[{"id":"o1","text":"An introduction"},{"id":"o2","text":"A conclusion"},{"id":"o3","text":"More questions"},{"id":"o4","text":"Visual distractions"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B2_I5', 'ingles-b2-U26', 10, 'multiple_choice', 'Why is it important to know the audience''s background before a presentation?', '{"prompt_es":"Why is it important to know the audience''s background before a presentation?","mastery_tag":"listening:b2-lectures","explanation":"Conocer el contexto de la audiencia ayuda a adaptar el contenido para que sea comprensible y relevante para ellos.","stimulus_en":"","options":[{"id":"o1","text":"To adjust the length of the presentation"},{"id":"o2","text":"To make it more entertaining"},{"id":"o3","text":"To tailor the content to their knowledge"},{"id":"o4","text":"To use complicated vocabulary"}],"correct_answer":"o3","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U26_B3_I1', 'ingles-b2-U26', 11, 'fill_blanks', 'Complete the sentences by forming the words from the base provided.

Base words: (1) CHANGE, (2) COMPETE, (3) IMPORT, (4) SKILL, (5) COMMUNICATE', '{"prompt_es":"Complete the sentences by forming the words from the base provided.\n\nBase words: (1) CHANGE, (2) COMPETE, (3) IMPORT, (4) SKILL, (5) COMMUNICATE","mastery_tag":"vocabulary:b2-media","main_text":"The rise of social media has brought many (1)___ (CHANGE) in how we consume news. Traditional journalism has faced (2)___ (COMPETE) from online platforms that provide instant updates. However, the (3)___ (IMPORT) of fact-checking has never been greater, as misinformation spreads rapidly. Journalists today must enhance their (4)___ (SKILL) to adapt to these new challenges. Effective (5)___ (COMMUNICATE) is crucial for maintaining trust in media.","correct_answer":["changes","competition","importance","skills","communication"],"explanation":"(1) La palabra ''change'' se convierte en ''changes'' para referirse a múltiples cambios.\n(2) La palabra ''compete'' se transforma en ''competition'', que es el sustantivo que describe el acto de competir.\n(3) La palabra ''import'' cambia a ''importance'' para denotar el significado de ser importante.\n(4) La palabra ''skill'' en plural ''skills'' se refiere a las capacidades necesarias para desempeñar un trabajo.\n(5) La palabra ''communicate'' se convierte en ''communication'', que se refiere al proceso de intercambio de información.","complexity":3,"concept_tags":["vocabulary","media","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U27', 'ingles-b2', 27, 'Unit 27', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B1_I1', 'ingles-b2-U27', 1, 'multiple_choice', 'What are the primary causes of climate change according to most scientists?', '{"prompt_es":"What are the primary causes of climate change according to most scientists?","mastery_tag":"reading:b2-complex-texts","explanation":"La mayoría de los científicos creen que las actividades humanas son las principales causas del cambio climático.","stimulus_en":"Climate change is one of the most pressing issues of our time, affecting ecosystems and human societies worldwide. Many scientists argue that human activities, particularly the burning of fossil fuels and deforestation, are the primary causes of the recent changes in our climate. These activities increase the concentration of greenhouse gases in the atmosphere, leading to global warming and extreme weather events. On the other hand, some skeptics question the extent of human impact, citing natural climate variability as a significant factor. They argue that the Earth has gone through cycles of warming and cooling long before industrialization. However, the majority of climate scientists emphasize that while natural cycles do occur, the current rapid changes are unprecedented and largely driven by human actions. To address climate change effectively, comprehensive international cooperation and innovative solutions, such as renewable energy investments, are essential. Without these efforts, the consequences could be dire, including rising sea levels, food insecurity, and widespread biodiversity loss.","correct_answer":"o1","options":[{"id":"o1","text":"Human activities like burning fossil fuels and deforestation."},{"id":"o2","text":"They question the extent of human impact and cite natural variability."},{"id":"o3","text":"Rising sea levels."},{"id":"o4","text":"They are unprecedented and largely driven by human actions."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B1_I2', 'ingles-b2-U27', 2, 'multiple_choice', 'What do skeptics believe about climate change?', '{"prompt_es":"What do skeptics believe about climate change?","mastery_tag":"reading:b2-complex-texts","explanation":"Los escépticos creen que el impacto humano no es tan grande y que hay variabilidad climática natural.","stimulus_en":"Climate change is one of the most pressing issues of our time, affecting ecosystems and human societies worldwide. Many scientists argue that human activities, particularly the burning of fossil fuels and deforestation, are the primary causes of the recent changes in our climate. These activities increase the concentration of greenhouse gases in the atmosphere, leading to global warming and extreme weather events. On the other hand, some skeptics question the extent of human impact, citing natural climate variability as a significant factor. They argue that the Earth has gone through cycles of warming and cooling long before industrialization. However, the majority of climate scientists emphasize that while natural cycles do occur, the current rapid changes are unprecedented and largely driven by human actions. To address climate change effectively, comprehensive international cooperation and innovative solutions, such as renewable energy investments, are essential. Without these efforts, the consequences could be dire, including rising sea levels, food insecurity, and widespread biodiversity loss.","correct_answer":"o1","options":[{"id":"o1","text":"They question the extent of human impact and cite natural variability."},{"id":"o2","text":"Human activities like burning fossil fuels and deforestation."},{"id":"o3","text":"Rising sea levels."},{"id":"o4","text":"They are unprecedented and largely driven by human actions."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B1_I3', 'ingles-b2-U27', 3, 'multiple_choice', 'According to the passage, what is a significant consequence of not addressing climate change?', '{"prompt_es":"According to the passage, what is a significant consequence of not addressing climate change?","mastery_tag":"reading:b2-complex-texts","explanation":"El texto menciona que una consecuencia significativa de no abordar el cambio climático son los niveles del mar en aumento.","stimulus_en":"Climate change is one of the most pressing issues of our time, affecting ecosystems and human societies worldwide. Many scientists argue that human activities, particularly the burning of fossil fuels and deforestation, are the primary causes of the recent changes in our climate. These activities increase the concentration of greenhouse gases in the atmosphere, leading to global warming and extreme weather events. On the other hand, some skeptics question the extent of human impact, citing natural climate variability as a significant factor. They argue that the Earth has gone through cycles of warming and cooling long before industrialization. However, the majority of climate scientists emphasize that while natural cycles do occur, the current rapid changes are unprecedented and largely driven by human actions. To address climate change effectively, comprehensive international cooperation and innovative solutions, such as renewable energy investments, are essential. Without these efforts, the consequences could be dire, including rising sea levels, food insecurity, and widespread biodiversity loss.","correct_answer":"o1","options":[{"id":"o1","text":"Rising sea levels."},{"id":"o2","text":"Human activities like burning fossil fuels and deforestation."},{"id":"o3","text":"They question the extent of human impact and cite natural variability."},{"id":"o4","text":"They are unprecedented and largely driven by human actions."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B1_I4', 'ingles-b2-U27', 4, 'multiple_choice', 'What do the majority of climate scientists emphasize about current climate changes?', '{"prompt_es":"What do the majority of climate scientists emphasize about current climate changes?","mastery_tag":"reading:b2-complex-texts","explanation":"La mayoría de los científicos climáticos enfatizan que los cambios actuales son sin precedentes y en gran parte impulsados por acciones humanas.","stimulus_en":"Climate change is one of the most pressing issues of our time, affecting ecosystems and human societies worldwide. Many scientists argue that human activities, particularly the burning of fossil fuels and deforestation, are the primary causes of the recent changes in our climate. These activities increase the concentration of greenhouse gases in the atmosphere, leading to global warming and extreme weather events. On the other hand, some skeptics question the extent of human impact, citing natural climate variability as a significant factor. They argue that the Earth has gone through cycles of warming and cooling long before industrialization. However, the majority of climate scientists emphasize that while natural cycles do occur, the current rapid changes are unprecedented and largely driven by human actions. To address climate change effectively, comprehensive international cooperation and innovative solutions, such as renewable energy investments, are essential. Without these efforts, the consequences could be dire, including rising sea levels, food insecurity, and widespread biodiversity loss.","correct_answer":"o1","options":[{"id":"o1","text":"They are unprecedented and largely driven by human actions."},{"id":"o2","text":"Human activities like burning fossil fuels and deforestation."},{"id":"o3","text":"They question the extent of human impact and cite natural variability."},{"id":"o4","text":"Rising sea levels."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B1_I5', 'ingles-b2-U27', 5, 'multiple_choice', 'What solutions do experts suggest to combat climate change?', '{"prompt_es":"What solutions do experts suggest to combat climate change?","mastery_tag":"reading:b2-complex-texts","explanation":"Los expertos sugieren soluciones como la cooperación internacional y las inversiones en energías renovables para combatir el cambio climático.","stimulus_en":"Climate change is one of the most pressing issues of our time, affecting ecosystems and human societies worldwide. Many scientists argue that human activities, particularly the burning of fossil fuels and deforestation, are the primary causes of the recent changes in our climate. These activities increase the concentration of greenhouse gases in the atmosphere, leading to global warming and extreme weather events. On the other hand, some skeptics question the extent of human impact, citing natural climate variability as a significant factor. They argue that the Earth has gone through cycles of warming and cooling long before industrialization. However, the majority of climate scientists emphasize that while natural cycles do occur, the current rapid changes are unprecedented and largely driven by human actions. To address climate change effectively, comprehensive international cooperation and innovative solutions, such as renewable energy investments, are essential. Without these efforts, the consequences could be dire, including rising sea levels, food insecurity, and widespread biodiversity loss.","correct_answer":"o1","options":[{"id":"o1","text":"International cooperation and renewable energy investments."},{"id":"o2","text":"Human activities like burning fossil fuels and deforestation."},{"id":"o3","text":"They question the extent of human impact and cite natural variability."},{"id":"o4","text":"Rising sea levels."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B2_I1', 'ingles-b2-U27', 6, 'multiple_choice', 'Choose the correct option to complete the sentences using participle clauses.', '{"prompt_es":"Choose the correct option to complete the sentences using participle clauses.","mastery_tag":"grammar:b2-participle-clauses","explanation":"La opción correcta es ''Although'' porque indica una contrariedad entre el clima y la decisión de ir de excursión.","stimulus_en":"___ the weather was terrible, we decided to go for a hike.","options":[{"id":"o1","text":"Despite"},{"id":"o2","text":"Because"},{"id":"o3","text":"Although"},{"id":"o4","text":"Since"}],"correct_answer":"o3","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B2_I2', 'ingles-b2-U27', 7, 'multiple_choice', 'Choose the correct option to complete the sentences using participle clauses.', '{"prompt_es":"Choose the correct option to complete the sentences using participle clauses.","mastery_tag":"grammar:b2-participle-clauses","explanation":"Aquí, ''encouraged'' es un participio pasado que describe a los estudiantes en relación con la acción de ser motivados por el profesor.","stimulus_en":"The students, ___ by the teacher, completed their assignments.","options":[{"id":"o1","text":"encouraged"},{"id":"o2","text":"encouraging"},{"id":"o3","text":"to encourage"},{"id":"o4","text":"encourage"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B2_I3', 'ingles-b2-U27', 8, 'multiple_choice', 'Choose the correct option to complete the sentences using participle clauses.', '{"prompt_es":"Choose the correct option to complete the sentences using participle clauses.","mastery_tag":"grammar:b2-participle-clauses","explanation":"''Being'' se usa en esta situación para señalar que la naturaleza del libro es fascinante.","stimulus_en":"The book, ___ fascinating, kept me awake all night.","options":[{"id":"o1","text":"to be"},{"id":"o2","text":"being"},{"id":"o3","text":"been"},{"id":"o4","text":"be"}],"correct_answer":"o2","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B2_I4', 'ingles-b2-U27', 9, 'multiple_choice', 'Choose the correct option to complete the sentences using participle clauses.', '{"prompt_es":"Choose the correct option to complete the sentences using participle clauses.","mastery_tag":"grammar:b2-participle-clauses","explanation":"''Finished'' aquí indica una acción completada antes de que él saliera a jugar.","stimulus_en":"Having finished his homework, he went out to play.","options":[{"id":"o1","text":"Finishing"},{"id":"o2","text":"Finished"},{"id":"o3","text":"To finish"},{"id":"o4","text":"Having finish"}],"correct_answer":"o2","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B2_I5', 'ingles-b2-U27', 10, 'multiple_choice', 'Choose the correct option to complete the sentences using participle clauses.', '{"prompt_es":"Choose the correct option to complete the sentences using participle clauses.","mastery_tag":"grammar:b2-participle-clauses","explanation":"''Having been'' indica que ella había experimentado la acción de estar molestada antes de dejar la reunión.","stimulus_en":"___ upset by the news, she left the meeting early.","options":[{"id":"o1","text":"Being"},{"id":"o2","text":"Having been"},{"id":"o3","text":"To be"},{"id":"o4","text":"Is being"}],"correct_answer":"o2","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B3_I1', 'ingles-b2-U27', 11, 'multiple_choice', 'What is a key feature of an article review?', '{"prompt_es":"What is a key feature of an article review?","mastery_tag":"writing:b2-reviews-articles","explanation":"Una revisión de artículo a menudo incluye la opinión personal del autor sobre el contenido revisado.","stimulus_en":"","options":[{"id":"o1","text":"Personal opinion"},{"id":"o2","text":"Storytelling"},{"id":"o3","text":"Data analysis"},{"id":"o4","text":"Fiction"}],"correct_answer":"o1","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B3_I2', 'ingles-b2-U27', 12, 'multiple_choice', 'Which element is NOT typically found in a review?', '{"prompt_es":"Which element is NOT typically found in a review?","mastery_tag":"writing:b2-reviews-articles","explanation":"Las revisiones deben ser claras y centradas, evitando distracciones que no aporten al contenido.","stimulus_en":"","options":[{"id":"o1","text":"Summary"},{"id":"o2","text":"Personal experience"},{"id":"o3","text":"Distraction"},{"id":"o4","text":"Recommendation"}],"correct_answer":"o3","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B3_I3', 'ingles-b2-U27', 13, 'multiple_choice', 'What is a common purpose of writing articles?', '{"prompt_es":"What is a common purpose of writing articles?","mastery_tag":"writing:b2-reviews-articles","explanation":"Los artículos pueden tener múltiples propósitos, incluyendo entretener, persuadir e informar al lector.","stimulus_en":"","options":[{"id":"o1","text":"To entertain"},{"id":"o2","text":"To persuade"},{"id":"o3","text":"To inform"},{"id":"o4","text":"All of the above"}],"correct_answer":"o4","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B3_I4', 'ingles-b2-U27', 14, 'multiple_choice', 'In a product review, what should the author primarily evaluate?', '{"prompt_es":"In a product review, what should the author primarily evaluate?","mastery_tag":"writing:b2-reviews-articles","explanation":"En una reseña de producto, el enfoque principal debe estar en las características y el rendimiento del producto.","stimulus_en":"","options":[{"id":"o1","text":"Author’s background"},{"id":"o2","text":"Market trends"},{"id":"o3","text":"Product features"},{"id":"o4","text":"Personal thoughts"}],"correct_answer":"o3","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U27_B3_I5', 'ingles-b2-U27', 15, 'multiple_choice', 'What writing style is typically used for formal articles?', '{"prompt_es":"What writing style is typically used for formal articles?","mastery_tag":"writing:b2-reviews-articles","explanation":"Los artículos formales suelen seguir un estilo académico que es más riguroso y objetivo.","stimulus_en":"","options":[{"id":"o1","text":"Casual"},{"id":"o2","text":"Conversational"},{"id":"o3","text":"Academic"},{"id":"o4","text":"Humorous"}],"correct_answer":"o3","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U28', 'ingles-b2', 28, 'Unit 28', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U28_B1_I1', 'ingles-b2-U28', 1, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate participles.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate participles.","mastery_tag":"grammar:b2-participle-clauses","main_text":"___ by the sudden noise, she jumped in surprise.\n\nThe book, ___ by many readers, is a bestseller.\n\n___ to the meeting, he arrived late.\n\n___ with the project, they took a break.\n\n___ in the rain, we decided to stay indoors.","correct_answer":["Startled","praised","Arriving","Finished","Caught"],"explanation":"(1) Aquí usamos ''startled'' como una cláusula de participio para demostrar la causa de su reacción.\n(2) El uso de ''praised'' aquí indica que el libro ha recibido elogios, mostrando la opinión de los lectores.\n(3) Aquí, ''arriving'' indica simultaneidad y se utiliza para mostrar que sucedió al mismo tiempo que llegó.\n(4) Utilizamos ''finished'' para mostrar que completaron el proyecto y luego tomaron un descanso.\n(5) En este caso, ''caught'' indica que la lluvia fue la causa de su decisión.","complexity":3,"concept_tags":["grammar","participle","clauses","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U28_B2_I1', 'ingles-b2-U28', 2, 'fill_blanks', 'Complete the sentences by filling in the blanks with the correct form of the verbs in parentheses.', '{"prompt_es":"Complete the sentences by filling in the blanks with the correct form of the verbs in parentheses.","mastery_tag":"grammar:b2-mixed-conditionals","main_text":"If I (1)___ (know) about the meeting, I would have come earlier.","correct_answer":["had known","hadn''t broken","had studied","were","rains"],"explanation":"(1) Esta oración es un condicional mixto que expresa una acción en el pasado que no ocurrió y su resultado en el presente.\n(2) Aquí, el pasado influye en una situación presente. Se usa la tercera condicional para el pasado.\n(3) Este ejemplo muestra cómo un esfuerzo en el pasado afecta el presente.\n(4) En esta oración, se usa ''were'' en un contexto hipotético que refleja una decisión no tomada en el pasado.\n(5) Este ejemplo combina el potencial futuro con un resultado pasado, mostrando una relación compleja entre el tiempo.","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U28_B3_I1', 'ingles-b2-U28', 3, 'multiple_choice_cloze', 'Fill in the blanks with the correct word from the options provided.', '{"prompt_es":"Fill in the blanks with the correct word from the options provided.","mastery_tag":"vocabulary:b2-media","main_text":"In today''s fast-paced world of media, effective [GAP 1] (1) is essential for journalists. They must not only report facts but also engage their audience through various [GAP 2] (2) platforms. The rise of digital [GAP 3] (3) has transformed traditional journalism, allowing news to be shared instantly and widely. Many media outlets now use [GAP 4] (4) to gather and analyze audience data, improving their content. However, ethical standards in [GAP 5] (5) remain crucial to maintain trust and credibility.","gaps":[{"id":"1","options":[{"id":"o1","text":"communication"},{"id":"o2","text":"conflict"},{"id":"o3","text":"connection"},{"id":"o4","text":"community"}]},{"id":"2","options":[{"id":"o1","text":"digital"},{"id":"o2","text":"physical"},{"id":"o3","text":"manual"},{"id":"o4","text":"occasional"}]},{"id":"3","options":[{"id":"o1","text":"media"},{"id":"o2","text":"message"},{"id":"o3","text":"method"},{"id":"o4","text":"moment"}]},{"id":"4","options":[{"id":"o1","text":"analysts"},{"id":"o2","text":"algorithms"},{"id":"o3","text":"advertisements"},{"id":"o4","text":"articles"}]},{"id":"5","options":[{"id":"o1","text":"journalism"},{"id":"o2","text":"communication"},{"id":"o3","text":"broadcasting"},{"id":"o4","text":"advertising"}]}],"correct_answer":{"1":"o1","2":"o1","3":"o1","4":"o2","5":"o1"},"explanation":"(1) La comunicación efectiva es clave para los periodistas en la era digital.\n(2) Las plataformas digitales se utilizan ampliamente para interactuar con la audiencia.\n(3) Los medios digitales han revolucionado la forma en que se distribuye la información.\n(4) Los algoritmos son fundamentales para comprender los patrones de la audiencia.\n(5) Los estándares éticos en el periodismo son esenciales para la credibilidad.","complexity":3,"concept_tags":["vocabulary","media","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U29', 'ingles-b2', 29, 'Unit 29', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B1_I1', 'ingles-b2-U29', 1, 'multiple_choice', 'What is a common problem affecting urban areas today?', '{"prompt_es":"What is a common problem affecting urban areas today?","mastery_tag":"vocabulary:b2-society","explanation":"El desempleo es un problema común en áreas urbanas debido a la falta de trabajos disponibles.","stimulus_en":"","options":[{"id":"o1","text":"Unemployment"},{"id":"o2","text":"Vacation"},{"id":"o3","text":"Happiness"},{"id":"o4","text":"Creativity"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","society","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B1_I2', 'ingles-b2-U29', 2, 'multiple_choice', 'Which term refers to the way individuals interact within a community?', '{"prompt_es":"Which term refers to the way individuals interact within a community?","mastery_tag":"vocabulary:b2-society","explanation":"La sociedad se refiere a cómo las personas se relacionan y se organizan en un grupo.","stimulus_en":"","options":[{"id":"o1","text":"Society"},{"id":"o2","text":"Economy"},{"id":"o3","text":"Market"},{"id":"o4","text":"Government"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","society","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B1_I3', 'ingles-b2-U29', 3, 'multiple_choice', 'What is a significant social issue regarding the environment?', '{"prompt_es":"What is a significant social issue regarding the environment?","mastery_tag":"vocabulary:b2-society","explanation":"El cambio climático es un problema social importante que afecta a la salud del planeta y las comunidades.","stimulus_en":"","options":[{"id":"o1","text":"Climate change"},{"id":"o2","text":"Social media"},{"id":"o3","text":"Fashion"},{"id":"o4","text":"Travel"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","society","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B1_I4', 'ingles-b2-U29', 4, 'multiple_choice', 'What is the role of government in addressing social issues?', '{"prompt_es":"What is the role of government in addressing social issues?","mastery_tag":"vocabulary:b2-society","explanation":"El gobierno tiene la responsabilidad de ofrecer soluciones a los problemas sociales que afectan a su población.","stimulus_en":"","options":[{"id":"o1","text":"To ignore them"},{"id":"o2","text":"To provide solutions"},{"id":"o3","text":"To limit them"},{"id":"o4","text":"To create problems"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","society","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B1_I5', 'ingles-b2-U29', 5, 'multiple_choice', 'Which of the following best describes activism?', '{"prompt_es":"Which of the following best describes activism?","mastery_tag":"vocabulary:b2-society","explanation":"El activismo se refiere al apoyo activo hacia una causa o movimiento social.","stimulus_en":"","options":[{"id":"o1","text":"Passive behavior"},{"id":"o2","text":"Active support for a cause"},{"id":"o3","text":"Indifference"},{"id":"o4","text":"Social media usage"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","society","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B2_I1', 'ingles-b2-U29', 6, 'multiple_choice', 'What is the primary purpose of a lecture?', '{"prompt_es":"What is the primary purpose of a lecture?","mastery_tag":"listening:b2-lectures","explanation":"El propósito principal de una conferencia es informar a la audiencia sobre un tema específico a través de una exposición clara y detallada.","stimulus_en":"","options":[{"id":"o1","text":"To entertain"},{"id":"o2","text":"To inform"},{"id":"o3","text":"To sell"},{"id":"o4","text":"To socialize"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B2_I2', 'ingles-b2-U29', 7, 'multiple_choice', 'Which of the following is a common feature of academic presentations?', '{"prompt_es":"Which of the following is a common feature of academic presentations?","mastery_tag":"listening:b2-lectures","explanation":"Las presentaciones académicas a menudo utilizan un lenguaje formal para comunicar ideas de manera clara y profesional.","stimulus_en":"","options":[{"id":"o1","text":"Dance performances"},{"id":"o2","text":"Formal language"},{"id":"o3","text":"Casual clothes"},{"id":"o4","text":"Open discussions"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B2_I3', 'ingles-b2-U29', 8, 'multiple_choice', 'What is a good way to engage an audience during a lecture?', '{"prompt_es":"What is a good way to engage an audience during a lecture?","mastery_tag":"listening:b2-lectures","explanation":"Hacer preguntas durante una conferencia involucra al público y estimula su interés y participación en el tema.","stimulus_en":"","options":[{"id":"o1","text":"Reading slides verbatim"},{"id":"o2","text":"Asking questions"},{"id":"o3","text":"Ignoring the audience"},{"id":"o4","text":"Speaking quickly"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B2_I4', 'ingles-b2-U29', 9, 'multiple_choice', 'Which of the following is NOT typically included in a lecture?', '{"prompt_es":"Which of the following is NOT typically included in a lecture?","mastery_tag":"listening:b2-lectures","explanation":"Una conferencia generalmente incluye una introducción, un cuerpo principal y una conclusión, pero no actividades sociales.","stimulus_en":"","options":[{"id":"o1","text":"Introduction"},{"id":"o2","text":"Main body"},{"id":"o3","text":"Conclusion"},{"id":"o4","text":"Social activity"}],"correct_answer":"o4","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B2_I5', 'ingles-b2-U29', 10, 'multiple_choice', 'What should a speaker do if they notice the audience is losing interest?', '{"prompt_es":"What should a speaker do if they notice the audience is losing interest?","mastery_tag":"listening:b2-lectures","explanation":"Invitar a preguntas puede revitalizar el interés del público y fomentar una mejor comprensión del tema.","stimulus_en":"","options":[{"id":"o1","text":"Continue without changes"},{"id":"o2","text":"Change the topic"},{"id":"o3","text":"Invite questions"},{"id":"o4","text":"Speak louder"}],"correct_answer":"o3","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B3_I1', 'ingles-b2-U29', 11, 'multiple_choice', 'Choose the best option that completes the idiomatic expression or phrase.', '{"prompt_es":"Choose the best option that completes the idiomatic expression or phrase.","mastery_tag":"vocabulary:b2-idiomatic","explanation":"La expresión ''not to take it personally'' significa no sentirse ofendido por las acciones o palabras de otros.","stimulus_en":"He was really upset after the meeting, but I told him not to take it _____.","options":[{"id":"o1","text":"personally"},{"id":"o2","text":"seriously"},{"id":"o3","text":"lightly"},{"id":"o4","text":"casually"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","idiomatic","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B3_I2', 'ingles-b2-U29', 12, 'multiple_choice', 'Choose the best option that completes the idiomatic expression or phrase.', '{"prompt_es":"Choose the best option that completes the idiomatic expression or phrase.","mastery_tag":"vocabulary:b2-idiomatic","explanation":"La expresión ''way off'' se usa para indicar que algo está muy lejos de lo correcto o esperado.","stimulus_en":"I thought I knew the answer, but it turns out I was way _____.","options":[{"id":"o1","text":"off"},{"id":"o2","text":"away"},{"id":"o3","text":"out"},{"id":"o4","text":"down"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","idiomatic","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B3_I3', 'ingles-b2-U29', 13, 'multiple_choice', 'Choose the best option that completes the idiomatic expression or phrase.', '{"prompt_es":"Choose the best option that completes the idiomatic expression or phrase.","mastery_tag":"vocabulary:b2-idiomatic","explanation":"La expresión ''think outside the box'' significa ser creativo o innovador en la resolución de problemas.","stimulus_en":"When it comes to traveling, she really knows how to think outside the _____.","options":[{"id":"o1","text":"box"},{"id":"o2","text":"line"},{"id":"o3","text":"circle"},{"id":"o4","text":"frame"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","idiomatic","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B3_I4', 'ingles-b2-U29', 14, 'multiple_choice', 'Choose the best option that completes the idiomatic expression or phrase.', '{"prompt_es":"Choose the best option that completes the idiomatic expression or phrase.","mastery_tag":"vocabulary:b2-idiomatic","explanation":"La expresión ''on cloud nine'' significa estar muy feliz o eufórico.","stimulus_en":"He is on cloud nine since he got the promotion; he is so _____.","options":[{"id":"o1","text":"happy"},{"id":"o2","text":"angry"},{"id":"o3","text":"busy"},{"id":"o4","text":"tired"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","idiomatic","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U29_B3_I5', 'ingles-b2-U29', 15, 'multiple_choice', 'Choose the best option that completes the idiomatic expression or phrase.', '{"prompt_es":"Choose the best option that completes the idiomatic expression or phrase.","mastery_tag":"vocabulary:b2-idiomatic","explanation":"La expresión ''sit on the fence'' significa no tomar una decisión o no comprometerse con una opinión.","stimulus_en":"You can''t just sit on the _____. You need to take action.","options":[{"id":"o1","text":"fence"},{"id":"o2","text":"couch"},{"id":"o3","text":"bed"},{"id":"o4","text":"floor"}],"correct_answer":"o1","complexity":3,"concept_tags":["vocabulary","idiomatic","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U30', 'ingles-b2', 30, 'Unit 30', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B1_I1', 'ingles-b2-U30', 1, 'fill_blanks', 'Fill in the blanks with the correct perfect modal verb.', '{"prompt_es":"Fill in the blanks with the correct perfect modal verb.","mastery_tag":"grammar:b2-perfect-modals","main_text":"She ___ (must) have taken the wrong train; she is late again.","correct_answer":["must","should","could","might","must"],"explanation":"(1) Aquí se usa ''must have'' para indicar una fuerte suposición sobre algo que sucedió en el pasado.\n(2) El uso de ''should have'' indica que se esperaba que completaran el proyecto en el pasado.\n(3) ''Could have'' sugiere una posibilidad que no se realizó, indicando que tenía la opción de llamar.\n(4) ''Might have'' expresa una posibilidad en el pasado de que la persona la haya visto en la fiesta.\n(5) ''Must have'' se utiliza aquí para suponer que es muy probable que hayan escuchado las noticias.","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B2_I1', 'ingles-b2-U30', 2, 'multiple_choice', 'What is the primary purpose of a review?', '{"prompt_es":"What is the primary purpose of a review?","mastery_tag":"writing:b2-reviews-articles","explanation":"El propósito principal de una reseña es evaluar un producto, servicio o experiencia. Las reseñas ayudan a los lectores a tomar decisiones informadas.","stimulus_en":"","options":[{"id":"o1","text":"To inform"},{"id":"o2","text":"To entertain"},{"id":"o3","text":"To persuade"},{"id":"o4","text":"To evaluate"}],"correct_answer":"o4","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B2_I2', 'ingles-b2-U30', 3, 'multiple_choice', 'Which of the following should NOT be included in a professional article?', '{"prompt_es":"Which of the following should NOT be included in a professional article?","mastery_tag":"writing:b2-reviews-articles","explanation":"Un artículo profesional debe basarse en la evidencia y se espera que se mantenga objetivo. Las opiniones personales pueden no ser apropiadas.","stimulus_en":"","options":[{"id":"o1","text":"Personal opinions"},{"id":"o2","text":"Factual evidence"},{"id":"o3","text":"Citations"},{"id":"o4","text":"Research data"}],"correct_answer":"o1","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B2_I3', 'ingles-b2-U30', 4, 'multiple_choice', 'What is a key feature of a well-written review?', '{"prompt_es":"What is a key feature of a well-written review?","mastery_tag":"writing:b2-reviews-articles","explanation":"Una buena reseña debe ofrecer una perspectiva equilibrada, discutiendo tanto los aspectos positivos como negativos del sujeto.","stimulus_en":"","options":[{"id":"o1","text":"Lengthy descriptions"},{"id":"o2","text":"Balanced viewpoints"},{"id":"o3","text":"Sole focus on negatives"},{"id":"o4","text":"Use of jargon"}],"correct_answer":"o2","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B2_I4', 'ingles-b2-U30', 5, 'multiple_choice', 'Choose the best option for each question based on your understanding of reviews and articles.', '{"prompt_es":"Choose the best option for each question based on your understanding of reviews and articles.","mastery_tag":"writing:b2-reviews-articles","explanation":"Un artículo de opinión se centra en las creencias y perspectivas del autor sobre un tema, presentando argumentos que lo respaldan.","stimulus_en":"In an opinion piece, the writer should primarily focus on:","options":[{"id":"o1","text":"Analysis of data"},{"id":"o2","text":"Personal beliefs"},{"id":"o3","text":"Historical context"},{"id":"o4","text":"Literary style"}],"correct_answer":"o2","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B2_I5', 'ingles-b2-U30', 6, 'multiple_choice', 'Which element is crucial for attracting readers to an article?', '{"prompt_es":"Which element is crucial for attracting readers to an article?","mastery_tag":"writing:b2-reviews-articles","explanation":"Los titulares atractivos capturan la atención del lector y son un componente esencial de un artículo efectivo.","stimulus_en":"","options":[{"id":"o1","text":"Abstract titles"},{"id":"o2","text":"Boring introductions"},{"id":"o3","text":"Engaging headlines"},{"id":"o4","text":"Complex vocabulary"}],"correct_answer":"o3","complexity":3,"concept_tags":["writing","reviews","articles","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B3_I1', 'ingles-b2-U30', 7, 'multiple_choice', 'What was the main focus of the lecture in 1967?', '{"prompt_es":"What was the main focus of the lecture in 1967?","mastery_tag":"listening:b2-lectures","explanation":"La respuesta correcta es ''Technological advancements'' porque el enfoque era sobre cómo la tecnología estaba cambiando la sociedad en ese año.","stimulus_en":"","options":[{"id":"o1","text":"Historical events"},{"id":"o2","text":"Technological advancements"},{"id":"o3","text":"Cultural changes"},{"id":"o4","text":"Political movements"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B3_I2', 'ingles-b2-U30', 8, 'multiple_choice', 'Which device was highlighted as revolutionary during the discussion?', '{"prompt_es":"Which device was highlighted as revolutionary during the discussion?","mastery_tag":"listening:b2-lectures","explanation":"Se consideró que la computadora era revolucionaria debido a su impacto en el trabajo y la comunicación.","stimulus_en":"","options":[{"id":"o1","text":"Television"},{"id":"o2","text":"Computer"},{"id":"o3","text":"Radio"},{"id":"o4","text":"Telephone"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B3_I3', 'ingles-b2-U30', 9, 'multiple_choice', 'What did the speaker suggest about the future of technology?', '{"prompt_es":"What did the speaker suggest about the future of technology?","mastery_tag":"listening:b2-lectures","explanation":"El orador expresó optimismo sobre las mejoras tecnológicas y su potencial para revolucionar la vida diaria.","stimulus_en":"","options":[{"id":"o1","text":"It will remain the same"},{"id":"o2","text":"It will greatly improve"},{"id":"o3","text":"It will become less important"},{"id":"o4","text":"It will confuse people"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B3_I4', 'ingles-b2-U30', 10, 'multiple_choice', 'How did the audience react to the examples given?', '{"prompt_es":"How did the audience react to the examples given?","mastery_tag":"listening:b2-lectures","explanation":"La reacción entusiasta del público indica que estaban interesados y comprometidos con el tema presentado.","stimulus_en":"","options":[{"id":"o1","text":"Negatively"},{"id":"o2","text":"Indifferently"},{"id":"o3","text":"Enthusiastically"},{"id":"o4","text":"Critically"}],"correct_answer":"o3","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U30_B3_I5', 'ingles-b2-U30', 11, 'multiple_choice', 'What method did the speaker use to engage the audience?', '{"prompt_es":"What method did the speaker use to engage the audience?","mastery_tag":"listening:b2-lectures","explanation":"El orador utilizó estadísticas, ayudas visuales y historias personales para mantener la atención de la audiencia.","stimulus_en":"","options":[{"id":"o1","text":"Statistics"},{"id":"o2","text":"Visual aids"},{"id":"o3","text":"Personal stories"},{"id":"o4","text":"All of the above"}],"correct_answer":"o4","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

COMMIT;