BEGIN;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U6', 'ingles-b2', 6, 'Unit 6', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B1_I1', 'ingles-b2-U6', 1, 'fill_blanks', 'Complete the sentences by changing the form of the word in parentheses.

Base words: (1) DEVELOP, (2) SOCIAL, (3) INVOLVE, (4) COMMUNICATE, (5) COMMUNICATE', '{"prompt_es":"Complete the sentences by changing the form of the word in parentheses.\n\nBase words: (1) DEVELOP, (2) SOCIAL, (3) INVOLVE, (4) COMMUNICATE, (5) COMMUNICATE","mastery_tag":"vocabulary:b2-media","main_text":"The rapid (1)___ of digital media has transformed how we communicate. The rise of (2)___ platforms has changed the landscape of journalism. Many journalists now focus on (3)___ reporting to engage their audience. The importance of (4)___ in media cannot be overstated, as it shapes public perception. To succeed in this field, one must develop strong (5)___ skills.","correct_answer":["DEVELOPMENT","SOCIAL MEDIA","INVOLVING","COMMUNICATION","COMMUNICATIVE"],"explanation":"(1) Aquí necesitas un sustantivo que describe el proceso de desarrollo.\n(2) Se necesita una frase que describe plataformas interactivas en línea.\n(3) Se requiere un gerundio que describe el tipo de reportes.\n(4) Buscas un sustantivo que se refiere al acto de transmitir información.\n(5) Aquí necesitas un adjetivo que describe habilidades relacionadas con la comunicación.","complexity":3,"concept_tags":["vocabulary","media","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B2_I1', 'ingles-b2-U6', 2, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La inversión se utiliza para enfatizar la rareza de la situación, por lo que se utiliza ''have'' en lugar de ''has'', ya que el sujeto es plural.","stimulus_en":"Seldom ___ such a talented team have we seen.","options":[{"id":"o1","text":"have"},{"id":"o2","text":"has"},{"id":"o3","text":"did"},{"id":"o4","text":"do"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B2_I2', 'ingles-b2-U6', 3, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La inversión se utiliza aquí porque ''never'' está al principio de la oración, lo que requiere invertir el sujeto y el verbo.","stimulus_en":"Never ___ I think of quitting my job.","options":[{"id":"o1","text":"do"},{"id":"o2","text":"did"},{"id":"o3","text":"have"},{"id":"o4","text":"am"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B2_I3', 'ingles-b2-U6', 4, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"En este caso, ''hardly'' indica que la acción de llegar fue muy poco antes de que comenzara a llover, y se usa la inversión con ''had''.","stimulus_en":"Hardly ___ we arrived when it started to rain.","options":[{"id":"o1","text":"had"},{"id":"o2","text":"have"},{"id":"o3","text":"did"},{"id":"o4","text":"are"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B2_I4', 'ingles-b2-U6', 5, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"El adverbio ''seldom'' requiere la inversión con el verbo auxiliar ''do'' para enfatizar la declaración.","stimulus_en":"Seldom ___ people express their true feelings in meetings.","options":[{"id":"o1","text":"do"},{"id":"o2","text":"does"},{"id":"o3","text":"are"},{"id":"o4","text":"have"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B2_I5', 'ingles-b2-U6', 6, 'multiple_choice', 'Choose the correct option to complete each sentence using inversion.', '{"prompt_es":"Choose the correct option to complete each sentence using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La inversión se utiliza después de ''not only'' para conectar dos partes de la oración, comenzando con un verbo auxiliar.","stimulus_en":"Not only ___ she an excellent researcher, but she also leads the team.","options":[{"id":"o1","text":"is"},{"id":"o2","text":"was"},{"id":"o3","text":"does"},{"id":"o4","text":"has"}],"correct_answer":"o1","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U6_B3_I1', 'ingles-b2-U6', 7, 'fill_blanks', 'Complete each sentence with the correct word or phrase related to debate and discussion.', '{"prompt_es":"Complete each sentence with the correct word or phrase related to debate and discussion.","mastery_tag":"speaking:b2-debate","main_text":"In a debate, participants present their points of view on a specific topic. Effective debaters must be able to articulate their arguments clearly and ___(1)___. It is essential to listen to opposing arguments and ___(2)___ them respectfully. One way to strengthen your position is to use credible evidence to ___(3)___. During a debate, it is also important to remain ___(4)___, even when faced with challenging questions. Finally, a successful debater should aim to persuade the audience, not just to ___(5)___ their own viewpoint.","correct_answer":["persuasively","address","support their claims","calm","defend"],"explanation":"(1) En los debates, es crucial que los participantes presenten sus argumentos de manera persuasiva para convencer a la audiencia.\n(2) Es importante que los debatientes respondan y aborden los argumentos opuestos de manera respetuosa.\n(3) El uso de evidencia creíble es fundamental para respaldar las afirmaciones en un debate.\n(4) Mantener la calma durante un debate es crucial para poder responder adecuadamente a las preguntas difíciles.\n(5) Un buen debatiente no solo defiende su punto de vista, sino que también trata de convencer a la audiencia.","complexity":3,"concept_tags":["speaking","debate","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U7', 'ingles-b2', 7, 'Unit 7', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B1_I1', 'ingles-b2-U7', 1, 'fill_blanks', 'Fill in the blanks with the correct words to make the sentences complete using inversion.', '{"prompt_es":"Fill in the blanks with the correct words to make the sentences complete using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"En esta oración, usamos inversión porque comenzamos con una palabra que indica frecuencia (rarely). En inglés formal, esto requiere la inversión del sujeto y el verbo auxiliar.","stimulus_en":"In the following sentences, complete the gaps with appropriate words for inversion.\n\n____ (rarely) have I encountered such a dedicated team in my career.","correct_answer":"Rarely","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B1_I2', 'ingles-b2-U7', 2, 'fill_blanks', 'Fill in the blanks with the correct words to make the sentences complete using inversion.', '{"prompt_es":"Fill in the blanks with the correct words to make the sentences complete using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"Al iniciar con ''never'', debemos invertir el sujeto y el verbo auxiliar. Esto es típico en inglés formal.","stimulus_en":"In the following sentences, complete the gaps with appropriate words for inversion.\n\nNever ____ (I/see) such an impressive presentation before.","correct_answer":"have I seen","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B1_I3', 'ingles-b2-U7', 3, 'fill_blanks', 'Fill in the blanks with the correct words to make the sentences complete using inversion.', '{"prompt_es":"Fill in the blanks with the correct words to make the sentences complete using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La palabra ''seldom'' requiere una inversión del sujeto y el verbo, que es un uso correcto en contextos formales.","stimulus_en":"In the following sentences, complete the gaps with appropriate words for inversion.\n\nSeldom ____ (we/have) the opportunity to work on such prestigious projects.","correct_answer":"do we have","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B1_I4', 'ingles-b2-U7', 4, 'fill_blanks', 'Fill in the blanks with the correct words to make the sentences complete using inversion.', '{"prompt_es":"Fill in the blanks with the correct words to make the sentences complete using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La palabra ''hardly'' también requiere que utilicemos la inversión del sujeto y el verbo. Es fundamental para mantener la formalidad en la oración.","stimulus_en":"In the following sentences, complete the gaps with appropriate words for inversion.\n\nHardly ____ (they/prepare) for the upcoming changes in the market.","correct_answer":"had they prepared","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B1_I5', 'ingles-b2-U7', 5, 'fill_blanks', 'Fill in the blanks with the correct words to make the sentences complete using inversion.', '{"prompt_es":"Fill in the blanks with the correct words to make the sentences complete using inversion.","mastery_tag":"grammar:b2-inversion","explanation":"La frase comienza con ''no sooner'' y requiere inversión del sujeto y el verbo auxiliar, lo que es típico en construcciones formales.","stimulus_en":"In the following sentences, complete the gaps with appropriate words for inversion.\n\nNo sooner ____ (the team/submit) the report than feedback arrived.","correct_answer":"had the team submitted","complexity":3,"concept_tags":["grammar","inversion","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B2_I1', 'ingles-b2-U7', 6, 'fill_blanks', 'Fill in the blanks with the correct verb forms to complete the sentences using mixed conditionals.', '{"prompt_es":"Fill in the blanks with the correct verb forms to complete the sentences using mixed conditionals.","mastery_tag":"grammar:b2-mixed-conditionals","main_text":"If I (1)___ the presentation better, I would have succeeded in the meeting.","correct_answer":["had prepared","had gone","had managed","had had","had completed"],"explanation":"(1) En esta oración, el resultado ''would have succeeded'' se refiere a una acción que no ocurrió en el pasado.\n(2) Aquí se usa el pasado perfecto para expresar una acción que no se realizó en el pasado y su impacto en el presente.\n(3) Esta oración muestra cómo una acción pasada afecta a un resultado pasado.\n(4) Usamos ''had had'' para referirnos a una falta de tiempo en el pasado que afecta el presente.\n(5) Esta oración muestra que la falta de acción en el pasado afecta la situación actual.","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B3_I1', 'ingles-b2-U7', 7, 'multiple_choice', 'What is one main argument of proponents of strict regulations?', '{"prompt_es":"What is one main argument of proponents of strict regulations?","mastery_tag":"reading:b2-complex-texts","explanation":"Los defensores de regulaciones estrictas creen que la falta de acción tendrá consecuencias negativas para las generaciones futuras.","stimulus_en":"In recent years, the debate surrounding climate change has intensified, leading to various viewpoints on how societies should respond. Proponents of strict regulations argue that without immediate action, future generations will suffer the consequences of inaction. They cite scientific evidence indicating that rising temperatures will result in more extreme weather patterns, affecting agriculture, water supply, and health. On the other hand, critics of these regulations point out the economic implications, suggesting that such measures could stifle growth and lead to job losses in key industries. They advocate for a more balanced approach, emphasizing adaptation over restriction, which could allow for economic stability while still addressing environmental concerns. Ultimately, the challenge lies in finding a solution that reconciles environmental sustainability with economic vitality, ensuring a livable planet for future generations.","correct_answer":"o1","options":[{"id":"o1","text":"Future generations will suffer from inaction."},{"id":"o2","text":"They suggest regulations could stifle growth."},{"id":"o3","text":"More extreme weather patterns."},{"id":"o4","text":"A balanced approach emphasizing adaptation."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B3_I2', 'ingles-b2-U7', 8, 'multiple_choice', 'What do critics of regulations argue?', '{"prompt_es":"What do critics of regulations argue?","mastery_tag":"reading:b2-complex-texts","explanation":"Los críticos argumentan que las regulaciones pueden detener el crecimiento económico.","stimulus_en":"In recent years, the debate surrounding climate change has intensified, leading to various viewpoints on how societies should respond. Proponents of strict regulations argue that without immediate action, future generations will suffer the consequences of inaction. They cite scientific evidence indicating that rising temperatures will result in more extreme weather patterns, affecting agriculture, water supply, and health. On the other hand, critics of these regulations point out the economic implications, suggesting that such measures could stifle growth and lead to job losses in key industries. They advocate for a more balanced approach, emphasizing adaptation over restriction, which could allow for economic stability while still addressing environmental concerns. Ultimately, the challenge lies in finding a solution that reconciles environmental sustainability with economic vitality, ensuring a livable planet for future generations.","correct_answer":"o1","options":[{"id":"o1","text":"They suggest regulations could stifle growth."},{"id":"o2","text":"Future generations will suffer from inaction."},{"id":"o3","text":"More extreme weather patterns."},{"id":"o4","text":"A balanced approach emphasizing adaptation."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B3_I3', 'ingles-b2-U7', 9, 'multiple_choice', 'According to the passage, what is one consequence of rising temperatures?', '{"prompt_es":"According to the passage, what is one consequence of rising temperatures?","mastery_tag":"reading:b2-complex-texts","explanation":"El aumento de temperaturas provocará patrones climáticos más extremos, afectando varios aspectos de la vida.","stimulus_en":"In recent years, the debate surrounding climate change has intensified, leading to various viewpoints on how societies should respond. Proponents of strict regulations argue that without immediate action, future generations will suffer the consequences of inaction. They cite scientific evidence indicating that rising temperatures will result in more extreme weather patterns, affecting agriculture, water supply, and health. On the other hand, critics of these regulations point out the economic implications, suggesting that such measures could stifle growth and lead to job losses in key industries. They advocate for a more balanced approach, emphasizing adaptation over restriction, which could allow for economic stability while still addressing environmental concerns. Ultimately, the challenge lies in finding a solution that reconciles environmental sustainability with economic vitality, ensuring a livable planet for future generations.","correct_answer":"o1","options":[{"id":"o1","text":"More extreme weather patterns."},{"id":"o2","text":"Future generations will suffer from inaction."},{"id":"o3","text":"They suggest regulations could stifle growth."},{"id":"o4","text":"A balanced approach emphasizing adaptation."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B3_I4', 'ingles-b2-U7', 10, 'multiple_choice', 'What does the passage suggest is a potential solution to the climate debate?', '{"prompt_es":"What does the passage suggest is a potential solution to the climate debate?","mastery_tag":"reading:b2-complex-texts","explanation":"El texto sugiere un enfoque equilibrado que enfatiza la adaptación mientras enfrenta preocupaciones ambientales.","stimulus_en":"In recent years, the debate surrounding climate change has intensified, leading to various viewpoints on how societies should respond. Proponents of strict regulations argue that without immediate action, future generations will suffer the consequences of inaction. They cite scientific evidence indicating that rising temperatures will result in more extreme weather patterns, affecting agriculture, water supply, and health. On the other hand, critics of these regulations point out the economic implications, suggesting that such measures could stifle growth and lead to job losses in key industries. They advocate for a more balanced approach, emphasizing adaptation over restriction, which could allow for economic stability while still addressing environmental concerns. Ultimately, the challenge lies in finding a solution that reconciles environmental sustainability with economic vitality, ensuring a livable planet for future generations.","correct_answer":"o1","options":[{"id":"o1","text":"A balanced approach emphasizing adaptation."},{"id":"o2","text":"Future generations will suffer from inaction."},{"id":"o3","text":"They suggest regulations could stifle growth."},{"id":"o4","text":"More extreme weather patterns."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U7_B3_I5', 'ingles-b2-U7', 11, 'multiple_choice', 'What challenge is highlighted at the end of the passage?', '{"prompt_es":"What challenge is highlighted at the end of the passage?","mastery_tag":"reading:b2-complex-texts","explanation":"El desafío mencionado es encontrar un equilibrio entre la sostenibilidad ambiental y la vitalidad económica.","stimulus_en":"In recent years, the debate surrounding climate change has intensified, leading to various viewpoints on how societies should respond. Proponents of strict regulations argue that without immediate action, future generations will suffer the consequences of inaction. They cite scientific evidence indicating that rising temperatures will result in more extreme weather patterns, affecting agriculture, water supply, and health. On the other hand, critics of these regulations point out the economic implications, suggesting that such measures could stifle growth and lead to job losses in key industries. They advocate for a more balanced approach, emphasizing adaptation over restriction, which could allow for economic stability while still addressing environmental concerns. Ultimately, the challenge lies in finding a solution that reconciles environmental sustainability with economic vitality, ensuring a livable planet for future generations.","correct_answer":"o1","options":[{"id":"o1","text":"Reconciling environmental sustainability with economic vitality."},{"id":"o2","text":"Future generations will suffer from inaction."},{"id":"o3","text":"They suggest regulations could stifle growth."},{"id":"o4","text":"More extreme weather patterns."}],"complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U8', 'ingles-b2', 8, 'Unit 8', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B1_I1', 'ingles-b2-U8', 1, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate words.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate words.","mastery_tag":"writing:b2-formal-writing","explanation":"Un saludo adecuado es importante en una carta formal para establecer un tono profesional.","stimulus_en":"In today''s business environment, effective communication is essential. Writing formal letters and reports is a key skill, as it helps convey information clearly and professionally. Below are some sentences where you need to fill in the missing words.\n\nA formal letter usually begins with a proper ___.","correct_answer":"greeting","complexity":3,"concept_tags":["writing","formal","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B1_I2', 'ingles-b2-U8', 2, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate words.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate words.","mastery_tag":"writing:b2-formal-writing","explanation":"Una estructura clara ayuda a que los lectores comprendan mejor la información presentada.","stimulus_en":"In today''s business environment, effective communication is essential. Writing formal letters and reports is a key skill, as it helps convey information clearly and professionally. Below are some sentences where you need to fill in the missing words.\n\nIn reports, it is crucial to use a ___ structure.","correct_answer":"clear","complexity":3,"concept_tags":["writing","formal","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B1_I3', 'ingles-b2-U8', 3, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate words.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate words.","mastery_tag":"writing:b2-formal-writing","explanation":"Un argumento sólido es esencial para persuadir y mantener el interés del lector.","stimulus_en":"In today''s business environment, effective communication is essential. Writing formal letters and reports is a key skill, as it helps convey information clearly and professionally. Below are some sentences where you need to fill in the missing words.\n\nWhen writing essays, it is important to present a strong ___.","correct_answer":"argument","complexity":3,"concept_tags":["writing","formal","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B1_I4', 'ingles-b2-U8', 4, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate words.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate words.","mastery_tag":"writing:b2-formal-writing","explanation":"Los errores gramaticales pueden afectar la credibilidad de un documento formal.","stimulus_en":"In today''s business environment, effective communication is essential. Writing formal letters and reports is a key skill, as it helps convey information clearly and professionally. Below are some sentences where you need to fill in the missing words.\n\nAlways proofread your work to avoid ___ errors.","correct_answer":"grammar","complexity":3,"concept_tags":["writing","formal","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B1_I5', 'ingles-b2-U8', 5, 'fill_blanks', 'Complete the sentences by filling in the blanks with appropriate words.', '{"prompt_es":"Complete the sentences by filling in the blanks with appropriate words.","mastery_tag":"writing:b2-formal-writing","explanation":"El profesionalismo es esencial en cualquier tipo de escritura formal.","stimulus_en":"In today''s business environment, effective communication is essential. Writing formal letters and reports is a key skill, as it helps convey information clearly and professionally. Below are some sentences where you need to fill in the missing words.\n\nUsing a formal tone is key to maintaining ___.","correct_answer":"professionalism","complexity":3,"concept_tags":["writing","formal","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B2_I1', 'ingles-b2-U8', 6, 'multiple_choice_cloze', 'Choose the correct word to fill in the blanks based on the context of media and communication.', '{"prompt_es":"Choose the correct word to fill in the blanks based on the context of media and communication.","mastery_tag":"vocabulary:b2-media","main_text":"In today''s world, the role of (1)[GAP 1] has become pivotal in shaping public opinion. With the rise of social media platforms, (2)[GAP 2] has transformed from traditional print to instantaneous digital updates. Many journalists now rely on (3)[GAP 3] to gather information quickly. Moreover, the (4)[GAP 4] of news has changed dramatically, requiring media outlets to adapt to a fast-paced environment. Finally, the importance of (5)[GAP 5] in journalism cannot be overstated, as it ensures accuracy and credibility.","gaps":[{"id":"1","options":[{"id":"o1","text":"advertising"},{"id":"o2","text":"journalism"},{"id":"o3","text":"television"},{"id":"o4","text":"broadcasting"}]},{"id":"2","options":[{"id":"o1","text":"communication"},{"id":"o2","text":"journalism"},{"id":"o3","text":"broadcasting"},{"id":"o4","text":"media"}]},{"id":"3","options":[{"id":"o1","text":"technology"},{"id":"o2","text":"communication"},{"id":"o3","text":"broadcasting"},{"id":"o4","text":"print"}]},{"id":"4","options":[{"id":"o1","text":"delivery"},{"id":"o2","text":"format"},{"id":"o3","text":"broadcasting"},{"id":"o4","text":"reporting"}]},{"id":"5","options":[{"id":"o1","text":"accuracy"},{"id":"o2","text":"journalism"},{"id":"o3","text":"advertising"},{"id":"o4","text":"reporting"}]}],"correct_answer":{"1":"o2","2":"o2","3":"o1","4":"o1","5":"o1"},"explanation":"(1) El periodismo juega un papel fundamental en la formación de la opinión pública.\n(2) El periodismo se ha transformado de lo impreso a lo digital de manera instantánea.\n(3) La tecnología es esencial para que los periodistas obtengan información rápidamente.\n(4) La entrega de noticias ha cambiado dramáticamente en los últimos años.\n(5) La precisión es crucial en el periodismo para mantener la credibilidad.","complexity":3,"concept_tags":["vocabulary","media","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U8_B3_I1', 'ingles-b2-U8', 7, 'multiple_choice_cloze', 'Choose the correct word to fill in the blanks in the passage below.', '{"prompt_es":"Choose the correct word to fill in the blanks in the passage below.","mastery_tag":"vocabulary:b2-media","main_text":"In today''s world, the role of the (1)[GAP 1] is more important than ever. Journalists must navigate the complexities of (2)[GAP 2] and ensure they provide accurate information. With the rise of digital platforms, many traditional (3)[GAP 3] have adapted to include online content. Effective (4)[GAP 4] skills are essential for engaging audiences, and media literacy is becoming a crucial part of education. As we consume news from various sources, understanding the impact of (5)[GAP 5] on our perceptions is key.","gaps":[{"id":"1","options":[{"id":"o1","text":"journalism"},{"id":"o2","text":"journalist"},{"id":"o3","text":"journalists"},{"id":"o4","text":"journalistic"}]},{"id":"2","options":[{"id":"o1","text":"broadcast"},{"id":"o2","text":"communication"},{"id":"o3","text":"media"},{"id":"o4","text":"journalism"}]},{"id":"3","options":[{"id":"o1","text":"broadcasts"},{"id":"o2","text":"journalists"},{"id":"o3","text":"networks"},{"id":"o4","text":"media"}]},{"id":"4","options":[{"id":"o1","text":"communication"},{"id":"o2","text":"broadcasting"},{"id":"o3","text":"writing"},{"id":"o4","text":"reading"}]},{"id":"5","options":[{"id":"o1","text":"communication"},{"id":"o2","text":"broadcasting"},{"id":"o3","text":"media"},{"id":"o4","text":"journalism"}]}],"correct_answer":{"1":"o2","2":"o3","3":"o4","4":"o1","5":"o3"},"explanation":"(1) El sustantivo correcto es ''journalist'', que se refiere a la persona que trabaja en el campo del periodismo.\n(2) El término ''media'' se refiere a los canales a través de los cuales se comunica la información.\n(3) Aquí, ''media'' se refiere a las organizaciones que producen contenido, como periódicos y canales de televisión.\n(4) El término ''communication'' se refiere a la habilidad de transmitir información de manera efectiva.\n(5) El impacto de ''media'' incluye cómo nuestras percepciones pueden ser moldeadas por la información que consumimos.","complexity":3,"concept_tags":["vocabulary","media","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U9', 'ingles-b2', 9, 'Unit 9', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B1_I1', 'ingles-b2-U9', 1, 'multiple_choice', 'What is a common benefit of practicing mindfulness?', '{"prompt_es":"What is a common benefit of practicing mindfulness?","mastery_tag":"vocabulary:b2-lifestyle","explanation":"La práctica de la atención plena ayuda a mejorar la concentración y a reducir el estrés.","stimulus_en":"","options":[{"id":"o1","text":"Increased stress"},{"id":"o2","text":"Improved focus"},{"id":"o3","text":"Less sleep"},{"id":"o4","text":"More distractions"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","lifestyle","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B1_I2', 'ingles-b2-U9', 2, 'multiple_choice', 'Which of the following is essential for maintaining a healthy lifestyle?', '{"prompt_es":"Which of the following is essential for maintaining a healthy lifestyle?","mastery_tag":"vocabulary:b2-lifestyle","explanation":"El ejercicio regular es fundamental para mantener un estilo de vida saludable, mejorando la salud física y mental.","stimulus_en":"","options":[{"id":"o1","text":"Fast food"},{"id":"o2","text":"Regular exercise"},{"id":"o3","text":"High sugar intake"},{"id":"o4","text":"Sedentary lifestyle"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","lifestyle","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B1_I3', 'ingles-b2-U9', 3, 'multiple_choice', 'How can personal growth be achieved?', '{"prompt_es":"How can personal growth be achieved?","mastery_tag":"vocabulary:b2-lifestyle","explanation":"Establecer metas permite a las personas crecer personalmente y alcanzar sus aspiraciones.","stimulus_en":"","options":[{"id":"o1","text":"By avoiding challenges"},{"id":"o2","text":"By setting goals"},{"id":"o3","text":"By staying in comfort zones"},{"id":"o4","text":"By ignoring feedback"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","lifestyle","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B1_I4', 'ingles-b2-U9', 4, 'multiple_choice', 'What is an important aspect of modern living?', '{"prompt_es":"What is an important aspect of modern living?","mastery_tag":"vocabulary:b2-lifestyle","explanation":"Abrirse a las herramientas digitales puede mejorar la calidad de vida y facilitar la comunicación.","stimulus_en":"","options":[{"id":"o1","text":"Ignoring technology"},{"id":"o2","text":"Embracing digital tools"},{"id":"o3","text":"Resisting change"},{"id":"o4","text":"Living in isolation"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","lifestyle","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B1_I5', 'ingles-b2-U9', 5, 'multiple_choice', 'Which practice can enhance well-being?', '{"prompt_es":"Which practice can enhance well-being?","mastery_tag":"vocabulary:b2-lifestyle","explanation":"Mantener conexiones sociales es vital para la salud emocional y el bienestar general.","stimulus_en":"","options":[{"id":"o1","text":"Neglecting self-care"},{"id":"o2","text":"Maintaining social connections"},{"id":"o3","text":"Overworking"},{"id":"o4","text":"Avoiding hobbies"}],"correct_answer":"o2","complexity":3,"concept_tags":["vocabulary","lifestyle","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B2_I1', 'ingles-b2-U9', 6, 'multiple_choice_cloze', 'Choose the correct word to fill in the blanks in the passage below.', '{"prompt_es":"Choose the correct word to fill in the blanks in the passage below.","mastery_tag":"reading:b2-complex-texts","main_text":"In today''s society, the debate over climate change has become one of the most contentious issues. Many scientists argue that human activities are significantly (1)[GAP 1] global warming, while others question the extent of its impact. The (2)[GAP 2] of climate change is not only an environmental concern but also an economic and social one. Advocates for immediate action point to the (3)[GAP 3] consequences of inaction, such as rising sea levels and extreme weather events. However, some skeptics believe that the data presented is (4)[GAP 4] and exaggerated, leading to public panic. To reach a consensus, a thorough (5)[GAP 5] of the available evidence is essential, as it allows for a more informed discussion on the best paths forward.","gaps":[{"id":"1","options":[{"id":"o1","text":"affecting"},{"id":"o2","text":"affected"},{"id":"o3","text":"affects"},{"id":"o4","text":"affect"}]},{"id":"2","options":[{"id":"o1","text":"impact"},{"id":"o2","text":"affected"},{"id":"o3","text":"reaction"},{"id":"o4","text":"response"}]},{"id":"3","options":[{"id":"o1","text":"serious"},{"id":"o2","text":"seriously"},{"id":"o3","text":"seriousness"},{"id":"o4","text":"seriousnesses"}]},{"id":"4","options":[{"id":"o1","text":"misleading"},{"id":"o2","text":"misled"},{"id":"o3","text":"mislead"},{"id":"o4","text":"misleads"}]},{"id":"5","options":[{"id":"o1","text":"analysis"},{"id":"o2","text":"analyst"},{"id":"o3","text":"analyze"},{"id":"o4","text":"analyzed"}]}],"correct_answer":{"1":"o1","2":"o1","3":"o1","4":"o1","5":"o1"},"explanation":"(1) La forma correcta de usar el verbo en este contexto es el gerundio, que indica una acción continua.\n(2) Aquí se hace referencia a la influencia general de cambio climático, y ''impact'' es el término más adecuado.\n(3) En este caso, un adjetivo describe las consecuencias, por lo que se necesita ''serious''.\n(4) El adjetivo ''misleading'' describe la información que crea confusión y no es clara.\n(5) En este contexto, se requiere un sustantivo que indique el proceso de examinar la evidencia, por lo que ''analysis'' es correcto.","complexity":3,"concept_tags":["reading","complex","texts","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U9_B3_I1', 'ingles-b2-U9', 7, 'fill_blanks', 'Complete the sentences with the correct form of the verbs in brackets to express wishes and regrets.', '{"prompt_es":"Complete the sentences with the correct form of the verbs in brackets to express wishes and regrets.","mastery_tag":"grammar:b2-wish-regret","main_text":"I ___ (finish) my project on time. I feel so stressed now.","correct_answer":["wish I had finished","were","wish I had not taken","had known","wish I had gone"],"explanation":"(1) Usamos ''wish + past perfect'' para expresar arrepentimiento sobre algo que no hicimos en el pasado.\n(2) ''If only'' se usa para expresar un deseo fuerte sobre una situación que no es real. En este caso, usamos ''were'' para situaciones irreales.\n(3) Usamos ''wish + past perfect'' para expresar un arrepentimiento sobre una acción negativa en el pasado.\n(4) En este caso, ''if only + past perfect'' expresa un deseo de que algo diferente hubiera sucedido en el pasado.\n(5) Aquí, ''wish + past perfect'' indica un deseo de haber hecho algo que no hicimos.","complexity":3,"concept_tags":["grammar","wish","regret","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-b2-U10', 'ingles-b2', 10, 'Unit 10', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B1_I1', 'ingles-b2-U10', 1, 'multiple_choice', 'What is the primary purpose of a lecture?', '{"prompt_es":"What is the primary purpose of a lecture?","mastery_tag":"listening:b2-lectures","explanation":"El propósito principal de una conferencia es informar a los estudiantes sobre un tema específico.","stimulus_en":"","options":[{"id":"o1","text":"To entertain"},{"id":"o2","text":"To inform"},{"id":"o3","text":"To debate"},{"id":"o4","text":"To socialize"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B1_I2', 'ingles-b2-U10', 2, 'multiple_choice', 'During a presentation, what is often used to enhance understanding?', '{"prompt_es":"During a presentation, what is often used to enhance understanding?","mastery_tag":"listening:b2-lectures","explanation":"Los materiales impresos, como folletos, ayudan a los oyentes a seguir la presentación y comprender mejor el contenido.","stimulus_en":"","options":[{"id":"o1","text":"Handouts"},{"id":"o2","text":"Emotions"},{"id":"o3","text":"Silence"},{"id":"o4","text":"Random stories"}],"correct_answer":"o1","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B1_I3', 'ingles-b2-U10', 3, 'multiple_choice', 'What should a speaker do to engage the audience?', '{"prompt_es":"What should a speaker do to engage the audience?","mastery_tag":"listening:b2-lectures","explanation":"Hacer preguntas a la audiencia mantiene su interés y les invita a participar en la charla.","stimulus_en":"","options":[{"id":"o1","text":"Speak monotonously"},{"id":"o2","text":"Ask questions"},{"id":"o3","text":"Ignore feedback"},{"id":"o4","text":"Use jargon"}],"correct_answer":"o2","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B1_I4', 'ingles-b2-U10', 4, 'multiple_choice', 'Which of the following is a common evaluation method for presentations?', '{"prompt_es":"Which of the following is a common evaluation method for presentations?","mastery_tag":"listening:b2-lectures","explanation":"La revisión entre compañeros permite a los estudiantes recibir comentarios útiles sobre su desempeño en presentaciones.","stimulus_en":"","options":[{"id":"o1","text":"Peer review"},{"id":"o2","text":"Group fun"},{"id":"o3","text":"Individual study"},{"id":"o4","text":"Silent attention"}],"correct_answer":"o1","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B1_I5', 'ingles-b2-U10', 5, 'multiple_choice', 'What is an effective way to conclude a lecture?', '{"prompt_es":"What is an effective way to conclude a lecture?","mastery_tag":"listening:b2-lectures","explanation":"Resumir los puntos clave ayuda a los estudiantes a recordar la información importante presentada durante la conferencia.","stimulus_en":"","options":[{"id":"o1","text":"Summarize key points"},{"id":"o2","text":"Introduce new topics"},{"id":"o3","text":"Thank the audience"},{"id":"o4","text":"Stay silent"}],"correct_answer":"o1","complexity":3,"concept_tags":["listening","lectures","unit","grammar"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B2_I1', 'ingles-b2-U10', 6, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''must have'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''must have'':","mastery_tag":"grammar:b2-perfect-modals","explanation":"Aquí se utiliza ''must have'' para expresar una obligación pasada que es muy probable que se haya cumplido.","stimulus_en":"It was necessary for him to attend the meeting. (must)\n\nHe must have ...","correct_answer":"attended the meeting.","example":"must have","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B2_I2', 'ingles-b2-U10', 7, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''should have'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''should have'':","mastery_tag":"grammar:b2-perfect-modals","explanation":"Aquí ''should have'' indica que era una buena idea hacer algo en el pasado.","stimulus_en":"It would have been a good idea to ask for help. (should)\n\nYou should have ...","correct_answer":"asked for help.","example":"should have","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B2_I3', 'ingles-b2-U10', 8, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''could have'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''could have'':","mastery_tag":"grammar:b2-perfect-modals","explanation":"Se utiliza ''could have'' para indicar una posibilidad en el pasado que no se cumplió.","stimulus_en":"It was possible for her to finish the project early. (could)\n\nShe could have ...","correct_answer":"finished the project early.","example":"could have","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B2_I4', 'ingles-b2-U10', 9, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''should have'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''should have'':","mastery_tag":"grammar:b2-perfect-modals","explanation":"Aquí se expresa un arrepentimiento sobre algo que no se hizo en el pasado.","stimulus_en":"I regret not studying more for the exam. (should)\n\nI should have ...","correct_answer":"studied more for the exam.","example":"should have","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B2_I5', 'ingles-b2-U10', 10, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''must have'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''must have'':","mastery_tag":"grammar:b2-perfect-modals","explanation":"Usamos ''must have'' para expresar una fuerte suposición sobre una acción pasada.","stimulus_en":"It''s very likely that he arrived late. (must)\n\nHe must have ...","correct_answer":"arrived late.","example":"must have","complexity":3,"concept_tags":["grammar","perfect","modals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B3_I1', 'ingles-b2-U10', 11, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''HARD'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''HARD'':","mastery_tag":"grammar:b2-mixed-conditionals","explanation":"En esta oración transformamos la parte condicional para reflejar un hecho en el pasado que tiene consecuencias en el presente.","stimulus_en":"If he had studied harder, he would be successful now.\n\nIf he had studied harder, he would have... ...","correct_answer":"been successful now.","example":"HARD","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B3_I2', 'ingles-b2-U10', 12, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''LONELY'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''LONELY'':","mastery_tag":"grammar:b2-mixed-conditionals","explanation":"Se utiliza la estructura condicional mixta para expresar cómo una acción pasada podría haber cambiado su estado actual.","stimulus_en":"She didn’t go to the party. Now she feels lonely.\n\nIf she had gone to the party, she wouldn''t feel... ...","correct_answer":"lonely now.","example":"LONELY","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B3_I3', 'ingles-b2-U10', 13, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''LATE'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''LATE'':","mastery_tag":"grammar:b2-mixed-conditionals","explanation":"La transformación de esta oración muestra cómo una decisión pasada afecta el presente.","stimulus_en":"They missed the bus. Now they are late.\n\nIf they hadn''t missed the bus, they wouldn''t be... ...","correct_answer":"late now.","example":"LATE","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B3_I4', 'ingles-b2-U10', 14, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''HEALTHY'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''HEALTHY'':","mastery_tag":"grammar:b2-mixed-conditionals","explanation":"Utilizamos esta versión para conectar acciones hipotéticas con resultados presentes.","stimulus_en":"He doesn''t exercise. He is not healthy.\n\nIf he exercised, he would be... ...","correct_answer":"healthy now.","example":"HEALTHY","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('B2_U10_B3_I5', 'ingles-b2-U10', 15, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''EXPERIENCES'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''EXPERIENCES'':","mastery_tag":"grammar:b2-mixed-conditionals","explanation":"Se usa el pasado perfecto para expresar cómo una acción pasada influyó en su presente.","stimulus_en":"She studied abroad. She has great experiences.\n\nIf she hadn''t studied abroad, she wouldn''t have had... ...","correct_answer":"such great experiences.","example":"EXPERIENCES","complexity":3,"concept_tags":["grammar","mixed","conditionals","unit"]}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

COMMIT;