/**
 * Unidad 49 — Lección 6: Expresión escrita (Transport & Travel Experiences)
 * 15 ejercicios: fill-blank
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_49_LESSON_6_WRITING: Exercise[] = [
  { id: 'a2-u49-l6-w1', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con flight, journey o trip.', questions: [{ question: "[[Our|Nuestro]] ____ [[to|a]] [[London|Londres]] [[took|tardó]] [[three|tres]] [[hours|horas]].", correctAnswer: 'flight', acceptableAnswers: ['flight'], explanation: "[[Flight|Flight]] = [[by plane|en avión]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w2', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra correcta.', questions: [{ question: "[[We|Nosotros]] [[had|tuvimos]] [[a|un]] ____ ____ ____ [[to|a]] [[Paris|París]] [[last|el pasado]] [[month|mes]].", correctAnswer: 'wonderful trip', acceptableAnswers: ['wonderful trip'], explanation: "[[Trip|Trip]] = [[whole experience|toda la experiencia]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w3', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[The|El]] ____ ____ ____ ____ ____ [[was|fue]] [[very|muy]] [[long|larga]].", correctAnswer: 'train journey', acceptableAnswers: ['train journey'], explanation: "[[Journey|Journey]] = [[the act of travelling|el acto de viajar]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w4', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[The|El]] [[flight|vuelo]] [[was|fue]] ____ [[by|por]] [[two|dos]] [[hours|horas]].", correctAnswer: 'delayed', acceptableAnswers: ['delayed'], explanation: "[[Delayed|Delayed]] = [[retrasado]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w5', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: "[[We|Nosotros]] [[took|tomamos]] [[the|el]] ____ [[to|a]] [[the|la]] [[island|isla]].", correctAnswer: 'ferry', acceptableAnswers: ['ferry'], explanation: "[[Ferry|Ferry]] = [[transbordador]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w6', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[The|El]] ____ [[from|de]] [[the|el]] [[airport|aeropuerto]] [[to|a]] [[the|el]] [[hotel|hotel]] [[took|tardó]] [[forty|cuarenta]] [[minutes|minutos]].", correctAnswer: 'journey', acceptableAnswers: ['journey'], explanation: "[[Journey|Journey]] = [[trayecto]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w7', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[He|Él]] [[went|fue]] [[on|en]] [[a|un]] ____ ____ ____ [[to|a]] [[Tokyo|Tokio]].", correctAnswer: 'business trip', acceptableAnswers: ['business trip'], explanation: "[[Business trip|Business trip]] = [[viaje de negocios]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w8', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra correcta.', questions: [{ question: "[[We|Nosotros]] [[had|tuvimos]] [[a|un]] ____ ____ ____ ____ ____ [[across|a través de]] [[America|América]].", correctAnswer: 'great road trip', acceptableAnswers: ['great road trip'], explanation: "[[Road trip|Road trip]] = [[viaje por carretera]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w9', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: "[[I|Yo]] [[have|he]] [[never|nunca]] [[been|estado]] ____ ____ ____ ____ ____ [[but|pero]] [[I|yo]] [[would|me]] [[love|gustaría]] [[to|]] [[try|probar]] [[one|uno]] [[day|algún día]].", correctAnswer: 'on a cruise', acceptableAnswers: ['on a cruise'], explanation: "[[Cruise|Cruise]] = [[crucero]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w10', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[She|Ella]] ____ ____ ____ ____ ____ [[because|porque]] [[she|ella]] [[was|estaba]] [[late|tarde]].", correctAnswer: 'missed her flight', acceptableAnswers: ['missed her flight'], explanation: "[[Miss a flight|Miss a flight]] = [[perder un vuelo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w11', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[We|Nosotros]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[online|en línea]] [[last|el pasado]] [[week|semana]].", correctAnswer: 'booked our flights', acceptableAnswers: ['booked our flights'], explanation: "[[Book a flight|Book a flight]] = [[reservar un vuelo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w12', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[The|El]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[was|fue]] [[beautiful|hermoso]].", correctAnswer: 'train journey to Florence', acceptableAnswers: ['train journey to Florence'], explanation: "[[Journey|Journey]] = [[trayecto]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w13', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[I|Yo]] [[prefer|prefiero]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____.", correctAnswer: 'travelling by train', acceptableAnswers: ['travelling by train'], explanation: "[[Travel by train|Travel by train]] = [[viajar en tren]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w14', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[The|El]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[at|en]] [[three|tres]] [[different|diferentes]] [[ports|puertos]].", correctAnswer: 'cruise stopped', acceptableAnswers: ['cruise stopped'], explanation: "[[Cruise|Cruise]] = [[crucero]]." }] }, topicName: 'Writing' },
  { id: 'a2-u49-l6-w15', type: 'fill-blank', level: 'A2', topic: 'Transport & Travel Experiences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: "[[Our|Nuestro]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[took|tardó]] [[two|dos]] [[hours|horas]].", correctAnswer: 'flight to Rome', acceptableAnswers: ['flight to Rome'], explanation: "[[Flight|Flight]] = [[vuelo]]." }] }, topicName: 'Writing' },
];
