/**
 * Unidad 36 — Lección 6: Expresión escrita (Weekend & Holiday Plans)
 * 15 ejercicios: fill-blank
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_36_LESSON_6_WRITING: Exercise[] = [
  { id: 'a2-u36-l6-w1', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con going to.', questions: [{ question: "[[What|Qué]] ____ ____ ____ ____ [[do|hacer]] [[this|este]] [[weekend|fin de semana]]?", correctAnswer: 'are you going to', acceptableAnswers: ['are you going to'], explanation: "[[What are you going to do|Qué vas a hacer]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w2', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[I|Yo]] ____ ____ ____ [[visit|visitar]] [[my|mis]] [[parents|padres]] [[on|el]] [[Saturday|sábado]].", correctAnswer: 'am going to', acceptableAnswers: ['am going to'], explanation: "[[Going to|Going to]] [[for|para]] [[plans|planes]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w3', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[We|Nosotros]] ____ ____ ____ [[go|ir]] [[to|a]] [[the|la]] [[beach|playa]] [[next|el próximo]] [[Sunday|domingo]].", correctAnswer: 'are going to', acceptableAnswers: ['are going to'], explanation: "[[We are going to|Nosotros vamos a]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w4', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[I|Yo]] ____ ____ ____ [[spend|pasar]] [[my|mis]] [[holidays|vacaciones]] [[in|en]] [[Spain|España]].", correctAnswer: 'am going to', acceptableAnswers: ['am going to'], explanation: "[[Going to|Going to]] [[for|para]] [[holiday|vacaciones]] [[plans|planes]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w5', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[She|Ella]] ____ ____ ____ [[relax|relajarse]] [[at|en]] [[home|casa]] [[this|este]] [[weekend|fin de semana]].", correctAnswer: 'is going to', acceptableAnswers: ['is going to'], explanation: "[[She is going to|Ella va a]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w6', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[They|Ellos]] ____ ____ ____ [[have|tener]] [[a|una]] [[barbecue|barbacoa]] [[on|el]] [[Sunday|domingo]].", correctAnswer: 'are going to', acceptableAnswers: ['are going to'], explanation: "[[They are going to|Ellos van a]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w7', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con going to.', questions: [{ question: "[[I|Yo]] ____ ____ ____ [[stay|quedarme]] [[in|en]] [[bed|la cama]] [[all|toda]] [[morning|la mañana]] [[tomorrow|mañana]].", correctAnswer: 'am going to', acceptableAnswers: ['am going to'], explanation: "[[Going to|Going to]] [[for|para]] [[plans|planes]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w8', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[We|Nosotros]] ____ ____ ____ [[go|ir]] ____ [[hiking|de senderismo]] [[on|el]] [[Saturday|sábado]].", correctAnswer: 'are going to', acceptableAnswers: ['are going to'], explanation: "[[Going to go|Vamos a ir]] [[hiking|de senderismo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w9', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[What|Qué]] ____ ____ ____ ____ [[do|hacer]] [[during|durante]] [[your|tus]] [[holidays|vacaciones]]?", correctAnswer: 'are you going to', acceptableAnswers: ['are you going to'], explanation: "[[What are you going to do|Qué vas a hacer]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w10', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[He|Él]] ____ ____ ____ [[watch|ver]] [[a|un]] [[football|fútbol]] [[match|partido]] [[on|el]] [[Sunday|domingo]].", correctAnswer: 'is going to', acceptableAnswers: ['is going to'], explanation: "[[He is going to|Él va a]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w11', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[We|Nosotros]] ____ ____ ____ [[go|ir]] ____ [[camping|camping]] [[next|el próximo]] [[month|mes]].", correctAnswer: 'are going to', acceptableAnswers: ['are going to'], explanation: "[[Going to go|Vamos a ir]] [[camping|camping]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w12', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[I|Yo]] ____ ____ ____ [[meet|quedar]] [[friends|con amigos]] [[for|para]] [[dinner|cena]] [[this|esta]] [[Friday|viernes]].", correctAnswer: 'am going to', acceptableAnswers: ['am going to'], explanation: "[[Going to|Going to]] [[for|para]] [[arrangements|planes]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w13', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[During|Durante]] [[the|las]] ____ [[I|yo]] [[will|]] [[visit|visitar]] [[museums|museos]].", correctAnswer: 'holidays', acceptableAnswers: ['holidays'], explanation: "[[During the holidays|Durante las vacaciones]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w14', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Next|El próximo]] ____ [[I|yo]] [[am going to|voy a]] [[travel|viajar]] [[to|a]] [[Italy|Italia]].", correctAnswer: 'summer', acceptableAnswers: ['summer'], explanation: "[[Next summer|El próximo verano]]." }] }, topicName: 'Writing' },
  { id: 'a2-u36-l6-w15', type: 'fill-blank', level: 'A2', topic: 'Weekend & Holiday Plans', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con going to.', questions: [{ question: "[[She|Ella]] ____ ____ ____ [[take|hacer]] [[a|un]] [[photo|curso]] [[course|de fotografía]] [[next|el próximo]] [[summer|verano]].", correctAnswer: 'is going to', acceptableAnswers: ['is going to'], explanation: "[[She is going to|Ella va a]]." }] }, topicName: 'Writing' },
];
