/**
 * Unidad 29 — Lección 5: Expresión oral (Could Past Ability & Polite Requests)
 * 15 ejercicios pronunciation
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_29_LESSON_5_SPEAKING: Exercise[] = [
  {
    id: 'a2-u29-l5-s1',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha la frase y repítela en voz alta.',
      targetText: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] [[could|podía]] [[swim|nadar]] [[very well|muy bien]].',
      expectedResponse: 'When I was a child, I could swim very well.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s2',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[I|Yo]] [[could|podía]] [[ride|montar]] [[a|una]] [[bike|bici]] [[at|a]] [[the|los]] [[age|edad]] [[of|de]] [[five|cinco]].',
      expectedResponse: 'I could ride a bike at the age of five.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s3',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[I|Yo]] [[couldn\'t|couldn\'t]] [[speak|hablar]] [[English|inglés]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]].',
      expectedResponse: "I couldn't speak English when I was young.",
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s4',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[Could you|Podrías]] [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]], [[please|por favor]]?',
      expectedResponse: 'Could you pass me the salt, please?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s5',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase de abajo en voz alta.',
      targetText: '[[Could you|Podrías]] [[help|ayudar]] [[me|me]] [[with|con]] [[this|esta]] [[bag|bolsa]]?',
      expectedResponse: 'Could you help me with this bag?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s6',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase en voz alta.',
      targetText: '[[Could you|Podrías]] [[open|abrir]] [[the|la]] [[window|ventana]]? [[It|Hace]] [[is|está]] [[hot|calor]] [[in|en]] [[here|aquí]].',
      expectedResponse: 'Could you open the window? It is hot in here.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s7',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase en voz alta.',
      targetText: '[[Could you|Podrías]] [[turn down|bajar]] [[the|el]] [[volume|volumen]], [[please|por favor]]?',
      expectedResponse: 'Could you turn down the volume, please?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s8',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde en voz alta: ¿Qué podías hacer cuando eras niño?',
      targetText: '[[What could you do when you were a child?|¿Qué podías hacer cuando eras niño?]]',
      expectedResponse: 'When I was a child, I could [activity].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s9',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde en voz alta: ¿Qué no podías hacer cuando eras joven?',
      targetText: '[[What couldn\'t you do when you were young?|¿Qué no podías hacer cuando eras joven?]]',
      expectedResponse: "When I was young, I couldn't [activity].",
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s10',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Haz una petición educada pidiendo ayuda con algo.',
      targetText: '[[Could you help me with...?|¿Podrías ayudarme con...?]]',
      expectedResponse: 'Could you help me with [something]?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s11',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta 2 cosas que podías hacer en el pasado.',
      targetText: '[[I could|Yo podía]] …',
      expectedResponse: 'I could [ability 1]. I could [ability 2].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s12',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta 1 cosa que no podías hacer en el pasado.',
      targetText: '[[I couldn\'t|Yo no podía]] …',
      expectedResponse: "I couldn't [ability].",
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s13',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Haz 2 peticiones educadas usando "Could you...?"',
      targetText: '[[Could you|Podrías]] … [[please|por favor]]?',
      expectedResponse: 'Could you [request 1], please? Could you [request 2], please?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s14',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Inventa 2 frases: una sobre habilidad en el pasado, otra petición educada.',
      targetText: '[[I could|Yo podía]] … [[Could you|Podrías]] …?',
      expectedResponse: 'I could [ability]. Could you [request], please?',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u29-l5-s15',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Haz una breve presentación: 2 habilidades del pasado + 2 peticiones educadas que harías en un restaurante o en casa.',
      targetText: '[[I could|Yo podía]] … [[Could you|Podrías]] …?',
      expectedResponse: 'When I was young, I could [ability]. I could [ability]. Could you [request]? Could you [request]?',
    },
    topicName: 'Speaking',
  },
];
