/**
 * Unidad 60 — Lección 5: Expresión oral (Final A2 Review)
 * 15 ejercicios de pronunciación sobre terminar el curso
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_60_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a2-u60-l5-s1', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Congratulations! You have completed the A2 course|¡Felicitaciones! Has completado el curso A2]].', expectedResponse: 'Congratulations! You have completed the A2 course.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s2', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I have made a lot of progress in my English|He hecho mucho progreso en mi inglés]].', expectedResponse: 'I have made a lot of progress in my English.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s3', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I am proud of my achievement|Estoy orgulloso de mi logro]].', expectedResponse: 'I am proud of my achievement.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s4', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I received my certificate yesterday|Recibí mi certificado ayer]].', expectedResponse: 'I received my certificate yesterday.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s5', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[Well done! You have finished the A2 course|¡Bien hecho! Has terminado el curso A2]].', expectedResponse: 'Well done! You have finished the A2 course.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s6', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[This is a great success|Este es un gran éxito]].', expectedResponse: 'This is a great success.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s7', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[Congratulations on passing the exam|¡Felicitaciones por aprobar el examen!]]', expectedResponse: 'Congratulations on passing the exam!' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s8', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[Have you completed the A2 course|¿Has completado el curso A2?]]', expectedResponse: 'Yes, I have completed the A2 course. / No, not yet.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s9', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[Are you going to continue studying English|¿Vas a continuar estudiando inglés?]]', expectedResponse: 'Yes, I am going to continue. / I will start the B1 course soon.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s10', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[How much progress have you made in English|¿Cuánto progreso has hecho en inglés?]]', expectedResponse: 'I have made a lot of progress. / I have improved a lot.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s11', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta una frase sobre tu logro en el curso A2.', targetText: '[[I|Yo]] ____ ____. ([[completed|completé]]/[[finished|terminé]] + [[the course|el curso]])', expectedResponse: 'I completed the A2 course. / I finished the course.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s12', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: "[[I am proud of|Estoy orgulloso de]] ____" (my progress, my achievement, my certificate)', targetText: '[[I am proud of|Estoy orgulloso de]] ____.', expectedResponse: 'I am proud of my progress. / I am proud of my achievement.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s13', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta una frase con "success" o "achievement".', targetText: '____ ____ ____.', expectedResponse: 'This is a great success. / I am proud of my achievement.' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s14', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: "[[Congratulations|Felicitaciones]] ____" (on your success, on passing, on completing)', targetText: '[[Congratulations|Felicitaciones]] ____.', expectedResponse: 'Congratulations on your success! / Congratulations on passing!' }, topicName: 'Speaking' },
  { id: 'a2-u60-l5-s15', type: 'pronunciation', level: 'A2', topic: 'Final A2 Review', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Describe en 2-3 frases tu experiencia completando el curso A2. Usa: progress, achievement, certificate, congratulations.', targetText: '[[I|Yo]] ____ ____. [[I|Yo]] ____ ____ ____.', expectedResponse: 'I have made a lot of progress. I received my certificate and I am proud of my achievement.' }, topicName: 'Speaking' },
];
