/**
 * Unidad 46 — Lección 6: Expresión escrita (Comparing Places: Adjectives)
 * 15 ejercicios: fill-blank
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_46_LESSON_6_WRITING: Exercise[] = [
  { id: 'a2-u46-l6-w1', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el comparativo correcto.', questions: [{ question: "[[London|Londres]] [[is|es]] ____ [[than|que]] [[my|mi]] [[village|pueblo]].", correctAnswer: 'noisier', acceptableAnswers: ['noisier'], explanation: "[[Noisy|Noisy]] → [[noisier|noisier]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w2', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[The|El]] [[countryside|campo]] [[is|es]] ____ [[than|que]] [[the|la]] [[city|ciudad]].", correctAnswer: 'quieter', acceptableAnswers: ['quieter'], explanation: "[[Quiet|Quiet]] → [[quieter|quieter]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w3', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el comparativo correcto.', questions: [{ question: "[[Tokyo|Tokio]] [[is|es]] ____ [[than|que]] [[most|la mayoría]] [[cities|ciudades]].", correctAnswer: 'more modern', acceptableAnswers: ['more modern'], explanation: "[[Modern|Modern]] = [[long|adjetivo largo]] → [[more modern|más moderno]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w4', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[New York|Nueva York]] [[is|es]] ____ [[than|que]] [[Boston|Boston]].", correctAnswer: 'busier', acceptableAnswers: ['busier'], explanation: "[[Busy|Busy]] → [[busier|busier]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w5', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[The|La]] [[beach|playa]] [[is|es]] ____ [[than|que]] [[the|el]] [[city|centro]] [[centre|centro]].", correctAnswer: 'cleaner', acceptableAnswers: ['cleaner'], explanation: "[[Clean|Clean]] → [[cleaner|cleaner]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w6', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Paris|París]] [[is|es]] ____ [[than|que]] [[my|mi]] [[town|pueblo]].", correctAnswer: 'more expensive', acceptableAnswers: ['more expensive'], explanation: "[[Expensive|Expensive]] → [[more expensive|más caro]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w7', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[The|El]] [[village|pueblo]] [[is|es]] ____ [[than|que]] [[the|la]] [[city|ciudad]].", correctAnswer: 'safer', acceptableAnswers: ['safer'], explanation: "[[Safe|Safe]] → [[safer|safer]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w8', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Barcelona|Barcelona]] [[is|es]] ____ [[than|que]] [[many|muchas]] [[cities|ciudades]].", correctAnswer: 'more beautiful', acceptableAnswers: ['more beautiful'], explanation: "[[Beautiful|Beautiful]] → [[more beautiful|más bonita]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w9', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[The|El]] [[centre|centro]] [[is|es]] ____ [[than|que]] [[the|los]] [[suburbs|suburbios]].", correctAnswer: 'more crowded', acceptableAnswers: ['more crowded'], explanation: "[[Crowded|Crowded]] → [[more crowded|más concurrido]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w10', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[Life|La vida]] [[in|en]] [[the|el]] [[country|campo]] [[is|es]] ____ [[than|que]] [[in|en]] [[the|la]] [[city|ciudad]].", correctAnswer: 'slower', acceptableAnswers: ['slower'], explanation: "[[Slow|Slow]] → [[slower|slower]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w11', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[The|El]] [[air|aire]] [[in|en]] [[the|las]] [[mountains|montañas]] [[is|es]] ____ [[than|que]] [[in|en]] [[the|la]] [[city|ciudad]].", correctAnswer: 'fresher', acceptableAnswers: ['fresher'], explanation: "[[Fresh|Fresh]] → [[fresher|fresher]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w12', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Traffic|El tráfico]] [[in|en]] [[the|la]] [[city|ciudad]] [[is|es]] ____ [[than|que]] [[in|en]] [[the|el]] [[countryside|campo]].", correctAnswer: 'heavier', acceptableAnswers: ['heavier'], explanation: "[[Heavy|Heavy]] → [[heavier|heavier]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w13', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[This|Esta]] [[area|zona]] [[is|es]] ____ [[than|que]] [[downtown|el centro]].", correctAnswer: 'greener', acceptableAnswers: ['greener'], explanation: "[[Green|Green]] → [[greener|greener]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w14', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[The|Las]] [[streets|calles]] [[here|aquí]] [[are|son]] ____ [[than|que]] [[in|en]] [[the|el]] [[centre|centro]].", correctAnswer: 'wider', acceptableAnswers: ['wider'], explanation: "[[Wide|Wide]] → [[wider|wider]]." }] }, topicName: 'Writing' },
  { id: 'a2-u46-l6-w15', type: 'fill-blank', level: 'A2', topic: 'Comparing Places: Adjectives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[Singapore|Singapur]] [[is|es]] ____ [[than|que]] [[my|mi]] [[country|país]].", correctAnswer: 'more developed', acceptableAnswers: ['more developed'], explanation: "[[Developed|Developed]] → [[more developed|más desarrollado]]." }] }, topicName: 'Writing' },
];
