/**
 * Unidad 33 — Lección 2: Vocabulario (Predictions & Future)
 * 15 ejercicios: predicciones, futuro, opiniones
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Predictions|Predicciones]] [[&|y]] [[Future|Futuro]]';
const INSTRUCTIONS_SB = 'Ordena las palabras para formar una oración correcta.';

export const UNIT_33_LESSON_2_VOCABULARY: Exercise[] = [
  {
    id: 'a2-u33-l2-v1',
    type: 'flashcard',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Aprende las palabras más importantes de la unidad.',
      items: [
        { front: '[[Prediction|Predicción]]', back: 'Predicción' },
        { front: '[[Forecast|Pronóstico]]', back: 'Pronóstico' },
        { front: '[[Future|Futuro]]', back: 'Futuro' },
        { front: '[[Maybe|Quizás]]', back: 'Quizás' },
        { front: '[[Probably|Probablemente]]', back: 'Probablemente' },
        { front: '[[Definitely|Definitivamente]]', back: 'Definitivamente' },
        { front: '[[Perhaps|Tal vez]]', back: 'Tal vez' },
        { front: '[[Expect|Esperar]]', back: 'Esperar' },
        { front: '[[Believe|Creer]]', back: 'Creer' },
        { front: '[[Hope|Esperar]]', back: 'Esperar' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v2',
    type: 'matching',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Relaciona cada palabra con su traducción.',
      pairs: [
        { id: 'p1', left: '[[Prediction|Predicción]]', right: 'Predicción' },
        { id: 'p2', left: '[[Forecast|Pronóstico]]', right: 'Pronóstico' },
        { id: 'p3', left: '[[Probably|Probablemente]]', right: 'Probablemente' },
        { id: 'p4', left: '[[Expect|Esperar]]', right: 'Esperar' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v3',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I think it will rain tomorrow|Creo que lloverá mañana]].",
      words: ['[[I|Yo]]', '[[think|creo]]', '[[it|que]]', '[[will|]]', '[[rain|lloverá]]', '[[tomorrow|mañana]]'],
      explanation: 'I think + it will + verb = predicción.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v4',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[She will probably pass the exam|Ella probablemente aprobará el examen]].",
      words: ['[[She|Ella]]', '[[will|]]', '[[probably|probablemente]]', '[[pass|aprobará]]', '[[the|el]]', '[[exam|examen]]'],
      explanation: 'Will + probably + verb.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v5',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Maybe he will change his mind|Quizás él cambiará de opinión]].",
      words: ['[[Maybe|Quizás]]', '[[he|él]]', '[[will|]]', '[[change|cambiará]]', '[[his|su]]', '[[mind|opinión]]'],
      explanation: 'Maybe + subject + will + verb.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v6',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[They won't win the game|Ellos no ganarán el juego]].",
      words: ['[[They|Ellos]]', "[[won't|no]]", '[[win|ganarán]]', '[[the|el]]', '[[game|juego]]'],
      explanation: "Won't = will not para predicción negativa.",
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v7',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Will it be sunny tomorrow|¿Será soleado mañana?]]",
      words: ['[[Will|¿]]', '[[it|]]', '[[be|será]]', '[[sunny|soleado]]', '[[tomorrow|mañana]]'],
      explanation: 'Will it be + adjective = pregunta sobre tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v8',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[In 2050 people will live longer|En 2050 la gente vivirá más tiempo]].",
      words: ['[[In|En]]', '[[2050|2050]]', '[[people|la gente]]', '[[will|]]', '[[live|vivirá]]', '[[longer|más tiempo]]'],
      explanation: 'Predicción para futuro lejano.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v9',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I will never forget your birthday|Nunca olvidaré tu cumpleaños]].",
      words: ['[[I|Yo]]', '[[will|]]', '[[never|nunca]]', '[[forget|olvidaré]]', '[[your|tu]]', '[[birthday|cumpleaños]]'],
      explanation: 'Will never + verb.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v10',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[The price will go up next year|El precio subirá el próximo año]].",
      words: ['[[The|El]]', '[[price|precio]]', '[[will|]]', '[[go|subirá]]', '[[up|]]', '[[next|el próximo]]', '[[year|año]]'],
      explanation: 'Will + go up = subir.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v11',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Who will win the election|¿Quién ganará la elección?]]",
      words: ['[[Who|Quién]]', '[[will|]]', '[[win|ganará]]', '[[the|la]]', '[[election|elección]]'],
      explanation: 'Who will + verb = pregunta de predicción.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v12',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Technology will improve our lives|La tecnología mejorará nuestras vidas]].",
      words: ['[[Technology|La tecnología]]', '[[will|]]', '[[improve|mejorará]]', '[[our|nuestras]]', '[[lives|vidas]]'],
      explanation: 'Predicción sobre tecnología.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v13',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[It won't take long to get there|No llevará mucho llegar allí]].",
      words: ["[[It|]]", "[[won't|no]]", '[[take|llevará]]', '[[long|mucho]]', '[[to|para]]', '[[get|llegar]]', '[[there|allí]]'],
      explanation: "Won't take long = no llevará mucho.",
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v14',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I expect it will be busy|Espero que esté ocupado]].",
      words: ['[[I|Yo]]', '[[expect|espero]]', '[[it|que]]', '[[will|]]', '[[be|esté]]', '[[busy|ocupado]]'],
      explanation: 'I expect + it will + be.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u33-l2-v15',
    type: 'sentence-building',
    level: 'A2',
    topic: "Future with 'Will': Predictions",
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Do you think they will come|¿Crees que vendrán?]]",
      words: ['[[Do|¿]]', '[[you|tú]]', '[[think|crees]]', '[[they|que ellos]]', '[[will|]]', '[[come|vendrán]]'],
      explanation: 'Do you think + subject + will + verb?',
    },
    topicName: 'Vocabulary',
  },
];
