/**
 * Unidad 44 — Lección 2: Vocabulario (For & Since - Duration)
 * 15 ejercicios: flashcard, matching, sentence-building
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[For & Since|For y Since]]';
const INSTRUCTIONS_SB = 'Ordena las palabras para formar una oración correcta.';

export const UNIT_44_LESSON_2_VOCABULARY: Exercise[] = [
  {
    id: 'a2-u44-l2-v1',
    type: 'flashcard',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Aprende las palabras más importantes de la unidad.',
      items: [
        { front: '[[For|Durante]]', back: 'Durante (período de tiempo)' },
        { front: '[[Since|Desde]]', back: 'Desde (punto en el tiempo)' },
        { front: '[[Years|Años]]', back: 'Años' },
        { front: '[[Months|Meses]]', back: 'Meses' },
        { front: '[[Weeks|Semanas]]', back: 'Semanas' },
        { front: '[[Hours|Horas]]', back: 'Horas' },
        { front: '[[Childhood|Infancia]]', back: 'Infancia' },
        { front: '[[January|Enero]]', back: 'Enero' },
        { front: '[[Monday|Lunes]]', back: 'Lunes' },
        { front: '[[Long time|Mucho tiempo]]', back: 'Mucho tiempo' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v2',
    type: 'matching',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Relaciona cada palabra con su uso.',
      pairs: [
        { id: 'p1', left: '[[For|For]]', right: 'Período (5 years, 2 hours)' },
        { id: 'p2', left: '[[Since|Since]]', right: 'Punto en el tiempo (2020, Monday)' },
        { id: 'p3', left: '[[Years|Years]]', right: 'Años' },
        { id: 'p4', left: '[[Childhood|Childhood]]', right: 'Infancia' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v3',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have lived here for five years|He vivido aquí durante cinco años]].",
      words: ['[[I|Yo]]', '[[have lived|he vivido]]', '[[here|aquí]]', '[[for|durante]]', '[[five|cinco]]', '[[years|años]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v4',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[She has worked at this company since 2020|Ha trabajado en esta empresa desde 2020]].",
      words: ['[[She|Ella]]', '[[has worked|ha trabajado]]', '[[at|en]]', '[[this|esta]]', '[[company|empresa]]', '[[since|desde]]', '[[2020|2020]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v5',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[We have known each other for a long time|Nos conocemos desde hace mucho tiempo]].",
      words: ['[[We|Nosotros]]', '[[have known|hemos conocido]]', '[[each other|el uno al otro]]', '[[for|durante]]', '[[a long time|mucho tiempo]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v6',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[He has been here since Monday|Ha estado aquí desde el lunes]].",
      words: ['[[He|Él]]', '[[has been|ha estado]]', '[[here|aquí]]', '[[since|desde]]', '[[Monday|lunes]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v7',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[They have been married for ten years|Han estado casados durante diez años]].",
      words: ['[[They|Ellos]]', '[[have been|han estado]]', '[[married|casados]]', '[[for|durante]]', '[[ten|diez]]', '[[years|años]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v8',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have studied English since last year|He estudiado inglés desde el año pasado]].",
      words: ['[[I|Yo]]', '[[have studied|he estudiado]]', '[[English|inglés]]', '[[since|desde]]', '[[last year|el año pasado]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v9',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[She has lived in London for three months|Ha vivido en Londres durante tres meses]].",
      words: ['[[She|Ella]]', '[[has lived|ha vivido]]', '[[in|en]]', '[[London|Londres]]', '[[for|durante]]', '[[three|tres]]', '[[months|meses]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v10',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[He has had that job since January|Ha tenido ese trabajo desde enero]].",
      words: ['[[He|Él]]', '[[has had|ha tenido]]', '[[that|ese]]', '[[job|trabajo]]', '[[since|desde]]', '[[January|enero]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v11',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have not seen him for a long time|No le he visto desde hace mucho tiempo]].",
      words: ['[[I|Yo]]', '[[have not seen|no he visto]]', '[[him|a él]]', '[[for|desde hace]]', '[[a long time|mucho tiempo]]'],
      explanation: 'For + período de tiempo en negativas.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v12',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[They have lived here since childhood|Han vivido aquí desde la infancia]].",
      words: ['[[They|Ellos]]', '[[have lived|han vivido]]', '[[here|aquí]]', '[[since|desde]]', '[[childhood|infancia]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v13',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[She has been waiting for half an hour|Ha estado esperando durante media hora]].",
      words: ['[[She|Ella]]', '[[has been|ha estado]]', '[[waiting|esperando]]', '[[for|durante]]', '[[half|media]]', '[[an hour|hora]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v14',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have had this phone for six months|He tenido este teléfono durante seis meses]].",
      words: ['[[I|Yo]]', '[[have had|he tenido]]', '[[this|este]]', '[[phone|teléfono]]', '[[for|durante]]', '[[six|seis]]', '[[months|meses]]'],
      explanation: 'For + período de tiempo.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u44-l2-v15',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: For & Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[My brother has been living in Paris since March|Mi hermano ha estado viviendo en París desde marzo]].",
      words: ['[[My|Mi]]', '[[brother|hermano]]', '[[has been living|ha estado viviendo]]', '[[in|en]]', '[[Paris|París]]', '[[since|desde]]', '[[March|marzo]]'],
      explanation: 'Since + punto en el tiempo.',
    },
    topicName: 'Vocabulary',
  },
];
