/**
 * Unidad 48 — Lección 6: Expresión escrita (Comparing Lifestyles)
 * 15 ejercicios: fill-blank
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_48_LESSON_6_WRITING: Exercise[] = [
  { id: 'a2-u48-l6-w1', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma comparativa correcta.', questions: [{ question: "[[Life|La vida]] [[in|en]] [[the city|la ciudad]] [[is|es]] ____ ____ [[than|que]] [[life|la vida]] [[in|en]] [[the country|el campo]].", correctAnswer: 'busier than', acceptableAnswers: ['busier than'], explanation: "[[Busy|Busy]] → [[busier than|más ajetreada que]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w2', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[People|La gente]] [[in|en]] [[villages|pueblos]] [[have|tiene]] ____ ____ ____ [[lifestyle|estilo de vida]].", correctAnswer: 'a quieter', acceptableAnswers: ['a quieter'], explanation: "[[Quiet|Quiet]] → [[quieter|más tranquilo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w3', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el comparativo correcto.', questions: [{ question: "[[Living|Vivir]] [[in|en]] [[a|una]] [[big|gran]] [[city|ciudad]] [[is|es]] ____ ____ ____ [[than|que]] [[living|vivir]] [[in|en]] [[a|un]] [[small|pequeño]] [[town|pueblo]].", correctAnswer: 'more expensive than', acceptableAnswers: ['more expensive than'], explanation: "[[Expensive|Expensive]] → [[more expensive than|más caro que]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w4', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Country|La vida]] [[life|rural]] [[is|es]] ____ ____ [[than|que]] [[city|la vida]] [[life|urbana]].", correctAnswer: 'healthier than', acceptableAnswers: ['healthier than'], explanation: "[[Healthy|Healthy]] → [[healthier than|más saludable que]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w5', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[I|Yo]] [[prefer|prefiero]] ____ ____ ____ [[lifestyle|estilo de vida]] [[with|con]] [[less|menos]] [[stress|estrés]].", correctAnswer: 'a simpler', acceptableAnswers: ['a simpler'], explanation: "[[Simple|Simple]] → [[simpler|más simple]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w6', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[She|Ella]] [[works|trabaja]] ____ ____ ____ [[than|que]] [[her|su]] [[brother|hermano]] [[does|]]", correctAnswer: 'longer hours than', acceptableAnswers: ['longer hours than'], explanation: "[[Long|Long]] → [[longer|más largo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w7', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[My|Mi]] [[neighbours|vecinos]] [[are|son]] ____ ____ [[than|que]] [[yours|los tuyos]] [[in|en]] [[the city|la ciudad]].", correctAnswer: 'friendlier than', acceptableAnswers: ['friendlier than'], explanation: "[[Friendly|Friendly]] → [[friendlier than|más amigables que]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w8', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[There|Hay]] [[are|]] ____ ____ ____ [[in|en]] [[big|grandes]] [[cities|ciudades]] [[than|que]] [[in|en]] [[small|pequeños]] [[towns|pueblos]].", correctAnswer: 'more opportunities', acceptableAnswers: ['more opportunities'], explanation: "[[More|More]] + [[noun|sustantivo]] = [[comparison|comparación]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w9', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[He|Él]] [[enjoys|disfruta]] ____ ____ ____ ____ [[of|de]] [[life|vida]] [[now|ahora]].", correctAnswer: 'a more relaxed pace', acceptableAnswers: ['a more relaxed pace'], explanation: "[[Relaxed|Relaxed]] → [[more relaxed|más relajado]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w10', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra que falta.', questions: [{ question: "[[We|Nosotros]] [[have|tenemos]] ____ ____ ____ ____ [[than|que]] [[we|nosotros]] [[used to|solíamos]] [[have|tener]].", correctAnswer: 'less free time than', acceptableAnswers: ['less free time than'], explanation: "[[Less|Less]] = [[comparison|comparación]] [[with|con]] [[uncountable|no contable]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w11', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[Urban|La vida]] [[life|urbana]] [[is|es]] ____ ____ [[than|que]] [[rural|la vida]] [[life|rural]].", correctAnswer: 'faster than', acceptableAnswers: ['faster than'], explanation: "[[Fast|Fast]] → [[faster than|más rápida que]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w12', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[Do|¿]] [[you|te]] [[prefer|prefieres]] ____ ____ ____ ____ [[or|o]] [[quieter|más tranquilo]] [[lifestyle|estilo de vida]]?", correctAnswer: 'a busier', acceptableAnswers: ['a busier'], explanation: "[[Busy|Busy]] → [[busier|más ajetreado]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w13', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase.', questions: [{ question: "[[The|El]] [[air|aire]] [[is|es]] ____ [[in|en]] [[the country|el campo]] [[than|que]] [[in|en]] [[the city|la ciudad]].", correctAnswer: 'cleaner', acceptableAnswers: ['cleaner'], explanation: "[[Clean|Clean]] → [[cleaner|más limpio]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w14', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[They|Ellos]] [[chose|eligieron]] ____ ____ ____ ____ [[lifestyle|estilo de vida]] [[after|después de]] [[retiring|jubilarse]].", correctAnswer: 'a more active', acceptableAnswers: ['a more active'], explanation: "[[Active|Active]] → [[more active|más activo]]." }] }, topicName: 'Writing' },
  { id: 'a2-u48-l6-w15', type: 'fill-blank', level: 'A2', topic: 'Comparing Lifestyles', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[There|Hay]] [[are|]] ____ ____ ____ ____ [[in|en]] [[the city|la ciudad]] [[than|que]] [[in|en]] [[the country|el campo]].", correctAnswer: 'more restaurants', acceptableAnswers: ['more restaurants'], explanation: "[[More|More]] + [[plural noun|sustantivo plural]]." }] }, topicName: 'Writing' },
];
