/**
 * Unidad 37 — Lección 4: Comprensión auditiva (Future Hopes & Dreams)
 * 15 actividades: 1 audio + 15 preguntas
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[What|Qué]] [[would|te]] [[you|gustaría]] [[like to|]] [[do|hacer]] [[in|en]] [[the|el]] [[future|futuro]]? [[I|Yo]] [[hope to|espero]] [[travel|viajar]] [[to|a]] [[many|muchos]] [[countries|países]]. [[I|Yo]] [[dream of|sueño con]] [[living|vivir]] [[in|en]] [[Japan|Japón]] [[one|algún]] [[day|día]]. [[I|Yo]] [[would like to|me gustaría]] [[learn|aprender]] [[Japanese|japonés]] [[and|y]] [[visit|visitar]] [[Tokyo|Tokio]]. [[My|Mi]] [[brother|hermano]] [[dreams of|sueña con]] [[becoming|convertirse]] [[a|en]] [[pilot|piloto]]. [[We|Nosotros]] [[both|ambos]] [[hope to|esperamos]] [[see|ver]] [[the|el]] [[world|mundo]] [[one|algún]] [[day|día]].`;

const INSTRUCTIONS = 'Escucha el audio de abajo. Puedes leer la transcripción después de escuchar. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does|espera]] [[the|el]] [[speaker|hablante]] [[hope to|el hablante]] [[do|hacer]]?', options: ['[[Study|Estudiar]] [[abroad|en el extranjero]]', '[[Travel|Viajar]] [[to|a]] [[many|muchos]] [[countries|países]]', '[[Learn|Aprender]] [[English|inglés]]', '[[Get|Conseguir]] [[a|un]] [[job|trabajo]]'], correctAnswer: 1, explanation: '[[He/She|Él/Ella]] [[says|dice]] "[[I hope to travel to many countries|espero viajar a muchos países]]".' },
  { question: '[[What|Con qué]] [[does|sueña]] [[the|el]] [[speaker|hablante]] [[dream of|el hablante]]?', options: ['[[Living|Vivir]] [[in|en]] [[Japan|Japón]]', '[[Becoming|Convertirse]] [[a|en]] [[pilot|piloto]]', '[[Teaching|Enseñar]] [[English|inglés]]', '[[Working|Trabajar]] [[in|en]] [[Tokyo|Tokio]]'], correctAnswer: 0, explanation: '[[He/She|Él/Ella]] [[says|dice]] "[[I dream of living in Japan|sueño con vivir en Japón]]".' },
  { question: '[[What|Qué]] [[would|le]] [[the|el]] [[speaker|hablante]] [[like to|gustaría]] [[learn|aprender]]?', options: ['[[Chinese|Chino]]', '[[Japanese|Japonés]]', '[[Korean|Coreano]]', '[[Spanish|Español]]'], correctAnswer: 1, explanation: '[[He/She|Él/Ella]] [[says|dice]] "[[I would like to learn Japanese|me gustaría aprender japonés]]".' },
  { question: '[[What|Con qué]] [[does|sueña]] [[the|el]] [[speaker\'s|del hablante]] [[brother|hermano]] [[dream of|el hermano]]?', options: ['[[Living|Vivir]] [[in|en]] [[Japan|Japón]]', '[[Becoming|Convertirse]] [[a|en]] [[pilot|piloto]]', '[[Learning|Aprender]] [[Japanese|japonés]]', '[[Travelling|Viajar]] [[to|a]] [[Tokyo|Tokio]]'], correctAnswer: 1, explanation: '[[He/She|Él/Ella]] [[says|dice]] "[[My brother dreams of becoming a pilot|mi hermano sueña con convertirse en piloto]]".' },
  { question: '[[What|Qué]] [[city|ciudad]] [[would|le]] [[the|el]] [[speaker|hablante]] [[like to|gustaría]] [[visit|visitar]]?', options: ['[[Osaka|Osaka]]', '[[Tokyo|Tokio]]', '[[Kyoto|Kioto]]', '[[Nagoya|Nagoya]]'], correctAnswer: 1, explanation: '[[He/She|Él/Ella]] [[says|dice]] "[[visit Tokyo|visitar Tokio]]".' },
  { question: '[[What|Qué]] [[do|esperan]] [[both|ambos]] [[the|el]] [[speaker|hablante]] [[and|y]] [[brother|hermano]] [[hope to|hermano]] [[do|hacer]]?', options: ['[[Learn|Aprender]] [[Japanese|japonés]]', '[[See|Ver]] [[the|el]] [[world|mundo]]', '[[Become|Convertirse]] [[pilots|pilotos]]', '[[Live|Vivir]] [[in|en]] [[Japan|Japón]]'], correctAnswer: 1, explanation: '[[They|Ellos]] [[say|dicen]] "[[we both hope to see the world|ambos esperamos ver el mundo]]".' },
  { question: '[[The|El]] [[speaker|hablante]] [[uses|usa]] [[hope to|hope to]], [[would like to|would like to]] [[and|y]] [[dream of|dream of]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[He/She|Él/Ella]] [[uses|usa]] [[all|todas]] [[three|tres]] [[structures|estructuras]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]] [[of|del]] [[this|este]] [[audio|audio]]?', options: ['[[Past|Eventos]] [[events|pasados]]', '[[Future|Esperanzas]] [[hopes|y]] [[dreams|sueños]]', '[[Weather|Tiempo]]', '[[Shopping|Compras]]'], correctAnswer: 1, explanation: '[[The|El]] [[audio|audio]] [[is|es]] [[about|sobre]] [[hopes|esperanzas]] [[and|y]] [[dreams|sueños]].' },
  { question: '[[How many|Cuántas]] [[structures|estructuras]] [[does|usa]] [[the|el]] [[speaker|hablante]] [[use|el hablante]] [[for|para]] [[hopes|esperanzas]] [[and|y]] [[dreams|sueños]]?', options: ['[[one|una]]', '[[two|dos]]', '[[three|tres]]', '[[four|cuatro]]'], correctAnswer: 2, explanation: '[[Three|Tres]]: [[hope to|hope to]], [[would like to|would like to]], [[dream of|dream of]].' },
  { question: '[[The|El]] ____ ____ ____ ____ [[brother|hermano]] ____ ____ ____ ____ ____ ____ ____ ____ [[pilot|piloto]].', options: ['[[speaker\'s|del hablante]]', '[[listener\'s|del oyente]]', '[[friend\'s|del amigo]]', '[[teacher\'s|del profesor]]'], correctAnswer: 0, explanation: '[[The|El]] [[speaker|hablante]] [[mentions|menciona]] "[[my brother|mi hermano]]".' },
  { question: '[[Japan|Japón]] [[is|es]] ____ ____ ____ ____ ____ ____ ____ ____ [[important|importante]] ____ ____ ____ ____ ____ ____ ____ ____ [[the|el]] ____ ____ ____ ____ ____ ____ ____ ____ [[speaker|hablante]].', options: ['[[important to|importante para]]', '[[not important to|no importante para]]', '[[sometimes important to|a veces importante para]]', '[[never important to|nunca importante para]]'], correctAnswer: 0, explanation: '[[He/She|Él/Ella]] [[dreams of|sueña con]] [[living|vivir]] [[there|allí]] [[and|y]] [[wants|quiere]] [[to|a]] [[learn|aprender]] [[Japanese|japonés]].' },
  { question: '[[The|El]] [[speaker|hablante]] [[and|y]] [[brother|hermano]] ____ ____ ____ ____ ____ ____ ____ ____ [[same|mismo]] ____ ____ ____ ____ ____ ____ ____ ____ [[hope|esperanza]].', options: ['[[share|comparten]] [[the|la]]', '[[do not share|no comparten]] [[the|la]]', '[[might share|podrían compartir]] [[the|la]]', '[[shared|compartían]] [[the|la]]'], correctAnswer: 0, explanation: '[[Both|Ambos]] [[hope to|esperan]] [[see|ver]] [[the|el]] [[world|mundo]].' },
  { question: '[[Would you like to|¿Te gustaría]] [[is|es]] ____ ____ ____ ____ ____ ____ ____ ____ [[polite|educada]] ____ ____ ____ ____ ____ ____ ____ ____ [[way|forma]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[ask|preguntar]].', options: ['[[a|una]]', '[[not a|no una]]', '[[sometimes a|a veces una]]', '[[never a|nunca una]]'], correctAnswer: 0, explanation: '[[Would you like to|¿Te gustaría]] = [[polite|educada]] [[way|forma]] [[to|de]] [[ask|preguntar]].' },
  { question: '[[Dream of|Dream of]] ____ ____ ____ ____ ____ ____ ____ ____ [[followed|seguido]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[by|por]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[gerund|gerundio]].', options: ['[[is|es]]', '[[is not|no es]]', '[[might be|podría ser]]', '[[was|era]]'], correctAnswer: 0, explanation: '[[Dream of|Dream of]] + [[gerund|gerundio]] ([[living|vivir]], [[becoming|convertirse]]).' },
  { question: '[[The|El]] ____ ____ ____ ____ ____ ____ ____ ____ [[is|está]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[about|sobre]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[future|futuro]].', options: ['[[conversation|conversación]]', '[[argument|discusión]]', '[[story|historia]]', '[[news|noticias]]'], correctAnswer: 0, explanation: '[[It|Es]] [[is|una]] [[conversation|conversación]] [[about|sobre]] [[future|futuras]] [[hopes|esperanzas]] [[and|y]] [[dreams|sueños]].' },
];

export const UNIT_37_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `a2-u37-l4-l${i + 1}`,
  type: 'listening',
  level: 'A2',
  topic: 'Future Hopes & Dreams',
  difficulty: 'easy',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
