/**
 * Unidad 42 — Lección 2: Vocabulario (Ever & Never - Experiences)
 * 15 ejercicios: flashcard, matching, sentence-building
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Ever & Never|Ever y Never]]';
const INSTRUCTIONS_SB = 'Ordena las palabras para formar una oración correcta.';

export const UNIT_42_LESSON_2_VOCABULARY: Exercise[] = [
  {
    id: 'a2-u42-l2-v1',
    type: 'flashcard',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Aprende las palabras más importantes de la unidad.',
      items: [
        { front: '[[Ever|Alguna vez]]', back: 'Alguna vez' },
        { front: '[[Never|Nunca]]', back: 'Nunca' },
        { front: '[[Met|Conocido]]', back: 'Conocido' },
        { front: '[[Ridden|Montado]]', back: 'Montado' },
        { front: '[[Tried|Probado]]', back: 'Probado' },
        { front: '[[Travelled|Viajado]]', back: 'Viajado' },
        { front: '[[Famous|Famoso]]', back: 'Famoso' },
        { front: '[[Beach|Playa]]', back: 'Playa' },
        { front: '[[Cruise|Crucero]]', back: 'Crucero' },
        { front: '[[Motorcycle|Motocicleta]]', back: 'Motocicleta' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v2',
    type: 'matching',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Relaciona cada palabra con su traducción.',
      pairs: [
        { id: 'p1', left: '[[Ever|Alguna vez]]', right: 'Alguna vez' },
        { id: 'p2', left: '[[Never|Nunca]]', right: 'Nunca' },
        { id: 'p3', left: '[[Cruise|Crucero]]', right: 'Crucero' },
        { id: 'p4', left: '[[Famous|Famoso]]', right: 'Famoso' },
      ],
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v3',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Have you ever been to Spain|¿Has estado alguna vez en España?]]",
      words: ['[[Have|¿]]', '[[you|tú]]', '[[ever|alguna vez]]', '[[been|estado]]', '[[to|en]]', '[[Spain|España]]'],
      explanation: 'Ever en preguntas sobre experiencias.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v4',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have never eaten sushi in my life|Nunca he comido sushi en mi vida]].",
      words: ['[[I|Yo]]', '[[have never|nunca he]]', '[[eaten|comido]]', '[[sushi|sushi]]', '[[in my life|en mi vida]]'],
      explanation: 'Never va después de have/has.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v5',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Has she ever ridden a horse|¿Ha montado alguna vez a caballo?]]",
      words: ['[[Has|¿]]', '[[she|ella]]', '[[ever|alguna vez]]', '[[ridden|montado]]', '[[a|un]]', '[[horse|caballo]]'],
      explanation: 'Ever en preguntas con has.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v6',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[He has never been to the beach|Nunca ha estado en la playa]].",
      words: ['[[He|Él]]', '[[has never|nunca ha]]', '[[been to|estado en]]', '[[the|la]]', '[[beach|playa]]'],
      explanation: 'Never + has + been to.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v7',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Have they ever tried Indian food|¿Han probado alguna vez comida india?]]",
      words: ['[[Have|¿]]', '[[they|ellos]]', '[[ever|alguna vez]]', '[[tried|probado]]', '[[Indian|india]]', '[[food|comida]]'],
      explanation: 'Ever en preguntas con have.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v8',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[I have never seen a real snowstorm|Nunca he visto una ventisca real]].",
      words: ['[[I|Yo]]', '[[have never|nunca he]]', '[[seen|visto]]', '[[a|una]]', '[[real|verdadera]]', '[[snowstorm|ventisca]]'],
      explanation: 'Never para experiencias negativas.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v9',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Has your brother ever travelled abroad|¿Tu hermano ha viajado alguna vez al extranjero?]]",
      words: ['[[Has|¿]]', '[[your|tu]]', '[[brother|hermano]]', '[[ever|alguna vez]]', '[[travelled|viajado]]', '[[abroad|al extranjero]]'],
      explanation: 'Ever en preguntas sobre experiencias.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v10',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[We have never tried Thai food|Nunca hemos probado comida tailandesa]].",
      words: ['[[We|Nosotros]]', '[[have never|nunca hemos]]', '[[tried|probado]]', '[[Thai|tailandesa]]', '[[food|comida]]'],
      explanation: 'Never con we have.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v11',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Have you ever been on a cruise|¿Has estado alguna vez en un crucero?]]",
      words: ['[[Have|¿]]', '[[you|tú]]', '[[ever|alguna vez]]', '[[been on|estado en]]', '[[a|un]]', '[[cruise|crucero]]'],
      explanation: 'Ever en preguntas. Been on a cruise.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v12',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[She has never travelled alone abroad|Nunca ha viajado sola al extranjero]].",
      words: ['[[She|Ella]]', '[[has never|nunca ha]]', '[[travelled|viajado]]', '[[alone|sola]]', '[[abroad|al extranjero]]'],
      explanation: 'Never + has + past participle.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v13',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Have you ever met a famous person|¿Has conocido alguna vez a una persona famosa?]]",
      words: ['[[Have|¿]]', '[[you|tú]]', '[[ever|alguna vez]]', '[[met|conocido]]', '[[a|a una]]', '[[famous|famosa]]', '[[person|persona]]'],
      explanation: 'Ever en preguntas sobre experiencias.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v14',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[Have you ever ridden a motorcycle|¿Has montado alguna vez una motocicleta?]]",
      words: ['[[Have|¿]]', '[[you|tú]]', '[[ever|alguna vez]]', '[[ridden|montado]]', '[[a|una]]', '[[motorcycle|motocicleta]]'],
      explanation: 'Ever en preguntas. Ridden = past participle de ride.',
    },
    topicName: 'Vocabulary',
  },
  {
    id: 'a2-u42-l2-v15',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Present Perfect: Ever & Never',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: INSTRUCTIONS_SB,
      correctSentence: "[[My friend has never been to Africa|Mi amigo nunca ha estado en África]].",
      words: ['[[My|Mi]]', '[[friend|amigo]]', '[[has never|nunca ha]]', '[[been to|estado en]]', '[[Africa|África]]'],
      explanation: 'Third person: has never been to.',
    },
    topicName: 'Vocabulary',
  },
];
