/**
 * Unidad 54 — Lección 2: Vocabulario (Permission & Possibility)
 * 15 ejercicios: flashcard, matching, sentence-building
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Permission|Permiso]] [[&|y]] [[Possibility|Posibilidad]]';
const INSTRUCTIONS_SB = 'Ordena las palabras para formar una oración correcta.';

export const UNIT_54_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'a2-u54-l2-v1', type: 'flashcard', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Aprende las palabras más importantes de la unidad.', items: [{ front: '[[Permission|Permiso]]', back: 'Permiso' }, { front: '[[Possibility|Posibilidad]]', back: 'Posibilidad' }, { front: '[[Could|Podría]]', back: 'Podría' }, { front: '[[May|Puede]]', back: 'Puede' }, { front: '[[Request|Petición]]', back: 'Petición' }, { front: '[[Allow|Permitir]]', back: 'Permitir' }, { front: '[[Perhaps|Quizás]]', back: 'Quizás' }, { front: '[[Maybe|Tal vez]]', back: 'Tal vez' }, { front: '[[Borrow|Pedir prestado]]', back: 'Pedir prestado' }, { front: '[[Polite|Educado]]', back: 'Educado' }] }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v2', type: 'matching', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Relaciona cada palabra con su traducción.', pairs: [{ id: 'p1', left: '[[Permission|Permiso]]', right: 'Permiso' }, { id: 'p2', left: '[[Possibility|Posibilidad]]', right: 'Posibilidad' }, { id: 'p3', left: '[[Could|Podría]]', right: 'Podría' }, { id: 'p4', left: '[[May|Puede]]', right: 'Puede' }] }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v3', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[Could you pass the salt, please|¿Podrías pasar la sal, por favor?]]", words: ['[[Could|¿]]', '[[you|tú]]', '[[pass|pasar]]', '[[the|la]]', '[[salt|sal]]', '[[please|por favor]]'], explanation: 'Could para petición educada.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v4', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[It may rain tomorrow|Puede que llueva mañana]].", words: ['[[It|Puede]]', '[[may|que]]', '[[rain|llueva]]', '[[tomorrow|mañana]]'], explanation: 'May para posibilidad.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v5', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[May I use your phone|¿Puedo usar tu teléfono?]]", words: ['[[May|¿]]', '[[I|yo]]', '[[use|usar]]', '[[your|tu]]', '[[phone|teléfono]]'], explanation: 'May I para pedir permiso.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v6', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[Could you help me with this|¿Podrías ayudarme con esto?]]", words: ['[[Could|¿]]', '[[you|tú]]', '[[help|ayudar]]', '[[me|me]]', '[[with|con]]', '[[this|esto]]'], explanation: 'Could you para petición.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v7', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[We could go to the beach|Podríamos ir a la playa]].", words: ['[[We|Nosotros]]', '[[could|podríamos]]', '[[go|ir]]', '[[to|a]]', '[[the|la]]', '[[beach|playa]]'], explanation: 'Could para posibilidad.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v8', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[You may sit here|Puedes sentarte aquí]].", words: ['[[You|Tú]]', '[[may|puedes]]', '[[sit|sentarte]]', '[[here|aquí]]'], explanation: 'May para dar permiso.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v9', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[I could speak Spanish when I was young|Podía hablar español cuando era joven]].", words: ['[[I|Yo]]', '[[could|podía]]', '[[speak|hablar]]', '[[Spanish|español]]', '[[when|cuando]]'], explanation: 'Could para capacidad pasada.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v10', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[Could I borrow your pen|¿Podría pedir prestado tu bolígrafo?]]", words: ['[[Could|¿]]', '[[I|yo]]', '[[borrow|pedir prestado]]', '[[your|tu]]', '[[pen|bolígrafo]]'], explanation: 'Could I para petición educada.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v11', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[The train may be late|El tren puede estar retrasado]].", words: ['[[The|El]]', '[[train|tren]]', '[[may|puede]]', '[[be|estar]]', '[[late|retrasado]]'], explanation: 'May para posibilidad.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v12', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[She may be at home now|Puede que esté en casa ahora]].", words: ['[[She|Ella]]', '[[may|puede]]', '[[be|estar]]', '[[at|en]]', '[[home|casa]]'], explanation: 'May para posibilidad.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v13', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[Could you repeat that, please|¿Podrías repetir eso, por favor?]]", words: ['[[Could|¿]]', '[[you|tú]]', '[[repeat|repetir]]', '[[that|eso]]', '[[please|por favor]]'], explanation: 'Could you para petición.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v14', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[Students may leave early today|Los estudiantes pueden salir temprano hoy]].", words: ['[[Students|Estudiantes]]', '[[may|pueden]]', '[[leave|salir]]', '[[early|temprano]]', '[[today|hoy]]'], explanation: 'May para permiso.' }, topicName: 'Vocabulary' },
  { id: 'a2-u54-l2-v15', type: 'sentence-building', level: 'A2', topic: 'Modals: Could & May', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS_SB, correctSentence: "[[This could be the right answer|Esto podría ser la respuesta correcta]].", words: ['[[This|Esto]]', '[[could|podría]]', '[[be|ser]]', '[[the|la]]', '[[right|correcta]]', '[[answer|respuesta]]'], explanation: 'Could para posibilidad.' }, topicName: 'Vocabulary' },
];
