/**
 * Unidad 38 — Lección 4: Comprensión auditiva (Time Clauses)
 * 15 actividades: 1 audio + 15 preguntas
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[I|Yo]] [[will|te]] [[call|llamaré]] [[you|te]] [[when|cuando]] [[I|yo]] [[arrive|llegue]]. [[As soon as|Tan pronto como]] [[I|yo]] [[finish|termine]] [[work|trabajo]], [[I|yo]] [[will|iré]] [[go|a]] [[home|casa]]. [[When|Cuando]] [[the|el]] [[meeting|reunión]] [[ends|termine]], [[we|nosotros]] [[will|podremos]] [[can|]] [[discuss|discutir]] [[it|eso]]. [[I|Yo]] [[will|te]] [[send|enviaré]] [[you|te]] [[the|el]] [[file|archivo]] [[as soon as|tan pronto como]] [[I|yo]] [[can|pueda]].`;

const INSTRUCTIONS = 'Escucha el audio de abajo. Puedes leer la transcripción después de escuchar. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[will|hará]] [[the|el]] [[speaker|hablante]] [[do|el hablante]] [[when|cuando]] [[he|él]] [[arrives|llegue]]?', options: ['[[Send|Enviar]] [[file|archivo]]', '[[Call|Llamar]] [[you|te]]', '[[Go|Ir]] [[home|casa]]', '[[Finish|Terminar]] [[work|trabajo]]'], correctAnswer: 1, explanation: '[[He|Él]] [[says|dice]] "[[I will call you when I arrive|te llamaré cuando llegue]]".' },
  { question: '[[What|Qué]] [[will|hará]] [[the|el]] [[speaker|hablante]] [[do|el hablante]] [[as soon as|tan pronto como]] [[he|él]] [[finishes|termine]] [[work|trabajo]]?', options: ['[[Call|Llamar]]', '[[Go|Ir]] [[home|casa]]', '[[Send|Enviar]] [[file|archivo]]', '[[Discuss|Discutir]]'], correctAnswer: 1, explanation: '[[He|Él]] [[says|dice]] "[[I will go home|iré a casa]]".' },
  { question: '[[When|Cuándo]] [[will|podrán]] [[they|ellos]] [[discuss|discutir]] [[it|eso]]?', options: ['[[When|Cuando]] [[speaker|hablante]] [[arrives|llegue]]', '[[When|Cuando]] [[the|la]] [[meeting|reunión]] [[ends|termine]]', '[[As soon as|Tan pronto como]] [[work|trabajo]] [[finishes|termine]]', '[[Before|Antes]] [[meeting|reunión]]'], correctAnswer: 1, explanation: '[[They|Ellos]] [[say|dicen]] "[[when the meeting ends|cuando termine la reunión]]".' },
  { question: '[[What|Qué]] [[will|enviará]] [[the|el]] [[speaker|hablante]] [[send|el hablante]]?', options: ['[[A|Un]] [[message|mensaje]]', '[[The|el]] [[file|archivo]]', '[[An|Un]] [[email|email]]', '[[A|Una]] [[letter|carta]]'], correctAnswer: 1, explanation: '[[He|Él]] [[says|dice]] "[[I will send you the file|te enviaré el archivo]]".' },
  { question: '[[When|Cuándo]] [[will|enviará]] [[the|el]] [[speaker|hablante]] [[send|el hablante]] [[the|el]] [[file|archivo]]?', options: ['[[When|Cuando]] [[he|él]] [[arrives|llegue]]', '[[As soon as|Tan pronto como]] [[he|él]] [[can|pueda]]', '[[When|Cuando]] [[meeting|reunión]] [[ends|termine]]', '[[Before|Antes]] [[work|trabajo]]'], correctAnswer: 1, explanation: '[[He|Él]] [[says|dice]] "[[as soon as I can|tan pronto como pueda]]".' },
  { question: '[[The|El]] [[speaker|hablante]] [[uses|usa]] [[when|when]] [[and|y]] [[as soon as|as soon as]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[He|Él]] [[uses|usa]] [[both|ambas]] [[structures|estructuras]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the|el]] [[main|principal]] [[topic|tema]]?', options: ['[[Past|Eventos]] [[events|pasados]]', '[[Time|Oraciones]] [[clauses|temporales]]', '[[Weather|Tiempo]]', '[[Shopping|Compras]]'], correctAnswer: 1, explanation: '[[The|El]] [[audio|audio]] [[is|es]] [[about|sobre]] [[time|oraciones]] [[clauses|temporales]].' },
  { question: '[[How many|Cuántas]] [[time|oraciones]] [[clauses|temporales]] [[does|usa]] [[the|el]] [[speaker|hablante]] [[use|el hablante]]?', options: ['[[one|una]]', '[[two|dos]]', '[[three|tres]]', '[[four|cuatro]]'], correctAnswer: 3, explanation: '[[Four|Cuatro]]: [[when I arrive|cuando llegue]], [[as soon as I finish|tan pronto como termine]], [[when meeting ends|cuando termine reunión]], [[as soon as I can|tan pronto como pueda]].' },
  { question: '[[The|El]] [[speaker|hablante]] [[uses|usa]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[in|en]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[time|oraciones]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[clauses|temporales]].', options: ['[[present|presente]] [[simple|simple]]', '[[past|pasado]] [[simple|simple]]', '[[future|futuro]]', '[[continuous|continuo]]'], correctAnswer: 0, explanation: '[[Present|Presente]] [[simple|simple]] [[in|en]] [[time|oraciones]] [[clauses|temporales]].' },
  { question: '[[The|El]] [[speaker|hablante]] [[is|está]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[at|en]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[work|trabajo]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[He|Él]] [[mentions|menciona]] [[finish work|terminar trabajo]] [[and|y]] [[meeting|reunión]].' },
  { question: '[[What|Qué]] [[will|hará]] [[the|el]] [[speaker|hablante]] [[do|el hablante]] [[first|primero]]?', options: ['[[Go|Ir]] [[home|casa]]', '[[Call|Llamar]]', '[[Send|Enviar]] [[file|archivo]]', '[[Not clear|No está claro]]'], correctAnswer: 3, explanation: '[[The|El]] [[order|orden]] [[depends|depende]] [[on|de]] [[when|cuando]] [[things|cosas]] [[happen|ocurran]].' },
  { question: '[[The|El]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[speaker|hablante]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[promises|promete]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[to|a]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[do|hacer]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[several|varias]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[things|cosas]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[He|Él]] [[promises|promete]] [[call|llamar]], [[go home|ir a casa]], [[send file|enviar archivo]].' },
  { question: '[[As soon as|As soon as]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[means|significa]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[immediately|inmediatamente]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[after|después]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[As soon as|Tan pronto como]] = [[immediately|inmediatamente]] [[after|después]].' },
  { question: '[[The|El]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[is|es]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[probably|probablemente]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[at|en]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[work|trabajo]].', options: ['[[speaker|hablante]]', '[[listener|oyente]]', '[[friend|amigo]]', '[[boss|jefe]]'], correctAnswer: 0, explanation: '[[The|El]] [[speaker|hablante]] [[mentions|menciona]] [[work|trabajo]] [[and|y]] [[meeting|reunión]].' },
  { question: '[[In|En]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[main|oraciones]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[clauses|principales]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[the|el]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[speaker|hablante]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[uses|usa]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[will|will]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[I will call|te llamaré]], [[I will go|iré]], [[we will can|podremos]], [[I will send|enviaré]].' },
];

export const UNIT_38_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `a2-u38-l4-l${i + 1}`,
  type: 'listening',
  level: 'A2',
  topic: 'Time Clauses: When, As soon as',
  difficulty: 'easy',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
