/**
 * Unidad 16 — Lección 6: Expresión escrita (Past Continuous)
 * 15 ejercicios: 5 fill-blank + 10 writing
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_16_LESSON_6_WRITING: Exercise[] = [
  {
    id: 'a2-u16-l6-w1',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase con was o were. Escribe tu respuesta.',
      questions: [
        {
          question: '[[I|Yo]] ____ [[watching|viendo]] [[TV|televisión]] [[at|a]] [[8pm|las 8]].',
          correctAnswer: 'was',
          acceptableAnswers: ['was'],
          explanation: '[[I|Yo]]/[[he|él]]/[[she|ella]]/[[it|él]] + [[was|estaba]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w2',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que complete la frase.',
      questions: [
        {
          question: '[[They|Ellos]] ____ [[playing|jugando]] [[football|fútbol]] [[when|cuando]] [[it|él]] [[rained|llovió]].',
          correctAnswer: 'were',
          acceptableAnswers: ['were'],
          explanation: '[[We|Nosotros]]/[[you|tú]]/[[they|ellos]] + [[were|estaban]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w3',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa con la forma correcta del verbo (-ing).',
      questions: [
        {
          question: '[[She|Ella]] [[was|estaba]] ____ [[dinner|cena]] [[at|a]] [[7pm|las 7]]. (cook)',
          correctAnswer: 'cooking',
          acceptableAnswers: ['cooking'],
          explanation: '[[Was|Estaba]] + [[verb|verbo]] + [[-ing|-ando]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w4',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          question: '[[We|Nosotros]] ____ [[studying|estudiando]] [[when|cuando]] [[the|el]] [[teacher|profesor]] [[arrived|llegó]].',
          correctAnswer: 'were',
          acceptableAnswers: ['were'],
          explanation: '[[We|Nosotros]] + [[were|estábamos]] + [[-ing|-ando]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w5',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase.',
      questions: [
        {
          question: '[[He|Él]] [[was|estaba]] ____ [[his|su]] [[dog|perro]] [[when|cuando]] [[he|él]] [[saw|vió]] [[the|el]] [[cat|gato]]. (walk)',
          correctAnswer: 'walking',
          acceptableAnswers: ['walking'],
          explanation: '[[Was|Estaba]] + [[walking|paseando]] ([[walk|pasear]] + -ing).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w6',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[I|Yo]] [[was|estaba]] [[watching|viendo]] [[TV|televisión]] [[at|a]] [[8pm|las 8]].',
      words: ['[[was|estaba]]', '[[I|Yo]]', '[[watching|viendo]]', '[[TV|televisión]]', '[[at|a]]', '[[8pm|las 8]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w7',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[They|Ellos]] [[were|estaban]] [[playing|jugando]] [[football|fútbol]] [[when|cuando]] [[it|él]] [[rained|llovió]].',
      words: ['[[were|estaban]]', '[[They|Ellos]]', '[[playing|jugando]]', '[[football|fútbol]]', '[[when|cuando]]', '[[it|él]]', '[[rained|llovió]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w8',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras.',
      correctSentence: '[[While|Mientras]] [[she|ella]] [[was|estaba]] [[cooking|cocinando]], [[the|el]] [[phone|teléfono]] [[rang|sonó]].',
      words: ['[[While|Mientras]]', '[[she|ella]]', '[[was|estaba]]', '[[cooking|cocinando]]', '[[the|el]]', '[[phone|teléfono]]', '[[rang|sonó]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w9',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe dos frases sobre lo que estabas haciendo ayer a las 8. Usa "I was + -ing".',
      prompt: '[[At|A]] [[8pm|las 8]] [[yesterday|ayer]] [[I|yo]] ____.',
      modelExample: '[[At|A]] [[8pm|las 8]] [[yesterday|ayer]] [[I|yo]] [[was|estaba]] [[watching|viendo]] [[TV|televisión]]. [[I|Yo]] [[was|estaba]] [[also|tambien]] [[eating|comiendo]] [[dinner|cena]].',
      minWords: 10,
      maxWords: 25,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w10',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe una frase sobre lo que estaban haciendo dos personas. Usa "They were + -ing".',
      prompt: '[[They|Ellos]] ____.',
      modelExample: '[[They|Ellos]] [[were|estaban]] [[playing|jugando]] [[football|fútbol]] [[in|en]] [[the|el]] [[park|parque]].',
      minWords: 6,
      maxWords: 15,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w11',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe una frase con "While ... was ..., ... happened".',
      prompt: '[[While|Mientras]] ____ ____, ____.',
      modelExample: '[[While|Mientras]] [[I|yo]] [[was|estaba]] [[reading|leyendo]], [[the|el]] [[phone|teléfono]] [[rang|sonó]].',
      minWords: 8,
      maxWords: 20,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w12',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2-3 frases sobre lo que hacía tu familia anoche. Usa was/were + -ing.',
      prompt: '[[Last night|Anoche]] ____.',
      modelExample: '[[Last night|Anoche]] [[my|mi]] [[mother|madre]] [[was|estaba]] [[cooking|cocinando]]. [[My|Mi]] [[father|padre]] [[was|estaba]] [[watching|viendo]] [[TV|televisión]]. [[I|Yo]] [[was|estaba]] [[studying|estudiando]].',
      minWords: 15,
      maxWords: 40,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w13',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo breve (4-5 frases) sobre lo que estabas haciendo cuando algo interrumpió. Usa Past Continuous y Past Simple.',
      prompt: '[[Describe what you were doing when something interrupted|Describe lo que estabas haciendo cuando algo te interrumpió]].',
      modelExample: '[[Yesterday|Ayer]] [[afternoon|tarde]] [[I|yo]] [[was|estaba]] [[reading|leyendo]] [[in|en]] [[the|el]] [[park|parque]]. [[My|Mi]] [[friend|amigo]] [[was|estaba]] [[running|corriendo]]. [[Suddenly|De repente]] [[it|él]] [[started|empezó]] [[to|a]] [[rain|llover]]. [[Everyone|Todos]] [[ran|corrió]] [[to|a]] [[find|encontrar]] [[shelter|refugio]].',
      minWords: 35,
      maxWords: 80,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w14',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 4-5 frases describiendo qué hacía cada persona en tu casa ayer a las 7. Usa was/were + -ing.',
      prompt: '[[At 7pm yesterday|Ayer a las 7]] ____.',
      modelExample: '[[At|A]] [[7pm|las 7]] [[yesterday|ayer]] [[my|mi]] [[mother|madre]] [[was|estaba]] [[cooking|cocinando]] [[dinner|cena]]. [[My|Mi]] [[father|padre]] [[was|estaba]] [[reading|leyendo]] [[the|el]] [[newspaper|periódico]]. [[My|Mi]] [[sister|hermana]] [[was|estaba]] [[studying|estudiando]] [[in|en]] [[her|su]] [[room|habitación]]. [[I|Yo]] [[was|estaba]] [[watching|viendo]] [[TV|televisión]].',
      minWords: 40,
      maxWords: 90,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u16-l6-w15',
    type: 'writing',
    level: 'A2',
    topic: 'Past Continuous',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo (4-6 frases) sobre un momento del pasado. Describe qué estaban haciendo varias personas cuando algo pasó. Usa Past Continuous y Past Simple.',
      prompt: '[[Describe a moment in the past|Describe un momento del pasado]].',
      modelExample: '[[Last|El]] [[Saturday|sábado]] [[night|noche]] [[at|a]] [[8pm|las 8]] [[I|yo]] [[was|estaba]] [[watching|viendo]] [[TV|televisión]]. [[My|Mi]] [[sister|hermana]] [[was|estaba]] [[studying|estudiando]]. [[My|Mis]] [[parents|padres]] [[were|estaban]] [[cooking|cocinando]] [[dinner|cena]]. [[Suddenly|De repente]] [[the|el]] [[doorbell|timbre]] [[rang|sonó]]. [[It|Era]] [[was|era]] [[our|nuestro]] [[neighbour|vecino]]. [[We|Nosotros]] [[were|estábamos]] [[all|todos]] [[surprised|sorprendidos]].',
      minWords: 50,
      maxWords: 120,
    },
    topicName: 'Writing',
  },
];
