/**
 * Unidad 29 — Lección 6: Expresión escrita (Could Past Ability & Polite Requests)
 * 15 ejercicios: 5 fill-blank + 10 writing
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_29_LESSON_6_WRITING: Exercise[] = [
  {
    id: 'a2-u29-l6-w1',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa con could o couldn\'t.',
      questions: [
        {
          question: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] ____ [[swim|nadar]] [[very well|muy bien]].',
          correctAnswer: 'could',
          acceptableAnswers: ['could'],
          explanation: '[[Could|Could]] = [[past ability|habilidad en pasado]] [[positive|positiva]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w2',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la forma correcta.',
      questions: [
        {
          question: '[[I|Yo]] ____ [[speak|hablar]] [[English|inglés]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]].',
          correctAnswer: "couldn't",
          acceptableAnswers: ["couldn't", 'could not'],
          explanation: '[[Couldn\'t|couldn\'t]] = [[past ability|habilidad en pasado]] [[negative|negativa]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w3',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la petición educada.',
      questions: [
        {
          question: '____ ____ ____ [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]], [[please|por favor]]?',
          correctAnswer: 'Could you',
          acceptableAnswers: ['Could you'],
          explanation: '[[Could you|Could you]] = [[polite|educada]] [[request|petición]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w4',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          question: '[[Could you|Podrías]] ____ [[me|me]] [[with|con]] [[this|esta]] [[bag|bolsa]]?',
          correctAnswer: 'help',
          acceptableAnswers: ['help'],
          explanation: '[[Could you help me|¿Podrías ayudarme]] = [[polite|educada]] [[request|petición]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w5',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase.',
      questions: [
        {
          question: '[[Could you|Podrías]] ____ [[the|la]] [[window|ventana]]? [[It|Hace]] [[is|está]] [[hot|calor]].',
          correctAnswer: 'open',
          acceptableAnswers: ['open'],
          explanation: '[[Could you open|¿Podrías abrir]] = [[polite|educada]] [[request|petición]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w6',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2 frases: una habilidad que tenías de niño y una que no tenías.',
      prompt: '[[I could|Yo podía]] … [[I couldn\'t|Yo no podía]] …',
      modelExample: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] [[could|podía]] [[swim|nadar]] [[very well|muy bien]]. [[I|Yo]] [[couldn\'t|couldn\'t]] [[speak|hablar]] [[English|inglés]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]].',
      minWords: 25,
      maxWords: 55,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w7',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2 peticiones educadas usando "Could you...?"',
      prompt: '[[Could you|Podrías]] … [[please|por favor]]?',
      modelExample: '[[Could you|Podrías]] [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]], [[please|por favor]]? [[Could you|Podrías]] [[help|ayudar]] [[me|me]] [[with|con]] [[this|esta]] [[bag|bolsa]]?',
      minWords: 20,
      maxWords: 50,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w8',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 3 frases sobre habilidades en el pasado: 2 que podías hacer y 1 que no podías.',
      prompt: '[[Past abilities|Habilidades en el pasado]]',
      modelExample: '[[I|Yo]] [[could|podía]] [[ride|montar]] [[a|una]] [[bike|bici]] [[at|a]] [[the|los]] [[age|edad]] [[of|de]] [[five|cinco]]. [[I|Yo]] [[could|podía]] [[run|correr]] [[very fast|muy rápido]]. [[I|Yo]] [[couldn\'t|couldn\'t]] [[cook|cocinar]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]].',
      minWords: 35,
      maxWords: 75,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w9',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo breve (4-5 frases) sobre tus habilidades en el pasado y haz 2 peticiones educadas.',
      prompt: '[[Past abilities + polite requests|Habilidades en pasado + peticiones educadas]]',
      modelExample: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] [[could|podía]] [[swim|nadar]] [[very well|muy bien]]. [[I|Yo]] [[could|podía]] [[ride|montar]] [[a|una]] [[bike|bici]]. [[I|Yo]] [[couldn\'t|couldn\'t]] [[speak|hablar]] [[English|inglés]]. [[Could you|Podrías]] [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]], [[please|por favor]]? [[Could you|Podrías]] [[open|abrir]] [[the|la]] [[window|ventana]]?',
      minWords: 50,
      maxWords: 100,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w10',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde: ¿Qué podías hacer cuando eras niño? 3-4 frases.',
      prompt: '[[What could you do when you were a child?|¿Qué podías hacer cuando eras niño?]]',
      modelExample: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] [[could|podía]] [[swim|nadar]] [[very well|muy bien]]. [[I|Yo]] [[could|podía]] [[ride|montar]] [[a|una]] [[bike|bici]] [[at|a]] [[the|los]] [[age|edad]] [[of|de]] [[five|cinco]]. [[I|Yo]] [[couldn\'t|couldn\'t]] [[speak|hablar]] [[English|inglés]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]].',
      minWords: 30,
      maxWords: 65,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w11',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 3 peticiones educadas que harías en un restaurante.',
      prompt: '[[Polite requests at a restaurant|Peticiones educadas en un restaurante]]',
      modelExample: '[[Could you|Podrías]] [[bring|traer]] [[me|me]] [[the|la]] [[menu|carta]], [[please|por favor]]? [[Could you|Podrías]] [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]]? [[Could you|Podrías]] [[bring|traer]] [[the|la]] [[bill|cuenta]], [[please|por favor]]?',
      minWords: 30,
      maxWords: 65,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w12',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Explica la diferencia entre "could" (past ability) y "Could you...?" (polite request) en 2 frases.',
      prompt: '[[Difference between could uses|Diferencia entre los usos de could]]',
      modelExample: '[[Could|Could]] [[for|para]] [[past ability|habilidad en pasado]] [[means|significa]] "[[I could swim|podía nadar]]" — [[ability|habilidad]] [[in|en]] [[the|el]] [[past|pasado]]. [[Could you|Could you]] [[for|para]] [[polite requests|peticiones educadas]] [[means|significa]] "[[Could you help me?|¿Podrías ayudarme?]]" — [[asking|pedir]] [[politely|educadamente]].',
      minWords: 30,
      maxWords: 65,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w13',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2 peticiones educadas que harías en clase o en la oficina.',
      prompt: '[[Polite requests at class or office|Peticiones educadas en clase u oficina]]',
      modelExample: '[[Could you|Podrías]] [[repeat|repetir]] [[that|eso]], [[please|por favor]]? [[Could you|Podrías]] [[turn down|bajar]] [[the|el]] [[volume|volumen]]? [[Could you|Podrías]] [[tell|decir]] [[me|me]] [[the|la]] [[time|hora]]?',
      minWords: 25,
      maxWords: 55,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w14',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 3 frases: 2 con "I could" y 1 con "Could you...?"',
      prompt: '[[2 I could + 1 Could you|2 I could + 1 Could you]]',
      modelExample: '[[I|Yo]] [[could|podía]] [[play|tocar]] [[the|la]] [[piano|piano]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]]. [[I|Yo]] [[could|podía]] [[run|correr]] [[very fast|muy rápido]]. [[Could you|Podrías]] [[open|abrir]] [[the|la]] [[window|ventana]], [[please|por favor]]?',
      minWords: 35,
      maxWords: 75,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u29-l6-w15',
    type: 'writing',
    level: 'A2',
    topic: 'Could Past Ability & Polite Requests',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un texto breve (4-6 frases) sobre tus habilidades en el pasado y 2-3 peticiones educadas que harías en una situación cotidiana.',
      prompt: '[[Past abilities + polite requests in daily life|Habilidades en pasado + peticiones educadas en la vida diaria]].',
      modelExample: '[[When|Cuando]] [[I|yo]] [[was|era]] [[a|un]] [[child|niño]], [[I|yo]] [[could|podía]] [[swim|nadar]] [[very well|muy bien]]. [[I|Yo]] [[could|podía]] [[ride|montar]] [[a|una]] [[bike|bici]] [[at|a]] [[the|los]] [[age|edad]] [[of|de]] [[five|cinco]]. [[I|Yo]] [[couldn\'t|couldn\'t]] [[speak|hablar]] [[English|inglés]] [[when|cuando]] [[I|yo]] [[was|era]] [[young|joven]]. [[Could you|Podrías]] [[pass|pasar]] [[me|me]] [[the|la]] [[salt|sal]], [[please|por favor]]? [[Could you|Podrías]] [[help|ayudar]] [[me|me]] [[with|con]] [[this|esta]] [[bag|bolsa]]? [[Could you|Podrías]] [[open|abrir]] [[the|la]] [[window|ventana]]?',
      minWords: 55,
      maxWords: 120,
    },
    topicName: 'Writing',
  },
];
