/**
 * Unidad 21 — Lección 6: Expresión escrita (Going to Plans & Intentions)
 * 15 ejercicios: 5 fill-blank + 10 writing
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_21_LESSON_6_WRITING: Exercise[] = [
  {
    id: 'a2-u21-l6-w1',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase con la palabra correcta. Escribe tu respuesta.',
      questions: [
        {
          question: '[[I|Yo]] ____ [[going to|a]] [[visit|visitar]] [[my|mi]] [[family|familia]] [[next week|la próxima semana]].',
          correctAnswer: 'am',
          acceptableAnswers: ['am'],
          explanation: '[[I|Yo]] + [[am going to|voy a]] + [[infinitive|infinitivo]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w2',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que complete la frase.',
      questions: [
        {
          question: '[[She|Ella]] ____ [[going to|a]] [[study|estudiar]] [[English|inglés]] [[next year|el próximo año]].',
          correctAnswer: 'is',
          acceptableAnswers: ['is'],
          explanation: '[[She|Ella]] + [[is going to|va a]] + [[infinitive|infinitivo]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w3',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa con una palabra.',
      questions: [
        {
          question: '[[They|Ellos]] ____ [[going to|a]] [[travel|viajar]] [[to|a]] [[Spain|España]] [[in August|en agosto]].',
          correctAnswer: 'are',
          acceptableAnswers: ['are'],
          explanation: '[[They|Ellos]] + [[are going to|van a]] + [[infinitive|infinitivo]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w4',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          question: '[[We|Nosotros]] ____ ____ [[going to|a]] [[stay|quedarnos]] [[at|en]] [[home|casa]] [[tonight|esta noche]].',
          correctAnswer: 'are not',
          acceptableAnswers: ['are not', "aren't"],
          explanation: '[[Negative|Negativa]]: [[we|nosotros]] + [[are not going to|no vamos a]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w5',
    type: 'fill-blank',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase.',
      questions: [
        {
          question: '[[He|Él]] ____ [[going to|a]] [[buy|comprar]] [[a|un]] [[new|nuevo]] [[car|coche]] [[soon|pronto]].',
          correctAnswer: 'is',
          acceptableAnswers: ['is'],
          explanation: '[[He|Él]] + [[is going to|va a]] + [[infinitive|infinitivo]].',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w6',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[I|Yo]] [[am going to|voy a]] [[visit|visitar]] [[my|mi]] [[family|familia]] [[next week|la próxima semana]].',
      words: ['[[I|Yo]]', '[[am going to|voy a]]', '[[visit|visitar]]', '[[my|mi]]', '[[family|familia]]', '[[next week|la próxima semana]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w7',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[She|Ella]] [[is going to|va a]] [[study|estudiar]] [[English|inglés]] [[next year|el próximo año]].',
      words: ['[[She|Ella]]', '[[is going to|va a]]', '[[study|estudiar]]', '[[English|inglés]]', '[[next year|el próximo año]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w8',
    type: 'sentence-building',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras.',
      correctSentence: '[[They|Ellos]] [[are going to|van a]] [[travel|viajar]] [[to|a]] [[Spain|España]] [[in August|en agosto]].',
      words: ['[[They|Ellos]]', '[[are going to|van a]]', '[[travel|viajar]]', '[[to|a]]', '[[Spain|España]]', '[[in August|en agosto]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w9',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2-3 frases sobre tus planes para las próximas vacaciones. Usa "[[I am going to|Voy a]]".',
      prompt: '[[I am going to|Voy a]] ____. [[I am going to|Voy a]] ____.',
      modelExample: '[[I am going to|Voy a]] [[travel|viajar]] [[to|a]] [[the|la]] [[beach|playa]]. [[I am going to|Voy a]] [[visit|visitar]] [[my|mi]] [[family|familia]] [[and|y]] [[relax|relajarme]].',
      minWords: 15,
      maxWords: 40,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w10',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2 frases sobre lo que vas a estudiar o aprender. Usa "[[I am going to|Voy a]] [[study|estudiar]]".',
      prompt: '[[I am going to study|Voy a estudiar]] ____.',
      modelExample: '[[I am going to|Voy a]] [[study|estudiar]] [[English|inglés]] [[next year|el próximo año]]. [[I am going to|Voy a]] [[learn|aprender]] [[to|a]] [[drive|conducir]] [[soon|pronto]].',
      minWords: 10,
      maxWords: 25,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w11',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe algo que vas a hacer este fin de semana. Usa "[[I am going to|Voy a]]".',
      prompt: '[[I am going to|Voy a]] ____ [[this weekend|este fin de semana]].',
      modelExample: '[[I am going to|Voy a]] [[visit|visitar]] [[my|mis]] [[friends|amigos]] [[this weekend|este fin de semana]]. [[I am going to|Voy a]] [[watch|ver]] [[a|una]] [[film|película]] [[with|con]] [[them|ellos]].',
      minWords: 10,
      maxWords: 25,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w12',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo breve (4-5 frases) sobre tus planes para el próximo año. Incluye: viajes, estudios o trabajo, algo que vas a comprar.',
      prompt: '[[Write about your plans for next year|Escribe sobre tus planes para el próximo año]].',
      modelExample: '[[I am going to|Voy a]] [[finish|terminar]] [[university|universidad]] [[next year|el próximo año]]. [[I am going to|Voy a]] [[look for|buscar]] [[a|un]] [[job|trabajo]] [[in|en]] [[Madrid|Madrid]]. [[I am going to|Voy a]] [[travel|viajar]] [[to|a]] [[Italy|Italia]] [[in|en]] [[summer|verano]]. [[I am going to|Voy a]] [[buy|comprar]] [[a|un]] [[new|nuevo]] [[laptop|portátil]] [[soon|pronto]].',
      minWords: 35,
      maxWords: 80,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w13',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde: ¿Qué vas a hacer este verano? 3-4 frases.',
      prompt: '[[What are you going to do this summer?|¿Qué vas a hacer este verano?]]',
      modelExample: '[[I am going to|Voy a]] [[travel|viajar]] [[to|a]] [[the|la]] [[beach|playa]] [[with|con]] [[my|mi]] [[family|familia]]. [[I am going to|Voy a]] [[learn|aprender]] [[to|a]] [[swim|nadar]] [[better|mejor]]. [[I am going to|Voy a]] [[read|leer]] [[some|algunos]] [[books|libros]] [[and|y]] [[relax|relajarme]].',
      minWords: 25,
      maxWords: 60,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w14',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe sobre un lugar que vas a visitar pronto. 2-3 frases.',
      prompt: '[[What place are you going to visit soon?|¿Qué lugar vas a visitar pronto?]]',
      modelExample: '[[I am going to|Voy a]] [[visit|visitar]] [[Barcelona|Barcelona]] [[next month|el próximo mes]]. [[I am going to|Voy a]] [[see|ver]] [[the|la]] [[Sagrada Familia|Sagrada Familia]] [[and|y]] [[the|la]] [[beach|playa]].',
      minWords: 15,
      maxWords: 45,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u21-l6-w15',
    type: 'writing',
    level: 'A2',
    topic: 'Going to',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un texto breve (4-6 frases) sobre tus planes: viajes, estudios, trabajo, cosas que vas a comprar. Usa [[going to|voy a]].',
      prompt: '[[Write about your plans|Escribe sobre tus planes]]: [[travel|viajes]], [[study|estudios]], [[work|trabajo]].',
      modelExample: '[[I am going to|Voy a]] [[travel|viajar]] [[to|a]] [[Japan|Japón]] [[next summer|el próximo verano]]. [[I am going to|Voy a]] [[study|estudiar]] [[English|inglés]] [[next year|el próximo año]]. [[I am going to|Voy a]] [[look for|buscar]] [[a|un]] [[new|nuevo]] [[job|trabajo]] [[soon|pronto]]. [[I am going to|Voy a]] [[buy|comprar]] [[a|un]] [[new|nuevo]] [[car|coche]] [[when|cuando]] [[I|yo]] [[save|ahorre]] [[enough|suficiente]] [[money|dinero]].',
      minWords: 40,
      maxWords: 90,
    },
    topicName: 'Writing',
  },
];
