/**
 * Unidad 47 — Lección 5: Expresión oral (Superlatives: The best in the world)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_47_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a2-u47-l5-s1', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: "[[Mount Everest|El Monte Everest]] [[is|es]] [[the|la]] [[highest|más alta]] [[mountain|montaña]] [[in|en]] [[the world|el mundo]].", expectedResponse: 'Mount Everest is the highest mountain in the world.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s2', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[The Nile|El Nilo]] [[is|es]] [[the|el]] [[longest|más largo]] [[river|río]] [[in|en]] [[the world|el mundo]].", expectedResponse: 'The Nile is the longest river in the world.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s3', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[Tokyo|Tokio]] [[is|es]] [[the|la]] [[most|más]] [[expensive|cara]] [[city|ciudad]] [[to|para]] [[live|vivir]] [[in|en]].", expectedResponse: 'Tokyo is the most expensive city to live in.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s4', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[Russia|Rusia]] [[is|es]] [[the|el]] [[largest|más grande]] [[country|país]] [[in|en]] [[the world|el mundo]].", expectedResponse: 'Russia is the largest country in the world.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s5', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: "[[She|Ella]] [[is|es]] [[the|la]] [[best|mejor]] [[student|estudiante]] [[in|en]] [[the class|la clase]].", expectedResponse: 'She is the best student in the class.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s6', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[That|Esa]] [[was|fue]] [[the|la]] [[worst|peor]] [[film|película]] [[I|yo]] [[have|he]] [[ever|nunca]] [[seen|visto]].", expectedResponse: 'That was the worst film I have ever seen.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s7', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[This|Este]] [[is|es]] [[the|el]] [[biggest|más grande]] [[hotel|hotel]] [[in|en]] [[town|la ciudad]].", expectedResponse: 'This is the biggest hotel in town.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s8', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[He|Él]] [[is|es]] [[the|el]] [[most|más]] [[interesting|interesante]] [[person|persona]] [[I|yo]] [[know|conozco]].", expectedResponse: 'He is the most interesting person I know.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s9', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[This|Este]] [[is|es]] [[the|el]] [[cheapest|más barato]] [[restaurant|restaurante]] [[in|en]] [[the city|la ciudad]].", expectedResponse: 'This is the cheapest restaurant in the city.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s10', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[December|Diciembre]] [[is|es]] [[the|el]] [[coldest|más frío]] [[month|mes]] [[of|del]] [[the year|año]].", expectedResponse: 'December is the coldest month of the year.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s11', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[The Pacific|El Pacífico]] [[is|es]] [[the|el]] [[deepest|más profundo]] [[ocean|océano]] [[in|en]] [[the world|el mundo]].", expectedResponse: 'The Pacific is the deepest ocean in the world.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s12', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[This|Este]] [[is|es]] [[the|el]] [[most popular|más popular]] [[place|lugar]] [[to|para]] [[visit|visitar]] [[in|en]] [[Europe|Europa]].", expectedResponse: 'This is the most popular place to visit in Europe.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s13', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[She|Ella]] [[is|es]] [[the|la]] [[most famous|más famosa]] [[actress|actriz]] [[in|en]] [[the country|el país]].", expectedResponse: 'She is the most famous actress in the country.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s14', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[This|Esta]] [[is|es]] [[the|la]] [[most beautiful|más bonita]] [[beach|playa]] [[I|yo]] [[have|he]] [[ever|nunca]] [[seen|visto]].", expectedResponse: 'This is the most beautiful beach I have ever seen.' }, topicName: 'Speaking' },
  { id: 'a2-u47-l5-s15', type: 'pronunciation', level: 'A2', topic: 'Superlatives', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[Short|Adjetivos cortos]] [[adjectives|adjetivos]] [[add|añaden]] [[-est|est]]. [[Long|Adjetivos largos]] [[use|usan]] [[the most|el más]].", expectedResponse: 'Short adjectives add -est. Long adjectives use the most.' }, topicName: 'Speaking' },
];
