/**
 * Unidad 18 — Lección 6: Expresión escrita (For & Since, time periods)
 * 15 ejercicios: 5 fill-blank + 10 writing
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_18_LESSON_6_WRITING: Exercise[] = [
  {
    id: 'a2-u18-l6-w1',
    type: 'fill-blank',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase con for o since. Escribe tu respuesta.',
      questions: [
        {
          question: '[[I|Yo]] [[have|he]] [[lived|vivido]] ____ [[five years|cinco años]].',
          correctAnswer: 'for',
          acceptableAnswers: ['for'],
          explanation: '[[For|Durante]] + [[duration|duración]] ([[five years|cinco años]]).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w2',
    type: 'fill-blank',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que complete la frase.',
      questions: [
        {
          question: '[[She|Ella]] [[has|ha]] [[worked|trabajado]] ____ [[2020|2020]].',
          correctAnswer: 'since',
          acceptableAnswers: ['since'],
          explanation: '[[Since|Desde]] + [[starting point|punto de inicio]] ([[2020|2020]]).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w3',
    type: 'fill-blank',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa con for o since.',
      questions: [
        {
          question: '[[We|Nosotros]] [[have|hemos]] [[known|conocido]] [[each other|el uno al otro]] ____ [[ten years|diez años]].',
          correctAnswer: 'for',
          acceptableAnswers: ['for'],
          explanation: '[[For|Durante]] + [[duration|duración]] ([[ten years|diez años]]).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w4',
    type: 'fill-blank',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          question: '[[He|Él]] [[has|ha]] [[been|estado]] [[ill|enfermo]] ____ [[last Monday|el lunes pasado]].',
          correctAnswer: 'since',
          acceptableAnswers: ['since'],
          explanation: '[[Since|Desde]] + [[starting point|punto de inicio]] ([[last Monday|el lunes pasado]]).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w5',
    type: 'fill-blank',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Completa la frase.',
      questions: [
        {
          question: '[[I|Yo]] [[have|he]] [[been|estado]] [[learning|aprendiendo]] [[English|inglés]] ____ [[six months|seis meses]].',
          correctAnswer: 'for',
          acceptableAnswers: ['for'],
          explanation: '[[For|Durante]] + [[duration|duración]] ([[six months|seis meses]]).',
        },
      ],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w6',
    type: 'sentence-building',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[I|Yo]] [[have|he]] [[lived|vivido]] [[here|aquí]] [[for|durante]] [[five years|cinco años]].',
      words: ['[[I|Yo]]', '[[have|he]]', '[[lived|vivido]]', '[[here|aquí]]', '[[for|durante]]', '[[five years|cinco años]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w7',
    type: 'sentence-building',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras para formar una oración correcta.',
      correctSentence: '[[She|Ella]] [[has|ha]] [[worked|trabajado]] [[there|allí]] [[since|desde]] [[2020|2020]].',
      words: ['[[She|Ella]]', '[[has|ha]]', '[[worked|trabajado]]', '[[there|allí]]', '[[since|desde]]', '[[2020|2020]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w8',
    type: 'sentence-building',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Ordena las palabras.',
      correctSentence: '[[We|Nosotros]] [[have|hemos]] [[known|conocido]] [[each other|el uno al otro]] [[for|durante]] [[ten years|diez años]].',
      words: ['[[We|Nosotros]]', '[[have|hemos]]', '[[known|conocido]]', '[[each other|el uno al otro]]', '[[for|durante]]', '[[ten years|diez años]].'],
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w9',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe dos frases sobre lo que has hecho durante mucho tiempo. Usa "for" y "since".',
      prompt: '[[I|Yo]] ____ [[for|durante]] ____. [[I|Yo]] ____ [[since|desde]] ____.',
      modelExample: '[[I|Yo]] [[have|he]] [[lived|vivido]] [[here|aquí]] [[for|durante]] [[five years|cinco años]]. [[I|Yo]] [[have|he]] [[worked|trabajado]] [[here|aquí]] [[since|desde]] [[2020|2020]].',
      minWords: 15,
      maxWords: 35,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w10',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe una frase con "I have lived ... for ...".',
      prompt: '[[I|Yo]] ____.',
      modelExample: '[[I|Yo]] [[have|he]] [[lived|vivido]] [[in|en]] [[this|esta]] [[city|ciudad]] [[for|durante]] [[three years|tres años]].',
      minWords: 8,
      maxWords: 20,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w11',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe una frase con "I have known ... since ...".',
      prompt: '[[I|Yo]] ____.',
      modelExample: '[[I|Yo]] [[have|he]] [[known|conocido]] [[my|mi]] [[friend|amigo]] [[since|desde]] [[2020|2020]].',
      minWords: 8,
      maxWords: 20,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w12',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 2-3 frases sobre tu vida. Usa for y since para hablar de períodos.',
      prompt: '[[My|Mi]] [[life|vida]] ____.',
      modelExample: '[[I|Yo]] [[have|he]] [[lived|vivido]] [[here|aquí]] [[for|durante]] [[two years|dos años]]. [[I|Yo]] [[have|he]] [[worked|trabajado]] [[at|en]] [[this|esta]] [[company|empresa]] [[since|desde]] [[last|el]] [[year|año]].',
      minWords: 20,
      maxWords: 50,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w13',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo breve (4-5 frases) sobre tu vida. Incluye: dónde vives, trabajo/estudios, amigos. Usa for y since.',
      prompt: '[[Describe your life|Describe tu vida]].',
      modelExample: '[[I|Yo]] [[have|he]] [[lived|vivido]] [[in|en]] [[Madrid|Madrid]] [[for|durante]] [[five years|cinco años]]. [[I|Yo]] [[have|he]] [[worked|trabajado]] [[as|como]] [[a|un]] [[teacher|profesor]] [[since|desde]] [[2020|2020]]. [[I|Yo]] [[have|he]] [[known|conocido]] [[my|mi]] [[best|mejor]] [[friend|amiga]] [[for|durante]] [[ten years|diez años]]. [[I|Yo]] [[feel|me siento]] [[happy|feliz]] [[because|porque]] [[I|yo]] [[have|tengo]] [[a|una]] [[good|buena]] [[life|vida]].',
      minWords: 45,
      maxWords: 100,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w14',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe 4-5 frases sobre tus estudios o trabajo. Usa for y since.',
      prompt: '[[My|Mi]] [[work|trabajo]] [[or|o]] [[studies|estudios]] ____.',
      modelExample: '[[I|Yo]] [[have|he]] [[studied|estudiado]] [[English|inglés]] [[for|durante]] [[two years|dos años]]. [[I|Yo]] [[have|he]] [[been|estado]] [[at|en]] [[this|esta]] [[school|escuela]] [[since|desde]] [[September|septiembre]]. [[I|Yo]] [[have|he]] [[learned|aprendido]] [[a|mucho]] [[lot|mucho]] [[since|desde]] [[then|entonces]].',
      minWords: 35,
      maxWords: 80,
    },
    topicName: 'Writing',
  },
  {
    id: 'a2-u18-l6-w15',
    type: 'writing',
    level: 'A2',
    topic: 'For Since',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escribe un párrafo (4-6 frases) sobre una persona que describe su vida. Usa for y since para todos los períodos.',
      prompt: '[[Write about someone\'s life|Escribe sobre la vida de alguien]].',
      modelExample: '[[My|Mi]] [[friend|amiga]] [[Emma|Emma]] [[has|ha]] [[lived|vivido]] [[in|en]] [[London|Londres]] [[for|durante]] [[five years|cinco años]]. [[She|Ella]] [[has|ha]] [[worked|trabajado]] [[at|en]] [[the|la]] [[same|misma]] [[company|empresa]] [[since|desde]] [[2020|2020]]. [[She|Ella]] [[has|ha]] [[known|conocido]] [[her|su]] [[best|mejor]] [[friend|amiga]] [[for|durante]] [[ten years|diez años]]. [[She|Ella]] [[has|ha]] [[been|estado]] [[learning|aprendiendo]] [[Spanish|español]] [[for|durante]] [[six months|seis meses]]. [[She|Ella]] [[feels|se siente]] [[good|bien]] [[because|porque]] [[she|ella]] [[has|tiene]] [[a|una]] [[stable|estable]] [[life|vida]].',
      minWords: 55,
      maxWords: 130,
    },
    topicName: 'Writing',
  },
];
