/**
 * Unidad 56 — Lección 5: Expresión oral (Adverbs of Manner)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_56_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'a2-u56-l5-s1', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She runs very quickly|Ella corre muy rápidamente]].', expectedResponse: 'She runs very quickly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s2', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He speaks English very well|Él habla inglés muy bien]].', expectedResponse: 'He speaks English very well.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s3', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Please walk quietly in the library|Por favor camina en silencio en la biblioteca]].', expectedResponse: 'Please walk quietly in the library.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s4', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He drove carefully through the rain|Él condujo con cuidado bajo la lluvia]].', expectedResponse: 'He drove carefully through the rain.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s5', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[They laughed loudly at the joke|Ellos rieron fuerte con el chiste]].', expectedResponse: 'They laughed loudly at the joke.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s6', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[She smiled happily at him|Ella sonrió felizmente hacia él]].', expectedResponse: 'She smiled happily at him.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s7', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[The teacher explained the lesson clearly|El profesor explicó la lección claramente]].', expectedResponse: 'The teacher explained the lesson clearly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s8', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[How|Cómo]] [[do|conduces]] [[you|tú]] [[drive|conducir]]? [[Quickly|Rápido]] [[or|o]] [[carefully|con cuidado]]?', expectedResponse: 'I drive carefully. / I drive quickly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s9', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[Do|¿]] [[you|tú]] [[speak|hablas]] [[English|inglés]] [[well|bien]]?', expectedResponse: 'Yes, I speak English well. / I speak it quite well.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s10', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Responde la pregunta en voz alta.', targetText: '[[How|Cómo]] [[do|trabajas]] [[you|tú]] [[work|trabajar]]? [[Quickly|Rápido]] [[or|o]] [[slowly|despacio]]?', expectedResponse: 'I work quickly. / I work slowly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s11', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta una frase sobre cómo haces algo (trabajar, estudiar, conducir). Usa un adverbio de modo.', targetText: '[[I|Yo]] ____ ____. ([[work|trabajo]]/[[study|estudio]]/[[drive|conduzco]] + [[adverb|adverbio]])', expectedResponse: 'I work carefully. / I study hard. / I drive slowly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s12', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: "[[I|Yo]] [[finished|terminé]] [[my|mi]] [[homework|deberes]] ____." (usa quickly, slowly o carefully)', targetText: '[[I finished my homework|Terminé mis deberes]] ____.', expectedResponse: 'I finished my homework quickly/slowly/carefully.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s13', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta una frase con "well" o "badly".', targetText: '[[I|Yo]] ____ ____. ([[sing|canto]]/[[dance|bailo]]/[[cook|cocino]] + [[well|bien]]/[[badly|mal]])', expectedResponse: 'I sing well. / I cook badly.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s14', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: "[[Please|Por favor]] ____" (speak slowly, walk quietly, drive carefully)', targetText: '[[Please|Por favor]] ____.', expectedResponse: 'Please speak slowly. / Please walk quietly. / Please drive carefully.' }, topicName: 'Speaking' },
  { id: 'a2-u56-l5-s15', type: 'pronunciation', level: 'A2', topic: 'Adverbs of Manner', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Describe en 2-3 frases cómo haces una actividad (estudiar, trabajar, cocinar). Usa adverbios de modo.', targetText: '[[I|Yo]] ____ ____. [[I|Yo]] ____ ____ ____.', expectedResponse: 'I study carefully. I work hard. I cook slowly.' }, topicName: 'Speaking' },
];
