/**
 * Unidad 14 — Lección 5: Expresión oral (Just, acciones recientes)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_14_LESSON_5_SPEAKING: Exercise[] = [
  {
    id: 'a2-u14-l5-s1',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha la frase y repítela en voz alta.',
      targetText: '[[I|Yo]] [[have|he]] [[just|acabar de]] [[arrived|llegado]] [[home|casa]].',
      expectedResponse: 'I have just arrived home.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s2',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[She|Ella]] [[has|ha]] [[just|acabar de]] [[finished|terminado]] [[her|su]] [[lunch|comida]].',
      expectedResponse: 'She has just finished her lunch.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s3',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[I|Yo]] [[have|he]] [[just|acabar de]] [[received|recibido]] [[your|tu]] [[message|mensaje]].',
      expectedResponse: 'I have just received your message.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s4',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Escucha y repite en voz alta.',
      targetText: '[[He|Él]] [[has|ha]] [[just|acabar de]] [[woken up|despertado]].',
      expectedResponse: 'He has just woken up.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s5',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase de abajo en voz alta.',
      targetText: '[[We|Nosotros]] [[have|hemos]] [[just|acabar de]] [[heard|oído]] [[the|las]] [[news|noticias]].',
      expectedResponse: 'We have just heard the news.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s6',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase en voz alta.',
      targetText: '[[I|Yo]] [[have|he]] [[just|acabar de]] [[left|salido]] [[the|la]] [[office|oficina]].',
      expectedResponse: 'I have just left the office.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s7',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Lee la frase en voz alta.',
      targetText: '[[They|Ellos]] [[have|han]] [[just|acabar de]] [[arrived|llegado]] [[at|en]] [[the|el]] [[airport|aeropuerto]].',
      expectedResponse: 'They have just arrived at the airport.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s8',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde la pregunta en voz alta. Ejemplo: "[[Yes|Sí]], [[I|yo]] [[have|he]] [[just|acabar de]] [[arrived|llegado]]."',
      targetText: '[[Have|Has]] [[you|tú]] [[just|acabar de]] [[arrived|llegado]]?',
      expectedResponse: 'Yes, I have just arrived. / No, I arrived earlier.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s9',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde la pregunta en voz alta.',
      targetText: '[[What|Qué]] [[have|has]] [[you|tú]] [[just|acabar de]] [[done|hecho]]?',
      expectedResponse: 'I have just [arrived/finished/received/...].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s10',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Responde la pregunta en voz alta.',
      targetText: '[[Has|Ha]] [[she|ella]] [[just|acabar de]] [[finished|terminado]] [[her|su]] [[work|trabajo]]?',
      expectedResponse: 'Yes, she has just finished. / No, she hasn\'t yet.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s11',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta algo que acabas de hacer. Modelo: "[[I have just|Acabo de]] ..."',
      targetText: '[[I have just|Acabo de]] ____.',
      expectedResponse: 'I have just [woken up/arrived/finished/...].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s12',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta dos acciones recientes que tú o alguien acaba de hacer. Usa "just".',
      targetText: '[[I have just|Acabo de]] ____. [[He/She has just|Él/Ella acaba de]] ____.',
      expectedResponse: 'I have just [X]. He/She has just [Y].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s13',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta que acabas de recibir un mensaje o una llamada.',
      targetText: '[[I have just|Acabo de]] ____ [[a|un]] ____.',
      expectedResponse: 'I have just received a message/call.',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s14',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Di en voz alta que acabas de llegar a un lugar. Cambia el lugar según tu situación.',
      targetText: '[[I have just|Acabo de]] [[arrived|llegado]] ____.',
      expectedResponse: 'I have just arrived [home/at work/at the station/...].',
    },
    topicName: 'Speaking',
  },
  {
    id: 'a2-u14-l5-s15',
    type: 'pronunciation',
    level: 'A2',
    topic: 'Present Perfect Just',
    difficulty: 'easy',
    content: {
      title: LESSON_TITLE,
      instructions: 'Haz una breve presentación en 4 o 5 frases sobre lo que acabas de hacer. Incluye: 3-4 acciones recientes con "just".',
      targetText: '[[I have just|Acabo de]] ____. [[I have just|Acabo de]] ____. [[I|Yo]] ____.',
      expectedResponse: 'I have just [woken up]. I have just [had breakfast]. I have just [received a message]. I am [ready to...].',
    },
    topicName: 'Speaking',
  },
];
