/**
 * Unidad 19 B2 — Lección 1: Gramática (Comparative & Superlative advanced) & Sport
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Comparative & Superlative (advanced)|Comparativo y superlativo (avanzado)]]';
const INSTRUCTIONS = 'Elige la forma correcta del comparativo o superlativo según el contexto.';

export const UNIT_19_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u19-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '____ [[more|más]] [[you practise|practiques]], ____ [[better|mejor]] [[you become|te vuelves]].', options: ['[[The / the|Cuanto más... más]]', '[[More / more|Más... más]]', '[[The most / the most|Lo más... lo más]]'], correctAnswer: 'The / the', acceptableAnswers: ['The / the'], explanation: '[[The more... the more|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She runs|Ella corre]] ____ [[faster|más rápido]] [[than she did last year|que el año pasado]].', options: ['[[far|mucho]]', '[[more|más]]', '[[the most|el más]]'], correctAnswer: 0, explanation: '[[Far/much + comparative|Far/much + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This is|Es]] ____ [[the best|el mejor]] [[result we\'ve ever had|resultado que hemos tenido]].', options: ['[[by far|con diferencia]]', '[[far|mucho]]', '[[more|más]]'], correctAnswer: 'by far', acceptableAnswers: ['by far'], explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ____ we get|Cuanto más envejecemos]], [[the ____ we learn|más aprendemos]].', options: ['[[older / more|más viejos / más]]', '[[old / much|viejos / mucho]]', '[[oldest / most|más viejos / más]]'], correctAnswer: 0, explanation: '[[The + comparative... the + comparative|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This laptop is|Este portátil es]] ____ [[more expensive|más caro]] [[than the previous model|que el modelo anterior]].', options: ['[[much|mucho]]', '[[more|más]]', '[[the most|el más]]'], correctAnswer: 'much', acceptableAnswers: ['much', 'far'], explanation: '[[Much/far + comparative|Much/far + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He\'s|Es]] ____ [[the most talented|el más talentoso]] [[player in the team|jugador del equipo]].', options: ['[[by far|con diferencia]]', '[[far|mucho]]', '[[more|más]]'], correctAnswer: 0, explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '____ [[harder|más duro]] [[you work|trabajes]], ____ [[better|mejor]] [[your results|tus resultados]].', options: ['[[The / the|Cuanto más... más]]', '[[More / more|Más... más]]', '[[Harder / better|Más duro... mejor]]'], correctAnswer: 'The / the', acceptableAnswers: ['The / the'], explanation: '[[The more... the more|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She\'s|Es]] ____ [[more confident|más segura]] [[than she used to be|que solía ser]].', options: ['[[a lot|mucho]]', '[[more|más]]', '[[the most|la más]]'], correctAnswer: 0, explanation: '[[A lot + comparative|A lot + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This is|Es]] ____ [[the most difficult|el más difícil]] [[exam I\'ve ever taken|examen que he hecho]].', options: ['[[by far|con diferencia]]', '[[far|mucho]]', '[[more|más]]'], correctAnswer: 'by far', acceptableAnswers: ['by far'], explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ____ we waited|Cuanto más esperamos]], [[the ____ anxious we became|más ansiosos nos volvimos]].', options: ['[[longer / more|más tiempo / más]]', '[[long / much|tiempo / mucho]]', '[[longest / most|más tiempo / más]]'], correctAnswer: 0, explanation: '[[The + comparative... the + comparative|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The new version is|La nueva versión es]] ____ [[slightly better|ligeramente mejor]] [[than the old one|que la antigua]].', options: ['[[slightly|ligeramente]]', '[[more|más]]', '[[the most|la más]]'], correctAnswer: 'slightly', acceptableAnswers: ['slightly'], explanation: '[[Slightly + comparative|Slightly + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She\'s|Es]] ____ [[the fastest|la más rápida]] [[runner in the school|corredora del colegio]].', options: ['[[easily|fácilmente]]', '[[easy|fácil]]', '[[more|más]]'], correctAnswer: 0, explanation: '[[Easily + superlative|Easily + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '____ [[earlier|más temprano]] [[you start|empieces]], ____ [[sooner|antes]] [[you finish|terminas]].', options: ['[[The / the|Cuanto más... más]]', '[[More / more|Más... más]]', '[[Earlier / sooner|Más temprano... antes]]'], correctAnswer: 'The / the', acceptableAnswers: ['The / the'], explanation: '[[The more... the more|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This is|Es]] ____ [[the best|el mejor]] [[performance I\'ve seen|actuación que he visto]].', options: ['[[by far|con diferencia]]', '[[far|mucho]]', '[[more|más]]'], correctAnswer: 0, explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The results are|Los resultados son]] ____ [[worse|peores]] [[than we expected|de lo que esperábamos]].', options: ['[[much|mucho]]', '[[more|más]]', '[[the most|el más]]'], correctAnswer: 'much', acceptableAnswers: ['much', 'far'], explanation: '[[Much/far + comparative|Much/far + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He\'s|Es]] ____ [[the most experienced|el más experimentado]] [[candidate in the pool|candidato del grupo]].', options: ['[[by far|con diferencia]]', '[[far|mucho]]', '[[more|más]]'], correctAnswer: 0, explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The second attempt was|El segundo intento fue]] ____ [[a bit better|un poco mejor]] [[than the first|que el primero]].', options: ['[[a bit|un poco]]', '[[more|más]]', '[[the most|el más]]'], correctAnswer: 'a bit', acceptableAnswers: ['a bit', 'slightly'], explanation: '[[A bit/slightly + comparative|A bit/slightly + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u19-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Comparative & Superlative', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ____ we invest|Cuanto más invertimos]], [[the ____ we earn|más ganamos]].', options: ['[[more / more|más / más]]', '[[much / much|mucho / mucho]]', '[[most / most|más / más]]'], correctAnswer: 0, explanation: '[[The more... the more|Cuanto más... más]].' }] }, topicName: 'Grammar' },
];
