/**
 * Unidad 23 B2 — Lección 4: Comprensión auditiva (Communication)
 * 13 preguntas (B2: recreado con transcripción y preguntas reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hi|Hola]], [[I'm|soy]] [[Emma|Emma]] [[and|y]] [[I work|trabajo]] [[as|como]] [[a project manager|gerente de proyectos]]. [[Last month|El mes pasado]] [[we were about to|estábamos a punto de]] [[launch|lanzar]] [[our new product|nuestro nuevo producto]] [[when|cuando]] [[the system|el sistema]] [[broke down|se averió]]. [[It was|Fue]] [[a disaster|un desastre]] [[because|porque]] [[we had|teníamos]] [[invested|invertido]] [[months|meses]] [[of work|de trabajo]]. [[I brought up|Mencioné]] [[the problem|el problema]] [[at the meeting|en la reunión]] [[and|y]] [[suggested|sugerí]] [[bringing in|traer]] [[an IT specialist|un especialista en informática]]. [[My boss|Mi jefe]] [[had been|había sido]] [[brought up|criado]] [[in|en]] [[a very traditional company|una empresa muy tradicional]] [[and|y]] [[at first|al principio]] [[he didn't want|no quería]] [[to change|cambiar]] [[things|las cosas]]. [[However|Sin embargo]], [[he agreed|acordó]] [[and|y]] [[the expert|el experto]] [[brought about|causó]] [[a complete solution|una solución completa]] [[within|en]] [[a week|una semana]]. [[The communication|La comunicación]] [[between|entre]] [[our team|nuestro equipo]] [[and|y]] [[the IT department|el departamento de informática]] [[had broken down|había fracasado]] [[before|antes]], [[but|pero]] [[now|ahora]] [[we|nosotros]] [[work|trabajamos]] [[much better together|mucho mejor juntos]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Emma, a project manager|Emma, gerente de proyectos]]', '[[An IT specialist|Una especialista en informática]]', '[[A traditional boss|Un jefe tradicional]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Emma and I work as a project manager|soy Emma y trabajo como gerente de proyectos]]".' },
  { question: '[[What|Qué]] [[was about to happen|estaba a punto de pasar]] [[when|cuando]] [[the problem occurred|ocurrió el problema]]?', options: ['[[They were about to launch the new product|Estaban a punto de lanzar el nuevo producto]]', '[[They were about to hire an IT specialist|Estaban a punto de contratar un especialista en informática]]', '[[They were about to have a meeting|Estaban a punto de tener una reunión]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[we were about to launch our new product when the system broke down|estábamos a punto de lanzar nuestro nuevo producto cuando el sistema se averió]]".' },
  { question: '[[What|Qué]] [[broke down|se averió]]?', options: ['[[The system|El sistema]]', '[[The meeting|La reunión]]', '[[The product|El producto]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[the system broke down|el sistema se averió]]".' },
  { question: '[[What|Qué]] [[did Emma bring up|mencionó Emma]] [[at the meeting|en la reunión]]?', options: ['[[The problem and suggested bringing in an IT specialist|El problema y sugirió traer un especialista en informática]]', '[[A new product idea|Una idea de nuevo producto]]', '[[A traditional approach|Un enfoque tradicional]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I brought up the problem at the meeting and suggested bringing in an IT specialist|mencioné el problema en la reunión y sugerí traer un especialista en informática]]".' },
  { question: '[[Why|Por qué]] [[was the boss initially reluctant|el jefe fue inicialmente reacio]]?', options: ['[[He had been brought up in a very traditional company|Había sido criado en una empresa muy tradicional]]', '[[He didn\'t like Emma|No le gustaba Emma]]', '[[He didn\'t have the budget|No tenía el presupuesto]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[My boss had been brought up in a very traditional company and at first he didn\'t want to change things|mi jefe había sido criado en una empresa muy tradicional y al principio no quería cambiar las cosas]]".' },
  { question: '[[What|Qué]] [[did the expert bring about|causó el experto]]?', options: ['[[A complete solution within a week|Una solución completa en una semana]]', '[[More problems|Más problemas]]', '[[A breakdown in communication|Un fracaso en la comunicación]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[the expert brought about a complete solution within a week|el experto causó una solución completa en una semana]]".' },
  { question: '[[What|Qué]] [[had happened|había pasado]] [[to communication|con la comunicación]] [[before|antes]]?', options: ['[[It had broken down between the team and IT|Había fracasado entre el equipo y el departamento de informática]]', '[[It had improved|Había mejorado]]', '[[It had never been a problem|Nunca había sido un problema]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[The communication between our team and the IT department had broken down before|la comunicación entre nuestro equipo y el departamento de informática había fracasado antes]]".' },
  { question: '[[The product|El producto]] [[was launched successfully|fue lanzado con éxito]] [[before|antes de]] [[the system broke down|el sistema se averió]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The system broke down|El sistema se averió]] [[before|antes de]] [[the launch|el lanzamiento]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the listening|de la escucha]]?', options: ['[[A project problem was solved by bringing in expertise and improving communication|Un problema de proyecto se resolvió trayendo experiencia y mejorando la comunicación]]', '[[IT specialists are always needed|Siempre se necesitan especialistas en informática]]', '[[Traditional companies never change|Las empresas tradicionales nunca cambian]]'], correctAnswer: 0, explanation: '[[The speaker|El hablante]] [[describes|describe]] [[how| cómo]] [[a problem was solved|un problema se resolvió]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[with "break"|con "break"]] [[is used|se usa]] [[for the system|para el sistema]]?', options: ['[[Broke down|Broke down]]', '[[Broke in|Broke in]]', '[[Broke out|Broke out]]'], correctAnswer: 0, explanation: '[[Broke down|Broke down]] [[= stop working|= dejar de funcionar]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[project|proyecto]], [[system|sistema]], [[communication|comunicación]], [[solution|solución]]', '[[salary|salario]], [[budget|presupuesto]], [[profit|beneficio]]', '[[airport|aeropuerto]], [[flight|vuelo]], [[luggage|equipaje]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[project and communication vocabulary|vocabulario de proyecto y comunicación]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[Emma|Emma]]?', options: ['[[She is proactive and solves problems|Es proactiva y resuelve problemas]]', '[[She prefers not to speak up|Prefiere no hablar]]', '[[She doesn\'t like her boss|No le gusta su jefe]]'], correctAnswer: 0, explanation: '[[She brought up|Mencionó]] [[the problem|el problema]] [[and|y]] [[suggested|sugirió]] [[a solution|una solución]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[means|significa]] [["invite someone to help"|"invitar a alguien a ayudar"]]?', options: ['[[Bringing in|Bringing in]]', '[[Bringing up|Bringing up]]', '[[Bringing about|Bringing about]]'], correctAnswer: 0, explanation: '[[Bring in|Bring in]] [[= introduce someone to help|= traer a alguien para ayudar]].' },
];

export const UNIT_23_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u23-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Communication',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
