/**
 * Unidad 37 B2 — Lección 1: Gramática (Auxiliaries: emphasis, short answers)
 * 18 ejercicios (B2: auxiliares para énfasis y respuestas cortas) — Tema: Business (extended)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Auxiliaries (emphasis, short answers)|Auxiliares (énfasis, respuestas cortas)]]';
const INSTRUCTIONS = 'Elige la forma correcta del auxiliar para énfasis o respuesta corta.';

export const UNIT_37_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u37-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[want|quiero]] [[to attend|asistir]] [[the meeting|a la reunión]] — [[please|por favor]] [[confirm|confirma]].', options: ['[[do|sí]]', '[[am|estoy]]', '[[have|he]]'], correctAnswer: 'do', acceptableAnswers: ['do'], explanation: '[[Do for emphasis in affirmative|Do para énfasis en afirmativa]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Did they sign the contract|¿Firmaron el contrato]]? — [[Yes|Sí]], [[they|ellos]] ____.', options: ['[[did|sí]]', '[[signed|firmaron]]', '[[have|han]]'], correctAnswer: 0, explanation: '[[Short answer: same auxiliary as question|Respuesta corta: mismo auxiliar que la pregunta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[finish|terminó]] [[the report|el informe]] [[on time|a tiempo]] — [[I saw it|lo vi]].', options: ['[[did|sí]]', '[[has|ha]]', '[[is|está]]'], correctAnswer: 'did', acceptableAnswers: ['did'], explanation: '[[Did for emphasis in past|Did para énfasis en pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Have you submitted the proposal|¿Has enviado la propuesta]]? — [[No|No]], [[I|yo]] ____.', options: ['[[haven\'t|no]]', '[[didn\'t|no]]', '[[don\'t|no]]'], correctAnswer: 0, explanation: '[[Short answer: haven\'t (present perfect)|Respuesta corta: haven\'t (present perfect)]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[agree|está de acuerdo]] [[with the terms|con los términos]] — [[he told me|me lo dijo]].', options: ['[[does|sí]]', '[[is|está]]', '[[has|ha]]'], correctAnswer: 'does', acceptableAnswers: ['does'], explanation: '[[Does for emphasis (3rd person)|Does para énfasis (3ª persona)]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Are you attending the conference|¿Asistes a la conferencia]]? — [[Yes|Sí]], [[I|yo]] ____.', options: ['[[am|sí]]', '[[do|sí]]', '[[have|sí]]'], correctAnswer: 0, explanation: '[[Short answer: am (present continuous)|Respuesta corta: am (present continuous)]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[complete|completamos]] [[the project|el proyecto]] [[last week|la semana pasada]] — [[despite|a pesar de]] [[the delays|los retrasos]].', options: ['[[did|sí]]', '[[have|hemos]]', '[[are|estamos]]'], correctAnswer: 'did', acceptableAnswers: ['did'], explanation: '[[Did for emphasis in past|Did para énfasis en pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Will they approve the budget|¿Aprobarán el presupuesto]]? — [[Yes|Sí]], [[they|ellos]] ____.', options: ['[[will|sí]]', '[[do|sí]]', '[[are|sí]]'], correctAnswer: 0, explanation: '[[Short answer: will|Respuesta corta: will]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[like|me gusta]] [[the new strategy|la nueva estrategia]] — [[it\'s|es]] [[very effective|muy efectiva]].', options: ['[[do|sí]]', '[[am|estoy]]', '[[have|he]]'], correctAnswer: 'do', acceptableAnswers: ['do'], explanation: '[[Do for emphasis|Do para énfasis]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can you meet the deadline|¿Puedes cumplir el plazo]]? — [[Yes|Sí]], [[I|yo]] ____.', options: ['[[can|sí]]', '[[do|sí]]', '[[will|sí]]'], correctAnswer: 0, explanation: '[[Short answer: can|Respuesta corta: can]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[have|han]] [[finished|terminado]] [[the audit|la auditoría]] — [[I saw the report|vi el informe]].', options: ['[[have|sí]]', '[[did|sí]]', '[[do|sí]]'], correctAnswer: 'have', acceptableAnswers: ['have'], explanation: '[[Have for emphasis (present perfect)|Have para énfasis (present perfect)]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Do you work from home|¿Trabajas desde casa]]? — [[No|No]], [[I|yo]] ____.', options: ['[[don\'t|no]]', '[[am not|no]]', '[[haven\'t|no]]'], correctAnswer: 0, explanation: '[[Short answer: don\'t|Respuesta corta: don\'t]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[is|está]] [[coming|viniendo]] [[to the meeting|a la reunión]] — [[she confirmed|confirmó]].', options: ['[[is|sí]]', '[[does|sí]]', '[[has|sí]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[Be for emphasis (stress on is)|Be para énfasis]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Has the deal been closed|¿Se ha cerrado el trato]]? — [[Yes|Sí]], [[it|]] ____.', options: ['[[has|sí]]', '[[did|sí]]', '[[is|sí]]'], correctAnswer: 0, explanation: '[[Short answer: has (passive)|Respuesta corta: has]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[understand|entiendo]] [[your concerns|tus preocupaciones]] — [[let me explain|déjame explicar]].', options: ['[[do|sí]]', '[[am|estoy]]', '[[have|he]]'], correctAnswer: 'do', acceptableAnswers: ['do'], explanation: '[[Do for emphasis|Do para énfasis]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Were they at the presentation|¿Estuvieron en la presentación]]? — [[No|No]], [[they|ellos]] ____.', options: ['[[weren\'t|no]]', '[[didn\'t|no]]', '[[haven\'t|no]]'], correctAnswer: 0, explanation: '[[Short answer: weren\'t|Respuesta corta: weren\'t]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The team|El equipo]] ____ [[exceed|superó]] [[the target|el objetivo]] — [[despite|a pesar de]] [[the challenges|los desafíos]].', options: ['[[did|sí]]', '[[has|ha]]', '[[was|estaba]]'], correctAnswer: 'did', acceptableAnswers: ['did'], explanation: '[[Did for emphasis|Did para énfasis]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u37-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Business (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Should we proceed with the merger|¿Deberíamos proceder con la fusión]]? — [[Yes|Sí]], [[we|nosotros]] ____.', options: ['[[should|sí]]', '[[do|sí]]', '[[will|sí]]'], correctAnswer: 0, explanation: '[[Short answer: should|Respuesta corta: should]].' }] }, topicName: 'Grammar' },
];
