/**
 * Unidad 14 B2 — Lección 3: Comprensión lectora (Business)
 * 13 preguntas (B2: recreado con texto y preguntas distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Remote work|El trabajo remoto]] [[has changed|ha cambiado]] [[how companies operate|cómo operan las empresas]]. [[Before the pandemic|Antes de la pandemia]], [[many managers|muchos directivos]] [[must have believed|deben haber creído]] [[that productivity would drop|que la productividad caería]] [[if employees worked from home|si los empleados trabajaban desde casa]]. [[Yet studies show|Sin embargo los estudios muestran]] [[that output has often increased|que la producción a menudo ha aumentado]]. [[Some employees|Algunos empleados]] [[who struggled at first|que tuvieron dificultades al principio]] [[might have found|podrían haber encontrado]] [[it hard to separate work from life|difícil separar trabajo y vida]]; [[others|otros]] [[can't have imagined|no pueden haber imaginado]] [[going back to the office full-time|volver a la oficina a tiempo completo]]. [[Companies|Las empresas]] [[that adopted flexible policies|que adoptaron políticas flexibles]] [[have seen|han visto]] [[higher retention rates|tasas de retención más altas]]. [[The CEO|El director ejecutivo]] [[must have realised|debe haber comprendido]] [[that talent values flexibility|que el talento valora la flexibilidad]] [[when she announced|cuando anunció]] [[the permanent hybrid model|el modelo híbrido permanente]]. [[Investors|Los inversores]] [[who were sceptical|que eran escépticos]] [[might have worried|podrían haberse preocupado]] [[about costs|por los costes]], [[but|pero]] [[reduced office space|el espacio de oficina reducido]] [[has cut expenses|ha reducido gastos]] [[significantly|significativamente]].`;

const INSTRUCTIONS = 'Lee el texto sobre trabajo remoto y negocios. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[did many managers must have believed|deben haber creído muchos directivos]] [[before the pandemic|antes de la pandemia]]?', options: ['[[That productivity would drop if employees worked from home|Que la productividad caería si los empleados trabajaban desde casa]]', '[[That remote work would increase profits|Que el trabajo remoto aumentaría beneficios]]', '[[That offices would close forever|Que las oficinas cerrarían para siempre]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[many managers must have believed that productivity would drop|muchos directivos deben haber creído que la productividad caería]]".' },
  { question: '[[What|Qué]] [[do studies show|muestran los estudios]] [[about output|sobre la producción]]?', options: ['[[It has often increased|A menudo ha aumentado]]', '[[It has always decreased|Siempre ha disminuido]]', '[[It has stayed the same|Se ha mantenido igual]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[studies show that output has often increased|los estudios muestran que la producción a menudo ha aumentado]]".' },
  { question: '[[What|Qué]] [[might some employees have found hard|podrían haber encontrado difícil algunos empleados]]?', options: ['[[To separate work from life|Separar trabajo y vida]]', '[[To use technology|Usar la tecnología]]', '[[To attend meetings|Asistir a reuniones]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[might have found it hard to separate work from life|podrían haber encontrado difícil separar trabajo y vida]]".' },
  { question: '[[What|Qué]] [[can\'t others have imagined|no pueden haber imaginado otros]]?', options: ['[[Going back to the office full-time|Volver a la oficina a tiempo completo]]', '[[Working from home|Trabajar desde casa]]', '[[Having flexible hours|Tener horarios flexibles]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[can\'t have imagined going back to the office full-time|no pueden haber imaginado volver a la oficina a tiempo completo]]".' },
  { question: '[[What|Qué]] [[have companies with flexible policies seen|han visto las empresas con políticas flexibles]]?', options: ['[[Higher retention rates|Tasas de retención más altas]]', '[[Lower costs|Costes más bajos]]', '[[Fewer employees|Menos empleados]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[have seen higher retention rates|han visto tasas de retención más altas]]".' },
  { question: '[[What|Qué]] [[must the CEO have realised|debe haber comprendido el director ejecutivo]]?', options: ['[[That talent values flexibility|Que el talento valora la flexibilidad]]', '[[That offices are essential|Que las oficinas son esenciales]]', '[[That costs would rise|Que los costes subirían]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[must have realised that talent values flexibility|debe haber comprendido que el talento valora la flexibilidad]]".' },
  { question: '[[What|Qué]] [[has reduced office space done|ha hecho el espacio de oficina reducido]]?', options: ['[[Cut expenses significantly|Reducido gastos significativamente]]', '[[Increased productivity|Aumentado la productividad]]', '[[Hired more staff|Contratado más personal]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[reduced office space has cut expenses significantly|el espacio de oficina reducido ha reducido gastos significativamente]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[all employees prefer the office|todos los empleados prefieren la oficina]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] [[some can\'t have imagined going back|algunos no pueden haber imaginado volver]].' },
  { question: '[[According to the text|Según el texto]], [[investors were never sceptical|los inversores nunca fueron escépticos]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[investors who were sceptical|inversores que eran escépticos]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the text|del texto]]?', options: ['[[Remote work has proven successful despite initial doubts; flexibility benefits both companies and talent|El trabajo remoto ha demostrado ser exitoso pese a dudas iniciales; la flexibilidad beneficia a empresas y talento]]', '[[Offices will disappear completely|Las oficinas desaparecerán por completo]]', '[[Managers were right about productivity|Los directivos tenían razón sobre la productividad]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[combines|combina]] [[challenged beliefs|creencias desafiadas]], [[positive outcomes|resultados positivos]] [[and|y]] [[flexibility|flexibilidad]].' },
  { question: '[[Which modal deduction|Qué deducción modal]] [[expresses certainty about the past|expresa certeza sobre el pasado]] [[in the text|en el texto]]?', options: ['[[must have believed|deben haber creído]]', '[[might have found|podrían haber encontrado]]', '[[can\'t have imagined|no pueden haber imaginado]]'], correctAnswer: 0, explanation: '[[Must have|Must have]] [[expresses logical certainty|expresa certeza lógica]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[remote work|trabajo remoto]], [[productivity|productividad]], [[retention|retención]], [[flexibility|flexibilidad]]', '[[festival|festival]], [[heritage|patrimonio]], [[tradition|tradición]]', '[[budget|presupuesto]], [[savings|ahorros]], [[debt|deuda]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[business and work vocabulary|vocabulario de negocios y trabajo]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the future of offices|el futuro de las oficinas]]?', options: ['[[They may become smaller or hybrid|Pueden hacerse más pequeñas o híbridas]]', '[[They will close completely|Cerrarán por completo]]', '[[Nothing will change|Nada cambiará]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[mentions|menciona]] [[reduced office space|espacio de oficina reducido]] [[and|y]] [[hybrid model|modelo híbrido]].' },
];

export const UNIT_14_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u14-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Business',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
