/**
 * Unidad 41 B2 — Lección 2: Vocabulario (Education, teaching methods, online learning)
 * 18 ejercicios (B2: educación, métodos de enseñanza, aprendizaje, universidad)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Education Systems & Learning|Sistemas educativos y aprendizaje]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con educación y aprendizaje.';

export const UNIT_41_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u41-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The set of subjects|El conjunto de asignaturas]] [[taught|enseñadas]] [[in a school|en una escuela]]:', options: ['[[curriculum|currículo]]', '[[syllabus|programa]]', '[[degree|título]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning online|Aprendizaje en línea]] [[via|vía]] [[internet|internet]]:', options: ['[[online learning|aprendizaje en línea]]', '[[distance learning|aprendizaje a distancia]]', '[[blended learning|aprendizaje híbrido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal test|Un examen formal]] [[to assess knowledge|para evaluar conocimientos]]:', options: ['[[exam|examen]]', '[[assignment|tarea]]', '[[essay|ensayo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The grounds|El recinto]] [[of a university|de una universidad]]:', options: ['[[campus|campus]]', '[[lecture hall|aula magna]]', '[[seminars|seminarios]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Success in studies|Éxito en los estudios]]:', options: ['[[academic achievement|logro académico]]', '[[graduation|graduación]]', '[[qualification|calificación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal talk|Una charla formal]] [[to students|a estudiantes]]:', options: ['[[lecture|conferencia, clase magistral]]', '[[seminar|seminario]]', '[[tutorial|tutoría]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Different ways|Diferentes formas]] [[of teaching|de enseñar]]:', options: ['[[teaching methods|métodos de enseñanza]]', '[[pedagogy|pedagogía]]', '[[assessment|evaluación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A piece of work|Un trabajo]] [[given to students|dado a estudiantes]]:', options: ['[[assignment|tarea, trabajo]]', '[[homework|deberes]]', '[[project|proyecto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A written piece|Un escrito]] [[of several paragraphs|de varios párrafos]] [[on a topic|sobre un tema]]:', options: ['[[essay|ensayo]]', '[[report|informe]]', '[[dissertation|tesis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A qualification|Una titulación]] [[from university|de la universidad]]:', options: ['[[degree|título universitario]]', '[[diploma|diploma]]', '[[certificate|certificado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A small group|Un grupo pequeño]] [[discussion class|clase de discusión]]:', options: ['[[seminar|seminario]]', '[[lecture|conferencia]]', '[[workshop|taller]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The process|El proceso]] [[of evaluating|de evaluar]] [[student work|trabajo del estudiante]]:', options: ['[[assessment|evaluación]]', '[[examination|examen]]', '[[grading|calificación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Technology in education|Tecnología en educación]]:', options: ['[[EdTech|tecnología educativa]]', '[[e-learning|aprendizaje electrónico]]', '[[MOOC|curso masivo online]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Mix of online and face-to-face|Mezcla de online y presencial]]:', options: ['[[blended learning|aprendizaje híbrido]]', '[[distance learning|aprendizaje a distancia]]', '[[self-study|autoaprendizaje]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much students participate|Cuánto participan los estudiantes]] [[in class|en clase]]:', options: ['[[student engagement|participación del estudiante]]', '[[attendance|asistencia]]', '[[participation|participación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The study of teaching|El estudio de la enseñanza]]:', options: ['[[pedagogy|pedagogía]]', '[[methodology|metodología]]', '[[curriculum|currículo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A deadline|Una fecha límite]] [[for submitting work|para entregar trabajo]]:', options: ['[[due date|fecha de entrega]]', '[[deadline|plazo]]', '[[extension|prórroga]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u41-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To pass an exam|Aprobar un examen]] [[with high marks|con notas altas]]:', options: ['[[to pass with flying colours|aprobar con nota]]', '[[to graduate|graduarse]]', '[[to qualify|calificar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
