/**
 * Unidad 44 B2 — Lección 2: Vocabulario (Medical research, clinical trials, healthcare)
 * 18 ejercicios (B2: investigación médica, ensayos clínicos, salud)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Medical Research & Health|Investigación médica y salud]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con investigación médica y salud.';

export const UNIT_44_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u44-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Tests on humans|Pruebas en humanos]] [[to evaluate|para evaluar]] [[new treatments|nuevos tratamientos]]:', options: ['[[clinical trials|ensayos clínicos]]', '[[laboratory tests|pruebas de laboratorio]]', '[[diagnosis|diagnóstico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A major discovery|Un descubrimiento importante]] [[that changes|que cambia]] [[treatment|el tratamiento]]:', options: ['[[breakthrough|avance, descubrimiento]]', '[[research|investigación]]', '[[experiment|experimento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The study of|El estudio de]] [[how diseases spread|cómo se propagan las enfermedades]]:', options: ['[[epidemiology|epidemiología]]', '[[pharmacology|farmacología]]', '[[pathology|patología]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Medical care|Atención médica]] [[provided to patients|proporcionada a pacientes]]:', options: ['[[healthcare|atención sanitaria]]', '[[hospital|hospital]]', '[[clinic|clínica]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Therapeutic methods|Métodos terapéuticos]] [[for diseases|para enfermedades]]:', options: ['[[treatments|tratamientos]]', '[[medication|medicación]]', '[[surgery|cirugía]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A substance|Una sustancia]] [[that prevents|que previene]] [[or cures|o cura]] [[disease|enfermedad]]:', options: ['[[vaccine|vacuna]]', '[[drug|fármaco]]', '[[antibiotic|antibiótico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The identification|La identificación]] [[of a disease|de una enfermedad]]:', options: ['[[diagnosis|diagnóstico]]', '[[symptom|síntoma]]', '[[prognosis|pronóstico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Results|Resultados]] [[from research|de investigación]] [[or experiments|o experimentos]]:', options: ['[[findings|hallazgos]]', '[[data|datos]]', '[[evidence|evidencia]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A physical sign|Un signo físico]] [[of illness|de enfermedad]]:', options: ['[[symptom|síntoma]]', '[[diagnosis|diagnóstico]]', '[[syndrome|síndrome]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A prediction|Una predicción]] [[of disease outcome|del resultado de la enfermedad]]:', options: ['[[prognosis|pronóstico]]', '[[diagnosis|diagnóstico]]', '[[treatment|tratamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ability|La capacidad]] [[of a drug|de un fármaco]] [[to produce|de producir]] [[the desired effect|el efecto deseado]]:', options: ['[[efficacy|eficacia]]', '[[dosage|dosis]]', '[[side effect|efecto secundario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[An unwanted effect|Un efecto no deseado]] [[of medication|de la medicación]]:', options: ['[[side effect|efecto secundario]]', '[[allergy|alergia]]', '[[reaction|reacción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The amount|La cantidad]] [[of medicine|de medicina]] [[to take|a tomar]]:', options: ['[[dosage|dosis]]', '[[prescription|receta]]', '[[treatment|tratamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The return|El regreso]] [[to health|a la salud]] [[after illness|después de enfermedad]]:', options: ['[[recovery|recuperación]]', '[[rehabilitation|rehabilitación]]', '[[remission|remisión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The period|El período]] [[when disease|cuando la enfermedad]] [[is less severe|es menos severa]]:', options: ['[[remission|remisión]]', '[[recovery|recuperación]]', '[[relapse|recaída]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A group|Un grupo]] [[that receives|que recibe]] [[no treatment|ningún tratamiento]] [[in a trial|en un ensayo]]:', options: ['[[control group|grupo de control]]', '[[placebo|placebo]]', '[[sample|muestra]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A harmless substance|Una sustancia inofensiva]] [[given to|dada a]] [[control group|grupo de control]]:', options: ['[[placebo|placebo]]', '[[vaccine|vacuna]]', '[[drug|fármaco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u44-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The prevention|La prevención]] [[of disease|de enfermedad]] [[through vaccination|mediante vacunación]]:', options: ['[[immunisation|inmunización]]', '[[treatment|tratamiento]]', '[[diagnosis|diagnóstico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
