/**
 * Unidad 27 B2 — Lección 5: Expresión oral (Music & Entertainment)
 * 18 ejercicios (B2: phrasal verbs LOOK, MAKE, PUT)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_27_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u27-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[We need to look into|Necesitamos investigar]] [[cheaper concert tickets|entradas de concierto más baratas]] [[before the festival sells out|antes de que el festival se agote]].', expectedResponse: 'We need to look into cheaper concert tickets before the festival sells out.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She made up a story|Inventó una historia]] [[about why she was late|sobre por qué llegó tarde]] [[to the rehearsal|al ensayo]].', expectedResponse: 'She made up a story about why she was late to the rehearsal.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We put off the gig|Pospusimos el concierto]] [[until next month|hasta el próximo mes]] [[because of the venue\'s schedule|por la agenda del local]].', expectedResponse: 'We put off the gig until next month because of the venue\'s schedule.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I look forward to the music festival|Estoy deseando el festival de música]] [[in the summer|en el verano]] — [[we\'re going to see our favourite band|vamos a ver nuestra banda favorita]].', expectedResponse: 'I look forward to the music festival in the summer — we\'re going to see our favourite band.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Can you look after my instruments|¿Puedes cuidar mis instrumentos]] [[while I buy tickets at the box office|mientras compro entradas en la taquilla]]?', expectedResponse: 'Can you look after my instruments while I buy tickets at the box office?' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The venue made up for the delay|El local compensó el retraso]] [[by offering free drinks to the audience|ofreciendo bebidas gratis al público]].', expectedResponse: 'The venue made up for the delay by offering free drinks to the audience.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We put up at the hotel|Nos alojamos en el hotel]] [[near the venue|cerca del local]] [[at midnight|a medianoche]] [[after the concert|después del concierto]].', expectedResponse: 'We put up at the hotel near the venue at midnight after the concert.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I was looking for my concert tickets|Estaba buscando mis entradas del concierto]] [[everywhere|por todas partes]] — [[I can\'t find them|no las encuentro]].', expectedResponse: 'I was looking for my concert tickets everywhere — I can\'t find them.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[Don\'t put off buying tickets|No pospongas comprar entradas]] [[until the last minute|hasta el último momento]] — [[you might miss them sold out|podrías perderlas agotadas]].', expectedResponse: 'Don\'t put off buying tickets until the last minute — you might miss them sold out.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los phrasal verbs.', targetText: '[[We made up our minds|Decidimos]] [[and chose|y elegimos]] [[a different venue|un local diferente]].', expectedResponse: 'We made up our minds and chose a different venue.' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s11', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe un festival o concierto que tuviste que posponer (put off).', prompt: '[[Describe a festival or concert you had to put off. Use: put off, look into, make up your mind.|Describe un festival o concierto que tuviste que posponer. Usa: put off, look into, make up your mind.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s12', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica qué investigarías (look into) antes de planificar un viaje a un festival.', prompt: '[[Explain what you would look into before planning a festival trip. Use: look into, make up, put off.|Explica qué investigarías antes de planificar un viaje a un festival. Usa: look into, make up, put off.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s13', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué festival o concierto estás deseando ver (look forward to)?', prompt: '[[What festival or concert are you looking forward to attending? Give examples.|¿Qué festival o concierto estás deseando ver? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s14', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una vez que alguien cuidó de tu equipo o instrumentos (look after) durante un concierto.', prompt: '[[Describe a time when someone looked after your equipment or instruments during a concert. Use: look after, make up for, put up with.|Describe una vez que alguien cuidó de tu equipo o instrumentos durante un concierto. Usa: look after, make up for, put up with.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s15', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these phrasal verbs in your own sentences:|Usa estos phrasal verbs en tus propias oraciones:]]\n[[- look into|- look into]]\n[[- make up|- make up]]\n[[- put off|- put off]]\n[[- look forward to|- look forward to]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s16', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe un retraso que un local compensó (make up for).', prompt: '[[Describe a delay that a venue made up for. Mention what they offered.|Describe un retraso que un local compensó. Menciona qué ofrecieron.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s17', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe algo que tuviste que tolerar (put up with) durante un concierto o festival.', prompt: '[[Describe something you had to put up with during a concert or festival. Use: put up with, put off, look into.|Describe algo que tuviste que tolerar durante un concierto o festival. Usa: put up with, put off, look into.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u27-l5-s18', type: 'speaking', level: 'B2', topic: 'Music & Entertainment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cómo te decides (make up your mind) cuando planificas un viaje a un festival?', prompt: '[[How do you make up your mind when planning a festival trip? Use make up your mind and look into.|¿Cómo te decides cuando planificas un viaje a un festival? Usa make up your mind y look into.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
