/**
 * Unidad 1 B2 — Lección 1: Gramática (Repaso B1 → B2)
 * 18 ejercicios: Wish/regret, participle clauses, mixed conditionals (casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[B1 Review|Repaso B1]] [[→|→]] [[B2|B2]]';
const INSTRUCTIONS = 'Elige la forma correcta.';

export const UNIT_1_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u1-l1-g1', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[you|tú]] ____ [[told|dicho]] [[me|me]] [[before|antes]].', options: ['[[had|hubieras]]', '[[have|has]]', '[[would|habrías]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]] [[for past regrets|para arrepentimientos pasados]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g2', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If only|Ojalá]] [[they|ellos]] ____ [[accepted|aceptado]] [[the offer|la oferta]].', options: ['[[had|hubieran]]', '[[have|han]]', '[[would|habrían]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[If only + past perfect|If only + pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g3', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the applause|por los aplausos]], [[the singer|la cantante]] [[bowed|hizo una reverencia]].', options: ['[[Encouraged|Animada]]', '[[Encouraging|Animador]]', '[[Encourage|Animar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g4', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Having|Habiendo]] ____ [[the email|el email]], [[he|él]] [[replied|respondió]] [[immediately|inmediatamente]].', options: ['[[read|leído]]', '[[read|leer]]', '[[reading|leyendo]]'], correctAnswer: 'read', acceptableAnswers: ['read'], explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g5', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The contract|El contrato]] ____ [[signed|firmado]] [[last week|la semana pasada]].', options: ['[[was signed|fue firmado]]', '[[signed|firmó]]', '[[is signed|es firmado]]'], correctAnswer: 'was signed', acceptableAnswers: ['was signed'], explanation: '[[Passive past|Pasiva pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[prefer|preferiría]] [[walk|llegar]] [[to work|al trabajo]].', options: ['[[would|preferiría]]', '[[had better|más vale]]', '[[ought to|debería]]'], correctAnswer: 0, explanation: '[[Would prefer|Preferiría]] [[for preferences|para preferencias]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g7', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[regret|arrepentirse]] [[telling|haber contado]] [[her|a ella]] [[the secret|el secreto]].', options: ['[[regrets|se arrepiente de]]', '[[regret|arrepentirse]]'], correctAnswer: 'regrets', acceptableAnswers: ['regrets'], explanation: '[[Regret + gerund|Regret + gerundio]] [[for past actions|para acciones pasadas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g8', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In spite of|A pesar de]] ____ [[traffic|tráfico]], [[we arrived|llegamos]] [[on time|a tiempo]].', options: ['[[the|el]]', '[[a|un]]', '[[some|algo de]]'], correctAnswer: 'the', acceptableAnswers: ['the'], explanation: '[[In spite of + noun phrase|In spite of + sintagma nominal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g9', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[said to be|dice que es]] [[the richest|el más rico]] [[man in town|hombre del pueblo]].', options: ['[[is|es]]', '[[was|era]]', '[[has been|ha sido]]'], correctAnswer: 0, explanation: '[[Impersonal passive|Pasiva impersonal]]: [[He is said to be|Se dice que es]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g10', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[he|él]] ____ [[taken|tomado]] [[the job|el trabajo]], [[he would be|estaría]] [[rich now|rico ahora]].', options: ['[[had taken|hubiera tomado]]', '[[took|tomó]]', '[[takes|toma]]'], correctAnswer: 'had taken', acceptableAnswers: ['had taken'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g11', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[we|nosotros]] ____ [[afford|permitirnos]] [[that house|esa casa]].', options: ['[[could|pudiéramos]]', '[[can|podemos]]', '[[would|quisiéramos]]'], correctAnswer: 'could', acceptableAnswers: ['could'], explanation: '[[Wish + could|Wish + could]] [[for present impossibility|para imposibilidad presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the delay|por el retraso]], [[the passengers|los pasajeros]] [[complained|se quejaron]].', options: ['[[Frustrated|Frustrados]]', '[[Frustrating|Frustrante]]', '[[Frustrate|Frustrar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g13', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s high time|Ya es hora]] [[you|tú]] ____ [[apologised|disculparte]] [[to her|con ella]].', options: ['[[apologised|te disculparas]]', '[[apologise|disculparte]]', '[[had apologised|te hubieras disculpado]]'], correctAnswer: 'apologised', acceptableAnswers: ['apologised'], explanation: '[[It\'s high time + past simple|It\'s high time + pasado simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g14', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[regret|arrepentirse]] [[missing|haber perdido]] [[the concert|el concierto]].', options: ['[[regret|se arrepienten de]]', '[[regrets|se arrepiente de]]'], correctAnswer: 'regret', acceptableAnswers: ['regret'], explanation: '[[Regret + gerund|Regret + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g15', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[the exam|el examen]] [[early|temprano]], [[she|ella]] [[had time|tuvo tiempo]] [[for coffee|para café]].', options: ['[[Having finished|Habiendo terminado]]', '[[Finished|Terminado]]', '[[Finishing|Terminando]]'], correctAnswer: 0, explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g16', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____ [[taken|tomado]] [[that course|ese curso]] [[when I had the chance|cuando tuve la oportunidad]].', options: ['[[had|hubiera]]', '[[have|he]]', '[[would|habría]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g17', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the criticism|por las críticas]], [[he|él]] [[improved|mejoró]] [[his work|su trabajo]].', options: ['[[Motivated|Motivado]]', '[[Motivating|Motivador]]', '[[Motivate|Motivar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g18', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Despite|A pesar de]] ____ [[objections|objeciones]], [[the plan|el plan]] [[went ahead|siguió adelante]].', options: ['[[their|sus]]', '[[our|nuestras]]', '[[his|su]]'], correctAnswer: 'their', acceptableAnswers: ['their', 'our'], explanation: '[[Despite + noun phrase|Despite + sintagma nominal]].' }] }, topicName: 'Grammar' },
];
