/**
 * Unidad 6 B2 — Lección 3: Comprensión lectora (Music & Dance)
 * 13 preguntas con texto y casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Last year|El año pasado]] [[I|yo]] [[wish|ojalá]] [[I|yo]] [[had|hubiera]] [[listened|escuchado]] [[to|a]] [[my|mi]] [[teacher|profesor]] [[when|cuando]] [[he|él]] [[warned|advirtió]] [[me|me]] [[about|sobre]] [[the audition|la audición]]. [[I|Yo]] [[felt|me sentí]] [[overwhelmed|abrumado]] [[and|y]] [[frustrated|frustrado]] [[within|en]] [[weeks|semanas]] [[and|y]] [[I|yo]] [[wish|ojalá]] [[I|yo]] [[hadn\'t been|no hubiera estado]] [[so|tan]] [[confident|seguro]] [[that|de que]] [[I|yo]] [[could handle|podía manejar]] [[it|ello]]. [[If only|Ojalá]] [[I|yo]] [[had asked|hubiera preguntado]] [[for|por]] [[help|ayuda]] [[sooner|antes]]. [[Now|Ahora]] [[I|yo]] [[am|estoy]] [[relieved|aliviado]] [[that|de que]] [[I|yo]] [[left|dejé]] [[and|y]] [[found|encontré]] [[a better band|una banda mejor]]. [[I|Yo]] [[feel|me siento]] [[delighted|encantado]] [[that|de que]] [[my|mi]] [[sister|hermana]] [[has|ha]] [[learned|aprendido]] [[from|de]] [[my|mi]] [[mistake|error]] — [[she|ella]] [[was|estaba]] [[anxious|ansiosa]] [[about|por]] [[a similar audition|una audición similar]] [[and|y]] [[sought|buscó]] [[advice|consejo]] [[first|primero]]. [[I|Yo]] [[wish|ojalá]] [[everyone|todos]] [[could|pudieran]] [[recognise|reconocer]] [[when|cuando]] [[they|ellos]] [[feel|se sienten]] [[overwhelmed|abrumados]] [[and|y]] [[act|actuar]] [[before|antes de]] [[it|ello]] [[gets worse|empeore]].`;

const INSTRUCTIONS = 'Lee el texto. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does the person wish|desea la persona]] [[about listening to their teacher|sobre escuchar a su profesor]]?', options: ['[[To have more teachers|Tener más profesores]]', '[[To have listened when their teacher warned about the audition|Haber escuchado cuando su profesor advirtió sobre la audición]]', '[[To have travelled more|Haber viajado más]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I wish I had listened to my teacher when he warned me about the audition|ojalá hubiera escuchado a mi profesor cuando me advirtió sobre la audición]]".' },
  { question: '[[How|Cómo]] [[did the person feel|se sintió la persona]] [[within weeks|en semanas]]?', options: ['[[Delighted and grateful|Encantado y agradecido]]', '[[Overwhelmed and frustrated|Abrumado y frustrado]]', '[[Relieved and confident|Aliviado y seguro]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I felt overwhelmed and frustrated within weeks|me sentí abrumado y frustrado en semanas]]".' },
  { question: '[[What|Qué]] [[does the person wish they hadn\'t been|desea la persona no haber estado]]?', options: ['[[So nervous|Tan nervioso]]', '[[So confident that they could handle it|Tan seguro de que podía manejarlo]]', '[[So tired|Tan cansado]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I wish I hadn\'t been so confident that I could handle it|ojalá no hubiera estado tan seguro de que podía manejarlo]]".' },
  { question: '[[What|Qué]] [[does the person say with "If only"|dice la persona con "If only"]]?', options: ['[[If only they had more time|Ojalá tuvieran más tiempo]]', '[[If only they had asked for help sooner|Ojalá hubieran pedido ayuda antes]]', '[[If only they had studied more|Ojalá hubieran estudiado más]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[If only I had asked for help sooner|ojalá hubiera pedido ayuda antes]]".' },
  { question: '[[How|Cómo]] [[does the person feel now|se siente la persona ahora]]?', options: ['[[Anxious|Ansioso]]', '[[Relieved that they left and found a better band|Aliviado de haber dejado y encontrado una banda mejor]]', '[[Overwhelmed|Abrumado]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I am relieved that I left and found a better band|estoy aliviado de haber dejado y encontrado una banda mejor]]".' },
  { question: '[[What|Qué]] [[has the person\'s sister learned|ha aprendido la hermana de la persona]]?', options: ['[[To travel more|Viajar más]]', '[[From the person\'s mistake|Del error de la persona]]', '[[To work harder|Trabajar más duro]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[my sister has learned from my mistake|mi hermana ha aprendido de mi error]]".' },
  { question: '[[The sister|La hermana]] [[was anxious about a similar audition|estaba ansiosa por una audición similar]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 0, explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[she was anxious about a similar audition|estaba ansiosa por una audición similar]]".' },
  { question: '[[The person|La persona]] [[wishes everyone could recognise when they feel overwhelmed|desea que todos reconozcan cuándo se sienten abrumados]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 0, explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[I wish everyone could recognise when they feel overwhelmed|ojalá todos pudieran reconocer cuándo se sienten abrumados]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]] [[of|del]] [[this text|este texto]]?', options: ['[[Travel|Viajes]]', '[[Music career stress, regrets and emotional awareness|Estrés en carrera musical, arrepentimientos y conciencia emocional]]', '[[Education|Educación]]'], correctAnswer: 1, explanation: '[[The text|El texto]] [[describes|describe]] [[music career stress|estrés en carrera musical]], [[regrets|arrepentimientos]] [[and|y]] [[emotional awareness|conciencia emocional]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in|en]] [[this text|este texto]]?', options: ['[[Overwhelmed|Abrumado]], [[frustrated|frustrado]], [[relieved|aliviado]], [[anxious|ansioso]]', '[[Weather|Tiempo]], [[travel|viaje]]', '[[Food|Comida]], [[restaurant|restaurante]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[uses|usa]] [[vocabulary|vocabulario]] [[related to|relacionado con]] [[feelings|sentimientos]].' },
  { question: '[[The person|La persona]] [[asked for help|pidió ayuda]] [[when they felt overwhelmed|cuando se sintió abrumado]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[If only I had asked for help sooner|ojalá hubiera pedido ayuda antes]]" — [[they did not ask soon enough|no pidió lo suficientemente pronto]].' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[is used|se usa]] [[for|para]] "[[wish I had listened|ojalá hubiera escuchado]]"?', options: ['[[Wish + past perfect|Wish + pasado perfecto]]', '[[Wish + present|Wish + presente]]', '[[Wish + future|Wish + futuro]]'], correctAnswer: 0, explanation: '[[Wish + past perfect|Wish + pasado perfecto]] [[for past regrets|para arrepentimientos pasados]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the person|la persona]]?', options: ['[[They have no regrets|No tienen arrepentimientos]]', '[[They learned from a bad experience and want others to act early|Aprendieron de una mala experiencia y quieren que otros actúen pronto]]', '[[They never felt overwhelmed|Nunca se sintieron abrumados]]'], correctAnswer: 1, explanation: '[[They share their experience|Comparten su experiencia]] [[and|y]] [[wish others could recognise|desean que otros reconozcan]] [[overwhelmed feelings|sentimientos de abrumación]].' },
];

export const UNIT_6_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u6-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Music & Dance',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
