/**
 * Unidad 24 B2 — Lección 5: Expresión oral (Places)
 * 18 ejercicios (B2: phrasal verbs CALL, CARRY, COME)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_24_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u24-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[The match was called off|El partido fue cancelado]] [[because of the heavy rain|debido a la fuerte lluvia]].', expectedResponse: 'The match was called off because of the heavy rain.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Despite the noise|A pesar del ruido]], [[we carried on working|seguimos trabajando]] [[until we finished|hasta que terminamos]].', expectedResponse: 'Despite the noise, we carried on working until we finished.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I came across an old photo|Encontré una foto antigua por casualidad]] [[while cleaning the attic|mientras limpiaba el ático]].', expectedResponse: 'I came across an old photo while cleaning the attic.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Please call me back|Por favor devuélveme la llamada]] [[when you have a moment|cuando tengas un momento]].', expectedResponse: 'Please call me back when you have a moment.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The police carried out a search|La policía llevó a cabo una búsqueda]] [[of the building yesterday|del edificio ayer]].', expectedResponse: 'The police carried out a search of the building yesterday.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She came up with a brilliant idea|Se le ocurrió una idea brillante]] [[for the project at the meeting|para el proyecto en la reunión]].', expectedResponse: 'She came up with a brilliant idea for the project at the meeting.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The situation calls for immediate action|La situación requiere acción inmediata]].', expectedResponse: 'The situation calls for immediate action.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[How is your project coming along|Cómo va tu proyecto]]? [[Are you making progress|¿Estás avanzando]]?', expectedResponse: 'How is your project coming along? Are you making progress?' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[Why don\'t you come round this weekend|Por qué no pasas por casa este fin de semana]]? [[We\'d love to see you|Nos encantaría verte]].', expectedResponse: 'Why don\'t you come round this weekend? We\'d love to see you.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los phrasal verbs.', targetText: '[[We came through despite all the difficulties|Logramos superar a pesar de todas las dificultades]]. [[Success was worth it|El éxito valió la pena]].', expectedResponse: 'We came through despite all the difficulties. Success was worth it.' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s11', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe un lugar que encontraste por casualidad (come across).', prompt: '[[Describe a place you came across by chance. Use: come across, carry on, call off.|Describe un lugar que encontraste por casualidad. Usa: come across, carry on, call off.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s12', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica qué harías si tuvieras que cancelar (call off) un plan importante.', prompt: '[[Explain what you would do if you had to call off an important plan. Use: call off, carry on, come up with.|Explica qué harías si tuvieras que cancelar un plan importante. Usa: call off, carry on, come up with.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s13', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué lugares de tu ciudad requieren (call for) más atención?', prompt: '[[What places in your city call for more attention? Give examples.|¿Qué lugares de tu ciudad requieren más atención? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s14', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una visita que llevaste a cabo (carry out) a un lugar interesante.', prompt: '[[Describe a visit you carried out to an interesting place. Use: carry out, come across, come round.|Describe una visita que llevaste a cabo a un lugar interesante. Usa: carry out, come across, come round.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s15', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these phrasal verbs in your own sentences:|Usa estos phrasal verbs en tus propias oraciones:]]\n[[- call off|- call off]]\n[[- carry on|- carry on]]\n[[- come across|- come across]]\n[[- come up with|- come up with]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s16', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: invita a alguien a pasar por casa (come round) este fin de semana.', prompt: '[[Invite someone to come round this weekend. Mention what you could do together.|Invita a alguien a pasar por casa este fin de semana. Menciona qué podrían hacer juntos.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s17', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe un lugar fuera del camino trillado (off the beaten path) que conoces.', prompt: '[[Describe a place off the beaten path that you know. Use: come across, carry on, call for.|Describe un lugar fuera del camino trillado que conoces. Usa: come across, carry on, call for.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u24-l5-s18', type: 'speaking', level: 'B2', topic: 'Places', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué idea se te ocurrió (come up with) para mejorar tu ciudad o barrio?', prompt: '[[What idea did you come up with to improve your city or neighbourhood? Use come up with and carry out.|¿Qué idea se te ocurrió para mejorar tu ciudad o barrio? Usa come up with y carry out.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
