/**
 * Unidad 56 B2 — Lección 6: Expresión escrita (Digital Rights & Online Ethics)
 * 18 ejercicios (B2: oraciones de relativo, derechos digitales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_56_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u56-l6-w1', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre derechos digitales. Usa relative clauses (which, who, whose).', prompt: '[[Describe digital rights. Use relative clauses (which, who, whose).|Describe derechos digitales. Usa oraciones de relativo (which, who, whose).]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w2', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[Data|Los datos]] ____ [[companies collect|que las empresas recogen]] [[should be protected|deberían estar protegidos]].', options: ['[[that|que]]', '[[who|quien]]', '[[whose|cuyo]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which for things|That/which para cosas]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w3', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando non-defining relative clause: The platform was launched last year. It has millions of users.', prompt: '[[Rewrite using non-defining relative clause: The platform was launched last year. It has millions of users.|Reescribe usando oración de relativo no especificativa: La plataforma fue lanzada el año pasado. Tiene millones de usuarios.]]', expressionHint: '[[Usa: The platform, which..., has...|Usa: The platform, which..., has...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w4', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "whose" y otra con "where". Tema: datos y privacidad.', prompt: '[[Write two sentences: one with "whose" and one with "where". Topic: data and privacy.|Escribe dos oraciones: una con "whose" y otra con "where". Tema: datos y privacidad.]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w5', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[Users|Los usuarios]] ____ [[consent was not obtained|cuyo consentimiento no fue obtenido]] [[can file complaints|pueden presentar quejas]].', options: ['[[whose|cuyo]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 'whose', acceptableAnswers: ['whose'], explanation: '[[Whose for possession|Whose para posesión]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w6', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre la importancia del consentimiento online. Usa relative clauses.', prompt: '[[Describe the importance of online consent. Use relative clauses.|Describe la importancia del consentimiento online. Usa oraciones de relativo.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w7', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando relative clauses.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. The data that ____|1. Los datos que ____]]\n[[2. The platform, which ____|2. La plataforma, que ____]]\n[[3. Users whose ____|3. Los usuarios cuyo ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w8', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[The reason|La razón]] ____ [[we need encryption|por la que necesitamos encriptación]] [[is clear|es clara]].', options: ['[[why|por la que]]', '[[when|cuando]]', '[[where|donde]]'], correctAnswer: 'why', acceptableAnswers: ['why'], explanation: '[[Why for reason|Why para razón]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w9', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre ética digital. Usa relative clauses.', prompt: '[[Write an introduction to an article about digital ethics. Use relative clauses.|Escribe la introducción de un artículo sobre ética digital. Usa oraciones de relativo.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w10', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre defining y non-defining relative clauses.', prompt: '[[Explain the difference between defining and non-defining relative clauses. Use examples.|Explica la diferencia entre oraciones especificativas y no especificativas. Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w11', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[The website|La web]] ____ [[users share their data|donde los usuarios comparten sus datos]] [[must be secure|debe ser segura]].', options: ['[[where|donde]]', '[[when|cuando]]', '[[which|que]]'], correctAnswer: 'where', acceptableAnswers: ['where'], explanation: '[[Where for place|Where para lugar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w12', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte a relative clause: Cybersecurity is essential. We depend on it.', prompt: '[[Convert to relative clause: Cybersecurity is essential. We depend on it.|Convierte a oración de relativo: La ciberseguridad es esencial. Dependemos de ella.]]', expressionHint: '[[Usa: Cybersecurity, on which we depend, is...|Usa: Cybersecurity, on which we depend, is...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w13', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con: who, which, whose.', prompt: '[[Write three sentences with: who, which, whose.|Escribe tres oraciones con: who, which, whose.]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w14', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[Anyone|Cualquiera]] ____ [[breaches the rules|infringe las reglas]] [[will be banned|será baneado]].', options: ['[[who|quien]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who'], explanation: '[[Who for people|Who para personas]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w15', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre derechos digitales y privacidad. Usa relative clauses.', prompt: '[[Describe digital rights and privacy. Use relative clauses.|Describe derechos digitales y privacidad. Usa oraciones de relativo.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w16', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases sobre cómo proteger tu privacidad online. Usa: which, whose, where.', prompt: '[[Describe how to protect your privacy online. Use: which, whose, where.|Describe cómo proteger tu privacidad online. Usa: which, whose, where.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w17', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre relativo correcto.', questions: [{ question: '[[The platform|La plataforma]], ____ [[was launched last year|que fue lanzada el año pasado]], [[has millions of users|tiene millones de usuarios]].', options: ['[[which|que]]', '[[that|que]]', '[[who|quien]]'], correctAnswer: 'which', acceptableAnswers: ['which'], explanation: '[[Non-defining: which (not that)|No especificativa: which]].' }] }, topicName: 'Writing' },
  { id: 'b2-u56-l6-w18', type: 'writing', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre ética digital. Usa relative clauses.', prompt: '[[Write a short conclusion about digital ethics. Use relative clauses.|Escribe una breve conclusión sobre ética digital. Usa oraciones de relativo.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
