/**
 * Unidad 7 B2 — Lección 1: Gramática (Would rather, would prefer, It's time)
 * 18 ejercicios (B2: would rather, would prefer, It's time + past)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Would rather, would prefer, It\'s time|Would rather, would prefer, It\'s time]]';
const INSTRUCTIONS = 'Elige la opción correcta o completa el espacio.';

export const UNIT_7_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u7-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Would rather, would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[eat|comer]] [[at home|en casa]] [[tonight|esta noche]].', options: ['[[would rather|preferiría]]', '[[would prefer|preferiría]]', '[[prefer|prefiero]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather'], explanation: '[[Would rather + infinitive without to|Would rather + infinitivo sin to]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Would rather, would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____[[to fly|volar]] [[than|que]] [[to drive|conducir]].', options: ['[[would prefer|preferiría]]', '[[would rather|preferiría]]', '[[prefers|prefiere]]'], correctAnswer: 0, explanation: '[[Would prefer + to infinitive|Would prefer + infinitivo con to]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g3', type: 'fill-blank', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's time|Ya es hora]] [[he|él]] ____[[a job|un trabajo]].", options: ['[[got|consiguiera]]', '[[gets|consiga]]', '[[to get|conseguir]]'], correctAnswer: 'got', acceptableAnswers: ['got'], explanation: "[[It's time + subject + past simple|It's time + sujeto + pasado simple]]." }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Would rather', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[you came|que vinieras]] [[early|temprano]] [[tomorrow|mañana]].', options: ['[[would rather|preferiría]]', '[[would prefer|preferiría]]', '[[prefer|prefiero]]'], correctAnswer: 0, explanation: '[[Would rather + subject + past|Would rather + sujeto + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____[[not to discuss|no discutir]] [[this|esto]] [[now|ahora]].', options: ['[[would prefer|preferiría]]', '[[would rather|preferiría]]'], correctAnswer: 'would prefer', acceptableAnswers: ['would prefer'], explanation: '[[Would prefer + not to + infinitive|Would prefer + not to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g6', type: 'multiple-choice', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's high time|Ya es hora]] [[they|ellos]] ____[[apologising|disculparse]] [[for|por]] [[that|eso]].", options: ['[[started|empezaran]]', '[[start|empiecen]]', '[[to start|empezar]]'], correctAnswer: 0, explanation: "[[It's high time + past|It's high time + pasado]]." }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Would rather', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____[[cook|cocinar]] [[than|que]] [[order|pedir]] [[takeaway|comida para llevar]].', options: ['[[would rather|preferiríamos]]', '[[would prefer|preferiríamos]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather'], explanation: '[[Would rather + infinitive + than + infinitive|Would rather + infinitivo + than + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[water|agua]] [[to|a]] [[juice|zumo]].', options: ['[[would prefer|preferiría]]', '[[would rather|preferiría]]', '[[prefer|prefiero]]'], correctAnswer: 0, explanation: '[[Would prefer + noun + to + noun|Would prefer + sustantivo + to + sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g9', type: 'fill-blank', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's time|Ya es hora]] [[you|tú]] ____[[your homework|tus deberes]] [[seriously|en serio]] [[now|ahora]].", options: ['[[took|tomaras]]', '[[take|tomes]]'], correctAnswer: 'took', acceptableAnswers: ['took'], explanation: "[[It's time + subject + past simple|It's time + sujeto + pasado simple]]." }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Would rather', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[My boss|Mi jefe]] ____[[we finished|que termináramos]] [[the report|el informe]] [[today|hoy]].', options: ['[[would rather|preferiría]]', '[[would prefer|preferiría]]', '[[prefers|prefiere]]'], correctAnswer: 0, explanation: '[[Would rather + subject + past|Would rather + sujeto + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[to pay|pagar]] [[by card|con tarjeta]] [[please|por favor]].', options: ['[[would prefer|preferiría]]', '[[would rather|preferiría]]'], correctAnswer: 'would prefer', acceptableAnswers: ['would prefer'], explanation: '[[Would prefer + to infinitive|Would prefer + infinitivo con to]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g12', type: 'multiple-choice', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's about time|Ya era hora]] [[she|ella]] ____[[her room|su habitación]] [[cleaned|limpia]].", options: ['[[had|tuviera]]', '[[has|tenga]]', '[[to have|tener]]'], correctAnswer: 0, explanation: "[[It's about time + past|It's about time + pasado]]." }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Would rather', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[not go|no ir]] [[to the meeting|a la reunión]] [[today|hoy]].', options: ['[[would rather|preferiría]]', '[[would prefer|preferiría]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather'], explanation: '[[Would rather + not + infinitive|Would rather + not + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____[[us to stay|que nos quedáramos]] [[longer|más tiempo]] [[tonight|esta noche]].', options: ['[[would prefer|preferirían]]', '[[would rather|preferirían]]', '[[prefer|prefieren]]'], correctAnswer: 0, explanation: '[[Would prefer + object + to infinitive|Would prefer + objeto + infinitivo con to]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g15', type: 'fill-blank', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's time|Ya es hora]] [[for|de]] [[him|él]] ____[[his apology|su disculpa]] [[to|a]] [[her|ella]].", options: ['[[to make|hacer]]', '[[made|hiciera]]'], correctAnswer: 'to make', acceptableAnswers: ['to make'], explanation: "[[It's time for + object + to infinitive|It's time for + objeto + infinitivo con to]]." }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Would rather', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[My parents|Mis padres]] ____[[I lived|que viviera]] [[closer|más cerca]] [[to them|de ellos]].', options: ['[[would rather|preferirían]]', '[[would prefer|preferirían]]', '[[prefer|prefieren]]'], correctAnswer: 0, explanation: '[[Would rather + subject + past|Would rather + sujeto + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Would prefer', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____[[to leave|salir]] [[early|temprano]] [[tomorrow|mañana]].', options: ['[[would prefer|preferiríamos]]', '[[would rather|preferiríamos]]'], correctAnswer: 'would prefer', acceptableAnswers: ['would prefer'], explanation: '[[Would prefer + to infinitive|Would prefer + infinitivo con to]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u7-l1-g18', type: 'multiple-choice', level: 'B2', topic: "It's time", difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[It's time|Ya es hora]] [[you|tú]] ____[[your room|tu habitación]] [[up|ordenada]] [[now|ahora]].", options: ['[[tidied|ordenaras]]', '[[tidy|ordenes]]', '[[to tidy|ordenar]]'], correctAnswer: 0, explanation: "[[It's time + subject + past simple|It's time + sujeto + pasado simple]]." }] }, topicName: 'Grammar' },
];
