/**
 * Unidad 28 B2 — Lección 5: Expresión oral (Weather & Climate)
 * 18 ejercicios (B2: colocaciones verbo+sustantivo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_28_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u28-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I need to take a break|Necesito tomar un descanso]] [[from the heat|del calor]] — [[I\'ve been in the sun for hours|he estado al sol durante horas]].', expectedResponse: 'I need to take a break from the heat — I\'ve been in the sun for hours.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We made a decision yesterday|Tomamos una decisión ayer]] — [[we\'re cancelling the picnic because of the storm|cancelamos el picnic por la tormenta]].', expectedResponse: 'We made a decision yesterday — we\'re cancelling the picnic because of the storm.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The forecast made a mistake|El pronóstico cometió un error]] [[when it predicted sunny weather|cuando predijo tiempo soleado]] [[and it rained all day|y llovió todo el día]].', expectedResponse: 'The forecast made a mistake when it predicted sunny weather and it rained all day.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Can you take a photo of the rainbow|¿Puedes hacer una foto del arcoíris]]?', expectedResponse: 'Can you take a photo of the rainbow?' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He took responsibility for the climate report|Asumió la responsabilidad del informe climático]] [[last week|la semana pasada]].', expectedResponse: 'He took responsibility for the climate report last week.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We made a lot of progress this month|Hicimos mucho progreso este mes]] — [[the drought relief plan is almost finished|el plan de alivio de la sequía está casi terminado]].', expectedResponse: 'We made a lot of progress this month — the drought relief plan is almost finished.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I made an effort to check the forecast|Hice un esfuerzo por consultar el pronóstico]] [[before going out today|antes de salir hoy]].', expectedResponse: 'I made an effort to check the forecast before going out today.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She took a chance and went hiking|Se arriesgó y fue de senderismo]] [[despite the uncertain forecast|a pesar del pronóstico incierto]].', expectedResponse: 'She took a chance and went hiking despite the uncertain forecast.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[We have a meeting every Monday|Tenemos una reunión cada lunes]] [[to discuss the climate project|para discutir el proyecto climático]].', expectedResponse: 'We have a meeting every Monday to discuss the climate project.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en las colocaciones.', targetText: '[[I had a look at the forecast|Eché un vistazo al pronóstico]] [[and it looks good for tomorrow|y parece bien para mañana]].', expectedResponse: 'I had a look at the forecast and it looks good for tomorrow.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s11', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe una decisión que tuviste que tomar (make a decision) sobre el tiempo.', prompt: '[[Describe a decision you had to make about the weather. Use: make a decision, take a chance, take responsibility.|Describe una decisión que tuviste que tomar sobre el tiempo. Usa: make a decision, take a chance, take responsibility.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s12', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica cuándo es importante tomar un descanso del calor (take a break).', prompt: '[[Explain when it is important to take a break from the heat. Use: take a break, make progress, make an effort.|Explica cuándo es importante tomar un descanso del calor. Usa: take a break, make progress, make an effort.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s13', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿alguna vez el pronóstico cometió un error (make a mistake) y te afectó?', prompt: '[[Has the forecast ever made a mistake and affected you? Give examples.|¿Alguna vez el pronóstico cometió un error y te afectó? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s14', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una vez que te arriesgaste (take a chance) con el tiempo y qué pasó.', prompt: '[[Describe a time when you took a chance with the weather and what happened. Use: take a chance, make a decision, make progress.|Describe una vez que te arriesgaste con el tiempo y qué pasó. Usa: take a chance, make a decision, make progress.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s15', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these collocations in your own sentences:|Usa estas colocaciones en tus propias oraciones:]]\n[[- take a break|- take a break]]\n[[- make a decision|- make a decision]]\n[[- take responsibility|- take responsibility]]\n[[- make progress|- make progress]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s16', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una reunión sobre clima (have a meeting) y qué sugerencias hiciste (make a suggestion).', prompt: '[[Describe a meeting about climate you had and what suggestions you made. Use: have a meeting, make a suggestion, take a note.|Describe una reunión sobre clima que tuviste y qué sugerencias hiciste. Usa: have a meeting, make a suggestion, take a note.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s17', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe el progreso que has hecho (make progress) en algo relacionado con el clima.', prompt: '[[Describe the progress you have made in something related to climate. Use: make progress, make an effort, take a break.|Describe el progreso que has hecho en algo relacionado con el clima. Usa: make progress, make an effort, take a break.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s18', type: 'speaking', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cómo causas buena impresión (make a good impression) cuando hablas de clima?', prompt: '[[How do you make a good impression when discussing climate? Use make a good impression and make an effort.|¿Cómo causas buena impresión cuando hablas de clima? Usa make a good impression y make an effort.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
