/**
 * Unidad 26 B2 — Lección 4: Comprensión auditiva (Work)
 * 13 preguntas (B2: transcripción sobre trabajo y phrasal verbs GET, GIVE, GO)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hi|Hola]], [[I'm|soy]] [[Maria|María]] [[and|y]] [[I work|trabajo]] [[as|como]] [[an HR manager|gerente de recursos humanos]] [[at|en]] [[a tech company|una empresa tecnológica]]. [[Last year|El año pasado]] [[we|nosotros]] [[went through|atravesamos]] [[a major restructuring|una gran reestructuración]] — [[some colleagues|algunos compañeros]] [[gave up|se rindieron]] [[and|y]] [[left|dejaron]], [[but|pero]] [[most|la mayoría]] [[got through|superó]] [[the transition|la transición]] [[successfully|con éxito]]. [[I|Yo]] [[almost|casi]] [[gave up|me rendí]] [[too|también]] [[when|cuando]] [[the workload|carga de trabajo]] [[was overwhelming|era abrumadora]], [[but|pero]] [[I|yo]] [[got over|superé]] [[my stress|mi estrés]] [[and|y]] [[carried on|continué]]. [[Our team|Nuestro equipo]] [[gets along|se lleva]] [[well|bien]] [[with|con]] [[each other|entre sí]] — [[we|nosotros]] [[support|apoyamos]] [[one another|unos a otros]] [[when|cuando]] [[things|las cosas]] [[go wrong|salen mal]]. [[The presentation|La presentación]] [[went off|salió]] [[well|bien]] [[last month|el mes pasado]] [[and|y]] [[we|nosotros]] [[got a raise|conseguimos un aumento]]. [[If you|Si]] [[ever|alguna vez]] [[feel like|sientes ganas de]] [[giving up|rendirte]] [[at work|en el trabajo]], [[remember|recuerda]] [[that|que]] [[you can|puedes]] [[get through|superar]] [[any challenge|cualquier desafío]] [[with|con]] [[the right support|el apoyo adecuado]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Maria, an HR manager at a tech company|María, gerente de RRHH en una empresa tecnológica]]', '[[A colleague who left the company|Un compañero que dejó la empresa]]', '[[A tech developer|Un desarrollador tecnológico]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Maria and I work as an HR manager at a tech company|soy María y trabajo como gerente de RRHH en una empresa tecnológica]]".' },
  { question: '[[What|Qué]] [[did the company go through|atravesó la empresa]] [[last year|el año pasado]]?', options: ['[[A major restructuring|Una gran reestructuración]]', '[[A promotion campaign|Una campaña de ascensos]]', '[[A salary increase|Un aumento de salario]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[we went through a major restructuring|atravesamos una gran reestructuración]]".' },
  { question: '[[What|Qué]] [[did some colleagues do|hicieron algunos compañeros]]?', options: ['[[They gave up and left|Se rindieron y se fueron]]', '[[They got through the transition|Superaron la transición]]', '[[They got a raise|Consiguieron un aumento]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[some colleagues gave up and left|algunos compañeros se rindieron y se fueron]]".' },
  { question: '[[What|Qué]] [[did Maria almost do|casi hizo María]]?', options: ['[[She almost gave up when the workload was overwhelming|Casi se rindió cuando la carga de trabajo era abrumadora]]', '[[She almost left the company|Casi dejó la empresa]]', '[[She almost got promoted|Casi fue ascendida]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I almost gave up when the workload was overwhelming|casi me rendí cuando la carga de trabajo era abrumadora]]".' },
  { question: '[[What|Qué]] [[did Maria get over|superó María]]?', options: ['[[Her stress|Su estrés]]', '[[Her job|Su trabajo]]', '[[Her colleagues|Sus compañeros]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I got over my stress|superé mi estrés]]".' },
  { question: '[[How|Cómo]] [[does the team get along|se lleva el equipo]]?', options: ['[[They get along well with each other|Se llevan bien entre sí]]', '[[They gave up|Se rindieron]]', '[[They went through a crisis|Atravesaron una crisis]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[Our team gets along well with each other|nuestro equipo se lleva bien entre sí]]".' },
  { question: '[[The presentation|La presentación]] ____ [[well|bien]] [[last month|el mes pasado]].', options: ['[[went off|salió]]', '[[went on|continuó]]', '[[went through|atravesó]]'], correctAnswer: 0, explanation: '[[Go off = happen successfully|Go off = salir bien]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the listening|de la escucha]]?', options: ['[[Resilience and support help overcome work challenges|La resiliencia y el apoyo ayudan a superar los desafíos laborales]]', '[[Everyone should give up when things are difficult|Todos deberían rendirse cuando las cosas son difíciles]]', '[[HR managers never get stressed|Los gerentes de RRHH nunca se estresan]]'], correctAnswer: 0, explanation: '[[The speaker|El hablante]] [[shares|comparte]] [[her experience|su experiencia]] [[and|y]] [[encourages|anima]] [[persistence|la perseverancia]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[with "get"|con "get"]] [[means|significa]] [["recover from"|"recuperarse de"]]?', options: ['[[Get over|Get over]]', '[[Get through|Get through]]', '[[Get along|Get along]]'], correctAnswer: 0, explanation: '[[Get over|Get over]] [[= recover from|= recuperarse de]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[restructuring|reestructuración]], [[workload|carga de trabajo]], [[transition|transición]], [[raise|aumento]], [[support|apoyo]]', '[[gallery|galería]], [[harbour|puerto]], [[tour|tour]]', '[[computer|ordenador]], [[software|software]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[work vocabulary|vocabulario de trabajo]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[Maria|María]]?', options: ['[[She is resilient and values team support|Es resiliente y valora el apoyo del equipo]]', '[[She prefers to give up|Prefiere rendirse]]', '[[She doesn\'t like her job|No le gusta su trabajo]]'], correctAnswer: 0, explanation: '[[She got over|Superó]] [[her stress|su estrés]] [[and|y]] [[emphasises|enfatiza]] [[support|el apoyo]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[means|significa]] [["succeed in a difficult situation"|"tener éxito en una situación difícil"]]?', options: ['[[Get through|Get through]]', '[[Give up|Give up]]', '[[Go off|Go off]]'], correctAnswer: 0, explanation: '[[Get through|Get through]] [[= succeed in a difficult situation|= superar una situación difícil]].' },
  { question: '[[Maria suggests|María sugiere]] [[that|que]] [[when you feel like giving up|cuando sientes ganas de rendirte]] [[you should|deberías]] ____.', options: ['[[Remember that you can get through any challenge with the right support|Recordar que puedes superar cualquier desafío con el apoyo adecuado]]', '[[Give up immediately|Rendirte inmediatamente]]', '[[Leave the company|Dejar la empresa]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[remember that you can get through any challenge with the right support|recuerda que puedes superar cualquier desafío con el apoyo adecuado]]".' },
];

export const UNIT_26_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u26-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Work',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
