/**
 * Unidad 26 B2 — Lección 2: Vocabulario (Work)
 * 18 ejercicios (B2: trabajo, empleo, oficina)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Work|Trabajo]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con el trabajo.';

export const UNIT_26_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u26-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who works for themselves|Persona que trabaja por cuenta propia]]:', options: ['[[self-employed|autónomo]]', '[[unemployed|desempleado]]', '[[overemployed|sobreempleado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To increase responsibility or challenge|Aumentar responsabilidad o desafío]]:', options: ['[[promotion|ascenso]]', '[[demotion|descenso]]', '[[resignation|dimisión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Working from home|Trabajar desde casa]]:', options: ['[[remote work|trabajo remoto]]', '[[shift work|trabajo por turnos]]', '[[overtime|horas extra]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal meeting to assess performance|Reunión formal para evaluar el rendimiento]]:', options: ['[[performance review|evaluación de rendimiento]]', '[[brainstorm|lluvia de ideas]]', '[[deadline|fecha límite]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To leave your job voluntarily|Dejar tu trabajo voluntariamente]]:', options: ['[[resign|dimitir]]', '[[dismiss|despedir]]', '[[retire|jubilarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Balance between work and personal life|Equilibrio entre trabajo y vida personal]]:', options: ['[[work-life balance|equilibrio trabajo-vida]]', '[[workload|carga de trabajo]]', '[[workflow|flujo de trabajo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Skills that can be used in different jobs|Habilidades que se pueden usar en diferentes trabajos]]:', options: ['[[transferable skills|habilidades transferibles]]', '[[hard skills|habilidades técnicas]]', '[[soft skills|habilidades blandas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A fixed period of work experience|Período fijo de experiencia laboral]]:', options: ['[[internship|prácticas]]', '[[apprenticeship|aprendizaje]]', '[[probation|período de prueba]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a deadline"|Colocación: "to ____ a deadline"]]', options: ['[[meet|cumplir]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a decision"|Colocación: "to ____ a decision"]]', options: ['[[make|tomar]]', '[[do|hacer]]', '[[take|tomar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ the sack" (be dismissed)|Expresión: "ser despedido"]]', options: ['[[get|recibir]]', '[[give|dar]]', '[[take|tomar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A period when you are not working|Período en el que no trabajas]]:', options: ['[[career break|parón profesional]]', '[[breakdown|avería]]', '[[breakthrough|avance]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To reduce the number of employees|Reducir el número de empleados]]:', options: ['[[downsize|reducir plantilla]]', '[[upsize|aumentar plantilla]]', '[[outsource|externalizar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ responsibility"|Colocación: "to ____ responsibility"]]', options: ['[[take|asumir]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Working more than your contracted hours|Trabajar más de tus horas contratadas]]:', options: ['[[overtime|horas extra]]', '[[flexitime|horario flexible]]', '[[part-time|tiempo parcial]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ a promotion"|Expresión: "conseguir un ascenso"]]', options: ['[[get|conseguir]]', '[[make|hacer]]', '[[take|tomar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who works with you|Persona que trabaja contigo]]:', options: ['[[colleague|compañero de trabajo]]', '[[competitor|competidor]]', '[[client|cliente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u26-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a raise"|Colocación: "conseguir un aumento"]]', options: ['[[get|conseguir]]', '[[make|hacer]]', '[[give|dar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
