/**
 * Unidad 32 B2 — Lección 5: Expresión oral (Environment extended)
 * 18 ejercicios (B2: cuantificadores y medio ambiente)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_32_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u32-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[All of the trees in the park were planted last year|Todos los árboles del parque fueron plantados el año pasado]].', expectedResponse: 'All of the trees in the park were planted last year.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Most of the species in the reserve are protected|La mayoría de especies en la reserva están protegidas]].', expectedResponse: 'Most of the species in the reserve are protected.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Each ecosystem has its own delicate balance|Cada ecosistema tiene su propio balance delicado]].', expectedResponse: 'Each ecosystem has its own delicate balance.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Every single day we recycle our waste|Cada día reciclamos nuestros residuos]].', expectedResponse: 'Every single day we recycle our waste.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Both governments agreed to reduce emissions at the summit|Ambos gobiernos acordaron reducir emisiones en la cumbre]].', expectedResponse: 'Both governments agreed to reduce emissions at the summit.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Most of the water in the lake is contaminated|La mayoría del agua del lago está contaminada]].', expectedResponse: 'Most of the water in the lake is contaminated.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Every three hours the sensors record air quality|Cada tres horas los sensores registran la calidad del aire]].', expectedResponse: 'Every three hours the sensors record air quality.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Both wind and solar are renewable energy sources|Tanto viento como solar son fuentes de energía renovables]].', expectedResponse: 'Both wind and solar are renewable energy sources.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[All the recycling bins are full this week|Todos los contenedores de reciclaje están llenos esta semana]].', expectedResponse: 'All the recycling bins are full this week.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los cuantificadores.', targetText: '[[Each participant must bring their own reusable bottle|Cada participante debe traer su propia botella reutilizable]].', expectedResponse: 'Each participant must bring their own reusable bottle.' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s11', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe qué hace tu comunidad para proteger el medio ambiente.', prompt: '[[Describe what your community does to protect the environment. Use: all, most, each, every, both.|Describe qué hace tu comunidad para proteger el medio ambiente. Usa: all, most, each, every, both.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s12', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica la diferencia entre "all", "most" y "each".', prompt: '[[Explain the difference between "all", "most" and "each". Give examples from environment.|Explica la diferencia entre "all", "most" y "each". Da ejemplos del medio ambiente.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s13', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué amenazas enfrenta la biodiversidad en tu región?', prompt: '[[What threats does biodiversity face in your region? Use: endangered, habitat, deforestation, greenhouse gases.|¿Qué amenazas enfrenta la biodiversidad en tu región? Usa: endangered, habitat, deforestation, greenhouse gases.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s14', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe cómo "both" gobiernos y empresas pueden colaborar en conservación.', prompt: '[[Describe how both governments and businesses can collaborate on conservation. Use: both, raise awareness, pose a threat, strike a balance.|Describe cómo tanto gobiernos como empresas pueden colaborar en conservación. Usa: both, raise awareness, pose a threat, strike a balance.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s15', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada cuantificador.', prompt: '[[Use these quantifiers in your own sentences:|Usa estos cuantificadores en tus propias oraciones:]]\n[[- all|- all]]\n[[- most|- most]]\n[[- each|- each]]\n[[- every|- every]]\n[[- both|- both]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s16', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe un proyecto de conservación que conozcas.', prompt: '[[Describe a conservation project you know. Mention: biodiversity, habitat, renewable energy, nature reserve.|Describe un proyecto de conservación que conozcas. Menciona: biodiversity, habitat, renewable energy, nature reserve.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s17', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: explica por qué "every" persona debe tomar responsabilidad por el medio ambiente.', prompt: '[[Explain why every person must take responsibility for the environment. Use: every, each, raise awareness, have an impact.|Explica por qué cada persona debe tomar responsabilidad por el medio ambiente. Usa: every, each, raise awareness, have an impact.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u32-l5-s18', type: 'speaking', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cuándo usamos "each" y cuándo "every"?', prompt: '[[When do we use "each" and when "every"? Give examples from environment.|¿Cuándo usamos "each" y cuándo "every"? Da ejemplos del medio ambiente.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
