/**
 * Unidad 3 B2 — Lección 5: Expresión oral (Arts & Crafts)
 * 18 ejercicios con casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_3_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u3-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[love|me encanta]] [[reading|leer]] [[art books|libros de arte]] [[in my free time|en mi tiempo libre]].', expectedResponse: 'I love reading art books in my free time.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[chose|eligió]] [[to study|estudiar]] [[sculpture|escultura]] [[at the school|en la escuela]].', expectedResponse: 'He chose to study sculpture at the school.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[missed attending|perdió asistir]] [[the exhibition|a la exposición]] [[last week|la semana pasada]].', expectedResponse: 'She missed attending the exhibition last week.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[aim|pretendemos]] [[to meet|cumplir]] [[the deadline|la fecha límite]] [[next month|el mes que viene]].', expectedResponse: 'We aim to meet the deadline next month.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They|Ellos]] [[stopped|dejaron]] [[painting|de pintar]] [[the canvas|el lienzo]] [[yesterday|ayer]].', expectedResponse: 'They stopped painting the canvas yesterday.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[intend|tengo intención]] [[to do|de hacer]] [[a masterclass|una masterclass]] [[after|después de]] [[the workshop|el taller]].', expectedResponse: 'I intend to do a masterclass after the workshop.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Would you|¿Te importaría]] [[mind|]] [[opening|abrir]] [[the door|la puerta]]?', expectedResponse: 'Would you mind opening the door?' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[agreed|acordó]] [[to take|hacer]] [[the course|el curso]] [[next semester|el próximo semestre]].', expectedResponse: 'She agreed to take the course next semester.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué disfrutas hacer en tus estudios de arte.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I love/enjoy [verb+ing]...' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué esperas lograr en tu educación artística.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I hope/aim to [infinitive]...' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[delayed|retrasé]] [[applying|solicitar]] [[abroad|en el extranjero]] [[for|para]] [[my residency|mi residencia artística]].', expectedResponse: 'I delayed applying abroad for my residency.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[appears|parece]] [[to be|ser]] [[the top|el primero]] [[in the cohort|de la promoción]].', expectedResponse: 'He appears to be the top in the cohort.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[recommend|recomiendo]] [[attending|asistir a]] [[more tutorials|más tutorías]] [[for|para]] [[better results|mejores resultados]].', expectedResponse: 'I recommend attending more tutorials for better results.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una decisión que tomaste sobre tu educación artística.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I chose/decided to [infinitive]...' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases tu experiencia artística usando gerundio e infinitivo.', targetText: '____. ____. ____.', expectedResponse: 'I love... I hope to... I decided to...' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[hope|espero]] [[to obtain|obtener]] [[a scholarship|una beca]] [[for|para]] [[postgraduate study|estudios de posgrado]].', expectedResponse: 'I hope to obtain a scholarship for postgraduate study.' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué evitas hacer cuando estudias arte.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I avoid [verb+ing]...' }, topicName: 'Speaking' },
  { id: 'b2-u3-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Arts & Crafts', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases las ventajas de hacer un año sabático antes de la escuela de arte.', targetText: '____. ____. ____.', expectedResponse: 'A gap year allows... I would consider... It helps...' }, topicName: 'Speaking' },
];
