/**
 * Unidad 7 B2 — Lección 5: Expresión oral (Shopping & Consumerism)
 * 18 ejercicios (B2: would rather, would prefer, It's time, shopping vocabulary)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_7_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u7-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[would rather|preferiría]] [[shop|comprar]] [[online|en línea]] [[tonight|esta noche]].', expectedResponse: 'I would rather shop online tonight.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[would prefer|preferiría]] [[to buy|comprar]] [[local|local]] [[than|que]] [[imported|importado]].', expectedResponse: 'He would prefer to buy local than imported.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[It's time|Ya es hora]] [[he|él]] [[got|pusiera]] [[his budget|su presupuesto]] [[under control|bajo control]].", expectedResponse: "It's time he got his budget under control." }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[found|encontré]] [[a great|una gran]] [[bargain|ganga]] [[at|en]] [[the|el]] [[flea market|mercado de pulgas]] [[last|el pasado]] [[weekend|fin de semana]].', expectedResponse: 'I found a great bargain at the flea market last weekend.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[sister|hermana]] [[gets on with|se lleva bien con]] [[everyone|todos]] [[at|en]] [[the market|el mercado]].', expectedResponse: 'My sister gets on with everyone at the market.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[would rather|preferiría]] [[you came|que vinieras]] [[early|temprano]] [[tomorrow|mañana]] [[to the sale|a la rebaja]].', expectedResponse: 'I would rather you came early tomorrow to the sale.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[It's high time|Ya es hora]] [[they|ellos]] [[started|empezaran]] [[apologising|disculparse]] [[for|por]] [[that|ese]] [[defective product|producto defectuoso]].", expectedResponse: "It's high time they started apologising for that defective product." }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[avoid|evito]] [[impulse buys|compras impulsivas]] [[by|con]] [[sticking to|manteniéndome en]] [[my|mi]] [[shopping list|lista de la compra]].', expectedResponse: 'I avoid impulse buys by sticking to my shopping list.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué preferirías hacer este fin de semana.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I would rather / would prefer to...' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que ya es hora de que hagas.', targetText: "[[It's time|Ya es hora]] ____.", expectedResponse: "It's time I [past simple]..." }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[would prefer|preferiría]] [[not to discuss|no discutir]] [[prices|precios]] [[now|ahora]].', expectedResponse: 'She would prefer not to discuss prices now.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[always|siempre]] [[keep|guardo]] [[my|mis]] [[receipts|recibos]] [[for|para]] [[returns|devoluciones]] [[and|y]] [[refunds|reembolsos]].', expectedResponse: 'I always keep my receipts for returns and refunds.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My boss|Mi jefe]] [[would rather|preferiría]] [[we finished|que termináramos]] [[the inventory|el inventario]] [[today|hoy]].', expectedResponse: 'My boss would rather we finished the inventory today.' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: describe tus hábitos de compra (bargains, budget, discounts).', targetText: '____. ____. ____.', expectedResponse: 'I prefer... I avoid... I always...' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases una preferencia sobre compras usando would rather o would prefer.', targetText: '____. ____. ____.', expectedResponse: 'I would rather... I would prefer to...' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[It's about time|Ya era hora]] [[she|ella]] [[had|tuviera]] [[her wardrobe|su armario]] [[organised|organizado]].", expectedResponse: "It's about time she had her wardrobe organised." }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: qué preferirías que hiciera alguien en una tienda.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I would rather [person] [past]...' }, topicName: 'Speaking' },
  { id: 'b2-u7-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Shopping & Consumerism', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases la importancia de comprar localmente.', targetText: '____. ____. ____.', expectedResponse: 'Local shopping is better because... I prefer... It helps...' }, topicName: 'Speaking' },
];
