/**
 * Unidad 22 B2 — Lección 2: Vocabulario (Animals)
 * 18 ejercicios (B2: recreado con palabras reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Animals|Animales]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con animales.';

export const UNIT_22_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u22-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A species at risk of extinction|Especie en riesgo de extinción]]:', options: ['[[endangered|en peligro de extinción]]', '[[extended|extendido]]', '[[engaged|comprometido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The natural home of an animal|Hogar natural de un animal]]:', options: ['[[habitat|hábitat]]', '[[habit|hábito]]', '[[habitation|habitación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To hunt illegally|Cazar ilegalmente]]:', options: ['[[poach|cazar furtivamente]]', '[[poach|escalfar]]', '[[pouch|bolsa]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Animals that live in the wild, not domesticated|Animales que viven en estado salvaje]]:', options: ['[[wildlife|fauna salvaje]]', '[[wilderness|naturaleza salvaje]]', '[[wildfire|incendio forestal]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To disappear completely from Earth|Desaparecer completamente de la Tierra]]:', options: ['[[become extinct|extinguirse]]', '[[become exhausted|agotarse]]', '[[become excited|emocionarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place where animals are protected|Lugar donde los animales están protegidos]]:', options: ['[[sanctuary|santuario]]', '[[sanction|sanción]]', '[[sanitation|saneamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To breed animals in captivity|Criar animales en cautividad]]:', options: ['[[breed|criar]]', '[[bleed|sangrar]]', '[[blend|mezclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The variety of plant and animal life|Variedad de vida vegetal y animal]]:', options: ['[[biodiversity|biodiversidad]]', '[[biography|biografía]]', '[[biology|biología]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To move from one region to another seasonally|Moverse de una región a otra según la estación]]:', options: ['[[migrate|migrar]]', '[[emigrate|emigrar]]', '[[immigrate|inmigrar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[An animal that hunts other animals|Animal que caza a otros animales]]:', options: ['[[predator|depredador]]', '[[prey|presa]]', '[[prediction|predicción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[An animal that is hunted|Animal que es cazado]]:', options: ['[[prey|presa]]', '[[predator|depredador]]', '[[pray|rezar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "natural ____"|Colocación: "natural ____"]] [[(where animals live)|(donde viven los animales)]]', options: ['[[habitat|hábitat]]', '[[habit|hábito]]', '[[habitation|habitación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a species"|Colocación: "to ____ a species"]] [[(protect from extinction)|(proteger de la extinción)]]', options: ['[[protect|proteger]]', '[[prevent|prevenir]]', '[[promote|promover]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "on the ____ of extinction"|Expresión: "on the ____ of extinction"]]', options: ['[[brink|borde]]', '[[edge|borde]]', '[[blink|parpadeo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "____ loss"|Colocación: "____ loss"]] [[(destruction of animal homes)|(destrucción de hogares de animales)]]', options: ['[[habitat|hábitat]]', '[[habit|hábito]]', '[[habitual|habitual]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ an animal"|Expresión: "to ____ an animal"]] [[(set free)|(liberar)]]', options: ['[[release|liberar]]', '[[relieve|aliviar]]', '[[relate|relacionar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "____ species"|Colocación: "____ species"]]', options: ['[[endangered|en peligro]]', '[[enduring|perdurable]]', '[[engaging|atractivo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u22-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Animals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ wildlife"|Expresión: "to ____ wildlife"]] [[(protect)|(proteger)]]', options: ['[[conserve|conservar]]', '[[converse|conversar]]', '[[convert|convertir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
