/**
 * Unidad 21 B2 — Lección 5: Expresión oral (Personal Development)
 * 18 ejercicios (B2: recreado con casos reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_21_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u21-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen to the sentence and repeat it aloud.|Escucha la frase y repítela en voz alta.]]', targetText: '[[Although|Aunque]] [[she works on her goals every day|trabaja en sus metas cada día]], [[she still struggles|aún le cuesta]] [[to achieve them|conseguirlas]].', expectedResponse: 'Although she works on her goals every day, she still struggles to achieve them.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[Despite the setbacks|A pesar de los contratiempos]], [[the workshop went ahead|el taller siguió adelante]].', expectedResponse: 'Despite the setbacks, the workshop went ahead.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[Meditation is calming|La meditación es relajante]] [[whereas|mientras que]] [[goal-setting is more dynamic|establecer metas es más dinámico]].', expectedResponse: 'Meditation is calming whereas goal-setting is more dynamic.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[In spite of feeling discouraged|A pesar de sentirse desanimada]], [[she attended the coaching session|asistió a la sesión de coaching]].', expectedResponse: 'In spite of feeling discouraged, she attended the coaching session.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[He reads self-help books|Lee libros de autoayuda]]. [[However|Sin embargo]], [[he rarely applies the advice|raramente aplica los consejos]].', expectedResponse: 'He reads self-help books. However, he rarely applies the advice.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[Despite his doubts|A pesar de sus dudas]], [[he completed the course|completó el curso]].', expectedResponse: 'Despite his doubts, he completed the course.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[Reading builds knowledge|Leer construye conocimiento]] [[whereas|mientras que]] [[practising builds skills|practicar construye habilidades]].', expectedResponse: 'Reading builds knowledge whereas practising builds skills.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Listen and repeat aloud.|Escucha y repite en voz alta.]]', targetText: '[[The workshop was full|El taller estaba lleno]]. [[However|Sin embargo]], [[I found a seat at the back|encontré un asiento al fondo]].', expectedResponse: 'The workshop was full. However, I found a seat at the back.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Read aloud and focus on intonation.|Lee en voz alta y céntrate en la entonación.]]', targetText: '[[Although the mentor advised patience|Aunque el mentor aconsejó paciencia]], [[he rushed the project|se apresuró con el proyecto]].', expectedResponse: 'Although the mentor advised patience, he rushed the project.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Read aloud and use emphasis on contrast linkers.|Lee en voz alta y usa énfasis en los conectores de contraste.]]', targetText: '[[Despite the high cost|A pesar del alto coste]], [[many people join coaching programmes|muchas personas se apuntan a programas de coaching]].', expectedResponse: 'Despite the high cost, many people join coaching programmes.' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s11', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Speak for 1–2 minutes: describe your learning routine using at least 3 contrast linkers (although, despite, whereas, however).|Habla durante 1–2 minutos: describe tu rutina de aprendizaje usando al menos 3 conectores de contraste (although, despite, whereas, however).]]', prompt: '[[Describe your learning routine. Include:|Describe tu rutina de aprendizaje. Incluye:]]\n[[- what you do and how often|- qué haces y con qué frecuencia]]\n[[- what you find easy or difficult|- qué te resulta fácil o difícil]]\n[[- contrasts between different activities|- contrastes entre diferentes actividades]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s12', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Speak for 1–2 minutes: compare two learning methods using whereas.|Habla durante 1–2 minutos: compara dos métodos de aprendizaje usando whereas.]]', prompt: '[[Compare two learning methods (e.g. workshops vs self-study, reading vs courses).|Compara dos métodos de aprendizaje (ej. talleres vs autoestudio, lectura vs cursos).]]\n[[Use whereas to contrast:|Usa whereas para contrastar:]]\n[[- benefits|- beneficios]]\n[[- difficulties|- dificultades]]\n[[- who they suit|- a quién convienen]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s13', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Answer aloud: do you think it is possible to grow personally despite a busy life?|Responde en voz alta: ¿crees que es posible crecer personalmente a pesar de una vida ocupada?]]', prompt: '[[Do you think it is possible to grow personally despite a busy life? Give reasons and use contrast linkers.|¿Crees que es posible crecer personalmente a pesar de una vida ocupada? Da razones y usa conectores de contraste.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s14', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Speak aloud: describe a time when you attended a workshop despite not feeling like it.|Habla en voz alta: describe una vez que asististe a un taller a pesar de no tener ganas.]]', prompt: '[[Describe a time when you attended a workshop despite not feeling like it. Explain:|Describe una vez que asististe a un taller a pesar de no tener ganas. Explica:]]\n[[- what you did|- qué hiciste]]\n[[- why you didn\'t feel like it|- por qué no tenías ganas]]\n[[- how you felt afterwards|- cómo te sentiste después]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s15', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Practise expressions. Say aloud 3–4 sentences with each.|Practica expresiones. Di en voz alta 3–4 frases con cada una.]]', prompt: '[[Use these expressions in your own sentences:|Usa estas expresiones en tus propias oraciones:]]\n[[- work on|- trabajar en]]\n[[- keep learning|- seguir aprendiendo]]\n[[- build up confidence|- desarrollar confianza]]\n[[- set a goal|- establecer una meta]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s16', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Speak aloud: persuade a friend to join a coaching programme with you using contrasts.|Habla en voz alta: convence a un amigo de unirse a un programa de coaching contigo usando contrastes.]]', prompt: '[[Persuade a friend to join a coaching programme with you. Mention:|Convence a un amigo de unirse a un programa de coaching contigo. Menciona:]]\n[[- benefits despite the cost|- beneficios a pesar del coste]]\n[[- what they will gain|- qué ganarán]]\n[[- use although/despite/in spite of|- usa although/despite/in spite of]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s17', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Speak for 1 minute: describe the differences between learning alone and in a workshop using whereas.|Habla durante 1 minuto: describe las diferencias entre aprender solo y en un taller usando whereas.]]', prompt: '[[Describe the differences between learning alone and in a workshop.|Describe las diferencias entre aprender solo y en un taller.]]\n[[Use whereas at least twice.|Usa whereas al menos dos veces.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u21-l5-s18', type: 'speaking', level: 'B2', topic: 'Personal Development', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Answer aloud: what advice would you give someone who wants to start learning but has many excuses?|Responde en voz alta: ¿qué consejo darías a alguien que quiere empezar a aprender pero tiene muchas excusas?]]', prompt: '[[What advice would you give a person who wants to start learning but has many excuses? Use contrast linkers (although, despite, however).|¿Qué consejo darías a alguien que quiere empezar a aprender pero tiene muchas excusas? Usa conectores de contraste (although, despite, however).]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
