/**
 * Unidad 10 B2 — Lección 3: Comprensión lectora (Repaso 6–9)
 * 18 actividades (B2: mixed topics from units 6-9)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[had|hubiera]] [[more time|más tiempo]] [[with|con]] [[my|mi]] [[family|familia]] — [[my|mis]] [[siblings|hermanos]] [[and|y]] [[cousins|primos]] [[live|viven]] [[abroad|en el extranjero]] [[and|y]] [[I|yo]] [[would rather|preferiría]] [[visit|visitar]] [[them|a ellos]] [[than|que]] [[go|ir]] [[on holiday|de vacaciones]] [[alone|solo]]. [[If|Si]] [[I|yo]] [[had booked|hubiera reservado]] [[my flight|mi vuelo]] [[earlier|antes]], [[I|yo]] [[would have saved|habría ahorrado]] [[money|dinero]] [[for|para]] [[the trip|el viaje]]. [[Having felt|Habiendo sentido]] [[overwhelmed|abrumado]] [[and|y]] [[anxious|ansioso]] [[about|por]] [[the|el]] [[environment|medio ambiente]] [[lately|últimamente]], [[I|yo]] [[decided|decidí]] [[to|a]] [[recycle|reciclar]] [[more|más]] [[and|y]] [[reduce|reducir]] [[my|mi]] [[waste|residuos]]. [[It's time|Ya es hora]] [[I|yo]] [[called|llamara]] [[my|mi]] [[mother-in-law|suegra]] — [[she|ella]] [[gets on with|se lleva bien con]] [[everyone|todos]] [[and|y]] [[I|yo]] [[feel|me siento]] [[grateful|agradecido]] [[for|por]] [[her|ella]]. [[Climate change|El cambio climático]] [[and|y]] [[pollution|contaminación]] [[are|son]] [[real|reales]] [[threats|amenazas]] — [[we|nosotros]] [[must|debemos]] [[switch|cambiar]] [[to|a]] [[renewable energy|energía renovable]] [[and|y]] [[protect|proteger]] [[our|nuestro]] [[planet|planeta]].`;

const INSTRUCTIONS = 'Lee el texto. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does the person wish|desea la persona]]?', options: ['[[To travel alone|Viajar solo]]', '[[More time with family|Más tiempo con la familia]]', '[[To work more|Trabajar más]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I wish I had more time with my family|ojalá tuviera más tiempo con mi familia]]".' },
  { question: '[[Where|Dónde]] [[do the siblings and cousins live|viven los hermanos y primos]]?', options: ['[[In the same city|En la misma ciudad]]', '[[Abroad|En el extranjero]]', '[[With the person|Con la persona]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[my siblings and cousins live abroad|mis hermanos y primos viven en el extranjero]]".' },
  { question: '[[What|Qué]] [[would the person rather do|preferiría hacer la persona]]?', options: ['[[Go on holiday alone|Ir de vacaciones solo]]', '[[Visit family than go on holiday alone|Visitar a la familia que ir de vacaciones solo]]', '[[Stay at home|Quedarse en casa]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I would rather visit them than go on holiday alone|preferiría visitarlos que ir de vacaciones solo]]".' },
  { question: '[[What|Qué]] [[would have happened|habría pasado]] [[if the person had booked the flight earlier|si la persona hubiera reservado el vuelo antes]]?', options: ['[[They would have missed the flight|Habrían perdido el vuelo]]', '[[They would have saved money|Habrían ahorrado dinero]]', '[[They would have stayed home|Habrían permanecido en casa]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[If I had booked my flight earlier, I would have saved money|si hubiera reservado mi vuelo antes, habría ahorrado dinero]]".' },
  { question: '[[What|Qué]] [[feelings|sentimientos]] [[did the person have about the environment|tuvo la persona sobre el medio ambiente]]?', options: ['[[Delighted and grateful|Encantado y agradecido]]', '[[Overwhelmed and anxious|Abrumado y ansioso]]', '[[Relieved and confident|Aliviado y seguro]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[Having felt overwhelmed and anxious about the environment lately|habiendo sentido abrumado y ansioso por el medio ambiente últimamente]]".' },
  { question: '[[What|Qué]] [[did the person decide to do|decidió hacer la persona]]?', options: ['[[Travel more|Viajar más]]', '[[Recycle more and reduce waste|Reciclar más y reducir residuos]]', '[[Call less|Llamar menos]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I decided to recycle more and reduce my waste|decidí reciclar más y reducir mis residuos]]".' },
  { question: "[[What|Qué]] [[does the person say with \"It's time\"|dice la persona con \"It's time\"]]?", options: ["[[It's time to work|Ya es hora de trabajar]]", "[[It's time to call mother-in-law|Ya es hora de llamar a la suegra]]", "[[It's time to leave|Ya es hora de irse]]"], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[It\'s time I called my mother-in-law|ya es hora de llamar a mi suegra]]".' },
  { question: '[[How|Cómo]] [[does the person feel about their mother-in-law|cómo se siente la persona sobre su suegra]]?', options: ['[[Frustrated|Frustrado]]', '[[Grateful|Agradecido]]', '[[Anxious|Ansioso]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I feel grateful for her|me siento agradecido por ella]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]] [[of|del]] [[this text|este texto]]?', options: ['[[Only travel|Solo viajes]]', '[[Family, travel, feelings and environment|Familia, viajes, sentimientos y medio ambiente]]', '[[Only work|Solo trabajo]]'], correctAnswer: 1, explanation: '[[The text|El texto]] [[mixes|mezcla]] [[family|familia]], [[travel|viajes]], [[feelings|sentimientos]] [[and|y]] [[environment|medio ambiente]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in|en]] [[this text|este texto]]?', options: ['[[Siblings|Hermanos]], [[destination|destino]], [[recycle|reciclar]], [[climate change|cambio climático]]', '[[Weather|Tiempo]], [[food|comida]]', '[[Work|Trabajo]], [[education|educación]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[uses|usa]] [[vocabulary|vocabulario]] [[from|de]] [[units 6-9|unidades 6-9]].' },
  { question: '[[The text|El texto]] [[mentions|menciona]] [[climate change and pollution|cambio climático y contaminación]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[Climate change and pollution are real threats|el cambio climático y la contaminación son amenazas reales]]".' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[does "Having felt" use|usa "Having felt"]]?', options: ['[[Having + past participle|Having + participio pasado]]', '[[Present participle|Participio presente]]', '[[Wish + past|Wish + pasado]]'], correctAnswer: 0, explanation: '[[Having + past participle|Having + participio pasado]] [[for completed action before main clause|para acción completada antes de la cláusula principal]].' },
  { question: '[[The mother-in-law|La suegra]] [[gets on with everyone|se lleva bien con todos]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[she gets on with everyone|ella se lleva bien con todos]]".' },
  { question: '[[What|Qué]] [[must we do|debemos hacer]] [[according to the text|según el texto]]?', options: ['[[Use more fossil fuels|Usar más combustibles fósiles]]', '[[Switch to renewable energy and protect the planet|Cambiar a energía renovable y proteger el planeta]]', '[[Increase pollution|Aumentar la contaminación]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[we must switch to renewable energy and protect our planet|debemos cambiar a energía renovable y proteger nuestro planeta]]".' },
  { question: '[[The text|El texto]] [[uses|usa]] [[mixed conditionals|condicionales mixtos]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[If I had booked... I would have saved|Si hubiera reservado... habría ahorrado]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the person|la persona]]?', options: ['[[They don\'t care about family or environment|No les importa la familia ni el medio ambiente]]', '[[They value family, travel and environment|Valoran la familia, los viajes y el medio ambiente]]', '[[They never travel|Nunca viajan]]'], correctAnswer: 1, explanation: '[[They wish for family time|Desean tiempo familiar]], [[would rather visit family|prefieren visitar familia]], [[recycle and reduce waste|reciclan y reducen residuos]].' },
  { question: '[[The person|La persona]] [[has a mother-in-law|tiene una suegra]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[my mother-in-law|mi suegra]]".' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[does "I wish I had" use|usa "I wish I had"]]?', options: ['[[Wish + past simple|Wish + pasado simple]]', '[[Wish + past perfect|Wish + pasado perfecto]]', '[[Would rather + infinitive|Would rather + infinitivo]]'], correctAnswer: 0, explanation: '[[Wish + past simple|Wish + pasado simple]] [[for present regrets|para arrepentimientos presentes]].' },
];

export const UNIT_10_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u10-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Repaso 6–9',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
