/**
 * Unidad 57 B2 — Lección 1: Gramática (Compound Words)
 * 18 ejercicios (B2: palabras compuestas) — Tema: Media Literacy & Critical Thinking
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Compound Words|Palabras compuestas]]';
const INSTRUCTIONS = 'Elige la palabra compuesta correcta.';

export const UNIT_57_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u57-l1-g1', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Ability to understand|Capacidad de entender]] [[and evaluate media|y evaluar los medios]]:', options: ['[[media literacy|alfabetización mediática]]', '[[media bias|sesgo mediático]]', '[[media coverage|cobertura mediática]]'], correctAnswer: 'media literacy', acceptableAnswers: ['media literacy'], explanation: '[[Compound: media + literacy|Compuesta: media + literacy]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Thinking carefully|Pensar cuidadosamente]] [[about information|sobre la información]] [[before accepting it|antes de aceptarla]]:', options: ['[[critical thinking|pensamiento crítico]]', '[[fake news|noticias falsas]]', '[[news cycle|ciclo de noticias]]'], correctAnswer: 0, explanation: '[[Compound: critical + thinking|Compuesta: critical + thinking]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g3', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[False or misleading|Falsa o engañosa]] [[information|información]] [[spread as news|difundida como noticia]]:', options: ['[[misinformation|desinformación]]', '[[disinformation|desinformación intencional]]', '[[fake news|noticias falsas]]'], correctAnswer: 'misinformation', acceptableAnswers: ['misinformation', 'fake news'], explanation: '[[Compound: mis- + information|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where information|Donde la información]] [[comes from|proviene]]:', options: ['[[news source|fuente de noticias]]', '[[headline|titular]]', '[[breaking news|última hora]]'], correctAnswer: 0, explanation: '[[Compound: news + source|Compuesta: news + source]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g5', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Checking if something|Comprobar si algo]] [[is true|es verdad]]:', options: ['[[fact-checking|verificación de hechos]]', '[[fact-finding|búsqueda de hechos]]', '[[fact-based|basado en hechos]]'], correctAnswer: 'fact-checking', acceptableAnswers: ['fact-checking'], explanation: '[[Compound: fact + checking|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Unfair preference|Preferencia injusta]] [[in reporting|en el reportaje]]:', options: ['[[media bias|sesgo mediático]]', '[[media literacy|alfabetización mediática]]', '[[media outlet|medio de comunicación]]'], correctAnswer: 0, explanation: '[[Compound: media + bias|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g7', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[News that appears|Noticias que aparecen]] [[at the top of a page|en la parte superior de una página]]:', options: ['[[headline|titular]]', '[[byline|línea de autor]]', '[[deadline|fecha límite]]'], correctAnswer: 'headline', acceptableAnswers: ['headline'], explanation: '[[Compound: head + line|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[News that is|Noticias que son]] [[just happening|que acaban de ocurrir]]:', options: ['[[breaking news|última hora]]', '[[fake news|noticias falsas]]', '[[news cycle|ciclo de noticias]]'], correctAnswer: 0, explanation: '[[Compound: breaking + news|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g9', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A newspaper or channel|Un periódico o canal]] [[that provides news|que proporciona noticias]]:', options: ['[[news outlet|medio de comunicación]]', '[[news source|fuente de noticias]]', '[[news feed|feed de noticias]]'], correctAnswer: 'news outlet', acceptableAnswers: ['news outlet'], explanation: '[[Compound: news + outlet|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How news|Cómo las noticias]] [[spreads and repeats|se difunden y repiten]] [[over time|con el tiempo]]:', options: ['[[news cycle|ciclo de noticias]]', '[[news story|noticia]]', '[[news report|reportaje]]'], correctAnswer: 0, explanation: '[[Compound: news + cycle|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g11', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Information|Información]] [[that supports|que apoya]] [[a claim|una afirmación]]:', options: ['[[evidence-based|basado en evidencia]]', '[[fact-based|basado en hechos]]', '[[source-based|basado en fuentes]]'], correctAnswer: 'evidence-based', acceptableAnswers: ['evidence-based', 'fact-based'], explanation: '[[Compound: evidence + based|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To spread|Difundir]] [[information widely|información ampliamente]] [[often quickly|a menudo rápidamente]]:', options: ['[[to go viral|volverse viral]]', '[[to share|compartir]]', '[[to post|publicar]]'], correctAnswer: 0, explanation: '[[Phrasal compound: go + viral|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g13', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A story|Una historia]] [[reported in the media|reportada en los medios]]:', options: ['[[news story|noticia]]', '[[cover story|historia de portada]]', '[[human interest story|historia de interés humano]]'], correctAnswer: 'news story', acceptableAnswers: ['news story'], explanation: '[[Compound: news + story|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To present|Presentar]] [[information|información]] [[in a biased way|de forma sesgada]]:', options: ['[[to spin|manipular/interpretar]]', '[[to report|reportar]]', '[[to verify|verificar]]'], correctAnswer: 0, explanation: '[[Spin = to present biased|Spin = presentar sesgado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g15', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much|Cuánto]] [[attention|atención]] [[the media gives|los medios dan]] [[to a topic|a un tema]]:', options: ['[[media coverage|cobertura mediática]]', '[[media attention|atención mediática]]', '[[media focus|enfoque mediático]]'], correctAnswer: 'media coverage', acceptableAnswers: ['media coverage'], explanation: '[[Compound: media + coverage|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To confirm|Confirmar]] [[that something|que algo]] [[is accurate|es preciso]]:', options: ['[[to verify|verificar]]', '[[to check|comprobar]]', '[[to confirm|confirmar]]'], correctAnswer: 0, explanation: '[[Verify = to confirm accuracy|Verify = confirmar precisión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g17', type: 'fill-blank', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The line|La línea]] ____ [[shows who wrote|que muestra quién escribió]] [[an article|un artículo]]:', options: ['[[byline|línea de autor]]', '[[headline|titular]]', '[[deadline|fecha límite]]'], correctAnswer: 'byline', acceptableAnswers: ['byline'], explanation: '[[Compound: by + line|Compuesta]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u57-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'media-communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Intentionally false|Intencionalmente falsa]] [[information|información]] [[spread to deceive|difundida para engañar]]:', options: ['[[disinformation|desinformación intencional]]', '[[misinformation|desinformación]]', '[[information|información]]'], correctAnswer: 0, explanation: '[[Dis- = intentionally|Dis- = intencionalmente]].' }] }, topicName: 'Grammar' },
];
