/**
 * Unidad 9 B2 — Lección 2: Vocabulario (Environment)
 * 18 ejercicios (B2: pollution, sustainability, recycle, etc.)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Environment|Medio ambiente]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_9_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u9-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Harmful substances in air, water or soil|Sustancias dañinas en aire, agua o suelo]]:', options: ['[[pollution|contaminación]]', '[[recycling|reciclaje]]', '[[conservation|conservación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Ability to maintain resources for future generations|Capacidad de mantener recursos para generaciones futuras]]:', options: ['[[sustainability|sostenibilidad]]', '[[pollution|contaminación]]', '[[waste|residuos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To process used materials for reuse|Procesar materiales usados para reutilizar]]:', options: ['[[recycle|reciclar]]', '[[pollute|contaminar]]', '[[waste|desperdiciar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Unwanted or unused material|Material no deseado o no usado]]:', options: ['[[waste|residuos]]', '[[recycling|reciclaje]]', '[[conservation|conservación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Protection of natural resources|Protección de recursos naturales]]:', options: ['[[conservation|conservación]]', '[[pollution|contaminación]]', '[[deforestation|deforestación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cutting down trees on a large scale|Talar árboles a gran escala]]:', options: ['[[deforestation|deforestación]]', '[[reforestation|reforestación]]', '[[conservation|conservación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Gases that trap heat in the atmosphere|Gases que atrapan calor en la atmósfera]]:', options: ['[[greenhouse gases|gases de efecto invernadero]]', '[[oxygen|oxígeno]]', '[[nitrogen|nitrógeno]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Long-term change in global temperatures|Cambio a largo plazo en temperaturas globales]]:', options: ['[[climate change|cambio climático]]', '[[weather|tiempo]]', '[[pollution|contaminación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Energy from natural sources that replenish|Energía de fuentes naturales que se reponen]]:', options: ['[[renewable energy|energía renovable]]', '[[fossil fuels|combustibles fósiles]]', '[[nuclear energy|energía nuclear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Coal, oil, natural gas|Carbón, petróleo, gas natural]]:', options: ['[[fossil fuels|combustibles fósiles]]', '[[renewable energy|energía renovable]]', '[[solar power|energía solar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use less of something|Usar menos de algo]]:', options: ['[[reduce|reducir]]', '[[reuse|reutilizar]]', '[[recycle|reciclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use something again|Usar algo de nuevo]]:', options: ['[[reuse|reutilizar]]', '[[reduce|reducir]]', '[[recycle|reciclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Danger of extinction|Peligro de extinción]]:', options: ['[[endangered|en peligro de extinción]]', '[[extinct|extinto]]', '[[rare|raro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[No longer existing|Que ya no existe]]:', options: ['[[extinct|extinto]]', '[[endangered|en peligro]]', '[[rare|raro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Contamination of environment by harmful substances|Contaminación del medio por sustancias dañinas]]:', options: ['[[pollution|contaminación]]', '[[conservation|conservación]]', '[[sustainability|sostenibilidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something dirty or harmful|Hacer algo sucio o dañino]]:', options: ['[[pollute|contaminar]]', '[[conserve|conservar]]', '[[recycle|reciclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To keep and protect from harm|Mantener y proteger del daño]]:', options: ['[[conserve|conservar]]', '[[pollute|contaminar]]', '[[waste|desperdiciar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Environment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The three Rs: reduce, reuse, ____|Las tres R: reducir, reutilizar, ____]]:', options: ['[[recycle|reciclar]]', '[[reject|rechazar]]', '[[remove|eliminar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
