/**
 * Unidad 19 B2 — Lección 2: Vocabulario (Sport)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Sport|Deporte]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con el deporte.';

export const UNIT_19_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u19-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who takes part in a competition|Persona que participa en una competición]]:', options: ['[[competitor|competidor]]', '[[spectator|espectador]]', '[[coach|entrenador]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Physical or mental strength to continue despite difficulty|Fuerza física o mental para continuar a pesar de la dificultad]]:', options: ['[[endurance|resistencia]]', '[[speed|velocidad]]', '[[agility|agilidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To prepare for a competition or event|Prepararse para una competición o evento]]:', options: ['[[train|entrenar]]', '[[compete|competir]]', '[[referee|arbitrar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[An injury to a joint caused by sudden twisting|Lesión en una articulación por torsión repentina]]:', options: ['[[sprain|esguince]]', '[[strain|distensión]]', '[[fracture|fractura]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who watches a sports event|Persona que ve un evento deportivo]]:', options: ['[[spectator|espectador]]', '[[player|jugador]]', '[[umpire|árbitro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ability to move quickly and easily|Capacidad de moverse rápido y con facilidad]]:', options: ['[[agility|agilidad]]', '[[strength|fuerza]]', '[[stamina|resistencia]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who trains athletes|Persona que entrena atletas]]:', options: ['[[coach|entrenador]]', '[[referee|árbitro]]', '[[captain|capitán]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To beat an opponent or record|Superar a un oponente o récord]]:', options: ['[[break|batir]]', '[[make|hacer]]', '[[set|establecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The best result ever achieved in a sport|Mejor resultado jamás logrado en un deporte]]:', options: ['[[record|récord]]', '[[score|puntuación]]', '[[trophy|trofeo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A period of rest between parts of a game|Período de descanso entre partes de un partido]]:', options: ['[[half-time|descanso]]', '[[time-out|tiempo muerto]]', '[[interval|intervalo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a record" → batir un récord|Colocación: "___ a record" → batir un récord]]', options: ['[[break|batir]]', '[[make|hacer]]', '[[set|establecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ fit" → estar en forma|Colocación: "___ fit" → estar en forma]]', options: ['[[keep|mantenerse]]', '[[get|ponerse]]', '[[stay|permanecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "___ the lead" → tomar la delantera|Expresión: "___ the lead" → tomar la delantera]]', options: ['[[take|tomar]]', '[[get|conseguir]]', '[[hold|mantener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a match" → ganar un partido|Colocación: "___ a match" → ganar un partido]]', options: ['[[win|ganar]]', '[[beat|vencer]]', '[[defeat|derrotar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Physical exercise to improve fitness|Ejercicio físico para mejorar la forma]]:', options: ['[[workout|entrenamiento]]', '[[warm-up|calentamiento]]', '[[cool-down|enfriamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "___ shape" → estar en forma|Expresión: "estar en ___" → estar en forma]]', options: ['[[good|buena]]', '[[bad|mala]]', '[[top|óptima]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ the odds" → vencer las probabilidades|Colocación: "___ the odds" → vencer las probabilidades]]', options: ['[[beat|vencer]]', '[[defy|desafiar]]', '[[overcome|superar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u19-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Sport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Exercises done before intense activity|Ejercicios hechos antes de actividad intensa]]:', options: ['[[warm-up|calentamiento]]', '[[cool-down|enfriamiento]]', '[[stretch|estiramiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
