/**
 * Unidad 19 B2 — Lección 3: Comprensión lectora (Literature & Books)
 * 13 preguntas (B2: recreado con texto y preguntas distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[The more|Cuanto más]] [[you read|lees]], [[the better|mejor]] [[you write|escribes]]; [[this|esto]] [[is|es]] [[one of the most basic|una de las más básicas]] [[principles|principios]] [[in literature|en la literatura]]. [[Writers|Los escritores]] [[who|que]] [[compete at the highest level|compiten al más alto nivel]] [[are often|son a menudo]] [[by far|con diferencia]] [[the most dedicated|los más dedicados]] [[people|personas]] [[you will meet|que conocerás]]. [[The novel|La novela]] [[is|es]] [[much harder|mucho más dura]] [[than|que]] [[a short story|un cuento corto]]; [[the extra length|la longitud extra]] [[makes|hace]] [[it|lo]] [[significantly more demanding|significativamente más exigente]]. [[Plot structure|La estructura de la trama]] [[is|es]] [[slightly more important|ligeramente más importante]] [[than|que]] [[style alone|el estilo solo]] [[for engaging readers|para enganchar a los lectores]]. [[The best|Los mejores]] [[editors|editores]] [[understand|entienden]] [[that|que]] [[the earlier|cuanto antes]] [[you start revising|empieces a revisar]], [[the better|mejor]] [[your final draft|tu borrador final]] [[will be|será]]. [[Rest|El descanso]] [[is|es]] [[just as important|tan importante]] [[as|como]] [[writing itself|la escritura en sí]]; [[without|sin]] [[enough breaks|suficientes descansos]], [[creativity|la creatividad]] [[declines|disminuye]].`;

const INSTRUCTIONS = 'Lee el texto sobre literatura y escritura. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[is one of the most basic principles|es uno de los principios más básicos]] [[in literature|en la literatura]]?', options: ['[[The more you read, the better you write|Cuanto más lees, mejor escribes]]', '[[Rest is unnecessary|El descanso es innecesario]]', '[[Style is everything|El estilo es todo]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[The more you read, the better you write|Cuanto más lees, mejor escribes]]".' },
  { question: '[[What|Qué]] [[are writers who compete at the highest level|son los escritores que compiten al más alto nivel]]?', options: ['[[By far the most dedicated people you will meet|Con diferencia las personas más dedicadas que conocerás]]', '[[Lazy|Perezosos]]', '[[Untalented|Sin talento]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[are often by far the most dedicated people|son a menudo con diferencia las personas más dedicadas]]".' },
  { question: '[[What|Qué]] [[is the novel compared to a short story|es la novela comparada con un cuento corto]]?', options: ['[[Much harder|Mucho más dura]]', '[[Easier|Más fácil]]', '[[The same|Igual]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[is much harder than a short story|es mucho más dura que un cuento corto]]".' },
  { question: '[[What|Qué]] [[is slightly more important than style alone|es ligeramente más importante que el estilo solo]] [[for engaging readers|para enganchar a los lectores]]?', options: ['[[Plot structure|La estructura de la trama]]', '[[Length|La longitud]]', '[[Imagery|La imaginería]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Plot structure is slightly more important than style alone|La estructura de la trama es ligeramente más importante que el estilo solo]]".' },
  { question: '[[What|Qué]] [[do the best editors understand|entienden los mejores editores]]?', options: ['[[The earlier you start revising, the better your final draft will be|Cuanto antes empieces a revisar, mejor será tu borrador final]]', '[[You should never revise|Nunca debes revisar]]', '[[Only style matters|Solo importa el estilo]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the earlier you start revising, the better your final draft will be|cuanto antes empieces a revisar, mejor será tu borrador final]]".' },
  { question: '[[What|Qué]] [[is just as important as writing|es tan importante como la escritura]]?', options: ['[[Rest|El descanso]]', '[[Publishing|Publicar]]', '[[Marketing|El marketing]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Rest is just as important as writing itself|El descanso es tan importante como la escritura en sí]]".' },
  { question: '[[What|Qué]] [[happens without enough breaks|qué pasa sin suficientes descansos]]?', options: ['[[Creativity declines|La creatividad disminuye]]', '[[Creativity improves|La creatividad mejora]]', '[[Nothing changes|Nada cambia]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[without enough breaks, creativity declines|sin suficientes descansos, la creatividad disminuye]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[style is more important than plot for engaging readers|el estilo es más importante que la trama para enganchar a los lectores]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[Plot structure is slightly more important than style alone|La estructura de la trama es ligeramente más importante que el estilo solo]]".' },
  { question: '[[According to the text|Según el texto]], [[rest is less important than writing|el descanso es menos importante que la escritura]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[Rest is just as important as writing|El descanso es tan importante como la escritura]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the text|del texto]]?', options: ['[[Reading, dedication, and rest are key; the more you prepare, the better; balance matters|Lectura, dedicación y descanso son clave; cuanto más te preparas, mejor; el equilibrio importa]]', '[[Only novelists matter|Solo importan los novelistas]]', '[[Rest is unnecessary|El descanso es innecesario]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[covers|abarca]] [[reading|lectura]], [[dedication|dedicación]], [[comparisons|comparaciones]] [[and|y]] [[rest|descanso]].' },
  { question: '[[Which structure|Qué estructura]] [[uses "the more... the more"|usa "the more... the more"]] [[in the text|en el texto]]?', options: ['[[The more you read, the better you write|Cuanto más lees, mejor escribes]]', '[[By far the most dedicated|Con diferencia los más dedicados]]', '[[Much harder than|Mucho más duro que]]'], correctAnswer: 0, explanation: '[[The more... the more|Cuanto más... más]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[read|leer]], [[write|escribir]], [[plot|trama]], [[creativity|creatividad]]', '[[computer|ordenador]], [[software|software]], [[internet|internet]]', '[[profit|beneficio]], [[debt|deuda]], [[budget|presupuesto]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[literature vocabulary|vocabulario literario]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[success in literature|el éxito en la literatura]]?', options: ['[[It requires reading, dedication, and balanced rest|Requiere lectura, dedicación y descanso equilibrado]]', '[[Only talent matters|Solo importa el talento]]', '[[Rest is harmful|El descanso es perjudicial]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[emphasizes|enfatiza]] [[reading|lectura]], [[dedication|dedicación]] [[and|y]] [[rest|descanso]].' },
];

export const UNIT_19_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u19-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Literature & Books',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
