/**
 * Unidad 26 B2 — Lección 6: Expresión escrita (Sustainability & Eco-living)
 * 18 ejercicios (B2: phrasal verbs GET, GIVE, GO)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_26_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u26-l6-w1', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo un período difícil que atravesaste (go through) en tu transición ecológica. Usa go through, get over, give up.', prompt: '[[Describe a difficult period you went through in your eco transition. Use: go through, get over, give up.|Describe un período difícil que atravesaste en tu transición ecológica. Usa: go through, get over, give up.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto: get over, give up, go through.', questions: [{ question: '[[It took her months|Le llevó meses]] ____ [[her old habits|superar sus viejos hábitos]] [[of single-use plastic|de plástico de un solo uso]].', options: ['[[to get over|superar]]', '[[to get through|terminar]]', '[[to get along|llevarse bien]]'], correctAnswer: 'to get over', acceptableAnswers: ['to get over'], explanation: '[[Get over = recover from|Get over = recuperarse de]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w3', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando give up o get through.', prompt: '[[He stopped using plastic|Dejó de usar plástico]]. [[She finished the zero-waste transition|Terminó la transición al cero residuos]].', expressionHint: '[[Usa: "He gave up on plastic" y "She got through the zero-waste transition"|Usa: "He gave up on plastic" y "She got through the zero-waste transition"]]', targetLength: '1-2 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w4', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con get along y otra con go through.', prompt: '[[Write two sentences: one with get along (have a good relationship) and one with go through (experience).|Escribe dos oraciones: una con get along (llevarse bien) y otra con go through (experimentar).]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[Don\'t|No]] ____ [[now|ahora]] — [[you\'re|estás]] [[so close|tan cerca]] [[to|de]] [[reducing your carbon footprint|reducir tu huella de carbono]]!', options: ['[[give up|te rindas]]', '[[give in|cedas]]', '[[give away|regales]]'], correctAnswer: 'give up', acceptableAnswers: ['give up'], explanation: '[[Give up = stop trying|Give up = rendirse]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w6', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre una iniciativa ecológica que se abandonó o que continuó a pesar de las dificultades. Usa give up, get through, go through.', prompt: '[[Describe an eco initiative that was abandoned or that carried on despite difficulties. Use: give up, get through, go through.|Describe una iniciativa ecológica que fue abandonada o que continuó a pesar de las dificultades. Usa: give up, get through, go through.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w7', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando phrasal verbs.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. I went through ____ when...|1. Atravesé ____ cuando...]]\n[[2. She gave up ____ because ____|2. Ella dejó ____ porque ____]]\n[[3. We got through ____ last week.|3. Superamos ____ la semana pasada.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "get over" o "get through".', questions: [{ question: '[[She|Ella]] ____ [[her fear|su miedo]] [[of change|al cambio]] [[after|después de]] [[trying sustainable living|probar la vida sostenible]].', options: ['[[got over|superó]]', '[[got through|terminó]]', '[[got along|llevó bien]]'], correctAnswer: 'got over', acceptableAnswers: ['got over'], explanation: '[[Get over = overcome|Get over = superar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w9', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre cómo superar el miedo al cambio en sostenibilidad.', prompt: '[[Write an introduction to an article about overcoming fear of change in sustainability. Use at least one phrasal verb (get over, give up, go through, get through).|Escribe la introducción de un artículo sobre cómo superar el miedo al cambio en sostenibilidad. Usa al menos un phrasal verb.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w10', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando qué puede requerir llevarse bien (get along) con la familia en hábitos ecológicos.', prompt: '[[Explain what getting along with your family on eco habits can require. Use get along and go through.|Explica qué puede requerir llevarse bien con la familia en hábitos ecológicos. Usa get along y go through.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb adecuado.', questions: [{ question: '[[The recycling workshop|El taller de reciclaje]] ____ [[until|hasta]] [[late|tarde]] [[last night|anoche]] — [[we had|teníamos]] [[a lot to discuss|mucho que discutir]].', options: ['[[went on|continuó]]', '[[went through|atravesó]]', '[[went off|explotó]]'], correctAnswer: 'went on', acceptableAnswers: ['went on'], explanation: '[[Go on = continue|Go on = continuar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w12', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte estas frases en una usando give in.', prompt: '[[After hours of debating|Después de horas debatiendo]]. [[They approved the green project|Aprobaron el proyecto verde]].', expressionHint: '[[Usa: "After hours of debating, they gave in and approved the green project"|Usa: "After hours of debating, they gave in and approved the green project"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w13', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con phrasal verbs (una con give up, otra con get through y otra con go through).', prompt: '[[Write three sentences with phrasal verbs:|Escribe tres oraciones con phrasal verbs:]]\n[[- one with "give up"|- una con "give up"]]\n[[- one with "get through"|- una con "get through"]]\n[[- one with "go through"|- una con "go through"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "get along" o "go off".', questions: [{ question: '[[The eco workshop|El taller ecológico]] ____ [[well|bien]] — [[they|ellos]] [[learned a lot|aprendieron mucho]] [[about composting|sobre compostaje]].', options: ['[[went off|salió bien]]', '[[went on|continuó]]', '[[got along|llevó bien]]'], correctAnswer: 'went off', acceptableAnswers: ['went off'], explanation: '[[Go off = happen successfully|Go off = salir bien (evento)]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w15', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre un desafío en sostenibilidad que superaste y qué aprendiste.', prompt: '[[Describe a sustainability challenge you overcame and what you learned. Use: go through, get over, give up, get through.|Describe un desafío en sostenibilidad que superaste y qué aprendiste. Usa: go through, get over, give up, get through.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w16', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando cómo superar el miedo al cambio en sostenibilidad.', prompt: '[[Give advice on how to get through fear of change in sustainability. Use get over and give up.|Da consejos sobre cómo superar el miedo al cambio en sostenibilidad. Usa get over y give up.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[We|Nosotros]] ____ [[well|bien]] [[with|con]] [[our eco-friendly neighbours|nuestros vecinos ecológicos]] — [[they\'re|son]] [[very supportive|muy solidarios]].', options: ['[[get along|nos llevamos]]', '[[get over|nos recuperamos]]', '[[get through|terminamos]]'], correctAnswer: 'get along', acceptableAnswers: ['get along'], explanation: '[[Get along = have a good relationship|Get along = llevarse bien]].' }] }, topicName: 'Writing' },
  { id: 'b2-u26-l6-w18', type: 'writing', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué vale la pena no rendirse cuando las cosas son difíciles en sostenibilidad.', prompt: '[[Write a short conclusion explaining why it is worth not giving up when things are difficult in sustainability. Use give up and get through.|Escribe una breve conclusión explicando por qué vale la pena no rendirse cuando las cosas son difíciles en sostenibilidad. Usa give up y get through.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
