/**
 * Unidad 8 B2 — Lección 6: Expresión escrita (Architecture & Design)
 * 18 ejercicios (B2: Mixed conditionals, fill-blank + writing prompts)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_8_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u8-l6-w1', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2-3 frases sobre un proyecto usando mixed conditional (If I had..., I would...).', expressionHint: 'Puedes usar: [[If I had booked|Si hubiera reservado]]..., [[I would have saved|habría ahorrado]]..., [[destination|destino]], [[blueprint|plano]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[I|yo]] ____[[harder|más duro]] [[at|en]] [[architecture school|la escuela de arquitectura]], [[I|yo]] ____[[a better job now|un mejor trabajo ahora]].', options: ['[[had worked|hubiera trabajado]]', '[[would have|tendría]]'], correctAnswer: 'had worked', acceptableAnswers: ['had worked'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would + infinitive|pasado perfecto + would + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w3', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre una visita a obra que tuviste y qué habrías hecho diferente.', expressionHint: 'Usa: [[If I had|Si hubiera]]..., [[would have|habría]]..., [[blueprint|plano]], [[check in|registro]], [[facade|fachada]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w4', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con third conditional y otra con mixed conditional sobre proyectos.', expressionHint: '[[If I had booked|Si hubiera reservado]]... / [[If I had left|Si hubiera salido]]... [[I would be|estaría]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[she|ella]] ____[[the train|el tren]] [[yesterday|ayer]], [[she|ella]] ____[[here now|aquí ahora]] [[inspecting|inspeccionando]] [[the facade|la fachada]].', options: ['[[had caught|hubiera cogido]]', '[[would be|estaría]]'], correctAnswer: 'had caught', acceptableAnswers: ['had caught'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would + infinitive|pasado perfecto + would + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w6', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre consejos para visitas a obra (booking, check-in, portfolio).', expressionHint: 'Puedes usar: [[book early|reservar pronto]], [[check in online|registrarse en línea]], [[portfolio|portafolio]], [[set off early|salir temprano]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w7', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con "If I had known..., I would have..." sobre un proyecto.', expressionHint: '[[If I had known|Si hubiera sabido]]... [[I would have|habría]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[we|nosotros]] ____[[earlier|antes]], [[we|nosotros]] ____[[the groundbreaking|la inauguración de obras]].', options: ['[[had left|hubiéramos salido]]', '[[would not have missed|no habríamos perdido]]'], correctAnswer: 'had left', acceptableAnswers: ['had left'], explanation: '[[Third conditional|Tercer condicional]]: [[past perfect + would have + past participle|pasado perfecto + would have + participio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w9', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre tu edificio o landmark favorito y por qué.', expressionHint: 'Puedes usar: [[landmark|monumento]], [[facade|fachada]], [[blueprint|plano]], [[structure|estructura]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w10', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases usando vocabulario de arquitectura (blueprint, check in, destination, facade).', expressionHint: '[[I had to|Tuve que]]... [[My destination was|Mi destino era]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[I|yo]] ____[[my flight|mi vuelo]] [[earlier|antes]], [[I|yo]] ____[[a lot of money|mucho dinero]] [[on the project|en el proyecto]].', options: ['[[had booked|hubiera reservado]]', '[[would have saved|habría ahorrado]]'], correctAnswer: 'had booked', acceptableAnswers: ['had booked'], explanation: '[[Third conditional|Tercer condicional]]: [[past perfect + would have + past participle|pasado perfecto + would have + participio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w12', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre una vez que tuviste un retraso o cancelación en una visita a obra.', expressionHint: 'Puedes usar: [[delay|retraso]], [[call off|cancelar]], [[layover|pausa]], [[would have|habría]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w13', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con mixed conditional (past → present) sobre un proyecto.', expressionHint: '[[If I had|Si hubiera]] [past participle]..., [[I would be|estaría]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[they|ellos]] ____[[the offer|la oferta]] [[last year|el año pasado]], [[they|ellos]] ____[[abroad now|en el extranjero ahora]] [[designing|diseñando]] [[landmarks|monumentos]].', options: ['[[had accepted|hubieran aceptado]]', '[[would be living|estarían viviendo]]'], correctAnswer: 'had accepted', acceptableAnswers: ['had accepted'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w15', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre la importancia de planificar una visita a obra con antelación.', expressionHint: 'Puedes usar: [[booking|reserva]], [[blueprint|plano]], [[planning permission|permiso de obras]], [[specification|especificación]], [[timeline|cronograma]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w16', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "set off" y otra con "check in".', expressionHint: '[[I set off|Partí]]... / [[I had to check in|Tuve que registrarme]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[I|yo]] ____[[about|sobre]] [[the delay|el retraso]] [[earlier|antes]], [[I|yo]] ____[[it|ello]] [[by now|para ahora]].', options: ['[[had known|hubiera sabido]]', '[[would have fixed|habría arreglado]]'], correctAnswer: 'had known', acceptableAnswers: ['had known'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Writing' },
  { id: 'b2-u8-l6-w18', type: 'writing', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre una visita a obra ideal usando mixed conditionals y vocabulario de arquitectura.', expressionHint: 'Puedes usar: [[If I had|Si hubiera]]..., [[would have|habría]]..., [[destination|destino]], [[facade|fachada]], [[blueprint|plano]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
