/**
 * Unidad 29 B2 — Lección 6: Expresión escrita (Psychology & Mind)
 * 18 ejercicios (B2: colocaciones adjetivo+sustantivo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_29_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u29-l6-w1', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo un momento con presión intensa. Usa heavy pressure, strong anxiety, great progress.', prompt: '[[Describe a moment with heavy pressure and what you did. Use: heavy pressure, strong anxiety, great progress.|Describe un momento con presión intensa y qué hiciste. Usa: heavy pressure, strong anxiety, great progress.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el adjetivo correcto: strong, heavy, great.', questions: [{ question: '[[She felt|Sintió]] ____ [[anxiety|ansiedad]] [[before the presentation|antes de la presentación]] — [[she couldn\'t sleep|no podía dormir]].', options: ['[[strong|fuerte]]', '[[heavy|pesada]]', '[[deep|profunda]]'], correctAnswer: 'strong', acceptableAnswers: ['strong'], explanation: '[[Strong anxiety = intense anxiety|Strong anxiety = ansiedad fuerte]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w3', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando heavy pressure o strong anxiety.', prompt: '[[The session was cancelled|La sesión fue cancelada]]. [[There was intense pressure|Hubo presión intensa]].', expressionHint: '[[Usa: "We had to cancel the session because of heavy pressure"|Usa: "We had to cancel the session because of heavy pressure"]]', targetLength: '1-2 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w4', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con stunning results y otra con lively discussion.', prompt: '[[Write two sentences: one with stunning results and one with lively discussion.|Escribe dos oraciones: una con stunning results y otra con lively discussion.]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el adjetivo correcto.', questions: [{ question: '[[There was|Hubo]] ____ [[pressure|presión]] [[at work|en el trabajo]] [[this month|este mes]] — [[everyone felt stressed|todos se sintieron estresados]].', options: ['[[heavy|densa]]', '[[strong|fuerte]]', '[[big|grande]]'], correctAnswer: 'heavy', acceptableAnswers: ['heavy'], explanation: '[[Heavy pressure = intense pressure|Heavy pressure = presión intensa]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w6', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre algo que tuvo un impacto profundo (deep impact) en tu mentalidad.', prompt: '[[Describe something that had a deep impact on your mindset. Use: deep impact, great relief, strong belief.|Describe algo que tuvo un impacto profundo en tu mentalidad. Usa: deep impact, great relief, strong belief.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w7', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando colocaciones.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. We had to cancel ____ because of heavy ____|1. Tuvimos que cancelar ____ debido a ____ intensa]]\n[[2. The therapy had ____ results of ____|2. La terapia tuvo ____ resultados de ____]]\n[[3. We had a ____ discussion about ____|3. Tuvimos una ____ discusión sobre ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "great" o "high".', questions: [{ question: '[[He made|Hizo]] ____ [[progress|progreso]] [[in therapy|en terapia]] [[this year|este año]] — [[his mindset|su mentalidad]] [[has improved a lot|ha mejorado mucho]].', options: ['[[great|gran]]', '[[heavy|pesado]]', '[[strong|fuerte]]'], correctAnswer: 'great', acceptableAnswers: ['great'], explanation: '[[Great progress = significant progress|Great progress = gran progreso]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w9', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre la importancia de la salud mental.', prompt: '[[Write an introduction to an article about the importance of mental health. Use at least one collocation (strong anxiety, heavy pressure, great progress).|Escribe la introducción de un artículo sobre la importancia de la salud mental. Usa al menos una colocación.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w10', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando qué puede requerir hacer gran progreso (great progress) en terapia.', prompt: '[[Explain what making great progress in therapy can require. Use great progress and great interest.|Explica qué puede requerir hacer gran progreso en terapia. Usa great progress y great interest.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el adjetivo adecuado.', questions: [{ question: '[[She felt|Sintió]] ____ [[relief|alivio]] [[when|cuando]] [[she heard|oyó]] [[that the therapy was working|que la terapia funcionaba]].', options: ['[[great|gran]]', '[[heavy|pesado]]', '[[strong|fuerte]]'], correctAnswer: 'great', acceptableAnswers: ['great'], explanation: '[[Great relief = strong relief|Great relief = gran alivio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w12', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte estas frases en una usando stunning results.', prompt: '[[The therapy had|La terapia tuvo]] [[impressive results|resultados impresionantes]]. [[She felt much better|Se sintió mucho mejor]].', expressionHint: '[[Usa: "The therapy had stunning results — she felt much better"|Usa: "The therapy had stunning results — she felt much better"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w13', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con colocaciones (una con heavy pressure, otra con strong anxiety y otra con great progress).', prompt: '[[Write three sentences with collocations:|Escribe tres oraciones con colocaciones:]]\n[[- one with "heavy pressure"|- una con "heavy pressure"]]\n[[- one with "strong anxiety"|- una con "strong anxiety"]]\n[[- one with "great progress"|- una con "great progress"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "deep" o "great".', questions: [{ question: '[[The book had|El libro tuvo]] ____ [[impact|impacto]] [[on my mindset|en mi mentalidad]] — [[I couldn\'t stop thinking about it|no podía dejar de pensar en él]].', options: ['[[a deep|un profundo]]', '[[a heavy|un pesado]]', '[[a strong|un fuerte]]'], correctAnswer: 'a deep', acceptableAnswers: ['a deep'], explanation: '[[Deep impact = profound impact|Deep impact = impacto profundo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w15', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre un momento con resultados impresionantes en tu bienestar mental.', prompt: '[[Describe a moment with stunning results in your mental wellbeing. Use: stunning results, lively discussion, great interest, heavy pressure, strong anxiety.|Describe un momento con resultados impresionantes en tu bienestar mental. Usa: stunning results, lively discussion, great interest, heavy pressure, strong anxiety.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w16', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando cómo manejar la presión intensa en inglés.', prompt: '[[Give advice on how to handle heavy pressure in English. Use heavy pressure and strong anxiety.|Da consejos sobre cómo manejar la presión intensa en inglés. Usa heavy pressure y strong anxiety.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el adjetivo correcto.', questions: [{ question: '[[We had|Tuvimos]] ____ [[discussion|discusión]] [[about|sobre]] [[mental health|salud mental]] [[yesterday|ayer]] — [[everyone|todos]] [[shared their views|compartieron sus opiniones]].', options: ['[[a lively|una animada]]', '[[a heavy|una pesada]]', '[[a strong|una fuerte]]'], correctAnswer: 'a lively', acceptableAnswers: ['a lively'], explanation: '[[Lively discussion = animated discussion|Lively discussion = discusión animada]].' }] }, topicName: 'Writing' },
  { id: 'b2-u29-l6-w18', type: 'writing', level: 'B2', topic: 'Psychology & Mind', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué vale la pena aprender colocaciones de psicología.', prompt: '[[Write a short conclusion explaining why it is worth learning psychology collocations. Use great progress and strong belief.|Escribe una breve conclusión explicando por qué vale la pena aprender colocaciones de psicología. Usa great progress y strong belief.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
