/**
 * Unidad 48 B2 — Lección 1: Gramática (Reporting Verbs)
 * 18 ejercicios (B2: verbos de reporte) — Tema: Innovation in Teaching
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Reporting Verbs|Verbos de reporte]]';
const INSTRUCTIONS = 'Elige la forma correcta del verbo de reporte.';

export const UNIT_48_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u48-l1-g1', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[going|ir]] [[to the cinema|al cine]].', options: ['[[suggested|sugirió]]', '[[suggest|sugiere]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + gerund|Suggest + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[that we stay|que nos quedemos]].', options: ['[[insisted|insistió]]', '[[insist|insiste]]', '[[insisting|insistiendo]]'], correctAnswer: 0, explanation: '[[Insist + that + subjunctive|Insist + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g3', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The teacher|El profesor]] ____ [[using|usar]] [[more technology|más tecnología]] [[in class|en clase]].', options: ['[[recommended|recomendó]]', '[[recommend|recomienda]]', '[[recommending|recomendando]]'], correctAnswer: 'recommended', acceptableAnswers: ['recommended'], explanation: '[[Recommend + gerund|Recommend + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[him|le]] ____ [[to apply|aplicar]] [[for the course|para el curso]].', options: ['[[urged|urgió]] ... [[to apply|aplicar]]', '[[urged|urgió]] ... [[applying|aplicando]]', '[[urge|urge]] ... [[apply|aplicar]]'], correctAnswer: 0, explanation: '[[Urge sb to do|Urge + objeto + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g5', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[taking|tomar]] [[a break|un descanso]].', options: ['[[suggested|sugirió]]', '[[suggest|sugiere]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + gerund|Suggest + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[that I|que yo]] ____ [[a doctor|un médico]].', options: ['[[recommended|recomendó]] ... [[see|vea]]', '[[recommended|recomendó]] ... [[saw|vio]]', '[[recommended|recomendó]] ... [[to see|ver]]'], correctAnswer: 0, explanation: '[[Recommend + that + subjunctive|Recommend + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g7', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[us|nos]] ____ [[to reconsider|reconsiderar]] [[the offer|la oferta]].', options: ['[[urged|urgieron]]', '[[urge|urge]]', '[[urging|urgiendo]]'], correctAnswer: 'urged', acceptableAnswers: ['urged'], explanation: '[[Urge sb to do|Urge + objeto + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[on|en]] [[our|nuestro]] ____ [[longer|más tiempo]].', options: ['[[insisted|insistió]] ... [[staying|quedarnos]]', '[[insisted|insistió]] ... [[stay|quedarnos]]', '[[insist|insiste]] ... [[staying|quedarnos]]'], correctAnswer: 0, explanation: '[[Insist on + gerund|Insist on + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g9', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[that we|que nosotros]] ____ [[start|empezar]] [[early|temprano]].', options: ['[[suggested|sugerí]]', '[[suggest|sugiero]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + that + subjunctive|Suggest + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The expert|El experto]] ____ [[trying|probar]] [[different methods|diferentes métodos]].', options: ['[[recommended|recomendó]]', '[[recommend|recomienda]]', '[[recommending|recomendando]]'], correctAnswer: 0, explanation: '[[Recommend + gerund|Recommend + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g11', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[that he|que él]] ____ [[apologise|disculparse]].', options: ['[[insisted|insistió]]', '[[insist|insiste]]', '[[insisting|insistiendo]]'], correctAnswer: 'insisted', acceptableAnswers: ['insisted'], explanation: '[[Insist + that + subjunctive|Insist + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The doctor|El doctor]] ____ [[her|le]] ____ [[to rest|descansar]] [[more|más]].', options: ['[[urged|urgió]] ... [[to rest|descansar]]', '[[urged|urgió]] ... [[resting|descansando]]', '[[urge|urge]] ... [[rest|descansar]]'], correctAnswer: 0, explanation: '[[Urge sb to do|Urge + objeto + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g13', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[that we|que nosotros]] ____ [[postpone|pospongamos]] [[the meeting|la reunión]].', options: ['[[suggested|sugerí]]', '[[suggest|sugiero]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + that + subjunctive|Suggest + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[reading|leer]] [[the book|el libro]] [[before|antes de]] [[the seminar|el seminario]].', options: ['[[recommended|recomendó]]', '[[recommend|recomienda]]', '[[recommending|recomendando]]'], correctAnswer: 0, explanation: '[[Recommend + gerund|Recommend + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g15', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[that we|que nosotros]] ____ [[not leave|no salir]] [[yet|todavía]].', options: ['[[insisted|insistió]]', '[[insist|insiste]]', '[[insisting|insistiendo]]'], correctAnswer: 'insisted', acceptableAnswers: ['insisted'], explanation: '[[Insist + that + subjunctive|Insist + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The advisor|El asesor]] ____ [[students|a los estudiantes]] ____ [[to attend|asistir]] [[the workshop|al taller]].', options: ['[[urged|urgió]] ... [[to attend|asistir]]', '[[urged|urgió]] ... [[attending|asistiendo]]', '[[urge|urge]] ... [[attend|asistir]]'], correctAnswer: 0, explanation: '[[Urge sb to do|Urge + objeto + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g17', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[that he|que él]] ____ [[try|intentar]] [[again|de nuevo]].', options: ['[[suggested|sugirió]]', '[[suggest|sugiere]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + that + subjunctive|Suggest + that + subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u48-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[that I|que yo]] ____ [[the truth|la verdad]].', options: ['[[insisted|insistió]] ... [[tell|dijera]]', '[[insisted|insistió]] ... [[told|dijo]]', '[[insist|insiste]] ... [[tell|decir]]'], correctAnswer: 0, explanation: '[[Insist + that + subjunctive|Insist + that + subjuntivo]].' }] }, topicName: 'Grammar' },
];
