/**
 * Unidad 12 B2 — Lección 3: Comprensión lectora (Gardening & Plants)
 * 13 preguntas (B2: Gardening & Plants)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Community gardens|Los jardines comunitarios]] [[which|que]] [[provide|proporcionan]] [[green spaces|espacios verdes]] [[in cities|en ciudades]] [[have become|se han vuelto]] [[increasingly popular|cada vez más populares]] [[in urban areas|en zonas urbanas]]. [[The concept|El concepto]], [[which|que]] [[used to be|solía ser]] [[seen as a hobby|visto como un hobby]], [[now attracts|ahora atrae]] [[thousands of volunteers|miles de voluntarios]] [[who|que]] [[want|quieren]] [[to grow|cultivar]] [[their own food|su propia comida]] [[while improving|mientras mejoran]] [[the environment|el medio ambiente]]. [[A recent project|Un proyecto reciente]] [[launched|lanzado]] [[in the city centre|en el centro de la ciudad]] [[shows|muestra]] [[native plants|plantas nativas]] [[that|que]] [[few residents|pocos residentes]] [[had ever seen|habían visto alguna vez]]. [[The team|El equipo]], [[which|que]] [[spent two years|pasó dos años]] [[preparing the soil|preparando la tierra]], [[captured|capturó]] [[interest|interés]] [[from|de]] [[locals|vecinos]] [[that|que]] [[had never gardened before|nunca habían jardineado antes]]. [[The head gardener|El jardinero jefe]], [[whose expertise|cuya experiencia]] [[is recognised citywide|es reconocida en toda la ciudad]], [[adds|añade]] [[credibility|credibilidad]] [[to the project|al proyecto]]. [[Volunteers|Los voluntarios]] [[who|que]] [[have joined|se han unido]] [[the scheme|el esquema]] [[say|dicen]] [[that|que]] [[it has changed|ha cambiado]] [[their view|su visión]] [[of|de]] [[urban life|vida urbana]].`;

const INSTRUCTIONS = 'Lee el texto sobre jardines comunitarios. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[has become popular|se ha vuelto popular]] [[in urban areas|en zonas urbanas]]?', options: ['[[Community gardens providing green spaces|Jardines comunitarios que proporcionan espacios verdes]]', '[[Shopping centres|Centros comerciales]]', '[[Sports events|Eventos deportivos]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Community gardens which provide green spaces have become increasingly popular|los jardines comunitarios que proporcionan espacios verdes se han vuelto cada vez más populares]]".' },
  { question: '[[How|Cómo]] [[was the concept seen before|se veía el concepto antes]]?', options: ['[[As a hobby|Como un hobby]]', '[[As essential|Como esencial]]', '[[As professional|Como profesional]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[which used to be seen as a hobby|que solía ser visto como un hobby]]".' },
  { question: '[[Where|Dónde]] [[was the recent project launched|se lanzó el proyecto reciente]]?', options: ['[[In the city centre|En el centro de la ciudad]]', '[[In the countryside|En el campo]]', '[[In the suburbs|En las afueras]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[A recent project launched in the city centre|un proyecto reciente lanzado en el centro de la ciudad]]".' },
  { question: '[[What|Qué]] [[does the project show|muestra el proyecto]]?', options: ['[[Native plants that few residents had seen|Plantas nativas que pocos residentes habían visto]]', '[[City life|Vida urbana]]', '[[Historical events|Eventos históricos]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[shows native plants that few residents had ever seen|muestra plantas nativas que pocos residentes habían visto]]".' },
  { question: '[[How long|Cuánto tiempo]] [[did the team spend|pasó el equipo]] [[preparing the soil|preparando la tierra]]?', options: ['[[Two years|Dos años]]', '[[Six months|Seis meses]]', '[[One year|Un año]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[The team, which spent two years preparing the soil|el equipo, que pasó dos años preparando la tierra]]".' },
  { question: '[[What|Qué]] [[did the team capture|capturó el equipo]]?', options: ['[[Interest from locals who had never gardened before|Interés de vecinos que nunca habían jardineado]]', '[[Interviews with celebrities|Entrevistas con famosos]]', '[[Music performances|Actuaciones musicales]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[captured interest from locals that had never gardened before|capturó interés de vecinos que nunca habían jardineado antes]]".' },
  { question: '[[What|Qué]] [[do volunteers say|dicen los voluntarios]]?', options: ['[[The scheme has changed their view of urban life|El esquema ha cambiado su visión de la vida urbana]]', '[[The scheme was too long|El esquema era demasiado largo]]', '[[The scheme was boring|El esquema era aburrido]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[it has changed their view of urban life|ha cambiado su visión de la vida urbana]]".' },
  { question: '[[The head gardener|El jardinero jefe]] [[has expertise|tiene experiencia]] [[recognised citywide|reconocida en toda la ciudad]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 0, explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[whose expertise is recognised citywide|cuya experiencia es reconocida en toda la ciudad]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the text|del texto]]?', options: ['[[Community gardens have evolved and can change how we see urban life|Los jardines comunitarios han evolucionado y pueden cambiar cómo vemos la vida urbana]]', '[[Gardening is only for professionals|La jardinería es solo para profesionales]]', '[[Cities have no space for gardens|Las ciudades no tienen espacio para jardines]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[describes|describe]] [[the rise of community gardens|el auge de los jardines comunitarios]] [[and their impact|y su impacto]].' },
  { question: '[[Which reduced relative clause|Qué cláusula de relativo reducida]] [[appears in the text|aparece en el texto]]?', options: ['[[launched in the city centre|lanzado en el centro de la ciudad]]', '[[which provide green spaces|que proporcionan espacios verdes]]', '[[whose expertise is recognised|cuya experiencia es reconocida]]'], correctAnswer: 0, explanation: '[[Reduced form|Forma reducida]] [[of "which was launched"|de "which was launched"]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[community gardens|jardines comunitarios]], [[native plants|plantas nativas]], [[soil|tierra]], [[volunteers|voluntarios]]', '[[salary|salario]], [[budget|presupuesto]], [[profit|beneficio]]', '[[airport|aeropuerto]], [[flight|vuelo]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[gardening vocabulary|vocabulario de jardinería]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[community gardens|los jardines comunitarios]]?', options: ['[[They can be both practical and transformative|Pueden ser prácticos y transformadores]]', '[[They are only for experts|Solo son para expertos]]', '[[They are losing volunteers|Están perdiendo voluntarios]]'], correctAnswer: 0, explanation: '[[Volunteers want to grow food while improving the environment|Los voluntarios quieren cultivar comida mientras mejoran el medio ambiente]].' },
  { question: '[[Which non-defining relative clause|Qué oración de relativo no explicativa]] [[adds extra information|añade información extra]]?', options: ['[[which used to be seen as a hobby|que solía ser visto como un hobby]]', '[[that few residents had ever seen|que pocos residentes habían visto]]', '[[that had never gardened before|que nunca habían jardineado antes]]'], correctAnswer: 0, explanation: '[[Non-defining|No explicativa]] [[between commas|entre comas]].' },
];

export const UNIT_12_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u12-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Gardening & Plants',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
