/**
 * Unidad 16 B2 — Lección 4: Comprensión auditiva (History & Heritage)
 * 13 preguntas (B2: recreado con transcripción y preguntas distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hi|Hola]], [[I'm Maria|soy María]], [[a curator|conservadora]] [[who has been working|que ha estado trabajando]] [[in heritage|en patrimonio]] [[for over ten years|desde hace más de diez años]]. [[The sites|Los sitios]] [[that|que]] [[we manage|gestionamos]] [[are visited|son visitados]] [[by millions of people|por millones de personas]] [[every year|cada año]]. [[Last year|El año pasado]] [[our main building|nuestro edificio principal]] [[was damaged|fue dañado]] [[and|y]] [[the frescoes|los frescos]] [[were being restored|estaban siendo restaurados]] [[by specialists|por especialistas]] [[before|antes de]] [[we reopened|reabrimos]]. [[The damage|El daño]] [[had been discovered|había sido descubierto]] [[by our team|por nuestro equipo]] [[during a routine inspection|durante una inspección rutinaria]], [[but|pero]] [[the funds|los fondos]] [[hadn't been secured|no habían sido asegurados]] [[in time|a tiempo]]. [[Since then|Desde entonces]], [[all monuments|todos los monumentos]] [[must be|deben ser]] [[inspected|inspeccionados]] [[and|y]] [[maintained|mantenidos]] [[before|antes de]] [[they are opened|sean abiertos]] [[to the public|al público]]. [[New preservation methods|Nuevos métodos de preservación]] [[are being implemented|están siendo implementados]] [[across|en]] [[all our sites|todos nuestros sitios]] [[to prevent|para prevenir]] [[future damage|futuros daños]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Maria, a curator with over ten years in heritage|María, conservadora con más de diez años en patrimonio]]', '[[A software engineer|Un ingeniero de software]]', '[[A bank manager|Un director de banco]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Maria, a curator who has been working in heritage for over ten years|soy María, conservadora que ha estado trabajando en patrimonio desde hace más de diez años]]".' },
  { question: '[[What|Qué]] [[are the sites managed by her team|son los sitios que gestiona su equipo]]?', options: ['[[Visited by millions of people every year|Visitados por millones de personas cada año]]', '[[Only used internally|Solo usados internamente]]', '[[Never visited|Nunca visitados]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[are visited by millions of people every year|son visitados por millones de personas cada año]]".' },
  { question: '[[What|Qué]] [[happened last year|pasó el año pasado]]?', options: ['[[The main building was damaged and frescoes were being restored|El edificio principal fue dañado y los frescos estaban siendo restaurados]]', '[[They won an award|Ganaron un premio]]', '[[They launched a new exhibition|Lanzaron una nueva exposición]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[our main building was damaged and the frescoes were being restored|nuestro edificio principal fue dañado y los frescos estaban siendo restaurados]]".' },
  { question: '[[What|Qué]] [[had been discovered by the team|había sido descubierto por el equipo]]?', options: ['[[The damage during a routine inspection|El daño durante una inspección rutinaria]]', '[[A new artefact|Un nuevo artefacto]]', '[[A manuscript|Un manuscrito]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[The damage had been discovered by our team during a routine inspection|El daño había sido descubierto por nuestro equipo durante una inspección rutinaria]]".' },
  { question: '[[What|Qué]] [[hadn\'t been secured in time|no había sido asegurado a tiempo]]?', options: ['[[The funds|Los fondos]]', '[[The frescoes|Los frescos]]', '[[The building|El edificio]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[the funds hadn\'t been secured in time|los fondos no habían sido asegurados a tiempo]]".' },
  { question: '[[What|Qué]] [[must all monuments be|deben ser todos los monumentos]]?', options: ['[[Inspected and maintained before opening to the public|Inspeccionados y mantenidos antes de abrir al público]]', '[[Opened immediately|Abiertos inmediatamente]]', '[[Ignored|Ignorados]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[all monuments must be inspected and maintained before they are opened to the public|todos los monumentos deben ser inspeccionados y mantenidos antes de ser abiertos al público]]".' },
  { question: '[[What|Qué]] [[is being implemented|está siendo implementado]]?', options: ['[[New preservation methods across all sites|Nuevos métodos de preservación en todos los sitios]]', '[[Old techniques|Técnicas antiguas]]', '[[Manual processes|Procesos manuales]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[New preservation methods are being implemented across all our sites|Nuevos métodos de preservación están siendo implementados en todos nuestros sitios]]".' },
  { question: '[[The speaker|El hablante]] [[says|dice]] [[that|que]] [[the damage was never detected|el daño nunca fue detectado]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[had been discovered by our team during a routine inspection|había sido descubierto por nuestro equipo durante una inspección rutinaria]]".' },
  { question: '[[According to Maria|Según María]], [[monuments can be opened without inspection|los monumentos pueden abrirse sin inspección]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[must be inspected and maintained before they are opened|deben ser inspeccionados y mantenidos antes de ser abiertos]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the listening|de la escucha]]?', options: ['[[Damage led to stricter preservation and new methods|El daño llevó a preservación más estricta y nuevos métodos]]', '[[Heritage is easy|El patrimonio es fácil]]', '[[Nothing changed|Nada cambió]]'], correctAnswer: 0, explanation: '[[The speaker|El hablante]] [[describes|describe]] [[damage|daño]], [[response|respuesta]] [[and|y]] [[prevention|prevención]].' },
  { question: '[[Which passive form|Qué forma pasiva]] [[is used for past completed action|se usa para acción pasada completada]]?', options: ['[[had been discovered|había sido descubierto]]', '[[are being implemented|están siendo implementados]]', '[[must be inspected|deben ser inspeccionados]]'], correctAnswer: 0, explanation: '[[Past perfect passive|Pasiva pasado perfecto]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[curator|conservadora]], [[frescoes|frescos]], [[preservation|preservación]], [[heritage|patrimonio]]', '[[festival|festival]], [[streaming|streaming]], [[cast|reparto]]', '[[profit|beneficio]], [[debt|deuda]], [[budget|presupuesto]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[heritage and preservation vocabulary|vocabulario de patrimonio y preservación]].' },
  { question: '[[What|Qué]] [[does "preservation" mean|significa "preservation"]] [[in this context|en este contexto]]?', options: ['[[Protection and maintenance of heritage|Protección y mantenimiento del patrimonio]]', '[[A type of food|Un tipo de comida]]', '[[A repair|Una reparación]]'], correctAnswer: 0, explanation: '[[Preservation|Preservation]] [[means protecting heritage|significa proteger el patrimonio]].' },
];

export const UNIT_16_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u16-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'History & Heritage',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
