/**
 * Unidad 1 B2 — Lección 5: Expresión oral (Health & Fitness)
 * 18 ejercicios con casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_1_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u1-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I wish|Ojalá]] [[I|yo]] [[had known|hubiera sabido]] [[about|sobre]] [[this diet|esta dieta]] [[earlier|antes]].', expectedResponse: 'I wish I had known about this diet earlier.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Having|Habiendo]] [[completed|completado]] [[the workout|el entrenamiento]], [[he|él]] [[felt|se sintió]] [[exhausted|agotado]].', expectedResponse: 'Having completed the workout, he felt exhausted.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[regret|me arrepiento de]] [[not taking|no haber tomado]] [[better care of my health|mejor cuidado de mi salud]].', expectedResponse: 'I regret not taking better care of my health.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Despite|A pesar de]] [[the injury|la lesión]], [[they|ellos]] [[kept training|siguieron entrenando]].', expectedResponse: 'Despite the injury, they kept training.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee la frase en voz alta.', targetText: '[[I|Yo]] [[would rather|prefiero]] [[go|ir]] [[for a run|a correr]] [[than|que]] [[stay|quedarme]] [[at home|en casa]].', expectedResponse: 'I would rather go for a run than stay at home.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It is believed that|Se cree que]] [[she|ella]] [[is|es]] [[the fittest|la más en forma]] [[in the team|del equipo]].', expectedResponse: 'It is believed that she is the fittest in the team.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Encouraged|Animados]] [[by the results|por los resultados]], [[the athletes|los atletas]] [[continued|continuaron]] [[training hard|entrenando duro]].', expectedResponse: 'Encouraged by the results, the athletes continued training hard.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: "[[It's time|Ya es hora]] [[we|nosotros]] [[tried|probáramos]] [[a new sport|un deporte nuevo]]." , expectedResponse: "It's time we tried a new sport." }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que te arrepientes de no haber hecho por tu salud.', targetText: '[[I regret|Me arrepiento de]] ____.', expectedResponse: 'I regret not [verb-ing]...' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un reto fitness que te has propuesto.', targetText: '[[I have challenged myself to|Me he propuesto]] ____.', expectedResponse: 'I have challenged myself to...' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[have|he]] [[overcome|superado]] [[many|muchos]] [[health challenges|retos de salud]].', expectedResponse: 'I have overcome many health challenges.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Staying active|Mantenerse activo]] [[is|es]] [[the best way|la mejor forma]] [[to stay healthy|de mantenerse sano]].', expectedResponse: 'Staying active is the best way to stay healthy.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[joined|me uní]] [[a gym|a un gimnasio]] [[last year|el año pasado]].', expectedResponse: 'I joined a gym last year.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: cómo te sientes sobre un reto fitness que superaste.', targetText: '[[I feel|Me siento]] ____.', expectedResponse: 'I feel [proud/confident/energised] about...' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases una meta fitness que alcanzaste y cómo lo lograste.', targetText: '____. ____. ____.', expectedResponse: 'I set a goal to... I achieved it by... I learned that...' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[have|he]] [[set|establecido]] [[myself|me]] [[clear|claros]] [[fitness goals|objetivos de fitness]].', expectedResponse: 'I have set myself clear fitness goals.' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un objetivo de salud que te has fijado para los próximos meses.', targetText: '[[My goal|Mi meta]] ____.', expectedResponse: 'My goal for the next months is to...' }, topicName: 'Speaking' },
  { id: 'b2-u1-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases cómo has mejorado tu salud recientemente.', targetText: '____. ____. ____.', expectedResponse: 'I improved my health when... I felt... I learned...' }, topicName: 'Speaking' },
];
