/**
 * Unidad 7 B2 — Lección 4: Comprensión auditiva (Shopping & Consumerism)
 * 13 preguntas con audio y casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hi|Hola]], [[I'm|soy]] [[Sarah|Sarah]] [[and|y]] [[I|yo]] [[want|quiero]] [[to share|compartir]] [[something|algo]] [[about|sobre]] [[my|mi]] [[shopping habits|hábitos de compra]]. [[When|Cuando]] [[I|yo]] [[moved|me mudé]] [[to|a]] [[this city|esta ciudad]], [[I|yo]] [[discovered|descubrí]] [[two|dos]] [[great|grandes]] [[second-hand|de segunda mano]] [[shops|tiendas]] [[and|y]] [[a|un]] [[wonderful|maravilloso]] [[flea market|mercado de pulgas]]. [[I|Yo]] [[would rather|preferiría]] [[spend|pasar]] [[weekends|fines de semana]] [[at|en]] [[local markets|mercados locales]] [[than|que]] [[just|solo]] [[at|en]] [[big|grandes]] [[malls|centros comerciales]] — [[there|hay]] [[are|]] [[so many|tantas]] [[bargains|gangas]] [[to find|que encontrar]]. [[It's high time|Ya es hora]] [[we|nosotros]] [[organised|organizáramos]] [[a swap party|una fiesta de intercambio]] — [[my|mis]] [[friends|amigos]] [[and|y]] [[neighbours|vecinos]] [[have|tienen]] [[too much|demasiada]] [[stuff|cosas]] [[to declutter|para ordenar]]. [[I|yo]] [[would prefer|preferiría]] [[to invite|invitar]] [[everyone|a todos]] [[including|incluyendo]] [[my|mi]] [[sister|hermana]] [[who|quien]] [[gets on with|se lleva bien con]] [[everyone|todos]] [[at|en]] [[markets|mercados]]. [[My|Mi]] [[brother|hermano]] [[takes after|se parece a]] [[his|su]] [[father|padre]] — [[they|ellos]] [[both|ambos]] [[love|aman]] [[haggling|regatear]].`;

const INSTRUCTIONS = 'Escucha el audio. Puedes leer la transcripción. Después responde.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[is Sarah sharing|está compartiendo Sarah]]?', options: ['[[Her work|Su trabajo]]', '[[Something about her shopping habits|Algo sobre sus hábitos de compra]]', '[[A trip|Un viaje]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[I want to share something about my shopping habits|quiero compartir algo sobre mis hábitos de compra]]".' },
  { question: '[[What|Qué]] [[did Sarah discover when she moved|descubrió Sarah cuando se mudó]]?', options: ['[[A new job|Un nuevo trabajo]]', '[[Two second-hand shops and a flea market|Dos tiendas de segunda mano y un mercado de pulgas]]', '[[A trip|Un viaje]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[I discovered two great second-hand shops and a wonderful flea market|descubrí dos grandes tiendas de segunda mano y un maravilloso mercado de pulgas]]".' },
  { question: '[[What|Qué]] [[would Sarah rather do at weekends|preferiría hacer Sarah los fines de semana]]?', options: ['[[Stay alone|Quedarse sola]]', '[[Spend them at local markets rather than just at big malls|Pasarlos en mercados locales en lugar de solo en grandes centros comerciales]]', '[[Travel abroad|Viajar al extranjero]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[I would rather spend weekends at local markets than just at big malls|preferiría pasar fines de semana en mercados locales que solo en grandes centros comerciales]]".' },
  { question: "[[What|Qué]] [[does Sarah say with \"It's high time\"|dice Sarah con \"It's high time\"]]?", options: ["[[It's high time to work|Ya es hora de trabajar]]", "[[It's high time we organised a swap party|Ya es hora de que organicemos una fiesta de intercambio]]", "[[It's high time to leave|Ya es hora de irse]]"], correctAnswer: 1, explanation: '[[She says|Dice]] "[[It\'s high time we organised a swap party|ya es hora de que organicemos una fiesta de intercambio]]".' },
  { question: '[[Why|Por qué]] [[do friends and neighbours have too much stuff|tienen amigos y vecinos demasiadas cosas]]?', options: ['[[They are rich|Son ricos]]', '[[To declutter|Para ordenar]]', '[[They collect|Coleccionan]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[my friends and neighbours have too much stuff to declutter|mis amigos y vecinos tienen demasiadas cosas para ordenar]]".' },
  { question: '[[What|Qué]] [[would Sarah prefer to do|preferiría hacer Sarah]]?', options: ['[[Avoid everyone|Evitar a todos]]', '[[Invite everyone including her sister|Invitar a todos incluyendo a su hermana]]', '[[Travel alone|Viajar sola]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[I would prefer to invite everyone including my sister|preferiría invitar a todos incluyendo a mi hermana]]".' },
  { question: '[[Who|A quién]] [[does Sarah\'s brother take after|a quién se parece el hermano de Sarah]]?', options: ['[[His mother|A su madre]]', '[[His father|A su padre]]', '[[His cousin|A su primo]]'], correctAnswer: 1, explanation: '[[She says|Dice]] "[[My brother takes after his father|mi hermano se parece a su padre]]".' },
  { question: '[[Sarah|Sarah]] [[has discovered|ha descubierto]] [[second-hand shops|tiendas de segunda mano]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 0, explanation: '[[True|Verdadero]]. [[She says|Dice]] "[[a wonderful flea market|un maravilloso mercado de pulgas]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]]?', options: ['[[Travel|Viajes]]', '[[Sustainable shopping, local markets and swap parties|Compras sostenibles, mercados locales y fiestas de intercambio]]', '[[Work|Trabajo]]'], correctAnswer: 1, explanation: '[[The listening|La escucha]] [[describes|describe]] [[shopping habits|hábitos de compra]], [[local markets|mercados locales]] [[and|y]] [[swap party|fiesta de intercambio]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in|en]] [[this listening|esta escucha]]?', options: ['[[Second-hand|Segunda mano]], [[flea market|mercado de pulgas]], [[bargains|gangas]], [[swap party|fiesta de intercambio]]', '[[Weather|Tiempo]], [[travel|viaje]]', '[[Food|Comida]], [[restaurant|restaurante]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[uses|usa]] [[vocabulary|vocabulario]] [[related to|relacionado con]] [[shopping|compras]].' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[does "would rather spend" use|usa "would rather spend"]]?', options: ['[[Would rather + infinitive|Would rather + infinitivo]]', '[[Would prefer + to infinitive|Would prefer + infinitivo]]', "[[It's time + past|It's time + pasado]]"], correctAnswer: 0, explanation: '[[Would rather + infinitive without to|Would rather + infinitivo sin to]].' },
  { question: '[[Sarah|Sarah]] [[wants to invite her sister|quiere invitar a su hermana]] [[to the swap party|a la fiesta de intercambio]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 0, explanation: '[[True|Verdadero]]. [[She says|Dice]] "[[I would prefer to invite everyone including my sister|preferiría invitar a todos incluyendo a mi hermana]]".' },
  { question: '[[What|Qué]] [[can we conclude|podemos concluir]] [[about|sobre]] [[Sarah|Sarah]]?', options: ['[[She has no shopping habits|No tiene hábitos de compra]]', '[[She values sustainable shopping and wants to bring people together|Valora las compras sostenibles y quiere reunir a la gente]]', '[[She dislikes markets|No le gustan los mercados]]'], correctAnswer: 1, explanation: '[[She prefers local markets|Prefiere mercados locales]], [[wants swap party|quiere fiesta de intercambio]], [[invites sister|invita a la hermana]].' },
];

export const UNIT_7_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u7-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Shopping & Consumerism',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
