/**
 * Unidad 5 B2 — Lección 6: Expresión escrita (Repaso 1–4)
 * 18 ejercicios (B2: más vocabulario y complejidad que B1)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_5_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u5-l6-w1', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2-3 frases sobre qué habrás logrado para dentro de cinco años.', expressionHint: 'Usa: By..., I will have..., future perfect.', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[the report|el informe]] [[by|para]] [[Friday|viernes]].', options: ['[[will have finished|habré terminado]]', '[[will finish|terminaré]]'], correctAnswer: 'will have finished', acceptableAnswers: ['will have finished'], explanation: '[[Future perfect|Future perfect]] [[with by + time|con by + tiempo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w3', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) combinando trabajo, educación y ocio.', expressionHint: 'Usa: enjoy, hope to, encouraged me to, take up, unwind.', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w4', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "encouraged me to" y otra con "hope to".', expressionHint: 'They encouraged me to... / I hope to...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con gerund o infinitivo.', questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[studying|estudiando]] [[at university|en la universidad]].', options: ['[[enjoys|disfruta]]', '[[enjoy|disfruta]]'], correctAnswer: 'enjoys', acceptableAnswers: ['enjoys'], explanation: '[[Enjoy + gerund|Enjoy + gerundio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w6', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre cómo equilibras trabajo y tiempo libre.', expressionHint: 'Puedes usar: leisure time, take up, give up, unwind, work remotely.', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w7', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "This time next week I will be..."', expressionHint: 'Future continuous.', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[My parents|Mis padres]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[join|unirse]] [[a sports club|a un club deportivo]].', options: ['[[encouraged me to|me animaron a]]', '[[encouraged me|me animaron]]'], correctAnswer: 'encouraged me to', acceptableAnswers: ['encouraged me to'], explanation: '[[Encourage + object + infinitive|Encourage + objeto + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w9', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre tus planes profesionales y educativos.', expressionHint: 'Puedes usar: get promoted, performance review, scholarship, degree.', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w10', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases usando "avoid + gerund" y "refuse + infinitive".', expressionHint: 'I avoided... / They refused to...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[stay|quedarse]] [[longer|más tiempo]] [[at the beach|en la playa]].', options: ['[[allowed us to|nos permitieron]]', '[[allowed us|nos permitieron]]'], correctAnswer: 'allowed us to', acceptableAnswers: ['allowed us to'], explanation: '[[Allow + object + infinitive|Allow + objeto + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w12', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre la importancia del tiempo libre.', expressionHint: 'Puedes usar: leisure time, pastime, unwind, relax, take up.', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w13', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con "I am going to..." para un plan y otra con "I will..." para una predicción.', expressionHint: 'I am going to... / I think... will...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con gerund o infinitivo.', questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[abroad|en el extranjero]] [[next year|el año que viene]].', options: ['[[hope to study|esperamos estudiar]]', '[[hope studying|esperamos estudiando]]'], correctAnswer: 'hope to study', acceptableAnswers: ['hope to study'], explanation: '[[Hope + infinitive|Hope + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w15', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre un hobby que te animaron a empezar.', expressionHint: 'Puedes usar: encouraged me to, take up, invited me to, pastime.', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w16', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con future perfect y otra con future continuous.', expressionHint: 'By 2030 I will have... / At 9 pm I will be...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ [[a master\'s degree|un máster]] [[after|después de]] [[graduating|graduarme]].', options: ['[[suggest doing|sugiero hacer]]', '[[suggest to do|sugiero hacer]]'], correctAnswer: 'suggest doing', acceptableAnswers: ['suggest doing'], explanation: '[[Suggest + gerund|Suggest + gerundio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u5-l6-w18', type: 'writing', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) resumiendo lo que has aprendido en las unidades 1-4.', expressionHint: 'Incluye: future tenses, gerund/infinitive, work, education, leisure.', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
