/**
 * Unidad 6 B2 — Lección 5: Expresión oral (Feelings and emotions)
 * 18 ejercicios (B2: Wish, If only, feelings vocabulary)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_6_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u6-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[had|hubiera]] [[more time|más tiempo]] [[to study|para estudiar]].', expectedResponse: 'I wish I had more time to study.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[had gone|hubiera ido]] [[to the party|a la fiesta]] [[last night|anoche]].', expectedResponse: 'I wish I had gone to the party last night.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If only|Ojalá]] [[I|yo]] [[had known|hubiera sabido]] [[that|eso]] [[earlier|antes]].', expectedResponse: 'If only I had known that earlier.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[felt|se sintió]] [[overwhelmed|abrumada]] [[and|y]] [[anxious|ansiosa]] [[before|antes de]] [[the exam|el examen]].', expectedResponse: 'She felt overwhelmed and anxious before the exam.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[feel|me siento]] [[relieved|aliviado]] [[and|y]] [[delighted|encantado]] [[that|de que]] [[everything|todo]] [[went well|saliera bien]].', expectedResponse: 'I feel relieved and delighted that everything went well.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[could|pudiera]] [[speak|hablar]] [[French|francés]] [[fluently|con fluidez]].', expectedResponse: 'I wish I could speak French fluently.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[was|estaba]] [[so|tan]] [[frustrated|frustrado]] [[when|cuando]] [[things|las cosas]] [[didn\'t work out|no salieron bien]].', expectedResponse: 'He was so frustrated when things didn\'t work out.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If only|Ojalá]] [[we|nosotros]] [[had had|hubiéramos tenido]] [[more time|más tiempo]] [[together|juntos]].', expectedResponse: 'If only we had had more time together.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que desees haber hecho diferente en el pasado.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I wish I had [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: cómo te sentiste en una situación que te hizo sentir ansioso o abrumado.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I felt anxious/overwhelmed when...' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[grateful|agradecido]] [[for|por]] [[your|tu]] [[support|apoyo]] [[and|y]] [[feel|me siento]] [[hopeful|esperanzado]] [[about|sobre]] [[the future|el futuro]].', expectedResponse: 'I am grateful for your support and feel hopeful about the future.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They|Ellos]] [[were|estaban]] [[thrilled|emocionados]] [[when|cuando]] [[they|ellos]] [[heard|oyeron]] [[the news|las noticias]].', expectedResponse: 'They were thrilled when they heard the news.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[felt|se sintió]] [[ashamed|avergonzada]] [[and|y]] [[guilty|culpable]] [[after|después de]] [[the argument|la discusión]].', expectedResponse: 'She felt ashamed and guilty after the argument.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con "If only" sobre algo del pasado.', targetText: '[[If only|Ojalá]] ____.', expectedResponse: 'If only I had [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases una situación en la que te sentiste aliviado o encantado.', targetText: '____. ____. ____.', expectedResponse: 'I felt relieved/delighted when... It happened because...' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[hadn\'t been|no hubiera estado]] [[so nervous|tan nervioso]] [[before|antes de]] [[the interview|la entrevista]].', expectedResponse: 'I wish I hadn\'t been so nervous before the interview.' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que desees poder hacer ahora.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I wish I could [infinitive]...' }, topicName: 'Speaking' },
  { id: 'b2-u6-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Feelings and emotions', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases por qué es importante hablar de los sentimientos.', targetText: '____. ____. ____.', expectedResponse: 'It is important to talk about feelings because... When we share...' }, topicName: 'Speaking' },
];
