/**
 * Unidad 32 B2 — Lección 2: Vocabulario (Environment extended)
 * 18 ejercicios (B2: medio ambiente, sostenibilidad, conservación)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Environment (extended)|Medio Ambiente (ampliado)]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con el medio ambiente.';

export const UNIT_32_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u32-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The variety of life in an ecosystem|La variedad de vida en un ecosistema]]:', options: ['[[biodiversity|biodiversidad]]', '[[ecosystem|ecosistema]]', '[[habitat|hábitat]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Gases that trap heat in the atmosphere|Gases que atrapan calor en la atmósfera]]:', options: ['[[greenhouse gases|gases de efecto invernadero]]', '[[emissions|emisiones]]', '[[pollution|contaminación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use resources in a way that preserves them|Usar recursos de forma que los preserve]]:', options: ['[[sustain|sostener]]', '[[conserve|conservar]]', '[[preserve|preservar]]'], correctAnswer: 1 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The gradual increase in Earth\'s temperature|El aumento gradual de la temperatura terrestre]]:', options: ['[[global warming|calentamiento global]]', '[[climate change|cambio climático]]', '[[greenhouse effect|efecto invernadero]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a threat"|Colocación: "to ____ a threat"]]', options: ['[[pose|plantear]]', '[[make|hacer]]', '[[get|obtener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ awareness"|Colocación: "to ____ awareness"]]', options: ['[[raise|aumentar]]', '[[get|obtener]]', '[[make|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A species that no longer exists|Una especie que ya no existe]]:', options: ['[[extinct|extinta]]', '[[endangered|en peligro]]', '[[vulnerable|vulnerable]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To destroy forests on a large scale|Destruir bosques a gran escala]]:', options: ['[[deforestation|deforestación]]', '[[reforestation|reforestación]]', '[[conservation|conservación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a balance"|Colocación: "to ____ a balance"]]', options: ['[[strike|lograr]]', '[[make|hacer]]', '[[get|obtener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Water that is safe to drink|Agua que es segura para beber]]:', options: ['[[potable water|agua potable]]', '[[sewage|aguas residuales]]', '[[contaminated|contaminada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The natural home of an animal or plant|El hogar natural de un animal o planta]]:', options: ['[[habitat|hábitat]]', '[[ecosystem|ecosistema]]', '[[reserve|reserva]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ an impact"|Expresión: "to ____ an impact"]]', options: ['[[have|tener]]', '[[make|hacer]]', '[[get|obtener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Energy from natural sources that renew|Energía de fuentes naturales que se renuevan]]:', options: ['[[renewable energy|energía renovable]]', '[[fossil fuels|combustibles fósiles]]', '[[nuclear|nuclear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use something again|Usar algo de nuevo]]:', options: ['[[reuse|reutilizar]]', '[[reduce|reducir]]', '[[recycle|reciclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a conclusion"|Colocación: "to ____ a conclusion"]]', options: ['[[draw|sacar]]', '[[make|hacer]]', '[[get|obtener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A protected area for wildlife|Área protegida para vida silvestre]]:', options: ['[[nature reserve|reserva natural]]', '[[landfill|vertedero]]', '[[industrial zone|zona industrial]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Harmful substances in the environment|Sustancias dañinas en el medio ambiente]]:', options: ['[[pollutants|contaminantes]]', '[[resources|recursos]]', '[[renewables|renovables]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u32-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ responsibility"|Expresión: "asumir responsabilidad"]] [[for the environment|por el medio ambiente]]', options: ['[[take|asumir]]', '[[get|obtener]]', '[[make|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
