/**
 * Unidad 21 B2 — Lección 3: Comprensión lectora (Personal Development)
 * 13 preguntas (B2: recreado con texto y preguntas reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Regular learning|El aprendizaje regular]] [[is essential|es esencial]] [[for|para]] [[personal growth|crecimiento personal]], [[although|aunque]] [[many people|muchas personas]] [[find it hard|les resulta difícil]] [[to fit it into|encajarlo en]] [[their busy schedules|sus agendas ocupadas]]. [[In spite of|A pesar de]] [[the benefits|los beneficios]] [[that|que]] [[self-improvement|la superación personal]] [[brings|trae]], [[a large number|un gran número]] [[of adults|de adultos]] [[remain stuck|permanecen estancados]] [[in their comfort zone|en su zona de confort]]. [[Whereas|Mientras que]] [[some people|algunas personas]] [[prefer|prefieren]] [[workshops and courses|talleres y cursos]], [[others|otras]] [[enjoy|disfrutan]] [[self-directed learning|aprendizaje autodirigido]] [[such as|como]] [[reading|leer]] [[or|o]] [[online courses|cursos online]]. [[However|Sin embargo]], [[the key|la clave]] [[is|es]] [[to find|encontrar]] [[something|algo]] [[you enjoy|que disfrutes]] [[and|y]] [[stick to it|mantenerlo]]. [[Despite|A pesar de]] [[popular belief|la creencia popular]], [[you don't need|no necesitas]] [[expensive coaches|coaches caros]] [[to grow|para crecer]]. [[Simple activities|Actividades simples]] [[like|como]] [[journaling|escribir un diario]], [[reflection|reflexión]] [[and|y]] [[setting small goals|establecer metas pequeñas]] [[can be|pueden ser]] [[highly effective|muy efectivos]]. [[Although|Aunque]] [[motivation alone|la motivación sola]] [[won't make you succeed|no te hará triunfar]], [[combining|combinar]] [[learning|aprendizaje]] [[with|con]] [[consistent action|acción constante]] [[produces|produce]] [[the best results|los mejores resultados]].`;

const INSTRUCTIONS = '[[Read the text about personal development. Then answer the questions.|Lee el texto sobre desarrollo personal. Después responde las preguntas.]]';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does the text say|dice el texto]] [[about|sobre]] [[fitting learning into schedules|encajar el aprendizaje en las agendas]]?', options: ['[[Many people find it hard|A muchas personas les resulta difícil]]', '[[Everyone manages easily|Todo el mundo lo consigue fácilmente]]', '[[Only young people struggle|Solo los jóvenes tienen problemas]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[many people find it hard to fit it into their busy schedules|a muchas personas les resulta difícil encajarlo en sus agendas ocupadas]]".' },
  { question: '[[What|Qué]] [[contrast|contraste]] [[does the text make|hace el texto]] [[about preferences|sobre preferencias]]?', options: ['[[Some prefer workshops, others prefer self-directed learning|Unos prefieren talleres, otros aprendizaje autodirigido]]', '[[Everyone prefers workshops|Todos prefieren talleres]]', '[[Nobody likes online courses|A nadie le gustan los cursos online]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Whereas some prefer workshops and courses, others enjoy self-directed learning|mientras que unos prefieren talleres y cursos, otros disfrutan aprendizaje autodirigido]]".' },
  { question: '[[According to the text|Según el texto]], [[what|qué]] [[is the key|es la clave]]?', options: ['[[Finding something you enjoy and sticking to it|Encontrar algo que disfrutes y mantenerlo]]', '[[Hiring expensive coaches|Contratar coaches caros]]', '[[Learning alone|Aprender solo]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the key is to find something you enjoy and stick to it|la clave es encontrar algo que disfrutes y mantenerlo]]".' },
  { question: '[[What|Qué]] [[does the text say|dice el texto]] [[about|sobre]] [[expensive coaches|coaches caros]]?', options: ['[[You don\'t need them to grow|No los necesitas para crecer]]', '[[They are essential|Son esenciales]]', '[[Only executives need them|Solo los ejecutivos los necesitan]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Despite popular belief, you don\'t need expensive coaches to grow|a pesar de la creencia popular, no necesitas coaches caros para crecer]]".' },
  { question: '[[Which activities|Qué actividades]] [[does the text mention|menciona el texto]] [[as effective|como efectivas]]?', options: ['[[Journaling, reflection and setting small goals|Escribir diario, reflexión y establecer metas pequeñas]]', '[[Only formal courses|Solo cursos formales]]', '[[Extreme challenges|Desafíos extremos]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Simple activities like journaling, reflection and setting small goals can be highly effective|actividades simples como escribir diario, reflexión y establecer metas pequeñas pueden ser muy efectivas]]".' },
  { question: '[[What|Qué]] [[produces the best results|produce los mejores resultados]] [[according to the text|según el texto]]?', options: ['[[Combining learning with consistent action|Combinar aprendizaje con acción constante]]', '[[Motivation alone|Solo la motivación]]', '[[Learning alone|Solo el aprendizaje]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[combining learning with consistent action produces the best results|combinar aprendizaje con acción constante produce los mejores resultados]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[all adults|todos los adultos]] [[learn regularly|aprenden regularmente]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[a large number of adults remain stuck in their comfort zone|un gran número de adultos permanecen estancados en su zona de confort]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the text|del texto]]?', options: ['[[Learning is important and you can grow with simple activities and consistent action|El aprendizaje es importante y puedes crecer con actividades simples y acción constante]]', '[[You need expensive coaches to grow|Necesitas coaches caros para crecer]]', '[[Only workshops work|Solo los talleres funcionan]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[covers|cubre]] [[learning importance|importancia del aprendizaje]], [[simple activities|actividades simples]] [[and|y]] [[consistent action|acción constante]].' },
  { question: '[[Which linker|Qué conector]] [[of contrast|de contraste]] [[is used|se usa]] [[to compare workshops and self-directed learning|para comparar talleres y aprendizaje autodirigido]]?', options: ['[[Whereas|Whereas]]', '[[Because of|Because of]]', '[[In order to|In order to]]'], correctAnswer: 0, explanation: '[[Whereas|Whereas]] [[introduces the contrast|introduce el contraste]] [[between workshops and self-directed learning|entre talleres y aprendizaje autodirigido]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the author\'s view|la opinión del autor]]?', options: ['[[Anyone can improve with the right approach|Cualquiera puede mejorar con el enfoque correcto]]', '[[Only experts should learn|Solo los expertos deberían aprender]]', '[[Learning is not important|El aprendizaje no es importante]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[emphasises|enfatiza]] [[accessibility|accesibilidad]] [[and|y]] [[simplicity|simplicidad]].' },
  { question: '[[The text|El texto]] [[says|dice]] [[that motivation alone will make you succeed|que la motivación sola te hará triunfar]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[Although motivation alone won\'t make you succeed|aunque la motivación sola no te hará triunfar]]".' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[growth|crecimiento]], [[workshop|taller]], [[comfort zone|zona de confort]], [[consistent action|acción constante]]', '[[computer|ordenador]], [[software|software]], [[internet|internet]]', '[[salary|salario]], [[budget|presupuesto]], [[investment|inversión]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[personal development vocabulary|vocabulario de desarrollo personal]].' },
  { question: '[[What|Qué]] [[does "in spite of"|qué hace "in spite of"]] [[introduce|introduce]] [[in the text|en el texto]]?', options: ['[[A contrast: benefits exist but many stay stuck|Un contraste: hay beneficios pero muchos permanecen estancados]]', '[[A reason|Una razón]]', '[[A purpose|Un propósito]]'], correctAnswer: 0, explanation: '[[In spite of|In spite of]] [[the benefits|los beneficios]] [[contrasts with|contrasta con]] [[many remain stuck|muchos permanecen estancados]].' },
];

export const UNIT_21_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u21-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Personal Development',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
