/**
 * Unidad 56 B2 — Lección 1: Gramática (Relative Clauses - Advanced)
 * 18 ejercicios (B2: oraciones de relativo avanzadas) — Tema: Digital Rights & Online Ethics
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Relative Clauses - Advanced|Oraciones de relativo avanzadas]]';
const INSTRUCTIONS = 'Elige la forma correcta (defining, non-defining, relative pronoun).';

export const UNIT_56_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u56-l1-g1', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Data|Los datos]] ____ [[companies collect|que las empresas recogen]] [[should be protected|deberían estar protegidos]].', options: ['[[that|que]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[Defining relative clause: that/which for things|Oración de relativo especificativa]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The platform|La plataforma]], ____ [[was launched last year|que fue lanzada el año pasado]], [[has millions of users|tiene millones de usuarios]].', options: ['[[which|que]]', '[[that|que]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Non-defining: which (not that)|No especificativa: which]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g3', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Users|Los usuarios]] ____ [[consent|consentimiento]] [[was not obtained|no fue obtenido]] [[can file complaints|pueden presentar quejas]].', options: ['[[whose|cuyo]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 'whose', acceptableAnswers: ['whose'], explanation: '[[Whose = possession|Whose = posesión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The law|La ley]] ____ [[we discussed|que discutimos]] [[yesterday|ayer]] [[protects privacy|protege la privacidad]].', options: ['[[which|que]]', '[[that|que]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Which/that can be omitted when object|Which/that can be omitted]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g5', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The moment|El momento]] ____ [[I received the request|en que recibí la solicitud]] [[I knew|supe]] [[something was wrong|algo iba mal]].', options: ['[[when|cuando]]', '[[where|donde]]', '[[which|que]]'], correctAnswer: 'when', acceptableAnswers: ['when'], explanation: '[[When for time|When para tiempo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The website|La web]] ____ [[users share their data|donde los usuarios comparten sus datos]] [[must be secure|debe ser segura]].', options: ['[[where|donde]]', '[[when|cuando]]', '[[which|que]]'], correctAnswer: 0, explanation: '[[Where for place|Where para lugar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g7', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Anyone|Cualquiera]] ____ [[breaches the rules|infringe las reglas]] [[will be banned|será baneado]].', options: ['[[who|quien]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who'], explanation: '[[Who for people|Who para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The algorithm|El algoritmo]], ____ [[accuracy is debated|cuya precisión es debatida]], [[may show bias|puede mostrar sesgo]].', options: ['[[whose|cuyo]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Whose for possession (things)|Whose para posesión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g9', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The reason|La razón]] ____ [[we need encryption|por la que necesitamos encriptación]] [[is clear|es clara]].', options: ['[[why|por la que]]', '[[when|cuando]]', '[[where|donde]]'], correctAnswer: 'why', acceptableAnswers: ['why'], explanation: '[[Why for reason|Why para razón]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The company|La empresa]] ____ [[I work for|para la que trabajo]] [[values ethics|valora la ética]].', options: ['[[which|que]]', '[[who|quien]]', '[[whose|cuyo]]'], correctAnswer: 0, explanation: '[[Which for company (thing)|Which para empresa]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g11', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[All|Todo]] ____ [[we asked for|lo que pedimos]] [[was transparency|era transparencia]].', options: ['[[that|que]]', '[[which|que]]', '[[what|lo que]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[That after all|That after all]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The expert|El experto]] ____ [[opinion we sought|cuya opinión buscamos]] [[advised caution|aconsejó cautela]].', options: ['[[whose|cuyo]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 0, explanation: '[[Whose for possession|Whose para posesión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g13', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There is nothing|No hay nada]] ____ [[we can do|que podamos hacer]] [[without consent|sin consentimiento]].', options: ['[[that|que]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[That after nothing|That after nothing]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The policy|La política]], ____ [[implementation was delayed|cuya implementación fue retrasada]], [[is now active|ahora está activa]].', options: ['[[whose|cuyo]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Whose for possession|Whose para posesión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g15', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The way|La forma]] ____ [[data is used|en que se usan los datos]] [[matters|importa]].', options: ['[[in which|en la que]]', '[[when|cuando]]', '[[where|donde]]'], correctAnswer: 'in which', acceptableAnswers: ['in which', 'that'], explanation: '[[Preposition + which|Preposición + which]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The person|La persona]] ____ [[to whom|a quien]] [[we reported the issue|reportamos el problema]] [[was helpful|fue servicial]].', options: ['[[to whom|a quien]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 0, explanation: '[[Preposition + whom (formal)|Preposición + whom]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g17', type: 'fill-blank', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cybersecurity|La ciberseguridad]] ____ [[we depend on|de la que dependemos]] [[is essential|es esencial]].', options: ['[[on which|de la que]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 'on which', acceptableAnswers: ['on which', 'that'], explanation: '[[Preposition + which|Preposición + which]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u56-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'technology-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The first thing|Lo primero]] ____ [[we must do|que debemos hacer]] [[is verify consent|es verificar el consentimiento]].', options: ['[[that|que]]', '[[which|que]]', '[[what|lo que]]'], correctAnswer: 0, explanation: '[[That after superlatives|That after superlatives]].' }] }, topicName: 'Grammar' },
];
