/**
 * Unidad 9 B2 — Lección 3: Comprensión lectora (Environment)
 * 13 preguntas con texto y casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Having read|Habiendo leído]] [[about|sobre]] [[climate change|cambio climático]] [[and|y]] [[deforestation|deforestación]], [[I|yo]] [[decided|decidí]] [[to reduce|reducir]] [[my|mi]] [[carbon footprint|huella de carbono]]. [[The pollution|La contaminación]] [[in|en]] [[our|nuestra]] [[city|ciudad]] [[has|ha]] [[increased|aumentado]] [[and|y]] [[many|muchas]] [[species|especies]] [[are|están]] [[endangered|en peligro de extinción]]. [[I|Yo]] [[recycle|reciclo]] [[everything|todo]] [[I|yo]] [[can|puedo]] [[and|y]] [[reuse|reutilizo]] [[bags|bolsas]] [[instead of|en lugar de]] [[throwing|tirar]] [[them|las]] [[away|a la basura]]. [[Reducing|Reducir]] [[waste|residuos]] [[is|es]] [[key|clave]] [[for|para]] [[sustainability|sostenibilidad]]. [[The|Los]] [[greenhouse gases|gases de efecto invernadero]] [[from|de]] [[fossil fuels|combustibles fósiles]] [[are|son]] [[a major|un gran]] [[cause|causa]] [[of|de]] [[global warming|calentamiento global]]. [[I|yo]] [[support|apoyo]] [[renewable energy|energía renovable]] [[and|y]] [[conservation|conservación]] [[projects|proyectos]] [[whenever|siempre que]] [[I|yo]] [[can|puedo]]. [[Having joined|Habiendo unido]] [[a local|un grupo local]] [[environmental group|medioambiental]] [[last year|el año pasado]], [[I|yo]] [[feel|me siento]] [[hopeful|esperanzado]] [[about|sobre]] [[the future|el futuro]].`;

const INSTRUCTIONS = 'Lee el texto. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[did the person decide to do|decidió hacer la persona]] [[after reading about climate change|después de leer sobre cambio climático]]?', options: ['[[To travel more|Viajar más]]', '[[To reduce their carbon footprint|Reducir su huella de carbono]]', '[[To use more fossil fuels|Usar más combustibles fósiles]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[Having read about climate change and deforestation, I decided to reduce my carbon footprint|habiendo leído sobre cambio climático y deforestación, decidí reducir mi huella de carbono]]".' },
  { question: '[[What|Qué]] [[problems|problemas]] [[does the text mention|menciona el texto]]?', options: ['[[Only work|Solo trabajo]]', '[[Pollution has increased and many species are endangered|La contaminación ha aumentado y muchas especies están en peligro]]', '[[Only travel|Solo viajes]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[The pollution in our city has increased and many species are endangered|la contaminación en nuestra ciudad ha aumentado y muchas especies están en peligro]]".' },
  { question: '[[What|Qué]] [[does the person do|hace la persona]] [[with bags|con las bolsas]]?', options: ['[[Throws them away|Las tira]]', '[[Reuses them instead of throwing them away|Las reutiliza en lugar de tirarlas]]', '[[Burns them|Las quema]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I reuse bags instead of throwing them away|reutilizo bolsas en lugar de tirarlas]]".' },
  { question: '[[What|Qué]] [[is key for sustainability|es clave para la sostenibilidad]]?', options: ['[[Using more fossil fuels|Usar más combustibles fósiles]]', '[[Reducing waste|Reducir residuos]]', '[[Increasing pollution|Aumentar contaminación]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[Reducing waste is key for sustainability|reducir residuos es clave para la sostenibilidad]]".' },
  { question: '[[What|Qué]] [[are a major cause of global warming|son una gran causa del calentamiento global]]?', options: ['[[Renewable energy|Energía renovable]]', '[[Greenhouse gases from fossil fuels|Gases de efecto invernadero de combustibles fósiles]]', '[[Recycling|Reciclaje]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[The greenhouse gases from fossil fuels are a major cause of global warming|los gases de efecto invernadero de combustibles fósiles son una gran causa del calentamiento global]]".' },
  { question: '[[What|Qué]] [[does the person support|apoya la persona]]?', options: ['[[Fossil fuels only|Solo combustibles fósiles]]', '[[Renewable energy and conservation projects|Energía renovable y proyectos de conservación]]', '[[Deforestation|Deforestación]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I support renewable energy and conservation projects|apoyo energía renovable y proyectos de conservación]]".' },
  { question: '[[When|Cuándo]] [[did the person join a local environmental group|se unió la persona a un grupo medioambiental local]]?', options: ['[[This year|Este año]]', '[[Last year|El año pasado]]', '[[Five years ago|Hace cinco años]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[Having joined a local environmental group last year|habiendo unido un grupo medioambiental local el año pasado]]".' },
  { question: '[[The person|La persona]] [[feels hopeful about the future|se siente esperanzado sobre el futuro]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[I feel hopeful about the future|me siento esperanzado sobre el futuro]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]] [[of|del]] [[this text|este texto]]?', options: ['[[Travel|Viajes]]', '[[Environmental awareness and personal action|Conciencia medioambiental y acción personal]]', '[[Work|Trabajo]]'], correctAnswer: 1, explanation: '[[The text|El texto]] [[describes|describe]] [[environmental awareness|conciencia medioambiental]] [[and|y]] [[personal action|acción personal]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in|en]] [[this text|este texto]]?', options: ['[[Climate change|Cambio climático]], [[pollution|contaminación]], [[recycle|reciclar]], [[sustainability|sostenibilidad]], [[renewable energy|energía renovable]]', '[[Weather|Tiempo]], [[travel|viaje]]', '[[Food|Comida]], [[restaurant|restaurante]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[uses|usa]] [[vocabulary|vocabulario]] [[related to|relacionado con]] [[environment|medio ambiente]].' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[does "Having read" use|usa "Having read"]]?', options: ['[[Having + past participle|Having + participio pasado]]', '[[Present participle|Participio presente]]', '[[Past simple|Past simple]]'], correctAnswer: 0, explanation: '[[Having + past participle|Having + participio pasado]] [[for action before main clause|para acción antes de la cláusula principal]].' },
  { question: '[[The person|La persona]] [[recycles everything they can|recicla todo lo que puede]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[I recycle everything I can|reciclo todo lo que puedo]]".' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the person|la persona]]?', options: ['[[They do not care about the environment|No les importa el medio ambiente]]', '[[They are environmentally conscious and take action|Son conscientes del medio ambiente y toman acción]]', '[[They only recycle|Solo reciclan]]'], correctAnswer: 1, explanation: '[[They reduce|Reducen]], [[recycle|reciclan]], [[reuse|reutilizan]], [[support renewable energy|apoyan energía renovable]], [[joined environmental group|se unieron a grupo medioambiental]].' },
];

export const UNIT_9_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u9-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Environment',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
