/**
 * Unidad 16 B2 — Lección 5: Expresión oral (Technology)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_16_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u16-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[Millions of apps|Millones de aplicaciones]] [[are downloaded|son descargadas]] [[every year|cada año]].', expectedResponse: 'Millions of apps are downloaded every year.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The first iPhone|El primer iPhone]] [[was launched|fue lanzado]] [[in 2007|en 2007]].', expectedResponse: 'The first iPhone was launched in 2007.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[A new software update|Una nueva actualización]] [[is being installed|está siendo instalada]] [[right now|ahora mismo]].', expectedResponse: 'A new software update is being installed right now.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Your password|Tu contraseña]] [[must be changed|debe ser cambiada]] [[every 90 days|cada 90 días]].', expectedResponse: 'Your password must be changed every 90 days.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The bug|El error]] [[was fixed|fue corregido]] [[by the development team|por el equipo de desarrollo]] [[yesterday|ayer]].', expectedResponse: 'The bug was fixed by the development team yesterday.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Personal data|Los datos personales]] [[must be protected|deben ser protegidos]] [[under GDPR regulations|bajo las regulaciones GDPR]].', expectedResponse: 'Personal data must be protected under GDPR regulations.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The algorithm|El algoritmo]] [[has been improved|ha sido mejorado]] [[since 2020|desde 2020]].', expectedResponse: 'The algorithm has been improved since 2020.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The new feature|La nueva función]] [[will have been released|habrá sido lanzada]] [[by next month|para el próximo mes]].', expectedResponse: 'The new feature will have been released by next month.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[The data|Los datos]] [[that is collected|que se recogen]] [[from users|de usuarios]] [[must be protected|deben ser protegidos]] [[under strict regulations|bajo regulaciones estrictas]].', expectedResponse: 'The data that is collected from users must be protected under strict regulations.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en las palabras clave.', targetText: '[[New features|Nuevas funciones]] [[are being added|están siendo añadidas]] [[constantly|constantemente]] [[to meet user demand|para satisfacer la demanda del usuario]].', expectedResponse: 'New features are being added constantly to meet user demand.' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s11', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe cómo se usa la tecnología en tu trabajo o vida. Usa pasiva.', prompt: '[[Describe how technology is used in your work or daily life. Use passive forms (is used, are sent, was developed, etc.).|Describe cómo se usa la tecnología en tu trabajo o vida diaria. Usa formas pasivas (is used, are sent, was developed, etc.).]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s12', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica qué debe ser protegido en la era digital.', prompt: '[[Explain what must be protected in the digital age. Use passive forms (must be protected, should be encrypted, etc.).|Explica qué debe ser protegido en la era digital. Usa formas pasivas (must be protected, should be encrypted, etc.).]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s13', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué invento tecnológico ha cambiado más tu vida?', prompt: '[[What technological invention has changed your life the most? Use passive to describe how it was developed or how it is used.|¿Qué invento tecnológico ha cambiado más tu vida? Usa pasiva para describir cómo fue desarrollado o cómo se usa.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s14', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe un proceso tecnológico (ej. cómo se envía un email).', prompt: '[[Describe a technological process (e.g. how an email is sent, how data is stored). Use passive forms throughout.|Describe un proceso tecnológico (ej. cómo se envía un email, cómo se almacenan los datos). Usa formas pasivas.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s15', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these tech expressions in your own sentences:|Usa estas expresiones tecnológicas en tus propias oraciones:]]\n[[- run an application|- ejecutar una aplicación]]\n[[- install software|- instalar software]]\n[[- fix a bug|- corregir un error]]\n[[- release an update|- lanzar una actualización]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s16', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: convence a alguien de que sus datos deben ser protegidos.', prompt: '[[Persuade someone that their data must be protected. Use passive forms (data must be encrypted, passwords should be changed, etc.).|Convence a alguien de que sus datos deben ser protegidos. Usa formas pasivas (data must be encrypted, passwords should be changed, etc.).]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s17', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe un producto tecnológico que fue lanzado recientemente.', prompt: '[[Describe a tech product that was released recently. Use passive (was launched, is being used, has been updated, etc.).|Describe un producto tecnológico que fue lanzado recientemente. Usa pasiva (was launched, is being used, has been updated, etc.).]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u16-l5-s18', type: 'speaking', level: 'B2', topic: 'Technology', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué debería ser implementado para mejorar la seguridad online?', prompt: '[[What should be implemented to improve online security? Use passive forms (should be encrypted, must be protected, etc.).|¿Qué debería ser implementado para mejorar la seguridad online? Usa formas pasivas (should be encrypted, must be protected, etc.).]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
