/**
 * Unidad 52 B2 — Lección 2: Vocabulario (Human Migration & Society)
 * 18 ejercicios (B2: migration, refugees, asylum, integration, displacement, borders, society)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Human Migration & Society|Migración humana y sociedad]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con migración y sociedad.';

export const UNIT_52_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u52-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Movement of people from one place to another|Desplazamiento de personas de un lugar a otro]]:', options: ['[[migration|migración]]', '[[refugee|refugiado]]', '[[asylum|asilo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Person fleeing persecution or war|Persona que huye de persecución o guerra]]:', options: ['[[refugee|refugiado]]', '[[migrant|migrante]]', '[[asylum seeker|solicitante de asilo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Protection granted to someone fleeing persecution|Protección concedida a quien huye de persecución]]:', options: ['[[asylum|asilo]]', '[[migration|migración]]', '[[refugee|refugiado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Process of fitting into a new society|Proceso de adaptación a una nueva sociedad]]:', options: ['[[integration|integración]]', '[[displacement|desplazamiento]]', '[[borders|fronteras]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Forced removal from home|Desplazamiento forzado del hogar]]:', options: ['[[displacement|desplazamiento]]', '[[borders|fronteras]]', '[[society|sociedad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Lines between countries|Líneas entre países]]:', options: ['[[borders|fronteras]]', '[[society|sociedad]]', '[[refugee|refugiado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Community of people living together|Comunidad de personas que viven juntas]]:', options: ['[[society|sociedad]]', '[[migration|migración]]', '[[asylum|asilo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Person applying for asylum|Persona que solicita asilo]]:', options: ['[[asylum seeker|solicitante de asilo]]', '[[refugee|refugiado]]', '[[migrant|migrante]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Place for temporary housing of refugees|Lugar para alojamiento temporal de refugiados]]:', options: ['[[refugee camp|campamento de refugiados]]', '[[society|sociedad]]', '[[borders|fronteras]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To leave one\'s country|Abandonar el país de uno]]:', options: ['[[to flee|huir]]', '[[to integrate|integrarse]]', '[[to settle|establecerse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make a new home in a place|Hacer un nuevo hogar en un lugar]]:', options: ['[[to settle|establecerse]]', '[[to flee|huir]]', '[[to displace|desplazar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Unfair treatment|Trato injusto]]:', options: ['[[discrimination|discriminación]]', '[[integration|integración]]', '[[displacement|desplazamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Legal right to stay|Derecho legal a quedarse]]:', options: ['[[residency|residencia]]', '[[asylum|asilo]]', '[[migration|migración]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Person who moves to another country|Persona que se muda a otro país]]:', options: ['[[migrant|migrante]]', '[[refugee|refugiado]]', '[[asylum seeker|solicitante de asilo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To become part of a society|Convertirse en parte de una sociedad]]:', options: ['[[to integrate|integrarse]]', '[[to flee|huir]]', '[[to displace|desplazar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[People forced to leave their country|Personas forzadas a dejar su país]]:', options: ['[[internally displaced|desplazados internos]]', '[[refugees|refugiados]]', '[[migrants|migrantes]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cultural diversity|Diversidad cultural]]:', options: ['[[multiculturalism|multiculturalismo]]', '[[society|sociedad]]', '[[borders|fronteras]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u52-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'social-issues', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To send someone back to their country|Devolver a alguien a su país]]:', options: ['[[to deport|deportar]]', '[[to integrate|integrarse]]', '[[to settle|establecerse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
