/**
 * Unidad 14 B2 — Lección 2: Vocabulario (Business)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Business|Negocios]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con el mundo empresarial.';

export const UNIT_14_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u14-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who starts their own business|Persona que inicia su propio negocio]]:', options: ['[[entrepreneur|emprendedor]]', '[[employee|empleado]]', '[[employer|empleador]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A fixed date by which something must be done|Fecha fija para la que algo debe estar hecho]]:', options: ['[[deadline|fecha límite]]', '[[deadlock|punto muerto]]', '[[deal|trato]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A document listing goods or services and their prices|Documento que lista bienes o servicios y sus precios]]:', options: ['[[invoice|factura]]', '[[inventory|inventario]]', '[[investment|inversión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The main office of a company|Oficina principal de una empresa]]:', options: ['[[headquarters|sede]]', '[[headcount|plantilla]]', '[[headhunter|cazatalentos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To discuss terms to reach an agreement|Discutir términos para llegar a un acuerdo]]:', options: ['[[negotiate|negociar]]', '[[navigate|navegar]]', '[[nominate|nombrar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal meeting to assess a candidate for a job|Reunión formal para evaluar a un candidato para un puesto]]:', options: ['[[interview|entrevista]]', '[[introduction|presentación]]', '[[inspection|inspección]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A plan to achieve long-term goals|Plan para lograr objetivos a largo plazo]]:', options: ['[[strategy|estrategia]]', '[[schedule|horario]]', '[[summary|resumen]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Money earned after deducting costs|Dinero ganado tras deducir costes]]:', options: ['[[profit|beneficio]]', '[[loss|pérdida]]', '[[revenue|ingresos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A situation where two companies join to form one|Situación en que dos empresas se unen para formar una]]:', options: ['[[merger|fusión]]', '[[takeover|adquisición hostil]]', '[[partnership|asociación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To promote a product to increase sales|Promocionar un producto para aumentar ventas]]:', options: ['[[market|comercializar]]', '[[manufacture|fabricar]]', '[[manage|gestionar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "meet a ___" → cumplir un plazo|Colocación: "meet a ___" → cumplir un plazo]]', options: ['[[deadline|fecha límite]]', '[[demand|demanda]]', '[[target|objetivo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "close a ___" → cerrar un trato|Colocación: "close a ___" → cerrar un trato]]', options: ['[[deal|trato]]', '[[door|puerta]]', '[[gap|brecha]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "think ___ the box" → pensar de forma creativa|Expresión: "pensar ___ de la caja"]]', options: ['[[outside|fuera]]', '[[inside|dentro]]', '[[around|alrededor]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "run a ___" → dirigir un negocio|Colocación: "run a ___" → dirigir un negocio]]', options: ['[[business|negocio]]', '[[meeting|reunión]]', '[[risk|riesgo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who buys shares in companies|Persona que compra acciones en empresas]]:', options: ['[[shareholder|accionista]]', '[[stakeholder|parte interesada]]', '[[stockholder|accionista]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "on the same ___" → de acuerdo|Expresión: "en la misma ___" → de acuerdo]]', options: ['[[page|página]]', '[[line|línea]]', '[[level|nivel]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "take ___" → asumir responsabilidad|Colocación: "take ___" → asumir responsabilidad]]', options: ['[[responsibility|responsabilidad]]', '[[advantage|ventaja]]', '[[place|lugar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u14-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Business', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal agreement between two parties|Acuerdo formal entre dos partes]]:', options: ['[[contract|contrato]]', '[[contact|contacto]]', '[[context|contexto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
