/**
 * Unidad 50 B2 — Lección 6: Expresión escrita (Repaso 41-49)
 * 18 ejercicios mixtos de repaso
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_50_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u50-l6-w1', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases resumiendo lo que has aprendido en las unidades 41-49. Usa al menos 3 estructuras diferentes.', prompt: '[[Summarise what you have learned in units 41-49. Use at least 3 different structures.|Resume lo que has aprendido en las unidades 41-49. Usa al menos 3 estructuras diferentes.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w2', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta. Repaso de gramática.', questions: [{ question: '[[By next year|Para el año que viene]] [[I|yo]] ____ ____ [[graduated|graduado]] [[from university|de la universidad]].', options: ['[[will have|habré]]', '[[would have|habría]]', '[[have|he]]'], correctAnswer: 'will have', acceptableAnswers: ['will have'], explanation: '[[Future Perfect|Future Perfect]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w3', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando las estructuras de repaso: Cleft, Reporting verb, Inversion.', prompt: '[[John broke the window. She said: "Let\'s go." I have never seen such beauty.|John rompió la ventana. Ella dijo: "Vamos." Nunca he visto tal belleza.]]', expressionHint: '[[Usa: It was... who, suggest + gerund, Never have I...|Usa: It was... who, suggest + gerund, Never have I...]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w4', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con Future Perfect y otra con Mixed Conditional.', prompt: '[[Write two sentences: one with Future Perfect and one with Mixed Conditional.|Escribe dos oraciones: una con Future Perfect y otra con Mixed Conditional.]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w5', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She|Ella]] ____ [[tired|cansada]] — [[she\'s been working|ha estado trabajando]] [[all day|todo el día]].', options: ['[[must be|debe estar]]', '[[can\'t be|no puede estar]]', '[[might be|podría estar]]'], correctAnswer: 'must be', acceptableAnswers: ['must be'], explanation: '[[Modal deduction: must = strong certainty|Deducción modal: must = certeza fuerte]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w6', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre la importancia de la educación. Usa Cleft sentences y Reporting verbs.', prompt: '[[Describe the importance of education. Use Cleft sentences and Reporting verbs.|Describe la importancia de la educación. Usa oraciones hendidas y verbos de reporte.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w7', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando las estructuras de repaso.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. By 2030 I will have ____|1. Para 2030 habré ____]]\n[[2. What I need is ____|2. Lo que necesito es ____]]\n[[3. Never have I ____|3. Nunca he ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w8', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[What|Lo que]] [[I need|necesito]] ____ [[a good night\'s sleep|una buena noche de sueño]].', options: ['[[is|es]]', '[[are|son]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[Cleft sentence: What-clause + is|Oración hendida: What-clause + is]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w9', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre tu experiencia en las unidades 41-49. Usa estructuras variadas.', prompt: '[[Write an introduction about your experience in units 41-49. Use varied structures.|Escribe una introducción sobre tu experiencia en las unidades 41-49. Usa estructuras variadas.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w10', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre suggest + gerund e insist + that + subjunctive.', prompt: '[[Explain the difference between suggest + gerund and insist + that + subjunctive. Use examples.|Explica la diferencia entre suggest + gerund e insist + that + subjunctive. Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w11', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If I|Si yo]] ____ [[studied|estudiado]] [[harder|más]], [[I would be|sería]] [[a doctor now|doctor ahora]].', options: ['[[had|hubiera]]', '[[have|he]]', '[[would have|habría]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Mixed conditional|Condicional mixto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w12', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte usando Inversion: I have never seen such beauty. We realised it only then.', prompt: '[[Convert using Inversion: I have never seen such beauty. We realised it only then.|Convierte usando Inversión: Nunca he visto tal belleza. Solo entonces nos dimos cuenta.]]', expressionHint: '[[Usa: Never have I..., Only then did we...|Usa: Never have I..., Only then did we...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w13', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con: Future Perfect, Modal deduction (must/can\'t), Cleft sentence.', prompt: '[[Write three sentences with: Future Perfect, Modal deduction (must/can\'t), Cleft sentence.|Escribe tres oraciones con: Future Perfect, Modal deduction (must/can\'t), Cleft sentence.]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w14', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She|Ella]] ____ [[going|ir]] [[to the cinema|al cine]].', options: ['[[suggested|sugirió]]', '[[suggest|sugiere]]', '[[suggesting|sugiriendo]]'], correctAnswer: 'suggested', acceptableAnswers: ['suggested'], explanation: '[[Suggest + gerund|Suggest + gerundio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w15', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre tu progreso en B2. Usa: Future Perfect, Cleft, Reporting verbs, Inversion.', prompt: '[[Describe your progress in B2. Use: Future Perfect, Cleft, Reporting verbs, Inversion.|Describe tu progreso en B2. Usa: Future Perfect, Cleft, Reporting verbs, Inversion.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w16', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando a un estudiante sobre las unidades 41-49. Usa suggest, recommend, urge.', prompt: '[[Give advice about units 41-49. Use suggest, recommend, urge.|Da consejos sobre las unidades 41-49. Usa suggest, recommend, urge.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w17', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Never|Nunca]] ____ [[I|yo]] ____ [[seen|visto]] [[such a beautiful sunset|un atardecer tan hermoso]].', options: ['[[have|he]]', '[[has|ha]]', '[[had|había]]'], correctAnswer: 'have', acceptableAnswers: ['have'], explanation: '[[Inversion: Never + have + subject + past participle|Inversión: Never + have + sujeto + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b2-u50-l6-w18', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre lo que has logrado en las unidades 41-49. Usa estructuras variadas.', prompt: '[[Write a short conclusion about what you have achieved in units 41-49. Use varied structures.|Escribe una breve conclusión sobre lo que has logrado en las unidades 41-49. Usa estructuras variadas.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
