/**
 * Unidad 23 B2 — Lección 6: Expresión escrita (Home & Living)
 * 18 ejercicios (B2: recreado con casos reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_23_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u23-l6-w1', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 3–4 sentences describing a situation where something was about to happen at home. Use: be about to, break down, bring up.|Escribe 3–4 frases describiendo una situación en la que algo estaba a punto de pasar en casa. Usa: be about to, break down, bring up.]]', prompt: '[[Describe a situation where something was about to happen at home. Use: be about to, break down, bring up.|Describe una situación en la que algo estaba a punto de pasar en casa. Usa: be about to, break down, bring up.]]', targetLevel: 'B2', writingType: 'story', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with the correct phrasal verb: be about to, break down, bring up, bring about, bring in.|Completa con el phrasal verb correcto: be about to, break down, bring up, bring about, bring in.]]', questions: [{ question: '[[I was|Estaba]] ____ [[leave the house|salir de casa]] [[when|cuando]] [[the plumber arrived|el fontanero llegó]].', options: ['[[about to|a punto de]]', '[[up to|hasta]]', '[[for|para]]'], correctAnswer: 'about to', acceptableAnswers: ['about to'], explanation: '[[Be about to + infinitive|Be about to + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w3', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Rewrite using bring up or bring about.|Reescribe usando bring up o bring about.]]', prompt: '[[She mentioned the topic of redecorating at the meeting. It caused a long discussion.|Mencionó el tema de redecorar en la reunión. Causó una larga discusión.]]', expressionHint: '[[Usa: "She brought up... which brought about..."|Usa: "She brought up... which brought about..."]]', targetLength: '1-2 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w4', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 2 sentences: one with break down (machine or talks) and one with bring in (expert).|Escribe 2 frases: una con break down (máquina o conversaciones) y otra con bring in (experto).]]', prompt: '[[Write two sentences: one with break down (machine or talks) and one with bring in (expert).|Escribe dos oraciones: una con break down (máquina o conversaciones) y otra con bring in (experto).]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with the correct phrasal verb.|Completa con el phrasal verb correcto.]]', questions: [{ question: '[[The boiler|La caldera]] ____ [[last winter|el invierno pasado]].', options: ['[[broke down|se averió]]', '[[broke in|entró por la fuerza]]', '[[broke out|estalló]]'], correctAnswer: 'broke down', acceptableAnswers: ['broke down'], explanation: '[[Break down = stop working|Break down = dejar de funcionar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w6', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 3–4 sentences about a home problem that was solved. Use: break down, bring up, bring in.|Escribe 3–4 frases sobre un problema del hogar que se resolvió. Usa: break down, bring up, bring in.]]', prompt: '[[Describe a home problem that was solved. Use: break down, bring up, bring in.|Describe un problema del hogar que se resolvió. Usa: break down, bring up, bring in.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w7', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete the sentences with your own ideas using phrasal verbs.|Completa las frases con ideas propias usando phrasal verbs.]]', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. I was about to ____ when...|1. Estaba a punto de ____ cuando...]]\n[[2. The ____ broke down and...|2. El ____ se averió y...]]\n[[3. She brought up ____ at the meeting.|3. Ella mencionó ____ en la reunión.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with "bring up" or "bring about".|Completa con "bring up" o "bring about".]]', questions: [{ question: '[[She|Ella]] ____ [[her children|a sus hijos]] [[to value|a valorar]] [[a tidy home|un hogar ordenado]].', options: ['[[brought up|crió]]', '[[brought about|causó]]', '[[brought in|introdujo]]'], correctAnswer: 'brought up', acceptableAnswers: ['brought up'], explanation: '[[Bring up = raise children|Bring up = criar niños]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w9', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write the introduction of an article (40–60 words) about the importance of a comfortable home.|Escribe la introducción de un artículo (40–60 palabras) sobre la importancia de un hogar cómodo.]]', prompt: '[[Write an introduction to an article about the importance of a comfortable home. Use at least one phrasal verb (be about to, break down, bring up, bring about, bring in).|Escribe la introducción de un artículo sobre la importancia de un hogar cómodo. Usa al menos un phrasal verb.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w10', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 2–3 sentences explaining what can bring about a breakdown in home projects. Use bring about and break down.|Escribe 2–3 frases explicando qué puede causar que los proyectos del hogar fracasen. Usa bring about y break down.]]', prompt: '[[Explain what can bring about a breakdown in home projects. Use bring about and break down.|Explica qué puede causar que los proyectos del hogar fracasen. Usa bring about y break down.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with the correct phrasal verb.|Completa con el phrasal verb adecuado.]]', questions: [{ question: '[[The renovation|La reforma]] ____ [[major changes|grandes cambios]] [[in the house|en la casa]].', options: ['[[brought about|causó]]', '[[brought up|crió]]', '[[brought in|introdujo]]'], correctAnswer: 'brought about', acceptableAnswers: ['brought about'], explanation: '[[Bring about = cause to happen|Bring about = causar que ocurra]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w12', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Combine these sentences into one using be about to.|Convierte estas frases en una sola usando be about to.]]', prompt: '[[We were going to move in. We found a leak.|Íbamos a mudarnos. Encontramos una fuga.]]', expressionHint: '[[Usa: "We were about to move in when we found a leak"|Usa: "We were about to move in when we found a leak"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w13', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 3 sentences with phrasal verbs (one with be about to, one with break down and one with bring up).|Escribe 3 oraciones con phrasal verbs (una con be about to, otra con break down y otra con bring up).]]', prompt: '[[Write three sentences with phrasal verbs:|Escribe tres oraciones con phrasal verbs:]]\n[[- one with "be about to"|- una con "be about to"]]\n[[- one with "break down"|- una con "break down"]]\n[[- one with "bring up"|- una con "bring up"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with "break down" or "bring in".|Completa con "break down" o "bring in".]]', questions: [{ question: '[[The family|La familia]] ____ [[an interior designer|un diseñador de interiores]] [[to advise|para asesorar]] [[on the project|sobre el proyecto]].', options: ['[[brought in|trajo]]', '[[broke down|se averió]]', '[[brought up|mencionó]]'], correctAnswer: 'brought in', acceptableAnswers: ['brought in'], explanation: '[[Bring in = introduce someone to help|Bring in = traer a alguien para ayudar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w15', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 60–80 words about a time when something at home broke down and how it was resolved.|Escribe 60–80 palabras sobre una vez que algo en casa se averió y cómo se resolvió.]]', prompt: '[[Describe a time when something at home broke down and how it was resolved. Use: break down, bring up, bring in, bring about.|Describe una vez que algo en casa se averió y cómo se resolvió. Usa: break down, bring up, bring in, bring about.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w16', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write 2–3 sentences advising how to avoid talks about a renovation breaking down.|Escribe 2–3 frases aconsejando cómo evitar que las conversaciones sobre una reforma fracasen.]]', prompt: '[[Give advice on how to avoid talks about a renovation breaking down. Use break down and bring up.|Da consejos sobre cómo evitar que las conversaciones sobre una reforma fracasen. Usa break down y bring up.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Complete with the correct phrasal verb.|Completa con el phrasal verb correcto.]]', questions: [{ question: '[[The talks|Las conversaciones]] ____ [[about the extension|sobre la ampliación]] [[after|después de]] [[hours of discussion|horas de discusión]].', options: ['[[broke down|fracasaron]]', '[[broke in|entraron por la fuerza]]', '[[broke out|estallaron]]'], correctAnswer: 'broke down', acceptableAnswers: ['broke down'], explanation: '[[Break down = fail (talks)|Break down = fracasar (conversaciones)]].' }] }, topicName: 'Writing' },
  { id: 'b2-u23-l6-w18', type: 'writing', level: 'B2', topic: 'Home & Living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: '[[Write a short conclusion (40–60 words) explaining why bringing in experts can improve home projects. Use bring in and bring about.|Redacta una breve conclusión (40–60 palabras) explicando por qué traer expertos puede mejorar los proyectos del hogar. Usa bring in y bring about.]]', prompt: '[[Write a short conclusion explaining why bringing in experts can improve home projects. Use bring in and bring about.|Escribe una breve conclusión explicando por qué traer expertos puede mejorar los proyectos del hogar. Usa bring in y bring about.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
