/**
 * Unidad 20 B2 — Lección 1: Gramática (Repaso 16-19: Passive, Modal Passive, So/such/too/enough, Comparatives)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Repaso 16–19|Repaso 16–19]]';
const INSTRUCTIONS = 'Repaso de pasiva, pasiva con modales, have something done, so/such/too/enough y comparativos/superlativos avanzados.';

export const UNIT_20_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u20-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The new app ____ developed by a small team last year.|La nueva app ____ fue desarrollada por un equipo pequeño el año pasado.]]', options: ['[[was|fue]]', '[[is|es]]', '[[has been|ha sido]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Passive past simple|Pasiva pasado simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The experiment ____ be repeated to confirm the results.|El experimento ____ debe ser repetido para confirmar los resultados.]]', options: ['[[must|debe]]', '[[might|podría]]', '[[can|puede]]'], correctAnswer: 0, explanation: '[[Modal passive: obligation|Pasiva con modal: obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The room was ____ small ____ fit everyone.|La habitación era ____ pequeña ____ para caber todos.]]', options: ['[[too / to|demasiado... para]]', '[[so / that|tan... que]]', '[[enough / to|suficiente... para]]'], correctAnswer: 'too / to', acceptableAnswers: ['too / to'], explanation: '[[Too + adj + to-infinitive|Too + adj + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She\'s ____ the most talented scientist in the department.|Es ____ la científica más talentosa del departamento.]]', options: ['[[by far|con diferencia]]', '[[much|mucho]]', '[[slightly|ligeramente]]'], correctAnswer: 0, explanation: '[[By far + superlative|By far + superlativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We ____ our roof repaired last month.|Nos ____ repararon el tejado el mes pasado.]]', options: ['[[had|hicimos]]', '[[got|conseguimos]]', '[[made|obligamos]]'], correctAnswer: 'had', acceptableAnswers: ['had', 'got'], explanation: '[[Have something done|Have something done]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The data ____ being analysed at the moment.|Los datos ____ están siendo analizados en este momento.]]', options: ['[[are|están]]', '[[is|es]]', '[[was|fue]]'], correctAnswer: 0, explanation: '[[Passive present continuous|Pasiva presente continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It was ____ a difficult exam ____ most students failed.|Era ____ un examen difícil ____ la mayoría suspendió.]]', options: ['[[such|tan]]', '[[so|tan]]', '[[too|demasiado]]'], correctAnswer: 'such', acceptableAnswers: ['such'], explanation: '[[Such + noun phrase|Such + sintagma nominal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The more you practise, ____ you become.|Cuanto más practicas, ____ te vuelves.]]', options: ['[[the better|mejor]]', '[[better|mejor]]', '[[the best|el mejor]]'], correctAnswer: 0, explanation: '[[The more... the more|Cuanto más... más]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The software ____ be updated regularly for security.|El software ____ debe ser actualizado regularmente por seguridad.]]', options: ['[[should|debería]]', '[[mustn\'t|no debe]]', '[[needn\'t|no necesita]]'], correctAnswer: 'should', acceptableAnswers: ['should', 'must', 'has to'], explanation: '[[Modal passive: recommendation|Pasiva con modal: recomendación]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I don\'t have ____ time ____ finish this today.|No tengo ____ tiempo ____ terminar esto hoy.]]', options: ['[[enough / to|suficiente... para]]', '[[too / to|demasiado... para]]', '[[so / that|tan... que]]'], correctAnswer: 0, explanation: '[[Enough + noun + to-infinitive|Enough + sustantivo + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The report ____ been sent to all stakeholders.|El informe ____ ha sido enviado a todos los interesados.]]', options: ['[[has|ha]]', '[[have|han]]', '[[had|había]]'], correctAnswer: 'has', acceptableAnswers: ['has'], explanation: '[[Passive present perfect|Pasiva presente perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She\'s ____ faster than she was last year.|Está ____ más rápida que el año pasado.]]', options: ['[[much|mucho]]', '[[the most|la más]]', '[[by far|con diferencia]]'], correctAnswer: 0, explanation: '[[Much + comparative|Much + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The samples ____ be stored at a low temperature.|Las muestras ____ deben ser almacenadas a baja temperatura.]]', options: ['[[must|deben]]', '[[can|pueden]]', '[[might|podrían]]'], correctAnswer: 'must', acceptableAnswers: ['must', 'have to'], explanation: '[[Modal passive: obligation|Pasiva con modal: obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The device ____ being tested when the power failed.|El dispositivo ____ estaba siendo probado cuando falló la corriente.]]', options: ['[[was|estaba]]', '[[is|está]]', '[[has been|ha sido]]'], correctAnswer: 0, explanation: '[[Passive past continuous|Pasiva pasado continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The dish was ____ spicy ____ I couldn\'t eat it.|El plato estaba ____ picante ____ no pude comerlo.]]', options: ['[[so|tan]]', '[[such|tan]]', '[[too|demasiado]]'], correctAnswer: 'so', acceptableAnswers: ['so'], explanation: '[[So + adj + that|So + adj + that]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They ____ their car serviced every six months.|Ellos ____ hacen revisar el coche cada seis meses.]]', options: ['[[have|hacen]]', '[[make|obligan]]', '[[let|dejan]]'], correctAnswer: 0, explanation: '[[Have something done|Have something done]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The results ____ be published next month.|Los resultados ____ serán publicados el próximo mes.]]', options: ['[[will|serán]]', '[[would|serían]]', '[[are|son]]'], correctAnswer: 'will', acceptableAnswers: ['will'], explanation: '[[Passive future|Pasiva futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u20-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The new model is ____ better than the previous one.|El nuevo modelo es ____ mejor que el anterior.]]', options: ['[[slightly|ligeramente]]', '[[the most|el más]]', '[[by far|con diferencia]]'], correctAnswer: 0, explanation: '[[Slightly + comparative|Slightly + comparativo]].' }] }, topicName: 'Grammar' },
];
