/**
 * Unidad 28 B2 — Lección 5: Expresión oral (Food & Gastronomy)
 * 18 ejercicios (B2: colocaciones verbo+sustantivo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_28_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u28-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I need to take a break|Necesito tomar un descanso]] [[from the kitchen|de la cocina]] — [[I\'ve been cooking for hours|he estado cocinando durante horas]].', expectedResponse: 'I need to take a break from the kitchen — I\'ve been cooking for hours.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We made a decision yesterday|Tomamos una decisión ayer]] — [[we\'re cancelling the dinner party because of the ingredients|cancelamos la cena por los ingredientes]].', expectedResponse: 'We made a decision yesterday — we\'re cancelling the dinner party because of the ingredients.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The chef made a mistake|El chef cometió un error]] [[when he added too much salt|cuando añadió demasiada sal]] [[and the dish was ruined|y el plato quedó arruinado]].', expectedResponse: 'The chef made a mistake when he added too much salt and the dish was ruined.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Can you take a photo of the dish|¿Puedes hacer una foto del plato]]?', expectedResponse: 'Can you take a photo of the dish?' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He took responsibility for the menu|Asumió la responsabilidad del menú]] [[last week|la semana pasada]].', expectedResponse: 'He took responsibility for the menu last week.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We made a lot of progress this month|Hicimos mucho progreso este mes]] — [[the new recipe is almost finished|la nueva receta está casi terminada]].', expectedResponse: 'We made a lot of progress this month — the new recipe is almost finished.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I made an effort to check the recipe|Hice un esfuerzo por consultar la receta]] [[before cooking today|antes de cocinar hoy]].', expectedResponse: 'I made an effort to check the recipe before cooking today.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She took a chance and tried the exotic cuisine|Se arriesgó y probó la cocina exótica]] [[despite her doubts|a pesar de sus dudas]].', expectedResponse: 'She took a chance and tried the exotic cuisine despite her doubts.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[We have a meeting every Monday|Tenemos una reunión cada lunes]] [[to discuss the restaurant menu|para discutir el menú del restaurante]].', expectedResponse: 'We have a meeting every Monday to discuss the restaurant menu.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en las colocaciones.', targetText: '[[I had a look at the menu|Eché un vistazo al menú]] [[and it looks good for tonight|y parece bien para esta noche]].', expectedResponse: 'I had a look at the menu and it looks good for tonight.' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s11', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe una decisión que tuviste que tomar (make a decision) sobre comida o un menú.', prompt: '[[Describe a decision you had to make about food or a menu. Use: make a decision, take a chance, take responsibility.|Describe una decisión que tuviste que tomar sobre comida o un menú. Usa: make a decision, take a chance, take responsibility.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s12', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica cuándo es importante tomar un descanso de la cocina (take a break).', prompt: '[[Explain when it is important to take a break from the kitchen. Use: take a break, make progress, make an effort.|Explica cuándo es importante tomar un descanso de la cocina. Usa: take a break, make progress, make an effort.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s13', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿alguna vez cometiste un error (make a mistake) cocinando y te afectó?', prompt: '[[Have you ever made a mistake while cooking and it affected you? Give examples.|¿Alguna vez cometiste un error cocinando y te afectó? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s14', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una vez que te arriesgaste (take a chance) con una receta nueva y qué pasó.', prompt: '[[Describe a time when you took a chance with a new recipe and what happened. Use: take a chance, make a decision, make progress.|Describe una vez que te arriesgaste con una receta nueva y qué pasó. Usa: take a chance, make a decision, make progress.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s15', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these collocations in your own sentences:|Usa estas colocaciones en tus propias oraciones:]]\n[[- take a break|- take a break]]\n[[- make a decision|- make a decision]]\n[[- take responsibility|- take responsibility]]\n[[- make progress|- make progress]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s16', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una reunión sobre menú (have a meeting) y qué sugerencias hiciste (make a suggestion).', prompt: '[[Describe a meeting about a menu you had and what suggestions you made. Use: have a meeting, make a suggestion, take a note.|Describe una reunión sobre menú que tuviste y qué sugerencias hiciste. Usa: have a meeting, make a suggestion, take a note.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s17', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe el progreso que has hecho (make progress) en algo relacionado con la cocina.', prompt: '[[Describe the progress you have made in something related to cooking. Use: make progress, make an effort, take a break.|Describe el progreso que has hecho en algo relacionado con la cocina. Usa: make progress, make an effort, take a break.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u28-l5-s18', type: 'speaking', level: 'B2', topic: 'Food & Gastronomy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cómo causas buena impresión (make a good impression) cuando hablas de gastronomía?', prompt: '[[How do you make a good impression when discussing gastronomy? Use make a good impression and make an effort.|¿Cómo causas buena impresión cuando hablas de gastronomía? Usa make a good impression y make an effort.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
