/**
 * Unidad 53 B2 — Lección 6: Expresión escrita (The Future of Work)
 * 18 ejercicios (B2: future continuous, future perfect, trabajo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_53_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u53-l6-w1', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo cómo será tu trabajo en 10 años. Usa: will be, will have.', prompt: '[[Describe how your work will be in 10 years. Use: will be, will have.|Describe cómo será tu trabajo en 10 años. Usa: will be, will have.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w2', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta (future continuous o future perfect).', questions: [{ question: '[[By 2030|Para 2030]], [[many jobs|muchos trabajos]] ____ ____ ____ [[by automation|por la automatización]].', options: ['[[will have been replaced|habrán sido reemplazados]]', '[[will be replacing|estarán reemplazando]]', '[[are replacing|están reemplazando]]'], correctAnswer: 'will have been replaced', acceptableAnswers: ['will have been replaced'], explanation: '[[Future perfect passive|Pasiva futuro perfecto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w3', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando future continuous: At 3pm tomorrow I have a video call.', prompt: '[[Rewrite using future continuous: At 3pm tomorrow I have a video call.|Reescribe usando futuro continuo: Mañana a las 3pm tengo una videollamada.]]', expressionHint: '[[Usa: will be + -ing|Usa: will be + -ing]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w4', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "will be + -ing" y otra con "will have + past participle".', prompt: '[[Write two sentences: one with "will be + -ing" and one with "will have + past participle".|Escribe dos oraciones: una con "will be + -ing" y otra con "will have + participio pasado".]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w5', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[At 3pm tomorrow|Mañana a las 3pm]], [[I|yo]] ____ ____ [[a video call|una videollamada]].', options: ['[[will be having|estaré teniendo]]', '[[will have had|habré tenido]]', '[[have had|he tenido]]'], correctAnswer: 'will be having', acceptableAnswers: ['will be having'], explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w6', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre qué habrás logrado en tu carrera para 2030. Usa: will have.', prompt: '[[Describe what you will have achieved in your career by 2030. Use: will have.|Describe qué habrás logrado en tu carrera para 2030. Usa: will have.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w7', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando future continuous y future perfect.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. This time next year I will be ____|1. A esta hora el año que viene estaré ____]]\n[[2. By 2030 I will have ____|2. Para 2030 habré ____]]\n[[3. At noon tomorrow we will be ____|3. Mañana al mediodía estaremos ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w8', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[By next year|Para el año que viene]], [[she|ella]] ____ ____ ____ [[ten years|diez años]] [[in this company|en esta empresa]].', options: ['[[will have worked|habrá trabajado]]', '[[will be working|estará trabajando]]', '[[is working|está trabajando]]'], correctAnswer: 'will have worked', acceptableAnswers: ['will have worked'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w9', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre el futuro del trabajo. Usa: will be, will have.', prompt: '[[Write an introduction to an article about the future of work. Use: will be, will have.|Escribe la introducción de un artículo sobre el futuro del trabajo. Usa: will be, will have.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w10', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre future continuous y future perfect.', prompt: '[[Explain the difference between future continuous and future perfect. Use examples.|Explica la diferencia entre futuro continuo y futuro perfecto. Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w11', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[This time next week|A esta hora la próxima semana]], [[we|nosotros]] ____ ____ [[remotely|en remoto]].', options: ['[[will be working|estaremos trabajando]]', '[[will have worked|habremos trabajado]]', '[[are working|estamos trabajando]]'], correctAnswer: 'will be working', acceptableAnswers: ['will be working'], explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w12', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte a future perfect: They finish the project by the end of the month.', prompt: '[[Convert to future perfect: They finish the project by the end of the month.|Convierte a futuro perfecto: Terminan el proyecto para final de mes.]]', expressionHint: '[[Usa: will have + past participle|Usa: will have + participio pasado]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w13', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con: future continuous, future perfect, future perfect passive.', prompt: '[[Write three sentences with: future continuous, future perfect, future perfect passive.|Escribe tres oraciones con: futuro continuo, futuro perfecto, pasiva futuro perfecto.]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w14', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[By the end of the month|Para final de mes]], [[they|ellos]] ____ ____ ____ [[the project|el proyecto]].', options: ['[[will have finished|habrán terminado]]', '[[will be finishing|estarán terminando]]', '[[have finished|han terminado]]'], correctAnswer: 'will have finished', acceptableAnswers: ['will have finished'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w15', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre el futuro del trabajo. Usa: will be, will have, automation, remote work.', prompt: '[[Describe the future of work. Use: will be, will have, automation, remote work.|Describe el futuro del trabajo. Usa: will be, will have, automation, remote work.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w16', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases sobre las habilidades que necesitarás en el futuro. Usa: will be, will have.', prompt: '[[Describe skills you will need in the future. Use: will be, will have.|Describe las habilidades que necesitarás en el futuro. Usa: will be, will have.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w17', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[In 2050|En 2050]], [[most workers|la mayoría de trabajadores]] ____ ____ ____ [[from home|desde casa]].', options: ['[[will be working|estarán trabajando]]', '[[will have worked|habrán trabajado]]', '[[work|trabajan]]'], correctAnswer: 'will be working', acceptableAnswers: ['will be working'], explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u53-l6-w18', type: 'writing', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre el futuro del trabajo. Usa: will be, will have.', prompt: '[[Write a short conclusion about the future of work. Use: will be, will have.|Escribe una breve conclusión sobre el futuro del trabajo. Usa: will be, will have.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
