/**
 * Unidad 53 B2 — Lección 1: Gramática (Future Continuous, Future Perfect)
 * 18 ejercicios (B2: futuro continuo, futuro perfecto) — Tema: The Future of Work
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Future Continuous, Future Perfect|Futuro continuo, Futuro perfecto]]';
const INSTRUCTIONS = 'Elige la forma correcta (future continuous o future perfect).';

export const UNIT_53_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u53-l1-g1', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By 2030|Para 2030]], [[many jobs|muchos trabajos]] ____ ____ ____ [[by automation|por la automatización]].', options: ['[[will have been replaced|habrán sido reemplazados]]', '[[will be replacing|estarán reemplazando]]', '[[are replacing|están reemplazando]]'], correctAnswer: 'will have been replaced', acceptableAnswers: ['will have been replaced'], explanation: '[[Future perfect: action completed by a future time|Futuro perfecto: acción completada para un momento futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[At 3pm tomorrow|Mañana a las 3pm]], [[I|yo]] ____ ____ [[a video call|una videollamada]].', options: ['[[will be having|estaré teniendo]]', '[[will have had|habré tenido]]', '[[have had|he tenido]]'], correctAnswer: 0, explanation: '[[Future continuous: action in progress at a future time|Futuro continuo: acción en progreso en un momento futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g3', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By next year|Para el año que viene]], [[she|ella]] ____ ____ ____ [[ten years|diez años]] [[in this company|en esta empresa]].', options: ['[[will have worked|habrá trabajado]]', '[[will be working|estará trabajando]]', '[[is working|está trabajando]]'], correctAnswer: 'will have worked', acceptableAnswers: ['will have worked'], explanation: '[[Future perfect: duration completed by a future time|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This time next week|A esta hora la próxima semana]], [[we|nosotros]] ____ ____ [[remotely|en remoto]].', options: ['[[will be working|estaremos trabajando]]', '[[will have worked|habremos trabajado]]', '[[are working|estamos trabajando]]'], correctAnswer: 0, explanation: '[[Future continuous: action in progress at a specific future time|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g5', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By the end of the month|Para final de mes]], [[they|ellos]] ____ ____ ____ [[the project|el proyecto]].', options: ['[[will have finished|habrán terminado]]', '[[will be finishing|estarán terminando]]', '[[have finished|han terminado]]'], correctAnswer: 'will have finished', acceptableAnswers: ['will have finished'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In 2050|En 2050]], [[most workers|la mayoría de trabajadores]] ____ ____ [[from home|desde casa]].', options: ['[[will be working|estarán trabajando]]', '[[will have worked|habrán trabajado]]', '[[work|trabajan]]'], correctAnswer: 0, explanation: '[[Future continuous: prediction about future state|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g7', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By then|Para entonces]], [[the gig economy|la economía gig]] ____ ____ ____ [[traditional jobs|los trabajos tradicionales]].', options: ['[[will have transformed|habrá transformado]]', '[[will be transforming|estará transformando]]', '[[transforms|transforma]]'], correctAnswer: 'will have transformed', acceptableAnswers: ['will have transformed'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[At noon tomorrow|Mañana al mediodía]], [[he|él]] ____ ____ [[a training session|una sesión de formación]].', options: ['[[will be attending|estará asistiendo]]', '[[will have attended|habrá asistido]]', '[[attends|asiste]]'], correctAnswer: 0, explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g9', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By 2028|Para 2028]], [[AI|la IA]] ____ ____ ____ [[many routine tasks|muchas tareas rutinarias]].', options: ['[[will have automated|habrá automatizado]]', '[[will be automating|estará automatizando]]', '[[automates|automatiza]]'], correctAnswer: 'will have automated', acceptableAnswers: ['will have automated'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This time next month|A esta hora el próximo mes]], [[I|yo]] ____ ____ [[new skills|nuevas habilidades]].', options: ['[[will be learning|estaré aprendiendo]]', '[[will have learnt|habré aprendido]]', '[[learn|aprendo]]'], correctAnswer: 0, explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g11', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By retirement|Para la jubilación]], [[she|ella]] ____ ____ ____ [[in five different companies|en cinco empresas diferentes]].', options: ['[[will have worked|habrá trabajado]]', '[[will be working|estará trabajando]]', '[[works|trabaja]]'], correctAnswer: 'will have worked', acceptableAnswers: ['will have worked'], explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In ten years|En diez años]], [[remote work|el teletrabajo]] ____ ____ [[the norm|la norma]].', options: ['[[will be becoming|estará convirtiéndose en]]', '[[will have become|habrá llegado a ser]]', '[[becomes|se convierte en]]'], correctAnswer: 1, explanation: '[[Future perfect: change completed by future time|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g13', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[At 9am on Monday|El lunes a las 9am]], [[the team|el equipo]] ____ ____ [[the meeting|la reunión]].', options: ['[[will be starting|estará empezando]]', '[[will have started|habrá empezado]]', '[[starts|empieza]]'], correctAnswer: 'will be starting', acceptableAnswers: ['will be starting'], explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By the deadline|Para la fecha límite]], [[we|nosotros]] ____ ____ ____ [[the report|el informe]].', options: ['[[will have submitted|habremos entregado]]', '[[will be submitting|estaremos entregando]]', '[[submit|entregamos]]'], correctAnswer: 0, explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g15', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[In the future|En el futuro]], [[workers|los trabajadores]] ____ ____ [[multiple careers|múltiples carreras]].', options: ['[[will be having|tendrán]]', '[[will have had|habrán tenido]]', '[[have|tienen]]'], correctAnswer: 'will be having', acceptableAnswers: ['will be having'], explanation: '[[Future continuous: ongoing situation in future|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By next Friday|Para el próximo viernes]], [[they|ellos]] ____ ____ ____ [[the contract|el contrato]].', options: ['[[will have signed|habrán firmado]]', '[[will be signing|estarán firmando]]', '[[sign|firman]]'], correctAnswer: 0, explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g17', type: 'fill-blank', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This time next year|A esta hora el año que viene]], [[I|yo]] ____ ____ [[a new role|un nuevo rol]].', options: ['[[will be doing|estaré desempeñando]]', '[[will have done|habré desempeñado]]', '[[do|desempeño]]'], correctAnswer: 'will be doing', acceptableAnswers: ['will be doing'], explanation: '[[Future continuous|Futuro continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u53-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By 2040|Para 2040]], [[technology|la tecnología]] ____ ____ ____ [[how we work|cómo trabajamos]].', options: ['[[will have changed|habrá cambiado]]', '[[will be changing|estará cambiando]]', '[[changes|cambia]]'], correctAnswer: 0, explanation: '[[Future perfect|Futuro perfecto]].' }] }, topicName: 'Grammar' },
];
