/**
 * Unidad 32 B2 — Lección 6: Expresión escrita (Environment extended)
 * 18 ejercicios (B2: cuantificadores y medio ambiente)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_32_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u32-l6-w1', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo amenazas ambientales en tu región. Usa: all, most, each.', prompt: '[[Describe environmental threats in your region. Use: all, most, each.|Describe amenazas ambientales en tu región. Usa: all, most, each.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el cuantificador correcto: all, most, each, every, both.', questions: [{ question: '[[____ of the trees in the park were planted last year|____ de los árboles del parque fueron plantados el año pasado]].', options: ['[[All|Todos]]', '[[Most|La mayoría de]]', '[[Each|Cada uno]]'], correctAnswer: 'All', acceptableAnswers: ['All'], explanation: '[[All = 100%|All = 100%]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w3', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando most o both.', prompt: '[[Most rivers are polluted. Both governments agreed.|La mayoría de ríos están contaminados. Ambos gobiernos acordaron.]]', expressionHint: '[[Usa: "Most of the rivers are polluted" y "Both governments agreed"|Usa: "Most of the rivers are polluted" y "Both governments agreed"]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w4', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con each y otra con every.', prompt: '[[Write two sentences: one with each (individual) and one with every (regularity).|Escribe dos oraciones: una con each (individual) y otra con every (regularidad).]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el cuantificador correcto.', questions: [{ question: '[[____ single day we recycle our waste|____ día reciclamos nuestros residuos]].', options: ['[[Every|Cada]]', '[[All|Todos]]', '[[Each|Cada uno]]'], correctAnswer: 'Every', acceptableAnswers: ['Every'], explanation: '[[Every for regularity|Every para regularidad]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w6', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre cómo gobiernos y empresas pueden colaborar. Usa: both, all, most.', prompt: '[[Describe how governments and businesses can collaborate. Use: both, all, most.|Describe cómo gobiernos y empresas pueden colaborar. Usa: both, all, most.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w7', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando cuantificadores.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. All of the ____ in my city ____|1. Todos los ____ en mi ciudad ____]]\n[[2. Most of the ____ are ____|2. La mayoría de los ____ son ____]]\n[[3. Each ____ has ____|3. Cada ____ tiene ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "each" o "every".', questions: [{ question: '[[____ ecosystem has its own delicate balance|____ ecosistema tiene su propio balance delicado]].', options: ['[[Each|Cada]]', '[[Every|Cada]]', '[[All|Todos]]'], correctAnswer: 'Each', acceptableAnswers: ['Each'], explanation: '[[Each = individual|Each = individual]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w9', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre la biodiversidad.', prompt: '[[Write an introduction to an article about biodiversity. Use: all, most, each, habitat, endangered.|Escribe la introducción de un artículo sobre biodiversidad. Usa: all, most, each, habitat, endangered.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w10', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre "all" y "most".', prompt: '[[Explain the difference between "all" and "most". Use examples from environment.|Explica la diferencia entre "all" y "most". Usa ejemplos del medio ambiente.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el cuantificador adecuado.', questions: [{ question: '[[____ governments agreed to reduce emissions|____ gobiernos acordaron reducir emisiones]].', options: ['[[Both|Ambos]]', '[[All|Todos]]', '[[Each|Cada]]'], correctAnswer: 'Both', acceptableAnswers: ['Both'], explanation: '[[Both = two|Both = dos]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w12', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte estas frases en una usando both.', prompt: '[[The government supports the project. Businesses support the project.|El gobierno apoya el proyecto. Las empresas apoyan el proyecto.]]', expressionHint: '[[Usa: "Both the government and businesses support the project"|Usa: "Both the government and businesses support the project"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w13', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con cuantificadores (una con all, otra con most y otra con each).', prompt: '[[Write three sentences with quantifiers:|Escribe tres oraciones con cuantificadores:]]\n[[- one with "all"|- una con "all"]]\n[[- one with "most"|- una con "most"]]\n[[- one with "each"|- una con "each"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "most of" o "all of".', questions: [{ question: '[[____ the plastic in the ocean comes from land|____ el plástico del océano proviene de tierra]].', options: ['[[Most of|La mayoría de]]', '[[All of|Todo]]', '[[Each of|Cada uno de]]'], correctAnswer: 'Most of', acceptableAnswers: ['Most of'], explanation: '[[Most of = majority|Most of = mayoría]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w15', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre cómo tu comunidad protege el medio ambiente.', prompt: '[[Describe how your community protects the environment. Use: biodiversity, conservation, raise awareness, habitat, renewable energy.|Describe cómo tu comunidad protege el medio ambiente. Usa: biodiversity, conservation, raise awareness, habitat, renewable energy.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w16', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando cómo reducir la huella de carbono.', prompt: '[[Give advice on how to reduce your carbon footprint. Use: every, each, reuse, recycle, renewable energy.|Da consejos sobre cómo reducir tu huella de carbono. Usa: every, each, reuse, recycle, renewable energy.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el cuantificador correcto.', questions: [{ question: '[[____ wind and solar are renewable energy sources|____ viento y solar son fuentes de energía renovables]].', options: ['[[Both|Ambos]]', '[[All|Todos]]', '[[Each|Cada]]'], correctAnswer: 'Both', acceptableAnswers: ['Both'], explanation: '[[Both = two things|Both = dos cosas]].' }] }, topicName: 'Writing' },
  { id: 'b2-u32-l6-w18', type: 'writing', level: 'B2', topic: 'Environment (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué todos debemos actuar por el medio ambiente.', prompt: '[[Write a short conclusion explaining why we all must act for the environment. Use: all, each, every, raise awareness, take responsibility.|Escribe una breve conclusión explicando por qué todos debemos actuar por el medio ambiente. Usa: all, each, every, raise awareness, take responsibility.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
