/**
 * Unidad 39 B2 — Lección 1: Gramática (Phrasal Verbs 6: TURN, WORK, others)
 * 18 ejercicios (B2: turn up, work out, turn down, etc.) — Tema: Sport (extended)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Phrasal Verbs 6 (TURN, WORK, others)|Phrasal Verbs 6]]';
const INSTRUCTIONS = 'Elige el phrasal verb correcto o completa el espacio.';

export const UNIT_39_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u39-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Over 500 fans|Más de 500 aficionados]] ____ [[for the match|para el partido]] [[last Saturday|el sábado pasado]].', options: ['[[turned up|acudieron]]', '[[turned down|rechazaron]]', '[[turned into|se convirtieron en]]'], correctAnswer: 'turned up', acceptableAnswers: ['turned up'], explanation: '[[Turn up = arrive|Turn up = acudir, llegar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[at the gym|en el gimnasio]] [[every morning|cada mañana]] [[to stay fit|para mantenerse en forma]].', options: ['[[works out|entrena]]', '[[works on|trabaja en]]', '[[works through|supera]]'], correctAnswer: 0, explanation: '[[Work out = exercise|Work out = entrenar, hacer ejercicio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[the offer|la oferta]] [[to join|de unirse a]] [[the team|al equipo]] [[because|porque]] [[of|de]] [[the salary|el salario]].', options: ['[[turned down|rechazó]]', '[[turned up|acudió]]', '[[turned into|se convirtió en]]'], correctAnswer: 'turned down', acceptableAnswers: ['turned down'], explanation: '[[Turn down = reject|Turn down = rechazar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The match|El partido]] ____ [[to be|ser]] [[a great success|un gran éxito]] — [[the stadium|el estadio]] [[was full|estaba lleno]].', options: ['[[turned out|resultó]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 0, explanation: '[[Turn out = result|Turn out = resultar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[her serve|su saque]] [[for months|durante meses]] [[before|antes de]] [[the tournament|el torneo]].', options: ['[[worked on|trabajó en]]', '[[worked out|entrenó]]', '[[worked through|superó]]'], correctAnswer: 'worked on', acceptableAnswers: ['worked on'], explanation: '[[Work on = improve|Work on = trabajar en, mejorar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[a professional athlete|un atleta profesional]] [[after years of training|después de años de entrenamiento]].', options: ['[[turned into|se convirtió en]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 0, explanation: '[[Turn into = become|Turn into = convertirse en]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[the injury|la lesión]] [[and|y]] [[came back|came back]] [[stronger|más fuertes]].', options: ['[[worked through|superaron]]', '[[worked out|entrenaron]]', '[[worked on|trabajaron en]]'], correctAnswer: 'worked through', acceptableAnswers: ['worked through'], explanation: '[[Work through = deal with|Work through = superar, enfrentar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[late|tarde]] [[for training|al entrenamiento]] [[yesterday|ayer]].', options: ['[[turned up|llegó]]', '[[turned down|rechazó]]', '[[turned into|se convirtió en]]'], correctAnswer: 0, explanation: '[[Turn up = arrive|Turn up = llegar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The team|El equipo]] ____ [[the problem|el problema]] [[together|juntos]] [[and|y]] [[found a solution|encontró una solución]].', options: ['[[worked out|resolvió]]', '[[worked on|trabajó en]]', '[[worked through|superó]]'], correctAnswer: 'worked out', acceptableAnswers: ['worked out'], explanation: '[[Work out = solve|Work out = resolver]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Nobody|Nadie]] ____ [[for the match|para el partido]] [[because of|a causa del]] [[the rain|la lluvia]].', options: ['[[turned up|acudió]]', '[[turned down|rechazó]]', '[[turned into|se convirtió en]]'], correctAnswer: 0, explanation: '[[Turn up = arrive|Turn up = acudir]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[the invitation|la invitación]] [[to play|a jugar]] [[in the charity match|en el partido benéfico]].', options: ['[[turned down|rechazó]]', '[[turned up|acudió]]', '[[turned into|se convirtió en]]'], correctAnswer: 'turned down', acceptableAnswers: ['turned down'], explanation: '[[Turn down = reject|Turn down = rechazar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The young player|El joven jugador]] ____ [[a star|una estrella]] [[overnight|de la noche a la mañana]].', options: ['[[turned into|se convirtió en]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 0, explanation: '[[Turn into = become|Turn into = convertirse en]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[three times a week|tres veces por semana]] [[to prepare|para prepararse]] [[for the marathon|para el maratón]].', options: ['[[work out|entreno]]', '[[work on|trabajo en]]', '[[work through|supero]]'], correctAnswer: 'work out', acceptableAnswers: ['work out'], explanation: '[[Work out = exercise|Work out = entrenar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It|]] ____ [[that|que]] [[the match|el partido]] [[was postponed|fue aplazado]].', options: ['[[turned out|resultó]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 0, explanation: '[[Turn out = result|Turn out = resultar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ [[their differences|sus diferencias]] [[and|y]] [[won|ganaron]] [[the cup|la copa]].', options: ['[[worked through|superaron]]', '[[worked out|entrenaron]]', '[[worked on|trabajaron en]]'], correctAnswer: 'worked through', acceptableAnswers: ['worked through'], explanation: '[[Work through = deal with|Work through = superar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[her technique|su técnica]] [[every day|cada día]] [[before|antes de]] [[the competition|la competición]].', options: ['[[works on|trabaja en]]', '[[works out|entrena]]', '[[works through|supera]]'], correctAnswer: 0, explanation: '[[Work on = improve|Work on = trabajar en, mejorar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The team|El equipo]] ____ [[to be|ser]] [[much stronger|mucho más fuerte]] [[than|que]] [[we expected|esperábamos]].', options: ['[[turned out|resultó]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 'turned out', acceptableAnswers: ['turned out'], explanation: '[[Turn out = result|Turn out = resultar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u39-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Sport (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[a new training schedule|un nuevo horario de entrenamiento]] [[that|que]] [[suits|conviene]] [[everyone|a todos]].', options: ['[[worked out|elaboramos]]', '[[worked on|trabajamos en]]', '[[worked through|superamos]]'], correctAnswer: 0, explanation: '[[Work out = develop, solve|Work out = elaborar, resolver]].' }] }, topicName: 'Grammar' },
];
