/**
 * Unidad 29 B2 — Lección 3: Comprensión lectora (Collocations Adj+Noun)
 * 13 preguntas (B2: texto sobre colocaciones adjetivo+sustantivo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Using|Usar]] [[the right|las correctas]] [[adjective-noun collocations|colocaciones adjetivo-sustantivo]] [[makes|hace]] [[your English|tu inglés]] [[sound more natural|suene más natural]]. [[Last weekend|El fin de semana pasado]] [[we|nosotros]] [[had to cancel|tuvimos que cancelar]] [[our|nuestro]] [[beach trip|viaje a la playa]] [[because of|debido a]] [[heavy rain|lluvia fuerte]] — [[the forecast|el pronóstico]] [[had warned|había advertido]] [[of|de]] [[strong winds|vientos fuertes]] [[too|también]]. [[Instead|En lugar de eso]], [[we|nosotros]] [[stayed|nos quedamos]] [[at home|en casa]] [[and|y]] [[had|tomamos]] [[strong coffee|café fuerte]] [[while|mientras]] [[watching|viendo]] [[a film|una película]]. [[The film|La película]] [[had|tuvo]] [[a deep impact|un impacto profundo]] [[on|en]] [[me|mí]] — [[it|ella]] [[made|hizo]] [[me|me]] [[think|pensar]] [[about|sobre]] [[important|importantes]] [[topics|temas]]. [[My friend|Mi amigo]] [[has|tiene]] [[a remarkable memory|una memoria notable]] — [[he|él]] [[remembers|recuerda]] [[every detail|cada detalle]] [[of|de]] [[our conversations|nuestras conversaciones]]. [[We|Nosotros]] [[had|tuvimos]] [[a lively discussion|una discusión animada]] [[about|sobre]] [[the film|la película]] [[and|y]] [[he|él]] [[showed|mostró]] [[great interest|gran interés]] [[in|en]] [[my views|mis opiniones]]. [[There is|Hay]] [[high demand|alta demanda]] [[for|de]] [[films|películas]] [[like that|como esa]] — [[they|ellas]] [[make|hacen]] [[great progress|gran progreso]] [[in|en]] [[raising awareness|concienciar]] [[about|sobre]] [[social issues|temas sociales]].`;

const INSTRUCTIONS = 'Lee el texto sobre colocaciones. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[did they have to cancel|tuvieron que cancelar]] [[last weekend|el fin de semana pasado]]?', options: ['[[Their beach trip because of heavy rain|Su viaje a la playa debido a la lluvia fuerte]]', '[[The film|La película]]', '[[The coffee|El café]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[we had to cancel our beach trip because of heavy rain|tuvimos que cancelar nuestro viaje a la playa debido a la lluvia fuerte]]".' },
  { question: '[[What|Qué]] [[did the forecast warn of|advirtió el pronóstico]]?', options: ['[[Strong winds|Vientos fuertes]]', '[[Heavy traffic|Tráfico denso]]', '[[High demand|Alta demanda]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the forecast had warned of strong winds|el pronóstico había advertido de vientos fuertes]]".' },
  { question: '[[What|Qué]] [[did they do instead|hicieron en su lugar]]?', options: ['[[They stayed at home and had strong coffee while watching a film|Se quedaron en casa y tomaron café fuerte viendo una película]]', '[[They went to the beach|Fueron a la playa]]', '[[They had a lively discussion|Tuvieron una discusión animada]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[instead we stayed at home and had strong coffee while watching a film|en lugar de eso nos quedamos en casa y tomamos café fuerte viendo una película]]".' },
  { question: '[[What|Qué]] [[had the film|tuvo la película]] [[on the author|en el autor]]?', options: ['[[A deep impact|Un impacto profundo]]', '[[Heavy rain|Lluvia fuerte]]', '[[Great progress|Gran progreso]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the film had a deep impact on me|la película tuvo un impacto profundo en mí]]".' },
  { question: '[[What|Qué]] [[does the friend have|tiene el amigo]]?', options: ['[[A remarkable memory|Una memoria notable]]', '[[Strong coffee|Café fuerte]]', '[[Heavy traffic|Tráfico denso]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[my friend has a remarkable memory|mi amigo tiene una memoria notable]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[they went to the beach|fueron a la playa]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[They cancelled|Cancelaron]] [[the beach trip|el viaje a la playa]] [[because of|debido a]] [[heavy rain|la lluvia fuerte]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the text|del texto]]?', options: ['[[Using the right adjective-noun collocations makes your English sound more natural|Usar las colocaciones adjetivo-sustantivo correctas hace que tu inglés suene más natural]]', '[[You should never cancel trips|Nunca deberías cancelar viajes]]', '[[Strong coffee is better than weak coffee|El café fuerte es mejor que el café suave]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[opens with|abre con]] [[this idea|esta idea]].' },
  { question: '[[Which collocation|Qué colocación]] [[means|significa]] [["intense rain"|"lluvia intensa"]]?', options: ['[[Heavy rain|Heavy rain]]', '[[Strong coffee|Strong coffee]]', '[[Strong wind|Strong wind]]'], correctAnswer: 0, explanation: '[[Heavy rain|Heavy rain]] [[= intense rain|= lluvia intensa]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the author|el autor]]?', options: ['[[He values natural language and uses collocations correctly|Valora el lenguaje natural y usa las colocaciones correctamente]]', '[[He prefers weak coffee|Prefiere café suave]]', '[[He never watches films|Nunca ve películas]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[uses|usa]] [[many|muchas]] [[collocations|colocaciones]] [[correctly|correctamente]].' },
  { question: '[[The friend|El amigo]] ____ [[great interest|gran interés]] [[in|en]] [[the author\'s views|las opiniones del autor]].', options: ['[[showed|mostró]]', '[[had|tuvo]]', '[[made|hizo]]'], correctAnswer: 0, explanation: '[[Show interest|Show interest]] [[= express interest|= mostrar interés]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[heavy rain|lluvia fuerte]], [[strong coffee|café fuerte]], [[deep impact|impacto profundo]], [[great interest|gran interés]], [[high demand|alta demanda]]', '[[gallery|galería]], [[harbour|puerto]]', '[[computer|ordenador]], [[software|software]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[adjective+noun collocations|colocaciones adjetivo+sustantivo]].' },
  { question: '[[Which collocation|Qué colocación]] [[means|significa]] [["animated discussion"|"discusión animada"]]?', options: ['[[Lively discussion|Lively discussion]]', '[[Heavy rain|Heavy rain]]', '[[Strong coffee|Strong coffee]]'], correctAnswer: 0, explanation: '[[Lively discussion|Lively discussion]] [[= animated discussion|= discusión animada]].' },
  { question: '[[What|Qué]] [[does the text say|dice el texto]] [[about|sobre]] [[demand for films like that|la demanda de películas como esa]]?', options: ['[[There is high demand|Hay alta demanda]]', '[[There is low demand|Hay baja demanda]]', '[[There is no demand|No hay demanda]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[there is high demand for films like that|hay alta demanda de películas como esa]]".' },
];

export const UNIT_29_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u29-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Mixed topics',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
