/**
 * Unidad 53 B2 — Lección 5: Expresión oral (The Future of Work)
 * 18 ejercicios (B2: future continuous, future perfect, trabajo)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_53_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u53-l5-s1', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[By 2030, many jobs will have been replaced by automation|Para 2030, muchos trabajos habrán sido reemplazados por la automatización]].', expectedResponse: 'By 2030, many jobs will have been replaced by automation.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s2', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[At 3pm tomorrow, I will be having a video call|Mañana a las 3pm, estaré teniendo una videollamada]].', expectedResponse: 'At 3pm tomorrow, I will be having a video call.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s3', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By next year, she will have worked ten years in this company|Para el año que viene, ella habrá trabajado diez años en esta empresa]].', expectedResponse: 'By next year, she will have worked ten years in this company.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s4', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[This time next week, we will be working remotely|A esta hora la próxima semana, estaremos trabajando en remoto]].', expectedResponse: 'This time next week, we will be working remotely.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s5', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By the end of the month, they will have finished the project|Para final de mes, habrán terminado el proyecto]].', expectedResponse: 'By the end of the month, they will have finished the project.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s6', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[In 2050, most workers will be working from home|En 2050, la mayoría de trabajadores estarán trabajando desde casa]].', expectedResponse: 'In 2050, most workers will be working from home.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s7', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By then, the gig economy will have transformed traditional jobs|Para entonces, la economía gig habrá transformado los trabajos tradicionales]].', expectedResponse: 'By then, the gig economy will have transformed traditional jobs.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s8', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Workers will be learning new skills throughout their lives|Los trabajadores estarán aprendiendo nuevas habilidades a lo largo de sus vidas]].', expectedResponse: 'Workers will be learning new skills throughout their lives.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s9', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[By 2028, AI will have automated many routine tasks|Para 2028, la IA habrá automatizado muchas tareas rutinarias]].', expectedResponse: 'By 2028, AI will have automated many routine tasks.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s10', type: 'pronunciation', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los verbos.', targetText: '[[This time next month, I will be learning new skills|A esta hora el próximo mes, estaré aprendiendo nuevas habilidades]].', expectedResponse: 'This time next month, I will be learning new skills.' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s11', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe cómo será tu trabajo en 10 años. Usa: will be, will have.', prompt: '[[Describe how your work will be in 10 years. Use: will be, will have.|Describe cómo será tu trabajo en 10 años. Usa: will be, will have.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s12', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: ¿qué habrás logrado en tu carrera para 2030? Usa: will have.', prompt: '[[What will you have achieved in your career by 2030? Use: will have.|¿Qué habrás logrado en tu carrera para 2030? Usa: will have.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s13', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cuál es la diferencia entre future continuous y future perfect?', prompt: '[[What is the difference between future continuous and future perfect? Give examples.|¿Cuál es la diferencia entre futuro continuo y futuro perfecto? Da ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s14', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe el futuro del trabajo usando will be y will have.', prompt: '[[Describe the future of work using will be and will have.|Describe el futuro del trabajo usando will be y will have.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s15', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these in your own sentences:|Usa estas en tus propias oraciones:]]\n[[- will be + -ing|- will be + -ing]]\n[[- will have + past participle|- will have + participio pasado]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s16', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: compara trabajo en oficina con teletrabajo. Usa future forms.', prompt: '[[Compare office work with remote work. Use future forms.|Compara trabajo en oficina con teletrabajo. Usa formas de futuro.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s17', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: explica cuándo usas future continuous vs future perfect.', prompt: '[[Explain when you use future continuous vs future perfect. Use examples.|Explica cuándo usas futuro continuo vs futuro perfecto. Usa ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u53-l5-s18', type: 'speaking', level: 'B2', topic: 'work-employment', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué habilidades crees que necesitarás en el futuro? Usa: will be, will have.', prompt: '[[What skills do you think you will need in the future? Use: will be, will have.|¿Qué habilidades crees que necesitarás en el futuro? Usa: will be, will have.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
