/**
 * Unidad 38 B2 — Lección 5: Expresión oral (Leisure extended)
 * 18 ejercicios (B2: phrasal verbs RUN/SET/TAKE y ocio)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_38_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u38-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[We ran into an old friend at the cinema|Nos encontramos con un viejo amigo en el cine]].', expectedResponse: 'We ran into an old friend at the cinema.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They set up a camping trip for the summer|Organizaron un viaje de camping para el verano]].', expectedResponse: 'They set up a camping trip for the summer.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She took to hiking last year|Se aficionó al senderismo el año pasado]].', expectedResponse: 'She took to hiking last year.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We ran out of snacks halfway through the concert|Nos quedamos sin aperitivos a mitad del concierto]].', expectedResponse: 'We ran out of snacks halfway through the concert.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They set off early for the beach|Partieron temprano para la playa]].', expectedResponse: 'They set off early for the beach.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He took up photography as a hobby|Empezó fotografía como hobby]].', expectedResponse: 'He took up photography as a hobby.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Let me run the plan by you before we book|Déjame comentarte el plan antes de reservar]].', expectedResponse: 'Let me run the plan by you before we book.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We set aside an hour for the picnic|Reservamos una hora para el picnic]].', expectedResponse: 'We set aside an hour for the picnic.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[The flight took off on time|El vuelo despegó a tiempo]].', expectedResponse: 'The flight took off on time.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los phrasal verbs.', targetText: '[[They ran through the itinerary before the trip|Repasaron el itinerario antes del viaje]].', expectedResponse: 'They ran through the itinerary before the trip.' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s11', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe un hobby que hayas empezado. Usa: take up, take to, set aside.', prompt: '[[Describe a hobby you have started. Use: take up, take to, set aside.|Describe un hobby que hayas empezado. Usa: take up, take to, set aside.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s12', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: cuenta una vez que te encontraste con alguien por casualidad. Usa: run into.', prompt: '[[Tell about a time you ran into someone by accident. Use: run into.|Cuenta una vez que te encontraste con alguien por casualidad. Usa: run into.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s13', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cuál es la diferencia entre take up y take to?', prompt: '[[What is the difference between take up and take to? Give examples.|¿Cuál es la diferencia entre take up y take to? Da ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s14', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe cómo organizarías un viaje. Usa: set up, set off, set out, run through.', prompt: '[[Describe how you would organise a trip. Use: set up, set off, set out, run through.|Describe cómo organizarías un viaje. Usa: set up, set off, set out, run through.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s15', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these expressions in your own sentences:|Usa estas expresiones en tus propias oraciones:]]\n[[- run into|- encontrarse con]]\n[[- set up|- organizar]]\n[[- take up|- empezar]]\n[[- run out of|- quedarse sin]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s16', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: compara run out of con set aside. Usa ejemplos de ocio.', prompt: '[[Compare run out of with set aside. Use leisure examples.|Compara run out of con set aside. Usa ejemplos de ocio.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s17', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: explica cuándo usas set off y set out.', prompt: '[[Explain when you use set off and set out. Use examples.|Explica cuándo usas set off y set out. Usa ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u38-l5-s18', type: 'speaking', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué hobbies te gustaría empezar y por qué? Usa: take up, take to.', prompt: '[[What hobbies would you like to take up and why? Use: take up, take to.|¿Qué hobbies te gustaría empezar y por qué? Usa: take up, take to.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
