/**
 * Unidad 12 B2 — Lección 4: Comprensión auditiva (Gardening & Plants)
 * 13 preguntas (B2: Gardening & Plants)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[I'm|Soy]] [[Tom|Tom]], [[a horticulturist|un horticultor]] [[who|que]] [[works|trabaja]] [[at|en]] [[a botanical garden|un jardín botánico]] [[that|que]] [[specialises in|se especializa en]] [[rare species|especies raras]]. [[The gardens|Los jardines]] [[that|que]] [[we maintain|mantenemos]] [[must|deben]] [[display|mostrar]] [[plants|plantas]] [[which|que]] [[thrive|prosperan]] [[in our climate|en nuestro clima]]. [[Last year|El año pasado]], [[we opened|abrimos]] [[a section|una sección]] [[planted|plantada]] [[with native herbs|con hierbas nativas]], [[showing|mostrando]] [[varieties|variedades]] [[whose medicinal uses|cuyos usos medicinales]] [[are documented|están documentados]] [[in old texts|en textos antiguos]]. [[The beds|Los parterres]], [[which|que]] [[were prepared|fueron preparados]] [[in the spring|en primavera]], [[received|recibieron]] [[excellent feedback|excelentes comentarios]]. [[The head gardener|El jardinero jefe]], [[whose previous projects|cuyos proyectos anteriores]] [[had won awards|habían ganado premios]], [[insisted|insistió]] [[on|en]] [[using|usar]] [[organic compost|compost orgánico]] [[that|que]] [[we produce|producimos]] [[on site|en el lugar]]. [[Visitors|Los visitantes]] [[who|que]] [[contacted us|nos contactaron]] [[said|dijeron]] [[that|que]] [[the garden|el jardín]] [[had changed|había cambiado]] [[their perspective|su perspectiva]] [[on|sobre]] [[urban green spaces|espacios verdes urbanos]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Tom, a horticulturist|Tom, horticultor]]', '[[A TV presenter|Un presentador de TV]]', '[[A film director|Un director de cine]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Tom, a horticulturist who works at a botanical garden|Soy Tom, un horticultor que trabaja en un jardín botánico]]".' },
  { question: '[[What|Qué]] [[must the gardens do|deben hacer los jardines]]?', options: ['[[Display plants that thrive in the climate|Mostrar plantas que prosperan en el clima]]', '[[Make a lot of money|Ganar mucho dinero]]', '[[Use artificial plants|Usar plantas artificiales]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[must display plants which thrive in our climate|deben mostrar plantas que prosperan en nuestro clima]]".' },
  { question: '[[Where|Dónde]] [[was the section planted|se plantó la sección]]?', options: ['[[With native herbs|Con hierbas nativas]]', '[[In the Arctic|En el Ártico]]', '[[In Africa|En África]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[a section planted with native herbs|una sección plantada con hierbas nativas]]".' },
  { question: '[[What|Qué]] [[does the section show|muestra la sección]]?', options: ['[[Varieties whose medicinal uses are documented|Variedades cuyos usos medicinales están documentados]]', '[[City life in big capitals|Vida urbana en grandes capitales]]', '[[Sports events|Eventos deportivos]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[showing varieties whose medicinal uses are documented in old texts|mostrando variedades cuyos usos medicinales están documentados en textos antiguos]]".' },
  { question: '[[When|Cuándo]] [[were the beds prepared|se prepararon los parterres]]?', options: ['[[In the spring|En primavera]]', '[[In the autumn|En otoño]]', '[[In the summer|En verano]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[The beds, which were prepared in the spring|Los parterres, que fueron preparados en primavera]]".' },
  { question: '[[What|Qué]] [[did the head gardener insist on|insistió el jardinero jefe en]]?', options: ['[[Using organic compost produced on site|Usar compost orgánico producido en el lugar]]', '[[Using chemical fertilisers|Usar fertilizantes químicos]]', '[[Planting artificial grass|Plantar césped artificial]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[insisted on using organic compost that we produce on site|insistió en usar compost orgánico que producimos en el lugar]]".' },
  { question: '[[What|Qué]] [[did visitors say|dijeron los visitantes]]?', options: ['[[The garden had changed their perspective on urban green spaces|El jardín había cambiado su perspectiva sobre espacios verdes urbanos]]', '[[The garden was too small|El jardín era demasiado pequeño]]', '[[The garden was boring|El jardín era aburrido]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[the garden had changed their perspective on urban green spaces|el jardín había cambiado su perspectiva sobre espacios verdes urbanos]]".' },
  { question: '[[The head gardener|El jardinero jefe]] [[had never won awards before|nunca había ganado premios antes]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[whose previous projects had won awards|cuyos proyectos anteriores habían ganado premios]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the listening|de la escucha]]?', options: ['[[Botanical gardens can raise awareness and change perspectives on green spaces|Los jardines botánicos pueden concienciar y cambiar perspectivas sobre espacios verdes]]', '[[Gardens only want profit|Los jardines solo quieren beneficios]]', '[[Native herbs are dangerous|Las hierbas nativas son peligrosas]]'], correctAnswer: 0, explanation: '[[The speaker|El hablante]] [[describes|describe]] [[how botanical gardens impact visitors|cómo los jardines botánicos impactan a los visitantes]].' },
  { question: '[[Which reduced relative clause|Qué cláusula de relativo reducida]] [[appears in the transcript|aparece en la transcripción]]?', options: ['[[planted with native herbs|plantada con hierbas nativas]]', '[[which were prepared|que fueron preparados]]', '[[whose medicinal uses|cuyos usos medicinales]]'], correctAnswer: 0, explanation: '[[Reduced form|Forma reducida]] [[of "which was planted"|de "which was planted"]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[horticulturist|horticultor]], [[botanical garden|jardín botánico]], [[compost|compost]], [[native herbs|hierbas nativas]]', '[[salary|salario]], [[budget|presupuesto]]', '[[airport|aeropuerto]], [[flight|vuelo]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[gardening vocabulary|vocabulario de jardinería]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[Tom|Tom]]?', options: ['[[He cares about sustainable gardening|Le importa la jardinería sostenible]]', '[[He only works for money|Solo trabaja por dinero]]', '[[He prefers artificial plants|Prefiere plantas artificiales]]'], correctAnswer: 0, explanation: '[[His work on organic compost|Su trabajo con compost orgánico]] [[and native species|y especies nativas]] [[suggests|sugiere]] [[care for sustainability|preocupación por la sostenibilidad]].' },
  { question: '[[Which defining relative clause|Qué oración de relativo explicativa]] [[identifies|identifica]] [[which gardens|qué jardines]]?', options: ['[[that we maintain|que mantenemos]]', '[[which were prepared|que fueron preparados]]', '[[whose previous projects|cuyos proyectos anteriores]]'], correctAnswer: 0, explanation: '[[Defining|Explicativa]] [[specifies which gardens|especifica qué jardines]].' },
];

export const UNIT_12_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u12-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Gardening & Plants',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
