/**
 * Unidad 30 B2 — Lección 6: Expresión escrita (Repaso 26–29)
 * 18 ejercicios (B2: phrasal verbs y colocaciones mixtas)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_30_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u30-l6-w1', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo una decisión que tuviste que tomar. Usa make a decision, take a chance, get through.', prompt: '[[Describe a decision you had to make. Use: make a decision, take a chance, get through.|Describe una decisión que tuviste que tomar. Usa: make a decision, take a chance, get through.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb o colocación correcta.', questions: [{ question: '[[It took her months|Le llevó meses]] ____ [[the loss|superar la pérdida]] [[of her job|de su trabajo]].', options: ['[[to get over|superar]]', '[[to get through|terminar]]', '[[to get along|llevarse bien]]'], correctAnswer: 'to get over', acceptableAnswers: ['to get over'], explanation: '[[Get over = recover from|Get over = recuperarse de]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w3', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando put off o make up for.', prompt: '[[The trip was postponed|El viaje fue pospuesto]]. [[The hotel compensated|El hotel compensó]] [[the delay|el retraso]].', expressionHint: '[[Usa: "We put off the trip" y "The hotel made up for the delay"|Usa: "We put off the trip" y "The hotel made up for the delay"]]', targetLength: '1-2 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w4', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con heavy rain y otra con strong coffee.', prompt: '[[Write two sentences: one with heavy rain and one with strong coffee.|Escribe dos oraciones: una con heavy rain y otra con strong coffee.]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[We|Nosotros]] ____ [[well|bien]] [[with|con]] [[our new colleague|nuestro nuevo compañero]] — [[he\'s very friendly|es muy amigable]].', options: ['[[get along|nos llevamos]]', '[[get over|nos recuperamos]]', '[[get through|terminamos]]'], correctAnswer: 'get along', acceptableAnswers: ['get along'], explanation: '[[Get along = have a good relationship|Get along = llevarse bien]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w6', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre un viaje que planificaste. Usa look into, put off, make up your mind, look forward to.', prompt: '[[Describe a trip you planned. Use: look into, put off, make up your mind, look forward to.|Describe un viaje que planificaste. Usa: look into, put off, make up your mind, look forward to.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w7', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando phrasal verbs y colocaciones.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. I made a decision to ____ when...|1. Tomé una decisión de ____ cuando...]]\n[[2. We had to put off ____ because ____|2. Tuvimos que posponer ____ porque ____]]\n[[3. The hotel made up for ____ by ____|3. El hotel compensó ____ con ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "take" o "make".', questions: [{ question: '[[I need to|Necesito]] ____ [[a break|un descanso]] — [[I\'ve been working for hours|he estado trabajando durante horas]].', options: ['[[take|tomar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 'take', acceptableAnswers: ['take'], explanation: '[[Take a break = have a rest|Take a break = tomar un descanso]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w9', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre lo que aprendiste en las unidades 26–29.', prompt: '[[Write an introduction to an article about what you learned in units 26–29. Use at least two phrasal verbs or collocations.|Escribe la introducción de un artículo sobre lo que aprendiste en las unidades 26–29. Usa al menos dos phrasal verbs o colocaciones.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w10', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando qué puede requerir superar (get through) una dificultad.', prompt: '[[Explain what getting through a difficulty can require. Use get through, give up, take a break.|Explica qué puede requerir superar una dificultad. Usa get through, give up, take a break.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb adecuado.', questions: [{ question: '[[We|Nosotros]] ____ [[cheaper flights|vuelos más baratos]] [[before|antes de]] [[booking|reservar]] [[our trip|nuestro viaje]].', options: ['[[looked into|investigamos]]', '[[looked after|cuidamos]]', '[[looked for|buscamos]]'], correctAnswer: 'looked into', acceptableAnswers: ['looked into'], explanation: '[[Look into = investigate|Look into = investigar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w12', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte estas frases en una usando give up.', prompt: '[[He stopped trying|Dejó de intentar]]. [[He was so close|Estaba tan cerca]].', expressionHint: '[[Usa: "He gave up even though he was so close"|Usa: "He gave up even though he was so close"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w13', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones: una con get over, otra con put off y otra con make a decision.', prompt: '[[Write three sentences:|Escribe tres oraciones:]]\n[[- one with "get over"|- una con "get over"]]\n[[- one with "put off"|- una con "put off"]]\n[[- one with "make a decision"|- una con "make a decision"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "heavy" o "strong".', questions: [{ question: '[[We had to cancel|Tuvimos que cancelar]] [[the picnic|el picnic]] [[because of|debido a]] ____ [[rain|lluvia]].', options: ['[[heavy|fuerte]]', '[[strong|fuerte]]', '[[big|grande]]'], correctAnswer: 'heavy', acceptableAnswers: ['heavy'], explanation: '[[Heavy rain = intense rain|Heavy rain = lluvia fuerte]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w15', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre cómo has aplicado lo aprendido en las unidades 26–29.', prompt: '[[Describe how you have applied what you learned in units 26–29. Use: get over, give up, look into, put off, take a break, make a decision, heavy rain, great progress.|Describe cómo has aplicado lo aprendido en las unidades 26–29. Usa al menos 4 de estas expresiones.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w16', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando cómo usar phrasal verbs y colocaciones en la vida diaria.', prompt: '[[Give advice on how to use phrasal verbs and collocations in daily life. Use take a break and make progress.|Da consejos sobre cómo usar phrasal verbs y colocaciones en la vida diaria. Usa take a break y make progress.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[The presentation|La presentación]] ____ [[well|bien]] — [[everyone liked it|a todos les gustó]].', options: ['[[went off|salió bien]]', '[[went on|continuó]]', '[[went through|atravesó]]'], correctAnswer: 'went off', acceptableAnswers: ['went off'], explanation: '[[Go off = happen successfully|Go off = salir bien]].' }] }, topicName: 'Writing' },
  { id: 'b2-u30-l6-w18', type: 'writing', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué vale la pena repasar las unidades 26–29.', prompt: '[[Write a short conclusion explaining why it is worth reviewing units 26–29. Use get through and make progress.|Escribe una breve conclusión explicando por qué vale la pena repasar las unidades 26–29. Usa get through y make progress.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
