/**
 * Unidad 50 B2 — Lección 2: Vocabulario (Repaso 41-49)
 * 18 ejercicios mixtos de vocabulario de unidades 41-49
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Repaso 41-49|Repaso 41-49]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta. Repaso de vocabulario de las unidades 41-49.';

export const UNIT_50_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u50-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The set of subjects|El conjunto de asignaturas]] [[taught in a school|enseñadas en una escuela]]:', options: ['[[curriculum|currículo]]', '[[syllabus|programa]]', '[[degree|título]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal piece of writing|Un escrito formal]] [[on a topic|sobre un tema]]:', options: ['[[essay|ensayo]]', '[[report|informe]]', '[[article|artículo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Technology in education|Tecnología en educación]]:', options: ['[[EdTech|tecnología educativa]]', '[[e-learning|aprendizaje electrónico]]', '[[MOOC|curso masivo online]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The study of society|El estudio de la sociedad]] [[and human behaviour|y comportamiento humano]]:', options: ['[[sociology|sociología]]', '[[psychology|psicología]]', '[[anthropology|antropología]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Presenting reasons|Presentar razones]] [[to support a claim|para apoyar una afirmación]]:', options: ['[[argumentation|argumentación]]', '[[evidence|evidencia]]', '[[conclusion|conclusión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much students participate|Cuánto participan los estudiantes]] [[in class|en clase]]:', options: ['[[student engagement|participación del estudiante]]', '[[attendance|asistencia]]', '[[participation|participación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Transformation in society|Transformación en la sociedad]] [[over time|con el tiempo]]:', options: ['[[social change|cambio social]]', '[[revolution|revolución]]', '[[reform|reforma]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A first version|Una primera versión]] [[of a text|de un texto]]:', options: ['[[draft|borrador]]', '[[manuscript|manuscrito]]', '[[proof|prueba]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Who you are as a person|Quién eres como persona]] [[or group|o grupo]]:', options: ['[[identity|identidad]]', '[[personality|personalidad]]', '[[character|carácter]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Different approaches|Diferentes enfoques]] [[to teaching|para enseñar]]:', options: ['[[teaching methods|métodos de enseñanza]]', '[[pedagogy|pedagogía]]', '[[curriculum|currículo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Variety of cultures|Variedad de culturas]] [[in one place|en un lugar]]:', options: ['[[diversity|diversidad]]', '[[multiculturalism|multiculturalismo]]', '[[pluralism|pluralismo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Facts or data|Hechos o datos]] [[that support an argument|que apoyan un argumento]]:', options: ['[[evidence|evidencia]]', '[[claim|afirmación]]', '[[hypothesis|hipótesis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[New ideas or changes|Ideas nuevas o cambios]]:', options: ['[[innovation|innovación]]', '[[tradition|tradición]]', '[[reform|reforma]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[General directions|Direcciones generales]] [[things are moving|hacia donde se mueven las cosas]]:', options: ['[[trends|tendencias]]', '[[fads|modas pasajeras]]', '[[movements|movimientos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To mention a source|Mencionar una fuente]] [[in academic work|en trabajo académico]]:', options: ['[[to cite|citar]]', '[[to quote|citar textualmente]]', '[[to reference|referenciar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning by doing|Aprendizaje haciendo]] [[practical tasks|tareas prácticas]]:', options: ['[[hands-on learning|aprendizaje práctico]]', '[[rote learning|aprendizaje memorístico]]', '[[self-study|autoaprendizaje]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Statistics about population|Estadísticas sobre población]] [[(age, income)|(edad, ingresos)]]:', options: ['[[demographics|demografía]]', '[[census|censo]]', '[[statistics|estadísticas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u50-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A statement|Un enunciado]] [[that the essay will prove|que el ensayo probará]]:', options: ['[[thesis statement|enunciado de tesis]]', '[[hypothesis|hipótesis]]', '[[claim|afirmación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
