/**
 * Unidad 40 B2 — Lección 6: Expresión escrita (Repaso 36–39)
 * 18 ejercicios (B2: used to/would, auxiliares, phrasal verbs)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_40_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u40-l6-w1', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo tradiciones y hobbies. Usa: used to, would, take up, run into.', prompt: '[[Describe traditions and hobbies. Use: used to, would, take up, run into.|Describe tradiciones y hobbies. Usa: used to, would, take up, run into.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[When I was young|Cuando era joven]], [[I|yo]] ____ [[visit|visitar]] [[my grandmother|a mi abuela]] [[every Sunday|cada domingo]].', options: ['[[used to|solía]]', '[[would|solía]]'], correctAnswer: 'used to', acceptableAnswers: ['used to', 'would'], explanation: '[[Used to / would for past habits|Used to / would para hábitos pasados]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w3', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando auxiliares para énfasis y phrasal verbs.', prompt: '[[Write two sentences: one with do for emphasis, one with run into.|Escribe dos oraciones: una con do para énfasis, una con run into.]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w4', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "set up" y otra con "turn up".', prompt: '[[Write two sentences: one with "set up" and one with "turn up".|Escribe dos oraciones: una con "set up" y otra con "turn up".]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[We|Nosotros]] ____ [[an old friend|a un viejo amigo]] [[at the cinema|en el cine]].', options: ['[[ran into|nos encontramos con]]', '[[ran out of|nos quedamos sin]]', '[[ran through|repasamos]]'], correctAnswer: 'ran into', acceptableAnswers: ['ran into'], explanation: '[[Run into = meet by accident|Run into = encontrarse por casualidad]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w6', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre deporte y negocios. Usa: work out, turn down, close a deal.', prompt: '[[Describe sport and business. Use: work out, turn down, close a deal.|Describe deporte y negocios. Usa: work out, turn down, close a deal.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w7', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. I used to ____|1. Solía ____]]\n[[2. I do want to ____|2. Sí quiero ____]]\n[[3. I ran into ____|3. Me encontré con ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[Over 500 fans|Más de 500 aficionados]] ____ [[for the match|para el partido]].', options: ['[[turned up|acudieron]]', '[[turned down|rechazaron]]', '[[turned into|se convirtieron en]]'], correctAnswer: 'turned up', acceptableAnswers: ['turned up'], explanation: '[[Turn up = arrive|Turn up = acudir]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w9', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre cultura y deporte. Usa vocabulario de unidades 36–39.', prompt: '[[Write an introduction about culture and sport. Use vocabulary from units 36–39.|Escribe una introducción sobre cultura y deporte. Usa vocabulario de unidades 36–39.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w10', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre turn up y turn down.', prompt: '[[Explain the difference between turn up and turn down. Use examples.|Explica la diferencia entre turn up y turn down. Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb adecuado.', questions: [{ question: '[[The match|El partido]] ____ [[to be|ser]] [[a great success|un gran éxito]].', options: ['[[turned out|resultó]]', '[[turned up|acudió]]', '[[turned down|rechazó]]'], correctAnswer: 'turned out', acceptableAnswers: ['turned out'], explanation: '[[Turn out = result|Turn out = resultar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w12', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte usando phrasal verbs: Organizamos un picnic. Partimos temprano.', prompt: '[[Convert using phrasal verbs: We organised a picnic. We left early.|Convierte usando phrasal verbs: Organizamos un picnic. Partimos temprano.]]', expressionHint: '[[Usa: set up, set off|Usa: set up, set off]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w13', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones: una con used to, una con do para énfasis, una con work out.', prompt: '[[Write three sentences: one with used to, one with do for emphasis, one with work out.|Escribe tres oraciones: una con used to, una con do para énfasis, una con work out.]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[She|Ella]] ____ [[at the gym|en el gimnasio]] [[every morning|cada mañana]].', options: ['[[works out|entrena]]', '[[works on|trabaja en]]', '[[works through|supera]]'], correctAnswer: 'works out', acceptableAnswers: ['works out'], explanation: '[[Work out = exercise|Work out = entrenar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w15', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre tu vida: cultura, trabajo, ocio y deporte. Usa vocabulario de unidades 36–39.', prompt: '[[Describe your life: culture, work, leisure and sport. Use vocabulary from units 36–39.|Describe tu vida: cultura, trabajo, ocio y deporte. Usa vocabulario de unidades 36–39.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w16', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando a alguien. Usa: take up, work through, set aside.', prompt: '[[Give advice. Use: take up, work through, set aside.|Da consejos. Usa: take up, work through, set aside.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[They|Ellos]] ____ [[the injury|la lesión]] [[and came back stronger|y volvieron más fuertes]].', options: ['[[worked through|superaron]]', '[[worked out|entrenaron]]', '[[worked on|trabajaron en]]'], correctAnswer: 'worked through', acceptableAnswers: ['worked through'], explanation: '[[Work through = deal with|Work through = superar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u40-l6-w18', type: 'writing', level: 'B2', topic: 'Repaso 36–39', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre lo aprendido en unidades 36–39.', prompt: '[[Write a short conclusion about what you learned in units 36–39.|Escribe una breve conclusión sobre lo aprendido en unidades 36–39.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
