/**
 * Unidad 5 B2 — Lección 1: Gramática (Repaso 1–4)
 * 18 ejercicios (B2: más vocabulario y complejidad que B1)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Repaso 1–4|Repaso 1–4]]';
const INSTRUCTIONS = 'Elige la opción correcta o completa el espacio.';

export const UNIT_5_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u5-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]] [[with|con]] [[the correct form|la forma correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct option|la opción correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Select|Selecciona]] [[the best answer|la mejor respuesta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 1, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fill in|Completa]] [[the blank|el espacio]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct form|la forma correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Select|Selecciona]] [[the correct option|la opción correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fill in|Completa]] [[the blank|el espacio]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the best answer|la mejor respuesta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Select|Selecciona]] [[the correct form|la forma correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fill in|Completa]] [[the blank|el espacio]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct option|la opción correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Select|Selecciona]] [[the best answer|la mejor respuesta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Complete|Completa]] [[the sentence|la frase]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]'], correctAnswer: 0, acceptableAnswers: ['Option A'], explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u5-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 1–4', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct form|la forma correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0, explanation: '[[Grammar point|Punto gramatical]].' }] }, topicName: 'Grammar' },
];
