/**
 * Unidad 20 B2 — Lección 2: Vocabulario (Repaso: History, Adventure, Cooking, Literature)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Repaso 16–19|Repaso 16–19]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta. Repaso de History, Adventure, Cooking y Literature.';

export const UNIT_20_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u20-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Objects and traditions from the past|Objetos y tradiciones del pasado]]:', options: ['[[heritage|patrimonio]]', '[[history|historia]]', '[[artifact|artefacto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A journey with a specific purpose, often risky|Viaje con un propósito específico, a menudo arriesgado]]:', options: ['[[expedition|expedición]]', '[[evidence|evidencia]]', '[[route|ruta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Food preserved in salt or vinegar|Comida conservada en sal o vinagre]]:', options: ['[[pickled|encurtido]]', '[[raw|crudo]]', '[[roasted|asado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Physical or mental strength to continue despite difficulty|Fuerza física o mental para continuar a pesar de la dificultad]]:', options: ['[[endurance|resistencia]]', '[[speed|velocidad]]', '[[agility|agilidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To find something for the first time|Encontrar algo por primera vez]]:', options: ['[[discover|descubrir]]', '[[invent|inventar]]', '[[create|crear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Information that supports or proves something|Información que apoya o prueba algo]]:', options: ['[[evidence|evidencia]]', '[[expedition|expedición]]', '[[theory|teoría]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who guides writers|Persona que guía a escritores]]:', options: ['[[mentor|mentor]]', '[[critic|crítico]]', '[[publisher|editor]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Having a strong, sharp taste|Que tiene un sabor fuerte y picante]]:', options: ['[[spicy|picante]]', '[[sweet|dulce]]', '[[bland|soso]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A safety belt worn by climbers|Cinturón de seguridad usado por escaladores]]:', options: ['[[harness|arnés]]', '[[rope|cuerda]]', '[[carabiner|mosquetón]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A proposed path to be tested|Ruta propuesta a probar]]:', options: ['[[route|ruta]]', '[[conclusion|conclusión]]', '[[method|método]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a record" → batir un récord|Colocación: "___ a record" → batir un récord]]', options: ['[[break|batir]]', '[[make|hacer]]', '[[set|establecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "___ fit" → mantenerse en forma|Expresión: "___ fit" → mantenerse en forma]]', options: ['[[keep|mantenerse]]', '[[get|ponerse]]', '[[stay|permanecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a recipe" → seguir una receta|Colocación: "___ a recipe" → seguir una receta]]', options: ['[[follow|seguir]]', '[[make|hacer]]', '[[break|romper]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "conduct ___" → realizar una expedición|Expresión: "conduct ___" → realizar una expedición]]', options: ['[[an expedition|una expedición]]', '[[an experiment|un experimento]]', '[[a survey|una encuesta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a meal" → preparar una comida|Colocación: "___ a meal" → preparar una comida]]', options: ['[[prepare|preparar]]', '[[cook|cocinar]]', '[[make|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The best result ever achieved in book sales|Mejor resultado jamás logrado en ventas de libros]]:', options: ['[[record|récord]]', '[[score|puntuación]]', '[[trophy|trofeo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A copy of data kept for safety|Copia de datos guardada por seguridad]]:', options: ['[[backup|copia de seguridad]]', '[[virus|virus]]', '[[update|actualización]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u20-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To examine something in detail|Examinar algo en detalle]]:', options: ['[[analyze|analizar]]', '[[assume|asumir]]', '[[approve|aprobar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
