/**
 * Unidad 35 B2 — Lección 1: Gramática (Repaso 31–34: Articles, Quantifiers, Regret/Remember/Forget, State verbs)
 * 18 ejercicios con casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Repaso 31–34|Repaso 31–34]]';
const INSTRUCTIONS = 'Elige la opción correcta o completa el espacio.';

export const UNIT_35_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u35-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She studied at|Estudió en]] ____ [[university|universidad]] [[in Oxford|en Oxford]].', options: ['[[—|(sin artículo)]]', '[[the|la]]', '[[a|una]]'], correctAnswer: '—', acceptableAnswers: ['—', ''], explanation: '[[No article with "at university"|Sin artículo con "at university"]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I regret|Lamento]] ____ [[you|decirte]] [[that|que]] [[the meeting is cancelled|la reunión está cancelada]].', options: ['[[to tell|decir]]', '[[telling|haber dicho]]'], correctAnswer: 0, explanation: '[[Regret + infinitive = bad news|Regret + infinitivo = malas noticias]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ of the trees|____ de los árboles]] [[in the park|en el parque]] [[were planted|fueron plantados]] [[last year|el año pasado]].', options: ['[[All|Todos]]', '[[Most|La mayoría de]]', '[[Each|Cada uno]]'], correctAnswer: 'All', acceptableAnswers: ['All'], explanation: '[[All = 100%|All = 100%]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[this app|esta aplicación]] — [[it\'s|es]] [[very useful|muy útil]].', options: ['[[like|me gusta]]', '[[am liking|estoy gustando]]'], correctAnswer: 0, explanation: '[[Like is a state verb|Like es verbo de estado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I remember|Recuerdo]] ____ [[her|verla]] [[at the conference|en la conferencia]] [[last year|el año pasado]].', options: ['[[seeing|ver]]', '[[to see|ver]]'], correctAnswer: 'seeing', acceptableAnswers: ['seeing'], explanation: '[[Remember + gerund = past memory|Remember + gerundio = recuerdo pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He has|Tiene]] ____ [[degree in economics|título en economía]].', options: ['[[a|un]]', '[[the|el]]', '[[—|(sin artículo)]]'], correctAnswer: 0, explanation: '[[A for singular countable|A para singular contable]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ wind and solar|____ viento y solar]] [[are|son]] [[renewable|renovables]] [[energy sources|fuentes de energía]].', options: ['[[Both|Ambos]]', '[[All|Todos]]', '[[Each|Cada]]'], correctAnswer: 'Both', acceptableAnswers: ['Both'], explanation: '[[Both = two things|Both = dos cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[how to code|cómo programar]] [[in Python|en Python]].', options: ['[[knows|sabe]]', '[[is knowing|está sabiendo]]'], correctAnswer: 0, explanation: '[[Know is a state verb|Know es verbo de estado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Don\'t forget|No olvides]] ____ [[to reply|responder]] [[to the email|al email]].', options: ['[[to reply|responder]]', '[[replying|haber respondido]]'], correctAnswer: 'to reply', acceptableAnswers: ['to reply'], explanation: '[[Forget + infinitive = future action|Forget + infinitivo = acción futura]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The course covers the history of education in|El curso cubre la historia de la educación en]] ____ [[UK|Reino Unido]].', options: ['[[the|el]]', '[[a|un]]', '[[—|(sin artículo)]]'], correctAnswer: 0, explanation: '[[The for UK|The para UK]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ single day|____ día]] [[we|nosotros]] [[recycle|reciclamos]] [[our waste|nuestros residuos]].', options: ['[[Every|Cada]]', '[[All|Todos]]', '[[Each|Cada uno]]'], correctAnswer: 'Every', acceptableAnswers: ['Every'], explanation: '[[Every for regularity|Every para regularidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[that AI will change|que la IA cambiará]] [[the industry|la industria]].', options: ['[[believe|creemos]]', '[[are believing|estamos creyendo]]'], correctAnswer: 0, explanation: '[[Believe is a state verb|Believe es verbo de estado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She regrets|Lamenta]] ____ [[hurting|haber herido]] [[her friend|a su amigo]] [[when she was angry|cuando estaba enfadada]].', options: ['[[hurting|haber herido]]', '[[to hurt|herir]]'], correctAnswer: 'hurting', acceptableAnswers: ['hurting'], explanation: '[[Regret + gerund = past action|Regret + gerundio = acción pasada]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Most students attend|La mayoría de estudiantes asisten a]] ____ [[classes regularly|clases regularmente]].', options: ['[[—|(sin artículo)]]', '[[the|las]]', '[[a|una]]'], correctAnswer: 0, explanation: '[[No article with plural in general|Sin artículo con plural en general]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[what you mean|lo que quieres decir]] — [[the software|el software]] [[needs an update|necesita una actualización]].', options: ['[[understand|entiendo]]', '[[am understanding|estoy entendiendo]]'], correctAnswer: 'understand', acceptableAnswers: ['understand'], explanation: '[[Understand is a state verb|Understand es verbo de estado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I forgot|Olvidé]] ____ [[to send|enviar]] [[the attachment|el adjunto]] [[with the email|con el email]].', options: ['[[to send|enviar]]', '[[sending|haber enviado]]'], correctAnswer: 0, explanation: '[[Forget + infinitive = didn\'t do|Forget + infinitivo = no hice]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The university is|La universidad es]] ____ [[centre of excellence|centro de excelencia]].', options: ['[[a|un]]', '[[the|el]]', '[[—|(sin artículo)]]'], correctAnswer: 'a', acceptableAnswers: ['a'], explanation: '[[A for singular|A para singular]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u35-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 31–34', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[to upgrade|actualizar]] [[his laptop|su portátil]] [[soon|pronto]].', options: ['[[wants|quiere]]', '[[is wanting|está queriendo]]'], correctAnswer: 0, explanation: '[[Want is a state verb|Want es verbo de estado]].' }] }, topicName: 'Grammar' },
];
