/**
 * Unidad 48 B2 — Lección 2: Vocabulario (Teaching methods, innovation, EdTech)
 * 18 ejercicios (B2: métodos de enseñanza, innovación, tecnología educativa)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Innovation in Teaching|Innovación en la enseñanza]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con innovación en la enseñanza.';

export const UNIT_48_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u48-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Different approaches|Diferentes enfoques]] [[to teaching|para enseñar]]:', options: ['[[teaching methods|métodos de enseñanza]]', '[[pedagogy|pedagogía]]', '[[curriculum|currículo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[New ideas|Ideas nuevas]] [[or changes|o cambios]]:', options: ['[[innovation|innovación]]', '[[tradition|tradición]]', '[[reform|reforma]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Technology|Tecnología]] [[in education|en educación]]:', options: ['[[EdTech|tecnología educativa]]', '[[e-learning|aprendizaje electrónico]]', '[[MOOC|curso masivo online]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The study of teaching|El estudio de la enseñanza]]:', options: ['[[pedagogy|pedagogía]]', '[[methodology|metodología]]', '[[curriculum|currículo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How much students participate|Cuánto participan los estudiantes]] [[in class|en clase]]:', options: ['[[student engagement|participación del estudiante]]', '[[attendance|asistencia]]', '[[participation|participación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Evaluating students|Evaluar estudiantes]] [[or learning|o aprendizaje]]:', options: ['[[assessment|evaluación]]', '[[examination|examen]]', '[[grading|calificación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning online|Aprendizaje en línea]] [[via internet|vía internet]]:', options: ['[[e-learning|aprendizaje electrónico]]', '[[blended learning|aprendizaje híbrido]]', '[[distance learning|aprendizaje a distancia]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A free online course|Un curso online gratuito]] [[for many people|para muchas personas]]:', options: ['[[MOOC|curso masivo online]]', '[[webinar|seminario web]]', '[[tutorial|tutorial]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A live online|Un evento en vivo online]] [[presentation|presentación]]:', options: ['[[webinar|seminario web]]', '[[podcast|podcast]]', '[[video|vídeo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning by doing|Aprendizaje haciendo]] [[practical tasks|tareas prácticas]]:', options: ['[[hands-on learning|aprendizaje práctico]]', '[[rote learning|aprendizaje memorístico]]', '[[self-study|autoaprendizaje]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A problem or project|Un problema o proyecto]] [[to solve|a resolver]] [[in real life|en la vida real]]:', options: ['[[real-world task|tarea del mundo real]]', '[[assignment|tarea]]', '[[exercise|ejercicio]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning at your own pace|Aprendizaje a tu propio ritmo]]:', options: ['[[self-paced learning|aprendizaje a ritmo propio]]', '[[synchronous learning|aprendizaje síncrono]]', '[[asynchronous learning|aprendizaje asíncrono]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning through|Aprendizaje a través de]] [[games|juegos]]:', options: ['[[gamification|gamificación]]', '[[play|juego]]', '[[game|juego]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Turning learning|Convertir el aprendizaje]] [[into a game|en un juego]]:', options: ['[[gamification|gamificación]]', '[[assessment|evaluación]]', '[[competition|competencia]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Learning by flipping|Aprendizaje invirtiendo]] [[class and homework|clase y deberes]]:', options: ['[[flipped classroom|clase invertida]]', '[[blended learning|aprendizaje híbrido]]', '[[online learning|aprendizaje en línea]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Adapting teaching|Adaptar la enseñanza]] [[to each student|a cada estudiante]]:', options: ['[[personalised learning|aprendizaje personalizado]]', '[[differentiation|diferenciación]]', '[[individual|individual]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Giving feedback|Dar retroalimentación]] [[to improve|para mejorar]] [[learning|aprendizaje]]:', options: ['[[formative feedback|retroalimentación formativa]]', '[[grade|nota]]', '[[mark|calificación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u48-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make learning|Hacer el aprendizaje]] [[more interactive|más interactivo]] [[and|y]] [[engaging|atractivo]]:', options: ['[[to engage students|implicar a los estudiantes]]', '[[to assess|evaluar]]', '[[to grade|calificar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
