/**
 * Unidad 15 B2 — Lección 1: Gramática (Repaso 11-14: Relative clauses, Modals, Modal Deduction)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Repaso 11–14|Repaso 11–14]]';
const INSTRUCTIONS = 'Repaso de oraciones de relativo, modales (must, have to, need to, needn\'t) y modales de deducción (must have, might have, can\'t have).';

export const UNIT_15_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u15-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The museum ____ we visited last month has a new exhibition.|El museo ____ que visitamos el mes pasado tiene una nueva exposición.]]', options: ['[[that|que]]', '[[where|donde]]', '[[whose|cuyo]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[Defining clause with that/which for things|Cláusula explicativa con that/which para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Employees ____ submit their reports by Friday. It\'s mandatory.|Los empleados ____ deben enviar sus informes antes del viernes. Es obligatorio.]]', options: ['[[must|deben]]', '[[needn\'t|no necesitan]]', '[[don\'t have to|no tienen que]]'], correctAnswer: 0, explanation: '[[Obligation|Obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She ____ missed the flight. Her luggage was on the carousel when we arrived.|No ____ puede haber perdido el vuelo. Su equipaje estaba en la cinta cuando llegamos.]]', options: ['[[can\'t have|no puede haber]]', '[[must have|debe haber]]', '[[might have|podría haber]]'], correctAnswer: 'can\'t have', acceptableAnswers: ['can\'t have'], explanation: '[[Impossibility|Imposibilidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The director ____ films have won Oscars is giving a masterclass.|El director ____ cuyas películas han ganado Oscars dará una masterclass.]]', options: ['[[whose|cuyo]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 0, explanation: '[[Whose for possession|Whose para posesión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You ____ worry about the bill; I\'ve already paid it.|No ____ preocuparte por la cuenta; ya la he pagado.]]', options: ['[[needn\'t|no necesitas]]', '[[must|debes]]', '[[have to|tienes que]]'], correctAnswer: 'needn\'t', acceptableAnswers: ['needn\'t', 'don\'t need to', 'don\'t have to'], explanation: '[[No necessity|Ausencia de necesidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The contract ____ they signed last week has been cancelled.|El contrato ____ que firmaron la semana pasada ha sido cancelado.]]', options: ['[[that|que]]', '[[where|donde]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[That/which for things|That/which para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They ____ received our offer. The email was read two hours ago.|Deben ____ haber recibido nuestra oferta. El correo fue leído hace dos horas.]]', options: ['[[must have|deben haber]]', '[[can\'t have|no pueden haber]]', '[[might have|podrían haber]]'], correctAnswer: 'must have', acceptableAnswers: ['must have'], explanation: '[[Certainty|Certeza]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[This is the square ____ the annual parade takes place.|Esta es la plaza ____ donde tiene lugar el desfile anual.]]', options: ['[[where|donde]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Where for places|Where para lugares]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To get a refund, you ____ show the original receipt.|Para obtener reembolso, ____ mostrar el recibo original.]]', options: ['[[need to|necesitas]]', '[[needn\'t|no necesitas]]', '[[mustn\'t|no debes]]'], correctAnswer: 'need to', acceptableAnswers: ['need to', 'must', 'have to'], explanation: '[[Necessity|Necesidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Madrid, ____ is the capital of Spain, hosts many cultural events.|Madrid, ____ que es la capital de España, acoge muchos eventos culturales.]]', options: ['[[which|que]]', '[[who|quien]]', '[[that|que]]'], correctAnswer: 0, explanation: '[[Non-defining with which|No explicativa con which]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We ____ attend the meeting yesterday. It was compulsory.|Tuvimos que ____ asistir a la reunión ayer. Era obligatorio.]]', options: ['[[had to|tuvimos que]]', '[[must|debemos]]', '[[need to|necesitamos]]'], correctAnswer: 'had to', acceptableAnswers: ['had to'], explanation: '[[Past obligation|Obligación en pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The budget ____ been cut. All projects are on hold.|El presupuesto ____ debe haber sido recortado. Todos los proyectos están en espera.]]', options: ['[[must have been|debe haber sido]]', '[[can\'t have been|no puede haber sido]]', '[[might have been|podría haber sido]]'], correctAnswer: 0, explanation: '[[Deduction from consequence|Deducción por consecuencia]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[People ____ respect local customs usually have a better experience.|La gente ____ que respeta las costumbres locales suele tener una mejor experiencia.]]', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who for people|Who para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You ____ bring your passport to the airport. It\'s required.|____ debes llevar tu pasaporte al aeropuerto. Es obligatorio.]]', options: ['[[must|Debes]]', '[[needn\'t|No necesitas]]', '[[don\'t have to|No tienes que]]'], correctAnswer: 0, explanation: '[[Obligation|Obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The series ____ we binge-watched last weekend has a new season.|La serie ____ que vimos el fin de semana pasado tiene una nueva temporada.]]', options: ['[[that|que]]', '[[where|donde]]', '[[who|quien]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which for things|That/which para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The deal ____ fallen through. Nobody has mentioned it for weeks.|El trato ____ podría haber fracasado. Nadie lo ha mencionado en semanas.]]', options: ['[[might have|podría haber]]', '[[must have|debe haber]]', '[[can\'t have|no puede haber]]'], correctAnswer: 0, explanation: '[[Possibility|Posibilidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Companies ____ keep accurate records by law.|Las empresas ____ deben mantener registros precisos por ley.]]', options: ['[[have to|tienen que]]', '[[needn\'t|no necesitan]]', '[[don\'t need to|no necesitan]]'], correctAnswer: 'have to', acceptableAnswers: ['have to', 'must'], explanation: '[[Legal obligation|Obligación legal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u15-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 11–14', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The composer ____ music inspired the ballet is world-famous.|El compositor ____ cuya música inspiró el ballet es mundialmente famoso.]]', options: ['[[whose|cuyo]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 0, explanation: '[[Whose for possession|Whose para posesión]].' }] }, topicName: 'Grammar' },
];
