/**
 * Unidad 64 B2 — Lección 5: Expresión oral (Collocations)
 * 10 ejercicios (B2: speaking con collocations de examen)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_64_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u64-l5-s1', type: 'pronunciation', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee y repite en voz alta.', targetText: '[[I try to make steady progress every week|Intento avanzar de forma constante cada semana]].', expectedResponse: 'I try to make steady progress every week.' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s2', type: 'pronunciation', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee y repite en voz alta.', targetText: '[[You need to take responsibility for your learning|Necesitas asumir la responsabilidad de tu aprendizaje]].', expectedResponse: 'You need to take responsibility for your learning.' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s3', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla 1 minuto: ¿cómo haces progreso con tu inglés? Usa: make progress, make an effort, do homework.', prompt: '[[How do you make progress with your English? Use: make progress, make an effort, do homework.|¿Cómo avanzas con tu inglés? Usa: make progress, make an effort, do homework.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s4', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde: describe una decisión importante. Usa: make a decision, take a risk, make a mistake (si aplica).', prompt: '[[Describe an important decision. Use: make a decision, take a risk, make a mistake.|Describe una decisión importante. Usa: make a decision, take a risk, make a mistake.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s5', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Da consejos de estudio en voz alta. Usa: take a break, make a plan, do your homework.', prompt: '[[Give study advice using: take a break, make a plan, do your homework.|Da consejos de estudio usando: take a break, make a plan, do your homework.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s6', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica 4 frases: make a good impression, make an appointment, do a favour, have a great time.', prompt: '[[Say 4 sentences using: make a good impression, make an appointment, do a favour, have a great time.|Di 4 frases usando: make a good impression, make an appointment, do a favour, have a great time.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s7', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Describe un problema y una solución (1 minuto). Usa: make a complaint, take action, make a suggestion.', prompt: '[[Describe a problem and a solution. Use: make a complaint, take action, make a suggestion.|Describe un problema y una solución. Usa: make a complaint, take action, make a suggestion.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s8', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde: ¿qué haces para mantenerte en contacto con amigos? Usa: keep in touch.', prompt: '[[What do you do to keep in touch with friends?|¿Qué haces para mantenerte en contacto con amigos?]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s9', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Cuenta una pequeña historia (45 segundos) usando 3 collocations de la unidad.', prompt: '[[Tell a short story using 3 collocations from this unit.|Cuenta una pequeña historia usando 3 colocaciones de esta unidad.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u64-l5-s10', type: 'speaking', level: 'B2', topic: 'core-collocations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde: ¿por qué las collocations ayudan en Cambridge B2? (30–45 segundos).', prompt: '[[Why do collocations help in Cambridge B2?|¿Por qué las colocaciones ayudan en Cambridge B2?]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];

