/**
 * Unidad 23 B2 — Lección 2: Vocabulario (Communication)
 * 18 ejercicios (B2: recreado con palabras reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Communication|Comunicación]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con comunicación.';

export const UNIT_23_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u23-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To exchange information or ideas|Intercambiar información o ideas]]:', options: ['[[communicate|comunicar]]', '[[commute|desplazarse]]', '[[compute|calcular]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A misunderstanding between people|Malentendido entre personas]]:', options: ['[[miscommunication|mala comunicación]]', '[[misconception|concepción errónea]]', '[[misdemeanour|delito menor]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To express your thoughts clearly|Expresar tus pensamientos con claridad]]:', options: ['[[articulate|articular]]', '[[approximate|aproximado]]', '[[artificial|artificial]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Feedback that is not spoken|Retroalimentación que no es hablada]]:', options: ['[[non-verbal|no verbal]]', '[[non-stop|sin parar]]', '[[non-profit|sin ánimo de lucro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To pass on information to others|Transmitir información a otros]]:', options: ['[[convey|transmitir]]', '[[convict|condenar]]', '[[convert|convertir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A formal discussion between opposing sides|Discusión formal entre partes opuestas]]:', options: ['[[negotiation|negociación]]', '[[navigation|navegación]]', '[[notification|notificación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To interrupt someone rudely|Interrumpir a alguien groseramente]]:', options: ['[[butt in|meterse]]', '[[back out|echarse atrás]]', '[[break in|entrar por la fuerza]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To reach an agreement|Llegar a un acuerdo]]:', options: ['[[come to terms|llegar a un acuerdo]]', '[[come across|encontrarse con]]', '[[come up with|ocurrírsele]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make your point understood|Hacer que tu punto se entienda]]:', options: ['[[get your message across|hacer llegar tu mensaje]]', '[[get over|superar]]', '[[get through|atravesar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To speak frankly and honestly|Hablar con franqueza y honestidad]]:', options: ['[[speak your mind|decir lo que piensas]]', '[[speak up|hablar más alto]]', '[[speak out|manifestarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A barrier that prevents understanding|Barrera que impide el entendimiento]]:', options: ['[[communication barrier|barrera de comunicación]]', '[[communication breakdown|fallo de comunicación]]', '[[communication channel|canal de comunicación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a message"|Colocación: "to ____ a message"]]', options: ['[[convey|transmitir]]', '[[convince|convencer]]', '[[convert|convertir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ feedback"|Colocación: "to ____ feedback"]]', options: ['[[give|dar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ in touch"|Expresión: "to ____ in touch"]]', options: ['[[stay|mantenerse]]', '[[keep|mantener]]', '[[remain|permanecer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "____ communication"|Colocación: "____ communication"]] [[(clear)|(clara)]]', options: ['[[effective|efectiva]]', '[[efficient|eficiente]]', '[[effortless|sin esfuerzo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ the point"|Expresión: "to ____ the point"]]', options: ['[[get to|llegar al]]', '[[go to|ir a]]', '[[come to|llegar a]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a conversation"|Colocación: "to ____ a conversation"]]', options: ['[[strike up|iniciar]]', '[[strike out|fallar]]', '[[strike down|derribar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u23-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Communication', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ someone up to speed"|Expresión: "to ____ someone up to speed"]]', options: ['[[bring|poner a alguien al día]]', '[[take|llevar]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
