/**
 * Unidad 38 B2 — Lección 2: Vocabulario (Leisure extended)
 * 18 ejercicios (B2: ocio, hobbies, tiempo libre)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Leisure (extended)|Ocio (ampliado)]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con ocio.';

export const UNIT_38_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u38-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[An activity done for pleasure in free time|Actividad hecha por placer en tiempo libre]]:', options: ['[[hobby|hobby]]', '[[work|trabajo]]', '[[chore|tarea]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a hobby"|Colocación: "to ____ a hobby"]]', options: ['[[take up|empezar]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A meal outdoors, often in nature|Una comida al aire libre, a menudo en la naturaleza]]:', options: ['[[picnic|picnic]]', '[[barbecue|barbacoa]]', '[[camping|camping]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To rest and recover energy|Descansar y recuperar energía]]:', options: ['[[unwind|relajarse]]', '[[stress|estresarse]]', '[[rush|apurarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ time"|Colocación: "to ____ time"]] [[for oneself|para uno mismo]]', options: ['[[set aside|reservar]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A planned route for a trip|Una ruta planificada para un viaje]]:', options: ['[[itinerary|itinerario]]', '[[schedule|horario]]', '[[plan|plan]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Staying in a tent outdoors|Quedarse en una tienda al aire libre]]:', options: ['[[camping|camping]]', '[[hiking|senderismo]]', '[[picnic|picnic]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a trip"|Colocación: "to ____ a trip"]]', options: ['[[set off on|partir en]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Walking in nature for pleasure|Caminar en la naturaleza por placer]]:', options: ['[[hiking|senderismo]]', '[[jogging|trotar]]', '[[cycling|ciclismo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To discover new places|Descubrir nuevos lugares]]:', options: ['[[explore|explorar]]', '[[visit|visitar]]', '[[travel|viajar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A group that meets for a shared interest|Un grupo que se reúne por un interés compartido]]:', options: ['[[club|club]]', '[[team|equipo]]', '[[group|grupo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a challenge"|Colocación: "to ____ a challenge"]]', options: ['[[take on|asumir]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Time when you are not working|Tiempo cuando no trabajas]]:', options: ['[[leisure time|tiempo libre]]', '[[overtime|horas extra]]', '[[deadline|fecha límite]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Something you do to pass time|Algo que haces para pasar el tiempo]]:', options: ['[[pastime|pasatiempo]]', '[[work|trabajo]]', '[[chore|tarea]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ an old friend"|Colocación: "encontrarse con un viejo amigo"]]', options: ['[[run into|encontrarse con]]', '[[meet|conocer]]', '[[see|ver]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A long walk in the countryside|Una caminata larga en el campo]]:', options: ['[[hike|excursión]]', '[[stroll|paseo]]', '[[run|carrera]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use all of something|Usar todo de algo]]:', options: ['[[run out of|quedarse sin]]', '[[finish|terminar]]', '[[end|acabar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u38-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Leisure (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ a club"|Expresión: "crear un club"]]', options: ['[[set up|crear]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
