/**
 * Unidad 31 B2 — Lección 2: Vocabulario (Education extended)
 * 18 ejercicios (B2: educación universitaria, exámenes, aprendizaje)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Education (extended)|Educación (ampliado)]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con educación.';

export const UNIT_31_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u31-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A qualification for postgraduate study|Calificación para estudios de posgrado]]:', options: ['[[degree|título]]', '[[diploma|diploma]]', '[[certificate|certificado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The main subject you study at university|La asignatura principal que estudias en la universidad]]:', options: ['[[major|especialidad]]', '[[minor|asignatura secundaria]]', '[[module|módulo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A period of study at university|Un período de estudio en la universidad]]:', options: ['[[semester|semestre]]', '[[term|trimestre]]', '[[quarter|trimestre]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To formally register for a course|Registrarse formalmente en un curso]]:', options: ['[[enrol|matricularse]]', '[[apply|solicitar]]', '[[attend|asistir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A long essay for a degree|Ensayo largo para un título]]:', options: ['[[dissertation|tesina]]', '[[thesis|tesis]]', '[[assignment|trabajo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A meeting with a supervisor to discuss progress|Reunión con un supervisor para discutir progreso]]:', options: ['[[tutorial|tutorial]]', '[[lecture|conferencia]]', '[[seminar|seminario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a degree"|Colocación: "to ____ a degree"]]', options: ['[[obtain|obtener]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a deadline"|Colocación: "to ____ a deadline"]]', options: ['[[meet|cumplir]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The highest grade in an exam|La nota más alta en un examen]]:', options: ['[[distinction|distinción]]', '[[pass|aprobado]]', '[[fail|suspenso]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To leave a course before completing it|Dejar un curso antes de completarlo]]:', options: ['[[drop out|abandonar]]', '[[graduate|graduarse]]', '[[pass|aprobar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The person who guides your research|La persona que guía tu investigación]]:', options: ['[[supervisor|supervisor]]', '[[tutor|tutor]]', '[[lecturer|profesor]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ research"|Colocación: "to ____ research"]]', options: ['[[conduct|realizar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A year of travel or work before university|Un año de viaje o trabajo antes de la universidad]]:', options: ['[[gap year|año sabático]]', '[[sabbatical|sabático]]', '[[break|descanso]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The list of books for a course|La lista de libros para un curso]]:', options: ['[[reading list|lista de lectura]]', '[[bibliography|bibliografía]]', '[[syllabus|sílabo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a degree"|Colocación: "to ____ a degree"]] [[in|en]] [[law|derecho]]', options: ['[[pursue|estudiar]]', '[[make|hacer]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ceremony when you receive your degree|La ceremonia cuando recibes tu título]]:', options: ['[[graduation|graduación]]', '[[convocation|convocatoria]]', '[[commencement|inicio]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To give a formal talk to students|Dar una charla formal a estudiantes]]:', options: ['[[deliver a lecture|impartir una conferencia]]', '[[give a lesson|dar una clase]]', '[[hold a seminar|celebrar un seminario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u31-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Education (extended)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ the course"|Expresión: "completar el curso"]]', options: ['[[complete|completar]]', '[[finish|terminar]]', '[[pass|aprobar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
