/**
 * Unidad 26 B2 — Lección 5: Expresión oral (Sustainability & Eco-living)
 * 18 ejercicios (B2: phrasal verbs GET, GIVE, GO)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_26_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u26-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[It took her months|Le llevó meses]] [[to get over|superar]] [[her old habits|sus viejos hábitos]] [[of single-use plastic|de plástico de un solo uso]].', expectedResponse: 'It took her months to get over her old habits of single-use plastic.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He gave up|Dejó de usar]] [[plastic bags|las bolsas de plástico]] [[last month|el mes pasado]] [[and feels much better now|y se siente mucho mejor ahora]].', expectedResponse: 'He gave up on plastic bags last month and feels much better now.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She went through a difficult period|Atravesó un período difícil]] [[when her community was transitioning to zero waste|cuando su comunidad estaba en transición al cero residuos]].', expectedResponse: 'She went through a difficult period when her community was transitioning to zero waste.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We get along well|Nos llevamos bien]] [[with our eco-friendly neighbours|con nuestros vecinos ecológicos]] — [[they\'re very supportive|son muy solidarios]].', expectedResponse: 'We get along well with our eco-friendly neighbours — they\'re very supportive.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Don\'t give up now|No te rindas ahora]] — [[you\'re so close to reducing your carbon footprint|estás tan cerca de reducir tu huella de carbono]]!', expectedResponse: 'Don\'t give up now — you\'re so close to reducing your carbon footprint!' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The recycling workshop went on|El taller de reciclaje continuó]] [[until late last night|hasta tarde anoche]] — [[we had a lot to discuss|teníamos mucho que discutir]].', expectedResponse: 'The recycling workshop went on until late last night — we had a lot to discuss.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I couldn\'t get through to the eco centre|No pude contactar al centro ecológico]] [[on the phone|por teléfono]] — [[the line was busy|la línea estaba ocupada]].', expectedResponse: 'I couldn\'t get through to the eco centre on the phone — the line was busy.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[After hours of debating|Después de horas debatiendo]], [[they gave in|cedieron]] [[and agreed to support the renewable energy project|y acordaron apoyar el proyecto de energía renovable]].', expectedResponse: 'After hours of debating, they gave in and agreed to support the renewable energy project.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[The eco workshop went off well|El taller ecológico salió bien]] — [[they learned a lot about composting|aprendieron mucho sobre compostaje]].', expectedResponse: 'The eco workshop went off well — they learned a lot about composting.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los phrasal verbs.', targetText: '[[We got through the rough patch yesterday|Superamos el bache difícil ayer]] — [[the eco transition was hard but we made it|la transición ecológica fue dura pero lo logramos]].', expectedResponse: 'We got through the rough patch yesterday — the eco transition was hard but we made it.' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s11', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe un período difícil que atravesaste (go through) en tu transición ecológica.', prompt: '[[Describe a difficult period you went through in your eco transition. Use: go through, get over, give up.|Describe un período difícil que atravesaste en tu transición ecológica. Usa: go through, get over, give up.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s12', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica qué harías si un amigo decidiera rendirse (give up) en su camino hacia el cero residuos.', prompt: '[[Explain what you would do if a friend decided to give up on their zero-waste journey. Use: give up, get through, get along.|Explica qué harías si un amigo decidiera rendirse en su camino hacia el cero residuos. Usa: give up, get through, get along.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s13', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cómo te llevas (get along) con tus vecinos o familia respecto a hábitos ecológicos?', prompt: '[[How do you get along with your neighbours or family regarding eco habits? Give examples.|¿Cómo te llevas con tus vecinos o familia respecto a hábitos ecológicos? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s14', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe algo que superaste (get over) en tu camino hacia una vida más sostenible.', prompt: '[[Describe something you got over in your journey towards sustainable living. Use: get over, go through, get through.|Describe algo que superaste en tu camino hacia una vida más sostenible. Usa: get over, go through, get through.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s15', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these phrasal verbs in your own sentences:|Usa estos phrasal verbs en tus propias oraciones:]]\n[[- get over|- get over]]\n[[- give up|- give up]]\n[[- go through|- go through]]\n[[- get along|- get along]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s16', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe un taller o iniciativa ecológica que salió bien (go off) en tu experiencia.', prompt: '[[Describe an eco workshop or initiative that went off well. Mention what happened and why it was successful.|Describe un taller o iniciativa ecológica que salió bien. Menciona qué pasó y por qué fue exitosa.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s17', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe un desafío en sostenibilidad que superaste (get through) con éxito.', prompt: '[[Describe a sustainability challenge you got through successfully. Use: get through, give up, go through.|Describe un desafío en sostenibilidad que superaste con éxito. Usa: get through, give up, go through.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u26-l5-s18', type: 'speaking', level: 'B2', topic: 'Sustainability & Eco-living', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿alguna vez has cedido (give in) en una discusión sobre sostenibilidad? ¿Por qué?', prompt: '[[Have you ever given in during a discussion about sustainability? Why? Use give in and get through.|¿Alguna vez has cedido en una discusión sobre sostenibilidad? ¿Por qué? Usa give in y get through.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
