/**
 * Unidad 30 B2 — Lección 1: Gramática (Repaso 26–29)
 * 18 ejercicios (B2: Phrasal verbs GET/GIVE/GO, LOOK/MAKE/PUT, Collocations Verb+Noun, Adj+Noun)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Repaso 26–29|Repaso 26–29]]';
const INSTRUCTIONS = 'Repaso de phrasal verbs (GET, GIVE, GO, LOOK, MAKE, PUT) y colocaciones.';

export const UNIT_30_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u30-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It took her months|Le llevó meses]] ____ [[the loss|superar la pérdida]] [[of her job|de su trabajo]].', options: ['[[to get over|superar]]', '[[to get through|terminar]]', '[[to get along|llevarse bien]]'], correctAnswer: 'to get over', acceptableAnswers: ['to get over'], explanation: '[[Get over = recover from|Get over = recuperarse de]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We need to|Necesitamos]] ____ [[cheaper flights|vuelos más baratos]] [[before|antes de]] [[booking|reservar]] [[our trip|nuestro viaje]].', options: ['[[look into|investigar]]', '[[look after|cuidar]]', '[[look forward to|esperar con ilusión]]'], correctAnswer: 0, explanation: '[[Look into = investigate|Look into = investigar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I need to|Necesito]] ____ [[a break|un descanso]] — [[I\'ve been working for hours|he estado trabajando durante horas]].', options: ['[[take|tomar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 'take', acceptableAnswers: ['take'], explanation: '[[Take a break = have a rest|Take a break = tomar un descanso]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We had to cancel|Tuvimos que cancelar]] [[the picnic|el picnic]] [[because of|debido a]] ____ [[rain|lluvia]].', options: ['[[heavy|fuerte]]', '[[strong|fuerte]]', '[[big|grande]]'], correctAnswer: 0, explanation: '[[Heavy rain = intense rain|Heavy rain = lluvia fuerte]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[the trip|el viaje]] [[until|hasta]] [[next month|el próximo mes]] [[because|porque]] [[of|de]] [[the weather|el tiempo]].', options: ['[[put off|pospusimos]]', '[[put on|nos pusimos]]', '[[put up with|toleramos]]'], correctAnswer: 'put off', acceptableAnswers: ['put off'], explanation: '[[Put off = postpone|Put off = posponer]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[a decision|una decisión]] [[yesterday|ayer]] — [[we\'re going to move|nos mudamos]] [[next month|el próximo mes]].', options: ['[[made|tomamos]]', '[[took|tomamos]]', '[[did|hicimos]]'], correctAnswer: 0, explanation: '[[Make a decision = decide|Make a decision = tomar una decisión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[a difficult period|un período difícil]] [[when|cuando]] [[her company|su empresa]] [[was restructuring|se estaba reestructurando]].', options: ['[[went through|atravesó]]', '[[went on|continuó]]', '[[went off|explotó]]'], correctAnswer: 'went through', acceptableAnswers: ['went through'], explanation: '[[Go through = experience|Go through = experimentar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The hotel|El hotel]] ____ [[for|por]] [[the delay|el retraso]] [[by|con]] [[offering|ofreciendo]] [[a free upgrade|una mejora gratis]].', options: ['[[made up|compensó]]', '[[made out|distinguió]]', '[[made for|se dirigió a]]'], correctAnswer: 0, explanation: '[[Make up for = compensate|Make up for = compensar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He made|Hizo]] ____ [[progress|progreso]] [[this year|este año]] — [[his English|su inglés]] [[has improved a lot|ha mejorado mucho]].', options: ['[[great|gran]]', '[[heavy|pesado]]', '[[strong|fuerte]]'], correctAnswer: 'great', acceptableAnswers: ['great'], explanation: '[[Great progress = significant progress|Great progress = gran progreso]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Don\'t|No]] ____ [[now|ahora]] — [[you\'re so close|estás tan cerca]] [[to finishing|de terminar]]!', options: ['[[give up|te rindas]]', '[[give in|cedas]]', '[[give away|regales]]'], correctAnswer: 0, explanation: '[[Give up = stop trying|Give up = rendirse]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can you|¿Puedes]] ____ [[my luggage|mi equipaje]] [[while|mientras]] [[I|yo]] [[check in|facturo]]?', options: ['[[look after|cuidar]]', '[[look into|investigar]]', '[[look for|buscar]]'], correctAnswer: 'look after', acceptableAnswers: ['look after'], explanation: '[[Look after = take care of|Look after = cuidar]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ [[a mistake|un error]] [[when|cuando]] [[she sent|envió]] [[the email|el correo]] [[to the wrong person|a la persona equivocada]].', options: ['[[made|cometió]]', '[[took|tomó]]', '[[did|hizo]]'], correctAnswer: 0, explanation: '[[Make a mistake = err|Make a mistake = cometer un error]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The presentation|La presentación]] ____ [[well|bien]] — [[everyone liked it|a todos les gustó]].', options: ['[[went off|salió bien]]', '[[went on|continuó]]', '[[went through|atravesó]]'], correctAnswer: 'went off', acceptableAnswers: ['went off'], explanation: '[[Go off = happen successfully|Go off = salir bien]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ [[responsibility|responsabilidad]] [[for|de]] [[the project|el proyecto]] [[last week|la semana pasada]].', options: ['[[took|asumió]]', '[[made|hizo]]', '[[did|hizo]]'], correctAnswer: 0, explanation: '[[Take responsibility = assume responsibility|Take responsibility = asumir responsabilidad]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ [[visiting|visitar]] [[my friend|a mi amigo]] [[in Barcelona|en Barcelona]] [[next month|el próximo mes]].', options: ['[[am looking forward to|estoy deseando]]', '[[am looking after|estoy cuidando]]', '[[am looking into|estoy investigando]]'], correctAnswer: 'am looking forward to', acceptableAnswers: ['am looking forward to'], explanation: '[[Look forward to = anticipate with pleasure|Look forward to = esperar con ilusión]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The hotel has|El hotel tiene]] ____ [[views|vistas]] [[of the sea|del mar]] — [[it\'s breathtaking|es impresionante]].', options: ['[[stunning|impresionantes]]', '[[heavy|pesadas]]', '[[strong|fuertes]]'], correctAnswer: 0, explanation: '[[Stunning views = impressive views|Stunning views = vistas impresionantes]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ [[well|bien]] [[with|con]] [[our new colleague|nuestro nuevo compañero]] — [[he\'s very friendly|es muy amigable]].', options: ['[[get along|nos llevamos]]', '[[get over|nos recuperamos]]', '[[get through|terminamos]]'], correctAnswer: 'get along', acceptableAnswers: ['get along'], explanation: '[[Get along = have a good relationship|Get along = llevarse bien]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u30-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 26–29', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We had|Tuvimos]] ____ [[discussion|discusión]] [[about|sobre]] [[the project|el proyecto]] [[yesterday|ayer]].', options: ['[[a lively|una animada]]', '[[a heavy|una pesada]]', '[[a strong|una fuerte]]'], correctAnswer: 0, explanation: '[[Lively discussion = animated discussion|Lively discussion = discusión animada]].' }] }, topicName: 'Grammar' },
];
