/**
 * Unidad 2 B2 — Lección 2: Vocabulario (Work)
 * 18 ejercicios (B2: más vocabulario y complejidad que B1)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Work|Trabajo]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_2_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u2-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To apply for a job|Solicitar un trabajo]]:', options: ['[[apply for|solicitar]]', '[[apply to|aplicar a]]', '[[apply with|aplicar con]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who works for a company|Persona que trabaja para una empresa]]:', options: ['[[employee|empleado]]', '[[employer|empleador]]', '[[employment|empleo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To give up your job|Dejar tu trabajo]]:', options: ['[[resign|dimitir]]', '[[retire|jubilarse]]', '[[dismiss|despedir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Extra hours worked beyond normal|Horas extra más allá de lo normal]]:', options: ['[[overtime|horas extra]]', '[[deadline|fecha límite]]', '[[shift|turno]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To discuss terms in business|Discutir condiciones en negocios]]:', options: ['[[negotiate|negociar]]', '[[discuss|discutir]]', '[[argue|discutir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A fixed date by which something must be done|Fecha fija para completar algo]]:', options: ['[[deadline|fecha límite]]', '[[schedule|horario]]', '[[appointment|cita]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To be promoted|Ser ascendido]]:', options: ['[[get promoted|ser ascendido]]', '[[get fired|ser despedido]]', '[[get hired|ser contratado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A meeting to assess performance|Reunión para evaluar rendimiento]]:', options: ['[[performance review|evaluación de rendimiento]]', '[[job interview|entrevista de trabajo]]', '[[board meeting|reunión de junta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To work from home|Trabajar desde casa]]:', options: ['[[work remotely|trabajar a distancia]]', '[[work overtime|trabajar horas extra]]', '[[work part-time|trabajar a tiempo parcial]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To take responsibility|Asumir responsabilidad]]:', options: ['[[take on|asumir]]', '[[take off|quitarse]]', '[[take up|ocupar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person in charge of a team|Persona a cargo de un equipo]]:', options: ['[[supervisor|supervisor]]', '[[colleague|colega]]', '[[subordinate|subordinado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make a formal request for a job|Hacer una solicitud formal de trabajo]]:', options: ['[[submit an application|enviar una solicitud]]', '[[hand in notice|entregar aviso]]', '[[sign a contract|firmar contrato]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Skills and experience listed for a job|Habilidades y experiencia para un trabajo]]:', options: ['[[qualifications|cualificaciones]]', '[[references|referencias]]', '[[benefits|beneficios]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To give your job to someone else|Dar tu trabajo a otra persona]]:', options: ['[[hand over|entregar]]', '[[hand in|entregar]]', '[[hand out|repartir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A period of time working for experience|Período trabajando para ganar experiencia]]:', options: ['[[internship|prácticas]]', '[[apprenticeship|aprendizaje]]', '[[probation|período de prueba]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To increase in level or position|Aumentar de nivel o posición]]:', options: ['[[advance|avanzar]]', '[[retire|jubilarse]]', '[[resign|dimitir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Extra pay for extra hours|Pago extra por horas extra]]:', options: ['[[overtime pay|pago por horas extra]]', '[[bonus|bonus]]', '[[raise|aumento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u2-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To inform your employer you are leaving|Informar a tu empleador que te vas]]:', options: ['[[hand in your notice|entregar tu aviso]]', '[[get fired|ser despedido]]', '[[take leave|coger baja]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
