/**
 * Unidad 18 B2 — Lección 2: Vocabulario (Food and drink)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Food and drink|Comida y bebida]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con comida y bebida.';

export const UNIT_18_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u18-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The list of dishes available at a restaurant|Lista de platos disponibles en un restaurante]]:', options: ['[[menu|carta/menú]]', '[[recipe|receta]]', '[[ingredients|ingredientes]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Food cooked in hot oil|Comida cocinada en aceite caliente]]:', options: ['[[fried|frito]]', '[[grilled|a la plancha]]', '[[baked|al horno]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A small amount of food eaten before the main course|Pequeña cantidad de comida antes del plato principal]]:', options: ['[[starter|entrante]]', '[[dessert|postre]]', '[[main course|plato principal]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Instructions for preparing a dish|Instrucciones para preparar un plato]]:', options: ['[[recipe|receta]]', '[[menu|menú]]', '[[ingredient|ingrediente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Food that has not been processed|Comida que no ha sido procesada]]:', options: ['[[fresh|fresco]]', '[[frozen|congelado]]', '[[canned|enlatado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who doesn\'t eat meat|Persona que no come carne]]:', options: ['[[vegetarian|vegetariano]]', '[[vegan|vegano]]', '[[carnivore|carnívoro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The sweet course at the end of a meal|Curso dulce al final de una comida]]:', options: ['[[dessert|postre]]', '[[starter|entrante]]', '[[appetizer|aperitivo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To add salt, pepper or spices to food|Añadir sal, pimienta o especias a la comida]]:', options: ['[[season|condimentar]]', '[[stir|remover]]', '[[slice|cortar en rodajas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A thick sauce served with food|Salsa espesa servida con comida]]:', options: ['[[gravy|salsa de carne]]', '[[dressing|aliño]]', '[[dip|salsa para mojar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Food that can be eaten without cooking|Comida que puede comerse sin cocinar]]:', options: ['[[raw|crudo]]', '[[burnt|quemado]]', '[[undercooked|poco hecho]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a meal" → preparar una comida|Colocación: "___ a meal" → preparar una comida]]', options: ['[[cook|preparar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ your appetite" → abrir el apetito|Colocación: "___ your appetite" → abrir el apetito]]', options: ['[[whet|abrir]]', '[[lose|perder]]', '[[spoil|estropear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "___ hungry" → estar hambriento|Expresión: "estar ___ hambriento"]]', options: ['[[ravenous|vorazmente]]', '[[slightly|ligeramente]]', '[[barely|apenas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ a diet" → seguir una dieta|Colocación: "___ a diet" → seguir una dieta]]', options: ['[[follow|seguir]]', '[[make|hacer]]', '[[break|romper]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The items used to make a dish|Los elementos usados para hacer un plato]]:', options: ['[[ingredients|ingredientes]]', '[[recipe|receta]]', '[[menu|menú]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "___ your fill" → comer hasta hartarse|Expresión: "comer ___ saciarse"]]', options: ['[[eat|comer]]', '[[have|tener]]', '[[get|conseguir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "___ weight" → ganar peso|Colocación: "___ weight" → ganar peso]]', options: ['[[gain|ganar]]', '[[put|poner]]', '[[add|añadir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u18-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Food and drink', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The taste of food when it has gone bad|El sabor de la comida cuando se ha echado a perder]]:', options: ['[[bitter|amargo]]', '[[sour|agrio]]', '[[rancid|rancio]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
