/**
 * Unidad 20 B2 — Lección 5: Expresión oral (Repaso: History, Adventure, Cooking, Literature)
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_20_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u20-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[The data are being analysed|Los datos están siendo analizados]] [[at the moment|en este momento]].', expectedResponse: 'The data are being analysed at the moment.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The route must be verified|La ruta debe ser verificada]] [[before we can attempt the climb|antes de intentar la ascensión]].', expectedResponse: 'The route must be verified before we can attempt the climb.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We had our roof repaired|Nos repararon el tejado]] [[last month|el mes pasado]].', expectedResponse: 'We had our roof repaired last month.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The kitchen was too small to fit everyone|La cocina era demasiado pequeña para caber todos]].', expectedResponse: 'The kitchen was too small to fit everyone.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She\'s by far the most talented writer|Es con diferencia la escritora más talentosa]] [[in the group|del grupo]].', expectedResponse: "She's by far the most talented writer in the group." }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It was such a difficult recipe|Era una receta tan difícil]] [[that most people gave up|que la mayoría abandonó]].', expectedResponse: 'It was such a difficult recipe that most people gave up.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The more you read|Cuanto más lees]], [[the better you write|mejor escribes]].', expectedResponse: 'The more you read, the better you write.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I don\'t have enough time to finish|No tengo suficiente tiempo para terminar]] [[this today|esto hoy]].', expectedResponse: "I don't have enough time to finish this today." }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[The report has been sent|El informe ha sido enviado]] [[to all stakeholders|a todos los interesados]].', expectedResponse: 'The report has been sent to all stakeholders.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en las palabras clave.', targetText: '[[The new edition is slightly better|La nueva edición es ligeramente mejor]] [[than the previous one|que la anterior]].', expectedResponse: 'The new edition is slightly better than the previous one.' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s11', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe algo que has tenido que hacer reparar (have something done).', prompt: '[[Describe something you had to get repaired (car, house, gear, device). Use "had something done" and passive structures.|Describe algo que tuviste que hacer reparar (coche, casa, equipo, dispositivo). Usa "had something done" y estructuras pasivas.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s12', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: compara dos cosas usando so/such, too/enough o comparativos avanzados.', prompt: '[[Compare two things (recipes, books, expeditions, heritage sites). Use so/such, too/enough, or advanced comparatives (the more... the more, by far, much).|Compara dos cosas (recetas, libros, expediciones, sitios patrimoniales). Usa so/such, too/enough o comparativos avanzados (the more... the more, by far, much).]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s13', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué debe ser hecho o puede ser mejorado en historia, aventura, cocina o literatura?', prompt: '[[What must be done or can be improved in history, adventure, cooking or literature? Use modal passive (must be done, should be improved, etc.).|¿Qué debe hacerse o puede mejorarse en historia, aventura, cocina o literatura? Usa pasiva con modal (must be done, should be improved, etc.).]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s14', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una situación en la que algo era "too" o "not enough".', prompt: '[[Describe a situation where something was too (expensive, difficult, far) or not enough (time, money, space). Use too + adj + to or not + adj + enough + to.|Describe una situación donde algo era demasiado (caro, difícil, lejos) o no suficiente (tiempo, dinero, espacio). Usa too + adj + to o not + adj + enough + to.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s15', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 2–3 frases con cada una.', prompt: '[[Use these structures in your own sentences:|Usa estas estructuras en tus propias oraciones:]]\n[[- have something done|- have something done]]\n[[- so/such... that|- so/such... that]]\n[[- the more... the more|- the more... the more]]\n[[- by far the most|- by far the most]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s16', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: explica algo que está siendo hecho o que fue hecho recientemente (passive).', prompt: '[[Explain something that is being done or was done recently (heritage restoration, expedition, cooking class, book launch). Use passive voice (is being built, was completed, etc.).|Explica algo que está siendo hecho o que fue hecho recientemente (restauración patrimonial, expedición, clase de cocina, lanzamiento de libro). Usa voz pasiva (is being built, was completed, etc.).]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s17', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: aplica "the more... the more" a tu vida o trabajo.', prompt: '[[Apply "the more... the more" to your life or work (e.g. "The more I read, the more I learn"). Give 2-3 examples.|Aplica "the more... the more" a tu vida o trabajo (ej. "The more I read, the more I learn"). Da 2-3 ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u20-l5-s18', type: 'speaking', level: 'B2', topic: 'Repaso 16–19', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué es "by far" el mejor o peor en algo que conoces?', prompt: '[[What is by far the best or worst in something you know (recipe, book, expedition, heritage site)? Use "by far the most/best/worst" and explain.|¿Qué es con diferencia lo mejor o peor en algo que conoces (receta, libro, expedición, sitio patrimonial)? Usa "by far the most/best/worst" y explica.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
