/**
 * Unidad 51 B2 — Lección 2: Vocabulario (Global Economic Crisis)
 * 18 ejercicios (B2: recession, inflation, unemployment, crisis, economy, markets, recovery)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Global Economic Crisis|Crisis económica global]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con economía y crisis.';

export const UNIT_51_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u51-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A period of economic decline|Un período de declive económico]]:', options: ['[[recession|recesión]]', '[[recovery|recuperación]]', '[[inflation|inflación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Rise in prices over time|Subida de precios con el tiempo]]:', options: ['[[inflation|inflación]]', '[[recession|recesión]]', '[[unemployment|desempleo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[People without jobs|Personas sin trabajo]]:', options: ['[[unemployment|desempleo]]', '[[recovery|recuperación]]', '[[inflation|inflación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A serious situation requiring emergency action|Situación grave que requiere acción urgente]]:', options: ['[[crisis|crisis]]', '[[recovery|recuperación]]', '[[market|mercado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The system of wealth and resources|El sistema de riqueza y recursos]]:', options: ['[[economy|economía]]', '[[market|mercado]]', '[[recovery|recuperación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where goods and services are traded|Donde se comercian bienes y servicios]]:', options: ['[[markets|mercados]]', '[[recession|recesión]]', '[[crisis|crisis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Return to normal or improved state|Retorno al estado normal o mejorado]]:', options: ['[[recovery|recuperación]]', '[[recession|recesión]]', '[[crisis|crisis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Sudden fall in stock prices|Caída repentina de precios bursátiles]]:', options: ['[[market crash|crash bursátil]]', '[[recovery|recuperación]]', '[[inflation|inflación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Money or assets put into something for profit|Dinero o activos invertidos para obtener ganancia]]:', options: ['[[investment|inversión]]', '[[recession|recesión]]', '[[unemployment|desempleo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Spreading risk across different assets|Repartir el riesgo entre diferentes activos]]:', options: ['[[diversification|diversificación]]', '[[crisis|crisis]]', '[[recovery|recuperación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Financial institution that holds money|Institución financiera que guarda dinero]]:', options: ['[[bank|banco]]', '[[market|mercado]]', '[[economy|economía]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Government financial aid|Ayuda financiera del gobierno]]:', options: ['[[bailout|rescate financiero]]', '[[recession|recesión]]', '[[inflation|inflación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Money or assets kept for future use|Dinero o activos guardados para uso futuro]]:', options: ['[[savings|ahorros]]', '[[recovery|recuperación]]', '[[crisis|crisis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Shares in a company|Participaciones en una empresa]]:', options: ['[[stocks|acciones]]', '[[recession|recesión]]', '[[unemployment|desempleo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To become stable again|Volver a estabilizarse]]:', options: ['[[to stabilise|estabilizarse]]', '[[to collapse|colapsar]]', '[[to crash|crash]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Sudden failure of a system|Fallo repentino de un sistema]]:', options: ['[[collapse|colapso]]', '[[recovery|recuperación]]', '[[inflation|inflación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Economic growth|Crecimiento económico]]:', options: ['[[recovery|recuperación]]', '[[recession|recesión]]', '[[crisis|crisis]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u51-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'business-economy', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To prevent something bad from happening|Evitar que algo malo ocurra]]:', options: ['[[to avoid|evitar]]', '[[to cause|causar]]', '[[to suffer|sufrir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
