/**
 * Unidad 44 B2 — Lección 5: Expresión oral (Medical Research & Health)
 * 18 ejercicios (B2: futuro perfecto e investigación médica)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_44_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u44-l5-s1', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[By next year, I will have graduated from university|Para el año que viene, me habré graduado de la universidad]].', expectedResponse: 'By next year, I will have graduated from university.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s2', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She will have finished the project by Friday|Habrá terminado el proyecto para el viernes]].', expectedResponse: 'She will have finished the project by Friday.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s3', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By 2030, scientists will have developed new treatments|Para 2030, los científicos habrán desarrollado nuevos tratamientos]].', expectedResponse: 'By 2030, scientists will have developed new treatments.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s4', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The clinical trial will have completed by next year|El ensayo clínico habrá completado para el año que viene]].', expectedResponse: 'The clinical trial will have completed by next year.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s5', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Healthcare will have improved significantly|La atención sanitaria habrá mejorado significativamente]].', expectedResponse: 'Healthcare will have improved significantly.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s6', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The breakthrough will have saved millions of lives|El avance habrá salvado millones de vidas]].', expectedResponse: 'The breakthrough will have saved millions of lives.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s7', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By the end of the decade, epidemiology will have advanced|Para final de la década, la epidemiología habrá avanzado]].', expectedResponse: 'By the end of the decade, epidemiology will have advanced.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s8', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By the time you arrive, the doctor will have left|Para cuando llegues, el doctor habrá salido]].', expectedResponse: 'By the time you arrive, the doctor will have left.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s9', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[I will have completed my PhD by next summer|Habré completado mi doctorado para el próximo verano]].', expectedResponse: 'I will have completed my PhD by next summer.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s10', type: 'pronunciation', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en will have.', targetText: '[[The research team will have published their findings|El equipo habrá publicado sus hallazgos]].', expectedResponse: 'The research team will have published their findings.' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s11', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe qué habrás logrado para 2030. Usa: will have + past participle.', prompt: '[[Describe what you will have achieved by 2030. Use: will have + past participle.|Describe qué habrás logrado para 2030. Usa: will have + participio pasado.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s12', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: predice avances médicos para la próxima década. Usa: by + future time.', prompt: '[[Predict medical advances for the next decade. Use: by + future time.|Predice avances médicos para la próxima década. Usa: by + tiempo futuro.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s13', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿cuál es la diferencia entre will + infinitive y will have + past participle?', prompt: '[[What is the difference between will + infinitive and will have + past participle? Give examples.|¿Cuál es la diferencia entre will + infinitivo y will have + participio pasado? Da ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s14', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe qué habrás terminado para el próximo año. Usa: by next year.', prompt: '[[Describe what you will have finished by next year. Use: by next year.|Describe qué habrás terminado para el próximo año. Usa: by next year.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s15', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con Future Perfect.', prompt: '[[Use Future Perfect in your own sentences:|Usa el Futuro Perfecto en tus propias oraciones:]]\n[[- By next month|Para el próximo mes]]\n[[- By the end of the year|Para final de año]]\n[[- By the time|Para cuando]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s16', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: ¿qué avances en healthcare esperas para 2030?', prompt: '[[What healthcare advances do you expect by 2030? Use Future Perfect.|¿Qué avances en atención sanitaria esperas para 2030? Usa Futuro Perfecto.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s17', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: explica cuándo usas Future Perfect.', prompt: '[[Explain when you use Future Perfect. Use examples.|Explica cuándo usas el Futuro Perfecto. Usa ejemplos.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u44-l5-s18', type: 'speaking', level: 'B2', topic: 'science-research', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿por qué es importante la investigación médica? Usa: breakthrough, clinical trial, healthcare.', prompt: '[[Why is medical research important? Use: breakthrough, clinical trial, healthcare.|¿Por qué es importante la investigación médica? Usa: breakthrough, clinical trial, healthcare.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
