/**
 * Unidad 8 B2 — Lección 1: Gramática (Mixed conditionals)
 * 18 ejercicios (B2: Past → present, Past → future: If I had..., I would...)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Mixed conditionals|Mixed conditionals]]';
const INSTRUCTIONS = 'Elige la opción correcta o completa el espacio.';

export const UNIT_8_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u8-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____[[the meeting|la reunión]] [[yesterday|ayer]], [[I|yo]] ____[[the details now|los detalles ahora]].', options: ['[[had attended|hubiera asistido a]]', '[[would know|conocería]]'], correctAnswer: 'had attended', acceptableAnswers: ['had attended'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would + infinitive|pasado perfecto + would + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[he|él]] ____[[the bus|el autobús]] [[this morning|esta mañana]], [[he|él]] ____[[here now|aquí ahora]].', options: ['[[had caught|hubiera cogido]] / [[would be|estaría]]', '[[caught|cogió]] / [[would be|estaría]]', '[[has caught|ha cogido]] / [[will be|estará]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would + infinitive|pasado perfecto + would + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[they|ellos]] ____[[the contract|el contrato]] [[last month|el mes pasado]], [[they|ellos]] ____[[abroad|en el extranjero]] [[now|ahora]].', options: ['[[had signed|hubieran firmado]]', '[[would be working|estarían trabajando]]'], correctAnswer: 'had signed', acceptableAnswers: ['had signed'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____[[Spanish|español]] [[at school|en el colegio]], [[I|yo]] ____[[fluently now|con fluidez ahora]].', options: ['[[had learned|hubiera aprendido]] / [[would speak|hablaría]]', '[[learned|aprendí]] / [[would speak|hablaría]]', '[[learn|aprendo]] / [[speak|hablo]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would + infinitive|pasado perfecto + would + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[she|ella]] ____[[the course|el curso]] [[last year|el año pasado]], [[she|ella]] ____[[qualified today|cualificada hoy]].', options: ['[[had completed|hubiera completado]]', '[[would be|sería]]'], correctAnswer: 'had completed', acceptableAnswers: ['had completed'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[we|nosotros]] ____[[the hotel|el hotel]] [[last week|la semana pasada]], [[we|nosotros]] ____[[a room|una habitación]] [[for Saturday|para el sábado]].', options: ['[[had booked|hubiéramos reservado]] / [[would have|tendríamos]]', '[[booked|reservamos]] / [[would have|tendríamos]]', '[[book|reservamos]] / [[will have|tendremos]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present/future|pasado → presente/futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[you|tú]] ____[[me|a mí]] [[earlier|antes]], [[I|yo]] ____[[you|te]] [[help|ayudar]] [[now|ahora]].', options: ['[[had contacted|hubieras contactado a]]', '[[would help|ayudaría a]]'], correctAnswer: 'had contacted', acceptableAnswers: ['had contacted'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[he|él]] ____[[the interview|la entrevista]] [[last Monday|el lunes pasado]], [[he|él]] ____[[next week|la semana que viene]].', options: ['[[had passed|hubiera aprobado]] / [[would start|empezaría]]', '[[passed|aprobó]] / [[would start|empezaría]]', '[[passes|aprueba]] / [[will start|empezará]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → future|pasado → futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____[[you|te]] [[were ill|estuvieras enfermo]], [[I|yo]] ____[[have visited|habría visitado]] [[you|te]] [[yesterday|ayer]].', options: ['[[had known|hubiera sabido que]]', '[[would|habría]]'], correctAnswer: 'had known', acceptableAnswers: ['had known'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past perfect + would have + past participle|pasado perfecto + would have + participio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[they|ellos]] ____[[invested|invertido]] [[in property|en propiedad]] [[five years ago|hace cinco años]], [[they|ellos]] ____[[rich now|ricos ahora]].', options: ['[[had|hubieran]] / [[would be|serían]]', '[[have|han]] / [[will be|serán]]', '[[invest|inviertan]] / [[are|son]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____[[about|sobre]] [[the sale|la venta]] [[earlier|antes]], [[I|yo]] ____[[it|ello]] [[by now|para ahora]].', options: ['[[had known|hubiera sabido]]', '[[would have bought|habría comprado]]'], correctAnswer: 'had known', acceptableAnswers: ['had known'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[she|ella]] ____[[me|a mí]] [[the file|el archivo]] [[yesterday|ayer]], [[I|yo]] ____[[the report|el informe]] [[ready|listo]] [[now|ahora]].', options: ['[[had sent|hubiera enviado a]] / [[would have|habría]]', '[[sent|envió a]] / [[would have|habría]]', '[[sends|envía a]] / [[have|tengo]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[we|nosotros]] ____[[the tickets|las entradas]] [[last month|el mes pasado]], [[we|nosotros]] ____[[the concert|el concierto]] [[tonight|esta noche]].', options: ['[[had bought|hubiéramos comprado]]', '[[would be attending|estaríamos asistiendo a]]'], correctAnswer: 'had bought', acceptableAnswers: ['had bought'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present/future|pasado → presente/futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[he|él]] ____[[piano|piano]] [[as a child|de niño]], [[he|él]] ____[[professionally now|profesionalmente ahora]].', options: ['[[had learned|hubiera aprendido]] / [[would play|tocaría]]', '[[learned|aprendió]] / [[would play|tocaría]]', '[[learns|aprende]] / [[plays|toca]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[she|ella]] ____[[the scholarship|la beca]] [[last year|el año pasado]], [[she|ella]] ____[[at Oxford|en Oxford]] [[now|ahora]].', options: ['[[had won|hubiera ganado]]', '[[would be studying|estudiaría]]'], correctAnswer: 'had won', acceptableAnswers: ['had won'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____[[to your warning|tu advertencia]] [[then|entonces]], [[I|yo]] ____[[in this mess|en este lío]] [[now|ahora]].', options: ['[[had listened|hubiera escuchado]] / [[would not be|no estaría]]', '[[listened|escuché]] / [[would not be|no estaría]]', '[[listen|escucho]] / [[am not|no estoy]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[they|ellos]] ____[[the flat|el piso]] [[three years ago|hace tres años]], [[they|ellos]] ____[[it|ello]] [[by now|para ahora]].', options: ['[[had rented|hubieran alquilado]]', '[[would have renewed|habrían renovado]]'], correctAnswer: 'had rented', acceptableAnswers: ['had rented'], explanation: '[[Mixed conditional|Condicional mixto]]: [[past → present|pasado → presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u8-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Mixed conditionals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[you|tú]] ____[[me|a mí]] [[the data|los datos]] [[last Friday|el viernes pasado]], [[I|yo]] ____[[the analysis|el análisis]] [[ready|listo]] [[for Monday|para el lunes]].', options: ['[[had given|hubieras dado a]] / [[would have|habría]]', '[[gave|diste a]] / [[would have|habría]]', '[[give|das a]] / [[have|tengo]]'], correctAnswer: 0, explanation: '[[Mixed conditional|Condicional mixto]]: [[past → future|pasado → futuro]].' }] }, topicName: 'Grammar' },
];
