/**
 * Unidad 27 B2 — Lección 2: Vocabulario (Cars & Transport)
 * 18 ejercicios (B2: coches, transporte, mantenimiento)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Cars & Transport|Coches y Transporte]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con coches y transporte.';

export const UNIT_27_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u27-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place where you get fuel for your car|Lugar donde repostar combustible]]:', options: ['[[petrol station|gasolinera]]', '[[parking lot|aparcamiento]]', '[[garage|taller]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A long journey by car for pleasure|Viaje largo en coche por placer]]:', options: ['[[road trip|viaje por carretera]]', '[[commute|desplazamiento al trabajo]]', '[[test drive|prueba de conducción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who repairs cars|Persona que repara coches]]:', options: ['[[mechanic|mecánico]]', '[[driver|conductor]]', '[[dealer|concesionario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place where cars are repaired|Lugar donde se reparan coches]]:', options: ['[[garage|taller]]', '[[showroom|sala de exposición]]', '[[car park|aparcamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The annual test for vehicle safety in the UK|Prueba anual de seguridad del vehículo en Reino Unido]]:', options: ['[[MOT test|ITV]]', '[[driving test|examen de conducir]]', '[[insurance check|revisión del seguro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Protection you pay for in case of accidents|Protección que pagas en caso de accidentes]]:', options: ['[[insurance|seguro]]', '[[tax|impuesto]]', '[[MOT|ITV]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a car"|Colocación: "to ____ a car"]]', options: ['[[service|revisar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a booking"|Colocación: "to ____ a booking"]] [[at the garage|en el taller]]', options: ['[[make|hacer]]', '[[do|hacer]]', '[[take|tomar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Many vehicles moving slowly on the road|Muchos vehículos moviéndose lentamente]]:', options: ['[[traffic|tráfico]]', '[[rush hour|hora punta]]', '[[congestion|congestión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A person who teaches you to drive|Persona que te enseña a conducir]]:', options: ['[[driving instructor|profesor de conducir]]', '[[mechanic|mecánico]]', '[[examiner|examinador]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Expression: "to ____ up" (fill the tank)|Expresión: "____" (llenar el depósito)]]', options: ['[[fill|repostar]]', '[[top|llenar]]', '[[run|quedarse sin]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When your car stops working unexpectedly|Cuando tu coche deja de funcionar inesperadamente]]:', options: ['[[breakdown|avería]]', '[[flat tyre|neumático pinchado]]', '[[overheating|recalentamiento]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Regular work to keep the car in good condition|Trabajo regular para mantener el coche en buen estado]]:', options: ['[[car maintenance|mantenimiento del coche]]', '[[repair|reparación]]', '[[inspection|inspección]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a road trip"|Colocación: "to ____ a road trip"]]', options: ['[[plan|planificar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place to leave your car|Lugar para dejar el coche]]:', options: ['[[parking|aparcamiento]]', '[[garage|taller]]', '[[showroom|sala de exposición]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A shop that sells new cars|Tienda que vende coches nuevos]]:', options: ['[[dealership|concesionario]]', '[[garage|taller]]', '[[petrol station|gasolinera]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A short drive to try a car before buying|Conducción corta para probar un coche antes de comprar]]:', options: ['[[test drive|prueba de conducción]]', '[[road trip|viaje por carretera]]', '[[joyride|paseo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u27-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Cars & Transport', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The busiest time for traffic|La hora más concurrida del tráfico]]:', options: ['[[rush hour|hora punta]]', '[[peak time|hora punta]]', '[[traffic jam|atasco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
