/**
 * Unidad 58 B2 — Lección 2: Vocabulario (Review: History & Society)
 * 18 ejercicios (B2: repaso historia y sociedad)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Review: History & Society|Repaso: Historia y sociedad]]';
const INSTRUCTIONS = 'Elige la palabra o expresión correcta relacionada con historia y sociedad.';

export const UNIT_58_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u58-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Formal agreement between nations|Acuerdo formal entre naciones]]:', options: ['[[treaty|tratado]]', '[[war|guerra]]', '[[conflict|conflicto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Overthrow of a government or system|Derrocamiento de un gobierno o sistema]]:', options: ['[[revolution|revolución]]', '[[treaty|tratado]]', '[[unity|unidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[State of being united|Estado de estar unidos]]:', options: ['[[unity|unidad]]', '[[division|división]]', '[[conflict|conflicto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[People living together in a community|Personas viviendo juntas en comunidad]]:', options: ['[[society|sociedad]]', '[[history|historia]]', '[[constitution|constitución]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Fundamental law of a country|Ley fundamental de un país]]:', options: ['[[constitution|constitución]]', '[[treaty|tratado]]', '[[revolution|revolución]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To pay attention to advice|Prestar atención a un consejo]]:', options: ['[[to heed|atender]]', '[[to ignore|ignorar]]', '[[to reveal|revelar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To reach an agreement|Llegar a un acuerdo]]:', options: ['[[to compromise|llegar a un acuerdo]]', '[[to escalate|escalar]]', '[[to protest|protestar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something known|Hacer algo conocido]]:', options: ['[[to reveal|revelar]]', '[[to hide|ocultar]]', '[[to heed|atender]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To express strong disagreement|Expresar fuerte desacuerdo]]:', options: ['[[to protest|protestar]]', '[[to compromise|ceder]]', '[[to heed|atender]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To become more intense|Volverse más intenso]]:', options: ['[[to escalate|escalar]]', '[[to end|terminar]]', '[[to avoid|evitar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Serious event causing great damage|Evento grave que causa gran daño]]:', options: ['[[disaster|desastre]]', '[[unity|unidad]]', '[[treaty|tratado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Separation into different groups|Separación en grupos diferentes]]:', options: ['[[division|división]]', '[[unity|unidad]]', '[[society|sociedad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Person who studies the past|Persona que estudia el pasado]]:', options: ['[[historian|historiador]]', '[[leader|líder]]', '[[society|sociedad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Person in charge of a group|Persona a cargo de un grupo]]:', options: ['[[leader|líder]]', '[[historian|historiador]]', '[[society|sociedad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To prevent something bad|Evitar algo malo]]:', options: ['[[to avoid|evitar]]', '[[to cause|causar]]', '[[to escalate|escalar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Accepting different views|Aceptar diferentes puntos de vista]]:', options: ['[[tolerant|tolerante]]', '[[divided|dividido]]', '[[intense|intenso]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Past events of a people or place|Eventos pasados de un pueblo o lugar]]:', options: ['[[history|historia]]', '[[society|sociedad]]', '[[constitution|constitución]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u58-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Written warning about danger|Advertencia escrita sobre peligro]]:', options: ['[[warning|advertencia]]', '[[treaty|tratado]]', '[[unity|unidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
