/**
 * Unidad 25 B2 — Lección 5: Expresión oral (Repaso 21–24)
 * 18 ejercicios (B2: repaso mixto)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_25_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u25-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[Although the weather was bad|Aunque el tiempo era malo]], [[we|nosotros]] [[went to the beach|fuimos a la playa]].', expectedResponse: 'Although the weather was bad, we went to the beach.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The car broke down|El coche se averió]] [[on the motorway|en la autopista]] [[yesterday|ayer]].', expectedResponse: 'The car broke down on the motorway yesterday.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The match was called off|El partido fue cancelado]] [[because of the rain|debido a la lluvia]].', expectedResponse: 'The match was called off because of the rain.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We left early|Salimos temprano]] [[so that we could|para que pudiéramos]] [[avoid the traffic|evitar el tráfico]].', expectedResponse: 'We left early so that we could avoid the traffic.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She brought up her children|Crió a sus hijos]] [[to speak three languages|a hablar tres idiomas]].', expectedResponse: 'She brought up her children to speak three languages.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I came across an old book|Encontré un libro antiguo por casualidad]] [[while cleaning the attic|mientras limpiaba el ático]].', expectedResponse: 'I came across an old book while cleaning the attic.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Despite the rain|A pesar de la lluvia]], [[the concert was a success|el concierto fue un éxito]].', expectedResponse: 'Despite the rain, the concert was a success.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The negotiations broke down|Las negociaciones fracasaron]] [[after hours of discussion|después de horas de discusión]].', expectedResponse: 'The negotiations broke down after hours of discussion.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[We carried on working|Seguimos trabajando]] [[despite the difficulties|a pesar de las dificultades]].', expectedResponse: 'We carried on working despite the difficulties.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en los phrasal verbs.', targetText: '[[The company brought in an expert|La empresa trajo un experto]] [[to advise on the project|para asesorar sobre el proyecto]].', expectedResponse: 'The company brought in an expert to advise on the project.' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s11', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe una situación en la que algo fue cancelado (call off) pero continuaste (carry on).', prompt: '[[Describe a situation where something was called off but you carried on. Use: call off, carry on, come up with.|Describe una situación en la que algo fue cancelado pero continuaste. Usa: call off, carry on, come up with.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s12', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: explica qué harías si las negociaciones se rompieran (break down).', prompt: '[[Explain what you would do if negotiations broke down. Use: break down, bring up, bring in, bring about.|Explica qué harías si las negociaciones se rompieran. Usa: break down, bring up, bring in, bring about.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s13', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué temas es importante traer a colación (bring up) en una reunión?', prompt: '[[What topics is it important to bring up in a meeting? Give examples. Use: bring up, although, however.|¿Qué temas es importante traer a colación en una reunión? Da ejemplos.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s14', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe un lugar que encontraste por casualidad (come across).', prompt: '[[Describe a place you came across by chance. Use: come across, carry on, despite.|Describe un lugar que encontraste por casualidad. Usa: come across, carry on, despite.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s15', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 2–3 frases con cada una.', prompt: '[[Use these in your own sentences:|Usa estos en tus propias oraciones:]]\n[[- although / despite / however|- although / despite / however]]\n[[- call off / carry on / come across|- call off / carry on / come across]]\n[[- bring up / bring about / bring in|- bring up / bring about / bring in]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s16', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: convence a tu jefe de traer (bring in) un experto para un proyecto.', prompt: '[[Persuade your boss to bring in an expert for a project. Mention why and what it would bring about.|Convence a tu jefe de traer un experto para un proyecto. Menciona por qué y qué causaría.]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s17', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: describe una situación en la que la comunicación se rompió (broke down).', prompt: '[[Describe a situation where communication broke down. Explain what happened and how it could have been avoided.|Describe una situación en la que la comunicación se rompió. Explica qué pasó y cómo podría haberse evitado.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u25-l5-s18', type: 'speaking', level: 'B2', topic: 'Repaso 21–24', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué cambio te gustaría que se produjera (bring about) en tu trabajo o estudios?', prompt: '[[What change would you like to bring about in your work or studies? Use bring about and in order to.|¿Qué cambio te gustaría que se produjera en tu trabajo o estudios? Usa bring about e in order to.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
