/**
 * Unidad 10 B2 — Lección 5: Expresión oral (Repaso 6–9)
 * 18 ejercicios (B2: mixed grammar and vocabulary from units 6-9)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_10_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u10-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[had|hubiera]] [[a bigger studio|un estudio más grande]] [[to practise|para practicar]] [[music|música]].', expectedResponse: 'I wish I had a bigger studio to practise music.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[would rather|preferiría]] [[shop|comprar]] [[at the market|en el mercado]] [[tonight|esta noche]].', expectedResponse: 'I would rather shop at the market tonight.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had attended|hubiera asistido a]] [[the site visit|la visita a la obra]] [[yesterday|ayer]], [[I|yo]] [[would know|conocería]] [[the details now|los detalles ahora]].', expectedResponse: 'If I had attended the site visit yesterday, I would know the details now.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Having completed|Habiendo completado]] [[the report|el informe]], [[she|ella]] [[sent|envió]] [[it|lo]] [[to the manager|al gerente]].', expectedResponse: 'Having completed the report, she sent it to the manager.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[felt|se sintió]] [[exhausted|agotada]] [[after|después de]] [[the long rehearsal|el largo ensayo]].', expectedResponse: 'She felt exhausted after the long rehearsal.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[bandmates|compañeros de banda]] [[get on with|se llevan bien con]] [[each other|entre ellos]] [[at|en]] [[the venue|el lugar]].', expectedResponse: 'My bandmates get on with each other at the venue.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had booked|hubiera reservado]] [[my ticket|mi entrada]] [[earlier|antes]], [[I|yo]] [[would have saved|habría ahorrado]] [[a fortune|una fortuna]].', expectedResponse: 'If I had booked my ticket earlier, I would have saved a fortune.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[deck out|decoramos]] [[the venue|el lugar]] [[by|mediante]] [[reusing|reutilizando]] [[costumes|disfraces]] [[and|y]] [[recycling|reciclando]] [[decorations|decoraciones]].', expectedResponse: 'We deck out the venue by reusing costumes and recycling decorations.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que desees haber hecho diferente en el pasado.', targetText: '[[I|Yo]] ____.', expectedResponse: 'I wish I had [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una preferencia usando would rather o would prefer.', targetText: '____.', expectedResponse: 'I would rather / would prefer to...' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: "[[It's time|Ya es hora]] [[he|él]] [[got|consiguiera]] [[a job|un trabajo]].", expectedResponse: "It's time he got a job." }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The facade|La fachada]] [[damaged|dañada]] [[in the storm|en la tormenta]] [[needed|necesitaba]] [[repairs|reparaciones]].', expectedResponse: 'The facade damaged in the storm needed repairs.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[set off|partí]] [[at dawn|al amanecer]] [[to avoid|para evitar]] [[crowds|multitudes]] [[and|y]] [[my|mi]] [[destination|destino]] [[was|era]] [[the festival|el festival]].', expectedResponse: 'I set off at dawn to avoid crowds and my destination was the festival.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con mixed conditional o third conditional.', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would have/would...' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases música, compras, arquitectura o festivales usando vocabulario de las unidades 6-9.', targetText: '____. ____. ____.', expectedResponse: 'I have... My... We get on... / I travelled to...' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Traditions|Las tradiciones]] [[and|y]] [[parades|desfiles]] [[are|son]] [[treasures|tesoros]] [[for|para]] [[our|nuestra]] [[cultural heritage|patrimonio cultural]].', expectedResponse: 'Traditions and parades are treasures for our cultural heritage.' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con "Having + past participle".', targetText: '____.', expectedResponse: 'Having [past participle]..., I...' }, topicName: 'Speaking' },
  { id: 'b2-u10-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases cómo conectas música, compras, arquitectura y festivales en tu vida.', targetText: '____. ____. ____.', expectedResponse: 'I feel... when... I try to... / My family... / When I travel...' }, topicName: 'Speaking' },
];
