/**
 * Unidad 14 B2 — Lección 5: Expresión oral (Fashion & Style)
 * 18 ejercicios (B2: Fashion & Style)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_14_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u14-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[The designer|El diseñador]] [[must have seen|debe haber visto]] [[our collection|nuestra colección]] [[by now|ya]].', expectedResponse: 'The designer must have seen our collection by now.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She can\'t have missed|No puede haber faltado]] [[the runway show|al desfile]]; [[I saw her|la vi]] [[in the front row|en la primera fila]] [[at 9 am|a las 9]].', expectedResponse: "She can't have missed the runway show; I saw her in the front row at 9 am." }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The trend|La tendencia]] [[might have fallen out of favour|podría haber pasado de moda]]; [[nobody has worn it|nadie la ha llevado]] [[for months|en meses]].', expectedResponse: 'The trend might have fallen out of favour; nobody has worn it for months.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They must have received|Deben haber recibido]] [[the invitation|la invitación]]; [[the courier confirmed|el mensajero confirmó]] [[delivery yesterday|la entrega ayer]].', expectedResponse: 'They must have received the invitation; the courier confirmed delivery yesterday.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He can\'t have forgotten|No puede haber olvidado]] [[the fashion week dates|las fechas de la semana de la moda]]; [[he never misses one|nunca falta a ninguna]].', expectedResponse: "He can't have forgotten the fashion week dates; he never misses one." }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The launch|El lanzamiento]] [[must have been approved|debe haber sido aprobado]] [[by the brand|por la marca]]; [[the press release went out|el comunicado salió]] [[this morning|esta mañana]].', expectedResponse: 'The launch must have been approved by the brand; the press release went out this morning.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The parcel|El paquete]] [[might have gone|podría haber ido]] [[to the wrong address|a la dirección equivocada]]; [[check the delivery details|revisa los detalles de entrega]].', expectedResponse: 'The parcel might have gone to the wrong address; check the delivery details.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They can\'t have reached|No pueden haber llegado]] [[a deal|a un acuerdo]]; [[both sides|ambas partes]] [[are still negotiating|siguen negociando]] [[the contract|el contrato]].', expectedResponse: "They can't have reached a deal; both sides are still negotiating the contract." }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y céntrate en la entonación.', targetText: '[[The model|La modelo]] [[must have impressed|debe haber impresionado]] [[the casting panel|al panel]]; [[she got the campaign|recibió la campaña]] [[the same day|el mismo día]].', expectedResponse: 'The model must have impressed the casting panel; she got the campaign the same day.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta y usa énfasis en las palabras clave.', targetText: '[[The order|El pedido]] [[must have been shipped|debe haber sido enviado]]; [[the tracking|el seguimiento]] [[shows it as delivered|lo muestra como entregado]].', expectedResponse: 'The order must have been shipped; the tracking shows it as delivered.' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s11', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: describe una situación de moda usando must have, might have o can\'t have.', prompt: '[[Describe a fashion situation where you had to deduce what happened. Use must have, might have and can\'t have to explain:|Describe una situación de moda en la que tuviste que deducir qué pasó. Usa must have, might have y can\'t have para explicar:]]\n[[- what you think definitely happened|- qué crees que definitivamente pasó]]\n[[- what might have happened|- qué podría haber pasado]]\n[[- what can\'t have happened|- qué no puede haber pasado]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s12', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1–2 minutos: da tu opinión sobre por qué una marca tuvo éxito o fracasó.', prompt: '[[Give your opinion on why a fashion brand (real or imagined) succeeded or failed. Use modal deductions (must have, might have, can\'t have).|Da tu opinión sobre por qué una marca de moda (real o imaginada) tuvo éxito o fracasó. Usa deducciones modales (must have, might have, can\'t have).]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s13', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué debe haber pasado para que un desfile salga mal?', prompt: '[[What must have (or might have) happened for a fashion show to go wrong? Give examples and use modal deductions.|¿Qué debe haber (o podría haber) pasado para que un desfile salga mal? Da ejemplos y usa deducciones modales.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s14', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: explica qué puede haber pasado cuando un cliente no respondió a tu correo sobre un pedido.', prompt: '[[Imagine a client didn\'t reply to your email about an order. What might have happened? What can\'t have happened? Use modal deductions.|Imagina que un cliente no respondió a tu correo sobre un pedido. ¿Qué podría haber pasado? ¿Qué no puede haber pasado? Usa deducciones modales.]]', targetLevel: 'B2', writingType: 'story' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s15', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Practica expresiones. Di en voz alta 3–4 frases con cada una.', prompt: '[[Use these fashion expressions in your own sentences:|Usa estas expresiones de moda en tus propias oraciones:]]\n[[- set a trend|- marcar una tendencia]]\n[[- pull off a look|- lucir un look]]\n[[- dress to the nines|- vestir de punta en blanco]]\n[[- launch a collection|- lanzar una colección]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s16', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: convence a un inversor de apoyar tu marca de moda.', prompt: '[[Persuade an investor to support your fashion brand. Mention:|Convence a un inversor de apoyar tu marca de moda. Menciona:]]\n[[- why it must succeed|- por qué debe tener éxito]]\n[[- what might happen if they invest|- qué podría pasar si invierten]]\n[[- what can\'t go wrong|- qué no puede salir mal]]', targetLevel: 'B2', writingType: 'article' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s17', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla durante 1 minuto: deduce qué pasó en un casting que salió bien.', prompt: '[[You had a casting that went well. Deduce what must have happened, what might have helped, and what can\'t have gone wrong. Use modal deductions.|Tuviste un casting que salió bien. Deduce qué debe haber pasado, qué podría haber ayudado y qué no puede haber salido mal. Usa deducciones modales.]]', targetLevel: 'B2', writingType: 'description' }, topicName: 'Speaking' },
  { id: 'b2-u14-l5-s18', type: 'speaking', level: 'B2', topic: 'Fashion & Style', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Responde en voz alta: ¿qué debe haber hecho una marca para tener tanto éxito?', prompt: '[[Think of a successful fashion brand. What must they have done right? What might they have avoided? Use modal deductions.|Piensa en una marca de moda exitosa. ¿Qué deben haber hecho bien? ¿Qué podrían haber evitado? Usa deducciones modales.]]', targetLevel: 'B2', writingType: 'essay' }, topicName: 'Speaking' },
];
