/**
 * Unidad 2 B2 — Lección 6: Expresión escrita (Work)
 * 18 ejercicios (B2: más vocabulario y complejidad que B1)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_2_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u2-l6-w1', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2-3 frases sobre tus planes profesionales para los próximos años.', expressionHint: 'Puedes usar: [[will|will (futuro)]], [[going to|ir a]], [[future perfect|futuro perfecto]], [[apply for|solicitar]], [[get promoted|ascender]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I|Yo]] ____[[the report|el informe]] [[by|para]] [[Friday|viernes]].', options: ['[[will have finished|habré terminado]]', '[[will finish|terminaré]]'], correctAnswer: 'will have finished', acceptableAnswers: ['will have finished'], explanation: '[[Future perfect|Future perfect]] [[with by + time|con by + tiempo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w3', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre qué habrás logrado en tu carrera para dentro de diez años.', expressionHint: 'Usa: [[By|Para]]..., [[I will have|habré]]..., [[future perfect|futuro perfecto]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w4', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "going to" para un plan y otra con "will" para una predicción.', expressionHint: '[[I am going to|Voy a]]... / [[I think|Creo que]]... [[will|haré]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She|Ella]] ____[[a meeting|una reunión]] [[at 3 pm|a las 15:00]].', options: ['[[is going to have|va a tener]]', '[[will have|tendrá]]'], correctAnswer: 'is going to have', acceptableAnswers: ['is going to have'], explanation: '[[Going to|Going to]] [[for planned arrangements|para planes organizados]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w6', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre las ventajas de trabajar a distancia.', expressionHint: 'Puedes usar: [[remote work|trabajo remoto]], [[flexibility|flexibilidad]], [[productivity|productividad]], [[apply for|solicitar]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w7', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "This time next week/month I will be..."', expressionHint: '[[Future continuous|Futuro continuo]] para acciones en progreso en un momento futuro.', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con will o going to.', questions: [{ question: '[[I|Yo]] ____[[the manager|al gerente]] [[tomorrow|mañana]].', options: ['[[am speaking to|estoy hablando con]]', '[[will speak to|hablaré con]]'], correctAnswer: 'am speaking to', acceptableAnswers: ['am speaking to'], explanation: '[[Present continuous|Present continuous]] [[for fixed arrangements|para planes fijos]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w9', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre cómo prepararte para una entrevista de trabajo.', expressionHint: 'Puedes usar: [[apply for|solicitar]], [[qualifications|cualificaciones]], [[performance review|evaluación de desempeño]], [[deadline|fecha límite]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w10', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases usando "By the time..." con future perfect.', expressionHint: '[[By the time|Para cuando]] [[I|yo]]..., [[I will have|habré]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[By next year|Para el año que viene]] [[they|ellos]] ____[[ten years|diez años]] [[at the company|en la empresa]].', options: ['[[will have worked|habrán trabajado]]', '[[will work|trabajarán]]'], correctAnswer: 'will have worked', acceptableAnswers: ['will have worked'], explanation: '[[Future perfect|Future perfect]] [[with by + future time|con by + tiempo futuro]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w12', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre la importancia de la formación continua en el trabajo.', expressionHint: 'Puedes usar: [[training course|curso de formación]], [[get promoted|ascender]], [[qualifications|cualificaciones]], [[advance|avanzar]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w13', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con "I promise I will..."', expressionHint: '[[Will|will]] para promesas.', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con will o going to.', questions: [{ question: '[[Look at those clouds|Mira esas nubes]]. [[It|]] ____[[rain|llover]].', options: ['[[is going to|va a]]', '[[will|will]]'], correctAnswer: 'is going to', acceptableAnswers: ['is going to'], explanation: '[[Going to|Going to]] [[for predictions based on evidence|para predicciones basadas en evidencia]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w15', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto sobre tus metas profesionales y cómo las alcanzarás.', expressionHint: 'Puedes usar: [[set goals|establecer metas]], [[achieve|lograr]], [[get promoted|ascender]], [[performance review|evaluación de desempeño]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w16', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con future continuous y otra con future perfect.', expressionHint: '[[At 9 pm tomorrow|Mañana a las 21:00]] [[I will be|estaré]]... / [[By 2030|Para 2030]] [[I will have|habré]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The train|El tren]] ____[[at 5 pm|a las 17:00]].', options: ['[[leaves|sale]]', '[[will leave|saldrá]]'], correctAnswer: 'leaves', acceptableAnswers: ['leaves'], explanation: '[[Present simple|Present simple]] [[for timetables|para horarios]].' }] }, topicName: 'Writing' },
  { id: 'b2-u2-l6-w18', type: 'writing', level: 'B2', topic: 'Work', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre cómo te imaginas tu trabajo ideal en el futuro.', expressionHint: 'Puedes usar: [[remote work|trabajo remoto]], [[flexible hours|horario flexible]], [[get promoted|ascender]], [[negotiate|negociar]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
