/**
 * Unidad 8 B2 — Lección 2: Vocabulario (Travel)
 * 18 ejercicios (B2: booking, luggage, destination, etc.)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Travel|Viajes]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_8_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u8-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To reserve a place|Reservar un lugar]]:', options: ['[[booking|reserva]]', '[[ticket|billete]]', '[[check-in|facturación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Bags you take on a trip|Bolsas que llevas en un viaje]]:', options: ['[[luggage|equipaje]]', '[[passport|pasaporte]]', '[[visa|visado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The place you are going to|El lugar al que vas]]:', options: ['[[destination|destino]]', '[[departure|salida]]', '[[arrival|llegada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To cancel a trip|Cancelar un viaje]]:', options: ['[[call off|cancelar]]', '[[set off|partir]]', '[[check in|facturar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To begin a journey|Empezar un viaje]]:', options: ['[[set off|partir]]', '[[check in|facturar]]', '[[touch down|aterrizar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To register at airport or hotel|Registrarse en aeropuerto o hotel]]:', options: ['[[check in|facturar]]', '[[check out|hacer checkout]]', '[[take off|despegar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To leave a hotel|Salir de un hotel]]:', options: ['[[check out|hacer checkout]]', '[[check in|facturar]]', '[[book in|reservar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When a plane leaves the ground|Cuando un avión deja el suelo]]:', options: ['[[take off|despegar]]', '[[touch down|aterrizar]]', '[[set off|partir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When a plane lands|Cuando un avión aterriza]]:', options: ['[[touch down|aterrizar]]', '[[take off|despegar]]', '[[set off|partir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A delay before departure|Un retraso antes de la salida]]:', options: ['[[layover|escala]]', '[[delay|retraso]]', '[[cancellation|cancelación]]'], correctAnswer: 1 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A stop between flights|Una parada entre vuelos]]:', options: ['[[layover|escala]]', '[[departure|salida]]', '[[arrival|llegada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Document to enter a country|Documento para entrar a un país]]:', options: ['[[visa|visado]]', '[[passport|pasaporte]]', '[[boarding pass|tarjeta de embarque]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Travel document that proves identity|Documento de viaje que prueba identidad]]:', options: ['[[passport|pasaporte]]', '[[visa|visado]]', '[[ticket|billete]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Small bag carried on plane|Bolsa pequeña que llevas en el avión]]:', options: ['[[hand luggage|equipaje de mano]]', '[[checked baggage|equipaje facturado]]', '[[suitcase|maleta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Luggage stored in plane hold|Equipaje guardado en la bodega del avión]]:', options: ['[[checked baggage|equipaje facturado]]', '[[hand luggage|equipaje de mano]]', '[[carry-on|equipaje de mano]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place to stay when travelling|Un lugar para quedarse cuando viajas]]:', options: ['[[accommodation|alojamiento]]', '[[destination|destino]]', '[[itinerary|itinerario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Plan of a journey|Plan de un viaje]]:', options: ['[[itinerary|itinerario]]', '[[booking|reserva]]', '[[ticket|billete]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u8-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To travel and stay somewhere for pleasure|Viajar y quedarse en algún lugar por placer]]:', options: ['[[go on holiday|ir de vacaciones]]', '[[commute|desplazarse]]', '[[relocate|reubicarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
