/**
 * Unidad 13 B2 — Lección 4: Comprensión auditiva (Volunteering & Charity)
 * 13 preguntas (B2: Volunteering & Charity)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hello|Hola]], [[I'm Sarah|soy Sarah]], [[and I work|y trabajo]] [[as a volunteer coordinator|como coordinadora de voluntarios]] [[for a charity|para una organización]] [[that helps homeless people|que ayuda a personas sin hogar]] [[in our city|en nuestra ciudad]]. [[One question|Una pregunta]] [[I hear constantly|que escucho constantemente]] [[is|es]]: [["Do I really have to attend the training?"|"¿De verdad tengo que asistir a la formación?"]] [[And the answer|Y la respuesta]] [[depends|depende]] [[on the role|del rol]], [[but|pero]] [[in most cases|en la mayoría de los casos]] [[you must|debes]] [[complete it before your first shift|completarla antes de tu primer turno]] [[or we can't assign you|o no podemos asignarte]]. [[The good news|La buena noticia]] [[is|es]] [[that you needn't|que no necesitas]] [[do it in person|hacerlo en persona]]; [[there are|hay]] [[online modules|módulos online]] [[and|y]] [[short videos|vídeos cortos]] [[that can help|que pueden ayudar]]. [[If you're fundraising|Si estás recaudando fondos]], [[you have to|tienes que]] [[keep records|mantener registros]] [[of all donations|de todas las donaciones]]. [[You need to|Necesitas]] [[set aside|reservar]] [[time for follow-ups|tiempo para seguimientos]] [[throughout the campaign|durante toda la campaña]], [[not just|no solo]] [[when it ends|cuando termina]]. [[Many volunteers|Muchos voluntarios]] [[who thought they couldn't spare the time|que pensaban que no podían dedicar el tiempo]] [[found|encontraron]] [[that they didn't have to give much|que no tenían que dar mucho]]; [[a few hours|unas pocas horas]] [[a month|al mes]] [[can make|pueden hacer]] [[a real difference|una diferencia real]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Sarah, a volunteer coordinator for a homeless charity|Sarah, coordinadora de voluntarios para una organización de personas sin hogar]]', '[[A bank manager|Un director de banco]]', '[[A university professor|Un profesor universitario]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Sarah, and I work as a volunteer coordinator for a charity that helps homeless people|soy Sarah y trabajo como coordinadora de voluntarios para una organización que ayuda a personas sin hogar]]".' },
  { question: '[[What|Cuál]] [[is a common question|es una pregunta común]] [[she hears|que escucha]]?', options: ['[["Do I really have to attend the training?"|"¿De verdad tengo que asistir a la formación?"]]', '[["How do I donate?"|"¿Cómo dono?"]]', '[["What is a shelter?"|"¿Qué es un refugio?"]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[One question I hear constantly is: Do I really have to attend the training?|Una pregunta que escucho constantemente es: ¿De verdad tengo que asistir a la formación?]]".' },
  { question: '[[What|Qué]] [[must most volunteers do|deben hacer la mayoría]] [[regarding training|respecto a la formación]]?', options: ['[[Complete it before their first shift or they can\'t be assigned|Completarla antes de su primer turno o no pueden ser asignados]]', '[[Ignore it completely|Ignorarla completamente]]', '[[Only do it if they have time|Solo hacerla si tienen tiempo]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[in most cases you must complete it before your first shift or we can\'t assign you|en la mayoría de los casos debes completarla antes de tu primer turno o no podemos asignarte]]".' },
  { question: '[[What|Qué]] [[does Sarah say|dice Sarah]] [[about doing it in person|sobre hacerlo en persona]]?', options: ['[[You needn\'t do it in person; there are online modules and short videos|No necesitas hacerlo en persona; hay módulos online y vídeos cortos]]', '[[You must always do it in person|Debes hacerlo siempre en persona]]', '[[Online training is useless|La formación online es inútil]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[you needn\'t do it in person; there are online modules and short videos|no necesitas hacerlo en persona; hay módulos online y vídeos cortos]]".' },
  { question: '[[What|Qué]] [[do fundraisers have to do|tienen que hacer los recaudadores]]?', options: ['[[Keep records of all donations|Mantener registros de todas las donaciones]]', '[[Close the campaign|Cerrar la campaña]]', '[[Never ask for money|Nunca pedir dinero]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[If you\'re fundraising, you have to keep records of all donations|Si estás recaudando fondos, tienes que mantener registros de todas las donaciones]]".' },
  { question: '[[What|Qué]] [[do you need to do|necesitas hacer]] [[throughout the campaign|durante toda la campaña]]?', options: ['[[Set aside time for follow-ups|Reservar tiempo para seguimientos]]', '[[Spend everything|Gastar todo]]', '[[Ignore donors until it ends|Ignorar a los donantes hasta que termine]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[You need to set aside time for follow-ups throughout the campaign|Necesitas reservar tiempo para seguimientos durante toda la campaña]]".' },
  { question: '[[What|Qué]] [[did many volunteers discover|descubrieron muchos voluntarios]] [[about time|sobre el tiempo]]?', options: ['[[They didn\'t have to give much; a few hours a month can make a real difference|No tenían que dar mucho; unas pocas horas al mes pueden hacer una diferencia real]]', '[[Volunteering is useless|El voluntariado es inútil]]', '[[They must give full-time|Deben dar tiempo completo]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[they didn\'t have to give much; a few hours a month can make a real difference|no tenían que dar mucho; unas pocas horas al mes pueden hacer una diferencia real]]".' },
  { question: '[[The audio suggests|El audio sugiere]] [[that|que]] [[you must always attend training in person|debes asistir siempre a la formación en persona]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker mentions|El hablante menciona]] [[online modules and short videos|módulos online y vídeos cortos]].' },
  { question: '[[According to Sarah|Según Sarah]], [[fundraisers needn\'t keep records|los recaudadores no necesitan mantener registros]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[you have to keep records|tienes que mantener registros]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the listening|de la escucha]]?', options: ['[[You must complete training but needn\'t do it in person; plan and commit a few hours|Debes completar la formación pero no necesitas hacerla en persona; planifica y comprométete unas horas]]', '[[Volunteering is optional|El voluntariado es opcional]]', '[[Never give your time|Nunca des tu tiempo]]'], correctAnswer: 0, explanation: '[[The speaker|El hablante]] [[combines|combina]] [[obligation|obligación]], [[no necessity for in-person|no necesidad de presencial]] [[and|y]] [[flexibility|flexibilidad]].' },
  { question: '[[Which modal|Qué modal]] [[expresses absence of necessity|expresa ausencia de necesidad]] [[in the transcript|en la transcripción]]?', options: ['[[needn\'t (You needn\'t do it in person)|needn\'t (No necesitas hacerlo en persona)]]', '[[must (you must complete)|must (debes completar)]]', '[[have to (you have to keep)|have to (tienes que mantener)]]'], correctAnswer: 0, explanation: '[[Needn\'t|Needn\'t]] [[indicates no necessity|indica que no es necesario]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[volunteer|voluntario]], [[training|formación]], [[donations|donaciones]], [[fundraising|recaudación]]', '[[festival|festival]], [[culture|cultura]], [[tradition|tradición]]', '[[series|serie]], [[streaming|streaming]], [[cast|reparto]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[volunteering vocabulary|vocabulario de voluntariado]].' },
  { question: '[[What|Qué]] [[does "set aside" mean|significa "set aside"]] [[in this context|en este contexto]]?', options: ['[[Reserve or allocate for later use|Reservar o asignar para uso posterior]]', '[[Spend immediately|Gastar inmediatamente]]', '[[Ignore completely|Ignorar completamente]]'], correctAnswer: 0, explanation: '[[Set aside|Set aside]] [[means reserve time|significa reservar tiempo]] [[for follow-ups|para seguimientos]].' },
];

export const UNIT_13_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u13-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Volunteering & Charity',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
