/**
 * Unidad 20 B2 — Lección 4: Comprensión auditiva (Repaso: History, Adventure, Cooking, Literature)
 * 13 preguntas (B2: recreado con transcripción y preguntas distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Listening|Comprensión auditiva]]';
const LISTENING_TRANSCRIPT = `[[Hi|Hola]], [[I\'m Dr. Sarah Chen|soy la Dra. Sarah Chen]], [[a historian|historiadora]] [[who has been studying|que ha estado estudiando]] [[how heritage|cómo el patrimonio]] [[is being used|está siendo usado]] [[in adventure tourism|en el turismo de aventura]] [[for over a decade|desde hace más de una década]]. [[The data|Los datos]] [[that|que]] [[were collected|fueron recogidos]] [[last year|el año pasado]] [[have been analysed|han sido analizados]] [[and|y]] [[the results|los resultados]] [[will be published|serán publicados]] [[next month|el próximo mes]]. [[The new equipment|El nuevo equipo]] [[had to be|tuvo que ser]] [[calibrated|calibrado]] [[before|antes de]] [[the expedition|la expedición]] [[could be conducted|pudiera ser realizada]]. [[Some of the samples|Algunas de las muestras]] [[were|eran]] [[too contaminated|demasiado contaminadas]] [[to use|para usar]]; [[others|otras]] [[were|eran]] [[clean enough|suficientemente limpias]] [[to proceed|para proceder]]. [[The more|Cuanto más]] [[we learn|aprendemos]] [[about the past|sobre el pasado]], [[the more|más]] [[we realise|nos damos cuenta]] [[how much|cuánto]] [[we don\'t know|no sabemos]]. [[This|Esto]] [[is|es]] [[by far|con diferencia]] [[the most challenging|lo más desafiante]] [[part|parte]] [[of our work|de nuestro trabajo]].`;

const INSTRUCTIONS = 'Escucha el audio (o lee la transcripción). Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[Who is speaking|Quién habla]]?', options: ['[[Dr. Sarah Chen, a historian who has studied how heritage is used in adventure tourism for over a decade|Dra. Sarah Chen, historiadora que ha estudiado cómo se usa el patrimonio en turismo de aventura más de una década]]', '[[A sports coach|Un entrenador deportivo]]', '[[A chef|Un chef]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[I\'m Dr. Sarah Chen, a historian who has been studying how heritage is being used in adventure tourism for over a decade|soy la Dra. Sarah Chen, historiadora que ha estado estudiando cómo el patrimonio está siendo usado en el turismo de aventura desde hace más de una década]]".' },
  { question: '[[What|Qué]] [[has happened to the data collected last year|ha pasado con los datos recogidos el año pasado]]?', options: ['[[They have been analysed and results will be published next month|Han sido analizados y los resultados serán publicados el próximo mes]]', '[[They were lost|Se perdieron]]', '[[They are being collected now|Se están recogiendo ahora]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[the data that were collected last year have been analysed and the results will be published next month|los datos que fueron recogidos el año pasado han sido analizados y los resultados serán publicados el próximo mes]]".' },
  { question: '[[What|Qué]] [[had to be done to the new equipment|tuvo que hacerse con el nuevo equipo]]?', options: ['[[It had to be calibrated before the expedition could be conducted|Tuvo que ser calibrado antes de que la expedición pudiera realizarse]]', '[[It was replaced|Fue reemplazado]]', '[[It was thrown away|Fue tirado]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[The new equipment had to be calibrated before the expedition could be conducted|El nuevo equipo tuvo que ser calibrado antes de que la expedición pudiera ser realizada]]".' },
  { question: '[[What|Qué]] [[were some samples like|cómo eran algunas muestras]]?', options: ['[[Too contaminated to use|Demasiado contaminadas para usar]]', '[[Clean enough for everything|Suficientemente limpias para todo]]', '[[Perfect|Perfectas]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[Some of the samples were too contaminated to use|Algunas de las muestras eran demasiado contaminadas para usar]]".' },
  { question: '[[What|Qué]] [[were other samples like|cómo eran otras muestras]]?', options: ['[[Clean enough to proceed|Suficientemente limpias para proceder]]', '[[Too dirty|Demasiado sucias]]', '[[Useless|Inútiles]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[others were clean enough to proceed|otras eran suficientemente limpias para proceder]]".' },
  { question: '[[What|Qué]] [[does the speaker say about learning|dice el hablante sobre aprender]]?', options: ['[[The more we learn about the past, the more we realise how much we don\'t know|Cuanto más aprendemos sobre el pasado, más nos damos cuenta de cuánto no sabemos]]', '[[We know everything|Lo sabemos todo]]', '[[Learning is easy|Aprender es fácil]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[The more we learn about the past, the more we realise how much we don\'t know|Cuanto más aprendemos sobre el pasado, más nos damos cuenta de cuánto no sabemos]]".' },
  { question: '[[What|Qué]] [[is by far the most challenging part of their work|es con diferencia la parte más desafiante de su trabajo]]?', options: ['[[Realising how much we don\'t know|Darse cuenta de cuánto no sabemos]]', '[[Calibrating equipment|Calibrar equipo]]', '[[Collecting samples|Recoger muestras]]'], correctAnswer: 0, explanation: '[[The speaker says|El hablante dice]] "[[This is by far the most challenging part of our work|Esto es con diferencia la parte más desafiante de nuestro trabajo]]" [[referring to|refiriéndose a]] "[[how much we don\'t know|cuánto no sabemos]]".' },
  { question: '[[The speaker|El hablante]] [[says|dice]] [[that|que]] [[all samples were clean enough to use|todas las muestras eran suficientemente limpias para usar]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[Some of the samples were too contaminated to use|Algunas de las muestras eran demasiado contaminadas para usar]]".' },
  { question: '[[According to the speaker|Según el hablante]], [[the results have already been published|los resultados ya han sido publicados]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The speaker says|El hablante dice]] "[[the results will be published next month|los resultados serán publicados el próximo mes]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the listening|de la escucha]]?', options: ['[[Research involves passive structures, too/enough, and the more... the more; challenges remain|La investigación implica pasiva, too/enough y the more... the more; quedan retos]]', '[[Heritage is useless|El patrimonio es inútil]]', '[[All expeditions succeed|Todas las expediciones tienen éxito]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[covers|abarca]] [[passive|pasiva]], [[too/enough|too/enough]] [[and|y]] [[the more... the more|the more... the more]].' },
  { question: '[[Which structure|Qué estructura]] [[uses passive voice|usa voz pasiva]] [[in the transcript|en la transcripción]]?', options: ['[[The data were collected / have been analysed / will be published|Los datos fueron recogidos / han sido analizados / serán publicados]]', '[[We learn|Aprendemos]]', '[[Samples were contaminated|Las muestras estaban contaminadas]]'], correctAnswer: 0, explanation: '[[Multiple passive forms|Múltiples formas pasivas]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is central|es central]] [[in this listening|en esta escucha]]?', options: ['[[data|datos]], [[samples|muestras]], [[expedition|expedición]], [[calibrated|calibrado]], [[contaminated|contaminado]]', '[[profit|beneficio]], [[debt|deuda]], [[budget|presupuesto]]', '[[museum|museo]], [[theatre|teatro]], [[concert|concierto]]'], correctAnswer: 0, explanation: '[[The listening|La escucha]] [[focuses on|se centra en]] [[history and adventure vocabulary|vocabulario de historia y aventura]].' },
  { question: '[[What|Qué]] [[does "calibrated" mean|significa "calibrated"]] [[in this context|en este contexto]]?', options: ['[[Adjusted or set to work correctly|Ajustado o configurado para funcionar correctamente]]', '[[Broken|Roto]]', '[[Replaced|Reemplazado]]'], correctAnswer: 0, explanation: '[[Calibrate|Calibrar]] [[means to adjust equipment|significa ajustar equipo]] [[for accuracy|para precisión]].' },
];

export const UNIT_20_LESSON_4_LISTENING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u20-l4-l${i + 1}`,
  type: 'listening',
  level: 'B2',
  topic: 'Repaso 16–19',
  difficulty: 'medium',
  transcript: LISTENING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Listening',
}));
