/**
 * Unidad 8 B2 — Lección 5: Expresión oral (Architecture & Design)
 * 18 ejercicios (B2: Mixed conditionals, architecture vocabulary)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_8_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u8-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had|hubiera]] [[booked|reservado]] [[earlier|antes]], [[I|yo]] [[would have saved|habría ahorrado]] [[a lot of money|mucho dinero]] [[on the project|en el proyecto]].', expectedResponse: 'If I had booked earlier, I would have saved a lot of money on the project.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[she|ella]] [[had caught|hubiera cogido]] [[the train|el tren]] [[yesterday|ayer]], [[she|ella]] [[would be|estaría]] [[here now|aquí ahora]] [[inspecting|inspeccionando]] [[the facade|la fachada]].', expectedResponse: 'If she had caught the train yesterday, she would be here now inspecting the facade.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[had to|tuve que]] [[check in|registrarme]] [[online|en línea]] [[because|porque]] [[the|el]] [[construction site|obra]] [[was|estaba]] [[very busy|muy ocupada]].', expectedResponse: 'I had to check in online because the construction site was very busy.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[destination|destino]] [[is|es]] [[Tokyo|Tokio]] [[and|y]] [[I|yo]] [[have|tengo]] [[a|una]] [[six-hour|seis horas]] [[layover|pausa]] [[in|en]] [[Dubai|Dubái]] [[to review|para revisar]] [[blueprints|planos]].', expectedResponse: 'My destination is Tokyo and I have a six-hour layover in Dubai to review blueprints.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had known|hubiera sabido]] [[about|sobre]] [[the delay|el retraso]] [[before|antes]], [[I|yo]] [[would have packed|habría empacado]] [[more|más]] [[blueprints|planos]] [[in my portfolio|en mi portafolio]].', expectedResponse: 'If I had known about the delay before, I would have packed more blueprints in my portfolio.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[set off|partí]] [[early|temprano]] [[this morning|esta mañana]] [[to avoid|para evitar]] [[traffic|tráfico]] [[before|antes de]] [[the site visit|la visita a la obra]].', expectedResponse: 'I set off early this morning to avoid traffic before the site visit.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[we|nosotros]] [[had left|hubiéramos salido]] [[earlier|antes]], [[we|nosotros]] [[would not have missed|no habríamos perdido]] [[the groundbreaking|la inauguración de obras]].', expectedResponse: 'If we had left earlier, we would not have missed the groundbreaking.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[planning permission|permiso de obras]] [[arrived|llegó]] [[just in time|justo a tiempo]] [[and|y]] [[my|mi]] [[blueprint|plano]] [[is|está]] [[valid|válido]] [[for|para]] [[another|otros]] [[five years|cinco años]].', expectedResponse: 'My planning permission arrived just in time and my blueprint is valid for another five years.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con mixed conditional sobre un proyecto de arquitectura (If I had..., I would...).', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would [infinitive]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que habrías hecho diferente en una visita a obra pasada.', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would have [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[had to|tuvimos que]] [[call off|cancelar]] [[our|nuestra]] [[site visit|visita a la obra]] [[because|porque]] [[of|de]] [[the storm|la tormenta]].', expectedResponse: 'We had to call off our site visit because of the storm.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The|El]] [[landmark|monumento]] [[was|fue]] [[completed|completado]] [[on time|a tiempo]] [[and|y]] [[the|la]] [[facade|fachada]] [[looks|se ve]] [[stunning|impresionante]] [[at|en]] [[our|nuestro]] [[destination|destino]].', expectedResponse: 'The landmark was completed on time and the facade looks stunning at our destination.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[they|ellos]] [[had accepted|hubieran aceptado]] [[the offer|la oferta]] [[last year|el año pasado]], [[they|ellos]] [[would be living|estarían viviendo]] [[abroad now|en el extranjero ahora]] [[designing|diseñando]] [[landmarks|monumentos]].', expectedResponse: 'If they had accepted the offer last year, they would be living abroad now designing landmarks.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: describe tu última visita a obra usando vocabulario de la unidad.', targetText: '____. ____. ____.', expectedResponse: 'I set off... My destination was... I had to check in...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases qué habrías hecho diferente en una visita de proyecto.', targetText: '____. ____. ____.', expectedResponse: 'If I had... I would have...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[packed|empacé]] [[light|ligero]] [[and|y]] [[only|solo]] [[took|llevé]] [[my|mi]] [[portfolio|portafolio]] [[to avoid|para evitar]] [[waiting|esperar]] [[at|en]] [[baggage claim|recogida de equipaje]].', expectedResponse: 'I packed light and only took my portfolio to avoid waiting at baggage claim.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con third conditional sobre un proyecto.', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would have [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Architecture & Design', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases consejos para visitas a obra (booking, check-in, portfolio).', targetText: '____. ____. ____.', expectedResponse: 'Book early... Check in online... Pack light...' }, topicName: 'Speaking' },
];
