/**
 * Unidad 28 B2 — Lección 2: Vocabulario (Weather & Climate)
 * 18 ejercicios (B2: tiempo, clima, pronósticos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Weather & Climate|Tiempo y Clima]]';
const INSTRUCTIONS = 'Elige la palabra o colocación correcta relacionada con tiempo y clima.';

export const UNIT_28_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u28-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A prediction of future weather|Predicción del tiempo futuro]]:', options: ['[[forecast|pronóstico]]', '[[temperature|temperatura]]', '[[humidity|humedad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a break"|Colocación: "to ____ a break"]] [[from the heat|del calor]]', options: ['[[take|tomar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a decision"|Colocación: "to ____ a decision"]] [[about the picnic|sobre el picnic]]', options: ['[[make|tomar]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a photo"|Colocación: "to ____ a photo"]] [[of the storm|de la tormenta]]', options: ['[[take|hacer]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ responsibility"|Colocación: "to ____ responsibility"]] [[for the climate report|del informe climático]]', options: ['[[take|asumir]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A violent weather event with wind and rain|Evento meteorológico violento con viento y lluvia]]:', options: ['[[storm|tormenta]]', '[[drizzle|llovizna]]', '[[breeze|brisa]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ progress"|Colocación: "to ____ progress"]] [[on climate action|en acción climática]]', options: ['[[make|hacer]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a mistake"|Colocación: "to ____ a mistake"]] [[in the forecast|en el pronóstico]]', options: ['[[make|cometer]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A long period without rain|Período largo sin lluvia]]:', options: ['[[drought|sequía]]', '[[flood|inundación]]', '[[hurricane|huracán]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ an effort"|Colocación: "to ____ an effort"]] [[to check the forecast|para consultar el pronóstico]]', options: ['[[make|hacer]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a chance"|Colocación: "to ____ a chance"]] [[with the weather|con el tiempo]]', options: ['[[take|aprovechar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Global warming and its effects|Calentamiento global y sus efectos]]:', options: ['[[climate change|cambio climático]]', '[[season|estación]]', '[[forecast|pronóstico]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a look"|Colocación: "to ____ a look"]] [[at the forecast|al pronóstico]]', options: ['[[have|echar]]', '[[take|tomar]]', '[[make|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a call"|Colocación: "to ____ a call"]] [[to discuss the weather|para comentar el tiempo]]', options: ['[[make|hacer]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Spring, summer, autumn, winter|Primavera, verano, otoño, invierno]]:', options: ['[[seasons|estaciones]]', '[[forecast|pronóstico]]', '[[temperature|temperatura]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a note"|Colocación: "to ____ a note"]] [[of the temperature|de la temperatura]]', options: ['[[take|tomar]]', '[[make|hacer]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a promise"|Colocación: "to ____ a promise"]] [[to reduce emissions|de reducir emisiones]]', options: ['[[make|hacer]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u28-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Weather & Climate', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Collocation: "to ____ a good impression"|Colocación: "to ____ a good impression"]] [[at the climate conference|en la conferencia climática]]', options: ['[[make|causar]]', '[[take|tomar]]', '[[do|hacer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
