/**
 * Unidad 16 B2 — Lección 1: Gramática (Passive: all tenses) & History & Heritage
 * 18 ejercicios (B2: recreado con casos distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Passive (all tenses)|Pasiva (todos los tiempos)]]';
const INSTRUCTIONS = 'Elige la forma pasiva correcta según el tiempo verbal indicado.';

export const UNIT_16_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u16-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Ancient monuments|Monumentos antiguos]] ____ [[every year|cada año]] [[by thousands of tourists|por miles de turistas]].', options: ['[[are visited|son visitados]]', '[[is visited|es visitado]]', '[[visit|visitar]]'], correctAnswer: 'are visited', acceptableAnswers: ['are visited'], explanation: '[[Present simple passive plural|Pasiva presente simple plural]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The castle|El castillo]] ____ [[in the 12th century|en el siglo XII]].', options: ['[[was built|fue construido]]', '[[were built|fueron construidos]]', '[[built|construyó]]'], correctAnswer: 0, explanation: '[[Past simple passive singular|Pasiva pasado simple singular]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The historic site|El sitio histórico]] ____ [[right now|ahora mismo]] [[for visitors|para visitantes]].', options: ['[[is being restored|está siendo restaurado]]', '[[are being restored|están siendo restaurados]]', '[[is restored|está restaurado]]'], correctAnswer: 'is being restored', acceptableAnswers: ['is being restored'], explanation: '[[Present continuous passive|Pasiva presente continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The artefacts|Los artefactos]] ____ [[by the time we arrived|para cuando llegamos]].', options: ['[[had already been moved|ya habían sido trasladados]]', '[[have been moved|han sido trasladados]]', '[[were moved|fueron trasladados]]'], correctAnswer: 0, explanation: '[[Past perfect passive|Pasiva pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Heritage sites|Los sitios patrimoniales]] ____ [[by law|por ley]].', options: ['[[must be protected|deben ser protegidos]]', '[[must protect|deben proteger]]', '[[must be protecting|deben estar protegiendo]]'], correctAnswer: 'must be protected', acceptableAnswers: ['must be protected'], explanation: '[[Modal passive|Pasiva modal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The documents|Los documentos]] ____ [[when the fire started|cuando empezó el fuego]].', options: ['[[were being digitised|estaban siendo digitalizados]]', '[[are being digitised|están siendo digitalizados]]', '[[digitised|digitalizaron]]'], correctAnswer: 0, explanation: '[[Past continuous passive|Pasiva pasado continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The exhibition|La exposición]] ____ [[by next month|para el próximo mes]].', options: ['[[will have been opened|habrá sido inaugurada]]', '[[will be opened|será inaugurada]]', '[[has been opened|ha sido inaugurada]]'], correctAnswer: 'will have been opened', acceptableAnswers: ['will have been opened'], explanation: '[[Future perfect passive|Pasiva futuro perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Historical records|Los registros históricos]] ____ [[in the archive|en el archivo]] [[for research|para investigación]].', options: ['[[are kept|son guardados]]', '[[is kept|es guardado]]', '[[keep|guardar]]'], correctAnswer: 0, explanation: '[[Present simple passive|Pasiva presente simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The manuscript|El manuscrito]] ____ [[by historians|por historiadores]] [[last year|el año pasado]].', options: ['[[was discovered|fue descubierto]]', '[[were discovered|fueron descubiertos]]', '[[discovered|descubrió]]'], correctAnswer: 'was discovered', acceptableAnswers: ['was discovered'], explanation: '[[Past simple passive|Pasiva pasado simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The cathedral|La catedral]] ____ [[for three years|durante tres años]] [[in the 1990s|en los 90]].', options: ['[[was being renovated|estaba siendo renovada]]', '[[is being renovated|está siendo renovada]]', '[[has been renovated|ha sido renovada]]'], correctAnswer: 0, explanation: '[[Past continuous passive|Pasiva pasado continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Guided tours|Las visitas guiadas]] ____ [[daily|diariamente]] [[at the museum|en el museo]].', options: ['[[are offered|son ofrecidas]]', '[[is offered|es ofrecida]]', '[[offer|ofrecer]]'], correctAnswer: 'are offered', acceptableAnswers: ['are offered'], explanation: '[[Present simple passive|Pasiva presente simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The statue|La estatua]] ____ [[before the ceremony|antes de la ceremonia]].', options: ['[[has been unveiled|ha sido descubierta]]', '[[had been unveiled|había sido descubierta]]', '[[was unveiled|fue descubierta]]'], correctAnswer: 0, explanation: '[[Present perfect passive|Pasiva presente perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The collection|La colección]] ____ [[by thousands of visitors|por miles de visitantes]] [[at the moment|en este momento]].', options: ['[[is being viewed|está siendo vista]]', '[[are being viewed|están siendo vistas]]', '[[was being viewed|estaba siendo vista]]'], correctAnswer: 'is being viewed', acceptableAnswers: ['is being viewed'], explanation: '[[Present continuous passive|Pasiva presente continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ruins|Las ruinas]] ____ [[by the end of the decade|para final de la década]].', options: ['[[will be excavated|serán excavadas]]', '[[will have been excavated|habrán sido excavadas]]', '[[are excavated|están excavadas]]'], correctAnswer: 0, explanation: '[[Future simple passive|Pasiva futuro simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Cultural heritage|El patrimonio cultural]] ____ [[under UNESCO regulations|bajo las regulaciones UNESCO]].', options: ['[[must be preserved|debe ser preservado]]', '[[must preserve|debe preservar]]', '[[must be preserving|debe estar preservando]]'], correctAnswer: 'must be preserved', acceptableAnswers: ['must be preserved'], explanation: '[[Modal passive|Pasiva modal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The archive|El archivo]] ____ [[since 2020|desde 2020]].', options: ['[[has been expanded|ha sido ampliado]]', '[[had been expanded|había sido ampliado]]', '[[was expanded|fue ampliado]]'], correctAnswer: 0, explanation: '[[Present perfect passive|Pasiva presente perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The old church|La iglesia antigua]] ____ [[and converted|y convertida]] [[into a museum|en museo]] [[last decade|la década pasada]].', options: ['[[was restored|fue restaurada]]', '[[are restored|son restauradas]]', '[[restored|restauró]]'], correctAnswer: 'was restored', acceptableAnswers: ['was restored'], explanation: '[[Past simple passive|Pasiva pasado simple]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u16-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Passive (all tenses)', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The fresco|El fresco]] ____ [[when the wall collapsed|cuando se derrumbó el muro]].', options: ['[[was being restored|estaba siendo restaurado]]', '[[is being restored|está siendo restaurado]]', '[[has been restored|ha sido restaurado]]'], correctAnswer: 0, explanation: '[[Past continuous passive|Pasiva pasado continuo]].' }] }, topicName: 'Grammar' },
];
