/**
 * Unidad 8 B2 — Lección 5: Expresión oral (Travel)
 * 18 ejercicios (B2: Mixed conditionals, travel vocabulary)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_8_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b2-u8-l5-s1', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had|hubiera]] [[booked|reservado]] [[earlier|antes]], [[I|yo]] [[would have saved|habría ahorrado]] [[a lot of money|mucho dinero]].', expectedResponse: 'If I had booked earlier, I would have saved a lot of money.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s2', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[she|ella]] [[had caught|hubiera cogido]] [[the train|el tren]] [[yesterday|ayer]], [[she|ella]] [[would be|estaría]] [[here now|aquí ahora]].', expectedResponse: 'If she had caught the train yesterday, she would be here now.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s3', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[had to|tuve que]] [[check in|facturar]] [[online|en línea]] [[because|porque]] [[the airport|el aeropuerto]] [[was|estaba]] [[very busy|muy ocupado]].', expectedResponse: 'I had to check in online because the airport was very busy.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s4', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[destination|destino]] [[is|es]] [[Tokyo|Tokio]] [[and|y]] [[I|yo]] [[have|tengo]] [[a|una]] [[six-hour|seis horas]] [[layover|escala]] [[in|en]] [[Dubai|Dubái]].', expectedResponse: 'My destination is Tokyo and I have a six-hour layover in Dubai.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s5', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[had known|hubiera sabido]] [[about|sobre]] [[the delay|el retraso]] [[before|antes]], [[I|yo]] [[would have packed|habría empacado]] [[more|más]] [[in my hand luggage|en mi equipaje de mano]].', expectedResponse: 'If I had known about the delay before, I would have packed more in my hand luggage.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s6', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[set off|partí]] [[early|temprano]] [[this morning|esta mañana]] [[to avoid|para evitar]] [[traffic|tráfico]].', expectedResponse: 'I set off early this morning to avoid traffic.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s7', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[we|nosotros]] [[had left|hubiéramos salido]] [[earlier|antes]], [[we|nosotros]] [[would not have missed|no habríamos perdido]] [[the flight|el vuelo]].', expectedResponse: 'If we had left earlier, we would not have missed the flight.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s8', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[My|Mi]] [[visa|visa]] [[arrived|llegó]] [[just in time|justo a tiempo]] [[and|y]] [[my|mi]] [[passport|pasaporte]] [[is|está]] [[valid|válido]] [[for|para]] [[another|otros]] [[five years|cinco años]].', expectedResponse: 'My visa arrived just in time and my passport is valid for another five years.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s9', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con mixed conditional sobre un viaje (If I had..., I would...).', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would [infinitive]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s10', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que habrías hecho diferente en un viaje pasado.', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would have [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s11', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[had to|tuvimos que]] [[call off|cancelar]] [[our|nuestra]] [[trip|viaje]] [[because|porque]] [[of|de]] [[the storm|la tormenta]].', expectedResponse: 'We had to call off our trip because of the storm.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s12', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The plane|El avión]] [[took off|despegó]] [[on time|a tiempo]] [[and|y]] [[touched down|aterrizó]] [[safely|con seguridad]] [[at|en]] [[our|nuestro]] [[destination|destino]].', expectedResponse: 'The plane took off on time and touched down safely at our destination.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s13', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[they|ellos]] [[had accepted|hubieran aceptado]] [[the offer|la oferta]] [[last year|el año pasado]], [[they|ellos]] [[would be living|estarían viviendo]] [[abroad now|en el extranjero ahora]].', expectedResponse: 'If they had accepted the offer last year, they would be living abroad now.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s14', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: describe tu último viaje usando vocabulario de la unidad.', targetText: '____. ____. ____.', expectedResponse: 'I set off... My destination was... I had to check in...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s15', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases qué habrías hecho diferente en un viaje.', targetText: '____. ____. ____.', expectedResponse: 'If I had... I would have...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s16', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[packed|empacé]] [[light|ligero]] [[and|y]] [[only|solo]] [[took|llevé]] [[hand luggage|equipaje de mano]] [[to avoid|para evitar]] [[waiting|esperar]] [[at|en]] [[baggage claim|recogida de equipaje]].', expectedResponse: 'I packed light and only took hand luggage to avoid waiting at baggage claim.' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s17', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase con third conditional sobre un viaje.', targetText: '[[If|Si]] ____.', expectedResponse: 'If I had [past participle]..., I would have [past participle]...' }, topicName: 'Speaking' },
  { id: 'b2-u8-l5-s18', type: 'pronunciation', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases consejos para viajar (booking, check-in, luggage).', targetText: '____. ____. ____.', expectedResponse: 'Book early... Check in online... Pack light...' }, topicName: 'Speaking' },
];
