/**
 * Unidad 15 B2 — Lección 2: Vocabulario (Mixed topics)
 * 18 ejercicios (B2: más vocabulario y complejidad que B1)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Mixed topics|Mixed topics]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_15_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u15-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u15-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Mixed topics', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Choose|Elige]] [[the correct word|la palabra correcta]].', options: ['[[Option A|Opción A]]', '[[Option B|Opción B]]', '[[Option C|Opción C]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
