/**
 * Unidad 1 B2 — Lección 1: Gramática (Repaso B1 → B2)
 * 18 ejercicios (B2): Wish/regret, participle clauses, mixed conditionals
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[B1 Review|Repaso B1]] [[→|→]] [[B2|B2]]';
const INSTRUCTIONS = 'Elige la opción correcta.';

export const UNIT_1_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u1-l1-g1', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____[[more time|más tiempo]] [[when|cuando]] [[I|yo]] [[was|estaba]] [[at university|en la universidad]].', options: ['[[had had|hubiera tenido]]', '[[had|tenía]]', '[[have had|he tenido]]'], correctAnswer: 'had had', acceptableAnswers: ['had had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]] [[for past regrets|para arrepentimientos pasados]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g2', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If only|Ojalá]] [[she|ella]] ____[[me|me]] [[earlier|antes]].', options: ['[[had told|hubiera dicho]]', '[[told|dijo]]', '[[would tell|diría]]'], correctAnswer: 'had told', acceptableAnswers: ['had told'], explanation: '[[If only + past perfect|If only + pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g3', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the scenery|por el paisaje]], [[the hikers|los excursionistas]] [[took|tomaron]] [[photos|fotos]].', options: ['[[Inspired|Inspirados]]', '[[Inspiring|Inspirador]]', '[[Inspire|Inspirar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g4', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Having|Habiendo]] ____[[the report|el informe]], [[she|ella]] [[submitted|envió]] [[it|lo]].', options: ['[[finished|terminado]]', '[[finish|terminar]]', '[[finishing|terminando]]'], correctAnswer: 'finished', acceptableAnswers: ['finished'], explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g5', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The project|El proyecto]] ____[[by|por]] [[the team|el equipo]] [[last month|el mes pasado]].', options: ['[[was completed|fue completado]]', '[[has completed|ha completado]]', '[[completed|completó]]'], correctAnswer: 'was completed', acceptableAnswers: ['was completed'], explanation: '[[Passive voice|Voz pasiva]]: [[past simple passive|pasado simple pasivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[rather|más bien]] [[stay|quedarme]] [[at home|en casa]] [[tonight|esta noche]].', options: ['[[would|prefiero]]', '[[had better|más vale]]', '[[ought to|debería]]'], correctAnswer: 0, explanation: '[[Would rather|Preferiría]] [[for preferences|para preferencias]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g7', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[regret|arrepentirse]] [[not applying|no solicitar]] [[for the scholarship|la beca]].', options: ['[[regrets|se arrepiente de]]', '[[regret|arrepentirse]]'], correctAnswer: 'regrets', acceptableAnswers: ['regrets'], explanation: '[[Regret + gerund|Regret + gerundio]] [[for past actions|para acciones pasadas]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g8', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Despite|A pesar de]] ____[[the weather|el tiempo]], [[we|nosotros]] [[had|tuvimos]] [[a great time|un gran momento]].', options: ['[[the|el]]', '[[a|un]]'], correctAnswer: 'the', acceptableAnswers: ['the'], explanation: '[[Despite + noun phrase|Despite + sintagma nominal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g9', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It is said that|Se dice que]] [[he|él]] ____[[the best|el mejor]] [[candidate|candidato]].', options: ['[[is|es]]', '[[was|era]]', '[[has been|ha sido]]'], correctAnswer: 0, explanation: '[[Impersonal passive|Pasiva impersonal]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g10', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[she|ella]] ____[[harder|más duro]] [[last year|el año pasado]], [[she|ella]] ____[[the exam|el examen]] [[now|ahora]].', options: ['[[had studied|hubiera estudiado]]', '[[studied|estudió]]'], correctAnswer: 'had studied', acceptableAnswers: ['had studied'], explanation: '[[Mixed conditional|Condicional mixto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g11', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____[[speak|hablar]] [[Spanish|español]] [[fluently|con fluidez]].', options: ['[[could|pudiera]]', '[[can|puedo]]', '[[would|me]]'], correctAnswer: 'could', acceptableAnswers: ['could'], explanation: '[[Wish + could|Wish + could]] [[for present ability|para capacidad presente]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the news|por la noticia]], [[she|ella]] [[couldn\'t|couldn\'t]] [[sleep|dormir]].', options: ['[[Disturbed|Perturbada]]', '[[Disturbing|Perturbador]]', '[[Disturb|Perturbar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g13', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] [[we|nosotros]] ____[[left|marcharnos]].', options: ['[[left|nos marcháramos]]', '[[leave|marcharnos]]', '[[had left|nos hubiéramos marchado]]'], correctAnswer: 'left', acceptableAnswers: ['left'], explanation: '[[It\'s time + past simple|It\'s time + pasado simple]] [[for subjunctive|para subjuntivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g14', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____[[regret|arrepentirse]] [[not visiting|no visitar]] [[my|a mis]] [[grandparents|abuelos]] [[more often|más a menudo]].', options: ['[[regret|me arrepiento de]]', '[[regrets|se arrepiente de]]'], correctAnswer: 'regret', acceptableAnswers: ['regret'], explanation: '[[Regret + gerund|Regret + gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g15', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[the meeting|la reunión]] [[early|temprano]], [[he|él]] [[had|tuvo]] [[time|tiempo]] [[for lunch|para almorzar]].', options: ['[[Having finished|Habiendo terminado]]', '[[Finished|Terminado]]', '[[Finishing|Terminando]]'], correctAnswer: 0, explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g16', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____[[known|sabido]] [[about|sobre]] [[this|esto]] [[earlier|antes]].', options: ['[[had|hubiera]]', '[[have|he]]', '[[would|me]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g17', type: 'multiple-choice', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____|____]] [[by the deadline|por la fecha límite]], [[she|ella]] [[worked|trabajó]] [[overtime|horas extra]].', options: ['[[Pushed|Presionada]]', '[[Pushing|Presionando]]', '[[Push|Presionar]]'], correctAnswer: 0, explanation: '[[Participle clause|Cláusula de participio]]: [[-ed for passive|-ed para pasiva]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u1-l1-g18', type: 'fill-blank', level: 'B2', topic: 'B1 Review', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Despite|A pesar de]] ____[[efforts|esfuerzos]], [[the project|el proyecto]] [[failed|fracasó]].', options: ['[[their|sus]]', '[[our|nuestros]]', '[[his|su]]'], correctAnswer: 'their', acceptableAnswers: ['their', 'our'], explanation: '[[Despite + noun phrase|Despite + sintagma nominal]].' }] }, topicName: 'Grammar' },
];
