/**
 * Unidad 1 B2 — Lección 6: Expresión escrita (Health & Fitness)
 * 18 ejercicios con casos distintos
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_1_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u1-l6-w1', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2-3 frases sobre un reto fitness que te has propuesto y cómo lo estás abordando.', expressionHint: 'Puedes usar: [[challenge|reto]], [[work out|entrenar]], [[achieve|lograr]], [[overcome|superar]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____ [[known|sabido]] [[about|sobre]] [[this exercise|este ejercicio]] [[earlier|antes]].', options: ['[[had|hubiera]]', '[[have|he]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w3', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[Despite|A pesar de]] ____ [[the pain|el dolor]], [[I|yo]] [[kept running|seguí corriendo]].', options: ['[[the|el]]', '[[some|algo de]]'], correctAnswer: 'the', acceptableAnswers: ['the'], explanation: '[[Despite + noun phrase|Despite + sintagma nominal]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w4', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "I regret" + gerund sobre algo del pasado relacionado con tu salud.', expressionHint: '[[I regret not|Lamento no]] + -ing / [[I regret|Lamento]] + -ing', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con Encouraged o Discouraged.', questions: [{ question: '[[____|____]] [[by the results|por los resultados]], [[he|él]] [[increased|aumentó]] [[his training|su entrenamiento]].', options: ['[[Encouraged|Animado]]', '[[Discouraged|Desanimado]]'], correctAnswer: 'Encouraged', acceptableAnswers: ['Encouraged'], explanation: '[[Participle clause|Cláusula de participio]]: [[Encouraged = affected positively|Encouraged = afectado positivamente]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w6', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "would rather" y otra con "It\'s high time" sobre ejercicio o salud.', expressionHint: '[[I would rather|Preferiría]]... / [[It\'s high time we|Ya es hora de que]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w7', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con Having + participio.', questions: [{ question: '[[____|____]] ____ [[the marathon|el maratón]], [[she|ella]] [[took|tomó]] [[a rest|un descanso]].', options: ['[[Having finished|Habiendo terminado]]', '[[Finished|Terminado]]'], correctAnswer: 'Having finished', acceptableAnswers: ['Having finished'], explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w8', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre un hábito saludable que adoptaste y qué aprendiste.', expressionHint: 'Puedes usar: [[stay active|mantenerse activo]], [[overcome|superar]], [[healthy diet|dieta saludable]], [[proud of|orgulloso de]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w9', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I wish|Ojalá]] [[I|yo]] ____ [[tried|intentado]] [[harder|más duro]] [[when|cuando]] [[I|yo]] [[had the chance|tuve la oportunidad]] [[to join the gym|de unirme al gimnasio]].', options: ['[[had|hubiera]]', '[[have|he]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Wish + past perfect|Wish + pasado perfecto]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w10', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases sobre cómo mantienes tu motivación para hacer ejercicio.', expressionHint: '[[stay motivated|mantenerse motivado]], [[set goals|establecer metas]], [[work out|entrenar]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con Motivated o Demotivated.', questions: [{ question: '[[____|____]] [[by her progress|por su progreso]], [[she|ella]] [[set|estableció]] [[new fitness goals|nuevas metas de fitness]].', options: ['[[Motivated|Motivada]]', '[[Demotivated|Desmotivada]]'], correctAnswer: 'Motivated', acceptableAnswers: ['Motivated'], explanation: '[[Participle clause|Cláusula de participio]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w12', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con "It is believed that" sobre alguien que admiras por su estilo de vida saludable.', expressionHint: '[[It is believed that|Se cree que]] + subject + verb', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w13', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con would rather o would prefer.', questions: [{ question: '[[I|Yo]] ____ [[go|ir]] [[for a run|a correr]] [[than|que]] [[stay|quedarme]] [[on the sofa|en el sofá]].', options: ['[[would rather|prefiero]]', '[[would prefer|prefiero]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather', 'would prefer'], explanation: '[[Would rather + infinitive|Would rather + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w14', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases sobre retos fitness que te has propuesto.', expressionHint: '[[set challenges|establecer retos]], [[work out|entrenar]], [[achieve|lograr]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w15', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con Having + participio.', questions: [{ question: '[[____|____]] ____ [[the injury|la lesión]], [[I|yo]] [[feel|me siento]] [[stronger|más fuerte]].', options: ['[[Having recovered from|Habiendo recuperado de]]', '[[Recovered from|Recuperado de]]'], correctAnswer: 'Having recovered from', acceptableAnswers: ['Having recovered from'], explanation: '[[Having + past participle|Habiendo + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w16', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo (3-4 frases) sobre tu evolución en salud y fitness en el último año.', expressionHint: 'Puedes usar: [[overcome|superar]], [[work out|entrenar]], [[build endurance|construir resistencia]], [[set goals|establecer metas]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con Despite o In spite of.', questions: [{ question: '[[____|____]] ____ [[the fatigue|la fatiga]], [[he|él]] [[never|nunca]] [[stopped|dejó]] [[training|de entrenar]].', options: ['[[Despite|A pesar de]]', '[[Although|Aunque]]'], correctAnswer: 'Despite', acceptableAnswers: ['Despite', 'In spite of'], explanation: '[[Despite + noun phrase|Despite + sintagma nominal]].' }] }, topicName: 'Writing' },
  { id: 'b2-u1-l6-w18', type: 'writing', level: 'B2', topic: 'Health & Fitness', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre la importancia de mantenerse activo.', expressionHint: '[[stay active|mantenerse activo]], [[healthy|sano]], [[work out|entrenar]], [[learn|aprender]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
