/**
 * Unidad 22 B2 — Lección 1: Gramática (Linkers Reason Purpose: because of, due to, in order to, so that, as a result)
 * 18 ejercicios (B2: recreado con casos reales)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Linkers Reason Purpose|Linkers de razón y propósito]]';
const INSTRUCTIONS = 'Elige el conector de razón, propósito o resultado correcto.';

export const UNIT_22_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b2-u22-l1-g1', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Many species are endangered|Muchas especies están en peligro]] ____ [[habitat loss|la pérdida de hábitat]].', options: ['[[because of|debido a]]', '[[in order to|para]]', '[[so that|para que]]'], correctAnswer: 'because of', acceptableAnswers: ['because of', 'due to'], explanation: '[[Because of + noun for reason|Because of + sustantivo para razón]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g2', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The flight was cancelled|El vuelo fue cancelado]] ____ [[the storm|la tormenta]].', options: ['[[due to|debido a]]', '[[in order to|para]]', '[[so that|para que]]'], correctAnswer: 0, explanation: '[[Due to + noun for reason|Due to + sustantivo para razón]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g3', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We recycle|Reciclamos]] ____ [[reduce our carbon footprint|reducir nuestra huella de carbono]].', options: ['[[in order to|para]]', '[[because of|debido a]]', '[[as a result|como resultado]]'], correctAnswer: 'in order to', acceptableAnswers: ['in order to', 'to'], explanation: '[[In order to + infinitive for purpose|In order to + infinitivo para propósito]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g4', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She left early|Salió temprano]] ____ [[she wouldn\'t miss the train|no perdiera el tren]].', options: ['[[so that|para que]]', '[[because of|debido a]]', '[[due to|debido a]]'], correctAnswer: 0, explanation: '[[So that + subject + verb for purpose|So that + sujeto + verbo para propósito]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g5', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The factory closed|La fábrica cerró]]. ____ [[many people lost their jobs|muchas personas perdieron sus trabajos]].', options: ['[[As a result|Como resultado]]', '[[Because of|Debido a]]', '[[In order to|Para]]'], correctAnswer: 'As a result', acceptableAnswers: ['As a result', 'As a result,'], explanation: '[[As a result introduces a consequence|As a result introduce una consecuencia]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g6', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ the drought|____ la sequía]], [[the crops failed|las cosechas fallaron]].', options: ['[[Due to|Debido a]]', '[[In order to|Para]]', '[[So that|Para que]]'], correctAnswer: 0, explanation: '[[Due to + noun for reason|Due to + sustantivo para razón]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g7', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They built a fence|Construyeron una valla]] ____ [[protect the wildlife|proteger la fauna]].', options: ['[[in order to|para]]', '[[because of|debido a]]', '[[as a result|como resultado]]'], correctAnswer: 'in order to', acceptableAnswers: ['in order to', 'to'], explanation: '[[In order to + infinitive|In order to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g8', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He spoke slowly|Habló despacio]] ____ [[everyone could understand|todos pudieran entender]].', options: ['[[so that|para que]]', '[[because of|debido a]]', '[[due to|debido a]]'], correctAnswer: 0, explanation: '[[So that + clause for purpose|So that + cláusula para propósito]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g9', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ heavy pollution|____ la fuerte contaminación]], [[the river is now lifeless|el río está ahora sin vida]].', options: ['[[Because of|Debido a]]', '[[In order to|Para]]', '[[So that|Para que]]'], correctAnswer: 'Because of', acceptableAnswers: ['Because of', 'Due to'], explanation: '[[Because of/Due to + noun|Because of/Due to + sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g10', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We need to act now|Necesitamos actuar ahora]] ____ [[future generations can enjoy a healthy planet|las futuras generaciones puedan disfrutar un planeta sano]].', options: ['[[so that|para que]]', '[[because of|debido a]]', '[[as a result|como resultado]]'], correctAnswer: 0, explanation: '[[So that for purpose with future result|So that para propósito con resultado futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g11', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The roads were blocked|Las carreteras estaban bloqueadas]]. ____ [[we had to take a detour|tuvimos que dar un rodeo]].', options: ['[[As a result|Como resultado]]', '[[Because of|Debido a]]', '[[In order to|Para]]'], correctAnswer: 'As a result', acceptableAnswers: ['As a result', 'As a result,'], explanation: '[[As a result links cause and effect|As a result enlaza causa y efecto]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g12', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ climate change|____ el cambio climático]], [[glaciers are melting|los glaciares se están derritiendo]].', options: ['[[Due to|Debido a]]', '[[In order to|Para]]', '[[So that|Para que]]'], correctAnswer: 0, explanation: '[[Due to + noun|Due to + sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g13', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They campaigned|Hicieron campaña]] ____ [[save the forest|salvar el bosque]].', options: ['[[in order to|para]]', '[[because of|debido a]]', '[[as a result|como resultado]]'], correctAnswer: 'in order to', acceptableAnswers: ['in order to', 'to'], explanation: '[[In order to + infinitive|In order to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g14', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She took notes|Tomó notas]] ____ [[she wouldn\'t forget the details|no olvidara los detalles]].', options: ['[[so that|para que]]', '[[because of|debido a]]', '[[due to|debido a]]'], correctAnswer: 0, explanation: '[[So that + subject + verb|So that + sujeto + verbo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g15', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ the lack of rain|____ la falta de lluvia]], [[water levels dropped|los niveles de agua bajaron]].', options: ['[[Because of|Debido a]]', '[[In order to|Para]]', '[[So that|Para que]]'], correctAnswer: 'Because of', acceptableAnswers: ['Because of', 'Due to'], explanation: '[[Because of + noun|Because of + sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g16', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The project failed|El proyecto falló]]. ____ [[the team was disbanded|el equipo fue disuelto]].', options: ['[[As a result|Como resultado]]', '[[Because of|Debido a]]', '[[In order to|Para]]'], correctAnswer: 0, explanation: '[[As a result introduces the consequence|As a result introduce la consecuencia]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g17', type: 'fill-blank', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We use solar panels|Usamos paneles solares]] ____ [[cut our electricity bills|reducir nuestras facturas de luz]].', options: ['[[in order to|para]]', '[[because of|debido a]]', '[[as a result|como resultado]]'], correctAnswer: 'in order to', acceptableAnswers: ['in order to', 'to'], explanation: '[[In order to for purpose|In order to para propósito]].' }] }, topicName: 'Grammar' },
  { id: 'b2-u22-l1-g18', type: 'multiple-choice', level: 'B2', topic: 'Linkers Reason Purpose', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[____ the new regulations|____ las nuevas regulaciones]], [[emissions have decreased|las emisiones han disminuido]].', options: ['[[Due to|Debido a]]', '[[In order to|Para]]', '[[So that|Para que]]'], correctAnswer: 0, explanation: '[[Due to + noun for reason|Due to + sustantivo para razón]].' }] }, topicName: 'Grammar' },
];
