/**
 * Unidad 27 B2 — Lección 3: Comprensión lectora (Travel)
 * 13 preguntas (B2: texto sobre viajes y phrasal verbs LOOK, MAKE, PUT)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Planning|Planificar]] [[a trip|un viaje]] [[can|puede]] [[be|ser]] [[overwhelming|abrumador]], [[but|pero]] [[with|con]] [[the right approach|el enfoque adecuado]] [[it gets easier|se vuelve más fácil]]. [[Last year|El año pasado]] [[we|nosotros]] [[looked into|investigamos]] [[several|varios]] [[package holidays|viajes organizados]] [[before|antes de]] [[making up our minds|decidirnos]] — [[we|nosotros]] [[wanted|queríamos]] [[good value|buena relación calidad-precio]] [[for|para]] [[our money|nuestro dinero]]. [[We|Nosotros]] [[had to|tuvimos que]] [[put off|posponer]] [[our trip|nuestro viaje]] [[twice|dos veces]] [[due to|debido a]] [[work commitments|compromisos laborales]], [[but|pero]] [[the wait|la espera]] [[was worth it|valió la pena]]. [[I|Yo]] [[was looking forward to|estaba deseando]] [[visiting|visitar]] [[the old town|el casco antiguo]] [[and|y]] [[the guide|el guía]] [[looked after|cuidó de]] [[our group|nuestro grupo]] [[perfectly|perfectamente]]. [[The hotel|El hotel]] [[made up for|compensó]] [[the delay|el retraso]] [[at the airport|en el aeropuerto]] [[by|con]] [[offering|ofreciendo]] [[a free upgrade|una mejora gratis]]. [[We|Nosotros]] [[put up with|toleramos]] [[a long layover|una larga escala]] [[on the way back|a la vuelta]], [[but|pero]] [[overall|en general]] [[it was|fue]] [[an unforgettable experience|una experiencia inolvidable]].`;

const INSTRUCTIONS = 'Lee el texto sobre viajes. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[did they look into|investigaron]] [[before|antes de]] [[deciding|decidir]]?', options: ['[[Several package holidays|Varios viajes organizados]]', '[[The old town|El casco antiguo]]', '[[Work commitments|Compromisos laborales]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[we looked into several package holidays before making up our minds|investigamos varios viajes organizados antes de decidirnos]]".' },
  { question: '[[What|Qué]] [[did they have to do|tuvieron que hacer]] [[to their trip|con su viaje]] [[twice|dos veces]]?', options: ['[[They had to put it off due to work commitments|Tuvieron que posponerlo debido a compromisos laborales]]', '[[They had to cancel it|Tuvieron que cancelarlo]]', '[[They had to book it|Tuvieron que reservarlo]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[we had to put off our trip twice due to work commitments|tuvimos que posponer nuestro viaje dos veces debido a compromisos laborales]]".' },
  { question: '[[What|Qué]] [[was the author looking forward to|estaba deseando el autor]]?', options: ['[[Visiting the old town|Visitar el casco antiguo]]', '[[The long layover|La larga escala]]', '[[Work commitments|Los compromisos laborales]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[I was looking forward to visiting the old town|estaba deseando visitar el casco antiguo]]".' },
  { question: '[[What|Qué]] [[did the guide do|hizo el guía]]?', options: ['[[He looked after the group perfectly|Cuidó del grupo perfectamente]]', '[[He put off the trip|Pospuso el viaje]]', '[[He made up the delay|Inventó el retraso]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the guide looked after our group perfectly|el guía cuidó de nuestro grupo perfectamente]]".' },
  { question: '[[What|Qué]] [[did the hotel do|hizo el hotel]] [[to make up for the delay|para compensar el retraso]]?', options: ['[[It offered a free upgrade|Ofreció una mejora gratis]]', '[[It put off the check-in|Pospuso el check-in]]', '[[It looked into the delay|Investigó el retraso]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[the hotel made up for the delay at the airport by offering a free upgrade|el hotel compensó el retraso en el aeropuerto ofreciendo una mejora gratis]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[they cancelled the trip|cancelaron el viaje]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[They put off|Pospusieron]] [[the trip|el viaje]] [[twice|dos veces]] [[but|pero]] [[went|fueron]] [[eventually|eventualmente]].' },
  { question: '[[What|Cuál]] [[is|es]] [[the main idea|la idea principal]] [[of the text|del texto]]?', options: ['[[Planning a trip with the right approach can lead to a great experience|Planificar un viaje con el enfoque adecuado puede llevar a una gran experiencia]]', '[[Package holidays are always the best option|Los viajes organizados son siempre la mejor opción]]', '[[You should never put off a trip|Nunca deberías posponer un viaje]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[opens with|abre con]] [[this idea|esta idea]] [[and|y]] [[develops it|la desarrolla]] [[throughout|a lo largo]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[with "look"|con "look"]] [[means|significa]] [["investigate"|"investigar"]]?', options: ['[[Look into|Look into]]', '[[Look after|Look after]]', '[[Look forward to|Look forward to]]'], correctAnswer: 0, explanation: '[[Look into|Look into]] [[= investigate|= investigar]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the travellers|los viajeros]]?', options: ['[[They are patient and value good planning|Son pacientes y valoran una buena planificación]]', '[[They prefer last-minute trips|Prefieren viajes de última hora]]', '[[They never put up with delays|Nunca toleran retrasos]]'], correctAnswer: 0, explanation: '[[They|Ellos]] [[put off|pospusieron]] [[and|y]] [[put up with|toleraron]] [[delays|retrasos]].' },
  { question: '[[The author|El autor]] [[put up with|toleró]] [[the delay at the airport|el retraso en el aeropuerto]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[They put up with|Toleraron]] [[a long layover on the way back|una larga escala a la vuelta]], [[not|no]] [[the airport delay|el retraso en el aeropuerto]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[package holiday|viaje organizado]], [[old town|casco antiguo]], [[upgrade|mejora]], [[layover|escala]], [[guide|guía]]', '[[salary|salario]], [[budget|presupuesto]], [[profit|beneficio]]', '[[computer|ordenador]], [[software|software]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[travel vocabulary|vocabulario de viajes]].' },
  { question: '[[Which phrasal verb|Qué phrasal verb]] [[means|significa]] [["postpone"|"posponer"]]?', options: ['[[Put off|Put off]]', '[[Put on|Put on]]', '[[Put up with|Put up with]]'], correctAnswer: 0, explanation: '[[Put off|Put off]] [[= postpone|= posponer]].' },
  { question: '[[What|Qué]] [[does "make up for"|significa "make up for"]] [[mean|]] [[in this context|en este contexto]]?', options: ['[[Compensate|Compensar]]', '[[Invent|Inventar]]', '[[Decide|Decidir]]'], correctAnswer: 0, explanation: '[[Make up for|Make up for]] [[= compensate|= compensar]].' },
];

export const UNIT_27_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u27-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Travel',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
