/**
 * Unidad 13 B2 — Lección 3: Comprensión lectora (Money)
 * 13 preguntas (B2: recreado con texto y preguntas distintos)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[Digital banking|La banca digital]] [[has transformed|ha transformado]] [[how we manage our money|cómo gestionamos nuestro dinero]]. [[Today|Hoy]], [[you needn't visit|no necesitas visitar]] [[a branch|una sucursal]] [[to open an account|para abrir una cuenta]] [[or transfer funds|o transferir fondos]]; [[everything|todo]] [[can be done|puede hacerse]] [[from your smartphone|desde tu smartphone]]. [[However|Sin embargo]], [[customers must|los clientes deben]] [[verify their identity|verificar su identidad]] [[when signing up|al registrarse]], [[and|y]] [[you have to|tienes que]] [[use strong passwords|usar contraseñas seguras]] [[to protect your data|para proteger tus datos]]. [[Many people|Mucha gente]] [[who were sceptical|que era escéptica]] [[about online banking|sobre la banca online]] [[have discovered|ha descubierto]] [[that they needn't worry|que no necesita preocuparse]] [[about security|por la seguridad]] [[if they follow|si siguen]] [[basic precautions|precauciones básicas]]. [[Banks must|Los bancos deben]] [[comply with|cumplir con]] [[strict regulations|regulaciones estrictas]] [[to keep your money safe|para mantener tu dinero seguro]]. [[You need to|Necesitas]] [[check your statements|revisar tus extractos]] [[regularly|regularmente]] [[to spot|para detectar]] [[any unusual activity|cualquier actividad inusual]]. [[If something looks wrong|Si algo parece mal]], [[you must|debes]] [[report it immediately|reportarlo inmediatamente]]. [[The convenience|La comodidad]] [[of digital banking|de la banca digital]] [[means|significa]] [[that you don't have to|que no tienes que]] [[queue for hours|hacer cola durante horas]] [[or rush|o apresurarte]] [[before closing time|antes de la hora de cierre]].`;

const INSTRUCTIONS = 'Lee el texto sobre banca digital. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does the text say|dice el texto]] [[about visiting a branch|sobre visitar una sucursal]]?', options: ['[[You needn\'t visit one to open an account or transfer funds|No necesitas visitar una para abrir cuenta o transferir fondos]]', '[[You must always visit in person|Debes visitar siempre en persona]]', '[[Branches are closing everywhere|Las sucursales cierran en todas partes]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[you needn\'t visit a branch to open an account or transfer funds|no necesitas visitar una sucursal para abrir una cuenta o transferir fondos]]".' },
  { question: '[[What|Qué]] [[must customers do|deben hacer los clientes]] [[when signing up|al registrarse]]?', options: ['[[Verify their identity|Verificar su identidad]]', '[[Visit a branch|Visitar una sucursal]]', '[[Pay a fee|Pagar una tarifa]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[customers must verify their identity when signing up|los clientes deben verificar su identidad al registrarse]]".' },
  { question: '[[What|Qué]] [[do sceptical people often discover|descubren a menudo los escépticos]]?', options: ['[[They needn\'t worry about security if they follow basic precautions|No necesitan preocuparse por la seguridad si siguen precauciones básicas]]', '[[Online banking is always unsafe|La banca online siempre es insegura]]', '[[They must use cash only|Deben usar solo efectivo]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[they needn\'t worry about security if they follow basic precautions|no necesitan preocuparse por la seguridad si siguen precauciones básicas]]".' },
  { question: '[[What|Qué]] [[must banks do|deben hacer los bancos]]?', options: ['[[Comply with strict regulations to keep money safe|Cumplir regulaciones estrictas para mantener el dinero seguro]]', '[[Close all branches|Cerrar todas las sucursales]]', '[[Charge higher fees|Cobrar tarifas más altas]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[Banks must comply with strict regulations to keep your money safe|Los bancos deben cumplir con regulaciones estrictas para mantener tu dinero seguro]]".' },
  { question: '[[What|Qué]] [[do you need to do regularly|necesitas hacer regularmente]]?', options: ['[[Check your statements to spot unusual activity|Revisar tus extractos para detectar actividad inusual]]', '[[Visit the branch|Visitar la sucursal]]', '[[Change your password daily|Cambiar tu contraseña diariamente]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[You need to check your statements regularly to spot any unusual activity|Necesitas revisar tus extractos regularmente para detectar cualquier actividad inusual]]".' },
  { question: '[[What|Qué]] [[must you do|debes hacer]] [[if something looks wrong|si algo parece mal]]?', options: ['[[Report it immediately|Reportarlo inmediatamente]]', '[[Ignore it|Ignorarlo]]', '[[Close your account|Cerrar tu cuenta]]'], correctAnswer: 0, explanation: '[[The text says|El texto dice]] "[[you must report it immediately|debes reportarlo inmediatamente]]".' },
  { question: '[[The text|El texto]] [[states|afirma]] [[that|que]] [[you have to queue for hours with digital banking|tienes que hacer cola horas con la banca digital]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[you don\'t have to queue for hours|no tienes que hacer cola durante horas]]".' },
  { question: '[[According to the text|Según el texto]], [[you must use weak passwords|debes usar contraseñas débiles]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 1, explanation: '[[False|Falso]]. [[The text says|El texto dice]] "[[you have to use strong passwords|tienes que usar contraseñas seguras]]".' },
  { question: '[[What|Cuál]] [[is the main idea|es la idea principal]] [[of the text|del texto]]?', options: ['[[Digital banking is convenient but requires identity verification, strong passwords and regular monitoring|La banca digital es cómoda pero requiere verificación de identidad, contraseñas fuertes y supervisión regular]]', '[[Banks are closing|Los bancos están cerrando]]', '[[Cash is better than digital|El efectivo es mejor que lo digital]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[covers|abarca]] [[convenience|comodidad]], [[security requirements|requisitos de seguridad]] [[and|y]] [[monitoring|supervisión]].' },
  { question: '[[Which modal|Qué modal]] [[expresses absence of necessity|expresa ausencia de necesidad]] [[in the text|en el texto]]?', options: ['[[needn\'t (you needn\'t visit)|needn\'t (no necesitas visitar)]]', '[[must (customers must)|must (los clientes deben)]]', '[[have to (you have to)|have to (tienes que)]]'], correctAnswer: 0, explanation: '[[Needn\'t|Needn\'t]] [[indicates no necessity|indica que no es necesario]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in this text|en este texto]]?', options: ['[[digital banking|banca digital]], [[identity|identidad]], [[passwords|contraseñas]], [[statements|extractos]]', '[[festival|festival]], [[heritage|patrimonio]], [[tradition|tradición]]', '[[series|serie]], [[streaming|streaming]], [[cast|reparto]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[focuses on|se centra en]] [[banking vocabulary|vocabulario bancario]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[digital banking security|la seguridad de la banca digital]]?', options: ['[[It is reliable if users follow precautions|Es fiable si los usuarios siguen precauciones]]', '[[It is always unsafe|Siempre es insegura]]', '[[Banks do not protect data|Los bancos no protegen los datos]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[suggests|sugiere]] [[that following precautions makes it safe|que seguir precauciones la hace segura]].' },
  { question: '[[The phrase|La frase]] [["don\'t have to"|"don\'t have to"]] [[in "you don\'t have to queue"|en "no tienes que hacer cola"]] [[expresses|expresa]]:', options: ['[[Absence of obligation|Ausencia de obligación]]', '[[Strong obligation|Obligación fuerte]]', '[[Prohibition|Prohibición]]'], correctAnswer: 0, explanation: '[[Don\'t have to|Don\'t have to]] [[means no obligation|significa que no es obligatorio]].' },
];

export const UNIT_13_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u13-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Money',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
