/**
 * Unidad 47 B2 — Lección 6: Expresión escrita (Academic Writing & Reports)
 * 18 ejercicios (B2: oraciones hendidas y escritura académica)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_47_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u47-l6-w1', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo tu experiencia con la escritura académica. Usa: What I need is..., It was... that...', prompt: '[[Describe your experience with academic writing. Use: What I need is..., It was... that...|Describe tu experiencia con la escritura académica. Usa: What I need is..., It was... that...]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w2', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta de la oración hendida.', questions: [{ question: '[[What|Lo que]] [[I need|necesito]] ____ [[a good night\'s sleep|una buena noche de sueño]].', options: ['[[is|es]]', '[[are|son]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[What-clause takes singular verb|La cláusula What + verbo singular]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w3', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando oraciones hendidas para enfatizar.', prompt: '[[John broke the window. His reaction surprised me.|John rompió la ventana. Su reacción me sorprendió.]]', expressionHint: '[[Usa: It was John who... / What surprised me was...|Usa: It was John who... / What surprised me was...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w4', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "What I need is..." y otra con "It was... that...".', prompt: '[[Write two sentences: one with "What I need is..." and one with "It was... that...".|Escribe dos oraciones: una con "What I need is..." y otra con "It was... that...".]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w5', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[It was John|Fue John]] ____ [[broke|rompió]] [[the window|la ventana]].', options: ['[[who|quien]]', '[[which|que]]', '[[that|que]]'], correctAnswer: 'who', acceptableAnswers: ['who'], explanation: '[[It was + person + who|It was + persona + who]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w6', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre la importancia de la estructura en un informe. Usa cleft sentences.', prompt: '[[Describe the importance of structure in a report. Use cleft sentences.|Describe la importancia de la estructura en un informe. Usa oraciones hendidas.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w7', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando oraciones hendidas.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. What I need is ____|1. Lo que necesito es ____]]\n[[2. It was ____ who/that ____|2. Fue ____ quien/que ____]]\n[[3. What matters most is ____|3. Lo que más importa es ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w8', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[What surprised me|Lo que me sorprendió]] ____ [[his reaction|su reacción]].', options: ['[[was|fue]]', '[[were|fueron]]', '[[be|ser]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[What-clause + was + noun|What-clause + was + sustantivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w9', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre escritura académica. Usa cleft sentences.', prompt: '[[Write an introduction to an article about academic writing. Use cleft sentences.|Escribe la introducción de un artículo sobre escritura académica. Usa oraciones hendidas.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w10', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre "What I need is..." y "It was X who...".', prompt: '[[Explain the difference between "What I need is..." and "It was X who...". Use examples.|Explica la diferencia entre "What I need is..." y "It was X who...". Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w11', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[It was in 2020|Fue en 2020]] ____ [[the pandemic|la pandemia]] [[started|empezó]].', options: ['[[that|que]]', '[[when|cuando]]', '[[which|que]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It was + time + that|It was + tiempo + that]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w12', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte usando oraciones hendidas: She wrote the report. The conclusion was controversial.', prompt: '[[Convert using cleft sentences: She wrote the report. The conclusion was controversial.|Convierte usando oraciones hendidas: Ella escribió el informe. La conclusión fue controvertida.]]', expressionHint: '[[Usa: It was she who... / It was the conclusion that...|Usa: It was she who... / It was the conclusion that...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w13', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con: What I want to emphasise is..., It was... that..., What matters most is...', prompt: '[[Write three sentences with: What I want to emphasise is..., It was... that..., What matters most is...|Escribe tres oraciones con: What I want to emphasise is..., It was... that..., What matters most is...]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w14', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[What the report shows|Lo que muestra el informe]] ____ [[significant progress|un progreso significativo]].', options: ['[[is|es]]', '[[are|son]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[What-clause + singular verb|What-clause + verbo singular]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w15', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre tu experiencia con informes académicos. Usa cleft sentences.', prompt: '[[Describe your experience with academic reports. Use cleft sentences.|Describe tu experiencia con informes académicos. Usa oraciones hendidas.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w16', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando a un estudiante sobre cómo escribir un buen ensayo. Usa cleft sentences.', prompt: '[[Give advice on how to write a good essay. Use cleft sentences.|Da consejos sobre cómo escribir un buen ensayo. Usa oraciones hendidas.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w17', type: 'fill-blank', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[It was the conclusion|Fue la conclusión]] ____ [[was most controversial|fue más controvertida]].', options: ['[[that|que]]', '[[who|quien]]', '[[which|que]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It was + thing + that|It was + cosa + that]].' }] }, topicName: 'Writing' },
  { id: 'b2-u47-l6-w18', type: 'writing', level: 'B2', topic: 'education-learning', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué la argumentación es importante. Usa cleft sentences.', prompt: '[[Write a short conclusion about why argumentation is important. Use cleft sentences.|Escribe una breve conclusión sobre por qué la argumentación es importante. Usa oraciones hendidas.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
