/**
 * Unidad 27 B2 — Lección 6: Expresión escrita (Travel)
 * 18 ejercicios (B2: phrasal verbs LOOK, MAKE, PUT)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_27_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u27-l6-w1', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo un viaje que tuviste que posponer. Usa put off, look into, make up your mind.', prompt: '[[Describe a trip you had to put off. Use: put off, look into, make up your mind.|Describe un viaje que tuviste que posponer. Usa: put off, look into, make up your mind.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w2', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto: look into, make up, put off.', questions: [{ question: '[[We need to|Necesitamos]] ____ [[cheaper flights|vuelos más baratos]] [[before|antes de]] [[booking|reservar]] [[our trip|nuestro viaje]].', options: ['[[look into|investigar]]', '[[look after|cuidar]]', '[[look forward to|esperar con ilusión]]'], correctAnswer: 'look into', acceptableAnswers: ['look into'], explanation: '[[Look into = investigate|Look into = investigar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w3', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando put off o make up for.', prompt: '[[The trip was postponed|El viaje fue pospuesto]]. [[The hotel compensated|El hotel compensó]] [[the delay|el retraso]].', expressionHint: '[[Usa: "We put off the trip" y "The hotel made up for the delay"|Usa: "We put off the trip" y "The hotel made up for the delay"]]', targetLength: '1-2 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w4', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con look forward to y otra con look after.', prompt: '[[Write two sentences: one with look forward to (anticipate) and one with look after (take care of).|Escribe dos oraciones: una con look forward to (esperar con ilusión) y otra con look after (cuidar).]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w5', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[We|Nosotros]] ____ [[the trip|el viaje]] [[until|hasta]] [[next month|el próximo mes]] [[because|porque]] [[of|de]] [[the weather|el tiempo]].', options: ['[[put off|pospusimos]]', '[[put on|nos pusimos]]', '[[put up with|toleramos]]'], correctAnswer: 'put off', acceptableAnswers: ['put off'], explanation: '[[Put off = postpone|Put off = posponer]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w6', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre un viaje que esperabas con ilusión y qué pasó. Usa look forward to, put off, make up for.', prompt: '[[Describe a trip you were looking forward to and what happened. Use: look forward to, put off, make up for.|Describe un viaje que esperabas con ilusión y qué pasó. Usa: look forward to, put off, make up for.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w7', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando phrasal verbs.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. I looked into ____ when...|1. Investigé ____ cuando...]]\n[[2. We put off ____ because ____|2. Pospusimos ____ porque ____]]\n[[3. The hotel made up for ____ by ____|3. El hotel compensó ____ con ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w8', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "look into" o "look after".', questions: [{ question: '[[Can you|¿Puedes]] ____ [[my luggage|mi equipaje]] [[while|mientras]] [[I|yo]] [[check in|facturo]]?', options: ['[[look after|cuidar]]', '[[look into|investigar]]', '[[look for|buscar]]'], correctAnswer: 'look after', acceptableAnswers: ['look after'], explanation: '[[Look after = take care of|Look after = cuidar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w9', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre cómo planificar un viaje.', prompt: '[[Write an introduction to an article about how to plan a trip. Use at least one phrasal verb (look into, put off, make up your mind).|Escribe la introducción de un artículo sobre cómo planificar un viaje. Usa al menos un phrasal verb.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w10', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando qué puede requerir decidirse (make up your mind) cuando planificas un viaje.', prompt: '[[Explain what making up your mind when planning a trip can require. Use make up your mind and look into.|Explica qué puede requerir decidirse cuando planificas un viaje. Usa make up your mind y look into.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w11', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb adecuado.', questions: [{ question: '[[She|Ella]] ____ [[a story|una historia]] [[about|sobre]] [[why|por qué]] [[she was late|llegó tarde]] [[to the airport|al aeropuerto]].', options: ['[[made up|inventó]]', '[[made out|distinguió]]', '[[made for|se dirigió a]]'], correctAnswer: 'made up', acceptableAnswers: ['made up'], explanation: '[[Make up = invent|Make up = inventar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w12', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte estas frases en una usando look forward to.', prompt: '[[I am excited|Estoy emocionado]]. [[I will visit|Visitaré]] [[my friend|a mi amigo]] [[in Barcelona|en Barcelona]] [[next month|el próximo mes]].', expressionHint: '[[Usa: "I am looking forward to visiting my friend in Barcelona next month"|Usa: "I am looking forward to visiting my friend in Barcelona next month"]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w13', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con phrasal verbs (una con look into, otra con put off y otra con make up for).', prompt: '[[Write three sentences with phrasal verbs:|Escribe tres oraciones con phrasal verbs:]]\n[[- one with "look into"|- una con "look into"]]\n[[- one with "put off"|- una con "put off"]]\n[[- one with "make up for"|- una con "make up for"]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w14', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con "put up with" o "put off".', questions: [{ question: '[[They|Ellos]] ____ [[a lot of time|mucho tiempo]] [[by|con]] [[delayed flights|vuelos retrasados]] [[last year|el año pasado]].', options: ['[[put up with|toleraron]]', '[[put off|pospusieron]]', '[[put on|se pusieron]]'], correctAnswer: 'put up with', acceptableAnswers: ['put up with'], explanation: '[[Put up with = tolerate|Put up with = tolerar]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w15', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre un viaje que planificaste y qué pasó.', prompt: '[[Describe a trip you planned and what happened. Use: look into, put off, make up your mind, look forward to, make up for.|Describe un viaje que planificaste y qué pasó. Usa: look into, put off, make up your mind, look forward to, make up for.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w16', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases aconsejando cómo planificar un viaje sin posponerlo demasiado.', prompt: '[[Give advice on how to plan a trip without putting it off too much. Use look into and put off.|Da consejos sobre cómo planificar un viaje sin posponerlo demasiado. Usa look into y put off.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w17', type: 'fill-blank', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con el phrasal verb correcto.', questions: [{ question: '[[I|Yo]] ____ [[visiting|visitar]] [[my grandparents|a mis abuelos]] [[in|en]] [[the summer|el verano]] — [[they live|viven]] [[in|en]] [[a beautiful village|un pueblo bonito]].', options: ['[[look forward to|espero con ilusión]]', '[[look after|cuido]]', '[[look into|investigo]]'], correctAnswer: 'look forward to', acceptableAnswers: ['look forward to'], explanation: '[[Look forward to = anticipate with pleasure|Look forward to = esperar con ilusión]].' }] }, topicName: 'Writing' },
  { id: 'b2-u27-l6-w18', type: 'writing', level: 'B2', topic: 'Travel', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre por qué vale la pena investigar antes de viajar.', prompt: '[[Write a short conclusion explaining why it is worth looking into options before travelling. Use look into and make up your mind.|Escribe una breve conclusión explicando por qué vale la pena investigar antes de viajar. Usa look into y make up your mind.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
