/**
 * Unidad 10 B2 — Lección 3: Comprensión lectora (Repaso 6–9)
 * 13 preguntas (B2: mixed topics from units 6-9)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Reading|Comprensión lectora]]';
const READING_TRANSCRIPT = `[[I|Yo]] [[wish|ojalá]] [[I|yo]] [[had|hubiera]] [[listened|escuchado]] [[to|a]] [[my|mi]] [[father-in-law|suegro]] [[when|cuando]] [[he|él]] [[advised|aconsejó]] [[me|me]] [[about|sobre]] [[the|el]] [[job|trabajo]]. [[My|Mis]] [[siblings|hermanos]] [[get on with|se llevan bien con]] [[each other|entre ellos]] [[but|pero]] [[I|yo]] [[felt|me sentí]] [[overwhelmed|abrumado]] [[and|y]] [[frustrated|frustrado]] [[in|en]] [[that role|ese puesto]]. [[If|Si]] [[I|yo]] [[had booked|hubiera reservado]] [[my|mi]] [[flight|vuelo]] [[to visit|para visitar]] [[them|a ellos]] [[earlier|antes]], [[I|yo]] [[would have saved|habría ahorrado]] [[money|dinero]]. [[Having joined|Habiendo unido]] [[an environmental group|un grupo medioambiental]] [[last year|el año pasado]], [[I|yo]] [[now|ahora]] [[recycle|reciclo]] [[more|más]] [[and|y]] [[reduce|reduzco]] [[waste|residuos]]. [[It's time|Ya es hora]] [[I|yo]] [[called|llamara]] [[my|mi]] [[niece|sobrina]] — [[she|ella]] [[takes after|se parece a]] [[her|su]] [[mother|madre]] [[and|y]] [[I|yo]] [[feel|me siento]] [[grateful|agradecido]] [[for|por]] [[our|nuestra]] [[relationship|relación]]. [[Climate change|El cambio climático]] [[and|y]] [[pollution|contaminación]] [[from|de]] [[fossil fuels|combustibles fósiles]] [[are|son]] [[threats|amenazas]] — [[we|nosotros]] [[must|debemos]] [[support|apoyar]] [[renewable energy|energía renovable]] [[and|y]] [[sustainability|sostenibilidad]].`;

const INSTRUCTIONS = 'Lee el texto. Después responde las preguntas.';

const QUESTIONS = [
  { question: '[[What|Qué]] [[does the person wish|desea la persona]]?', options: ['[[To travel more|Viajar más]]', '[[To have listened to father-in-law about the job|Haber escuchado al suegro sobre el trabajo]]', '[[To work more|Trabajar más]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I wish I had listened to my father-in-law when he advised me about the job|ojalá hubiera escuchado a mi suegro cuando me aconsejó sobre el trabajo]]".' },
  { question: '[[Do the siblings get on|Los hermanos se llevan bien]]?', options: ['[[No|No]]', '[[Yes, with each other|Sí, entre ellos]]', '[[Sometimes|A veces]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[My siblings get on with each other|mis hermanos se llevan bien entre ellos]]".' },
  { question: '[[How|Cómo]] [[did the person feel in that role|se sintió la persona en ese puesto]]?', options: ['[[Delighted and grateful|Encantado y agradecido]]', '[[Overwhelmed and frustrated|Abrumado y frustrado]]', '[[Relieved and confident|Aliviado y seguro]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I felt overwhelmed and frustrated in that role|me sentí abrumado y frustrado en ese puesto]]".' },
  { question: '[[What|Qué]] [[would have happened|habría pasado]] [[if the person had booked the flight earlier|si la persona hubiera reservado el vuelo antes]]?', options: ['[[They would have missed the flight|Habrían perdido el vuelo]]', '[[They would have saved money|Habrían ahorrado dinero]]', '[[They would have stayed home|Habrían permanecido en casa]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[If I had booked my flight earlier, I would have saved money|si hubiera reservado mi vuelo antes, habría ahorrado dinero]]".' },
  { question: '[[When|Cuándo]] [[did the person join an environmental group|se unió la persona a un grupo medioambiental]]?', options: ['[[This year|Este año]]', '[[Last year|El año pasado]]', '[[Five years ago|Hace cinco años]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[Having joined an environmental group last year|habiendo unido un grupo medioambiental el año pasado]]".' },
  { question: '[[What|Qué]] [[does the person do now|hace la persona ahora]]?', options: ['[[Travel more|Viaja más]]', '[[Recycle more and reduce waste|Recicla más y reduce residuos]]', '[[Call less|Llama menos]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[I now recycle more and reduce waste|ahora reciclo más y reduzco residuos]]".' },
  { question: "[[What|Qué]] [[does the person say with \"It's time\"|dice la persona con \"It's time\"]]?", options: ["[[It's time to work|Ya es hora de trabajar]]", "[[It's time to call niece|Ya es hora de llamar a la sobrina]]", "[[It's time to leave|Ya es hora de irse]]"], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[It\'s time I called my niece|ya es hora de llamar a mi sobrina]]".' },
  { question: '[[Who|A quién]] [[does the niece take after|a quién se parece la sobrina]]?', options: ['[[Her father|A su padre]]', '[[Her mother|A su madre]]', '[[Her cousin|A su prima]]'], correctAnswer: 1, explanation: '[[The text says|El texto dice]] "[[she takes after her mother|se parece a su madre]]".' },
  { question: '[[What|Cuál]] [[is|es]] [[the main topic|el tema principal]] [[of|del]] [[this text|este texto]]?', options: ['[[Only travel|Solo viajes]]', '[[Family, work, travel, feelings and environment|Familia, trabajo, viajes, sentimientos y medio ambiente]]', '[[Only work|Solo trabajo]]'], correctAnswer: 1, explanation: '[[The text|El texto]] [[mixes|mezcla]] [[family|familia]], [[work|trabajo]], [[travel|viajes]], [[feelings|sentimientos]] [[and|y]] [[environment|medio ambiente]].' },
  { question: '[[What|Qué]] [[vocabulary|vocabulario]] [[is key|es clave]] [[in|en]] [[this text|este texto]]?', options: ['[[Father-in-law|Suegro]], [[siblings|hermanos]], [[recycle|reciclar]], [[climate change|cambio climático]], [[niece|sobrina]]', '[[Weather|Tiempo]], [[food|comida]]', '[[Work|Trabajo]], [[education|educación]]'], correctAnswer: 0, explanation: '[[The text|El texto]] [[uses|usa]] [[vocabulary|vocabulario]] [[from|de]] [[units 6-9|unidades 6-9]].' },
  { question: '[[The text|El texto]] [[mentions|menciona]] [[climate change and pollution|cambio climático y contaminación]].', options: ['[[True|Verdadero]]', '[[False|Falso]]'], correctAnswer: 'True', explanation: '[[True|Verdadero]]. [[The text says|El texto dice]] "[[Climate change and pollution from fossil fuels are threats|el cambio climático y la contaminación de combustibles fósiles son amenazas]]".' },
  { question: '[[What|Qué]] [[grammar structure|estructura gramatical]] [[does "Having joined" use|usa "Having joined"]]?', options: ['[[Having + past participle|Having + participio pasado]]', '[[Present participle|Participio presente]]', '[[Wish + past|Wish + pasado]]'], correctAnswer: 0, explanation: '[[Having + past participle|Having + participio pasado]] [[for completed action before main clause|para acción completada antes de la cláusula principal]].' },
  { question: '[[What|Qué]] [[can we infer|podemos inferir]] [[about|sobre]] [[the person|la persona]]?', options: ['[[They don\'t care about family or environment|No les importa la familia ni el medio ambiente]]', '[[They value family, reflect on mistakes and care about environment|Valoran la familia, reflexionan sobre errores y se preocupan por el medio ambiente]]', '[[They never travel|Nunca viajan]]'], correctAnswer: 1, explanation: '[[They wish they had listened|Desean haber escuchado]], [[would have saved for visit|habrían ahorrado para visitar]], [[recycle and reduce|reciclan y reducen]], [[call niece|llaman a sobrina]].' },
];

export const UNIT_10_LESSON_3_READING: Exercise[] = QUESTIONS.map((q, i) => ({
  id: `b2-u10-l3-r${i + 1}`,
  type: 'reading',
  level: 'B2',
  topic: 'Repaso 6–9',
  difficulty: 'medium',
  transcript: READING_TRANSCRIPT,
  content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [q] },
  topicName: 'Reading',
}));
