/**
 * Unidad 10 B2 — Lección 2: Vocabulario (Repaso 6–9)
 * 18 ejercicios (B2: Feelings, Family, Travel, Environment)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Repaso 6–9|Repaso 6–9]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_10_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u10-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Feeling very tired after hard work|Sentirse muy cansado tras trabajo duro]]:', options: ['[[exhausted|agotado]]', '[[thrilled|emocionado]]', '[[delighted|encantado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Brothers and sisters as a group|Hermanos y hermanas como grupo]]:', options: ['[[siblings|hermanos]]', '[[cousins|primos]]', '[[in-laws|familia política]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The place you are travelling to|El lugar al que viajas]]:', options: ['[[destination|destino]]', '[[departure|salida]]', '[[booking|reserva]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To process used materials for reuse|Procesar materiales usados para reutilizar]]:', options: ['[[recycle|reciclar]]', '[[pollute|contaminar]]', '[[waste|desperdiciar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Feeling glad a problem is over|Sentirse contento de que un problema haya terminado]]:', options: ['[[relieved|aliviado]]', '[[overwhelmed|abrumado]]', '[[frustrated|frustrado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Your husband or wife\'s mother|La madre de tu marido o mujer]]:', options: ['[[mother-in-law|suegra]]', '[[stepmother|madrastra]]', '[[grandmother|abuela]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Bags and suitcases for a journey|Bolsas y maletas para un viaje]]:', options: ['[[luggage|equipaje]]', '[[passport|pasaporte]]', '[[visa|visado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Harmful substances in air, water or soil|Sustancias dañinas en aire, agua o suelo]]:', options: ['[[pollution|contaminación]]', '[[recycling|reciclaje]]', '[[conservation|conservación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To have a good relationship with someone|Tener buena relación con alguien]]:', options: ['[[get on with|llevarse bien con]]', '[[fall out with|pelearse con]]', '[[take after|parecerse a]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To start a journey|Empezar un viaje]]:', options: ['[[set off|partir]]', '[[check in|facturar]]', '[[touch down|aterrizar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Ability to maintain resources for future generations|Capacidad de mantener recursos para generaciones futuras]]:', options: ['[[sustainability|sostenibilidad]]', '[[pollution|contaminación]]', '[[waste|residuos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Feeling thankful for help received|Sentirse agradecido por ayuda recibida]]:', options: ['[[grateful|agradecido]]', '[[jealous|celoso]]', '[[guilty|culpable]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Children of your aunt or uncle|Hijos de tu tía o tío]]:', options: ['[[cousins|primos]]', '[[nephews|sobrinos]]', '[[nieces|sobrinas]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When a plane leaves the ground|Cuando un avión deja el suelo]]:', options: ['[[take off|despegar]]', '[[touch down|aterrizar]]', '[[set off|partir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Long-term change in global temperatures|Cambio a largo plazo en temperaturas globales]]:', options: ['[[climate change|cambio climático]]', '[[weather|tiempo]]', '[[pollution|contaminación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To resemble a family member in looks or behaviour|Parecerse a un familiar en aspecto o comportamiento]]:', options: ['[[take after|parecerse a]]', '[[look up to|admirar a]]', '[[get on with|llevarse bien con]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A stop between connecting flights|Una parada entre vuelos de conexión]]:', options: ['[[layover|escala]]', '[[departure|salida]]', '[[arrival|llegada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u10-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Repaso 6–9', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Energy from natural sources that replenish|Energía de fuentes naturales que se reponen]]:', options: ['[[renewable energy|energía renovable]]', '[[fossil fuels|combustibles fósiles]]', '[[nuclear energy|energía nuclear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
