/**
 * Unidad 9 B2 — Lección 2: Vocabulario (Festivals & Celebrations)
 * 18 ejercicios (B2: parade, celebration, tradition, ceremony, etc.)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Festivals & Celebrations|Festivales y Celebraciones]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_9_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b2-u9-l2-v1', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Public procession with floats and performers|Procesión pública con carrozas y artistas]]:', options: ['[[parade|desfile]]', '[[ceremony|ceremonia]]', '[[carnival|carnaval]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v2', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Act of marking a special occasion|Acto de marcar una ocasión especial]]:', options: ['[[celebration|celebración]]', '[[mourning|luto]]', '[[protest|protesta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v3', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Custom passed down through generations|Costumbre transmitida por generaciones]]:', options: ['[[tradition|tradición]]', '[[trend|tendencia]]', '[[habit|hábito]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v4', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Formal event with rituals|Evento formal con rituales]]:', options: ['[[ceremony|ceremonia]]', '[[party|fiesta]]', '[[concert|concierto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v5', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Clothing worn for a special occasion|Ropa usada para ocasión especial]]:', options: ['[[costume|disfraz]]', '[[uniform|uniforme]]', '[[outfit|conjunto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v6', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Festival with music, dancing and masks|Festival con música, baile y máscaras]]:', options: ['[[carnival|carnaval]]', '[[funeral|funeral]]', '[[wedding|boda]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v7', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To honour or remember someone or something|Honrar o recordar a alguien o algo]]:', options: ['[[commemorate|conmemorar]]', '[[forget|olvidar]]', '[[ignore|ignorar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v8', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Day when people do not work|Día cuando la gente no trabaja]]:', options: ['[[public holiday|festivo]]', '[[weekend|fin de semana]]', '[[vacation|vacaciones]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v9', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Special food or dish for a festival|Comida especial para un festival]]:', options: ['[[festive dish|plato festivo]]', '[[fast food|comida rápida]]', '[[snack|tentempié]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v10', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To gather for a celebration|Reunirse para una celebración]]:', options: ['[[get together|reunirse]]', '[[split up|separarse]]', '[[leave|irse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v11', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To decorate for a celebration|Decorar para una celebración]]:', options: ['[[deck out|decorar]]', '[[strip|quitar]]', '[[remove|eliminar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v12', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To enjoy oneself at a party|Disfrutar en una fiesta]]:', options: ['[[have a blast|pasarlo genial]]', '[[be bored|aburrirse]]', '[[leave early|irse pronto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v13', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A gift given at a celebration|Regalo dado en una celebración]]:', options: ['[[present|regalo]]', '[[donation|donación]]', '[[loan|préstamo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v14', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make a toast with drinks|Brindar con bebidas]]:', options: ['[[raise a glass|brindar]]', '[[spill|derramar]]', '[[refuse|rechazar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v15', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Annual festival in a town or city|Festival anual en un pueblo o ciudad]]:', options: ['[[local festival|fiesta local]]', '[[wedding|boda]]', '[[funeral|funeral]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v16', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To organise a celebration|Organizar una celebración]]:', options: ['[[throw a party|dar una fiesta]]', '[[cancel|cancelar]]', '[[avoid|evitar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v17', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To celebrate the new year|Celebrar el año nuevo]]:', options: ['[[ring in the new year|recibir el año nuevo]]', '[[ignore|ignorar]]', '[[sleep through|dormir durante]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b2-u9-l2-v18', type: 'multiple-choice', level: 'B2', topic: 'Festivals & Celebrations', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Special anniversary celebration|Celebración de aniversario especial]]:', options: ['[[milestone|hito]]', '[[failure|fracaso]]', '[[mistake|error]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
