/**
 * Unidad 49 B2 — Lección 6: Expresión escrita (Sociology & Cultural Shifts)
 * 18 ejercicios (B2: inversión y sociología)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_49_LESSON_6_WRITING: Exercise[] = [
  { id: 'b2-u49-l6-w1', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases describiendo cambios culturales que has observado. Usa: Never have I..., Only then did I...', prompt: '[[Describe cultural shifts you have observed. Use: Never have I..., Only then did I...|Describe cambios culturales que has observado. Usa: Never have I..., Only then did I...]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w2', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta de inversión.', questions: [{ question: '[[Never|Nunca]] ____ [[I|yo]] ____ [[seen|visto]] [[such a beautiful sunset|un atardecer tan hermoso]].', options: ['[[have|he]]', '[[has|ha]]', '[[had|había]]'], correctAnswer: 'have', acceptableAnswers: ['have'], explanation: '[[Never + have + subject + past participle|Never + have + sujeto + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w3', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Reescribe usando inversión para enfatizar.', prompt: '[[I have never seen such a beautiful sunset. I realised my mistake only then.|Nunca he visto un atardecer tan hermoso. Solo entonces me di cuenta de mi error.]]', expressionHint: '[[Usa: Never have I..., Only then did I...|Usa: Never have I..., Only then did I...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w4', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2 frases: una con "Never have I..." y otra con "Only then did I...".', prompt: '[[Write two sentences: one with "Never have I..." and one with "Only then did I...".|Escribe dos oraciones: una con "Never have I..." y otra con "Only then did I...".]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w5', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Only then|Solo entonces]] ____ [[I|yo]] ____ [[realise|darme cuenta]] [[my mistake|mi error]].', options: ['[[did|me]]', '[[do|me]]', '[[had|me]]'], correctAnswer: 'did', acceptableAnswers: ['did'], explanation: '[[Only then + did + subject + verb|Only then + did + sujeto + verbo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w6', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3–4 frases sobre el papel de la migración en la sociedad. Usa inversión.', prompt: '[[Describe the role of migration in society. Use inversion.|Describe el papel de la migración en la sociedad. Usa inversión.]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w7', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa las frases con ideas propias usando inversión.', prompt: '[[Finish these sentences:|Completa estas oraciones:]]\n[[1. Never have I ____|1. Nunca he ____]]\n[[2. Only then did I ____|2. Solo entonces ____]]\n[[3. Not only ____ but also ____|3. No solo ____ sino también ____]]', targetLength: '3-4 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w8', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Not only|No solo]] ____ [[she|ella]] ____ [[talented|talentosa]], [[but she\'s also|sino que también es]] [[hardworking|trabajadora]].', options: ['[[is|es]]', '[[are|son]]', '[[be|ser]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[Not only + is + subject + adjective|Not only + is + sujeto + adjetivo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w9', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe la introducción de un artículo (40–60 palabras) sobre cambios culturales. Usa inversión.', prompt: '[[Write an introduction to an article about cultural shifts. Use inversion.|Escribe la introducción de un artículo sobre cambios culturales. Usa inversión.]]', writingType: 'article', targetLength: '40-60 palabras' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w10', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases explicando la diferencia entre "Never have I..." y "Seldom do we...".', prompt: '[[Explain the difference between "Never have I..." and "Seldom do we...". Use examples.|Explica la diferencia entre "Never have I..." y "Seldom do we...". Usa ejemplos.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w11', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Seldom|Rara vez]] ____ [[we|nosotros]] ____ [[such|tal]] [[cultural shifts|cambios culturales]].', options: ['[[do|vemos]]', '[[does|ve]]', '[[did|vimos]]'], correctAnswer: 'do', acceptableAnswers: ['do'], explanation: '[[Seldom + do + subject + verb|Seldom + do + sujeto + verbo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w12', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Convierte usando inversión: I have never seen such diversity. We realised it only then.', prompt: '[[Convert using inversion: I have never seen such diversity. We realised it only then.|Convierte usando inversión: Nunca he visto tal diversidad. Solo entonces nos dimos cuenta.]]', expressionHint: '[[Usa: Never have I..., Only then did we...|Usa: Never have I..., Only then did we...]]', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w13', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 3 oraciones con: Never have I..., Only then did I..., Not only... but also...', prompt: '[[Write three sentences with: Never have I..., Only then did I..., Not only... but also...|Escribe tres oraciones con: Never have I..., Only then did I..., Not only... but also...]]', targetLength: '3 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w14', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Hardly|Apenas]] ____ [[had|había]] [[I|yo]] ____ [[arrived|llegado]] [[when|cuando]] [[the meeting started|empezó la reunión]].', options: ['[[arrived|llegado]]', '[[arrive|llegar]]', '[[arriving|llegando]]'], correctAnswer: 'arrived', acceptableAnswers: ['arrived'], explanation: '[[Hardly had + subject + past participle|Hardly had + sujeto + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w15', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 60–80 palabras sobre cambios culturales en tu sociedad. Usa inversión.', prompt: '[[Describe cultural shifts in your society. Use inversion.|Describe cambios culturales en tu sociedad. Usa inversión.]]', targetLength: '60-80 palabras' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w16', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Escribe 2–3 frases sobre por qué la diversidad es importante. Usa inversión.', prompt: '[[Explain why diversity is important. Use inversion.|Explica por qué la diversidad es importante. Usa inversión.]]', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w17', type: 'fill-blank', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Under no circumstances|Bajo ninguna circunstancia]] ____ [[should|debería]] [[you|tú]] ____ [[give up|rendirte]].', options: ['[[give|rendirte]]', '[[gives|rinde]]', '[[gave|te rindiste]]'], correctAnswer: 'give', acceptableAnswers: ['give'], explanation: '[[Under no circumstances + should + subject + verb|Under no circumstances + should + sujeto + verbo]].' }] }, topicName: 'Writing' },
  { id: 'b2-u49-l6-w18', type: 'writing', level: 'B2', topic: 'history-society', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: 'Redacta la conclusión de un artículo (40–60 palabras) sobre el futuro de la sociedad. Usa inversión.', prompt: '[[Write a short conclusion about the future of society. Use inversion.|Escribe una breve conclusión sobre el futuro de la sociedad. Usa inversión.]]', targetLength: '40-60 palabras' }, topicName: 'Writing' },
];
