#!/usr/bin/env python3
"""
Expands units 11-20 from 41-51 to 60 interactions.
Adds a new Block 6 with 9-19 additional exercises per unit.
"""
import json
import random
from pathlib import Path

CONTENT_DIR = Path('src/content/cursos/ingles-a1')
random.seed(99)

def make_mc(uid, block_num, ix_num, prompt_es, options, correct_opt, mastery='vocabulary', complexity=2, concept_tags=None):
    opts = [{'id': f'o{i+1}', 'text': t} for i, t in enumerate(options)]
    return {
        'interaction_id': f'A1_U{uid}_B{uid}_{block_num}_E{ix_num}',
        'type': 'multiple_choice',
        'prompt_es': prompt_es,
        'options': opts,
        'correct_answer': f'o{correct_opt}',
        'mastery_tag': mastery,
        'complexity': complexity,
        'concept_tags': concept_tags or ['vocabulary'],
    }

def make_fill(uid, block_num, ix_num, prompt_es, stimulus_en, correct_answer, mastery='grammar', concept_tags=None):
    return {
        'interaction_id': f'A1_U{uid}_B{uid}_{block_num}_F{ix_num}',
        'type': 'fill_blanks',
        'prompt_es': prompt_es,
        'stimulus_en': stimulus_en,
        'correct_answer': correct_answer,
        'mastery_tag': mastery,
        'complexity': 2,
        'concept_tags': concept_tags or ['grammar'],
    }

def make_match(uid, block_num, ix_num, prompt_es, pairs, correct_answer, mastery='vocabulary'):
    return {
        'interaction_id': f'A1_U{uid}_B{uid}_{block_num}_M{ix_num}',
        'type': 'matching',
        'prompt_es': prompt_es,
        'pairs': pairs,
        'correct_answer': correct_answer,
        'mastery_tag': mastery,
        'complexity': 2,
        'concept_tags': ['vocabulary'],
    }

def make_reorder(uid, block_num, ix_num, prompt_es, words, correct_order, mastery='syntax'):
    opts = [{'id': f'w{i+1}', 'text': w} for i, w in enumerate(words)]
    correct_answer = [f'w{correct_order[i]+1}' for i in range(len(correct_order))]
    return {
        'interaction_id': f'A1_U{uid}_B{uid}_{block_num}_R{ix_num}',
        'type': 'reorder_words',
        'prompt_es': prompt_es,
        'options': opts,
        'correct_answer': correct_answer,
        'mastery_tag': mastery,
        'complexity': 3,
        'concept_tags': ['grammar', 'syntax'],
    }

def make_tf(uid, block_num, ix_num, prompt_es, correct_answer, mastery='grammar'):
    return {
        'interaction_id': f'A1_U{uid}_B{uid}_{block_num}_T{ix_num}',
        'type': 'true_false',
        'prompt_es': prompt_es,
        'options': [{'id': 'o1', 'text': '[[True|Verdadero]]'}, {'id': 'o2', 'text': '[[False|Falso]]'}],
        'correct_answer': 'o1' if correct_answer else 'o2',
        'mastery_tag': mastery,
        'complexity': 2,
        'concept_tags': ['grammar'],
    }

# ─── Unit 11: Telling the Time ───────────────────────────────────────────────
def extra_unit11():
    uid = 11
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Cómo se dice "8:05" en inglés?',
            ["[[Five past eight|Las ocho y cinco]]", "Eight five", "Five to eight", "Eight and five"],
            1, 'vocabulary'),
        make_mc(uid, bn, 2,
            '¿Cómo se lee "9:45"?',
            ["Nine forty-five", "[[Quarter to ten|Cuarto para las diez]]", "Quarter past nine", "Nine and quarter"],
            2, 'vocabulary'),
        make_fill(uid, bn, 1,
            'Completa con la hora correcta ([[at|a las]]): The train leaves ________ six [[o\'clock|en punto]].',
            'The train leaves ________ six o\'clock.',
            'at'),
        make_fill(uid, bn, 2,
            'Usa "[[half past|y media]]" para completar: Lunch is ________ one.',
            'Lunch is ________ one.',
            'half past'),
        make_mc(uid, bn, 3,
            '¿Cómo preguntas la hora en inglés?',
            ["What is clock?", "[[What time is it?|¿Qué hora es?]]", "How is the time?", "Which hour is?"],
            2, 'speaking'),
        make_fill(uid, bn, 3,
            'Completa: "[[It\'s|Son las]] ________ past three." (20 minutos)',
            'It\'s ________ past three.',
            'twenty'),
        make_tf(uid, bn, 1,
            '"[[It\'s quarter to seven|Son las siete menos cuarto]]" = 6:45. ¿Verdadero o falso?',
            True),
        make_tf(uid, bn, 2,
            '"[[It\'s half past eleven|Son las once y media]]" = 11:00. ¿Verdadero o falso?',
            False),
        make_reorder(uid, bn, 1,
            'Ordena: "La reunión es a las nueve en punto"',
            ['The', 'meeting', 'is', 'at', 'nine', "o'clock"],
            [0, 1, 2, 3, 4, 5]),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Extended Time Practice',
        'content': content,
    }

# ─── Unit 12: Days of the Week ────────────────────────────────────────────────
def extra_unit12():
    uid = 12
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Qué día es después del [[Wednesday|miércoles]]?',
            ["[[Thursday|Jueves]]", "Tuesday", "Friday", "Monday"],
            1, 'vocabulary'),
        make_mc(uid, bn, 2,
            '¿Cuáles son los días del fin de semana?',
            ["Monday and Tuesday", "[[Saturday and Sunday|Sábado y domingo]]", "Friday and Saturday", "Sunday and Monday"],
            2, 'vocabulary'),
        make_fill(uid, bn, 1,
            'Completa con el día correcto: "[[On|El]] ________ I go to the gym. [[On Monday|Los lunes]]"',
            'On ________ I go to the gym.',
            'Monday'),
        make_fill(uid, bn, 2,
            'Usa "[[on|el]]": The class is ________ [[Thursday|el jueves]].',
            'The class is ________ Thursday.',
            'on'),
        make_match(uid, bn, 1,
            'Relaciona el día con el número de orden:',
            [
                {'id': 'p1', 'left': '[[Monday|Lunes]]', 'right': '3.º'},
                {'id': 'p2', 'left': '[[Wednesday|Miércoles]]', 'right': '5.º'},
                {'id': 'p3', 'left': '[[Friday|Viernes]]', 'right': '1.º'},
                {'id': 'p4', 'left': '[[Sunday|Domingo]]', 'right': '7.º'},
            ],
            {'p1': 'p3', 'p2': 'p1', 'p3': 'p2', 'p4': 'p4'}),
        make_tf(uid, bn, 1,
            '"[[Tuesday|Martes]]" viene después de "[[Monday|Lunes]]". ¿Verdadero o falso?',
            True),
        make_tf(uid, bn, 2,
            '"[[Weekend|Fin de semana]]" incluye el [[Friday|viernes]]. ¿Verdadero o falso?',
            False),
        make_reorder(uid, bn, 1,
            'Ordena: "Los sábados voy de compras"',
            ['On', 'Saturdays', 'I', 'go', 'shopping'],
            [0, 1, 2, 3, 4]),
        make_mc(uid, bn, 3,
            '"I work [[from|desde]] [[Monday|lunes]] ________ Friday." ¿Qué palabra falta?',
            ["to", "[[to|hasta]]", "at", "in"],
            2, 'grammar'),
        make_fill(uid, bn, 3,
            'Completa: [[Today|Hoy]] is [[Monday|lunes]], so [[tomorrow|mañana]] is ________.',
            'Today is Monday, so tomorrow is ________.',
            'Tuesday'),
        make_mc(uid, bn, 4,
            '¿Cómo preguntas qué día es hoy?',
            ["What time is today?", "[[What day is it today?|¿Qué día es hoy?]]", "Which is the day?", "Day is what?"],
            2, 'speaking'),
        make_mc(uid, bn, 5,
            '¿Cuál es el primer día de la semana laboral?',
            ["[[Monday|Lunes]]", "Sunday", "Saturday", "Friday"],
            1, 'vocabulary'),
        make_tf(uid, bn, 3,
            '"[[Yesterday|Ayer]]" significa el día antes de hoy. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 4,
            'Completa: [[Yesterday|Ayer]] was [[Wednesday|miércoles]], so today is ________.',
            'Yesterday was Wednesday, so today is ________.',
            'Thursday'),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Days & Routines Extended',
        'content': content,
    }

# ─── Unit 13: Daily Routine ───────────────────────────────────────────────────
def extra_unit13():
    uid = 13
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Qué hace alguien que "[[wakes up|se despierta]]" a las 7?',
            ["Sleeps at 7", "[[Gets out of bed at 7|Se levanta a las 7]]", "Eats at 7", "Works at 7"],
            2, 'vocabulary'),
        make_fill(uid, bn, 1,
            'Completa: I [[brush|cepillarme]] ________ my teeth every morning.',
            'I ________ my teeth every morning.',
            'brush'),
        make_fill(uid, bn, 2,
            'Usa el verbo correcto: She [[has|tomar]] ________ breakfast at 8 o\'clock.',
            'She ________ breakfast at 8 o\'clock.',
            'has'),
        make_reorder(uid, bn, 1,
            'Ordena: "Me ducho todos los días"',
            ['I', 'have', 'a', 'shower', 'every', 'day'],
            [0, 1, 2, 3, 4, 5]),
        make_mc(uid, bn, 2,
            '¿Cuál de estos verbos describe una acción de la mañana?',
            ["[[Get dressed|Vestirse]]", "Have dinner", "Watch TV", "Go to bed"],
            1, 'vocabulary'),
        make_tf(uid, bn, 1,
            '"[[I go to bed at night|Me voy a dormir por la noche]]" es una rutina nocturna. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 3,
            '"What time do you ________ work?" ¿Qué verbo falta?',
            ["to start", "[[start|empezar]]", "starts", "starting"],
            2, 'grammar'),
        make_fill(uid, bn, 3,
            'Completa: I [[get|llegar]] ________ home at 6 pm.',
            'I ________ home at 6 pm.',
            'get'),
        make_mc(uid, bn, 4,
            '¿Cuál es la respuesta correcta a "What do you do in the evening?"',
            ["I go school", "[[I watch TV and relax|Veo la tele y descanso]]", "I sleep morning", "I at work"],
            2, 'speaking'),
        make_tf(uid, bn, 2,
            '"[[Have lunch|Almorzar]]" es una actividad de mediodía. ¿Verdadero o falso?',
            True),
        make_reorder(uid, bn, 2,
            'Ordena: "Ella trabaja de lunes a viernes"',
            ['She', 'works', 'from', 'Monday', 'to', 'Friday'],
            [0, 1, 2, 3, 4, 5]),
        make_fill(uid, bn, 4,
            'Completa con la hora: I [[have|tomar]] dinner ________ eight o\'clock.',
            'I have dinner ________ eight o\'clock.',
            'at'),
        make_mc(uid, bn, 5,
            '¿Qué significa "[[commute|desplazarse al trabajo]]"?',
            ["Sleep", "[[Travel to work|Ir al trabajo en transporte]]", "Have breakfast", "Cook dinner"],
            2, 'vocabulary'),
        make_mc(uid, bn, 6,
            '¿Cómo se dice "Después del desayuno" en inglés?',
            ["[[After breakfast|Después del desayuno]]", "Before dinner", "In the morning start", "At breakfast"],
            1, 'vocabulary'),
        make_tf(uid, bn, 3,
            '"[[I brush my teeth before bed|Me cepillo los dientes antes de dormir]]" es correcto. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 5,
            'Completa: He [[goes|ir]] ________ to bed at eleven.',
            'He ________ to bed at eleven.',
            'goes'),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Routine Verbs & Times',
        'content': content,
    }

# ─── Unit 14: Present Simple I/You/We/They ────────────────────────────────────
def extra_unit14():
    uid = 14
    bn = 6
    content = [
        make_fill(uid, bn, 1,
            'Afirmativa: I ________ [[English|inglés]] every day. ([[study|estudiar]])',
            'I ________ English every day.',
            'study'),
        make_fill(uid, bn, 2,
            'Negativa: They ________ [[like|gustar]] coffee. (no)',
            'They ________ like coffee.',
            "don't"),
        make_mc(uid, bn, 1,
            '"We ________ in London." ¿Qué forma del verbo [[live|vivir]] es correcta?',
            ["lives", "[[live|vivimos]]", "liveing", "is live"],
            2, 'grammar'),
        make_reorder(uid, bn, 1,
            'Ordena la pregunta: "¿Tú trabajas aquí?"',
            ['Do', 'you', 'work', 'here', '?'],
            [0, 1, 2, 3, 4]),
        make_mc(uid, bn, 2,
            '"Do you ________ music?" ¿Qué verbo encaja mejor?',
            ["[[like|gustar]]", "likes", "liked", "liking"],
            1, 'grammar'),
        make_fill(uid, bn, 3,
            'Usa [[don\'t|no]]: You ________ [[understand|entender]] the question.',
            'You ________ understand the question.',
            "don't"),
        make_tf(uid, bn, 1,
            '"We plays football" es correcto en Present Simple. ¿Verdadero o falso?',
            False),
        make_tf(uid, bn, 2,
            '"[[They eat|Ellos comen]] lunch at school" es una frase válida. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 3,
            '"[[Do|Auxiliar de pregunta]] they ________ near here?" ¿Qué verbo falta?',
            ["lives", "[[live|vivir]]", "living", "to live"],
            2, 'grammar'),
        make_fill(uid, bn, 4,
            'Respuesta corta: "Do you [[speak|hablar]] Spanish?" "Yes, I ________."',
            'Yes, I ________.',
            'do'),
        make_reorder(uid, bn, 2,
            'Ordena: "Nosotros no bebemos café"',
            ['We', "don't", 'drink', 'coffee'],
            [0, 1, 2, 3]),
        make_mc(uid, bn, 4,
            '¿Cuál de estas frases está en Present Simple negativa?',
            ["You not work", "[[You don't work|Tú no trabajas]]", "You doesn't work", "You no work"],
            2, 'grammar'),
        make_fill(uid, bn, 5,
            'Forma la pregunta: "________ you [[like|gustar]] sports?"',
            '________ you like sports?',
            'Do'),
        make_mc(uid, bn, 5,
            '"They ________ at 9 o\'clock." ¿Qué forma de [[start|empezar]] es correcta?',
            ["starting", "starts", "[[start|empiezan]]", "to start"],
            3, 'grammar'),
        make_tf(uid, bn, 3,
            '"[[I don\'t go|No voy]] to school on Sunday" es correcto. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 6,
            'Completa: We ________ [[play|jugar]] tennis on Saturdays. (afirmativa)',
            'We ________ tennis on Saturdays.',
            'play'),
        make_mc(uid, bn, 6,
            '¿Cómo se forma la pregunta con "they"?',
            ["They do work?", "Do they work?", "[[Do they work?|¿Trabajan ellos?]]", "Does they work?"],
            3, 'grammar'),
        make_fill(uid, bn, 7,
            'Respuesta negativa: "Do you [[eat|comer]] meat?" "No, I ________."',
            'No, I ________.',
            "don't"),
        make_reorder(uid, bn, 3,
            'Ordena: "¿Dónde viven ellos?"',
            ['Where', 'do', 'they', 'live', '?'],
            [0, 1, 2, 3, 4]),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Present Simple Extended Practice',
        'content': content,
    }

# ─── Unit 15: Present Simple He/She/It ────────────────────────────────────────
def extra_unit15():
    uid = 15
    bn = 6
    content = [
        make_fill(uid, bn, 1,
            'Tercera persona: She ________ [[work|trabajar]] at a hospital.',
            'She ________ at a hospital.',
            'works'),
        make_mc(uid, bn, 1,
            '"He ________ TV every evening." ¿Qué forma de [[watch|ver]] es correcta?',
            ["watch", "[[watches|ve]]", "watching", "to watch"],
            2, 'grammar'),
        make_fill(uid, bn, 2,
            'Negativa: He ________ [[like|gustar]] vegetables.',
            'He ________ like vegetables.',
            "doesn't"),
        make_reorder(uid, bn, 1,
            'Ordena: "¿Ella estudia inglés?"',
            ['Does', 'she', 'study', 'English', '?'],
            [0, 1, 2, 3, 4]),
        make_mc(uid, bn, 2,
            '"It ________ a lot in Manchester." ¿Qué forma de [[rain|llover]] es correcta?',
            ["rain", "raining", "[[rains|llueve]]", "rained"],
            3, 'grammar'),
        make_tf(uid, bn, 1,
            '"He don\'t work" es correcto. ¿Verdadero o falso?',
            False),
        make_tf(uid, bn, 2,
            '"[[She doesn\'t eat|Ella no come]] meat" es correcto. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 3,
            'Respuesta corta: "[[Does|Auxiliar]] he [[speak|hablar]] French?" "Yes, he ________."',
            'Yes, he ________.',
            'does'),
        make_mc(uid, bn, 3,
            '"She ________ to school every day." ¿Qué forma de [[go|ir]] es correcta?',
            ["go", "going", "[[goes|va]]", "gos"],
            3, 'grammar'),
        make_fill(uid, bn, 4,
            'Completa: It ________ [[take|tardar]] 20 minutes by bus.',
            'It ________ 20 minutes by bus.',
            'takes'),
        make_reorder(uid, bn, 2,
            'Ordena: "Él no bebe alcohol"',
            ['He', "doesn't", 'drink', 'alcohol'],
            [0, 1, 2, 3]),
        make_mc(uid, bn, 4,
            '"Mary ________ in Madrid." ¿Correcto?',
            ["Mary live", "[[Mary lives|María vive]]", "Mary are live", "Mary do live"],
            2, 'grammar'),
        make_fill(uid, bn, 5,
            'Forma negativa: She ________ [[have|tener]] a car.',
            'She ________ have a car.',
            "doesn't"),
        make_mc(uid, bn, 5,
            '"Does she ________ coffee?" ¿Correcto?',
            ["drinks", "[[drink|beber]]", "drinking", "to drink"],
            2, 'grammar'),
        make_tf(uid, bn, 3,
            '"The bank _______ on Sundays." → [[closes|cierra]]. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 6,
            'Completa con [[does|auxiliar]]: "________ your sister [[speak|hablar]] English?"',
            '________ your sister speak English?',
            'Does'),
        make_mc(uid, bn, 6,
            '¿Cuál es la forma correcta del verbo [[fly|volar]] en 3ª persona?',
            ["flys", "[[flies|vuela]]", "flyes", "fly"],
            2, 'grammar'),
        make_fill(uid, bn, 7,
            'Respuesta: "Does it work?" "No, it ________."',
            'No, it ________.',
            "doesn't"),
        make_reorder(uid, bn, 3,
            'Ordena: "¿Cuándo trabaja ella?"',
            ['When', 'does', 'she', 'work', '?'],
            [0, 1, 2, 3, 4]),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: He/She/It Extended Practice',
        'content': content,
    }

# ─── Unit 16: At the Café ─────────────────────────────────────────────────────
def extra_unit16():
    uid = 16
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Cómo pides un café en inglés?',
            ["Give me a coffee", "[[Could I have a coffee, please?|¿Me pone un café, por favor?]]", "I want coffee now", "Coffee for me"],
            2, 'speaking'),
        make_fill(uid, bn, 1,
            'Completa el pedido: "[[Could|poder]] I ________ a glass of water, please?"',
            'Could I ________ a glass of water, please?',
            'have'),
        make_mc(uid, bn, 2,
            '¿Qué bebida fría es típica de un café?',
            ["[[Iced tea|Té frío]]", "Hot soup", "Warm milk", "Boiled water"],
            1, 'vocabulary'),
        make_fill(uid, bn, 2,
            'El camarero dice: "________ [[you|usted]] ready to order?" ([[Are|Estar]])',
            'Are ________ ready to order?',
            'you'),
        make_tf(uid, bn, 1,
            '"[[A slice of cake|Un trozo de tarta]]" es un postre típico de café. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 3,
            '"How much is it?" significa:',
            ["¿Dónde está?", "[[¿Cuánto cuesta?|How much does it cost?]]", "¿Qué es esto?", "¿Para llevar?"],
            2, 'vocabulary'),
        make_reorder(uid, bn, 1,
            'Ordena el pedido: "Quiero un té con leche, por favor"',
            ['I', "'d", 'like', 'a', 'tea', 'with', 'milk', 'please'],
            [0, 1, 2, 3, 4, 5, 6, 7]),
        make_mc(uid, bn, 4,
            '"[[Take away|Para llevar]]" significa:',
            ["Eat here", "[[Food to take with you|Comida para llevar]]", "Order online", "Free food"],
            2, 'vocabulary'),
        make_fill(uid, bn, 3,
            'Completa: "The [[bill|cuenta]], ________, please." (para pedir la cuenta)',
            'The bill, ________, please.',
            'please'),
        make_tf(uid, bn, 2,
            '"[[Excuse me|Disculpe]]" se usa para llamar al camarero. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 5,
            '¿Cómo se dice "mesa para dos" en inglés?',
            ["Table for two people", "[[A table for two|Una mesa para dos]]", "Two table", "For two table"],
            2, 'speaking'),
        make_fill(uid, bn, 4,
            'Responde: "Do you take [[sugar|azúcar]]?" "No, ________ you." (rechazar amablemente)',
            'No, ________ you.',
            'thank'),
        make_mc(uid, bn, 6,
            '¿Qué significa "[[dairy-free|sin lácteos]]"?',
            ["With lots of milk", "[[Contains no dairy products|Sin productos lácteos]]", "Made from cheese", "Very creamy"],
            2, 'vocabulary'),
        make_fill(uid, bn, 5,
            'Completa: "I\'ll [[have|tomar]] the ________ please." ([[sandwich|sándwich]])',
            'I\'ll have the ________ please.',
            'sandwich'),
        make_mc(uid, bn, 7,
            '"[[Enjoy your meal!|¡Buen provecho!]]" lo dice:',
            ["The customer", "[[The waiter/waitress|El camarero/la camarera]]", "The chef", "The cashier"],
            2, 'speaking'),
        make_tf(uid, bn, 3,
            '"[[I\'d like|Me gustaría]]" es más educado que "I want". ¿Verdadero o falso?',
            True),
        make_reorder(uid, bn, 2,
            'Ordena: "¿Tienen mesa disponible?"',
            ['Do', 'you', 'have', 'a', 'table', 'available'],
            [0, 1, 2, 3, 4, 5]),
        make_fill(uid, bn, 6,
            'Completa: "Can I ________ the menu, please?" ([[see|ver]])',
            'Can I ________ the menu, please?',
            'see'),
        make_mc(uid, bn, 8,
            '¿Cómo se dice "sin azúcar" en inglés?',
            ["No sweet", "[[Sugar-free|Sin azúcar]]", "Without the sweet", "Not sugar"],
            2, 'vocabulary'),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Café Dialogues Extended',
        'content': content,
    }

# ─── Unit 17: Breakfast, Lunch & Dinner ───────────────────────────────────────
def extra_unit17():
    uid = 17
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Qué suelen comer los ingleses en el [[breakfast|desayuno]]?',
            ["Pizza and pasta", "[[Toast and eggs|Tostadas y huevos]]", "Rice and beans", "Soup and bread"],
            2, 'vocabulary'),
        make_fill(uid, bn, 1,
            'Completa: I usually [[have|tomar]] ________ for breakfast. ([[cereal|cereales]])',
            'I usually have ________ for breakfast.',
            'cereal'),
        make_mc(uid, bn, 2,
            '"[[Lunch|El almuerzo]]" is the meal we have:',
            ["In the morning", "[[In the middle of the day|A mediodía]]", "In the evening", "At night"],
            2, 'vocabulary'),
        make_fill(uid, bn, 2,
            'Completa: She [[eats|comer]] ________ salad for lunch. (a)',
            'She eats ________ salad for lunch.',
            'a'),
        make_mc(uid, bn, 3,
            '¿Cómo se dice "Tengo hambre" en inglés?',
            ["I am hungry food", "[[I\'m hungry|Tengo hambre]]", "I have hunger", "I want food now"],
            2, 'speaking'),
        make_reorder(uid, bn, 1,
            'Ordena: "¿Qué desayunas normalmente?"',
            ['What', 'do', 'you', 'usually', 'have', 'for', 'breakfast'],
            [0, 1, 2, 3, 4, 5, 6]),
        make_tf(uid, bn, 1,
            '"[[Dinner|La cena]]" is the last meal of the day. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 3,
            'Completa: There is ________ [[milk|leche]] in the fridge. (some/any)',
            'There is ________ milk in the fridge.',
            'some'),
        make_mc(uid, bn, 4,
            '"Is there ________ [[bread|pan]] left?" ¿Qué palabra falta?',
            ["some", "[[any|algún]]", "a", "the"],
            2, 'grammar'),
        make_mc(uid, bn, 5,
            '¿Cuál de estos es un [[snack|merienda/snack]]?',
            ["Full roast dinner", "[[A piece of fruit|Un trozo de fruta]]", "Three-course meal", "Sunday lunch"],
            2, 'vocabulary'),
        make_fill(uid, bn, 4,
            'Completa: We don\'t [[have|tener]] ________ sugar. (any/some)',
            'We don\'t have ________ sugar.',
            'any'),
        make_reorder(uid, bn, 2,
            'Ordena: "Ella bebe zumo de naranja por las mañanas"',
            ['She', 'drinks', 'orange', 'juice', 'in', 'the', 'morning'],
            [0, 1, 2, 3, 4, 5, 6]),
        make_tf(uid, bn, 2,
            '"[[I eat|Yo como]] three meals a day" es una afirmación correcta. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 6,
            '¿Cuál es la traducción de "[[leftovers|sobras]]"?',
            ["Fresh food", "[[Food remaining after a meal|Comida que sobra]]", "Frozen food", "Fast food"],
            2, 'vocabulary'),
        make_fill(uid, bn, 5,
            'Completa: He [[drinks|beber]] ________ coffee every morning. (a cup of)',
            'He drinks ________ coffee every morning.',
            'a cup of'),
        make_mc(uid, bn, 7,
            '"[[I\'m full|Estoy lleno/a]]" significa:',
            ["I am empty", "[[I have eaten enough|He comido suficiente]]", "I am hungry", "I want more food"],
            2, 'vocabulary'),
        make_fill(uid, bn, 6,
            'Completa con [[some|algo]]: Would you like ________ cake?',
            'Would you like ________ cake?',
            'some'),
        make_tf(uid, bn, 3,
            '"[[Vegetarian food|Comida vegetariana]]" no contiene carne. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 8,
            '¿Qué significa "[[skip breakfast|saltarse el desayuno]]"?',
            ["Eat a big breakfast", "[[Not eat breakfast|No desayunar]]", "Have breakfast in bed", "Eat very fast"],
            2, 'vocabulary'),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Meals & Food Habits Extended',
        'content': content,
    }

# ─── Unit 18: Healthy Eating ──────────────────────────────────────────────────
def extra_unit18():
    uid = 18
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            '¿Cuál de estos alimentos es más [[healthy|saludable]]?',
            ["[[Broccoli|Brócoli]]", "Chips", "Cake", "Cola"],
            1, 'vocabulary'),
        make_fill(uid, bn, 1,
            'Completa: [[Fruit|Fruta]] and ________ are good for your health. ([[vegetables|verduras]])',
            'Fruit and ________ are good for your health.',
            'vegetables'),
        make_mc(uid, bn, 2,
            '"[[Protein|Proteína]]" is found mainly in:',
            ["Sweets", "[[Meat, fish and eggs|Carne, pescado y huevos]]", "Bread and pasta", "Sugar and oil"],
            2, 'vocabulary'),
        make_fill(uid, bn, 2,
            'Completa: I [[try|intentar]] to ________ five portions of fruit and vegetables a day. (eat)',
            'I try to ________ five portions of fruit and vegetables a day.',
            'eat'),
        make_tf(uid, bn, 1,
            '"[[Water|Agua]]" is the healthiest drink. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 3,
            '¿Cuál de estos alimentos tiene más [[sugar|azúcar]]?',
            ["[[A fizzy drink|Una bebida con gas]]", "A glass of water", "A boiled egg", "A grilled chicken"],
            1, 'vocabulary'),
        make_reorder(uid, bn, 1,
            'Ordena: "Como verduras todos los días"',
            ['I', 'eat', 'vegetables', 'every', 'day'],
            [0, 1, 2, 3, 4]),
        make_mc(uid, bn, 4,
            '"[[Organic food|Alimentos orgánicos]]" means:',
            ["Very expensive food", "[[Grown without chemicals|Cultivado sin químicos]]", "Frozen food", "Fast food"],
            2, 'vocabulary'),
        make_fill(uid, bn, 3,
            'Completa: She [[doesn\'t|no]] ________ junk food. (eat)',
            'She ________ eat junk food.',
            "doesn't"),
        make_mc(uid, bn, 5,
            '¿Cuál es un alimento rico en [[fibre|fibra]]?',
            ["[[Wholemeal bread|Pan integral]]", "White rice", "Butter", "Cheese"],
            1, 'vocabulary'),
        make_tf(uid, bn, 2,
            '"[[Junk food|Comida basura]]" es saludable. ¿Verdadero o falso?',
            False),
        make_fill(uid, bn, 4,
            'Completa: He ________ [[eats|comer]] fast food because he wants to be healthy. (rarely)',
            'He ________ eats fast food because he wants to be healthy.',
            'rarely'),
        make_mc(uid, bn, 6,
            '¿Qué hace una persona que es "[[vegan|vegano]]"?',
            ["Eats only meat", "[[Doesn't eat any animal products|No come ningún producto animal]]", "Eats only fish", "Drinks only water"],
            2, 'vocabulary'),
        make_reorder(uid, bn, 2,
            'Ordena: "Es importante beber mucha agua"',
            ['It', 'is', 'important', 'to', 'drink', 'lots', 'of', 'water'],
            [0, 1, 2, 3, 4, 5, 6, 7]),
        make_fill(uid, bn, 5,
            'Completa: [[Vitamin|Vitamina]] C is found in ________ ([[oranges|naranjas]]).',
            'Vitamin C is found in ________.',
            'oranges'),
        make_mc(uid, bn, 7,
            '¿Cuántas porciones de fruta al día recomienda la OMS?',
            ["One", "[[Five|Cinco]]", "Ten", "Two"],
            2, 'vocabulary'),
        make_tf(uid, bn, 3,
            '"[[Skipping meals|Saltarse comidas]]" es una buena práctica de salud. ¿Verdadero o falso?',
            False),
        make_fill(uid, bn, 6,
            'Completa: ________ [[sugar|azúcar]] is bad for your teeth. (Too much)',
            '________ sugar is bad for your teeth.',
            'Too much'),
        make_mc(uid, bn, 8,
            '¿Cuál de estos es un [[dairy|lácteo]] product?',
            ["[[Yoghurt|Yogur]]", "Spinach", "Olive oil", "Beans"],
            1, 'vocabulary'),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Healthy Habits Extended',
        'content': content,
    }

# ─── Unit 19: Months & Dates ──────────────────────────────────────────────────
def extra_unit19():
    uid = 19
    bn = 6
    content = [
        make_match(uid, bn, 1,
            'Relaciona el mes con la estación ([[season|estación]]):',
            [
                {'id': 'p1', 'left': '[[January|Enero]]', 'right': 'Otoño'},
                {'id': 'p2', 'left': '[[April|Abril]]', 'right': 'Invierno'},
                {'id': 'p3', 'left': '[[October|Octubre]]', 'right': 'Primavera'},
                {'id': 'p4', 'left': '[[July|Julio]]', 'right': 'Verano'},
            ],
            {'p1': 'p2', 'p2': 'p3', 'p3': 'p1', 'p4': 'p4'}),
        make_fill(uid, bn, 1,
            'Completa: My [[birthday|cumpleaños]] is ________ the fifth of March. ([[on|el]])',
            'My birthday is ________ the fifth of March.',
            'on'),
        make_mc(uid, bn, 1,
            '¿Cómo se escribe "el 21 de junio" en inglés?',
            ["June 21nd", "[[June 21st|El veintiuno de junio]]", "The 21 of June", "21 June-st"],
            2, 'vocabulary'),
        make_fill(uid, bn, 2,
            'Completa: [[Christmas|Navidad]] is ________ December. ([[in|en]])',
            'Christmas is ________ December.',
            'in'),
        make_mc(uid, bn, 2,
            '"[[When|Cuándo]] is your birthday?" "It\'s ________ the 3rd of May." ¿Qué preposición?',
            ["in", "[[on|el]]", "at", "by"],
            2, 'grammar'),
        make_reorder(uid, bn, 1,
            'Ordena: "Mi cumpleaños es el dos de febrero"',
            ['My', 'birthday', 'is', 'on', 'the', 'second', 'of', 'February'],
            [0, 1, 2, 3, 4, 5, 6, 7]),
        make_mc(uid, bn, 3,
            '¿Cuál es el tercer mes del año?',
            ["February", "[[March|Marzo]]", "April", "January"],
            2, 'vocabulary'),
        make_fill(uid, bn, 3,
            'Ordinal: "the ________ of August" → el primero de agosto ([[first|primero]])',
            'the ________ of August',
            'first'),
        make_tf(uid, bn, 1,
            '"[[In summer|En verano]]" los meses son June, July y August (en el hemisferio norte). ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 4,
            '¿Qué mes viene después de [[October|octubre]]?',
            ["September", "December", "[[November|Noviembre]]", "August"],
            3, 'vocabulary'),
        make_fill(uid, bn, 4,
            'Completa: The [[school|escuela]] year usually starts ________ September. ([[in|en]])',
            'The school year usually starts ________ September.',
            'in'),
        make_mc(uid, bn, 5,
            '"[[The 14th of February|El 14 de febrero]]" is:',
            ["New Year", "[[Valentine\'s Day|El Día de San Valentín]]", "Halloween", "Christmas"],
            2, 'vocabulary'),
        make_reorder(uid, bn, 2,
            'Ordena: "¿En qué mes es tu cumpleaños?"',
            ['What', 'month', 'is', 'your', 'birthday', 'in'],
            [0, 1, 2, 3, 4, 5]),
        make_tf(uid, bn, 2,
            '"[[February|Febrero]]" tiene siempre 28 o 29 días. ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 5,
            'Escribe el ordinal: "the ________ of December" → el veinticinco ([[twenty-fifth|vigésimo quinto]])',
            'the ________ of December',
            'twenty-fifth'),
        make_mc(uid, bn, 6,
            '¿Cuántos meses tienen 31 días?',
            ["Five", "[[Seven|Siete]]", "Six", "Eight"],
            2, 'vocabulary'),
        make_fill(uid, bn, 6,
            'Completa: I was born ________ [[1999|mil novecientos noventa y nueve]]. ([[in|en]])',
            'I was born ________ 1999.',
            'in'),
        make_mc(uid, bn, 7,
            '¿Qué estación es [[September|septiembre]] en España?',
            ["[[Autumn/Fall|Otoño]]", "Spring", "Summer", "Winter"],
            1, 'vocabulary'),
        make_tf(uid, bn, 3,
            '"[[The 31st of October|El 31 de octubre]]" es Halloween. ¿Verdadero o falso?',
            True),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Dates & Seasons Extended',
        'content': content,
    }

# ─── Unit 20: Module 2 Review ─────────────────────────────────────────────────
def extra_unit20():
    uid = 20
    bn = 6
    content = [
        make_mc(uid, bn, 1,
            'Repaso: "She ________ [[work|trabajar]] on Sundays." (3ª persona negativa)',
            ["don't work", "[[doesn't work|no trabaja]]", "not work", "doesn't works"],
            2, 'grammar'),
        make_fill(uid, bn, 1,
            'Repaso: What ________ [[do|hacer]] you have for breakfast? ([[do|auxiliar]])',
            'What ________ you have for breakfast?',
            'do'),
        make_mc(uid, bn, 2,
            'Repaso de tiempo: "It\'s [[half past|y media]] two" = ________',
            ["2:15", "[[2:30|Las dos y media]]", "2:45", "2:05"],
            2, 'vocabulary'),
        make_fill(uid, bn, 2,
            'Repaso: My birthday is ________ the 10th of [[October|octubre]]. ([[on|el]])',
            'My birthday is ________ the 10th of October.',
            'on'),
        make_mc(uid, bn, 3,
            'Repaso: "Do you ________ [[coffee|café]]?"',
            ["drinks", "[[drink|beber]]", "drank", "drinking"],
            2, 'grammar'),
        make_reorder(uid, bn, 1,
            'Repaso: Ordena: "Ella come ensalada todos los días"',
            ['She', 'eats', 'salad', 'every', 'day'],
            [0, 1, 2, 3, 4]),
        make_tf(uid, bn, 1,
            'Repaso: "[[I go to work on Mondays|Voy al trabajo los lunes]]" usa Present Simple. ¿Verdadero o falso?',
            True),
        make_mc(uid, bn, 4,
            'Repaso café: "[[I\'d like|Me gustaría]] a cappuccino, please." Es correcto.',
            ["False - wrong order", "[[True - correct|Verdadero]]", "False - wrong verb", "False - impolite"],
            2, 'grammar'),
        make_fill(uid, bn, 3,
            'Repaso: "Is there ________ [[milk|leche]] in the fridge?" (pregunta) [[any|alguna]]',
            'Is there ________ milk in the fridge?',
            'any'),
        make_mc(uid, bn, 5,
            'Repaso: "[[The third of March|El tres de marzo]]" = March ________',
            ["3th", "[[3rd|tercero]]", "3nd", "3st"],
            2, 'vocabulary'),
        make_fill(uid, bn, 4,
            'Repaso: He ________ [[eat|comer]] vegetables because he wants to be healthy. (usually)',
            'He ________ vegetables because he wants to be healthy.',
            'eats'),
        make_mc(uid, bn, 6,
            'Repaso días: "[[On Fridays|Los viernes]] I have English class." ¿Correcto?',
            ["Incorrect grammar", "[[Correct|Correcto]]", "Wrong preposition", "Wrong word order"],
            2, 'grammar'),
        make_reorder(uid, bn, 2,
            'Repaso: Ordena: "¿A qué hora empieza el trabajo?"',
            ['What', 'time', 'do', 'you', 'start', 'work'],
            [0, 1, 2, 3, 4, 5]),
        make_tf(uid, bn, 2,
            'Repaso: "[[February|Febrero]] is the second month of the year." ¿Verdadero o falso?',
            True),
        make_fill(uid, bn, 5,
            'Repaso: She ________ [[get|levantarse]] up at 7 every morning. (gets/get)',
            'She ________ up at 7 every morning.',
            'gets'),
        make_mc(uid, bn, 7,
            'Repaso: ¿Qué pregunta se usa para preguntar la hora?',
            ["What hour it is?", "[[What time is it?|¿Qué hora es?]]", "How is time?", "Which clock is?"],
            2, 'speaking'),
        make_fill(uid, bn, 6,
            'Repaso: There ________ some vegetables in the kitchen. (is/are) [[are|hay]]',
            'There ________ some vegetables in the kitchen.',
            'are'),
        make_mc(uid, bn, 8,
            'Repaso alimentación: "[[Healthy|Saludable]]" food includes:',
            ["Crisps and cola", "[[Fruit, veg and water|Fruta, verdura y agua]]", "Cake and chocolate", "Fast food daily"],
            2, 'vocabulary'),
        make_tf(uid, bn, 3,
            'Repaso: "[[Does he like|¿Le gusta?]]" uses "does" for he/she/it. ¿Verdadero o falso?',
            True),
    ]
    return {
        'block_id': f'B{uid}_6',
        'title': 'Block 6: Module 2 Comprehensive Review',
        'content': content,
    }

EXTRA_BLOCKS = {
    11: extra_unit11,
    12: extra_unit12,
    13: extra_unit13,
    14: extra_unit14,
    15: extra_unit15,
    16: extra_unit16,
    17: extra_unit17,
    18: extra_unit18,
    19: extra_unit19,
    20: extra_unit20,
}

def expand_unit(unit_num):
    filepath = CONTENT_DIR / f'unit{unit_num}.json'
    with open(filepath) as f:
        data = json.load(f)
    
    before = sum(len(b.get('content', [])) for b in data['blocks'])
    
    extra_fn = EXTRA_BLOCKS.get(unit_num)
    if not extra_fn:
        print(f'  Unit {unit_num}: no extra block defined, skipping')
        return
    
    new_block = extra_fn()
    data['blocks'].append(new_block)
    
    after = sum(len(b.get('content', [])) for b in data['blocks'])
    print(f'  Unit {unit_num}: {before} → {after} interactions (+{after - before})')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def main():
    print('=== Expanding Units 11-20 to 60 interactions ===\n')
    for i in range(11, 21):
        expand_unit(i)
    print('\nDone!')

if __name__ == '__main__':
    main()
