import type { PodcastEpisode } from './types'

/** Módulo 4 — solo contenido curricular (guion, vocabulario, preguntas). Los MP3 se generan aparte. */
export const A1_EPISODES_M4: PodcastEpisode[] = [
  {
    id: 'a1-gen-02m-007',
    level: 'A1',
    track: 'general',
    durationMinutes: 2,
    module: 4,
    title: 'At the Pharmacy',
    description:
      'Pide medicamentos básicos y entiende instrucciones sencillas en una farmacia.',
    topic: 'health pharmacy',
    audioUrl: '/audio/podcasts/a1/a1-gen-02m-007.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Good morning! I need something for a headache, please.' },
      { speaker: 'B', voice: 'luna', text: 'Good morning! How long have you had the headache?' },
      { speaker: 'A', voice: 'orion', text: 'Since yesterday. It is not very strong, but it is annoying.' },
      { speaker: 'B', voice: 'luna', text: 'OK. Do you have any allergies to medicine?' },
      { speaker: 'A', voice: 'orion', text: 'No, I do not. I am not allergic to anything.' },
      { speaker: 'B', voice: 'luna', text: 'Good. Take one tablet with water after food. Maximum three times a day.' },
      { speaker: 'A', voice: 'orion', text: 'After food — understood. Anything else I should know?' },
      { speaker: 'B', voice: 'luna', text: 'Do not drink alcohol with this medicine. And get some rest today.' },
      { speaker: 'A', voice: 'orion', text: 'Thank you very much. How much is it?' },
      { speaker: 'B', voice: 'luna', text: 'That is four pounds ninety-nine. Would you like a bag?' },
      { speaker: 'A', voice: 'orion', text: 'Yes, please. Here is my card. Thank you for your help!' },
      { speaker: 'B', voice: 'luna', text: 'You are welcome. I hope you feel better soon. Goodbye!' },
      { speaker: 'A', voice: 'orion', text: 'Goodbye! See you next time.' },
    ],
    vocabulary: [
      { word: 'headache', translation: 'dolor de cabeza', example: 'I need something for a headache.' },
      { word: 'allergy', translation: 'alergia', example: 'Do you have any allergies to medicine?' },
      { word: 'tablet', translation: 'comprimido', example: 'Take one tablet with water after food.' },
      { word: 'after food', translation: 'después de comer', example: 'Take one tablet after food.' },
      { word: 'rest', translation: 'descanso', example: 'Get some rest today.' },
      { word: 'feel better', translation: 'sentirse mejor', example: 'I hope you feel better soon.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What problem does Tom have?',
        options: ['A cough', 'A headache', 'A fever', 'A broken arm'],
        correctIndex: 1,
        explanation: 'Tom says he needs something for a headache.',
      },
      {
        question: 'What should Tom NOT do with this medicine?',
        options: ['Take it after food', 'Drink water', 'Drink alcohol', 'Rest'],
        correctIndex: 2,
        explanation: 'The pharmacist says: Do not drink alcohol with this medicine.',
      },
      {
        question: 'How much does Tom pay?',
        options: ['£3.99', '£4.49', '£4.99', '£5.99'],
        correctIndex: 2,
        explanation: 'The pharmacist says: That is four pounds ninety-nine.',
      },
    ],
  },
  {
    id: 'a1-gen-02m-008',
    level: 'A1',
    track: 'general',
    durationMinutes: 2,
    module: 4,
    title: 'Finding the Museum',
    description: 'Pide y entiende indicaciones básicas para llegar a un lugar en la ciudad.',
    topic: 'directions city',
    audioUrl: '/audio/podcasts/a1/a1-gen-02m-008.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Excuse me! Is there a museum near here?' },
      { speaker: 'B', voice: 'luna', text: 'Yes! The City Museum is about ten minutes away on foot.' },
      { speaker: 'A', voice: 'orion', text: 'Great! Which way should I go?' },
      { speaker: 'B', voice: 'luna', text: 'Go straight along this street until you see a big bridge.' },
      { speaker: 'A', voice: 'orion', text: 'OK — straight, then a bridge. What next?' },
      { speaker: 'B', voice: 'luna', text: 'Cross the bridge. Then turn left at the traffic lights.' },
      { speaker: 'A', voice: 'orion', text: 'Turn left at the lights. Is the museum on the left or the right?' },
      { speaker: 'B', voice: 'luna', text: 'It is on your right — you cannot miss the big red building.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. Is there an entrance fee?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, but students get a discount with ID. Are you a student?' },
      { speaker: 'A', voice: 'orion', text: 'Yes, I am. Thank you so much for your help!' },
      { speaker: 'B', voice: 'luna', text: 'You are welcome. Enjoy your visit!' },
    ],
    vocabulary: [
      { word: 'on foot', translation: 'a pie', example: 'It is ten minutes away on foot.' },
      { word: 'go straight', translation: 'seguir recto', example: 'Go straight along this street.' },
      { word: 'bridge', translation: 'puente', example: 'Cross the bridge.' },
      { word: 'traffic lights', translation: 'semáforo', example: 'Turn left at the traffic lights.' },
      { word: 'entrance fee', translation: 'entrada / precio de entrada', example: 'Is there an entrance fee?' },
      { word: 'discount', translation: 'descuento', example: 'Students get a discount with ID.' },
    ],
    comprehensionQuestions: [
      {
        question: 'How far is the museum?',
        options: ['Five minutes on foot', 'About ten minutes on foot', 'Twenty minutes by bus', 'One hour'],
        correctIndex: 1,
        explanation: 'Sara says the museum is about ten minutes away on foot.',
      },
      {
        question: 'What does Tom do after the bridge?',
        options: ['Turn right', 'Turn left at the traffic lights', 'Take the bus', 'Go back'],
        correctIndex: 1,
        explanation: 'Sara says: Cross the bridge. Then turn left at the traffic lights.',
      },
      {
        question: 'What colour is the museum building?',
        options: ['Blue', 'Green', 'Red', 'Yellow'],
        correctIndex: 2,
        explanation: 'Sara says you cannot miss the big red building.',
      },
    ],
  },
  {
    id: 'a1-gen-05m-007',
    level: 'A1',
    track: 'general',
    durationMinutes: 5,
    module: 4,
    title: 'My Family',
    description: 'Habla de tu familia con have got, números y relaciones básicas.',
    topic: 'family descriptions',
    audioUrl: '/audio/podcasts/a1/a1-gen-05m-007.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Sara, tell me about your family. Is it big or small?' },
      { speaker: 'B', voice: 'luna', text: 'It is quite small. I have got my parents and one younger brother.' },
      { speaker: 'A', voice: 'orion', text: 'How old is your brother?' },
      { speaker: 'B', voice: 'luna', text: 'He is twenty-two. He is a university student in Barcelona.' },
      { speaker: 'A', voice: 'orion', text: 'Nice! What are your parents like?' },
      { speaker: 'B', voice: 'luna', text: 'My mother is kind and very patient. My father is funny but a bit strict sometimes.' },
      { speaker: 'A', voice: 'orion', text: 'Do you look like your mother or your father?' },
      { speaker: 'B', voice: 'luna', text: 'People say I look like my mother, but I have got my father\'s eyes.' },
      { speaker: 'A', voice: 'orion', text: 'Have you got any grandparents nearby?' },
      { speaker: 'B', voice: 'luna', text: 'Yes! My grandparents live in the same city. We visit them every Sunday for lunch.' },
      { speaker: 'A', voice: 'orion', text: 'That sounds lovely. Have you got any cousins?' },
      { speaker: 'B', voice: 'luna', text: 'I have got three cousins — two on my mother\'s side and one on my father\'s side.' },
      { speaker: 'A', voice: 'orion', text: 'Do you see your cousins often?' },
      { speaker: 'B', voice: 'luna', text: 'Not every week, but we meet at birthdays and at Christmas. We are quite close.' },
      { speaker: 'A', voice: 'orion', text: 'What do you usually do when the whole family is together?' },
      { speaker: 'B', voice: 'luna', text: 'We cook big meals, talk for hours, and play board games. Very noisy but happy!' },
      { speaker: 'A', voice: 'orion', text: 'Who cooks best in your family?' },
      { speaker: 'B', voice: 'luna', text: 'My grandmother. Her paella is famous in the whole family!' },
      { speaker: 'A', voice: 'orion', text: 'I would love to try it one day! Is your family important to you?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, very important. They support me and make me laugh. I am very lucky.' },
      { speaker: 'A', voice: 'orion', text: 'That is beautiful, Sara. Family really matters.' },
      { speaker: 'B', voice: 'luna', text: 'I agree, Tom. Even when we argue, we are always there for each other.' },
    ],
    vocabulary: [
      { word: 'have got', translation: 'tener', example: 'I have got one younger brother.' },
      { word: 'parents', translation: 'padres', example: 'I have got my parents and one brother.' },
      { word: 'strict', translation: 'estricto', example: 'My father is a bit strict sometimes.' },
      { word: 'grandparents', translation: 'abuelos', example: 'My grandparents live in the same city.' },
      { word: 'cousins', translation: 'primos', example: 'I have got three cousins.' },
      { word: 'support', translation: 'apoyar', example: 'They support me and make me laugh.' },
    ],
    comprehensionQuestions: [
      {
        question: 'How many brothers or sisters has Sara got?',
        options: ['None', 'One brother', 'One sister', 'Two brothers'],
        correctIndex: 1,
        explanation: 'Sara says she has got one younger brother.',
      },
      {
        question: 'Where does Sara\'s brother study?',
        options: ['Madrid', 'Seville', 'Barcelona', 'Valencia'],
        correctIndex: 2,
        explanation: 'Sara says he is a university student in Barcelona.',
      },
      {
        question: 'When does Sara usually visit her grandparents?',
        options: ['Every Saturday', 'Every Sunday', 'Once a month', 'Only at Christmas'],
        correctIndex: 1,
        explanation: 'Sara says: We visit them every Sunday for lunch.',
      },
    ],
  },
  {
    id: 'a1-gen-05m-008',
    level: 'A1',
    track: 'general',
    durationMinutes: 5,
    module: 4,
    title: 'Plans for Next Week',
    description: 'Usa going to y el presente simple para hablar de planes cercanos.',
    topic: 'future plans',
    audioUrl: '/audio/podcasts/a1/a1-gen-05m-008.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Sara, what are you going to do next week? Anything exciting?' },
      { speaker: 'B', voice: 'luna', text: 'Yes! On Monday I am going to visit the dentist in the morning.' },
      { speaker: 'A', voice: 'orion', text: 'Oh — not very exciting, but important! What about Tuesday?' },
      { speaker: 'B', voice: 'luna', text: 'On Tuesday evening I am going to meet my English class for a film in English.' },
      { speaker: 'A', voice: 'orion', text: 'That sounds fun! Which film are you going to watch?' },
      { speaker: 'B', voice: 'luna', text: 'We are going to watch a comedy. I want to improve my listening skills.' },
      { speaker: 'A', voice: 'orion', text: 'Good idea! What about the weekend?' },
      { speaker: 'B', voice: 'luna', text: 'On Saturday I am going to help my mother in the kitchen. She is teaching me her recipes.' },
      { speaker: 'A', voice: 'orion', text: 'That is nice. Are you going to travel anywhere?' },
      { speaker: 'B', voice: 'luna', text: 'Not next week. But next month I am going to visit a friend in Lisbon.' },
      { speaker: 'A', voice: 'orion', text: 'Lisbon is beautiful! How are you going to get there?' },
      { speaker: 'B', voice: 'luna', text: 'I am going to fly. It is only one hour from Madrid.' },
      { speaker: 'A', voice: 'orion', text: 'Are you going to stay in a hotel?' },
      { speaker: 'B', voice: 'luna', text: 'No, I am going to stay with my friend. It is cheaper and more fun!' },
      { speaker: 'A', voice: 'orion', text: 'What are you going to do in Lisbon?' },
      { speaker: 'B', voice: 'luna', text: 'We are going to walk in the old town and try the local food. I love pastel de nata!' },
      { speaker: 'A', voice: 'orion', text: 'You are going to have a great time! Anything you are not going to do next week?' },
      { speaker: 'B', voice: 'luna', text: 'I am not going to work overtime. I need a calmer week!' },
      { speaker: 'A', voice: 'orion', text: 'Smart plan. Rest is important too.' },
      { speaker: 'B', voice: 'luna', text: 'Exactly! I am going to sleep more and drink more water. Small changes for a better week.' },
    ],
    vocabulary: [
      { word: 'going to', translation: 'ir a (futuro próximo)', example: 'I am going to visit the dentist.' },
      { word: 'next week', translation: 'la semana que viene', example: 'What are you going to do next week?' },
      { word: 'improve', translation: 'mejorar', example: 'I want to improve my listening skills.' },
      { word: 'overtime', translation: 'horas extra', example: 'I am not going to work overtime.' },
      { word: 'local food', translation: 'comida local', example: 'We are going to try the local food.' },
      { word: 'stay with', translation: 'alojarse con', example: 'I am going to stay with my friend.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What is Sara going to do on Monday morning?',
        options: ['Meet her class', 'Visit the dentist', 'Fly to Lisbon', 'Cook with her mother'],
        correctIndex: 1,
        explanation: 'Sara says: On Monday I am going to visit the dentist in the morning.',
      },
      {
        question: 'What kind of film is Sara\'s class going to watch?',
        options: ['A horror film', 'A comedy', 'A documentary', 'An action film'],
        correctIndex: 1,
        explanation: 'Sara says: We are going to watch a comedy.',
      },
      {
        question: 'Where is Sara going to stay in Lisbon?',
        options: ['In a hotel', 'With her friend', 'In a hostel', 'She does not know yet'],
        correctIndex: 1,
        explanation: 'Sara says: I am going to stay with my friend.',
      },
    ],
  },
  {
    id: 'a1-pro-02m-005',
    level: 'A1',
    track: 'professional',
    durationMinutes: 2,
    module: 4,
    title: 'Confirming a Meeting',
    description: 'Confirma hora y lugar de una reunión breve por teléfono o en persona.',
    topic: 'meetings confirmation',
    audioUrl: '/audio/podcasts/a1/a1-pro-02m-005.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Hi Sara, it is Tom from the office. Can we meet tomorrow?' },
      { speaker: 'B', voice: 'luna', text: 'Hi Tom! Yes, of course. What time works for you?' },
      { speaker: 'A', voice: 'orion', text: 'I am free at ten in the morning. Is that OK for you?' },
      { speaker: 'B', voice: 'luna', text: 'Ten o\'clock is perfect. Which room should we use?' },
      { speaker: 'A', voice: 'orion', text: 'Let us use Meeting Room B on the second floor.' },
      { speaker: 'B', voice: 'luna', text: 'Great. How long will the meeting take? About thirty minutes?' },
      { speaker: 'A', voice: 'orion', text: 'Yes, thirty minutes should be enough. I will send a short agenda by email.' },
      { speaker: 'B', voice: 'luna', text: 'Thank you, Tom. I will see you tomorrow at ten in Meeting Room B.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. See you then. Have a good afternoon!' },
      { speaker: 'B', voice: 'luna', text: 'You too. Goodbye!' },
    ],
    vocabulary: [
      { word: 'works for you', translation: 'te viene bien', example: 'What time works for you?' },
      { word: 'meeting room', translation: 'sala de reuniones', example: 'Let us use Meeting Room B.' },
      { word: 'agenda', translation: 'orden del día', example: 'I will send a short agenda by email.' },
      { word: 'second floor', translation: 'segunda planta', example: 'Meeting Room B on the second floor.' },
      { word: 'free', translation: 'libre / disponible', example: 'I am free at ten in the morning.' },
      { word: 'enough', translation: 'suficiente', example: 'Thirty minutes should be enough.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What time is the meeting?',
        options: ['9:00', '10:00', '11:00', '2:00'],
        correctIndex: 1,
        explanation: 'They agree on ten o\'clock in the morning.',
      },
      {
        question: 'Where will they meet?',
        options: ['Meeting Room A', 'Meeting Room B', 'The canteen', 'Tom\'s desk'],
        correctIndex: 1,
        explanation: 'They agree on Meeting Room B on the second floor.',
      },
      {
        question: 'How long will the meeting take?',
        options: ['Fifteen minutes', 'Thirty minutes', 'One hour', 'Two hours'],
        correctIndex: 1,
        explanation: 'Sara says: About thirty minutes? Tom agrees.',
      },
    ],
  },
  {
    id: 'a1-pro-05m-005',
    level: 'A1',
    track: 'professional',
    durationMinutes: 5,
    module: 4,
    title: 'Introducing Yourself at a New Job',
    description: 'Presentación corta en un primer día: rol, equipo y expectativas.',
    topic: 'workplace introduction',
    audioUrl: '/audio/podcasts/a1/a1-pro-05m-005.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Everyone, this is Sara — she is joining our marketing team today.' },
      { speaker: 'B', voice: 'luna', text: 'Hello everyone! I am very happy to be here. My name is Sara López.' },
      { speaker: 'A', voice: 'orion', text: 'Sara, would you like to tell us a little about your background?' },
      { speaker: 'B', voice: 'luna', text: 'I studied business at university and I worked for two years in a small company in Madrid.' },
      { speaker: 'A', voice: 'orion', text: 'What did you do in your last job?' },
      { speaker: 'B', voice: 'luna', text: 'I helped with social media and email campaigns. I also organised small events.' },
      { speaker: 'A', voice: 'orion', text: 'That is very useful for us. What are you most excited about in this role?' },
      { speaker: 'B', voice: 'luna', text: 'I am excited to learn from the team and to work on international projects.' },
      { speaker: 'A', voice: 'orion', text: 'Who will be your main contact in the first week?' },
      { speaker: 'B', voice: 'luna', text: 'I think Emma will show me the systems and introduce me to the clients.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. Is there anything you need from us today?' },
      { speaker: 'B', voice: 'luna', text: 'I need access to the shared drive and the company email on my laptop, please.' },
      { speaker: 'A', voice: 'orion', text: 'IT will set that up this morning. Anything else?' },
      { speaker: 'B', voice: 'luna', text: 'Maybe a map of the building — I do not want to get lost on my first day!' },
      { speaker: 'A', voice: 'orion', text: 'Ha! Good idea. We will give you a printed map and a welcome pack.' },
      { speaker: 'B', voice: 'luna', text: 'Thank you so much. I am a bit nervous but very motivated.' },
      { speaker: 'A', voice: 'orion', text: 'That is normal. We are here to help you. Welcome once again, Sara!' },
      { speaker: 'B', voice: 'luna', text: 'Thank you all. I am looking forward to working with you!' },
    ],
    vocabulary: [
      { word: 'marketing team', translation: 'equipo de marketing', example: 'She is joining our marketing team.' },
      { word: 'background', translation: 'formación / trayectoria', example: 'Tell us about your background.' },
      { word: 'campaign', translation: 'campaña', example: 'I helped with email campaigns.' },
      { word: 'role', translation: 'puesto / rol', example: 'What are you excited about in this role?' },
      { word: 'shared drive', translation: 'unidad compartida', example: 'I need access to the shared drive.' },
      { word: 'motivated', translation: 'motivado/a', example: 'I am very motivated.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What did Sara study?',
        options: ['Law', 'Medicine', 'Business', 'Engineering'],
        correctIndex: 2,
        explanation: 'Sara says she studied business at university.',
      },
      {
        question: 'Who will help Sara in her first week?',
        options: ['Tom', 'Emma', 'The IT team', 'A client'],
        correctIndex: 1,
        explanation: 'Sara says Emma will show her the systems and introduce her to clients.',
      },
      {
        question: 'What does Sara need from IT?',
        options: ['A new phone', 'Access to the shared drive and email', 'A printer', 'A parking space'],
        correctIndex: 1,
        explanation: 'Sara asks for access to the shared drive and company email.',
      },
    ],
  },
  {
    id: 'a1-tra-02m-005',
    level: 'A1',
    track: 'travel',
    durationMinutes: 2,
    module: 4,
    title: 'A Delayed Train',
    description: 'Entiende anuncios sencillos y pregunta por el próximo tren.',
    topic: 'transport delays',
    audioUrl: '/audio/podcasts/a1/a1-tra-02m-005.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Excuse me! Is the train to Brighton delayed?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, I am sorry. There is a delay of about twenty minutes.' },
      { speaker: 'A', voice: 'orion', text: 'Oh no! Why is it delayed?' },
      { speaker: 'B', voice: 'luna', text: 'There is a problem on the line. The staff are working on it now.' },
      { speaker: 'A', voice: 'orion', text: 'Will the train leave from this platform?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, platform 5. Do not worry — the screen will update when it is ready.' },
      { speaker: 'A', voice: 'orion', text: 'Can I get a coffee while I wait?' },
      { speaker: 'B', voice: 'luna', text: 'Of course. There is a café next to the ticket office.' },
      { speaker: 'A', voice: 'orion', text: 'Thank you. I hope the train is not cancelled!' },
      { speaker: 'B', voice: 'luna', text: 'It is not cancelled — only delayed. Have a safe journey!' },
    ],
    vocabulary: [
      { word: 'delayed', translation: 'retrasado', example: 'Is the train to Brighton delayed?' },
      { word: 'platform', translation: 'andén', example: 'The train leaves from platform 5.' },
      { word: 'cancelled', translation: 'cancelado', example: 'I hope the train is not cancelled.' },
      { word: 'ticket office', translation: 'taquilla', example: 'There is a café next to the ticket office.' },
      { word: 'line', translation: 'línea (vía)', example: 'There is a problem on the line.' },
      { word: 'safe journey', translation: 'buen viaje', example: 'Have a safe journey!' },
    ],
    comprehensionQuestions: [
      {
        question: 'How long is the delay?',
        options: ['Ten minutes', 'About twenty minutes', 'One hour', 'The train is cancelled'],
        correctIndex: 1,
        explanation: 'The staff member says: a delay of about twenty minutes.',
      },
      {
        question: 'Which platform does Tom need?',
        options: ['3', '4', '5', '6'],
        correctIndex: 2,
        explanation: 'Sara says: Yes, platform 5.',
      },
      {
        question: 'Is the train cancelled?',
        options: ['Yes', 'No', 'We do not know', 'Only on weekends'],
        correctIndex: 1,
        explanation: 'Sara says: It is not cancelled — only delayed.',
      },
    ],
  },
  {
    id: 'a1-tra-05m-005',
    level: 'A1',
    track: 'travel',
    durationMinutes: 5,
    module: 4,
    title: 'Hiring a Car on Holiday',
    description: 'Pregunta por seguro, kilometraje y devolución del vehículo alquilado.',
    topic: 'car rental',
    audioUrl: '/audio/podcasts/a1/a1-tra-05m-005.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Hello! I would like to hire a car for five days, please.' },
      { speaker: 'B', voice: 'luna', text: 'Of course. Do you have a reservation or do you want to book now?' },
      { speaker: 'A', voice: 'orion', text: 'I am booking now. I need a small car — automatic, if possible.' },
      { speaker: 'B', voice: 'luna', text: 'We have a compact automatic available. It includes basic insurance.' },
      { speaker: 'A', voice: 'orion', text: 'What does the basic insurance cover?' },
      { speaker: 'B', voice: 'luna', text: 'It covers damage to other cars. You can pay extra for full cover with no excess.' },
      { speaker: 'A', voice: 'orion', text: 'I think I will take full cover. I do not want to worry on holiday.' },
      { speaker: 'B', voice: 'luna', text: 'Good choice. Is there a second driver?' },
      { speaker: 'A', voice: 'orion', text: 'No, only me. I have got my driving licence and passport here.' },
      { speaker: 'B', voice: 'luna', text: 'Thank you. The fuel policy is full to full — you return the car with a full tank.' },
      { speaker: 'A', voice: 'orion', text: 'Understood. Is there a limit on kilometres?' },
      { speaker: 'B', voice: 'luna', text: 'You have unlimited kilometres on this rate. No extra charge for distance.' },
      { speaker: 'A', voice: 'orion', text: 'That is great. Where do I return the car?' },
      { speaker: 'B', voice: 'luna', text: 'You can return it here at the airport or at our city office — same price.' },
      { speaker: 'A', voice: 'orion', text: 'I will return it at the airport before my flight. What time do you open?' },
      { speaker: 'B', voice: 'luna', text: 'We open at six in the morning. Please arrive thirty minutes before your flight.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. How much is the total for five days?' },
      { speaker: 'B', voice: 'luna', text: 'With full insurance, the total is two hundred and forty euros. You pay now by card.' },
      { speaker: 'A', voice: 'orion', text: 'That is fine. Here is my card. Thank you for explaining everything clearly.' },
      { speaker: 'B', voice: 'luna', text: 'You are welcome. Here are your keys — car number 14 in bay B. Enjoy your trip!' },
    ],
    vocabulary: [
      { word: 'hire', translation: 'alquilar', example: 'I would like to hire a car for five days.' },
      { word: 'insurance', translation: 'seguro', example: 'It includes basic insurance.' },
      { word: 'excess', translation: 'franquicia', example: 'Full cover with no excess.' },
      { word: 'full to full', translation: 'lleno a lleno (combustible)', example: 'The fuel policy is full to full.' },
      { word: 'unlimited kilometres', translation: 'kilómetros ilimitados', example: 'You have unlimited kilometres on this rate.' },
      { word: 'return', translation: 'devolver', example: 'Where do I return the car?' },
    ],
    comprehensionQuestions: [
      {
        question: 'What kind of car does Tom want?',
        options: ['A large car', 'A small automatic car', 'A van', 'A motorbike'],
        correctIndex: 1,
        explanation: 'Tom says he needs a small car — automatic, if possible.',
      },
      {
        question: 'What is the fuel policy?',
        options: ['Empty to empty', 'Full to full', 'Pay for fuel at the end', 'Unlimited fuel included'],
        correctIndex: 1,
        explanation: 'Sara says: The fuel policy is full to full.',
      },
      {
        question: 'How much does Tom pay in total with full insurance?',
        options: ['€200', '€220', '€240', '€300'],
        correctIndex: 2,
        explanation: 'Sara says: With full insurance, the total is two hundred and forty euros.',
      },
    ],
  },
  {
    id: 'a1-gen-10m-007',
    level: 'A1',
    track: 'general',
    durationMinutes: 10,
    module: 4,
    title: 'A Healthy Week Plan',
    description: 'Planifica una semana saludable: comida, ejercicio, descanso y rutinas.',
    topic: 'healthy habits planning',
    audioUrl: '/audio/podcasts/a1/a1-gen-10m-007.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Sara, you said you want a healthier routine this month. Where do you want to start?' },
      { speaker: 'B', voice: 'luna', text: 'I want to start with simple habits: better sleep, more water, and regular exercise.' },
      { speaker: 'A', voice: 'orion', text: 'Excellent. What time do you usually go to bed now?' },
      { speaker: 'B', voice: 'luna', text: 'Too late, around midnight. I am going to try ten-thirty this week.' },
      { speaker: 'A', voice: 'orion', text: 'Good goal. How many hours of sleep do you need?' },
      { speaker: 'B', voice: 'luna', text: 'About seven or eight hours. When I sleep well, I feel calm and focused.' },
      { speaker: 'A', voice: 'orion', text: 'What about food? Any changes there?' },
      { speaker: 'B', voice: 'luna', text: 'Yes. I am going to cook at home from Monday to Friday and reduce fast food.' },
      { speaker: 'A', voice: 'orion', text: 'Do you have a weekly menu?' },
      { speaker: 'B', voice: 'luna', text: 'I do now: salads, grilled chicken, vegetable soup, and fruit for snacks.' },
      { speaker: 'A', voice: 'orion', text: 'Great. And exercise?' },
      { speaker: 'B', voice: 'luna', text: 'I am going to walk thirty minutes every day and do yoga twice a week.' },
      { speaker: 'A', voice: 'orion', text: 'That sounds realistic. Do you need a gym for that?' },
      { speaker: 'B', voice: 'luna', text: 'No, not really. I can walk outside and do yoga videos at home.' },
      { speaker: 'A', voice: 'orion', text: 'What can stop your plan?' },
      { speaker: 'B', voice: 'luna', text: 'Work stress and poor planning. If I finish work late, I usually choose unhealthy food.' },
      { speaker: 'A', voice: 'orion', text: 'How can you prepare for those busy days?' },
      { speaker: 'B', voice: 'luna', text: 'I can cook extra portions on Sunday and keep them in the fridge.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect strategy. And water intake?' },
      { speaker: 'B', voice: 'luna', text: 'I am going to carry a bottle and drink two litres a day.' },
      { speaker: 'A', voice: 'orion', text: 'Any screen-time goals before sleeping?' },
      { speaker: 'B', voice: 'luna', text: 'Yes. No phone thirty minutes before bed. I will read instead.' },
      { speaker: 'A', voice: 'orion', text: 'I like that. How will you track your progress?' },
      { speaker: 'B', voice: 'luna', text: 'I will use a simple checklist: sleep, water, food, and exercise each day.' },
      { speaker: 'A', voice: 'orion', text: 'At the end of the week, what is success for you?' },
      { speaker: 'B', voice: 'luna', text: 'If I follow the plan on five days, I will call it a success.' },
      { speaker: 'A', voice: 'orion', text: 'That is balanced and realistic. Small steps create big results.' },
      { speaker: 'B', voice: 'luna', text: 'Exactly. I do not need a perfect week, just a better one.' },
    ],
    vocabulary: [
      { word: 'habit', translation: 'hábito', example: 'I want to start with simple habits.' },
      { word: 'focused', translation: 'concentrado/a', example: 'When I sleep well, I feel focused.' },
      { word: 'weekly menu', translation: 'menú semanal', example: 'Do you have a weekly menu?' },
      { word: 'realistic', translation: 'realista', example: 'That sounds realistic.' },
      { word: 'intake', translation: 'ingesta', example: 'And water intake?' },
      { word: 'checklist', translation: 'lista de control', example: 'I will use a simple checklist.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What time is Sara going to try going to bed?',
        options: ['10:30', '11:30', '12:00', '9:30'],
        correctIndex: 0,
        explanation: 'Sara says she will try going to bed at ten-thirty.',
      },
      {
        question: 'How often is Sara going to do yoga?',
        options: ['Every day', 'Once a week', 'Twice a week', 'Only on weekends'],
        correctIndex: 2,
        explanation: 'She says she is going to do yoga twice a week.',
      },
      {
        question: 'How will Sara track her progress?',
        options: ['A mobile game', 'A simple checklist', 'A coach', 'A calendar app only'],
        correctIndex: 1,
        explanation: 'Sara says she will use a simple checklist each day.',
      },
    ],
  },
  {
    id: 'a1-pro-10m-004',
    level: 'A1',
    track: 'professional',
    durationMinutes: 10,
    module: 4,
    title: 'A Simple Client Call',
    description: 'Gestiona una llamada con cliente: objetivos, tiempos y próximos pasos.',
    topic: 'client communication basics',
    audioUrl: '/audio/podcasts/a1/a1-pro-10m-004.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Good afternoon, this is Tom from Bright Media. Am I speaking with Sara?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, speaking. Hello Tom, thanks for calling.' },
      { speaker: 'A', voice: 'orion', text: 'I am calling to discuss your website update. Is now a good time?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, I have about twenty minutes now.' },
      { speaker: 'A', voice: 'orion', text: 'Great. First, can you confirm your main goal for this update?' },
      { speaker: 'B', voice: 'luna', text: 'Our goal is to make the site easier to use on mobile phones.' },
      { speaker: 'A', voice: 'orion', text: 'Understood. Are there specific pages with problems?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, the booking page and the contact form are difficult on small screens.' },
      { speaker: 'A', voice: 'orion', text: 'Thanks, that is clear. Do you also want design changes or only technical fixes?' },
      { speaker: 'B', voice: 'luna', text: 'Both. We want a cleaner design and faster loading time.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. We can prepare two design options by next Tuesday.' },
      { speaker: 'B', voice: 'luna', text: 'Tuesday is fine. Can you also include a timeline for development?' },
      { speaker: 'A', voice: 'orion', text: 'Of course. After design approval, development should take about three weeks.' },
      { speaker: 'B', voice: 'luna', text: 'That works for us. We would like to launch before the end of next month.' },
      { speaker: 'A', voice: 'orion', text: 'Noted. Who will approve the final design on your side?' },
      { speaker: 'B', voice: 'luna', text: 'I will review first, then our director will give final approval.' },
      { speaker: 'A', voice: 'orion', text: 'Excellent. I will send a summary email after this call with action points.' },
      { speaker: 'B', voice: 'luna', text: 'Perfect, thank you. Please include estimated costs as well.' },
      { speaker: 'A', voice: 'orion', text: 'Yes, I will include a basic budget and two optional extras.' },
      { speaker: 'B', voice: 'luna', text: 'Great. This was very helpful. Thank you for your time, Tom.' },
      { speaker: 'A', voice: 'orion', text: 'My pleasure, Sara. Speak to you next Tuesday. Have a good day!' },
      { speaker: 'B', voice: 'luna', text: 'You too. Goodbye!' },
    ],
    vocabulary: [
      { word: 'main goal', translation: 'objetivo principal', example: 'Can you confirm your main goal?' },
      { word: 'update', translation: 'actualización', example: 'I am calling about your website update.' },
      { word: 'timeline', translation: 'cronograma', example: 'Include a timeline for development.' },
      { word: 'approval', translation: 'aprobación', example: 'Who will approve the final design?' },
      { word: 'action points', translation: 'puntos de acción', example: 'I will send a summary with action points.' },
      { word: 'estimated costs', translation: 'costes estimados', example: 'Please include estimated costs.' },
    ],
    comprehensionQuestions: [
      {
        question: 'What is the client’s main goal?',
        options: ['More blog posts', 'Better mobile usability', 'New office location', 'Hiring designers'],
        correctIndex: 1,
        explanation: 'Sara says the goal is to make the site easier on mobile phones.',
      },
      {
        question: 'When will Tom send design options?',
        options: ['Tomorrow', 'Next Tuesday', 'In three weeks', 'Next month'],
        correctIndex: 1,
        explanation: 'Tom says they can prepare two design options by next Tuesday.',
      },
      {
        question: 'What will Tom send after the call?',
        options: ['Only an invoice', 'A summary email with action points and budget', 'A contract', 'A final design'],
        correctIndex: 1,
        explanation: 'Tom confirms he will send a summary email and estimated costs.',
      },
    ],
  },
  {
    id: 'a1-tra-10m-004',
    level: 'A1',
    track: 'travel',
    durationMinutes: 10,
    module: 4,
    title: 'A Weekend City Break',
    description: 'Organiza una escapada: transporte, alojamiento, presupuesto y actividades.',
    topic: 'city break planning',
    audioUrl: '/audio/podcasts/a1/a1-tra-10m-004.mp3',
    transcript: [
      { speaker: 'A', voice: 'orion', text: 'Sara, are you free next weekend? I am thinking about a short city break.' },
      { speaker: 'B', voice: 'luna', text: 'Yes! That sounds great. Which city do you have in mind?' },
      { speaker: 'A', voice: 'orion', text: 'Maybe Valencia. It has beaches, good food, and nice weather.' },
      { speaker: 'B', voice: 'luna', text: 'Perfect choice. How do you want to travel — train or plane?' },
      { speaker: 'A', voice: 'orion', text: 'Train, I think. It is more comfortable and the station is in the city centre.' },
      { speaker: 'B', voice: 'luna', text: 'Good point. We can leave Friday evening and return Sunday night.' },
      { speaker: 'A', voice: 'orion', text: 'Great. What about accommodation?' },
      { speaker: 'B', voice: 'luna', text: 'I found a small hotel near the old town. Breakfast is included.' },
      { speaker: 'A', voice: 'orion', text: 'How much is it per night?' },
      { speaker: 'B', voice: 'luna', text: 'About ninety euros for a double room. Not bad for the location.' },
      { speaker: 'A', voice: 'orion', text: 'Sounds good. Let us set a total budget so we do not spend too much.' },
      { speaker: 'B', voice: 'luna', text: 'Agreed. Maybe three hundred euros each for transport, hotel, food, and activities.' },
      { speaker: 'A', voice: 'orion', text: 'What do you want to do there?' },
      { speaker: 'B', voice: 'luna', text: 'On Saturday morning, we can visit the City of Arts and Sciences.' },
      { speaker: 'A', voice: 'orion', text: 'Excellent. And in the afternoon?' },
      { speaker: 'B', voice: 'luna', text: 'Let us walk in the old town and try local paella for dinner.' },
      { speaker: 'A', voice: 'orion', text: 'Perfect. On Sunday, maybe the beach if the weather is good?' },
      { speaker: 'B', voice: 'luna', text: 'Yes, and we can rent bikes for an hour before going back to the station.' },
      { speaker: 'A', voice: 'orion', text: 'Do we need to book museum tickets in advance?' },
      { speaker: 'B', voice: 'luna', text: 'For some places, yes. I will book online tonight to avoid queues.' },
      { speaker: 'A', voice: 'orion', text: 'Great planning! I will book train tickets now.' },
      { speaker: 'B', voice: 'luna', text: 'And I will reserve the hotel. This trip is going to be amazing!' },
    ],
    vocabulary: [
      { word: 'city break', translation: 'escapada urbana', example: 'I am thinking about a short city break.' },
      { word: 'accommodation', translation: 'alojamiento', example: 'What about accommodation?' },
      { word: 'budget', translation: 'presupuesto', example: 'Let us set a total budget.' },
      { word: 'in advance', translation: 'con antelación', example: 'Do we need to book tickets in advance?' },
      { word: 'queue', translation: 'cola', example: 'Book online to avoid queues.' },
      { word: 'reserve', translation: 'reservar', example: 'I will reserve the hotel.' },
    ],
    comprehensionQuestions: [
      {
        question: 'How will they travel to Valencia?',
        options: ['By plane', 'By bus', 'By train', 'By car'],
        correctIndex: 2,
        explanation: 'Tom says they will travel by train.',
      },
      {
        question: 'How much is the hotel per night?',
        options: ['€60', '€75', '€90', '€120'],
        correctIndex: 2,
        explanation: 'Sara says the hotel is about ninety euros per night.',
      },
      {
        question: 'Why will Sara book some tickets online?',
        options: ['To save money only', 'To avoid queues', 'To get free transport', 'To change the schedule'],
        correctIndex: 1,
        explanation: 'Sara says she will book online to avoid queues.',
      },
    ],
  },
]
