-- Migration for ingles-c1
-- Generated on: 2026-02-10T17:03:47.976Z

BEGIN;

INSERT INTO public.course_modules (id, course_level, course_goal, order_index, title)
VALUES ('ingles-c1', 'C1', 'generic', 5, 'English C1 - Advanced')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, course_level = EXCLUDED.course_level;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-unit1', 'ingles-c1', 1, 'Advanced Emphasis and Focus', 60)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B1_I1', 'ingles-c1-unit1', 1, 'transformation', 'Reescribe la frase comenzando con la expresión negativa para dar énfasis (Inversion):', '{"prompt_es":"Reescribe la frase comenzando con la expresión negativa para dar énfasis (Inversion):","stimulus_en":"I have never seen such a beautiful sunset. (NEVER)","correct_answer":"Never have I seen such a beautiful sunset.","explanation":"When we start a sentence with a negative adverb like ''never'', we use question word order (auxiliary before subject).","concept_tags":["grammar","inversion","emphasis"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B1_I2', 'ingles-c1-unit1', 2, 'multiple_choice', 'Selecciona la opción gramaticalmente correcta:', '{"prompt_es":"Selecciona la opción gramaticalmente correcta:","options":[{"id":"o1","text":"Little he knew about the surprise waiting for him."},{"id":"o2","text":"Little did he know about the surprise waiting for him."},{"id":"o3","text":"Little he did know about the surprise waiting for him."}],"correct_answer":"o2","explanation":"''Little'' at the beginning of a sentence requires inversion of the auxiliary ''did''.","concept_tags":["grammar","inversion"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B2_I1', 'ingles-c1-unit1', 3, 'transformation', 'Transforma esta frase en una ''It-cleft'' para enfatizar al sujeto (John):', '{"prompt_es":"Transforma esta frase en una ''It-cleft'' para enfatizar al sujeto (John):","stimulus_en":"John broke the window.","correct_answer":"It was John who broke the window.","explanation":"An ''It-cleft'' structure is ''It + is/was + emphasized part + relative clause''.","concept_tags":["grammar","cleft-sentences","focus"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U1_B2_I2', 'ingles-c1-unit1', 4, 'fill_blanks', 'Completa la ''What-cleft'' para enfatizar la acción:', '{"prompt_es":"Completa la ''What-cleft'' para enfatizar la acción:","stimulus_en":"I need a long holiday. -> ________ I need is a long holiday.","correct_answer":"What","explanation":"A ''What-cleft'' (pseudo-cleft) uses a nominal relative clause to focus on a specific part of the sentence.","concept_tags":["grammar","cleft-sentences"],"complexity":3}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U2', 'ingles-c1', 2, 'Advanced Inversion', 60)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B1_I1', 'ingles-c1-U2', 1, 'fill_blanks', 'Fill in the blanks with the appropriate words to complete the sentences related to understanding implicit meanings in audio materials.', '{"prompt_es":"Fill in the blanks with the appropriate words to complete the sentences related to understanding implicit meanings in audio materials.","mastery_tag":"listening:c1-complex-audio","main_text":"Listeners must be able to (1)_____ the subtle cues in the speaker''s tone.\n\nInferences drawn from a complex audio can often lead to a deeper (2)_____ of the topic.\n\nThe ability to recognize (3)_____ in speech is crucial for effective communication.\n\nTo fully grasp the message, one must listen without (4)_____ to preconceived notions.\n\nEffective listening requires the ability to (5)_____ between the lines of the conversation.","correct_answer":["interpret","understanding","nuances","bias","read"],"explanation":"(1) La respuesta correcta es ''interpretar'', que se refiere a comprender o deducir algo a partir de pistas sutiles.\n(2) La respuesta correcta es ''comprensión'', que se refiere a la capacidad de captar matices complejos en la información.\n(3) La respuesta correcta es ''matices'', que se refiere a las diferencias sutiles que pueden cambiar el significado.\n(4) La respuesta correcta es ''sesgo'', que indica la necesidad de una mente abierta durante la escucha.\n(5) La respuesta correcta es ''leer'', que en este contexto significa interpretar significados no explícitos."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I1', 'ingles-c1-U2', 2, 'multiple_choice', 'What is considered crucial for effective leadership according to the audio?', '{"prompt_es":"What is considered crucial for effective leadership according to the audio?","mastery_tag":"listening:c1-complex-audio","explanation":"La inteligencia emocional se menciona como fundamental para la conexión con los equipos y la toma de decisiones efectivas.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Technical skills"},{"id":"o2","text":"Emotional intelligence"},{"id":"o3","text":"Experience"},{"id":"o4","text":"Authority"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I2', 'ingles-c1-U2', 3, 'multiple_choice', 'How should leaders adapt their styles according to the context discussed?', '{"prompt_es":"How should leaders adapt their styles according to the context discussed?","mastery_tag":"listening:c1-complex-audio","explanation":"Los líderes deben ser capaces de ajustar su estilo de liderazgo según las necesidades del equipo y el entorno.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Rigidly"},{"id":"o2","text":"Inflexibly"},{"id":"o3","text":"Dynamically"},{"id":"o4","text":"Casually"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I3', 'ingles-c1-U2', 4, 'multiple_choice', 'What impact does ethical decision-making have on a leader’s credibility?', '{"prompt_es":"What impact does ethical decision-making have on a leader’s credibility?","mastery_tag":"listening:c1-complex-audio","explanation":"La toma de decisiones éticas aumenta la credibilidad de un líder en los ojos de sus empleados.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"It diminishes it"},{"id":"o2","text":"It has no impact"},{"id":"o3","text":"It enhances it"},{"id":"o4","text":"It complicates it"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I4', 'ingles-c1-U2', 5, 'multiple_choice', 'Which of the following is implied as a disadvantage of authoritarian leadership?', '{"prompt_es":"Which of the following is implied as a disadvantage of authoritarian leadership?","mastery_tag":"listening:c1-complex-audio","explanation":"Se insinúa que el liderazgo autoritario puede llevar a una baja moral del equipo, ya que no fomenta la participación.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Clear communication"},{"id":"o2","text":"High respect"},{"id":"o3","text":"Low team morale"},{"id":"o4","text":"Fast decision-making"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B2_I5', 'ingles-c1-U2', 6, 'multiple_choice', 'According to the audio, what is a major reason leaders fail?', '{"prompt_es":"According to the audio, what is a major reason leaders fail?","mastery_tag":"listening:c1-complex-audio","explanation":"El audio sugiere que todos estos factores contribuyen al fracaso de los líderes en un entorno corporativo.","stimulus_en":"","main_text":"The audio discusses various perspectives on leadership styles in corporate settings, highlighting the importance of emotional intelligence, adaptability, and ethical decision-making.","options":[{"id":"o1","text":"Lack of vision"},{"id":"o2","text":"Poor communication skills"},{"id":"o3","text":"Inability to listen"},{"id":"o4","text":"All of the above"}],"correct_answer":"o4"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U2_B3_I1', 'ingles-c1-U2', 7, 'fill_blanks', 'Complete the sentences with the correct words related to public speaking.', '{"prompt_es":"Complete the sentences with the correct words related to public speaking.","mastery_tag":"speaking:c1-public-speaking","main_text":"Effective public speaking requires a clear (1)________ to guide the audience.\n\nUsing (2)________ can enhance your speech and engage your audience emotionally.\n\nTo manage speaking anxiety, practice (3)________ in front of an audience.\n\nA successful presentation often includes (4)________ to illustrate key points.\n\nTo connect with your audience, establish a sense of (5)________ at the beginning of your speech.","correct_answer":["structure","rhetoric","rehearsing","visuals","rapport"],"explanation":"(1) La ''estructura'' es esencial para que la presentación sea clara y fácil de seguir.\n(2) El ''rhetoric'' se refiere a los dispositivos de lenguaje que hacen que una presentación sea más persuasiva.\n(3) ''Rehearsing'' implica practicar tu discurso varias veces antes de la presentación real.\n(4) Los ''visuals'' como gráficos y diapositivas ayudan a clarificar y reforzar la información presentada.\n(5) El ''rapport'' se refiere a la relación de confianza y empatía que construyes con tu audiencia."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U3', 'ingles-c1', 3, 'Unit 3', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I1', 'ingles-c1-U3', 1, 'multiple_choice', 'What is the primary purpose of a thesis statement in an academic essay?', '{"prompt_es":"What is the primary purpose of a thesis statement in an academic essay?","mastery_tag":"writing:c1-academic-writing","explanation":"El propósito principal de una declaración de tesis es presentar la idea central que se argumentará en el ensayo.","stimulus_en":"","options":[{"id":"o1","text":"To summarize the essay"},{"id":"o2","text":"To introduce the topic"},{"id":"o3","text":"To present the main argument"},{"id":"o4","text":"To conclude the essay"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I2', 'ingles-c1-U3', 2, 'multiple_choice', 'Choose the correct answer for each question related to academic writing.', '{"prompt_es":"Choose the correct answer for each question related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"El lenguaje formal aporta credibilidad a la escritura académica, lo que es esencial en contextos académicos.","stimulus_en":"In academic writing, formal language is preferred over informal language because it...","options":[{"id":"o1","text":"is more entertaining"},{"id":"o2","text":"is easier to understand"},{"id":"o3","text":"adds credibility"},{"id":"o4","text":"is more concise"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I3', 'ingles-c1-U3', 3, 'multiple_choice', 'Which of the following is NOT a typical component of an academic report?', '{"prompt_es":"Which of the following is NOT a typical component of an academic report?","mastery_tag":"writing:c1-academic-writing","explanation":"Las opiniones personales no son componentes típicos de un informe académico ya que se basa en la evidencia y la investigación objetiva.","stimulus_en":"","options":[{"id":"o1","text":"Introduction"},{"id":"o2","text":"Methodology"},{"id":"o3","text":"Personal opinion"},{"id":"o4","text":"Conclusion"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I4', 'ingles-c1-U3', 4, 'multiple_choice', 'What is the use of citations in academic writing?', '{"prompt_es":"What is the use of citations in academic writing?","mastery_tag":"writing:c1-academic-writing","explanation":"Las citas se utilizan para respaldar afirmaciones con evidencia y para dar crédito a las fuentes originales.","stimulus_en":"","options":[{"id":"o1","text":"To provide personal experiences"},{"id":"o2","text":"To support claims with evidence"},{"id":"o3","text":"To make the text longer"},{"id":"o4","text":"To express personal views"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B1_I5', 'ingles-c1-U3', 5, 'multiple_choice', 'Why is it important to have a clear structure in an academic essay?', '{"prompt_es":"Why is it important to have a clear structure in an academic essay?","mastery_tag":"writing:c1-academic-writing","explanation":"Una estructura clara facilita la comprensión del argumento y la lógica del ensayo, lo cual es crucial en la escritura académica.","stimulus_en":"","options":[{"id":"o1","text":"It makes it more interesting"},{"id":"o2","text":"It helps the reader understand the argument"},{"id":"o3","text":"It allows for more personal expression"},{"id":"o4","text":"It can increase word count"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B2_I1', 'ingles-c1-U3', 6, 'fill_blanks', 'Fill in the blanks with the correct words to complete the sentences about proposals and evaluations.', '{"prompt_es":"Fill in the blanks with the correct words to complete the sentences about proposals and evaluations.","mastery_tag":"writing:c1-proposals","main_text":"1. When writing a proposal, it is essential to clearly define the (1)___ of the project, outlining its objectives and expected outcomes.\n2. A strong proposal often includes a detailed budget that justifies the (2)___ necessary to achieve the proposed goals.\n3. Evaluations should provide (3)___ feedback that highlights both strengths and weaknesses in the implementation of the project.\n4. It is advisable to use relevant data to support your (4)___, making your argument more persuasive.\n5. A well-crafted executive summary can significantly enhance a proposal by providing a concise (5)___ of the entire document.","correct_answer":["scope","resources","constructive","arguments","overview"],"explanation":"(1) La ''scope'' se refiere al alcance del proyecto, que es fundamental al redactar una propuesta.\n(2) Los ''resources'' son los recursos necesarios y deben estar claramente justificados en una propuesta sólida.\n(3) El feedback ''constructive'' es crucial para que las evaluaciones sean efectivas, ayudando a mejorar en el futuro.\n(4) Los ''arguments'' son fundamentales para una propuesta convincente, respaldados por datos relevantes.\n(5) Un ''overview'' es un resumen que permite comprender rápidamente el contenido del documento completo."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U3_B3_I1', 'ingles-c1-U3', 7, 'word_formation', 'Complete the sentences by transforming the base words into the correct forms.', '{"prompt_es":"Complete the sentences by transforming the base words into the correct forms.","mastery_tag":"vocabulary:c1-academic","main_text":"In academic writing, it is essential to maintain a high level of professionalism and (1)___ (ACCURATE) while presenting your findings. A thorough (2)___ (ANALYZE) of the data can lead to significant (3)___ (IMPROVE) in your research quality. Many scholars argue that a strong theoretical (4)___ (FOUND) is necessary for any (5)___ (DISCUSS) in the field.","correct_answer":["ACCURACY","ANALYSIS","IMPROVEMENTS","FOUNDATION","DISCUSSION"],"example":"ACCURATE, ANALYZE, IMPROVE, FOUND, DISCUSS","explanation":"(1) La palabra ''exactitud'' es el sustantivo que se forma a partir del adjetivo ''preciso''.\n(2) Aquí, ''análisis'' es el sustantivo correspondiente al verbo ''analizar''.\n(3) Se necesita el sustantivo plural ''mejoras'', derivado del verbo ''mejorar''.\n(4) El sustantivo ''fundación'' se forma a partir del verbo ''fundar''.\n(5) Aquí, ''discusión'' es el sustantivo relacionado con el verbo ''discutir''."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U4', 'ingles-c1', 4, 'Unit 4', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B1_I1', 'ingles-c1-U4', 1, 'word_formation', 'Fill in the blanks with the correct form of the word provided.', '{"prompt_es":"Fill in the blanks with the correct form of the word provided.","mastery_tag":"vocabulary:c1-academic","main_text":"The (1)___ of the study showed significant results. The researchers conducted a thorough (2)___ to support their (3)___ about the effects of climate change. This (4)___ helps to understand the complex relationships in environmental science. Future (5)___ will focus on expanding this research.","correct_answer":["ANALYSIS","INVESTIGATION","THEORY","CONTRIBUTION","STUDIES"],"example":"ANALYZE, INVESTIGATE, THEORIZE, CONTRIBUTE, STUDY","explanation":"(1) undefined\n(2) undefined\n(3) undefined\n(4) undefined\n(5) undefined"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B2_I1', 'ingles-c1-U4', 2, 'word_formation', 'Fill in the gaps with the correct form of the word provided in parentheses.', '{"prompt_es":"Fill in the gaps with the correct form of the word provided in parentheses.","mastery_tag":"vocabulary:c1-nuanced","main_text":"Effective communication often requires a deep understanding of (1)___ (NUANCE) in language. To express (2)___ (PRECISE) thoughts, one must choose words with care. A word’s (3)___ (CONNOTATE) can change its meaning entirely, making it essential to grasp subtleties. Moreover, (4)___ (SOPHISTICATE) language can enhance the (5)___ (EFFECT) of a message when used appropriately.","correct_answer":["NUANCES","PRECISION","CONNOTATION","SOPHISTICATION","EFFECTIVENESS"],"example":"NUANCE, PRECISE, CONNOTATE, SOPHISTICATE, EFFECT","explanation":"(1) undefined\n(2) undefined\n(3) undefined\n(4) undefined\n(5) undefined"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I1', 'ingles-c1-U4', 3, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Es importante que las conversaciones tengan un flujo natural para involucrar al oyente.","stimulus_en":"It''s important to maintain a sense of ___ during conversations to engage your listener.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"flow"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I2', 'ingles-c1-U4', 4, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Usar expresiones idiomáticas y coloquialismos hace que suene más natural.","stimulus_en":"To sound more ___, try using idiomatic expressions and colloquialisms.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"natural"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I3', 'ingles-c1-U4', 5, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"El feedback verbal ayuda a mostrar que estás atento y comprometido en la conversación.","stimulus_en":"Active listening involves providing ___ feedback to your conversation partner.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"verbal"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I4', 'ingles-c1-U4', 6, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Los gestos apropiados ayudan a ilustrar tus puntos y mantener la atención del oyente.","stimulus_en":"Using appropriate ___ can help clarify your points and maintain engagement.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"gestures"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U4_B3_I5', 'ingles-c1-U4', 7, 'fill_blanks', 'Complete the sentences with the appropriate words.', '{"prompt_es":"Complete the sentences with the appropriate words.","mastery_tag":"speaking:c1-fluent-interaction","explanation":"Una pausa puede ser útil para que pienses en lo que quieres decir a continuación.","stimulus_en":"A pause in conversation can be a powerful ___ to reflect on your thoughts.","main_text":"Fill in the blanks with suitable words to enhance fluent interaction in conversations.","correct_answer":"tool"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U5', 'ingles-c1', 5, 'Unit 5', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I1', 'ingles-c1-U5', 1, 'multiple_choice', 'What does ''to walk on eggshells'' mean?', '{"prompt_es":"What does ''to walk on eggshells'' mean?","mastery_tag":"vocabulary:c1-nuanced","explanation":"La expresión significa ser muy cuidadoso en una situación delicada.","stimulus_en":"","options":[{"id":"o1","text":"To be careful"},{"id":"o2","text":"To change direction"},{"id":"o3","text":"To act quickly"},{"id":"o4","text":"To be energetic"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I2', 'ingles-c1-U5', 2, 'multiple_choice', 'What does ''the elephant in the room'' refer to?', '{"prompt_es":"What does ''the elephant in the room'' refer to?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Se refiere a un problema obvio que todos evitan discutir.","stimulus_en":"","options":[{"id":"o1","text":"A big distraction"},{"id":"o2","text":"An obvious problem"},{"id":"o3","text":"A surprising idea"},{"id":"o4","text":"A heavy topic"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I3', 'ingles-c1-U5', 3, 'multiple_choice', 'What does ''to throw someone under the bus'' imply?', '{"prompt_es":"What does ''to throw someone under the bus'' imply?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Significa traicionar a alguien, generalmente para salvarse a sí mismo.","stimulus_en":"","options":[{"id":"o1","text":"To help someone"},{"id":"o2","text":"To betray someone"},{"id":"o3","text":"To support someone"},{"id":"o4","text":"To confuse someone"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I4', 'ingles-c1-U5', 4, 'multiple_choice', 'What does ''to read between the lines'' suggest?', '{"prompt_es":"What does ''to read between the lines'' suggest?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Se refiere a captar significados que no son explícitos.","stimulus_en":"","options":[{"id":"o1","text":"To read carefully"},{"id":"o2","text":"To understand the hidden meaning"},{"id":"o3","text":"To read fast"},{"id":"o4","text":"To ignore details"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B1_I5', 'ingles-c1-U5', 5, 'multiple_choice', 'What does ''to beat around the bush'' mean?', '{"prompt_es":"What does ''to beat around the bush'' mean?","mastery_tag":"vocabulary:c1-nuanced","explanation":"Implica no abordar el tema principal de manera directa.","stimulus_en":"","options":[{"id":"o1","text":"To be direct"},{"id":"o2","text":"To avoid getting to the point"},{"id":"o3","text":"To speak quickly"},{"id":"o4","text":"To explain clearly"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B2_I1', 'ingles-c1-U5', 6, 'word_formation', 'Complete the sentences by forming the correct word from the base provided.', '{"prompt_es":"Complete the sentences by forming the correct word from the base provided.","mastery_tag":"vocabulary:c1-culture-arts","main_text":"The study of culture and the arts encompasses various fields, each rich in (1)___ (SIGNIFY). Understanding the significance of (2)___ (CRITIC) is essential for appreciating art. The (3)___ (EXPRESS) of emotions through different mediums can lead to profound experiences. (4)___ (INFLUENCE) from historical context often shapes artistic movements. Finally, the (5)___ (CREATE) process is at the heart of artistic innovation.","correct_answer":["SIGNIFICANCE","CRITICISM","EXPRESSION","INFLUENCES","CREATIVE"],"example":"SIGNIFY, CRITIC, EXPRESS, INFLUENCE, CREATE","explanation":"(1) La palabra ''significance'' se refiere a la importancia o el significado de algo, especialmente en el contexto de la cultura.\n(2) El término ''criticism'' se utiliza para hablar de la evaluación o juicio de una obra de arte.\n(3) La palabra ''expression'' se refiere a la manifestación de emociones o ideas a través del arte.\n(4) La forma plural ''influences'' se refiere a los diversos factores que afectan el desarrollo artístico.\n(5) El término ''creative'' describe la capacidad de generar nuevas ideas o conceptos, esencial en el arte."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U5_B3_I1', 'ingles-c1-U5', 7, 'fill_blanks', 'Complete the sentences with the most appropriate word or phrase.', '{"prompt_es":"Complete the sentences with the most appropriate word or phrase.","mastery_tag":"speaking:c1-fluent-interaction","main_text":"In conversations, it is essential to express ideas clearly and (1)___. Good communication involves not just speaking, but also (2)___. When engaging in dialogue, be attentive to the other person''s (3)___ and adjust your responses accordingly. Spontaneous reactions often add (4)___ to discussions, making them more engaging. In a fluent interaction, both parties should feel (5)___ to share their opinions openly.","correct_answer":["coherently","listening","body language","dynamism","comfortable"],"explanation":"(1) Es importante que las ideas se expresen de manera clara y coherente para una buena comunicación.\n(2) La buena comunicación no se trata solo de hablar, sino también de escuchar a los demás.\n(3) El lenguaje corporal de la otra persona puede ayudar a entender mejor la conversación.\n(4) Las reacciones espontáneas pueden dar energía y dinamismo a las discusiones.\n(5) Es fundamental que ambas partes se sientan cómodas para poder intercambiar opiniones."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U6', 'ingles-c1', 6, 'Unit 6', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B1_I1', 'ingles-c1-U6', 1, 'multiple_choice', 'Choose the correct option to complete each sentence related to academic writing.', '{"prompt_es":"Choose the correct option to complete each sentence related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"En los ensayos académicos, se espera que el tono sea objetivo y profesional.","stimulus_en":"In academic essays, it is essential to maintain a tone that is _______.","options":[{"id":"o1","text":"formal"},{"id":"o2","text":"casual"},{"id":"o3","text":"colloquial"},{"id":"o4","text":"emotional"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B1_I2', 'ingles-c1-U6', 2, 'multiple_choice', 'Choose the correct option to complete each sentence related to academic writing.', '{"prompt_es":"Choose the correct option to complete each sentence related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"Una declaración de tesis clara es fundamental para guiar el ensayo.","stimulus_en":"A well-structured essay should begin with a clear _______.","options":[{"id":"o1","text":"thesis statement"},{"id":"o2","text":"summary"},{"id":"o3","text":"conclusion"},{"id":"o4","text":"review"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B1_I3', 'ingles-c1-U6', 3, 'multiple_choice', 'Choose the correct option to complete each sentence related to academic writing.', '{"prompt_es":"Choose the correct option to complete each sentence related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"Revisar la literatura relevante ayuda a situar la investigación en un contexto adecuado.","stimulus_en":"It is important to _______ relevant literature when conducting research.","options":[{"id":"o1","text":"review"},{"id":"o2","text":"ignore"},{"id":"o3","text":"summarize"},{"id":"o4","text":"doubt"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B1_I4', 'ingles-c1-U6', 4, 'multiple_choice', 'Choose the correct option to complete each sentence related to academic writing.', '{"prompt_es":"Choose the correct option to complete each sentence related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"El resumen (abstract) debe ofrecer una visión general clara del trabajo académico.","stimulus_en":"The _______ of an academic paper provides a concise summary of its content.","options":[{"id":"o1","text":"abstract"},{"id":"o2","text":"conclusion"},{"id":"o3","text":"introduction"},{"id":"o4","text":"chapter"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B1_I5', 'ingles-c1-U6', 5, 'multiple_choice', 'Choose the correct option to complete each sentence related to academic writing.', '{"prompt_es":"Choose the correct option to complete each sentence related to academic writing.","mastery_tag":"writing:c1-academic-writing","explanation":"Las citas son necesarias para dar crédito a las fuentes y evitar el plagio.","stimulus_en":"Citations are crucial in academic writing to avoid _______.","options":[{"id":"o1","text":"plagiarism"},{"id":"o2","text":"innovation"},{"id":"o3","text":"clarity"},{"id":"o4","text":"credibility"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B2_I1', 'ingles-c1-U6', 6, 'multiple_choice_cloze', 'Choose the correct word to fill in the blanks from the options provided.', '{"prompt_es":"Choose the correct word to fill in the blanks from the options provided.","mastery_tag":"reading:c1-abstract-texts","main_text":"In contemporary discussions, the (1)[GAP 1] of reality often diverges from traditional notions. Philosophers argue that abstract (2)[GAP 2] can sometimes provide more insight than empirical evidence. Furthermore, the interplay between (3)[GAP 3] and metaphor in language allows us to explore complex ideas more readily. The (4)[GAP 4] of meaning often lies in the nuances that are easily overlooked. Ultimately, engaging with these (5)[GAP 5] is essential for a comprehensive understanding of philosophical discourse.","gaps":[{"id":"1","options":[{"id":"o1","text":"interpretation"},{"id":"o2","text":"sensation"},{"id":"o3","text":"manifestation"},{"id":"o4","text":"revelation"}]},{"id":"2","options":[{"id":"o1","text":"theories"},{"id":"o2","text":"experiments"},{"id":"o3","text":"practices"},{"id":"o4","text":"observations"}]},{"id":"3","options":[{"id":"o1","text":"logic"},{"id":"o2","text":"syntax"},{"id":"o3","text":"semantics"},{"id":"o4","text":"grammar"}]},{"id":"4","options":[{"id":"o1","text":"essence"},{"id":"o2","text":"surface"},{"id":"o3","text":"simplicity"},{"id":"o4","text":"clarity"}]},{"id":"5","options":[{"id":"o1","text":"constructs"},{"id":"o2","text":"models"},{"id":"o3","text":"methods"},{"id":"o4","text":"definitions"}]}],"correct_answer":{"1":"o1","2":"o1","3":"o3","4":"o1","5":"o1"},"explanation":"(1) La interpretación de la realidad es un concepto clave en filosofía que se aleja de las nociones tradicionales.\n(2) Las teorías abstractas a menudo ofrecen perspectivas más profundas que la evidencia empírica.\n(3) La semántica se refiere al estudio del significado, que es crucial para entender conceptos complejos.\n(4) La esencia del significado se encuentra en los matices, elementos que frecuentemente se pasan por alto.\n(5) Los constructos abstractos son fundamentales para comprender el discurso filosófico en su totalidad."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B3_I1', 'ingles-c1-U6', 7, 'multiple_choice', 'What is the primary goal of a persuasive speech?', '{"prompt_es":"What is the primary goal of a persuasive speech?","mastery_tag":"speaking:c1-public-speaking","explanation":"El objetivo principal de un discurso persuasivo es convencer a la audiencia de un punto de vista o acción.","stimulus_en":"","options":[{"id":"o1","text":"To inform the audience"},{"id":"o2","text":"To entertain the audience"},{"id":"o3","text":"To convince the audience"},{"id":"o4","text":"To describe a process"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B3_I2', 'ingles-c1-U6', 8, 'multiple_choice', 'Which technique is NOT commonly used in effective public speaking?', '{"prompt_es":"Which technique is NOT commonly used in effective public speaking?","mastery_tag":"speaking:c1-public-speaking","explanation":"El uso de gestos exagerados puede distraer en lugar de ayudar a transmitir el mensaje.","stimulus_en":"","options":[{"id":"o1","text":"Use of anecdotes"},{"id":"o2","text":"Exaggerated gestures"},{"id":"o3","text":"Clear structure"},{"id":"o4","text":"Rhetorical questions"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B3_I3', 'ingles-c1-U6', 9, 'multiple_choice', 'How can a speaker effectively manage audience questions?', '{"prompt_es":"How can a speaker effectively manage audience questions?","mastery_tag":"speaking:c1-public-speaking","explanation":"Prepararse para las preguntas ayuda a manejar la conversación y demuestra dominio del tema.","stimulus_en":"","options":[{"id":"o1","text":"Ignore them"},{"id":"o2","text":"Answer only the easy ones"},{"id":"o3","text":"Prepare for questions in advance"},{"id":"o4","text":"Avoid questions entirely"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B3_I4', 'ingles-c1-U6', 10, 'multiple_choice', 'What is an essential part of a well-structured presentation?', '{"prompt_es":"What is an essential part of a well-structured presentation?","mastery_tag":"speaking:c1-public-speaking","explanation":"Puntos principales claros son fundamentales para guiar a la audiencia a través de la presentación.","stimulus_en":"","options":[{"id":"o1","text":"A long introduction"},{"id":"o2","text":"Clear main points"},{"id":"o3","text":"Complex vocabulary"},{"id":"o4","text":"A summary only"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U6_B3_I5', 'ingles-c1-U6', 11, 'multiple_choice', 'Which of these is a vital characteristic of effective rhetoric?', '{"prompt_es":"Which of these is a vital characteristic of effective rhetoric?","mastery_tag":"speaking:c1-public-speaking","explanation":"La repetición es una técnica retórica eficaz que ayuda a enfatizar ideas importantes y a mejorar la retención.","stimulus_en":"","options":[{"id":"o1","text":"Ambiguity"},{"id":"o2","text":"Repetition"},{"id":"o3","text":"Monotony"},{"id":"o4","text":"Complexity"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U7', 'ingles-c1', 7, 'Unit 7', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B1_I1', 'ingles-c1-U7', 1, 'multiple_choice', 'What is the primary focus of contemporary literature as mentioned in the passage?', '{"prompt_es":"What is the primary focus of contemporary literature as mentioned in the passage?","mastery_tag":"reading:c1-complex-literature","explanation":"El pasaje enfatiza que la literatura contemporánea fusiona las estructuras narrativas tradicionales con formatos fragmentados.","stimulus_en":"In contemporary literature, the fusion of traditional narrative structures with fragmented formats can create a rich tapestry of meaning. Writers often employ experimental styles, challenging readers to engage more critically with texts. For instance, authors like Virginia Woolf and James Joyce exemplify this approach, weaving their characters’ inner thoughts with the external world in a seamless manner. Furthermore, this stylistic evolution reflects broader societal shifts, as narratives now often intersect with themes of identity, memory, and reality. The complexity of such texts demands not only comprehension but also a nuanced interpretation, as readers navigate through layers of symbolism and ambiguity. Thus, modern literature serves as both a mirror and a lens, reflecting the intricate dynamics of human experience while simultaneously urging deeper engagement with the literary form.","options":[{"id":"o1","text":"Traditional narratives"},{"id":"o2","text":"Fragmented formats"},{"id":"o3","text":"Simple storytelling"},{"id":"o4","text":"Clear structures"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B1_I2', 'ingles-c1-U7', 2, 'multiple_choice', 'Which authors are cited as examples of employing experimental styles?', '{"prompt_es":"Which authors are cited as examples of employing experimental styles?","mastery_tag":"reading:c1-complex-literature","explanation":"El pasaje menciona específicamente a Virginia Woolf y James Joyce como ejemplos de escritores que utilizan estilos experimentales.","stimulus_en":"In contemporary literature, the fusion of traditional narrative structures with fragmented formats can create a rich tapestry of meaning. Writers often employ experimental styles, challenging readers to engage more critically with texts. For instance, authors like Virginia Woolf and James Joyce exemplify this approach, weaving their characters’ inner thoughts with the external world in a seamless manner. Furthermore, this stylistic evolution reflects broader societal shifts, as narratives now often intersect with themes of identity, memory, and reality. The complexity of such texts demands not only comprehension but also a nuanced interpretation, as readers navigate through layers of symbolism and ambiguity. Thus, modern literature serves as both a mirror and a lens, reflecting the intricate dynamics of human experience while simultaneously urging deeper engagement with the literary form.","options":[{"id":"o1","text":"Ernest Hemingway and F. Scott Fitzgerald"},{"id":"o2","text":"Virginia Woolf and James Joyce"},{"id":"o3","text":"Mark Twain and Nathaniel Hawthorne"},{"id":"o4","text":"Charles Dickens and Leo Tolstoy"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B1_I3', 'ingles-c1-U7', 3, 'multiple_choice', 'According to the passage, what elements do modern narratives often intersect with?', '{"prompt_es":"According to the passage, what elements do modern narratives often intersect with?","mastery_tag":"reading:c1-complex-literature","explanation":"Se menciona que las narrativas modernas a menudo se entrelazan con temas de identidad, memoria y realidad.","stimulus_en":"In contemporary literature, the fusion of traditional narrative structures with fragmented formats can create a rich tapestry of meaning. Writers often employ experimental styles, challenging readers to engage more critically with texts. For instance, authors like Virginia Woolf and James Joyce exemplify this approach, weaving their characters’ inner thoughts with the external world in a seamless manner. Furthermore, this stylistic evolution reflects broader societal shifts, as narratives now often intersect with themes of identity, memory, and reality. The complexity of such texts demands not only comprehension but also a nuanced interpretation, as readers navigate through layers of symbolism and ambiguity. Thus, modern literature serves as both a mirror and a lens, reflecting the intricate dynamics of human experience while simultaneously urging deeper engagement with the literary form.","options":[{"id":"o1","text":"Adventure and mystery"},{"id":"o2","text":"Themes of identity, memory, and reality"},{"id":"o3","text":"Historical events"},{"id":"o4","text":"Science and technology"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B1_I4', 'ingles-c1-U7', 4, 'multiple_choice', 'What does the passage suggest about the demands placed on readers of complex literature?', '{"prompt_es":"What does the passage suggest about the demands placed on readers of complex literature?","mastery_tag":"reading:c1-complex-literature","explanation":"El pasaje indica que la complejidad de dichos textos requiere que los lectores se involucren de manera crítica.","stimulus_en":"In contemporary literature, the fusion of traditional narrative structures with fragmented formats can create a rich tapestry of meaning. Writers often employ experimental styles, challenging readers to engage more critically with texts. For instance, authors like Virginia Woolf and James Joyce exemplify this approach, weaving their characters’ inner thoughts with the external world in a seamless manner. Furthermore, this stylistic evolution reflects broader societal shifts, as narratives now often intersect with themes of identity, memory, and reality. The complexity of such texts demands not only comprehension but also a nuanced interpretation, as readers navigate through layers of symbolism and ambiguity. Thus, modern literature serves as both a mirror and a lens, reflecting the intricate dynamics of human experience while simultaneously urging deeper engagement with the literary form.","options":[{"id":"o1","text":"Readers can read passively"},{"id":"o2","text":"Readers must engage critically"},{"id":"o3","text":"Readers need to finish quickly"},{"id":"o4","text":"Readers should avoid deep interpretation"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B1_I5', 'ingles-c1-U7', 5, 'multiple_choice', 'What metaphor is used to describe the role of modern literature in relation to human experience?', '{"prompt_es":"What metaphor is used to describe the role of modern literature in relation to human experience?","mastery_tag":"reading:c1-complex-literature","explanation":"Se menciona que la literatura moderna funciona como un espejo y una lente, reflejando y enfocando la experiencia humana.","stimulus_en":"In contemporary literature, the fusion of traditional narrative structures with fragmented formats can create a rich tapestry of meaning. Writers often employ experimental styles, challenging readers to engage more critically with texts. For instance, authors like Virginia Woolf and James Joyce exemplify this approach, weaving their characters’ inner thoughts with the external world in a seamless manner. Furthermore, this stylistic evolution reflects broader societal shifts, as narratives now often intersect with themes of identity, memory, and reality. The complexity of such texts demands not only comprehension but also a nuanced interpretation, as readers navigate through layers of symbolism and ambiguity. Thus, modern literature serves as both a mirror and a lens, reflecting the intricate dynamics of human experience while simultaneously urging deeper engagement with the literary form.","options":[{"id":"o1","text":"A book and a reader"},{"id":"o2","text":"A mirror and a lens"},{"id":"o3","text":"A window and a door"},{"id":"o4","text":"A path and a map"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B2_I1', 'ingles-c1-U7', 6, 'multiple_choice', 'Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.', '{"prompt_es":"Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.","mastery_tag":"grammar:c1-ellipsis","explanation":"En esta oración, ''does'' se usa para evitar repetir ''enjoys'', que es la acción que ambos disfrutan.","stimulus_en":"He enjoys tea; she ___ coffee.","options":[{"id":"o1","text":"enjoys"},{"id":"o2","text":"does"},{"id":"o3","text":"drinks"},{"id":"o4","text":"likes"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B2_I2', 'ingles-c1-U7', 7, 'multiple_choice', 'Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.', '{"prompt_es":"Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.","mastery_tag":"grammar:c1-ellipsis","explanation":"Aquí, ''do'' sustituye ''prefer math'', evitando la repetición.","stimulus_en":"Some students prefer math; others, ___ science.","options":[{"id":"o1","text":"prefer"},{"id":"o2","text":"do"},{"id":"o3","text":"like"},{"id":"o4","text":"enjoy"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B2_I3', 'ingles-c1-U7', 8, 'multiple_choice', 'Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.', '{"prompt_es":"Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.","mastery_tag":"grammar:c1-ellipsis","explanation":"La omisión de ''am'' en ''I am tired'' es un ejemplo de elipsis que se entiende en el contexto.","stimulus_en":"I could go to the party, but I might stay home instead. I ___ tired.","options":[{"id":"o1","text":"am"},{"id":"o2","text":"feel"},{"id":"o3","text":"may be"},{"id":"o4","text":"seem"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B2_I4', 'ingles-c1-U7', 9, 'multiple_choice', 'Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.', '{"prompt_es":"Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.","mastery_tag":"grammar:c1-ellipsis","explanation":"''Does'' se utiliza para evitar repetir ''wants to travel'', lo que muestra la elipsis.","stimulus_en":"He wants to travel, and so ___ she.","options":[{"id":"o1","text":"do"},{"id":"o2","text":"is"},{"id":"o3","text":"does"},{"id":"o4","text":"wants"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B2_I5', 'ingles-c1-U7', 10, 'multiple_choice', 'Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.', '{"prompt_es":"Choose the correct option that best completes the sentence, focusing on ellipsis and substitution.","mastery_tag":"grammar:c1-ellipsis","explanation":"''Will'' es la forma que sustituye ''will finish the report'', mostrando una omisión correcta.","stimulus_en":"Either you finish the report today, or I ___ it myself.","options":[{"id":"o1","text":"do"},{"id":"o2","text":"will"},{"id":"o3","text":"complete"},{"id":"o4","text":"make"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B3_I1', 'ingles-c1-U7', 11, 'multiple_choice', 'What is the primary purpose of a proposal in a professional context?', '{"prompt_es":"What is the primary purpose of a proposal in a professional context?","mastery_tag":"writing:c1-proposals","explanation":"En un contexto profesional, el propósito principal de una propuesta es delinear un plan o un enfoque para un proyecto o idea.","stimulus_en":"","options":[{"id":"o1","text":"To request funding"},{"id":"o2","text":"To outline a plan"},{"id":"o3","text":"To summarize a project"},{"id":"o4","text":"To criticize a process"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B3_I2', 'ingles-c1-U7', 12, 'multiple_choice', 'Which element is crucial for evaluating a proposal?', '{"prompt_es":"Which element is crucial for evaluating a proposal?","mastery_tag":"writing:c1-proposals","explanation":"Una evaluación efectiva de una propuesta debe incluir un análisis de costo-beneficio para determinar su viabilidad.","stimulus_en":"","options":[{"id":"o1","text":"Personal opinions"},{"id":"o2","text":"Historical data"},{"id":"o3","text":"Cost-benefit analysis"},{"id":"o4","text":"Emotional appeals"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B3_I3', 'ingles-c1-U7', 13, 'multiple_choice', 'How should recommendations be presented in a proposal?', '{"prompt_es":"How should recommendations be presented in a proposal?","mastery_tag":"writing:c1-proposals","explanation":"Las recomendaciones en una propuesta deben presentarse de manera clara y segura para que el lector comprenda su importancia.","stimulus_en":"","options":[{"id":"o1","text":"As optional suggestions"},{"id":"o2","text":"In a vague manner"},{"id":"o3","text":"Clearly and confidently"},{"id":"o4","text":"With extensive technical jargon"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B3_I4', 'ingles-c1-U7', 14, 'multiple_choice', 'What is a common mistake when writing proposals?', '{"prompt_es":"What is a common mistake when writing proposals?","mastery_tag":"writing:c1-proposals","explanation":"Un error común al redactar propuestas es no incluir un resumen ejecutivo, que proporciona una visión general clara del documento.","stimulus_en":"","options":[{"id":"o1","text":"Not including an executive summary"},{"id":"o2","text":"Using bullet points"},{"id":"o3","text":"Writing in the first person"},{"id":"o4","text":"Including too many visuals"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U7_B3_I5', 'ingles-c1-U7', 15, 'multiple_choice', 'When evaluating a proposal, which factor is least important?', '{"prompt_es":"When evaluating a proposal, which factor is least important?","mastery_tag":"writing:c1-proposals","explanation":"Las relaciones personales pueden influir, pero no son un factor determinante en la evaluación objetiva de una propuesta.","stimulus_en":"","options":[{"id":"o1","text":"Feasibility"},{"id":"o2","text":"Budget"},{"id":"o3","text":"Personal relationships"},{"id":"o4","text":"Expected outcomes"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U8', 'ingles-c1', 8, 'Unit 8', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B1_I1', 'ingles-c1-U8', 1, 'multiple_choice', 'What is the main purpose of the introduction in a presentation?', '{"prompt_es":"What is the main purpose of the introduction in a presentation?","mastery_tag":"speaking:c1-public-speaking","explanation":"La introducción tiene como objetivo captar la atención del público y establecer el tono de la presentación.","stimulus_en":"","options":[{"id":"o1","text":"To summarize"},{"id":"o2","text":"To engage the audience"},{"id":"o3","text":"To conclude"},{"id":"o4","text":"To provide examples"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B1_I2', 'ingles-c1-U8', 2, 'multiple_choice', 'Which rhetorical device is used to appeal to the audience''s emotions?', '{"prompt_es":"Which rhetorical device is used to appeal to the audience''s emotions?","mastery_tag":"speaking:c1-public-speaking","explanation":"Pathos se refiere a apelar a las emociones del público para hacer una conexión más profunda.","stimulus_en":"","options":[{"id":"o1","text":"Logos"},{"id":"o2","text":"Pathos"},{"id":"o3","text":"Ethos"},{"id":"o4","text":"Chronos"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B1_I3', 'ingles-c1-U8', 3, 'multiple_choice', 'What is a key characteristic of effective body language during a presentation?', '{"prompt_es":"What is a key characteristic of effective body language during a presentation?","mastery_tag":"speaking:c1-public-speaking","explanation":"Los gestos abiertos transmiten confianza y ayudan a conectar con la audiencia.","stimulus_en":"","options":[{"id":"o1","text":"Avoiding eye contact"},{"id":"o2","text":"Open gestures"},{"id":"o3","text":"Standing still"},{"id":"o4","text":"Crossed arms"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B1_I4', 'ingles-c1-U8', 4, 'multiple_choice', 'How should a speaker handle questions from the audience?', '{"prompt_es":"How should a speaker handle questions from the audience?","mastery_tag":"speaking:c1-public-speaking","explanation":"Hacer una pausa y escuchar demuestra respeto por la opinión del público y mejora la interacción.","stimulus_en":"","options":[{"id":"o1","text":"Ignore them"},{"id":"o2","text":"Answer quickly"},{"id":"o3","text":"Pause and listen"},{"id":"o4","text":"Redirect to another topic"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B1_I5', 'ingles-c1-U8', 5, 'multiple_choice', 'What is the purpose of using visual aids in a presentation?', '{"prompt_es":"What is the purpose of using visual aids in a presentation?","mastery_tag":"speaking:c1-public-speaking","explanation":"Las ayudas visuales deben complementar el contenido y hacer que los puntos clave sean más claros.","stimulus_en":"","options":[{"id":"o1","text":"To distract the audience"},{"id":"o2","text":"To support key points"},{"id":"o3","text":"To fill time"},{"id":"o4","text":"To look professional"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B2_I1', 'ingles-c1-U8', 6, 'multiple_choice', 'Choose the best option that completes each sentence with the most appropriate nuanced expression.', '{"prompt_es":"Choose the best option that completes each sentence with the most appropriate nuanced expression.","mastery_tag":"vocabulary:c1-nuanced","explanation":"En la comunicación profesional, una ''concesión'' implica un reconocimiento que puede ser sutil en su impacto.","stimulus_en":"In professional communication, a ''concession'' often implies a ___ that can be subtle in its impact.","options":[{"id":"o1","text":"favor"},{"id":"o2","text":"warning"},{"id":"o3","text":"acknowledgment"},{"id":"o4","text":"complaint"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B2_I2', 'ingles-c1-U8', 7, 'multiple_choice', 'Choose the best option that completes each sentence with the most appropriate nuanced expression.', '{"prompt_es":"Choose the best option that completes each sentence with the most appropriate nuanced expression.","mastery_tag":"vocabulary:c1-nuanced","explanation":"Usar el término ''desafiante'' en lugar de ''difícil'' transmite una actitud más positiva.","stimulus_en":"Using the term ''challenging'' instead of ''difficult'' conveys a more ___ attitude.","options":[{"id":"o1","text":"positive"},{"id":"o2","text":"negative"},{"id":"o3","text":"neutral"},{"id":"o4","text":"ambiguous"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B2_I3', 'ingles-c1-U8', 8, 'multiple_choice', 'Choose the best option that completes each sentence with the most appropriate nuanced expression.', '{"prompt_es":"Choose the best option that completes each sentence with the most appropriate nuanced expression.","mastery_tag":"vocabulary:c1-nuanced","explanation":"Describir la idea de un colega como ''intrigante'' sugiere una perspectiva curiosa en lugar de una actitud despectiva.","stimulus_en":"To describe a colleague’s idea as ''intriguing'' suggests a ___ perspective rather than a dismissive one.","options":[{"id":"o1","text":"hostile"},{"id":"o2","text":"curious"},{"id":"o3","text":"indifferent"},{"id":"o4","text":"critical"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B2_I4', 'ingles-c1-U8', 9, 'multiple_choice', 'Choose the best option that completes each sentence with the most appropriate nuanced expression.', '{"prompt_es":"Choose the best option that completes each sentence with the most appropriate nuanced expression.","mastery_tag":"vocabulary:c1-nuanced","explanation":"El uso de ''limitado'' en lugar de ''pobre'' puede reflejar una evaluación más cuidadosa de los recursos.","stimulus_en":"The use of ''limited'' instead of ''poor'' can reflect a more ___ assessment of resources.","options":[{"id":"o1","text":"harsh"},{"id":"o2","text":"tactful"},{"id":"o3","text":"blunt"},{"id":"o4","text":"ambiguous"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B2_I5', 'ingles-c1-U8', 10, 'multiple_choice', 'Choose the best option that completes each sentence with the most appropriate nuanced expression.', '{"prompt_es":"Choose the best option that completes each sentence with the most appropriate nuanced expression.","mastery_tag":"vocabulary:c1-nuanced","explanation":"Al proporcionar comentarios, una ''sugerencia'' suele ser más constructiva que una crítica directa.","stimulus_en":"When providing feedback, a ''suggestion'' is often more ___ than a direct critique.","options":[{"id":"o1","text":"harsh"},{"id":"o2","text":"unnecessary"},{"id":"o3","text":"constructive"},{"id":"o4","text":"irrelevant"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B3_I1', 'ingles-c1-U8', 11, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''neither'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''neither'':","mastery_tag":"grammar:c1-ellipsis","explanation":"En esta oración, usamos ''neither'' para sustituir la repetición de ''she didn''t see the problem''.","stimulus_en":"He didn''t see the problem, and she didn''t see it either.\n\nNeither did she see ...","correct_answer":"the problem.","example":"neither"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B3_I2', 'ingles-c1-U8', 12, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''as well'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''as well'':","mastery_tag":"grammar:c1-ellipsis","explanation":"Aquí, ''as well as'' permite omitir la repetición de ''the project was delayed''.","stimulus_en":"The project was delayed, and the budget was affected too.\n\nThe budget was affected too, ...","correct_answer":"as well as the project.","example":"as well"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B3_I3', 'ingles-c1-U8', 13, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''also'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''also'':","mastery_tag":"grammar:c1-ellipsis","explanation":"Se utiliza ''also'' para evitar la repetición de ''the presentation'' en la segunda parte de la oración.","stimulus_en":"Tom enjoyed the presentation, and Mary did too.\n\nMary also enjoyed ...","correct_answer":"the presentation.","example":"also"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B3_I4', 'ingles-c1-U8', 14, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''too'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''too'':","mastery_tag":"grammar:c1-ellipsis","explanation":"El uso de ''too'' aquí nos permite omitir la repetición de ''the report''.","stimulus_en":"I recommend the report, and John recommends it as well.\n\nJohn recommends it, too, ...","correct_answer":"the report.","example":"too"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U8_B3_I5', 'ingles-c1-U8', 15, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''will'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''will'':","mastery_tag":"grammar:c1-ellipsis","explanation":"Aquí, usamos ''too'' para no repetir ''lead it'' en la segunda parte de la oración.","stimulus_en":"Our team will lead the project, and the marketing team will lead it as well.\n\nThe marketing team will lead the project, ...","correct_answer":"too.","example":"will"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U9', 'ingles-c1', 9, 'Unit 9', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B1_I1', 'ingles-c1-U9', 1, 'multiple_choice', 'What reason does Mark give for wanting to stay indoors this weekend?', '{"prompt_es":"What reason does Mark give for wanting to stay indoors this weekend?","mastery_tag":"listening:c1-complex-audio","explanation":"Mark expresses disinterest in outdoor activities due to his dislike of the rain.","stimulus_en":"You will hear a conversation between two friends discussing their plans for the weekend. They talk about the weather, their favorite activities, and some recent movies they''ve seen.","options":[{"id":"o1","text":"He has a cold"},{"id":"o2","text":"He prefers movies"},{"id":"o3","text":"He has work"},{"id":"o4","text":"He dislikes the weather"}],"correct_answer":"o4"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B1_I2', 'ingles-c1-U9', 2, 'multiple_choice', 'Which movie do the friends agree is overrated?', '{"prompt_es":"Which movie do the friends agree is overrated?","mastery_tag":"listening:c1-complex-audio","explanation":"They discuss the popularity of ''Avatar'' and mention how they found it lacking.","stimulus_en":"You will hear a conversation between two friends discussing their plans for the weekend. They talk about the weather, their favorite activities, and some recent movies they''ve seen.","options":[{"id":"o1","text":"Inception"},{"id":"o2","text":"Titanic"},{"id":"o3","text":"The Matrix"},{"id":"o4","text":"Avatar"}],"correct_answer":"o4"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B1_I3', 'ingles-c1-U9', 3, 'multiple_choice', 'How does Lisa feel about the weather forecast?', '{"prompt_es":"How does Lisa feel about the weather forecast?","mastery_tag":"listening:c1-complex-audio","explanation":"Lisa mentions that she hopes the rain will stop, indicating a positive outlook.","stimulus_en":"You will hear a conversation between two friends discussing their plans for the weekend. They talk about the weather, their favorite activities, and some recent movies they''ve seen.","options":[{"id":"o1","text":"Concerned"},{"id":"o2","text":"Optimistic"},{"id":"o3","text":"Indifferent"},{"id":"o4","text":"Excited"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B1_I4', 'ingles-c1-U9', 4, 'multiple_choice', 'What activity do the friends plan to do instead of going out?', '{"prompt_es":"What activity do the friends plan to do instead of going out?","mastery_tag":"listening:c1-complex-audio","explanation":"Their discussion centers on binge-watching movies as an alternative to outdoor plans.","stimulus_en":"You will hear a conversation between two friends discussing their plans for the weekend. They talk about the weather, their favorite activities, and some recent movies they''ve seen.","options":[{"id":"o1","text":"Visit a museum"},{"id":"o2","text":"Watch films"},{"id":"o3","text":"Go hiking"},{"id":"o4","text":"Cook together"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B1_I5', 'ingles-c1-U9', 5, 'multiple_choice', 'What underlying message is conveyed about their friendship?', '{"prompt_es":"What underlying message is conveyed about their friendship?","mastery_tag":"listening:c1-complex-audio","explanation":"Their agreement on movies and plans shows a strong bond and shared interests.","stimulus_en":"You will hear a conversation between two friends discussing their plans for the weekend. They talk about the weather, their favorite activities, and some recent movies they''ve seen.","options":[{"id":"o1","text":"They often argue"},{"id":"o2","text":"They enjoy similar tastes"},{"id":"o3","text":"They dislike each other"},{"id":"o4","text":"They rarely meet"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B2_I1', 'ingles-c1-U9', 6, 'multiple_choice_cloze', 'Fill in the gaps with the most appropriate option from the choices provided.', '{"prompt_es":"Fill in the gaps with the most appropriate option from the choices provided.","mastery_tag":"reading:c1-abstract-texts","main_text":"In the realm of (1)[GAP 1], philosophers often grapple with the nature of (2)[GAP 2] and how it shapes our understanding of reality. One prominent theory suggests that our perception is merely a (3)[GAP 3] of the underlying truths. As we delve deeper into (4)[GAP 4] thought, it becomes clear that (5)[GAP 5] play a crucial role in conceptual frameworks.","gaps":[{"id":"1","options":[{"id":"o1","text":"philosophy"},{"id":"o2","text":"realism"},{"id":"o3","text":"psychology"},{"id":"o4","text":"history"}]},{"id":"2","options":[{"id":"o1","text":"existence"},{"id":"o2","text":"intellect"},{"id":"o3","text":"emotion"},{"id":"o4","text":"perception"}]},{"id":"3","options":[{"id":"o1","text":"reflection"},{"id":"o2","text":"reality"},{"id":"o3","text":"illusion"},{"id":"o4","text":"creation"}]},{"id":"4","options":[{"id":"o1","text":"historical"},{"id":"o2","text":"abstract"},{"id":"o3","text":"empirical"},{"id":"o4","text":"literal"}]},{"id":"5","options":[{"id":"o1","text":"advancements"},{"id":"o2","text":"values"},{"id":"o3","text":"theories"},{"id":"o4","text":"objects"}]}],"correct_answer":{"1":"o1","2":"o1","3":"o1","4":"o2","5":"o3"},"explanation":"(1) La filosofía es el estudio de conceptos abstractos y teorías.\n(2) La existencia es un concepto central en muchas teorías filosóficas.\n(3) Una reflexión sugiere una imagen distorsionada de la verdad subyacente.\n(4) El pensamiento abstracto permite explorar conceptos más allá de lo tangible.\n(5) Las teorías son fundamentales para construir marcos conceptuales en filosofía."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U9_B3_I1', 'ingles-c1-U9', 7, 'fill_blanks', 'Fill in the blanks with the correct words that fit the context of complex audio materials.', '{"prompt_es":"Fill in the blanks with the correct words that fit the context of complex audio materials.","mastery_tag":"listening:c1-complex-audio","main_text":"In today''s fast-paced world, the ability to understand complex audio materials has become increasingly important. Often, these materials contain various layers of meaning. Professionals must listen not just for the words, but also for the (1)___ that can indicate the speaker''s true intent. For example, a seemingly positive statement may carry a (2)___ meaning that suggests sarcasm. It is crucial to recognize these nuances to make appropriate (3)___ based on the audio''s content. Additionally, (4)___ requires focusing on tone and inflection, which can change the (5)___ of a message entirely.","correct_answer":["nuance","hidden","inferences","listening","interpretation"],"explanation":"(1) La ''nuance'' se refiere a los sutiles matices o detalles que pueden cambiar el significado de lo que se dice.\n(2) Un significado ''hidden'' se refiere a lo que está oculto o no es evidente a primera vista, especialmente en el contexto del sarcasmo.\n(3) Las ''inferences'' son deducciones que hacemos basándonos en información implícita en el discurso.\n(4) El ''listening'' en un contexto más profundo implica no solo oír, sino también interpretar las señales del hablante.\n(5) La ''interpretation'' se refiere a la manera en que comprendemos o damos sentido a un mensaje comunicativo."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

INSERT INTO public.course_lessons (id, module_id, order_index, title, duration)
VALUES ('ingles-c1-U10', 'ingles-c1', 10, 'Unit 10', 600)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, order_index = EXCLUDED.order_index;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B1_I1', 'ingles-c1-U10', 1, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''demand'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''demand'':","mastery_tag":"grammar:c1-subjunctive","explanation":"El subjuntivo se utiliza en este contexto para expresar la necesidad o urgencia de que se complete algo.","stimulus_en":"It is essential that we finish this project on time.\n\nWe demand that we finish... ...","correct_answer":"this project on time.","example":"demand"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B1_I2', 'ingles-c1-U10', 2, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''recommend'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''recommend'':","mastery_tag":"grammar:c1-subjunctive","explanation":"Usamos ''recommend'' con subjuntivo para expresar una sugerencia en inglés formal.","stimulus_en":"He suggested we go to the meeting early.\n\nHe recommends that we go... ...","correct_answer":"to the meeting early.","example":"recommend"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B1_I3', 'ingles-c1-U10', 3, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''require'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''require'':","mastery_tag":"grammar:c1-subjunctive","explanation":"El uso de ''require'' aquí es un ejemplo de cómo el subjuntivo se utiliza para expresar insistencia.","stimulus_en":"They insist that he apologize immediately.\n\nThey require that he apologize... ...","correct_answer":"immediately.","example":"require"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B1_I4', 'ingles-c1-U10', 4, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''hope'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''hope'':","mastery_tag":"grammar:c1-subjunctive","explanation":"El subjuntivo es necesario aquí porque estamos expresando un deseo que no es real.","stimulus_en":"I wish she were here for the celebration.\n\nI hope that she were... ...","correct_answer":"here for the celebration.","example":"hope"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B1_I5', 'ingles-c1-U10', 5, 'key_word_transformation', 'Reescribe la frase usando la palabra clave ''stress'':', '{"prompt_es":"Reescribe la frase usando la palabra clave ''stress'':","mastery_tag":"grammar:c1-subjunctive","explanation":"El subjuntivo se utiliza para expresar la importancia de una acción en presentaciones formales.","stimulus_en":"It’s important that she take the lead in this project.\n\nThey stress that she take... ...","correct_answer":"the lead in this project.","example":"stress"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B2_I1', 'ingles-c1-U10', 6, 'fill_blanks', 'Fill in the blanks with the correct word to complete each sentence.', '{"prompt_es":"Fill in the blanks with the correct word to complete each sentence.","mastery_tag":"listening:c1-complex-audio","main_text":"Listening to complex audio materials often requires the ability to understand ___1___ meanings and subtle nuances. When a speaker uses irony or sarcasm, the listener must draw ___2___ based on the context rather than the explicit words. In many cases, the tone of voice can convey ___3___ information that is not directly stated. Moreover, effective comprehension involves recognizing the speaker''s intention, which may imply ___4___ undercurrents. Ultimately, a nuanced understanding allows for deeper ___5___ of the material presented.","correct_answer":["implicit","inferences","additional","emotional","appreciation"],"explanation":"(1) La palabra ''implicit'' se refiere a significados que no se expresan de forma directa, sino que se infieren del contexto.\n(2) Las ''inferences'' son conclusiones que se sacan basadas en la información implícita y el contexto.\n(3) La palabra ''additional'' se refiere a la información extra que se comunica sin ser explícitamente mencionada.\n(4) La palabra ''emotional'' se refiere a los sentimientos que pueden estar implícitos en el mensaje del hablante.\n(5) La palabra ''appreciation'' se refiere a la comprensión y valoración más rica de un material."}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B3_I1', 'ingles-c1-U10', 7, 'multiple_choice', 'Which word best describes a situation that is not straightforward and has many layers?', '{"prompt_es":"Which word best describes a situation that is not straightforward and has many layers?","mastery_tag":"vocabulary:c1-nuanced","explanation":"La palabra ''nuanced'' describe algo que tiene varias capas o sutilezas, a diferencia de ''obvious'' o ''simple''.","stimulus_en":"","options":[{"id":"o1","text":"Transparent"},{"id":"o2","text":"Nuanced"},{"id":"o3","text":"Obvious"},{"id":"o4","text":"Simple"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B3_I2', 'ingles-c1-U10', 8, 'multiple_choice', 'What term refers to the emotional undertone of a word beyond its literal meaning?', '{"prompt_es":"What term refers to the emotional undertone of a word beyond its literal meaning?","mastery_tag":"vocabulary:c1-nuanced","explanation":"''Connotation'' se refiere a los significados o emociones adicionales que una palabra puede evocar más allá de su definición literal.","stimulus_en":"","options":[{"id":"o1","text":"Connotation"},{"id":"o2","text":"Denotation"},{"id":"o3","text":"Definition"},{"id":"o4","text":"Etymology"}],"correct_answer":"o1"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B3_I3', 'ingles-c1-U10', 9, 'multiple_choice', 'Which word indicates a careful and methodical approach that reflects sophistication?', '{"prompt_es":"Which word indicates a careful and methodical approach that reflects sophistication?","mastery_tag":"vocabulary:c1-nuanced","explanation":"''Sophisticated'' implica un alto nivel de complejidad y refinamiento, a diferencia de ''casual'' o ''rushed''.","stimulus_en":"","options":[{"id":"o1","text":"Rushed"},{"id":"o2","text":"Imprecise"},{"id":"o3","text":"Sophisticated"},{"id":"o4","text":"Casual"}],"correct_answer":"o3"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B3_I4', 'ingles-c1-U10', 10, 'multiple_choice', 'What phrase best expresses the idea of conveying an idea subtly and with precision?', '{"prompt_es":"What phrase best expresses the idea of conveying an idea subtly and with precision?","mastery_tag":"vocabulary:c1-nuanced","explanation":"La frase ''articulate clearly'' implica comunicar ideas de manera precisa y sutil, en contraste con ser indirecto.","stimulus_en":"","options":[{"id":"o1","text":"Hit the nail on the head"},{"id":"o2","text":"Beat around the bush"},{"id":"o3","text":"Get to the point"},{"id":"o4","text":"Articulate clearly"}],"correct_answer":"o4"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;
INSERT INTO public.course_exercises (id, lesson_id, order_index, type, title, content)
VALUES ('C1_U10_B3_I5', 'ingles-c1-U10', 11, 'multiple_choice', 'Which term is synonymous with ''delicate'' when referring to a subtle difference or distinction?', '{"prompt_es":"Which term is synonymous with ''delicate'' when referring to a subtle difference or distinction?","mastery_tag":"vocabulary:c1-nuanced","explanation":"''Faint'' se refiere a algo débil o sutil, que es adecuado cuando se discuten diferencias delicadas.","stimulus_en":"","options":[{"id":"o1","text":"Robust"},{"id":"o2","text":"Faint"},{"id":"o3","text":"Harsh"},{"id":"o4","text":"Obvious"}],"correct_answer":"o2"}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, type = EXCLUDED.type;

COMMIT;