/**
 * Unidad 44 B1 — Lección 6: Expresión escrita (For, since, from, Time expressions)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_44_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u44-l6-w1', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre tu vida usando for, since o from.', expressionHint: 'Puedes usar: [[I have lived|He vivido]] [[for|durante]]/[[since|desde]], [[from...to|desde...hasta]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con for, since o from.', questions: [{ question: '[[I have lived|He vivido]] [[here|aquí]] ____ ____ ____ ____ [[2015|2015]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[point in time|punto en el tiempo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[We have known|Hemos conocido]] [[each other|el uno al otro]] ____ ____ ____ ____ [[ten years|diez años]].', options: ['[[for|durante]]', '[[since|desde]]', '[[from|desde]]'], correctAnswer: 'for', acceptableAnswers: ['for'], explanation: '[[For|Durante]] + [[duration|duración]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la palabra correcta.', questions: [{ question: '[[The shop|La tienda]] [[is open|está abierta]] ____ ____ ____ ____ [[9am|9am]] [[to|a]] [[5pm|5pm]].', options: ['[[from|desde]]', '[[for|durante]]', '[[since|desde]]'], correctAnswer: 'from', acceptableAnswers: ['from'], explanation: '[[From...to|Desde...hasta]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w5', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con since y otra con for.', expressionHint: 'Puedes usar: [[I have lived since|He vivido desde]], [[I have worked for|He trabajado durante]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[She has been ill|Ha estado enferma]] ____ ____ ____ ____ [[Monday|el lunes]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[point in time|punto en el tiempo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I worked|Trabajé]] ____ ____ ____ ____ [[2010|2010]] [[to|hasta]] [[2015|2015]].', options: ['[[from|desde]]', '[[for|durante]]', '[[since|desde]]'], correctAnswer: 'from', acceptableAnswers: ['from'], explanation: '[[From...to|Desde...hasta]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[They haven\'t seen|No han visto]] [[each other|el uno al otro]] ____ ____ ____ ____ [[ages|siglos]].', options: ['[[for|durante]]', '[[since|desde]]', '[[from|desde]]'], correctAnswer: 'for', acceptableAnswers: ['for'], explanation: '[[For ages|Durante siglos]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w9', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre tu trabajo o estudios usando for, since y from.', expressionHint: 'Puedes usar: [[I have worked for|He trabajado durante]], [[since|desde]], [[from...to|desde...hasta]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la preposición correcta.', questions: [{ question: '[[I have studied|He estudiado]] [[English|inglés]] ____ ____ ____ ____ [[I was ten|tenía diez años]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[clause|oración]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Classes run|Las clases tienen lugar]] ____ ____ ____ ____ [[September|septiembre]] [[to|hasta]] [[June|junio]].', options: ['[[from|desde]]', '[[for|durante]]', '[[since|desde]]'], correctAnswer: 'from', acceptableAnswers: ['from'], explanation: '[[From...to|Desde...hasta]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w12', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "I have wanted to... since..." sobre algo que quieres hacer.', expressionHint: '[[I have wanted to|He querido]] + [[verb|verbo]] + [[since|desde]] + [[point in time|punto en el tiempo]].', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[He has worked|Ha trabajado]] [[there|allí]] ____ ____ ____ ____ [[last year|el año pasado]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[point in time|punto en el tiempo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w14', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con from...to y otra con for.', expressionHint: 'Ejemplo: The office is open from... to... I have lived here for...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u44-l6-w15', type: 'writing', level: 'B1', topic: 'Time Expressions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre tu vida usando for, since y from correctamente.', expressionHint: 'Puedes usar: [[I have lived|He vivido]], [[I have worked|He trabajado]], [[The office is open from...to|La oficina está abierta desde...hasta]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
