/**
 * Unidad 21 B1 — Lección 1: Gramática (Gerund vs infinitive 1)
 * 15 ejercicios: enjoy, finish, avoid + -ing; want, need, decide + to
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Gerund vs Infinitive (1)|Gerundio vs infinitivo (1)]]';
const INSTRUCTIONS = 'Elige la opción correcta. Usa -ing (gerund) o to + infinitivo según el verbo.';

export const UNIT_21_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u21-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[reading|leyendo]] [[books|libros]] [[in my free time|en mi tiempo libre]].', options: ['[[enjoy|disfruto]]', '[[enjoys|disfruta]]', '[[enjoyed|disfruté]]'], correctAnswer: 'enjoy', acceptableAnswers: ['enjoy'], explanation: '[[Enjoy|Disfrutar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[cleaning|limpiar]] [[her room|su habitación]] [[yesterday|ayer]].', options: ['[[finished|terminó de]]', '[[finish|termina de]]', '[[finishes|termina de]]'], correctAnswer: 'finished', acceptableAnswers: ['finished'], explanation: '[[Finish|Terminar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[eating|comer]] [[too much sugar|demasiado azúcar]].', options: ['[[avoid|evitamos]]', '[[avoids|evita]]', '[[avoided|evitamos]]'], correctAnswer: 'avoid', acceptableAnswers: ['avoid'], explanation: '[[Avoid|Evitar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[to learn|aprender]] [[how to cook|a cocinar]].', options: ['[[wants|quiere]]', '[[want|quiere]]', '[[wanting|queriendo]]'], correctAnswer: 'wants', acceptableAnswers: ['wants'], explanation: '[[Want|Querer]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[to buy|comprar]] [[a new bike|una bicicleta nueva]].', options: ['[[need|necesito]]', '[[needs|necesita]]', '[[needing|necesitando]]'], correctAnswer: 'need', acceptableAnswers: ['need'], explanation: '[[Need|Necesitar]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[to travel|viajar]] [[next summer|el próximo verano]].', options: ['[[decided|decidieron]]', '[[decide|deciden]]', '[[deciding|decidiendo]]'], correctAnswer: 'decided', acceptableAnswers: ['decided'], explanation: '[[Decide|Decidir]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[playing|jugar]] [[football|fútbol]] [[at weekends|los fines de semana]].', options: ['[[enjoy|disfruto]]', '[[enjoys|disfruta]]', '[[enjoyed|disfruté]]'], correctAnswer: 'enjoy', acceptableAnswers: ['enjoy'], explanation: '[[Enjoy|Disfrutar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[watching|ver]] [[films|películas]].', options: ['[[avoids|evita]]', '[[wants|quiere]]', '[[decides|decide]]'], correctAnswer: 0, explanation: '[[Avoid|Evitar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[finish|terminar]] [[the project|el proyecto]] [[by Friday|para el viernes]].', options: ['[[need to|necesitamos]]', '[[need|necesitamos]]', '[[needs to|necesita]]'], correctAnswer: 'need to', acceptableAnswers: ['need to'], explanation: '[[Need|Necesitar]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[making|hacer]] [[mistakes|errores]] [[in his work|en su trabajo]].', options: ['[[avoids|evita]]', '[[avoid|evita]]', '[[avoided|evitó]]'], correctAnswer: 'avoids', acceptableAnswers: ['avoids'], explanation: '[[Avoid|Evitar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[to join|unirme]] [[a gym|a un gimnasio]] [[this year|este año]].', options: ['[[want|quiero]]', '[[wants|quiere]]', '[[wanting|queriendo]]'], correctAnswer: 'want', acceptableAnswers: ['want'], explanation: '[[Want|Querer]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[swimming|nadar]] [[in the park|en el parque]] [[pool|piscina]].', options: ['[[enjoy|disfrutan]]', '[[want|quieren]]', '[[need|necesitan]]'], correctAnswer: 0, explanation: '[[Enjoy|Disfrutar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[writing|escribir]] [[her essay|su ensayo]] [[last night|anoche]].', options: ['[[finished|terminó de]]', '[[finish|termina de]]', '[[finishes|termina de]]'], correctAnswer: 'finished', acceptableAnswers: ['finished'], explanation: '[[Finish|Terminar]] + [[-ing|gerundio]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[to save|ahorrar]] [[money|dinero]] [[for|para]] [[our holiday|nuestras vacaciones]].', options: ['[[decided to|decidimos]]', '[[decide to|decidimos]]', '[[deciding to|decidiendo]]'], correctAnswer: 'decided to', acceptableAnswers: ['decided to'], explanation: '[[Decide|Decidir]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u21-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Gerund vs Infinitive', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[to speak|hablar]] [[to|con]] [[my boss|mi jefe]] [[about|sobre]] [[the promotion|el ascenso]].', options: ['[[need to|necesito]]', '[[enjoy|disfruto]]', '[[avoid|evito]]'], correctAnswer: 0, explanation: '[[Need|Necesitar]] + [[to + infinitive|to + infinitivo]].' }] }, topicName: 'Grammar' },
];
