/**
 * Unidad 18 B1 — Lección 1: Gramática (Reported speech - statements)
 * 15 ejercicios: said (that), told (that), backshift
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Reported Speech (Statements)|Estilo indirecto (afirmaciones)]]';
const INSTRUCTIONS = 'Elige la opción correcta. Usa reported speech (said that, told that, backshift).';

export const UNIT_18_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u18-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She said that she|Ella dijo que ella]] ____ ____ ____ ____ [[working|trabajando]] [[from home|desde casa]] [[that day|ese día]].', options: ['[[was|estaba]]', '[[is|está]]', '[[has been|ha estado]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Backshift|Cambio de tiempo]]: [[present continuous → past continuous|presente continuo → pasado continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He told me that he|Él me dijo que él]] ____ ____ ____ ____ [[received|recibió]] [[the message|el mensaje]] [[yesterday|ayer]].', options: ['[[had|había]]', '[[has|ha]]', '[[have|tiene]]'], correctAnswer: 'had', acceptableAnswers: ['had'], explanation: '[[Backshift|Cambio de tiempo]]: [[past simple → past perfect|pasado simple → pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They said that they|Ellos dijeron que ellos]] ____ ____ ____ ____ [[send|enviar]] [[the email|el email]] [[soon|pronto]].', options: ['[[would|enviarían]]', '[[will|enviarán]]', '[[can|pueden]]'], correctAnswer: 'would', acceptableAnswers: ['would'], explanation: '[[Backshift|Cambio de tiempo]]: [[will → would|will → would]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She told him that she|Ella le dijo que ella]] ____ ____ ____ ____ [[busy|ocupada]] [[at the moment|en ese momento]].', options: ['[[was|estaba]]', '[[is|está]]', '[[has been|ha estado]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Backshift|Cambio de tiempo]]: [[present → past|presente → pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He said that he|Él dijo que él]] ____ ____ ____ ____ [[didn\'t get|no recibió]] [[the text|el mensaje de texto]] [[yet|aún]].', options: ["[[hadn't|no había]]", "[[didn't|no]]", "[[hasn't|no ha]]"], correctAnswer: "hadn't", acceptableAnswers: ["hadn't"], explanation: '[[Backshift|Cambio de tiempo]]: [[past simple → past perfect|pasado simple → pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I told her that I|Yo le dije que yo]] ____ ____ ____ ____ [[would call|llamaría]] [[her|la]] [[later|más tarde]].', options: ['[[would|llamaría]]', '[[will|llamaré]]', '[[can|puedo]]'], correctAnswer: 'would', acceptableAnswers: ['would'], explanation: '[[Backshift|Cambio de tiempo]]: [[will → would|will → would]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She said that she|Ella dijo que ella]] ____ ____ ____ ____ [[lives|vive]] [[in Madrid|en Madrid]].', options: ['[[lived|vivía]]', '[[lives|vive]]', '[[has lived|ha vivido]]'], correctAnswer: 'lived', acceptableAnswers: ['lived'], explanation: '[[Backshift|Cambio de tiempo]]: [[present simple → past simple|presente simple → pasado simple]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which verb|Qué verbo]] [[do we use|usamos]] [[when we mention the person we spoke to|cuando mencionamos la persona a la que hablamos]]?', options: ['[[said|dijo]]', '[[told|dijo]]', '[[spoke|habló]]'], correctAnswer: 1, explanation: '[[Told|Dijo]] [[requires an object|requiere un objeto]]: [[told me|me dijo]], [[told him|le dijo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They told us that the meeting|Ellos nos dijeron que la reunión]] ____ ____ ____ ____ [[cancelled|cancelada]].', options: ['[[had been|había sido]]', '[[was|fue]]', '[[is|es]]'], correctAnswer: 'had been', acceptableAnswers: ['had been'], explanation: '[[Backshift|Cambio de tiempo]]: [[past passive → past perfect passive|pasiva pasado → pasiva pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He said that he|Él dijo que él]] ____ ____ ____ ____ [[can|puede]] [[speak|hablar]] [[three languages|tres idiomas]].', options: ['[[could|podía]]', '[[can|puede]]', '[[would|podría]]'], correctAnswer: 'could', acceptableAnswers: ['could'], explanation: '[[Backshift|Cambio de tiempo]]: [[can → could|can → could]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She told me that she|Ella me dijo que ella]] ____ ____ ____ ____ [[has sent|ha enviado]] [[the email|el email]] [[already|ya]].', options: ['[[had sent|había enviado]]', '[[has sent|ha enviado]]', '[[sent|envió]]'], correctAnswer: 'had sent', acceptableAnswers: ['had sent'], explanation: '[[Backshift|Cambio de tiempo]]: [[present perfect → past perfect|presente perfecto → pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Direct|Directo]]: "[[I am busy|Estoy ocupado]]". [[Reported|Indirecto]]: [[He said that he|Él dijo que él]] ____ ____ ____ ____ [[busy|ocupado]].', options: ['[[was|estaba]]', '[[is|está]]', '[[has been|ha estado]]'], correctAnswer: 0, explanation: '[[Backshift|Cambio de tiempo]]: [[am → was|am → was]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We said that we|Nosotros dijimos que nosotros]] ____ ____ ____ ____ [[didn\'t know|no sabíamos]] [[about the change|sobre el cambio]].', options: ["[[didn't|no]]", "[[hadn't|no habíamos]]", "[[don't|no]]"], correctAnswer: "didn't", acceptableAnswers: ["didn't"], explanation: '[[Backshift|Cambio de tiempo]]: [[present → past|presente → pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He told her that he|Él le dijo que él]] ____ ____ ____ ____ [[would reply|respondería]] [[to her message|a su mensaje]] [[soon|pronto]].', options: ['[[would|respondería]]', '[[will|responderá]]', '[[can|puede]]'], correctAnswer: 'would', acceptableAnswers: ['would'], explanation: '[[Backshift|Cambio de tiempo]]: [[will → would|will → would]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u18-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Reported Speech', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Direct|Directo]]: "[[I have received your email|He recibido tu email]]". [[Reported|Indirecto]]: [[She said that she|Ella dijo que ella]] ____ ____ ____ ____ ____ ____ ____ ____ [[received|recibió]] [[my email|mi email]].', options: ['[[had|había]]', '[[has|ha]]', '[[have|tiene]]'], correctAnswer: 0, explanation: '[[Backshift|Cambio de tiempo]]: [[present perfect → past perfect|presente perfecto → pasado perfecto]].' }] }, topicName: 'Grammar' },
];
