/**
 * Unidad 55 B1 — Lección 1: Gramática (Repaso 51–54)
 * 15 ejercicios: conditionals, passive, reported speech, modals, tenses
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Review 51–54|Repaso unidades 51–54]]';
const INSTRUCTIONS = 'Elige la forma correcta.';

export const UNIT_55_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u55-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[you|tú]] ____ ____ ____ ____ [[water|agua]], [[it boils|hierve]].', options: ['[[heat|calientas]]', '[[heated|calentaras]]', '[[will heat|calentarás]]'], correctAnswer: 'heat', acceptableAnswers: ['heat'], explanation: '[[Zero conditional|Condicional cero]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The book|El libro]] ____ ____ ____ ____ [[written|escrito]] [[by a famous author|por un autor famoso]].', options: ['[[was written|fue escrito]]', '[[is written|es escrito]]', '[[wrote|escribió]]'], correctAnswer: 'was written', acceptableAnswers: ['was written'], explanation: '[[Passive past|Pasiva pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[me|me]] [[that|que]] [[he would come|vendría]].', options: ['[[said|dijo]]', '[[told|dijo]]', '[[asked|preguntó]]'], correctAnswer: 'said', acceptableAnswers: ['said'], explanation: '[[Say that|Decir que]] [[without person|sin persona]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[wear|usar]] [[a seatbelt|el cinturón]] [[when driving|al conducir]].', options: ['[[must|debes]]', '[[might|podrías]]', '[[can\'t|no puedes]]'], correctAnswer: 'must', acceptableAnswers: ['must'], explanation: '[[Must|Debes]] [[for obligation|para obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[here|aquí]] [[since 2020|desde 2020]].', options: ['[[has lived|ha vivido]]', '[[lived|vivía]]', '[[lives|vive]]'], correctAnswer: 'has lived', acceptableAnswers: ['has lived'], explanation: '[[Present perfect|Presente perfecto]]: [[since|desde]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____ ____ ____ ____ [[you|tú]], [[I would apologise|me disculparía]].', options: ['[[were|fuera]]', '[[am|soy]]', '[[had been|hubiera sido]]'], correctAnswer: 'were', acceptableAnswers: ['were'], explanation: '[[Second conditional|Segundo condicional]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[English|El inglés]] ____ ____ ____ ____ [[spoken|hablado]] [[all over the world|en todo el mundo]].', options: ['[[is spoken|se habla]]', '[[speaks|habla]]', '[[was spoken|fue hablado]]'], correctAnswer: 'is spoken', acceptableAnswers: ['is spoken'], explanation: '[[Passive present|Pasiva presente]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[me|me]] [[if|si]] [[I had seen|había visto]] [[the film|la película]].', options: ['[[asked|preguntó]]', '[[told|dijo]]', '[[said|dijo]]'], correctAnswer: 'asked', acceptableAnswers: ['asked'], explanation: '[[Reported question|Pregunta indirecta]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[go|ir]] [[to the doctor|al médico]] — [[I feel ill|me siento mal]].', options: ['[[should|debería]]', '[[might|podría]]', '[[can\'t|no puedo]]'], correctAnswer: 'should', acceptableAnswers: ['should'], explanation: '[[Should|Debería]] [[for advice|para consejo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuando]] [[I arrived|llegué]], [[she|ella]] ____ ____ ____ ____ [[already left|ya había salido]].', options: ['[[had already left|ya había salido]]', '[[has already left|ya ha salido]]', '[[already left|ya salió]]'], correctAnswer: 'had already left', acceptableAnswers: ['had already left'], explanation: '[[Past perfect|Pasado perfecto]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____ ____ ____ ____ [[known|hubiera sabido]], [[I would have helped|habría ayudado]] [[you|te]].', options: ['[[had known|hubiera sabido]]', '[[knew|supiera]]', '[[have known|he sabido]]'], correctAnswer: 'had known', acceptableAnswers: ['had known'], explanation: '[[Third conditional|Tercer condicional]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The work|El trabajo]] ____ ____ ____ ____ [[must be finished|debe ser terminado]] [[by Friday|para el viernes]].', options: ['[[must be finished|debe ser terminado]]', '[[must finish|debe terminar]]', '[[must finished|debe terminado]]'], correctAnswer: 'must be finished', acceptableAnswers: ['must be finished'], explanation: '[[Modal passive|Pasiva con modal]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[a new house|una casa nueva]] [[next month|el próximo mes]].', options: ['[[are buying|están comprando]]', '[[will buy|comprarán]]', '[[bought|compraron]]'], correctAnswer: 'are buying', acceptableAnswers: ['are buying'], explanation: '[[Present continuous|Presente continuo]]: [[future plan|plan futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[it|él]] ____ ____ ____ ____ [[tomorrow|mañana]], [[we will stay|nos quedaremos]] [[at home|en casa]].', options: ['[[rains|llueve]]', '[[rained|lloviera]]', '[[would rain|llovería]]'], correctAnswer: 'rains', acceptableAnswers: ['rains'], explanation: '[[First conditional|Primer condicional]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u55-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[me|me]] [[to wait|a esperar]].', options: ['[[told|dijo]]', '[[said|dijo]]', '[[asked|preguntó]]'], correctAnswer: 0, explanation: '[[Reported command|Orden indirecta]]: [[tell + person + to|tell + persona + to]].' }] }, topicName: 'Grammar' },
];
