/**
 * Unidad 24 B1 — Lección 1: Gramática (Phrasal verbs 2)
 * 15 ejercicios: find out, give up, look into, fill in, hand in
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Phrasal Verbs 2|Phrasal verbs 2]]';
const INSTRUCTIONS = 'Elige el phrasal verb correcto para completar la frase.';

export const UNIT_24_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u24-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[when|cuando]] [[the shop|la tienda]] [[opens|abre]] [[tomorrow|mañana]].', options: ['[[find out|averiguar]]', '[[give up|rendirse]]', '[[look into|investigar]]'], correctAnswer: 'find out', acceptableAnswers: ['find out'], explanation: '[[Find out|Averiguar]] = [[discover|descubrir]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[smoking|fumar]] [[last year|el año pasado]].', options: ['[[gave up|dejó de]]', '[[found out|averiguó]]', '[[handed in|entregó]]'], correctAnswer: 'gave up', acceptableAnswers: ['gave up'], explanation: '[[Give up|Dejar de]] = [[stop trying|dejar de intentar]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We need to|Necesitamos]] ____ ____ ____ ____ [[this complaint|esta queja]] [[before|antes]] [[taking action|tomar medidas]].', options: ['[[look into|investigar]]', '[[fill in|rellenar]]', '[[hand in|entregar]]'], correctAnswer: 'look into', acceptableAnswers: ['look into'], explanation: '[[Look into|Investigar]] = [[investigate|investigar]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Please|Por favor]] ____ ____ ____ ____ [[this form|este formulario]] [[with|con]] [[your details|tus datos]].', options: ['[[fill in|rellena]]', '[[find out|averigua]]', '[[give up|abandona]]'], correctAnswer: 'fill in', acceptableAnswers: ['fill in'], explanation: '[[Fill in|Rellenar]] = [[complete a form|completar un formulario]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Students must|Los estudiantes deben]] ____ ____ ____ ____ [[their essays|sus ensayos]] [[by Friday|para el viernes]].', options: ['[[hand in|entregar]]', '[[fill in|rellenar]]', '[[look into|investigar]]'], correctAnswer: 'hand in', acceptableAnswers: ['hand in'], explanation: '[[Hand in|Entregar]] = [[submit|entregar]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[the price|el precio]] [[by|al]] [[asking|preguntar]] [[the assistant|al dependiente]].', options: ['[[found out|averiguó]]', '[[gave up|dejó de]]', '[[handed in|entregó]]'], correctAnswer: 'found out', acceptableAnswers: ['found out'], explanation: '[[Find out|Averiguar]] [[past|pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Don\'t|No]] ____ ____ ____ ____ [[!|!]] [[Keep trying|Sigue intentando]].', options: ['[[give up|te rindas]]', '[[find out|averigües]]', '[[hand in|entregues]]'], correctAnswer: 'give up', acceptableAnswers: ['give up'], explanation: '[[Give up|Rendirse]] = [[stop trying|dejar de intentar]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The manager|El gerente]] ____ ____ ____ ____ [[the problem|el problema]] [[and|y]] [[promised|prometió]] [[to fix it|arreglarlo]].', options: ['[[looked into|investigó]]', '[[gave up|abandonó]]', '[[handed in|entregó]]'], correctAnswer: 0, explanation: '[[Look into|Investigar]] [[past|pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[the application form|el formulario de solicitud]] [[yesterday|ayer]].', options: ['[[filled in|rellené]]', '[[found out|averigué]]', '[[gave up|abandoné]]'], correctAnswer: 'filled in', acceptableAnswers: ['filled in'], explanation: '[[Fill in|Rellenar]] [[past|pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[her homework|sus deberes]] [[late|llegó tarde]] [[because|porque]] [[she forgot|olvidó]].', options: ['[[handed in|entregó]]', '[[filled in|rellenó]]', '[[looked into|investigó]]'], correctAnswer: 'handed in', acceptableAnswers: ['handed in'], explanation: '[[Hand in|Entregar]] [[past|pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Can you|Puedes]] ____ ____ ____ ____ [[if|si]] [[this product|este producto]] [[is|está]] [[in stock|en stock]]?', options: ['[[find out|averiguar]]', '[[give up|rendirte]]', '[[hand in|entregar]]'], correctAnswer: 'find out', acceptableAnswers: ['find out'], explanation: '[[Find out|Averiguar]] [[for information|para información]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[After|Después]] [[years|años]] [[of trying|de intentar]], [[he|él]] ____ ____ ____ ____ [[his dream|su sueño]] [[of becoming|de convertirse]] [[a musician|músico]].', options: ['[[gave up|abandonó]]', '[[found out|averiguó]]', '[[handed in|entregó]]'], correctAnswer: 0, explanation: '[[Give up|Abandonar]] [[a dream|un sueño]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The police|La policía]] ____ ____ ____ ____ [[the robbery|el robo]] [[last week|la semana pasada]].', options: ['[[are looking into|están investigando]]', '[[gave up|abandonó]]', '[[handed in|entregó]]'], correctAnswer: 'are looking into', acceptableAnswers: ['are looking into'], explanation: '[[Look into|Investigar]] [[continuous|continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You need to|Necesitas]] ____ ____ ____ ____ [[your name|tu nombre]] [[and address|y dirección]] [[here|aquí]].', options: ['[[fill in|rellenar]]', '[[find out|averiguar]]', '[[give up|abandonar]]'], correctAnswer: 'fill in', acceptableAnswers: ['fill in'], explanation: '[[Fill in|Rellenar]] [[details|datos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u24-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Phrasal Verbs', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[All employees must|Todos los empleados deben]] ____ ____ ____ ____ [[their reports|sus informes]] [[by|para]] [[the end of the month|final de mes]].', options: ['[[hand in|entregar]]', '[[fill in|rellenar]]', '[[look into|investigar]]'], correctAnswer: 0, explanation: '[[Hand in|Entregar]] [[work|trabajo]].' }] }, topicName: 'Grammar' },
];
