/**
 * Unidad 58 B1 — Lección 1: Gramática (Mixed grammar practice)
 * 15 ejercicios: mixed grammar from B1
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Mixed Grammar Practice|Práctica gramatical mixta]]';
const INSTRUCTIONS = 'Elige la forma correcta.';

export const UNIT_58_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u58-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The new bridge|El nuevo puente]] ____ ____ ____ ____ [[built|construido]] [[last year|el año pasado]].', options: ['[[was built|fue construido]]', '[[is built|es construido]]', '[[built|construyó]]'], correctAnswer: 'was built', acceptableAnswers: ['was built'], explanation: '[[Passive past|Pasiva pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[live|vivir]] [[in the countryside|en el campo]] [[than in the city|que en la ciudad]].', options: ['[[would rather|preferiría]]', '[[had better|más vale que]]', '[[must|debo]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather'], explanation: '[[Would rather|Preferiría]] [[for preference|para preferencia]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The village|El pueblo]] ____ ____ ____ ____ [[I grew up|crecí]] [[is|es]] [[very small|muy pequeño]].', options: ['[[where|donde]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 'where', acceptableAnswers: ['where'], explanation: '[[Relative clause|Oración de relativo]]: [[where for places|where para lugares]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There|Hay]] ____ ____ ____ ____ [[many|muchos]] [[shops|tiendas]] [[in the town centre|en el centro de la ciudad]].', options: ['[[are|son]]', '[[is|es]]', '[[have|hay]]'], correctAnswer: 'are', acceptableAnswers: ['are'], explanation: '[[There are|Hay]] [[+ plural|+ plural]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The park|El parque]] ____ ____ ____ ____ [[visited|visitado]] [[by thousands of people|por miles de personas]] [[every day|cada día]].', options: ['[[is visited|es visitado]]', '[[visits|visita]]', '[[was visited|fue visitado]]'], correctAnswer: 'is visited', acceptableAnswers: ['is visited'], explanation: '[[Passive present|Pasiva presente]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[you|tú]] ____ ____ ____ ____ [[to the countryside|al campo]] [[next weekend|el próximo fin de semana]], [[you will love it|te encantará]].', options: ['[[go|vas]]', '[[went|fueras]]', '[[had gone|hubieras ido]]'], correctAnswer: 'go', acceptableAnswers: ['go'], explanation: '[[First conditional|Primer condicional]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The city|La ciudad]] ____ ____ ____ ____ [[much|mucho]] [[noisier|más ruidosa]] [[than|que]] [[the village|el pueblo]].', options: ['[[is much|es mucho]]', '[[are much|son mucho]]', '[[is many|es muchos]]'], correctAnswer: 'is much', acceptableAnswers: ['is much'], explanation: '[[Much + comparative|Much + comparativo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[me|me]] [[that|que]] [[she had moved|había mudado]] [[to a new flat|a un piso nuevo]].', options: ['[[told|dijo]]', '[[said|dijo]]', '[[asked|preguntó]]'], correctAnswer: 'told', acceptableAnswers: ['told'], explanation: '[[Tell + person|Tell + persona]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[take|tomar]] [[the bus|el autobús]] [[to get to the centre|para llegar al centro]].', options: ['[[should|deberías]]', '[[must|debes]]', '[[can\'t|no puedes]]'], correctAnswer: 'should', acceptableAnswers: ['should'], explanation: '[[Should|Deberías]] [[for advice|para consejo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The mountains|Las montañas]] ____ ____ ____ ____ [[covered|cubiertas]] [[with snow|con nieve]] [[in winter|en invierno]].', options: ['[[are covered|están cubiertas]]', '[[cover|cubren]]', '[[were covered|estaban cubiertas]]'], correctAnswer: 'are covered', acceptableAnswers: ['are covered'], explanation: '[[Passive present|Pasiva presente]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Although|Aunque]] [[the town|el pueblo]] ____ ____ ____ ____ [[small|pequeño]], [[it has|tiene]] [[everything|todo]].', options: ['[[is small|es pequeño]]', '[[small|pequeño]]', '[[was small|era pequeño]]'], correctAnswer: 'is small', acceptableAnswers: ['is small'], explanation: '[[Clause of contrast|Oración de contraste]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[living|viviendo]] [[here|aquí]] [[since 2015|desde 2015]].', options: ['[[have been living|he estado viviendo]]', '[[had been living|había estado viviendo]]', '[[am living|estoy viviendo]]'], correctAnswer: 'have been living', acceptableAnswers: ['have been living'], explanation: '[[Present perfect continuous|Presente perfecto continuo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The river|El río]] ____ ____ ____ ____ [[through|a través de]] [[the valley|el valle]].', options: ['[[flows|fluye]]', '[[flow|fluye]]', '[[is flowing|está fluyendo]]'], correctAnswer: 'flows', acceptableAnswers: ['flows'], explanation: '[[Present simple|Presente simple]]: [[general fact|hecho general]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[If|Si]] [[I|yo]] ____ ____ ____ ____ [[in the countryside|en el campo]], [[I would have a garden|tendría un jardín]].', options: ['[[lived|viviera]]', '[[live|vivo]]', '[[had lived|hubiera vivido]]'], correctAnswer: 'lived', acceptableAnswers: ['lived'], explanation: '[[Second conditional|Segundo condicional]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u58-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Mixed Grammar', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The building|El edificio]] ____ ____ ____ ____ [[which|que]] [[was built|fue construido]] [[in 1900|en 1900]] [[is|es]] [[a museum|un museo]].', options: ['[[which|que]]', '[[where|donde]]', '[[who|quien]]'], correctAnswer: 0, explanation: '[[Defining relative clause|Oración de relativo definida]]: [[which for things|which para cosas]].' }] }, topicName: 'Grammar' },
];
