/**
 * Unidad 53 B1 — Lección 1: Gramática (Review: modals)
 * 15 ejercicios: must, might, can't, have to, should, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Review Modals|Repaso de modales]]';
const INSTRUCTIONS = 'Elige el modal correcto.';

export const UNIT_53_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u53-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[wear|usar]] [[a seatbelt|el cinturón]] [[when|cuando]] [[driving|conduces]].', options: ['[[must|debes]]', '[[might|podrías]]', '[[can\'t|no puedes]]'], correctAnswer: 'must', acceptableAnswers: ['must', 'have to'], explanation: '[[Must|Debe]] [[for obligation|para obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[be at home|estar en casa]] [[–|–]] [[her car|su coche]] [[is|está]] [[there|allí]].', options: ['[[must|debe]]', '[[can\'t|no puede]]', '[[might|podría]]'], correctAnswer: 'must', acceptableAnswers: ['must'], explanation: '[[Must|Debe]] [[for deduction|para deducción]] [[(certainty)|(certeza)]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[be French|ser francés]] [[–|–]] [[he speaks|habla]] [[perfect French|francés perfecto]].', options: ['[[can\'t|no puede]]', '[[must|debe]]', '[[might|podría]]'], correctAnswer: 'must', acceptableAnswers: ['must'], explanation: '[[Must|Debe]] [[for strong deduction|para deducción fuerte]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[be at the cinema|estar en el cine]] [[–|–]] [[they left|salieron]] [[an hour ago|hace una hora]].', options: ['[[might|podrían]]', '[[can\'t|no pueden]]', '[[must|deben]]'], correctAnswer: 'might', acceptableAnswers: ['might', 'could'], explanation: '[[Might|Podría]] [[for possibility|para posibilidad]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[see a doctor|ver a un médico]] [[–|–]] [[you look|te ves]] [[very ill|muy enfermo]].', options: ['[[should|deberías]]', '[[must|debes]]', '[[can\'t|no puedes]]'], correctAnswer: 'should', acceptableAnswers: ['should', 'ought to'], explanation: '[[Should|Debería]] [[for advice|para consejo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[go to work|ir al trabajo]] [[tomorrow|mañana]] [[–|–]] [[it\'s a holiday|es festivo]].', options: ['[[don\'t have to|no tengo que]]', '[[mustn\'t|no debo]]', '[[can\'t|no puedo]]'], correctAnswer: 'don\'t have to', acceptableAnswers: ['don\'t have to'], explanation: '[[Don\'t have to|No tener que]] [[for no obligation|para no obligación]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[be at work|estar en el trabajo]] [[–|–]] [[it\'s Sunday|es domingo]] [[and|y]] [[the office|la oficina]] [[is closed|está cerrada]].', options: ['[[can\'t|no puede]]', '[[must|debe]]', '[[might|podría]]'], correctAnswer: 'can\'t', acceptableAnswers: ['can\'t'], explanation: '[[Can\'t|No puede]] [[for negative deduction|para deducción negativa]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[smoke|fumar]] [[here|aquí]] [[–|–]] [[it\'s a hospital|es un hospital]].', options: ['[[mustn\'t|no debes]]', '[[don\'t have to|no tienes que]]', '[[might not|podrías no]]'], correctAnswer: 'mustn\'t', acceptableAnswers: ['mustn\'t'], explanation: '[[Mustn\'t|No debe]] [[for prohibition|para prohibición]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[swim|nadar]] [[when|cuando]] [[I was young|era joven]] [[but|pero]] [[I can\'t now|no puedo ahora]].', options: ['[[could|podía]]', '[[must|debía]]', '[[should|debería]]'], correctAnswer: 'could', acceptableAnswers: ['could'], explanation: '[[Could|Podía]] [[for past ability|para capacidad pasada]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[hurry up|darnos prisa]] [[–|–]] [[we|nosotros]] [[have|tenemos]] [[plenty of time|mucho tiempo]].', options: ['[[needn\'t|no necesitamos]]', '[[mustn\'t|no debemos]]', '[[can\'t|no podemos]]'], correctAnswer: 'needn\'t', acceptableAnswers: ['needn\'t', 'don\'t need to'], explanation: '[[Needn\'t|No necesitar]] [[for no necessity|para no necesidad]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[leave now|irte ahora]] [[if|si]] [[you|tú]] [[want|quieres]] [[to catch|coger]] [[the train|el tren]].', options: ['[[had better|más te vale]]', '[[should|deberías]]', '[[must|debes]]'], correctAnswer: 'had better', acceptableAnswers: ['had better', 'should'], explanation: '[[Had better|Más te vale]] [[for strong advice|para consejo fuerte]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Students|Los estudiantes]] ____ ____ ____ ____ [[hand in|entregar]] [[their homework|sus deberes]] [[by Friday|para el viernes]].', options: ['[[have to|tienen que]]', '[[might|podrían]]', '[[can\'t|no pueden]]'], correctAnswer: 'have to', acceptableAnswers: ['have to', 'must'], explanation: '[[Have to|Tener que]] [[for external obligation|para obligación externa]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[rather stay|preferiría quedarme]] [[home|en casa]] [[tonight|esta noche]].', options: ['[[would|preferiría]]', '[[should|debería]]', '[[must|debo]]'], correctAnswer: 'would', acceptableAnswers: ['would'], explanation: '[[Would rather|Preferiría]] [[for preference|para preferencia]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It|Ello]] ____ ____ ____ ____ [[rain|llover]] [[later|más tarde]] [[–|–]] [[the sky|el cielo]] [[is|está]] [[getting dark|oscureciéndose]].', options: ['[[might|podría]]', '[[can\'t|no puede]]', '[[must|debe]]'], correctAnswer: 'might', acceptableAnswers: ['might', 'could', 'may'], explanation: '[[Might|Podría]] [[for possibility|para posibilidad]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u53-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Modals', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[be able to|ser capaz de]] [[speak|hablar]] [[English|inglés]] [[well|bien]] [[after|después de]] [[this course|este curso]].', options: ['[[will be able to|serás capaz de]]', '[[must be able to|debes ser capaz de]]', '[[might be able to|podrías ser capaz de]]'], correctAnswer: 0, explanation: '[[Will be able to|Serás capaz de]] [[for future ability|para capacidad futura]].' }] }, topicName: 'Grammar' },
];
