/**
 * Unidad 26 B1 — Lección 1: Gramática (Quantifiers: much, many, a lot, few, little)
 * 15 ejercicios: much/many con incontables/contables, a lot, few, little
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Quantifiers|Cuantificadores]] ([[much|mucho]], [[many|muchos]], [[a lot|mucho]], [[few|pocos]], [[little|poco]])';
const INSTRUCTIONS = 'Elige la opción correcta. Usa much/many/a lot/few/little según el sustantivo.';

export const UNIT_26_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u26-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There isn\'t|No hay]] ____ ____ ____ ____ [[water|agua]] [[left|left]].', options: ['[[much|mucha]]', '[[many|muchas]]', '[[few|pocas]]'], correctAnswer: 'much', explanation: '[[Water|Agua]] = [[uncountable|incontable]] → [[much|mucho]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There are|Hay]] ____ ____ ____ ____ [[apples|manzanas]] [[in|en]] [[the|la]] [[fridge|nevera]].', options: ['[[many|muchas]]', '[[much|mucha]]', '[[little|poca]]'], correctAnswer: 'many', explanation: '[[Apples|Manzanas]] = [[countable|contable]] → [[many|muchos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[have|tengo]] ____ ____ ____ ____ [[of|de]] [[friends|amigos]] [[here|aquí]].', options: ['[[a lot|muchos]]', '[[much|mucho]]', '[[little|poco]]'], correctAnswer: 'a lot', acceptableAnswers: ['a lot'], explanation: '[[A lot of|Muchos]] [[works with both|funciona con ambos]] [[countable and uncountable|contables e incontables]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There is|Hay]] ____ ____ ____ ____ [[sugar|azúcar]] [[in|en]] [[this|esta]] [[coffee|café]].', options: ['[[little|poca]]', '[[few|pocas]]', '[[many|muchas]]'], correctAnswer: 'little', explanation: '[[Sugar|Azúcar]] = [[uncountable|incontable]] → [[little|poco]] [[for small amount|para cantidad pequeña]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Very|Muy]] ____ ____ ____ ____ [[people|gente]] [[came|vino]] [[to|a]] [[the|la]] [[party|fiesta]].', options: ['[[few|pocas]]', '[[little|poca]]', '[[much|mucha]]'], correctAnswer: 'few', explanation: '[[People|Gente]] = [[countable|contable]] → [[few|pocos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g6', type: 'multiple-choice', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuánta]] ____ ____ ____ ____ [[milk|leche]] [[do you need|necesitas]]?', options: ['[[much|leche]]', '[[many|leche]]', '[[few|leche]]'], correctAnswer: 0, explanation: '[[Milk|Leche]] = [[uncountable|incontable]] → [[how much|cuánta]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[How|Cuántos]] ____ ____ ____ ____ [[eggs|huevos]] [[are there|hay]]?', options: ['[[many|huevos]]', '[[much|huevos]]', '[[little|huevos]]'], correctAnswer: 'many', acceptableAnswers: ['many'], explanation: '[[Eggs|Huevos]] = [[countable|contable]] → [[how many|cuántos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[drinks|bebe]] ____ ____ ____ ____ [[of|de]] [[coffee|café]] [[every|cada]] [[day|día]].', options: ['[[a lot|mucho]]', '[[few|pocos]]', '[[many|muchos]]'], correctAnswer: 'a lot', acceptableAnswers: ['a lot'], explanation: '[[A lot of|Mucho]] + [[uncountable|incontable]] [[coffee|café]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[have|tenemos]] ____ ____ ____ ____ [[time|tiempo]] [[left|left]].', options: ['[[little|poco]]', '[[few|pocos]]', '[[many|muchos]]'], correctAnswer: 'little', explanation: '[[Time|Tiempo]] = [[uncountable|incontable]] → [[little|poco]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There are|Hay]] ____ ____ ____ ____ [[restaurants|restaurantes]] [[in|en]] [[this|esta]] [[street|calle]].', options: ['[[a few|unos pocos]]', '[[a little|un poco de]]', '[[much|mucha]]'], correctAnswer: 'a few', acceptableAnswers: ['a few'], explanation: '[[A few|Unos pocos]] = [[some|algunos]] [[with countable|con contables]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Add|Añade]] ____ ____ ____ ____ [[salt|sal]] [[to|a]] [[the|la]] [[soup|sopa]].', options: ['[[a little|un poco de]]', '[[a few|unos pocos]]', '[[many|muchos]]'], correctAnswer: 'a little', acceptableAnswers: ['a little'], explanation: '[[A little|Un poco de]] + [[uncountable|incontable]] [[salt|sal]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[don\'t|no]] [[eat|como]] ____ ____ ____ ____ [[meat|carne]].', options: ['[[much|mucha]]', '[[many|mucha]]', '[[few|poca]]'], correctAnswer: 0, explanation: '[[Meat|Carne]] = [[uncountable|incontable]] → [[much|mucho]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There are|Hay]] ____ ____ ____ ____ [[vegetables|verduras]] [[in|en]] [[the|la]] [[salad|ensalada]].', options: ['[[a lot of|muchas]]', '[[much|mucha]]', '[[little|poca]]'], correctAnswer: 'a lot of', acceptableAnswers: ['a lot of'], explanation: '[[Vegetables|Verduras]] = [[countable|contable]] → [[a lot of|muchas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[need|necesitamos]] ____ ____ ____ ____ [[bread|pan]] [[for|para]] [[dinner|cena]].', options: ['[[some|algo de]]', '[[many|muchos]]', '[[few|pocos]]'], correctAnswer: 'some', acceptableAnswers: ['some'], explanation: '[[Some|Algo de]] [[works with uncountable|funciona con incontables]] [[bread|pan]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u26-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Quantifiers', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Only|Solo]] ____ ____ ____ ____ [[students|estudiantes]] [[passed|aprobaron]] [[the|el]] [[exam|examen]].', options: ['[[a few|unos pocos]]', '[[a little|un poco de]]', '[[much|mucha]]'], correctAnswer: 0, explanation: '[[A few|Unos pocos]] = [[small positive number|pequeño número positivo]] [[with countable|con contables]].' }] }, topicName: 'Grammar' },
];
