/**
 * Unidad 33 B1 — Lección 1: Gramática (Question tags)
 * 15 ejercicios: isn't it?, don't you?, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Question Tags|Coletillas interrogativas]]';
const INSTRUCTIONS = 'Completa con la question tag correcta.';

export const UNIT_33_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u33-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s|Es]] [[a nice day|un buen día]], ____ ____ ____ ____?', options: ["[[isn't it|no es así]]", "[[is it|es así]]", "[[doesn't it|no es así]]"], correctAnswer: "isn't it", acceptableAnswers: ["isn't it"], explanation: "[[Positive statement|Afirmación positiva]] → [[negative tag|tag negativa]]: [[isn't it|no es así]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] [[like|te gusta]] [[this restaurant|este restaurante]], ____ ____ ____ ____?', options: ["[[don't you|no te gusta]]", "[[do you|te gusta]]", "[[doesn't you|no te gusta]]"], correctAnswer: "don't you", acceptableAnswers: ["don't you"], explanation: "[[You like|Te gusta]] → [[don't you|no te gusta]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[works|trabaja]] [[at the bank|en el banco]], ____ ____ ____ ____?', options: ["[[doesn't she|no trabaja]]", "[[does she|trabaja]]", "[[isn't she|no es]]"], correctAnswer: "doesn't she", acceptableAnswers: ["doesn't she"], explanation: "[[She works|Ella trabaja]] → [[doesn't she|no trabaja]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[They|Ellos]] [[haven't|no han]] [[finished|terminado]] [[yet|todavía]], ____ ____ ____ ____?", options: ['[[have they|han]]', '[[haven\'t they|no han]]', '[[did they|hicieron]]'], correctAnswer: 'have they', acceptableAnswers: ['have they'], explanation: "[[Negative statement|Afirmación negativa]] → [[positive tag|tag positiva]]: [[have they|han]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The doctor|El doctor]] [[is|está]] [[available|disponible]] [[now|ahora]], ____ ____ ____ ____?', options: ["[[isn't he|no está]]", "[[is he|está]]", "[[doesn't he|no está]]"], correctAnswer: "isn't he", acceptableAnswers: ["isn't he"], explanation: "[[The doctor is|El doctor está]] → [[isn't he|no está]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[can|podemos]] [[pay|pagar]] [[by card|con tarjeta]], ____ ____ ____ ____?', options: ["[[can't we|no podemos]]", "[[can we|podemos]]", "[[don't we|no]]"], correctAnswer: "can't we", acceptableAnswers: ["can't we"], explanation: "[[We can|Podemos]] → [[can't we|no podemos]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[He|Él]] [[didn't|no]] [[go|fue]] [[to the bank|al banco]] [[yesterday|ayer]], ____ ____ ____ ____?", options: ['[[did he|fue]]', '[[didn\'t he|no fue]]', '[[does he|va]]'], correctAnswer: 'did he', acceptableAnswers: ['did he'], explanation: "[[Negative statement|Afirmación negativa]] → [[positive tag|tag positiva]]: [[did he|fue]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] [[need|necesitas]] [[an appointment|una cita]] [[for the doctor|para el doctor]], ____ ____ ____ ____?', options: ["[[don't you|no necesitas]]", "[[do you|necesitas]]", "[[needn't you|no necesitas]]"], correctAnswer: 0, explanation: "[[You need|Necesitas]] → [[don't you|no necesitas]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It|Eso]] [[was|era]] [[a good service|un buen servicio]], ____ ____ ____ ____?', options: ["[[wasn't it|no era]]", "[[was it|era]]", "[[isn't it|no es]]"], correctAnswer: "wasn't it", acceptableAnswers: ["wasn't it"], explanation: "[[It was|Era]] → [[wasn't it|no era]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[There|Hay]] [[is|está]] [[a pharmacy|una farmacia]] [[nearby|cerca]], ____ ____ ____ ____?', options: ["[[isn't there|no hay]]", "[[is there|hay]]", "[[aren't there|no hay]]"], correctAnswer: "isn't there", acceptableAnswers: ["isn't there"], explanation: "[[There is|Hay]] → [[isn't there|no hay]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: "[[They|Ellos]] [[won't|no]] [[accept|aceptarán]] [[credit cards|tarjetas de crédito]], ____ ____ ____ ____?", options: ['[[will they|aceptarán]]', '[[won\'t they|no aceptarán]]', '[[do they|aceptan]]'], correctAnswer: 'will they', acceptableAnswers: ['will they'], explanation: "[[Negative statement|Afirmación negativa]] → [[positive tag|tag positiva]]: [[will they|aceptarán]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[am|soy]] [[right|correcto]], ____ ____ ____ ____?', options: ["[[aren't I|no soy]]", "[[am I|soy]]", "[[isn't I|no soy]]"], correctAnswer: 0, explanation: "[[I am|Soy]] → [[aren't I|no soy]] ([[exception|excepción]])." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The restaurant|El restaurante]] [[opens|abre]] [[at|a]] [[seven|siete]], ____ ____ ____ ____?', options: ["[[doesn't it|no abre]]", "[[does it|abre]]", "[[isn't it|no es]]"], correctAnswer: "doesn't it", acceptableAnswers: ["doesn't it"], explanation: "[[It opens|Abre]] → [[doesn't it|no abre]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] [[have|tienes]] [[an account|una cuenta]] [[at this bank|en este banco]], ____ ____ ____ ____?', options: ["[[don't you|no tienes]]", "[[do you|tienes]]", "[[haven't you|no has]]"], correctAnswer: "don't you", acceptableAnswers: ["don't you"], explanation: "[[You have|Tienes]] ([[possess|poseer]]) → [[don't you|no tienes]]." }] }, topicName: 'Grammar' },
  { id: 'b1-u33-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Question Tags', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Let\'s|Vamos a]] [[order|pedir]] [[now|ahora]], ____ ____ ____ ____?', options: ["[[shall we|vamos]]", "[[don't we|no]]", "[[do we|sí]]"], correctAnswer: 0, explanation: "[[Let's|Vamos a]] → [[shall we|vamos]]." }] }, topicName: 'Grammar' },
];
