/**
 * Unidad 58 B1 — Lección 6: Expresión escrita (Places: town & countryside)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_58_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u58-l6-w1', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una describiendo tu pueblo o ciudad y otra con lo que te gusta de él.', expressionHint: '[[I live in|Vivo en]]... [[I like|Me gusta]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The new bridge|El nuevo puente]] ____ ____ ____ ____ [[built|construido]] [[last year|el año pasado]].', options: ['[[was built|fue construido]]', '[[is built|es construido]]', '[[built|construyó]]'], correctAnswer: 'was built', acceptableAnswers: ['was built'], explanation: '[[Passive past|Pasiva pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[rather|preferiría]] [[live|vivir]] [[in the countryside|en el campo]] [[than in the city|que en la ciudad]].', options: ['[[would rather|preferiría]]', '[[had better|más vale que]]', '[[must|debo]]'], correctAnswer: 'would rather', acceptableAnswers: ['would rather'], explanation: '[[Would rather|Preferiría]] [[for preference|para preferencia]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[There|Hay]] ____ ____ ____ ____ [[many|muchos]] [[shops|tiendas]] [[in the town centre|en el centro de la ciudad]].', options: ['[[are many|muchas]]', '[[is many|mucho]]', '[[are much|muchas]]'], correctAnswer: 'are many', acceptableAnswers: ['are many'], explanation: '[[There are|Hay]] [[+ plural|+ plural]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w5', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando although para contrastar tamaño y características de un lugar.', expressionHint: '[[Although|Aunque]] [[it is small|es pequeño]]... [[it has|tiene]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The park|El parque]] ____ ____ ____ ____ [[visited|visitado]] [[by thousands of people|por miles de personas]] [[every day|cada día]].', options: ['[[is visited|es visitado]]', '[[visits|visita]]', '[[was visited|fue visitado]]'], correctAnswer: 'is visited', acceptableAnswers: ['is visited'], explanation: '[[Passive present|Pasiva presente]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[If|Si]] [[you|tú]] ____ ____ ____ ____ [[to the countryside|al campo]] [[next weekend|el próximo fin de semana]], [[you will love it|te encantará]].', options: ['[[go|vas]]', '[[went|fueras]]', '[[had gone|hubieras ido]]'], correctAnswer: 'go', acceptableAnswers: ['go'], explanation: '[[First conditional|Primer condicional]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The village|El pueblo]] ____ ____ ____ ____ [[I grew up|crecí]] [[is|es]] [[very small|muy pequeño]].', options: ['[[where|donde]]', '[[which|que]]', '[[who|quien]]'], correctAnswer: 'where', acceptableAnswers: ['where'], explanation: '[[Relative clause|Oración de relativo]]: [[where for places|where para lugares]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w9', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una describiendo un lugar con passive y otra con reported speech.', expressionHint: 'Passive: [[The building was built|El edificio fue construido]]... Reported: [[He told me|Me dijo]]...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[me|me]] [[that|que]] [[she had moved|había mudado]] [[to a new flat|a un piso nuevo]].', options: ['[[told|dijo]]', '[[said|dijo]]', '[[asked|preguntó]]'], correctAnswer: 'told', acceptableAnswers: ['told'], explanation: '[[Tell + person|Tell + persona]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The river|El río]] ____ ____ ____ ____ [[through|a través de]] [[the valley|el valle]].', options: ['[[flows|fluye]]', '[[flow|fluye]]', '[[is flowing|está fluyendo]]'], correctAnswer: 'flows', acceptableAnswers: ['flows'], explanation: '[[Present simple|Presente simple]]: [[general fact|hecho general]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w12', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando second conditional sobre dónde te gustaría vivir.', expressionHint: '[[If I lived|Si viviera]]... [[I would have|tendría]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The mountains|Las montañas]] ____ ____ ____ ____ [[covered|cubiertas]] [[with snow|con nieve]] [[in winter|en invierno]].', options: ['[[are covered|están cubiertas]]', '[[cover|cubren]]', '[[were covered|estaban cubiertas]]'], correctAnswer: 'are covered', acceptableAnswers: ['are covered'], explanation: '[[Passive present|Pasiva presente]].' }] }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w14', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase de consejo para alguien que visita tu ciudad usando should.', expressionHint: '[[You should|Deberías]] [[visit|visitar]]... [[take|tomar]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u58-l6-w15', type: 'writing', level: 'B1', topic: 'Places', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) comparando tu pueblo/ciudad con el campo o otra ciudad.', expressionHint: 'Incluye: dónde vives, qué tiene, qué prefieres y por qué.', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
