/**
 * Unidad 31 B1 — Lección 1: Gramática (Defining relative clauses)
 * 15 ejercicios: who, which, that - repaso + ampliación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Defining Relative Clauses|Oraciones de relativo especificativas]]';
const INSTRUCTIONS = 'Completa con who, which o that según corresponda.';

export const UNIT_31_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u31-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The woman|La mujer]] ____ ____ ____ ____ [[lives|vive]] [[next door|al lado]] [[is|es]] [[a vet|veterinaria]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The book|El libro]] ____ ____ ____ ____ [[I bought|compré]] [[yesterday|ayer]] [[is|es]] [[very interesting|muy interesante]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'which', acceptableAnswers: ['which', 'that'], explanation: '[[Which|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Animals|Los animales]] ____ ____ ____ ____ [[live|viven]] [[in the wild|en libertad]] [[are|son]] [[free|libres]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That|Que]] [[for animals|para animales]] [[or things|o cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The man|El hombre]] ____ ____ ____ ____ [[saw|vio]] [[the bear|el oso]] [[reported it|lo reportó]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The plants|Las plantas]] ____ ____ ____ ____ [[grow|crecen]] [[here|aquí]] [[need|necesitan]] [[lots of water|mucha agua]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The landscape|El paisaje]] ____ ____ ____ ____ [[we visited|visitamos]] [[was|era]] [[breathtaking|impresionante]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Anyone|Cualquiera]] ____ ____ ____ ____ [[loves|ama]] [[wildlife|vida silvestre]] [[should visit|debería visitar]] [[this park|este parque]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The river|El río]] ____ ____ ____ ____ [[flows|fluye]] [[through|a través de]] [[the valley|el valle]] [[is|es]] [[clean|limpio]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 1, explanation: '[[Which/that|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The bird|El pájaro]] ____ ____ ____ ____ [[I saw|vi]] [[was|era]] [[an eagle|un águila]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which|Que]] [[for animals|para animales]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The mountain|La montaña]] ____ ____ ____ ____ [[we climbed|escalamos]] [[is|es]] [[over 3000m|más de 3000m]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[People|Las personas]] ____ ____ ____ ____ [[protect|protegen]] [[wildlife|vida silvestre]] [[are|son]] [[heroes|héroes]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g12', type: 'multiple-choice', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The forest|El bosque]] ____ ____ ____ ____ [[covers|cubre]] [[this area|esta zona]] [[is|es]] [[ancient|antiguo]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 1, explanation: '[[Which/that|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The flowers|Las flores]] ____ ____ ____ ____ [[bloom|florecen]] [[in spring|en primavera]] [[are|son]] [[beautiful|hermosas]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'that', acceptableAnswers: ['that', 'which'], explanation: '[[That/which|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The scientist|El científico]] ____ ____ ____ ____ [[studies|estudia]] [[endangered species|especies en peligro]] [[gave|dio]] [[a talk|una charla]].', options: ['[[who|que]]', '[[which|que]]', '[[whose|cuyo]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u31-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Defining Relative Clauses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The lake|El lago]] ____ ____ ____ ____ [[we swam in|nadamos]] [[was|era]] [[very cold|muy frío]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 1, explanation: '[[Which/that|Que]] [[for things|para cosas]].' }] }, topicName: 'Grammar' },
];
