/**
 * Unidad 34 B1 — Lección 5: Expresión oral (-ed/-ing adjectives, Personal feelings)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_34_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u34-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I|Yo]] [[was|estaba]] [[bored|aburrido]] [[because|porque]] [[the film|la película]] [[was|era]] [[boring|aburrida]].', expectedResponse: 'I was bored because the film was boring.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The news|La noticia]] [[was|era]] [[exciting|emocionante]]. [[I|Yo]] [[felt|me sentí]] [[excited|emocionado]].', expectedResponse: 'The news was exciting. I felt excited.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[was|estaba]] [[worried|preocupada]] [[about|por]] [[the exam|el examen]].', expectedResponse: 'She was worried about the exam.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The match|El partido]] [[was|era]] [[exciting|emocionante]]. [[We|Nosotros]] [[were|estábamos]] [[excited|emocionados]].', expectedResponse: 'The match was exciting. We were excited.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[I|Yo]] [[find|encuentro]] [[this book|este libro]] [[interesting|interesante]].', expectedResponse: 'I find this book interesting.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[was|estaba]] [[surprised|sorprendido]] [[when|cuando]] [[he heard|oyó]] [[the news|la noticia]].', expectedResponse: 'He was surprised when he heard the news.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The film|La película]] [[was|era]] [[boring|aburrida]]. [[I|Yo]] [[almost|casi]] [[fell asleep|me dormí]].', expectedResponse: 'The film was boring. I almost fell asleep.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[interested|interesado]] [[in|en]] [[learning|aprender]] [[English|inglés]].', expectedResponse: 'I am interested in learning English.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que te aburrió y algo que te emocionó.', targetText: '[[I|Yo]] [[was|estaba]] ____ [[because|porque]] ____. [[I|Yo]] [[was|estaba]] ____ [[because|porque]] ____.', expectedResponse: 'I was bored because... I was excited because...' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que encuentras interesante.', targetText: '[[I|Yo]] [[find|encuentro]] ____ [[interesting|interesante]].', expectedResponse: 'I find [something] interesting.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The journey|El viaje]] [[was|era]] [[tiring|agotador]]. [[I|Yo]] [[was|estaba]] [[tired|cansado]].', expectedResponse: 'The journey was tiring. I was tired.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[were|estábamos]] [[disappointed|decepcionados]] [[when|cuando]] [[we heard|oímos]] [[the result|el resultado]].', expectedResponse: 'We were disappointed when we heard the result.' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[The situation|La situación]] [[is|es]] [[confusing|confusa]]. [[I|Yo]] [[don\'t know|no sé]] [[what to do|qué hacer]].', expectedResponse: "The situation is confusing. I don't know what to do." }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una situación que te preocupó o te sorprendió.', targetText: '[[I|Yo]] [[was|estaba]] ____ [[when|cuando]] ____.', expectedResponse: 'I was [worried/surprised] when...' }, topicName: 'Speaking' },
  { id: 'b1-u34-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Personal Feelings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe algo emocionante que viviste y cómo te sentiste.', targetText: '____. ____.', expectedResponse: 'The [event] was exciting. I felt excited/worried/disappointed...' }, topicName: 'Speaking' },
];
