/**
 * Unidad 19 B1 — Lección 2: Vocabulario (Language)
 * 15 ejercicios: translate, pronounce, grammar, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Language|Idioma]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_19_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u19-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "traducir"|Qué palabra significa "traducir"]]?', options: ['[[translate|traducir]]', '[[pronounce|pronunciar]]', '[[spell|deletrear]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "pronunciar"|Qué palabra significa "pronunciar"]]?', options: ['[[pronounce|pronunciar]]', '[[translate|traducir]]', '[[speak|hablar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "gramática"|Qué palabra significa "gramática"]]?', options: ['[[grammar|gramática]]', '[[vocabulary|vocabulario]]', '[[pronunciation|pronunciación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "vocabulario"|Qué palabra significa "vocabulario"]]?', options: ['[[vocabulary|vocabulario]]', '[[grammar|gramática]]', '[[spelling|ortografía]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "deletrear"|Qué palabra significa "deletrear"]]?', options: ['[[spell|deletrear]]', '[[pronounce|pronunciar]]', '[[write|escribir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "pronunciación"|Qué palabra significa "pronunciación"]]?', options: ['[[pronunciation|pronunciación]]', '[[grammar|gramática]]', '[[vocabulary|vocabulario]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "fluido"|Qué palabra significa "fluido"]]?', options: ['[[fluent|fluido]]', '[[native|nativo]]', '[[bilingual|bilingüe]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "nativo"|Qué palabra significa "nativo"]]?', options: ['[[native|nativo]]', '[[fluent|fluido]]', '[[foreign|extranjero]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "bilingüe"|Qué palabra significa "bilingüe"]]?', options: ['[[bilingual|bilingüe]]', '[[multilingual|multilingüe]]', '[[fluent|fluido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "expresión"|Qué palabra significa "expresión"]]?', options: ['[[expression|expresión]]', '[[phrase|frase]]', '[[idiom|modismo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "frase"|Qué palabra significa "frase"]]?', options: ['[[phrase|frase]]', '[[sentence|oración]]', '[[word|palabra]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "modismo" or saying|Qué palabra significa "modismo" o dicho]]?', options: ['[[idiom|modismo]]', '[[expression|expresión]]', '[[phrase|frase]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "acento"|Qué palabra significa "acento"]]?', options: ['[[accent|acento]]', '[[pronunciation|pronunciación]]', '[[dialect|dialecto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "aprender de memoria"|Qué palabra significa "aprender de memoria"]]?', options: ['[[memorise|aprender de memoria]]', '[[practise|practicar]]', '[[repeat|repetir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u19-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "traductor"|Qué palabra significa "traductor"]]?', options: ['[[translator|traductor]]', '[[interpreter|intérprete]]', '[[teacher|profesor]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
