/**
 * Unidad 13 B1 — Lección 5: Expresión oral (First vs second conditional, entertainment)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_13_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u13-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[If|Si]] [[it|ello]] [[rains|llueve]] [[tomorrow|mañana]], [[we|nosotros]] [[will stay|nos quedaremos]] [[at home|en casa]] [[and|y]] [[watch|veremos]] [[a film|una película]].', expectedResponse: 'If it rains tomorrow, we will stay at home and watch a film.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[could|pudiera]] [[meet|conocer]] [[any celebrity|cualquier celebridad]], [[I|yo]] [[would choose|elegiría]] [[a musician|un músico]].', expectedResponse: 'If I could meet any celebrity, I would choose a musician.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[you|tú]] [[book|reservas]] [[the tickets|las entradas]] [[early|temprano]], [[you|tú]] [[will get|conseguirás]] [[a discount|un descuento]].', expectedResponse: 'If you book the tickets early, you will get a discount.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[concerts|los conciertos]] [[were|fueran]] [[free|gratis]], [[more people|más gente]] [[would attend|asistiría]].', expectedResponse: 'If concerts were free, more people would attend.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[When|Cuando]] [[the new album|el nuevo álbum]] [[comes out|salga]], [[I|yo]] [[will buy|compraré]] [[it|ello]].', expectedResponse: 'When the new album comes out, I will buy it.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[I|yo]] [[were|fuera]] [[rich|rico]], [[I|yo]] [[would buy|compraría]] [[tickets|entradas]] [[for every concert|para cada concierto]].', expectedResponse: 'If I were rich, I would buy tickets for every concert.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The film|La película]] [[has|tiene]] [[great reviews|grandes reseñas]] [[from|de]] [[the audience|la audiencia]].', expectedResponse: 'The film has great reviews from the audience.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[would go|iría]] [[to the cinema|al cine]] [[more often|más a menudo]] [[if|si]] [[films|las películas]] [[were|fueran]] [[cheaper|más baratas]].', expectedResponse: 'I would go to the cinema more often if films were cheaper.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un plan real para el fin de semana (first conditional).', targetText: '[[If|Si]] ____, ____.', expectedResponse: 'If [present], I will [future action].' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un deseo hipotético sobre entretenimiento (second conditional).', targetText: '[[If|Si]] ____, ____.', expectedResponse: 'If [past], I would [result].' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Streaming services|Los servicios de streaming]] [[have changed|han cambiado]] [[the way|la forma]] [[we watch|en que vemos]] [[TV|la televisión]].', expectedResponse: 'Streaming services have changed the way we watch TV.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Live performances|Actuaciones en vivo]] [[are|son]] [[more exciting|más emocionantes]] [[than|que]] [[recorded music|música grabada]].', expectedResponse: 'Live performances are more exciting than recorded music.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[If|Si]] [[the show|el espectáculo]] [[is|es]] [[good|bueno]] [[tonight|esta noche]], [[I|yo]] [[will recommend|recomendaré]] [[it|ello]] [[to my friends|a mis amigos]].', expectedResponse: 'If the show is good tonight, I will recommend it to my friends.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: la diferencia entre first y second conditional con un ejemplo de cada uno.', targetText: '____. ____.', expectedResponse: 'First: If it rains, I will stay home. Second: If I had time, I would go to the concert.' }, topicName: 'Speaking' },
  { id: 'b1-u13-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Entertainment', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe tus planes de entretenimiento para el próximo fin de semana usando first conditional.', targetText: '____. ____.', expectedResponse: 'If [condition], I will [entertainment activity]. When [time], I will [activity].' }, topicName: 'Speaking' },
];
