/**
 * Unidad 16 B1 — Lección 6: Expresión escrita (Passive voice, technology)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_16_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u16-l6-w1', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre cómo se usa la tecnología en tu vida diaria. Usa voz pasiva.', expressionHint: 'Puedes usar: [[are used|son usados]], [[is stored|se almacena]], [[was developed|fue desarrollado]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase con la forma correcta de la voz pasiva.', questions: [{ question: '[[Smartphones|Los smartphones]] ____ ____ ____ ____ [[used|usados]] [[every day|cada día]].', options: ['[[are|son]]', '[[is|es]]', '[[were|fueron]]'], correctAnswer: 'are', acceptableAnswers: ['are'], explanation: '[[Passive present|Pasiva presente]]: [[plural + are + past participle|plural + are + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[This app|Esta aplicación]] ____ ____ ____ ____ [[developed|desarrollada]] [[last year|el año pasado]].', options: ['[[was|fue]]', '[[is|es]]', '[[are|son]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Passive past|Pasiva pasado]]: [[singular + was + past participle|singular + was + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: '[[The data|Los datos]] ____ ____ ____ ____ [[stored|almacenados]] [[in the cloud|en la nube]].', options: ['[[are|son]]', '[[is|es]]', '[[were|fueron]]'], correctAnswer: 'are', acceptableAnswers: ['are'], explanation: '[[Passive present|Pasiva presente]]: [[plural + are + past participle|plural + are + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w5', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una en pasiva presente y otra en pasiva pasado sobre tecnología.', expressionHint: 'Puedes usar: [[is/are + past participle|is/are + participio pasado]], [[was/were + past participle|was/were + participio pasado]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The device|El dispositivo]] ____ ____ ____ ____ [[manufactured|fabricado]] [[by|por]] [[a famous company|una empresa famosa]].', options: ['[[was|fue]]', '[[is|es]]', '[[were|fueron]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Passive past|Pasiva pasado]] + [[by for agent|by para el agente]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Updates|Las actualizaciones]] ____ ____ ____ ____ [[downloaded|descargadas]] [[automatically|automáticamente]].', options: ['[[are|son]]', '[[is|es]]', '[[was|fue]]'], correctAnswer: 'are', acceptableAnswers: ['are'], explanation: '[[Passive present|Pasiva presente]]: [[plural + are + past participle|plural + are + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra de tecnología correcta.', questions: [{ question: '[[I need to|Necesito]] ____ ____ ____ ____ [[my smartphone|mi smartphone]] [[before|antes]] [[the meeting|la reunión]].', options: ['[[update|actualizar]]', '[[download|descargar]]', '[[install|instalar]]'], correctAnswer: 'update', acceptableAnswers: ['update'], explanation: '[[Update|Actualizar]] [[means to get the latest version|significa obtener la última versión]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w9', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre un dispositivo que compraste o usas. Usa voz pasiva.', expressionHint: 'Puedes usar: [[was bought|fue comprado]], [[is used|es usado]], [[was made|fue hecho]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con was o were.', questions: [{ question: '[[The files|Los archivos]] ____ ____ ____ ____ [[deleted|eliminados]] [[by mistake|por error]] [[yesterday|ayer]].', options: ['[[were|fueron]]', '[[was|fue]]', '[[are|son]]'], correctAnswer: 'were', acceptableAnswers: ['were'], explanation: '[[Passive past|Pasiva pasado]]: [[plural + were + past participle|plural + were + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The software|El software]] ____ ____ ____ ____ [[updated|actualizado]] [[last month|el mes pasado]].', options: ['[[was|fue]]', '[[is|es]]', '[[are|son]]'], correctAnswer: 'was', acceptableAnswers: ['was'], explanation: '[[Passive past|Pasiva pasado]]: [[singular + was + past participle|singular + was + participio pasado]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w12', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando voz pasiva con "by" para indicar quién realizó la acción.', expressionHint: '[[The app was developed by...|La aplicación fue desarrollada por...]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la expresión correcta.', questions: [{ question: '[[Which word means "aplicación"|Qué palabra significa "aplicación"]]?', options: ['[[app|aplicación]]', '[[device|dispositivo]]', '[[software|software]]'], correctAnswer: 'app', acceptableAnswers: ['app'], explanation: '[[App|Aplicación]] [[short for application|abreviatura de application]].' }] }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w14', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una en pasiva presente (is/are) y otra en pasiva pasado (was/were) sobre tecnología.', expressionHint: 'Ejemplo: Emails are sent... / The laptop was repaired...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u16-l6-w15', type: 'writing', level: 'B1', topic: 'Technology', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre cómo la tecnología se usa en tu trabajo o estudios. Usa voz pasiva (is/are + past participle, was/were + past participle).', expressionHint: 'Puedes usar: [[are used|son usados]], [[is stored|se almacena]], [[was installed|fue instalado]], [[are sent|son enviados]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
