/**
 * Unidad 18 B1 — Lección 2: Vocabulario (Communication)
 * 15 ejercicios: message, email, text, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Communication|Comunicación]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_18_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u18-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "mensaje"|Qué palabra significa "mensaje"]]?', options: ['[[message|mensaje]]', '[[email|email]]', '[[text|mensaje de texto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "correo electrónico"|Qué palabra significa "correo electrónico"]]?', options: ['[[email|email]]', '[[text|mensaje de texto]]', '[[letter|carta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "mensaje de texto" or SMS|Qué palabra significa "mensaje de texto" o SMS]]?', options: ['[[text|mensaje de texto]]', '[[message|mensaje]]', '[[call|llamada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "llamada"|Qué palabra significa "llamada"]]?', options: ['[[call|llamada]]', '[[reply|respuesta]]', '[[contact|contacto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "respuesta"|Qué palabra significa "respuesta"]]?', options: ['[[reply|respuesta]]', '[[message|mensaje]]', '[[request|solicitud]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "contacto"|Qué palabra significa "contacto"]]?', options: ['[[contact|contacto]]', '[[connection|conexión]]', '[[conversation|conversación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "conversación"|Qué palabra significa "conversación"]]?', options: ['[[conversation|conversación]]', '[[discussion|discusión]]', '[[chat|chat]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "chat" or online conversation|Qué palabra significa "chat" o conversación online]]?', options: ['[[chat|chat]]', '[[email|email]]', '[[letter|carta]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "notificar" or inform|Qué palabra significa "notificar" o informar]]?', options: ['[[notify|notificar]]', '[[reply|responder]]', '[[send|enviar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "enviar"|Qué palabra significa "enviar"]]?', options: ['[[send|enviar]]', '[[receive|recibir]]', '[[forward|reenviar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "recibir"|Qué palabra significa "recibir"]]?', options: ['[[receive|recibir]]', '[[send|enviar]]', '[[forward|reenviar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "reenviar"|Qué palabra significa "reenviar"]]?', options: ['[[forward|reenviar]]', '[[reply|responder]]', '[[attach|adjuntar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "adjuntar" a file|Qué palabra significa "adjuntar" un archivo]]?', options: ['[[attach|adjuntar]]', '[[download|descargar]]', '[[upload|subir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "buzón de entrada"|Qué palabra significa "buzón de entrada"]]?', options: ['[[inbox|buzón de entrada]]', '[[outbox|buzón de salida]]', '[[spam|spam]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u18-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Communication', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "asunto" of an email|Qué palabra significa "asunto" de un email]]?', options: ['[[subject|asunto]]', '[[attachment|adjunto]]', '[[signature|firma]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
