/**
 * Unidad 19 B1 — Lección 6: Expresión escrita (Reported speech questions/commands, language)
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_19_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u19-l6-w1', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases reportando una pregunta y una orden que un profesor te dio. Usa asked if/whether y told to.', expressionHint: 'Puedes usar: [[She asked me if...|Ella me preguntó si...]], [[He told me to...|Él me dijo que...]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase con la forma correcta.', questions: [{ question: '[[She asked me|Ella me preguntó]] ____ ____ ____ ____ [[I spoke|yo hablaba]] [[English|inglés]].', options: ['[[if|si]]', '[[that|que]]', '[[what|qué]]'], correctAnswer: 'if', acceptableAnswers: ['if', 'whether'], explanation: '[[Yes/No questions|Preguntas sí/no]]: [[asked + if/whether|asked + if/whether]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[The teacher told us|El profesor nos dijo]] ____ ____ ____ ____ [[practise|practicar]] [[our pronunciation|nuestra pronunciación]].', options: ['[[to|a]]', '[[that|que]]', '[[if|si]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: '[[Commands|Órdenes]]: [[told + to + infinitive|told + to + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: '[[He asked her|Él le preguntó]] ____ ____ ____ ____ [[how to pronounce|cómo pronunciar]] [[that word|esa palabra]].', options: ['[[how|cómo]]', '[[if|si]]', '[[that|que]]'], correctAnswer: 'how', acceptableAnswers: ['how'], explanation: '[[Wh- questions|Preguntas Wh-]]: [[keep the question word|mantenemos la palabra interrogativa]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w5', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con "asked if" y otra con "told to" sobre una clase de idiomas.', expressionHint: 'Puedes usar: [[The teacher asked me if I had studied...|El profesor me preguntó si había estudiado...]], [[She told me to practise...|Ella me dijo practicar...]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta para orden negativa.', questions: [{ question: '[[She told him|Ella le dijo]] ____ ____ ____ ____ ____ ____ ____ ____ [[forget|olvidar]] [[his homework|sus deberes]].', options: ["[[not to|no]]", '[[to not|a no]]', "[[don't|no]]"], correctAnswer: 'not to', acceptableAnswers: ['not to'], explanation: '[[Negative command|Orden negativa]]: [[told + not to + infinitive|told + not to + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con if o whether.', questions: [{ question: '[[They asked us|Ellos nos preguntaron]] ____ ____ ____ ____ [[we had studied|habíamos estudiado]] [[grammar|gramática]] [[before|antes]].', options: ['[[if|si]]', '[[that|que]]', '[[what|qué]]'], correctAnswer: 'if', acceptableAnswers: ['if', 'whether'], explanation: '[[If and whether|If y whether]] [[are both correct|son ambos correctos]] [[for yes/no questions|para preguntas sí/no]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[Which word means "traducir"|Qué palabra significa "traducir"]]?', options: ['[[translate|traducir]]', '[[pronounce|pronunciar]]', '[[spell|deletrear]]'], correctAnswer: 'translate', acceptableAnswers: ['translate'], explanation: '[[Translate|Traducir]] [[means to change from one language to another|significa cambiar de un idioma a otro]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w9', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases reportando preguntas y órdenes de una clase de idiomas.', expressionHint: 'Puedes usar: [[asked if/whether|preguntó si]], [[asked how/what|preguntó cómo/qué]], [[told to|dijo que]], [[told not to|dijo que no]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I asked her|Yo le pregunté]] ____ ____ ____ ____ [[what|qué]] [[the word meant|significaba la palabra]].', options: ['[[what|qué]]', '[[if|si]]', '[[that|que]]'], correctAnswer: 'what', acceptableAnswers: ['what'], explanation: '[[Wh- question|Pregunta Wh-]]: [[asked + what|asked + what]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Direct|Directo]]: "[[Do your homework|Haz los deberes]]". [[Reported|Indirecto]]: [[She told him|Ella le dijo]] ____ ____ ____ ____ ____ ____ ____ ____ [[do|hacer]] [[his homework|sus deberes]].', options: ['[[to|a]]', '[[that|que]]', '[[if|si]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: '[[Commands|Órdenes]]: [[told + to + infinitive|told + to + infinitivo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w12', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase reportando: "Can you translate this?"', expressionHint: '[[He/She asked me if I could translate...|Él/Ella me preguntó si podía traducir...]]', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la expresión correcta.', questions: [{ question: '[[Which word means "pronunciar"|Qué palabra significa "pronunciar"]]?', options: ['[[pronounce|pronunciar]]', '[[translate|traducir]]', '[[spell|deletrear]]'], correctAnswer: 'pronounce', acceptableAnswers: ['pronounce'], explanation: '[[Pronounce|Pronunciar]] [[means to say a word correctly|significa decir una palabra correctamente]].' }] }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w14', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una reportando una pregunta Wh- (how/what) y otra reportando una orden negativa (told not to).', expressionHint: 'Ejemplo: She asked me how to... / He told me not to...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u19-l6-w15', type: 'writing', level: 'B1', topic: 'Language', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre una clase de idiomas. Usa reported speech: asked if/whether, asked how/what, told to, told not to. Incluye vocabulario de idiomas.', expressionHint: 'Puedes usar: [[asked if|preguntó si]], [[asked how to pronounce|preguntó cómo pronunciar]], [[told us to practise|nos dijo practicar]], [[translate|traducir]], [[grammar|gramática]], [[pronunciation|pronunciación]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
