/**
 * Unidad 12 B1 — Lección 2: Vocabulario (Hypothetical situations)
 * 15 ejercicios: imagine, suppose, wish, dream, ideal, fantasy, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Hypothetical Situations|Situaciones hipotéticas]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_12_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u12-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "imaginar"|Qué palabra significa "imaginar"]]?', options: ['[[imagine|imaginar]]', '[[remember|recordar]]', '[[forget|olvidar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "suponer"|Qué palabra significa "suponer"]]?', options: ['[[suppose|suponer]]', '[[know|saber]]', '[[think|pensar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "desear" or "ojalá"|Qué palabra significa "desear" o "ojalá"]]?', options: ['[[wish|desear]]', '[[want|querer]]', '[[need|necesitar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "sueño" as something you wish for|Qué palabra significa "sueño" como algo que deseas]]?', options: ['[[dream|sueño]]', '[[sleep|sueño (dormir)]]', '[[nightmare|pesadilla]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "ideal"|Qué palabra significa "ideal"]]?', options: ['[[ideal|ideal]]', '[[real|real]]', '[[normal|normal]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "fantasía"|Qué palabra significa "fantasía"]]?', options: ['[[fantasy|fantasía]]', '[[reality|realidad]]', '[[truth|verdad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "imposible"|Qué palabra significa "imposible"]]?', options: ['[[impossible|imposible]]', '[[possible|posible]]', '[[probable|probable]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "irreal" or "imaginario"|Qué palabra significa "irreal" o "imaginario"]]?', options: ['[[unreal|irreal]]', '[[real|real]]', '[[true|verdadero]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which phrase means "en teoría"|Qué frase significa "en teoría"]]?', options: ['[[in theory|en teoría]]', '[[in practice|en la práctica]]', '[[in fact|de hecho]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which phrase means "en caso de que"|Qué frase significa "en caso de que"]]?', options: ['[[in case|en caso de que]]', '[[because|porque]]', '[[although|aunque]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "alternativa"|Qué palabra significa "alternativa"]]?', options: ['[[alternative|alternativa]]', '[[same|mismo]]', '[[only|único]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "hipotético"|Qué palabra significa "hipotético"]]?', options: ['[[hypothetical|hipotético]]', '[[certain|cierto]]', '[[sure|seguro]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "cambiar" in the sense of "what if"|Qué palabra significa "cambiar" en el sentido de "qué pasaría si"]]?', options: ['[[change|cambiar]]', '[[stay|quedarse]]', '[[keep|mantener]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which phrase means "qué pasaría si"|Qué frase significa "qué pasaría si"]]?', options: ['[[what if|qué pasaría si]]', '[[why not|por qué no]]', '[[how about|qué tal]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u12-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Hypothetical', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which word means "posible"|Qué palabra significa "posible"]]?', options: ['[[possible|posible]]', '[[impossible|imposible]]', '[[unlikely|poco probable]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
