/**
 * Unidad 35 B1 — Lección 2: Vocabulario (Repaso 31–34)
 * 15 ejercicios: mix natural world, environment, services, personal feelings
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Review 31–34|Repaso 31–34]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_35_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u35-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Animals and plants in nature|Animales y plantas en la naturaleza]]:', options: ['[[wildlife|vida silvestre]]', '[[pets|mascotas]]', '[[cattle|ganado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To use materials again|Usar materiales de nuevo]]:', options: ['[[recycle|reciclar]]', '[[throw away|tirar]]', '[[waste|desperdiciar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A meeting with a doctor|Una reunión con un médico]]:', options: ['[[appointment|cita]]', '[[reservation|reserva]]', '[[bill|factura]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When you have no interest|Cuando no tienes interés]]:', options: ['[[bored|aburrido]]', '[[excited|emocionado]]', '[[happy|feliz]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A large area of trees|Una gran área de árboles]]:', options: ['[[forest|bosque]]', '[[beach|playa]]', '[[desert|desierto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Harmful substances in air or water|Sustancias dañinas en aire o agua]]:', options: ['[[pollution|contaminación]]', '[[recycling|reciclaje]]', '[[nature|naturaleza]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A plastic card to pay|Una tarjeta de plástico para pagar]]:', options: ['[[credit card|tarjeta de crédito]]', '[[receipt|recibo]]', '[[bill|factura]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When you look forward to something|Cuando esperas algo con ilusión]]:', options: ['[[excited|emocionado]]', '[[sad|triste]]', '[[angry|enfadado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The view of the countryside|La vista del campo]]:', options: ['[[landscape|paisaje]]', '[[cityscape|paisaje urbano]]', '[[seascape|paisaje marino]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Climate change|Cambio climático]]:', options: ['[[global warming|cambio climático]]', '[[weather|tiempo]]', '[[pollution|contaminación]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where you buy medicine|Dónde compras medicinas]]:', options: ['[[pharmacy|farmacia]]', '[[supermarket|supermercado]]', '[[bank|banco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When something is not what you expected|Cuando algo no es lo que esperabas]]:', options: ['[[disappointed|decepcionado]]', '[[pleased|contento]]', '[[satisfied|satisfecho]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A bird of prey|Un ave de rapina]]:', options: ['[[eagle|águila]]', '[[sparrow|gorrión]]', '[[pigeon|paloma]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Extra money for good service|Dinero extra por buen servicio]]:', options: ['[[tip|propina]]', '[[bill|factura]]', '[[receipt|recibo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u35-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When you feel nervous about something|Cuando te sientes nervioso por algo]]:', options: ['[[worried|preocupado]]', '[[relaxed|relajado]]', '[[calm|tranquilo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
