/**
 * Unidad 5 B1 — Lección 5: Expresión oral (Repaso 1–4)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_5_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u5-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[She|Ella]] [[has|ha]] [[been|estado]] [[studying|estudiando]] [[for|durante]] [[two|dos]] [[hours|horas]].', expectedResponse: 'She has been studying for two hours.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[had|había]] [[already|ya]] [[finished|terminado]] [[before|antes]] [[I|yo]] [[arrived|llegué]].', expectedResponse: 'He had already finished before I arrived.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[went|fui]] [[to|a]] [[Paris|París]] [[yesterday|ayer]].', expectedResponse: 'I went to Paris yesterday.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[has|ha]] [[never|nunca]] [[been|estado]] [[to|en]] [[Japan|Japón]].', expectedResponse: 'She has never been to Japan.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[I|Yo]] [[have|he]] [[just|acabo de]] [[finished|terminado]] [[my|mi]] [[homework|deberes]].', expectedResponse: 'I have just finished my homework.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[By the time|Para cuando]] [[we|nosotros]] [[arrived|llegamos]], [[the film|la película]] [[had|había]] [[already|ya]] [[started|empezado]].', expectedResponse: 'By the time we arrived, the film had already started.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[They|Ellos]] [[have|han]] [[been|estado]] [[living|viviendo]] [[in|en]] [[London|Londres]] [[since|desde]] [[January|enero]].', expectedResponse: 'They have been living in London since January.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[visited|visité]] [[London|Londres]] [[last week|la semana pasada]].', expectedResponse: 'I visited London last week.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: cuánto tiempo llevas haciendo algo (estudiar, trabajar, vivir en un lugar).', targetText: '[[I|Yo]] [[have been|he estado]] ____ [[for|desde hace]] ____.', expectedResponse: 'I have been [verb+ing] for [duration].' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo que hiciste ayer y algo que nunca has hecho.', targetText: '____. ____.', expectedResponse: 'Yesterday I... I have never...' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[When|Cuando]] [[she|ella]] [[got|llegó]], [[the train|el tren]] [[had|había]] [[already|ya]] [[left|salido]].', expectedResponse: 'When she got there, the train had already left.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[has|ha]] [[already|ya]] [[booked|reservado]] [[the|el]] [[hotel|hotel]].', expectedResponse: 'She has already booked the hotel.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[had|había]] [[already|ya]] [[eaten|comido]] [[when|cuando]] [[she|ella]] [[invited|invitó]] [[me|me]].', expectedResponse: 'I had already eaten when she invited me.' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una experiencia que tuviste (usando Past Perfect para algo que había pasado antes).', targetText: '____. ____.', expectedResponse: 'When I arrived, ... had already...' }, topicName: 'Speaking' },
  { id: 'b1-u5-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Review 1-4', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases algo que llevas haciendo tiempo, algo que hiciste en el pasado y algo que acabas de hacer.', targetText: '____. ____. ____.', expectedResponse: 'I have been... for... Last week I... I have just...' }, topicName: 'Speaking' },
];
