/**
 * Unidad 1 B1 — Lección 5: Expresión oral (Repaso personal info, feelings)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_1_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u1-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I|Yo]] [[have|he]] [[been|estado]] [[living|viviendo]] [[here|aquí]] [[for|desde hace]] [[three|tres]] [[years|años]].', expectedResponse: 'I have been living here for three years.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[has|ha]] [[never|nunca]] [[been|estado]] [[to|en]] [[Japan|Japón]].', expectedResponse: 'She has never been to Japan.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[used to|solía]] [[feel|sentirme]] [[nervous|nervioso]] [[but|pero]] [[now|ahora]] [[I|yo]] [[am|estoy]] [[more|más]] [[confident|seguro]].', expectedResponse: 'I used to feel nervous but now I am more confident.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[it|]] [[rains|llueve]] [[tomorrow|mañana]], [[I|yo]] [[will|me]] [[stay|quedaré]] [[at|en]] [[home|casa]].', expectedResponse: 'If it rains tomorrow, I will stay at home.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[The|El]] [[person|persona]] [[who|que]] [[helped|ayudó]] [[me|me]] [[was|era]] [[very|muy]] [[kind|amable]].', expectedResponse: 'The person who helped me was very kind.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[have to|tengo que]] [[work|trabajar]] [[early|temprano]] [[tomorrow|mañana]].', expectedResponse: 'I have to work early tomorrow.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[had|había]] [[already|ya]] [[finished|terminado]] [[his|su]] [[homework|deberes]] [[before|antes]] [[I|yo]] [[arrived|llegué]].', expectedResponse: 'He had already finished his homework before I arrived.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[This|Este]] [[hotel|hotel]] [[is|es]] [[more expensive|más caro]] [[than|que]] [[that|ese]] [[one|uno]].', expectedResponse: 'This hotel is more expensive than that one.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: describe cómo te sientes cuando hablas inglés (nervous, confident, etc.).', targetText: '[[I feel|Me siento]] ____ [[when|cuando]] [[I speak English|hablo inglés]].', expectedResponse: 'I feel nervous/confident/... when I speak English.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: cuánto tiempo llevas estudiando inglés.', targetText: '[[I have been studying|Llevo estudiando]] ____ [[for|desde hace]] ____.', expectedResponse: 'I have been studying English for [X years/months].' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[is|está]] [[proud|orgullosa]] [[of|de]] [[her|su]] [[achievement|logro]].', expectedResponse: 'She is proud of her achievement.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[looking forward to|esperando]] [[visiting|visitar]] [[my|a mi]] [[family|familia]] [[next|el próximo]] [[month|mes]].', expectedResponse: 'I am looking forward to visiting my family next month.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[The|El]] [[book|libro]] [[which|que]] [[I|yo]] [[bought|compré]] [[is|es]] [[very|muy]] [[interesting|interesante]].', expectedResponse: 'The book which I bought is very interesting.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: tu profesión o la de alguien de tu familia.', targetText: '[[I am|Soy]] / [[My|Mi]] ____ [[is|es]] [[a|un/una]] ____.', expectedResponse: 'I am a teacher. / My sister is an architect.' }, topicName: 'Speaking' },
  { id: 'b1-u1-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Personal Info', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe en 2-3 frases tu experiencia aprendiendo inglés (cómo te sentías al principio, cómo te sientes ahora).', targetText: '____. ____. ____.', expectedResponse: 'At first I felt... Now I feel more... I have been studying for...' }, topicName: 'Speaking' },
];
