/**
 * Unidad 27 B1 — Lección 2: Vocabulario (Choices)
 * 15 ejercicios: vocabulario de elecciones y decisiones
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Choices|Elecciones]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_27_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u27-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The act of selecting between options|El acto de seleccionar entre opciones]]:', options: ['[[choice|elección]]', '[[chance|oportunidad]]', '[[change|cambio]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Something you can choose|Algo que puedes elegir]]:', options: ['[[option|opción]]', '[[obligation|obligación]]', '[[opinion|opinión]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To pick one thing over another|Elegir una cosa sobre otra]]:', options: ['[[prefer|preferir]]', '[[refuse|rechazar]]', '[[forget|olvidar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The other possibility|La otra posibilidad]]:', options: ['[[alternative|alternativa]]', '[[mistake|error]]', '[[problem|problema]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make a choice|Tomar una decisión]]:', options: ['[[decide|decidir]]', '[[delay|retrasar]]', '[[discuss|discutir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When you cannot choose|Cuando no puedes elegir]]:', options: ['[[indecisive|indeciso]]', '[[impatient|impaciente]]', '[[incorrect|incorrecto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A difficult choice between two bad options|Una elección difícil entre dos malas opciones]]:', options: ['[[dilemma|dilema]]', '[[dream|sueño]]', '[[dinner|cena]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To select from options|Seleccionar de entre opciones]]:', options: ['[[choose|elegir]]', '[[change|cambiar]]', '[[charge|cobrar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A list of things to choose from|Una lista de cosas para elegir]]:', options: ['[[menu|menú]]', '[[message|mensaje]]', '[[method|método]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What you want more|Lo que quieres más]]:', options: ['[[preference|preferencia]]', '[[pressure|presión]]', '[[problem|problema]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To think about options before deciding|Pensar en opciones antes de decidir]]:', options: ['[[consider|considerar]]', '[[complete|completar]]', '[[complain|quejarse]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The result of a decision|El resultado de una decisión]]:', options: ['[[outcome|resultado]]', '[[income|ingresos]]', '[[outline|esquema]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When you have to choose one of two|Cuando tienes que elegir uno de dos]]:', options: ['[[either...or|o...o]]', '[[both...and|y...y]]', '[[neither...nor|ni...ni]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To say no to an option|Decir no a una opción]]:', options: ['[[reject|rechazar]]', '[[receive|recibir]]', '[[remember|recordar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u27-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Choices', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The ability to choose freely|La capacidad de elegir libremente]]:', options: ['[[freedom of choice|libertad de elección]]', '[[lack of options|falta de opciones]]', '[[force of habit|fuerza del hábito]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
