/**
 * Unidad 46 B1 — Lección 1: Gramática (Had better, it's time)
 * 15 ejercicios: advice structures
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Had better & It\'s time|Had better e It\'s time]]';
const INSTRUCTIONS = 'Completa con la forma correcta de had better o it\'s time.';

export const UNIT_46_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u46-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[see|ver]] [[a doctor|un médico]] [[soon|pronto]].', options: ['[[had better|más te vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better|Más te vale]] [[expresses strong advice|expresa consejo fuerte]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] ____ ____ ____ ____ [[go|ir]] [[home|a casa]].', options: ['[[to|de]]', '[[for|de]]', '[[that|que]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: '[[It\'s time to + infinitive|Ya es hora de + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[leave|marcharnos]] [[now|ahora]] [[or|o]] [[we\'ll miss|perderemos]] [[the train|el tren]].', options: ['[[had better|más nos vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better|Más nos vale]] [[for urgent advice|para consejo urgente]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] ____ ____ ____ ____ [[you|tú]] [[started|empezaras]] [[studying|estudiar]].', options: ['[[that|que]]', '[[for|de]]', '[[to|de]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It\'s time (that) + past|Ya es hora (de que) + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[not|no]] [[tell|decir]] [[him|a él]] [[the truth|la verdad]] [[yet|todavía]].', options: ['[[had better|más le vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better not|Más vale que no]] [[for negative advice|para consejo negativo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s high time|Ya es hora]] ____ ____ ____ ____ [[we|nosotros]] [[made|tomáramos]] [[a decision|una decisión]].', options: ['[[that|que]]', '[[for|de]]', '[[to|de]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It\'s high time (that) + past|Ya es hora (de que) + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[apologise|disculparme]] [[to|con]] [[her|ella]] [[before|antes de]] [[it\'s too late|sea demasiado tarde]].', options: ['[[had better|más me vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better|Más me vale]] [[after I|después de I]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] ____ ____ ____ ____ [[for|para]] [[lunch|almorzar]].', options: ['[[for|de]]', '[[to|de]]', '[[that|que]]'], correctAnswer: 'for', acceptableAnswers: ['for'], explanation: '[[It\'s time for + noun|Ya es hora de + sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] ____ ____ ____ ____ [[hurry|darte prisa]] [[or|o]] [[you\'ll be late|llegarás tarde]].', options: ['[[had better|más te vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better|Más te vale]] [[warns of consequences|advierte de consecuencias]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s about time|Ya era hora]] ____ ____ ____ ____ [[he|él]] [[got|consiguiera]] [[a job|un trabajo]].', options: ['[[that|que]]', '[[for|de]]', '[[to|de]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It\'s about time (that) + past|Ya era hora (de que) + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[check|revisar]] [[the schedule|el horario]] [[before|antes de]] [[booking|reservar]].', options: ['[[had better|más les vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better|Más les vale]] [[for advice|para consejo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] ____ ____ ____ ____ [[go|ir]] [[to bed|a la cama]].', options: ['[[to|de]]', '[[for|de]]', '[[that|que]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: '[[It\'s time to + infinitive|Ya es hora de + infinitivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[not|no]] [[forget|olvidar]] [[to call|llamar]] [[her|a ella]].', options: ['[[had better|más le vale]]', '[[would better|]]', '[[have better|]]'], correctAnswer: 'had better', acceptableAnswers: ['had better'], explanation: '[[Had better not|Más vale que no]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[It\'s time|Ya es hora]] ____ ____ ____ ____ [[the children|los niños]] [[went|fueran]] [[to bed|a la cama]].', options: ['[[that|que]]', '[[for|de]]', '[[to|de]]'], correctAnswer: 'that', acceptableAnswers: ['that'], explanation: '[[It\'s time (that) + subject + past|Ya es hora (de que) + sujeto + pasado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u46-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Had better, It\'s time', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Which|Cuál]] [[is correct|es correcto]]?', options: ['[[You had better to leave|Deberías irte]]', '[[You had better leave|Más te vale irte]]', '[[You have better leave|]]'], correctAnswer: 1, explanation: '[[Had better + bare infinitive|Had better + infinitivo sin to]].' }] }, topicName: 'Grammar' },
];
