/**
 * Unidad 56 B1 — Lección 5: Expresión oral (Sport)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_56_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u56-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[The match|El partido]] [[was cancelled|fue cancelado]] [[due to rain|por la lluvia]].', expectedResponse: 'The match was cancelled due to rain.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[have been playing|he estado jugando]] [[football|fútbol]] [[since I was eight|desde que tenía ocho años]].', expectedResponse: 'I have been playing football since I was eight.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[If|Si]] [[you|tú]] [[train|entrenas]] [[hard|duro]], [[you|tú]] [[will improve|mejorarás]].', expectedResponse: 'If you train hard, you will improve.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Our team|Nuestro equipo]] [[won|ganó]] [[the championship|el campeonato]] [[last year|el año pasado]].', expectedResponse: 'Our team won the championship last year.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[You|Tú]] [[should warm up|deberías calentar]] [[before exercising|antes de hacer ejercicio]].', expectedResponse: 'You should warm up before exercising.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[The trophy|El trofeo]] [[was awarded|fue otorgado]] [[to the best player|al mejor jugador]].', expectedResponse: 'The trophy was awarded to the best player.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[is going to run|va a correr]] [[a marathon|un maratón]] [[next month|el próximo mes]].', expectedResponse: 'He is going to run a marathon next month.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[told me|me dijo]] [[that|que]] [[she had won|había ganado]] [[the race|la carrera]].', expectedResponse: 'She told me that she had won the race.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: tu deporte favorito y por qué te gusta.', targetText: '____ ____ ____ ____.', expectedResponse: 'My favourite sport is [sport] because [reason].' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: una frase sobre un partido o competición usando passive.', targetText: '____ ____ ____ ____.', expectedResponse: '[Event] was [past participle] [when/where].' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[Athletes|Los atletas]] [[must train|deben entrenar]] [[every day|cada día]] [[to stay fit|para mantenerse en forma]].', expectedResponse: 'Athletes must train every day to stay fit.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[When|Cuando]] [[you|tú]] [[do exercise|haces ejercicio]], [[you|tú]] [[feel better|te sientes mejor]].', expectedResponse: 'When you do exercise, you feel better.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[The stadium|El estadio]] [[was built|fue construido]] [[in 2020|en 2020]].', expectedResponse: 'The stadium was built in 2020.' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un consejo sobre deporte usando should.', targetText: '____ ____ ____ ____.', expectedResponse: 'You should [verb] [when/why].' }, topicName: 'Speaking' },
  { id: 'b1-u56-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Sport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe una competición o partido que recuerdes (2-3 frases).', targetText: '____. ____. ____.', expectedResponse: 'Last [time] I [watched/played] [sport]. [What happened]. It was [adjective].' }, topicName: 'Speaking' },
];
