/**
 * Unidad 35 B1 — Lección 6: Expresión escrita (Repaso 31–34)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_35_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u35-l6-w1', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases usando who, which o that y un question tag.', expressionHint: 'Puedes usar: [[The person who|La persona que]], [[It\'s nice, isn\'t it|Es bonito, no es]]?', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con who, which o that.', questions: [{ question: '[[The woman|La mujer]] ____ ____ ____ ____ [[lives|vive]] [[next door|al lado]] [[is|es]] [[a vet|veterinaria]].', options: ['[[who|que]]', '[[which|que]]', '[[where|donde]]'], correctAnswer: 'who', acceptableAnswers: ['who', 'that'], explanation: '[[Who|Quien]] [[for people|para personas]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la question tag correcta.', questions: [{ question: "[[It's|Es]] [[a nice day|un buen día]], ____ ____ ____ ____?", options: ["[[isn't it|no es así]]", "[[is it|es así]]", "[[doesn't it|no es así]]"], correctAnswer: "isn't it", acceptableAnswers: ["isn't it"], explanation: "[[Positive|Afirmación]] → [[negative tag|tag negativa]]." }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con bored/boring o excited/exciting.', questions: [{ question: '[[I|Yo]] [[was|estaba]] ____ ____ ____ ____ [[because|porque]] [[the film|la película]] [[was|era]] ____.', options: ['[[bored / boring|aburrido / aburrida]]', '[[boring / bored|aburrida / aburrido]]', '[[excited / exciting|emocionado / emocionante]]'], correctAnswer: 'bored / boring', acceptableAnswers: ['bored / boring'], explanation: '[[Bored|Aburrido]] = [[feeling|sentimiento]]. [[Boring|Aburrida]] = [[causes|causa]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w5', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con non-defining (who/which con comas) y otra con -ed/-ing.', expressionHint: 'Puedes usar: [[My friend, who|Mi amigo, que]], [[I was excited because|Estaba emocionado porque]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con who o which (non-defining).', questions: [{ question: '[[My sister|Mi hermana]], ____ ____ ____ ____ [[lives|vive]] [[in Madrid|en Madrid]], [[is|es]] [[a teacher|profesora]].', options: ['[[who|que]]', '[[which|que]]', '[[that|que]]'], correctAnswer: 'who', acceptableAnswers: ['who'], explanation: '[[Who|Quien]] [[for people|para personas]] [[with commas|con comas]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She|Ella]] [[works|trabaja]] [[at the bank|en el banco]], ____ ____ ____ ____?', options: ["[[doesn't she|no trabaja]]", "[[does she|trabaja]]", "[[isn't she|no es]]"], correctAnswer: "doesn't she", acceptableAnswers: ["doesn't she"], explanation: "[[She works|Ella trabaja]] → [[doesn't she|no trabaja]]." }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con interested o interesting.', questions: [{ question: '[[I|Yo]] [[am|estoy]] ____ ____ ____ ____ [[in|en]] [[learning|aprender]] [[English|inglés]].', options: ['[[interested|interesado]]', '[[interesting|interesante]]', '[[interest|interés]]'], correctAnswer: 'interested', acceptableAnswers: ['interested'], explanation: '[[Interested|Interesado]] = [[how I feel|cómo me siento]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w9', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre el medio ambiente o servicios usando who/which y un question tag.', expressionHint: 'Puedes usar: [[Recycling, which|El reciclaje, que]], [[The service was good, wasn\'t it|El servicio era bueno, no era]]?', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The river|El río]], ____ ____ ____ ____ [[flows|fluye]] [[through|a través de]] [[the city|la ciudad]], [[is|es]] [[polluted|contaminado]].', options: ['[[who|que]]', '[[which|que]]', '[[that|que]]'], correctAnswer: 'which', acceptableAnswers: ['which'], explanation: '[[Non-defining|Explicativa]]: [[which|que]] [[for things|para cosas]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la question tag correcta.', questions: [{ question: "[[There|Hay]] [[is|está]] [[a pharmacy|una farmacia]] [[nearby|cerca]], ____ ____ ____ ____?", options: ["[[isn't there|no hay]]", "[[is there|hay]]", "[[aren't there|no hay]]"], correctAnswer: "isn't there", acceptableAnswers: ["isn't there"], explanation: "[[There is|Hay]] → [[isn't there|no hay]]." }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w12', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase con "Anyone who..." sobre un hobby.', expressionHint: '[[Anyone who|Cualquiera que]] + [[loves|ama]] + [[noun|sustantivo]].', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The news|La noticia]] [[was|era]] ____ ____ ____ ____. [[I|Yo]] [[felt|me sentí]] ____.', options: ['[[exciting / excited|emocionante / emocionado]]', '[[excited / exciting|emocionado / emocionante]]', '[[boring / bored|aburrida / aburrido]]'], correctAnswer: 'exciting / excited', acceptableAnswers: ['exciting / excited'], explanation: '[[Exciting|Emocionante]] = [[causes|causa]]. [[Excited|Emocionado]] = [[feeling|sentimiento]].' }] }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w14', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con defining relative y otra con question tag.', expressionHint: 'Ejemplo: The book that I bought... It\'s interesting, isn\'t it?', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u35-l6-w15', type: 'writing', level: 'B1', topic: 'Review 31-34', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) que incluya: una oración con who/which, un question tag y un adjetivo -ed/-ing.', expressionHint: 'Puedes usar: [[The person who|La persona que]], [[Recycling, which|El reciclaje, que]], [[It\'s important, isn\'t it|Es importante, no es]]? [[I was excited because|Estaba emocionado porque]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
