/**
 * Unidad 54 B1 — Lección 1: Gramática (Review: tenses)
 * 15 ejercicios: present, past, future, perfect tenses
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Review Tenses|Repaso de tiempos verbales]]';
const INSTRUCTIONS = 'Elige la forma correcta del verbo.';

export const UNIT_54_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u54-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[English|inglés]] [[every day|cada día]].', options: ['[[studies|estudia]]', '[[is studying|está estudiando]]', '[[has studied|ha estudiado]]'], correctAnswer: 'studies', acceptableAnswers: ['studies'], explanation: '[[Present simple|Presente simple]]: [[habit|hábito]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[to London|a Londres]] [[last year|el año pasado]].', options: ['[[went|fui]]', '[[have been|he ido]]', '[[go|voy]]'], correctAnswer: 'went', acceptableAnswers: ['went'], explanation: '[[Past simple|Pasado simple]]: [[finished time|tiempo acabado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] ____ ____ ____ ____ [[a new house|una casa nueva]] [[next month|el próximo mes]].', options: ['[[are buying|están comprando]]', '[[will buy|comprarán]]', '[[bought|compraron]]'], correctAnswer: 'are buying', acceptableAnswers: ['are buying'], explanation: '[[Present continuous|Presente continuo]]: [[future plan|plan futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[never been|nunca he estado]] [[to Japan|en Japón]].', options: ['[[have|he]]', '[[had|había]]', '[[was|estaba]]'], correctAnswer: 'have', acceptableAnswers: ['have'], explanation: '[[Present perfect|Presente perfecto]]: [[experience|experiencia]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[When|Cuando]] [[I arrived|llegué]], [[she|ella]] ____ ____ ____ ____ [[already left|ya había salido]].', options: ['[[had already left|ya había salido]]', '[[has already left|ya ha salido]]', '[[already left|ya salió]]'], correctAnswer: 'had already left', acceptableAnswers: ['had already left'], explanation: '[[Past perfect|Pasado perfecto]]: [[before another past action|antes de otra acción pasada]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Look|Mira]]! [[It|Él]] ____ ____ ____ ____ [[raining|lloviendo]].', options: ['[[is raining|está lloviendo]]', '[[rains|llueve]]', '[[has rained|ha llovido]]'], correctAnswer: 'is raining', acceptableAnswers: ['is raining'], explanation: '[[Present continuous|Presente continuo]]: [[now|ahora]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I think|Creo que]] [[it|él]] ____ ____ ____ ____ [[tomorrow|mañana]].', options: ['[[will rain|lloverá]]', '[[rains|llueve]]', '[[is raining|está lloviendo]]'], correctAnswer: 'will rain', acceptableAnswers: ['will rain'], explanation: '[[Will|Will]]: [[prediction|predicción]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[here|aquí]] [[since 2020|desde 2020]].', options: ['[[has lived|ha vivido]]', '[[lived|vivía]]', '[[lives|vive]]'], correctAnswer: 'has lived', acceptableAnswers: ['has lived'], explanation: '[[Present perfect|Presente perfecto]]: [[since|desde]] [[unfinished time|tiempo no acabado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[While|Mientras]] [[I|yo]] ____ ____ ____ ____ [[,|,]] [[I saw|vi]] [[an old friend|un viejo amigo]].', options: ['[[was walking|estaba caminando]]', '[[walked|caminé]]', '[[have walked|he caminado]]'], correctAnswer: 'was walking', acceptableAnswers: ['was walking'], explanation: '[[Past continuous|Pasado continuo]]: [[background action|acción de fondo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[By next year|Para el próximo año]], [[I|yo]] ____ ____ ____ ____ [[finished|terminado]] [[my degree|mi carrera]].', options: ['[[will have finished|habré terminado]]', '[[have finished|he terminado]]', '[[finish|termino]]'], correctAnswer: 'will have finished', acceptableAnswers: ['will have finished'], explanation: '[[Future perfect|Futuro perfecto]]: [[by + future time|para + tiempo futuro]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[been working|estado trabajando]] [[all morning|toda la mañana]].', options: ['[[has been working|ha estado trabajando]]', '[[had been working|había estado trabajando]]', '[[is working|está trabajando]]'], correctAnswer: 'has been working', acceptableAnswers: ['has been working'], explanation: '[[Present perfect continuous|Presente perfecto continuo]]: [[duration|duración]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[going to visit|iba a visitar]] [[my parents|a mis padres]] [[but|pero]] [[I cancelled|cancelé]].', options: ['[[was going to visit|iba a visitar]]', '[[am going to visit|voy a visitar]]', '[[went to visit|fui a visitar]]'], correctAnswer: 'was going to visit', acceptableAnswers: ['was going to visit'], explanation: '[[Was going to|Iba a]]: [[unfulfilled plan|plan no realizado]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Water|El agua]] ____ ____ ____ ____ [[at 100°C|a 100°C]].', options: ['[[boils|hierve]]', '[[is boiling|está hirviendo]]', '[[has boiled|ha hervido]]'], correctAnswer: 'boils', acceptableAnswers: ['boils'], explanation: '[[Present simple|Presente simple]]: [[general truth|verdad general]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] ____ ____ ____ ____ [[to Paris|a París]] [[three times|tres veces]].', options: ['[[has been|ha estado]]', '[[went|fue]]', '[[was|estaba]]'], correctAnswer: 'has been', acceptableAnswers: ['has been'], explanation: '[[Present perfect|Presente perfecto]]: [[number of times|número de veces]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u54-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Tenses', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The train|El tren]] ____ ____ ____ ____ [[at 6pm|a las 6pm]] [[tomorrow|mañana]].', options: ['[[leaves|sale]]', '[[will leave|saldrá]]', '[[is leaving|está saliendo]]'], correctAnswer: 0, explanation: '[[Present simple|Presente simple]]: [[timetable|horario]].' }] }, topicName: 'Grammar' },
];
