/**
 * Unidad 30 B1 — Lección 6: Expresión escrita (Repaso 26–29)
 * 15 ejercicios - Mixed content from units 26-29
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_30_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u30-l6-w1', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre una decisión que tuviste que tomar. Usa both, either o neither y vocabulario de elecciones.', expressionHint: 'Puedes usar: [[Both|Ambos]], [[Either...or|O...o]], [[Neither...nor|Ni...ni]], [[choice|elección]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase con la palabra correcta.', questions: [{ question: '[[There isn\'t|No hay]] ____ [[sugar|azúcar]] [[left|left]].', options: ['[[much|mucho]]', '[[many|muchos]]', '[[a few|unos pocos]]'], correctAnswer: 'much', acceptableAnswers: ['much'], explanation: '[[Much|Mucho]] [[with uncountable|con incontable]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre reflexivo correcto.', questions: [{ question: '[[She|Ella]] [[cut|se cortó]] ____ [[while|mientras]] [[cooking|cocinaba]].', options: ['[[herself|a sí misma]]', '[[himself|a sí mismo]]', '[[myself|a mí mismo]]'], correctAnswer: 'herself', acceptableAnswers: ['herself'], explanation: '[[Herself|A sí misma]] [[for she|para ella]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el artículo correcto.', questions: [{ question: '[[I|Yo]] [[went|fui]] [[to|a]] ____ [[old|viejo]] [[church|iglesia]].', options: ['[[an|un]]', '[[a|un]]', '[[the|la]]'], correctAnswer: 'an', acceptableAnswers: ['an'], explanation: '[[An|Un]] [[before vowel sound|antes de sonido vocálico]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w5', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con much/many y otra con a/an/the sobre comida o edificios.', expressionHint: 'Puedes usar: [[There is much|Hay mucho]], [[There are many|Hay muchos]], [[The|El/La]], [[a|un]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[You can have|Puedes tener]] ____ [[tea|té]] [[or|o]] [[coffee|café]].', options: ['[[either|o]]', '[[neither|ni]]', '[[both|ambos]]'], correctAnswer: 'either', acceptableAnswers: ['either'], explanation: '[[Either A or B|O A o B]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el pronombre reflexivo correcto.', questions: [{ question: '[[We|Nosotros]] [[need|necesitamos]] [[to|a]] [[believe|creer]] [[in|en]] ____.', options: ['[[ourselves|nosotros mismos]]', '[[themselves|ellos mismos]]', '[[yourself|tú mismo]]'], correctAnswer: 'ourselves', acceptableAnswers: ['ourselves'], explanation: '[[Ourselves|A nosotros mismos]] [[for we|para nosotros]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el artículo correcto.', questions: [{ question: '[[There is|Hay]] ____ [[museum|museo]] [[opposite|enfrente]] [[the|del]] [[park|parque]].', options: ['[[a|un]]', '[[an|un]]', '[[the|el]]'], correctAnswer: 'a', acceptableAnswers: ['a'], explanation: '[[A|Un]] [[for first mention|para primera mención]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w9', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre una experiencia personal que te enseñó algo. Usa pronombres reflexivos.', expressionHint: 'Puedes usar: [[I learned|aprendí]], [[myself|a mí mismo]], [[by myself|por mí mismo]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[Both|Ambos]] ____ [[choices|opciones]] [[are|son]] [[valid|válidas]].', options: ['[[choices|opciones]]', '[[choice|opción]]'], correctAnswer: 'choices', acceptableAnswers: ['choices'], explanation: '[[Both + plural|Both + plural]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con much/many/a lot of.', questions: [{ question: '[[How|Cuántas]] ____ [[apples|manzanas]] [[do you need|necesitas]]?', options: ['[[many|muchas]]', '[[much|mucho]]', '[[a lot of|muchas]]'], correctAnswer: 'many', acceptableAnswers: ['many'], explanation: '[[Many|Muchas]] [[with countable|con contable]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w12', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase describiendo un edificio en tu ciudad usando the/a/an.', expressionHint: '[[The|El/La]] [[library|biblioteca]] [[is|está]] [[near|cerca]]...', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con neither...nor.', questions: [{ question: '[[Neither|Ni]] ____ [[nor|ni]] [[Maria|María]] [[wants|quiere]] [[to go|ir]].', options: ['[[Tom|Tom]]', '[[Tom or|Tom o]]'], correctAnswer: 'Tom', acceptableAnswers: ['Tom'], explanation: '[[Neither A nor B|Ni A ni B]].' }] }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w14', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con both...and y otra con either...or.', expressionHint: 'Ejemplo: Both...and... Either...or...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u30-l6-w15', type: 'writing', level: 'B1', topic: 'Review 26-29', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre tu ciudad o una decisión que tomaste. Usa: cuantificadores (much/many/a lot), both/either/neither, artículos (a/an/the), y pronombres reflexivos.', expressionHint: 'Puedes usar: [[There are many|Hay muchos]], [[Both|Ambos]], [[Either|O]], [[the|el/la]], [[myself|a mí mismo]], [[I enjoyed myself|disfruté]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
