/**
 * Unidad 39 B1 — Lección 2: Vocabulario (Explaining)
 * 15 ejercicios: explaining
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Explaining|Explicar]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_39_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u39-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear|Hacer algo claro]]:', options: ['[[explain|explicar]]', '[[confuse|confundir]]', '[[ignore|ignorar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The reason for something|La razón de algo]]:', options: ['[[cause|causa]]', '[[effect|efecto]]', '[[result|resultado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What happens as a result|Lo que ocurre como resultado]]:', options: ['[[effect|efecto]]', '[[cause|causa]]', '[[reason|razón]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To give more information|Dar más información]]:', options: ['[[clarify|aclarar]]', '[[hide|ocultar]]', '[[ignore|ignorar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear with examples|Hacer algo claro con ejemplos]]:', options: ['[[illustrate|ilustrar]]', '[[complicate|complicar]]', '[[confuse|confundir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something easier to understand|Hacer algo más fácil de entender]]:', options: ['[[simplify|simplificar]]', '[[complicate|complicar]]', '[[confuse|confundir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To describe in detail|Describir en detalle]]:', options: ['[[describe in detail|describir en detalle]]', '[[summarize|resumir]]', '[[brief|breve]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear|Hacer algo claro]]:', options: ['[[make clear|esclarecer]]', '[[obscure|oscurecer]]', '[[hide|ocultar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To give the main points|Dar los puntos principales]]:', options: ['[[summarize|resumir]]', '[[expand|expandir]]', '[[extend|extender]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To show the connection between things|Mostrar la conexión entre cosas]]:', options: ['[[demonstrate|demostrar]]', '[[hide|ocultar]]', '[[ignore|ignorar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear step by step|Hacer algo claro paso a paso]]:', options: ['[[break down|desglosar]]', '[[combine|combinar]]', '[[mix|mezclar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear|Hacer algo claro]]:', options: ['[[elaborate|elaborar]]', '[[reduce|reducir]]', '[[shorten|acortar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear with evidence|Hacer algo claro con evidencia]]:', options: ['[[prove|probar]]', '[[doubt|dudar]]', '[[guess|adivinar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear|Hacer algo claro]]:', options: ['[[point out|señalar]]', '[[overlook|pasar por alto]]', '[[miss|perder]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u39-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Explaining', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To make something clear by repeating|Hacer algo claro repitiendo]]:', options: ['[[rephrase|reformular]]', '[[copy|copiar]]', '[[delete|eliminar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
