/**
 * Unidad 26 B1 — Lección 6: Expresión escrita (Quantifiers, Food & drink)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_26_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u26-l6-w1', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre tu dieta: qué comes mucho, qué comes poco y qué bebes.', expressionHint: 'Puedes usar: [[I eat a lot of|como mucho]], [[I don\'t eat much|no como mucha]], [[I drink|bebo]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase con la palabra correcta.', questions: [{ question: '[[There isn\'t|No hay]] ____ [[water|agua]] [[left|left]].', options: ['[[much|mucha]]', '[[many|muchas]]', '[[few|pocas]]'], correctAnswer: 'much', acceptableAnswers: ['much'], explanation: '[[Water|Agua]] = [[uncountable|incontable]] → [[much|mucho]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[There are|Hay]] ____ [[apples|manzanas]] [[in|en]] [[the|la]] [[fridge|nevera]].', options: ['[[many|muchas]]', '[[much|mucha]]', '[[little|poca]]'], correctAnswer: 'many', acceptableAnswers: ['many'], explanation: '[[Apples|Manzanas]] = [[countable|contable]] → [[many|muchos]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: '[[Add|Añade]] ____ ____ ____ ____ [[salt|sal]] [[to|a]] [[the|la]] [[soup|sopa]].', options: ['[[a little|un poco de]]', '[[a few|unos pocos]]', '[[many|muchos]]'], correctAnswer: 'a little', acceptableAnswers: ['a little'], explanation: '[[A little|Un poco de]] + [[uncountable|incontable]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w5', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con "how much" y otra con "how many" sobre comida.', expressionHint: 'Puedes usar: [[How much|Cuánta]], [[How many|Cuántos]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[I|Yo]] [[have|tengo]] ____ ____ ____ ____ [[time|tiempo]] [[left|left]].', options: ['[[little|poco]]', '[[few|pocos]]', '[[many|muchos]]'], correctAnswer: 'little', acceptableAnswers: ['little'], explanation: '[[Time|Tiempo]] = [[uncountable|incontable]] → [[little|poco]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Very|Muy]] ____ ____ ____ ____ [[people|gente]] [[came|vino]] [[to|a]] [[the|la]] [[party|fiesta]].', options: ['[[few|pocas]]', '[[little|poca]]', '[[much|mucha]]'], correctAnswer: 'few', acceptableAnswers: ['few'], explanation: '[[People|Gente]] = [[countable|contable]] → [[few|pocos]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[She|Ella]] [[drinks|bebe]] ____ ____ ____ ____ [[of|de]] [[coffee|café]] [[every|cada]] [[day|día]].', options: ['[[a lot|mucho]]', '[[much|mucho]]', '[[few|pocos]]'], correctAnswer: 'a lot', acceptableAnswers: ['a lot'], explanation: '[[A lot of|Mucho]] + [[uncountable|incontable]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w9', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre qué compras en el supermercado (usa much, many, a lot of).', expressionHint: 'Puedes usar: [[I buy|compro]], [[a lot of|muchos/muchas]], [[many|muchos]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[How|Cuánta]] ____ ____ ____ ____ [[milk|leche]] [[do you need|necesitas]]?', options: ['[[much|leche]]', '[[many|leche]]', '[[few|leche]]'], correctAnswer: 'much', acceptableAnswers: ['much'], explanation: '[[Milk|Leche]] = [[uncountable|incontable]] → [[how much|cuánta]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[There are|Hay]] ____ ____ ____ ____ [[restaurants|restaurantes]] [[in|en]] [[this|esta]] [[street|calle]].', options: ['[[a few|unos pocos]]', '[[a little|un poco de]]', '[[much|mucha]]'], correctAnswer: 'a few', acceptableAnswers: ['a few'], explanation: '[[A few|Unos pocos]] + [[countable|contable]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w12', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "I don\'t eat much" y otra con "I eat a lot of".', expressionHint: '[[I don\'t eat much|No como mucha]] + [[uncountable|incontable]]. [[I eat a lot of|Como mucho]] + [[noun|sustantivo]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[I|Yo]] [[don\'t|no]] [[eat|como]] ____ ____ ____ ____ [[meat|carne]].', options: ['[[much|mucha]]', '[[many|mucha]]', '[[few|poca]]'], correctAnswer: 'much', acceptableAnswers: ['much'], explanation: '[[Meat|Carne]] = [[uncountable|incontable]] → [[much|mucho]].' }] }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w14', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con "a little" y otra con "a few" sobre comida.', expressionHint: 'Ejemplo: Add a little... There are a few...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u26-l6-w15', type: 'writing', level: 'B1', topic: 'Food & Drink', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre tus hábitos alimenticios: qué comes para desayuno, almuerzo y cena, y qué bebes. Usa much, many, a lot of, few o little.', expressionHint: 'Puedes usar: [[For breakfast I|Para el desayuno yo]], [[I drink|bebo]], [[I eat|como]], [[much|mucho]], [[many|muchos]], [[a lot of|mucho]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
