/**
 * Unidad 36 B1 — Lección 2: Vocabulario (Intensifiers)
 * 15 ejercicios: very, really, extremely, etc.
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Intensifiers|Intensificadores]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_36_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u36-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very high degree|A un grado muy alto]]:', options: ['[[extremely|extremadamente]]', '[[slightly|ligeramente]]', '[[a bit|un poco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a high degree, informal|A un grado alto, informal]]:', options: ['[[really|realmente]]', '[[hardly|apenas]]', '[[rarely|raramente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a moderate degree|A un grado moderado]]:', options: ['[[quite|bastante]]', '[[absolutely|absolutamente]]', '[[totally|totalmente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a small degree|A un grado pequeño]]:', options: ['[[slightly|ligeramente]]', '[[extremely|extremadamente]]', '[[completely|completamente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a complete degree|A un grado completo]]:', options: ['[[absolutely|absolutamente]]', '[[a bit|un poco]]', '[[fairly|bastante]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very small degree|A un grado muy pequeño]]:', options: ['[[a bit|un poco]]', '[[extremely|extremadamente]]', '[[completely|completamente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a reasonable degree|A un grado razonable]]:', options: ['[[fairly|bastante]]', '[[absolutely|absolutamente]]', '[[totally|totalmente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very strong degree|A un grado muy fuerte]]:', options: ['[[incredibly|increíblemente]]', '[[slightly|ligeramente]]', '[[a bit|un poco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a full degree|A un grado total]]:', options: ['[[completely|completamente]]', '[[hardly|apenas]]', '[[rarely|raramente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very surprising degree|A un grado muy sorprendente]]:', options: ['[[amazingly|sorprendentemente]]', '[[slightly|ligeramente]]', '[[fairly|bastante]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very bad degree|A un grado muy malo]]:', options: ['[[terribly|terriblemente]]', '[[quite|bastante]]', '[[a bit|un poco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very good degree|A un grado muy bueno]]:', options: ['[[wonderfully|maravillosamente]]', '[[hardly|apenas]]', '[[slightly|ligeramente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very clear degree|A un grado muy claro]]:', options: ['[[obviously|obviamente]]', '[[slightly|ligeramente]]', '[[a bit|un poco]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very strong degree|A un grado muy fuerte]]:', options: ['[[incredibly|increíblemente]]', '[[hardly|apenas]]', '[[rarely|raramente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u36-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Intensifiers', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To a very easy degree|A un grado muy fácil]]:', options: ['[[remarkably|notablemente]]', '[[terribly|terriblemente]]', '[[slightly|ligeramente]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
