/**
 * Unidad 37 B1 — Lección 6: Expresión escrita (Compound adjectives, Travel)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_37_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u37-l6-w1', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre un viaje que hiciste usando compound adjectives.', expressionHint: 'Puedes usar: [[a two-day trip|un viaje de dos días]], [[a five-star hotel|un hotel de cinco estrellas]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el compound adjective correcto.', questions: [{ question: '[[We went on|Fuimos de]] ____ ____ ____ ____ [[trip|viaje]] [[last summer|el verano pasado]].', options: ['[[a two-day|un viaje de dos días]]', '[[a two days|dos días]]', '[[two-day|de dos días]]'], correctAnswer: 'a two-day', acceptableAnswers: ['a two-day'], explanation: '[[Number + noun in singular|Número + sustantivo en singular]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[She has|Tiene]] [[a|un]] ____ ____ ____ ____ [[brother|hermano]] [[who lives in London|que vive en Londres]].', options: ['[[20-year-old|de 20 años]]', '[[20 years old|20 años]]', '[[20-years-old|de 20 años]]'], correctAnswer: '20-year-old', acceptableAnswers: ['20-year-old'], explanation: '[[Number + year + old|Número + año + viejo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: "[[It's|Es]] [[a|un]] ____ ____ ____ ____ [[hotel|hotel]] [[with great views|con vistas increíbles]].", options: ['[[five-star|de cinco estrellas]]', '[[five stars|cinco estrellas]]', '[[five-stars|de cinco estrellas]]'], correctAnswer: 'five-star', acceptableAnswers: ['five-star'], explanation: '[[Number + star|Número + estrella]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w5', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con number+noun (two-day) y otra con well-known o air-conditioned.', expressionHint: 'Puedes usar: [[a three-hour flight|un vuelo de tres horas]], [[air-conditioned rooms|habitaciones con aire acondicionado]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[We need|Necesitamos]] [[a|un]] ____ ____ ____ ____ [[break|descanso]] [[after this meeting|después de esta reunión]].', options: ['[[ten-minute|de diez minutos]]', '[[ten minutes|diez minutos]]', '[[ten-minutes|de diez minutos]]'], correctAnswer: 'ten-minute', acceptableAnswers: ['ten-minute'], explanation: '[[Number + minute|Número + minuto]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: "[[It's|Es]] [[a|una]] ____ ____ ____ ____ [[story|historia]] [[about a girl who travels|sobre una chica que viaja]].", options: ['[[well-known|bien conocida]]', '[[well known|bien conocida]]', '[[good-known|bien conocida]]'], correctAnswer: 'well-known', acceptableAnswers: ['well-known'], explanation: '[[Adverb + past participle|Adverbio + participio]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The hotel|El hotel]] [[offers|ofrece]] ____ ____ ____ ____ [[rooms|habitaciones]] [[with sea views|con vistas al mar]].', options: ['[[air-conditioned|con aire acondicionado]]', '[[air conditioned|con aire acondicionado]]', '[[air-condition|con aire acondicionado]]'], correctAnswer: 'air-conditioned', acceptableAnswers: ['air-conditioned'], explanation: '[[Noun + past participle|Sustantivo + participio]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w9', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases describiendo un hotel o resort usando compound adjectives.', expressionHint: 'Puedes usar: [[five-star|de cinco estrellas]], [[all-inclusive|todo incluido]], [[air-conditioned|con aire acondicionado]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con el compound adjective correcto.', questions: [{ question: '[[We took|Tomamos]] [[a|un]] ____ ____ ____ ____ [[flight|vuelo]] [[to Paris|a París]].', options: ['[[three-hour|de tres horas]]', '[[three hours|tres horas]]', '[[three-hours|de tres horas]]'], correctAnswer: 'three-hour', acceptableAnswers: ['three-hour'], explanation: '[[Number + hour|Número + hora]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The|La]] ____ ____ ____ ____ [[train|tren]] [[leaves at 8am|sale a las 8]].', options: ['[[high-speed|de alta velocidad]]', '[[high speed|de alta velocidad]]', '[[highly-speed|de alta velocidad]]'], correctAnswer: 'high-speed', acceptableAnswers: ['high-speed'], explanation: '[[Adjective + noun|Adjetivo + sustantivo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w12', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase describiendo a una persona usando un compound adjective de edad.', expressionHint: '[[He/She is a|Él/Ella es un/una]] [[30-year-old|de 30 años]] [[person|persona]].', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[The|La]] ____ ____ ____ ____ [[woman|mujer]] [[helped us|nos ayudó]] [[find the way|encontrar el camino]].', options: ['[[middle-aged|de mediana edad]]', '[[middle aged|de mediana edad]]', '[[middle-age|de mediana edad]]'], correctAnswer: 'middle-aged', acceptableAnswers: ['middle-aged'], explanation: '[[Adjective + past participle|Adjetivo + participio]].' }] }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w14', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con number+noun y otra con adverb+past participle.', expressionHint: 'Ejemplo: a four-hour journey. A well-known place.', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u37-l6-w15', type: 'writing', level: 'B1', topic: 'Travel & Descriptions', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre un viaje que hiciste, usando al menos 3 compound adjectives.', expressionHint: 'Puedes usar: [[two-day trip|viaje de dos días]], [[five-star hotel|hotel de cinco estrellas]], [[well-known|bien conocido]], [[air-conditioned|con aire acondicionado]], [[high-speed|de alta velocidad]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
