/**
 * Unidad 47 B1 — Lección 2: Vocabulario (Preferences)
 * 15 ejercicios: preference-related vocabulary
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Preferences|Preferencias]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta relacionada con preferences.';

export const UNIT_47_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u47-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To prefer one option|Preferir una opción]]:', options: ['[[would rather|preferiría]]', '[[would like|me gustaría]]', '[[would go|iría]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Stronger than would rather|Más fuerte que would rather]]:', options: ['[[would sooner|preferiría]]', '[[would prefer|preferiría]]', '[[would like|me gustaría]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Used to compare two options|Usado para comparar dos opciones]]:', options: ['[[than|que]]', '[[then|entonces]]', '[[that|que]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A personal choice|Una elección personal]]:', options: ['[[preference|preferencia]]', '[[obligation|obligación]]', '[[necessity|necesidad]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To like one thing more|Gustar más una cosa]]:', options: ['[[prefer|preferir]]', '[[need|necesitar]]', '[[want|querer]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Would prefer + to infinitive|Would prefer + infinitivo con to]]:', options: ['[[I\'d prefer to stay|Preferiría quedarme]]', '[[I\'d prefer stay|]]', '[[I prefer to stay|Prefiero quedarme]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[First choice|Primera opción]]:', options: ['[[first choice|primera opción]]', '[[last choice|última opción]]', '[[only choice|única opción]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To have a preference for|Tener preferencia por]]:', options: ['[[favour|favorecer]]', '[[favor|favorecer]]', '[[prefer|preferir]]'], correctAnswer: 2 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Instead of|En lugar de]]:', options: ['[[rather than|en lugar de]]', '[[more than|más que]]', '[[less than|menos que]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To choose one over another|Elegir uno sobre otro]]:', options: ['[[choose|elegir]]', '[[pick|elegir]]', '[[select|seleccionar]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[What you like best|Lo que más te gusta]]:', options: ['[[favourite|favorito]]', '[[best|mejor]]', '[[preferred|preferido]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To opt for something|Optar por algo]]:', options: ['[[opt for|optar por]]', '[[choose|elegir]]', '[[decide|decidir]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Would rather (that) + past|Would rather (que) + pasado]] [[expresses|expresa]]:', options: ['[[preference about another person|preferencia sobre otra persona]]', '[[obligation|obligación]]', '[[past action|acción pasada]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Contraction of would rather|Contracción de would rather]]:', options: ['[[I\'d rather|Preferiría]]', '[[I would rather|Yo preferiría]]', '[[I rather|]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u47-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Preferences', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[To express a wish for something different|Expresar deseo de algo diferente]]:', options: ['[[would rather|preferiría]]', '[[must|debe]]', '[[have to|tener que]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
