/**
 * Unidad 45 B1 — Lección 1: Gramática (Repaso 41–44)
 * 15 ejercicios: verb + preposition, adjective + preposition, during/for/while, for/since/from
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Review 41–44|Repaso 41–44]]';
const INSTRUCTIONS = 'Elige la opción correcta. Repasa unidades 41 a 44.';

export const UNIT_45_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u45-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[depend|dependo]] ____ ____ ____ ____ [[my parents|mis padres]].', options: ['[[on|de]]', '[[at|en]]', '[[for|por]]'], correctAnswer: 'on', acceptableAnswers: ['on'], explanation: '[[Depend on|Depender de]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[am|estoy]] [[interested|interesado]] ____ ____ ____ ____ [[learning|en aprender]] [[English|inglés]].', options: ['[[in|en]]', '[[at|en]]', '[[for|por]]'], correctAnswer: 'in', acceptableAnswers: ['in'], explanation: '[[Interested in|Interesado en]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I fell asleep|Me dormí]] ____ ____ ____ ____ [[the film|la película]].', options: ['[[during|durante]]', '[[for|durante]]', '[[while|mientras]]'], correctAnswer: 'during', acceptableAnswers: ['during'], explanation: '[[During|Durante]] + [[noun|sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[have lived|he vivido]] [[here|aquí]] ____ ____ ____ ____ [[2015|2015]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[point in time|punto en el tiempo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I met her|La conocí]] ____ ____ ____ ____ [[I was travelling|viajaba]].', options: ['[[while|mientras]]', '[[during|durante]]', '[[for|durante]]'], correctAnswer: 'while', acceptableAnswers: ['while'], explanation: '[[While|Mientras]] + [[clause|oración]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[is|está]] [[afraid|asustada]] ____ ____ ____ ____ [[spiders|las arañas]].', options: ['[[of|de]]', '[[about|por]]', '[[for|por]]'], correctAnswer: 'of', acceptableAnswers: ['of'], explanation: '[[Afraid of|Tener miedo de]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[lived|vivimos]] [[there|allí]] ____ ____ ____ ____ [[three years|tres años]].', options: ['[[for|durante]]', '[[during|durante]]', '[[while|mientras]]'], correctAnswer: 'for', acceptableAnswers: ['for'], explanation: '[[For|Durante]] + [[duration|duración]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g8', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The shop|La tienda]] [[is open|está abierta]] ____ ____ ____ ____ [[9am|9am]] [[to|a]] [[5pm|5pm]].', options: ['[[from|desde]]', '[[for|durante]]', '[[since|desde]]'], correctAnswer: 'from', acceptableAnswers: ['from'], explanation: '[[From...to|Desde...hasta]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Please|Por favor]] [[listen|escucha]] ____ ____ ____ ____ [[me|mí]].', options: ['[[to|a]]', '[[at|en]]', '[[for|por]]'], correctAnswer: 'to', acceptableAnswers: ['to'], explanation: '[[Listen to|Escuchar a]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] [[is|es]] [[good|bueno]] ____ ____ ____ ____ [[maths|matemáticas]].', options: ['[[at|en]]', '[[in|en]]', '[[for|para]]'], correctAnswer: 'at', acceptableAnswers: ['at'], explanation: '[[Good at|Bueno en]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] [[have known|han conocido]] [[each other|el uno al otro]] ____ ____ ____ ____ [[ten years|diez años]].', options: ['[[for|durante]]', '[[since|desde]]', '[[from|desde]]'], correctAnswer: 'for', acceptableAnswers: ['for'], explanation: '[[For|Durante]] + [[duration|duración]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[agree|estoy de acuerdo]] ____ ____ ____ ____ [[you|contigo]].', options: ['[[with|con]]', '[[to|con]]', '[[on|en]]'], correctAnswer: 'with', acceptableAnswers: ['with'], explanation: '[[Agree with|Estar de acuerdo con]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She phoned|Llamó]] ____ ____ ____ ____ [[the meeting|la reunión]].', options: ['[[during|durante]]', '[[for|durante]]', '[[while|mientras]]'], correctAnswer: 'during', acceptableAnswers: ['during'], explanation: '[[During|Durante]] + [[noun|sustantivo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[have studied|he estudiado]] [[English|inglés]] ____ ____ ____ ____ [[I was ten|tenía diez años]].', options: ['[[since|desde]]', '[[for|durante]]', '[[from|desde]]'], correctAnswer: 'since', acceptableAnswers: ['since'], explanation: '[[Since|Desde]] + [[clause|oración]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u45-l1-g15', type: 'multiple-choice', level: 'B1', topic: 'Review 41-44', difficulty: 'medium', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The phone rang|El teléfono sonó]] ____ ____ ____ ____ [[we were eating|estábamos comiendo]].', options: ['[[while|mientras]]', '[[during|durante]]', '[[for|durante]]'], correctAnswer: 0, explanation: '[[While|Mientras]] + [[clause|oración]].' }] }, topicName: 'Grammar' },
];
