/**
 * Unidad 29 B1 — Lección 1: Gramática (Reflexive pronouns)
 * 15 ejercicios: myself, yourself, himself, herself, itself, ourselves, yourselves, themselves
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Grammar|Gramática]]: [[Reflexive pronouns|Pronombres reflexivos]]';
const INSTRUCTIONS = 'Elige la opción correcta.';

export const UNIT_29_LESSON_1_GRAMMAR: Exercise[] = [
  { id: 'b1-u29-l1-g1', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[hurt|me hice daño]] ____ ____ ____ ____ [[when|cuando]] [[I|yo]] [[fell|caí]].', options: ['[[myself|a mí mismo]]', '[[yourself|a ti mismo]]', '[[himself|a sí mismo]]'], correctAnswer: 'myself', acceptableAnswers: ['myself'], explanation: '[[Myself|A mí mismo]] [[for I|para yo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g2', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[cut|se cortó]] ____ ____ ____ ____ [[while|mientras]] [[cooking|cocinaba]].', options: ['[[herself|a sí misma]]', '[[himself|a sí mismo]]', '[[itself|a sí mismo]]'], correctAnswer: 'herself', acceptableAnswers: ['herself'], explanation: '[[Herself|A sí misma]] [[for she|para ella]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g3', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] [[enjoyed|disfrutaron]] ____ ____ ____ ____ [[at|en]] [[the|la]] [[party|fiesta]].', options: ['[[themselves|a sí mismos]]', '[[ourselves|a nosotros mismos]]', '[[yourselves|a vosotros mismos]]'], correctAnswer: 'themselves', acceptableAnswers: ['themselves'], explanation: '[[Themselves|A sí mismos]] [[for they|para ellos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g4', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[need|necesitamos]] [[to|a]] [[believe|creer]] [[in|en]] ____.', options: ['[[ourselves|nosotros mismos]]', '[[themselves|ellos mismos]]', '[[yourself|tú mismo]]'], correctAnswer: 'ourselves', acceptableAnswers: ['ourselves'], explanation: '[[Ourselves|A nosotros mismos]] [[for we|para nosotros]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g5', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[He|Él]] [[taught|se enseñó]] ____ ____ ____ ____ [[to|a]] [[play|tocar]] [[the|la]] [[guitar|guitarra]].', options: ['[[himself|a sí mismo]]', '[[herself|a sí misma]]', '[[itself|a sí mismo]]'], correctAnswer: 'himself', acceptableAnswers: ['himself'], explanation: '[[Himself|A sí mismo]] [[for he|para él]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g6', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|El]] [[door|puerta]] [[opened|se abrió]] ____ ____ ____ ____.', options: ['[[itself|a sí misma]]', '[[himself|a sí mismo]]', '[[themselves|a sí mismas]]'], correctAnswer: 'itself', acceptableAnswers: ['itself'], explanation: '[[Itself|A sí misma]] [[for it (door)|para it (puerta)]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g7', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[You|Tú]] [[should|deberías]] [[be|ser]] [[proud|orgulloso]] ____ ____ ____ ____.', options: ['[[of yourself|de ti mismo]]', '[[of myself|de mí mismo]]', '[[of himself|de él mismo]]'], correctAnswer: 'of yourself', acceptableAnswers: ['of yourself'], explanation: '[[Yourself|A ti mismo]] [[for you|para tú]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g8', type: 'multiple-choice', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[made|me hice]] ____ ____ ____ ____ [[a|a]] [[sandwich|bocadillo]].', options: ['[[myself|a mí mismo]]', '[[yourself|a ti mismo]]', '[[himself|a sí mismo]]'], correctAnswer: 0, explanation: '[[Myself|A mí mismo]] [[for I|para yo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g9', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[The|Los]] [[children|niños]] [[dressed|se vistieron]] ____ ____ ____ ____ [[for|para]] [[school|el colegio]].', options: ['[[themselves|a sí mismos]]', '[[ourselves|a nosotros mismos]]', '[[yourselves|a vosotros mismos]]'], correctAnswer: 'themselves', acceptableAnswers: ['themselves'], explanation: '[[Themselves|A sí mismos]] [[for they (children)|para ellos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g10', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[organised|organizamos]] [[the|la]] [[trip|viaje]] ____.', options: ['[[by ourselves|por nosotros mismos]]', '[[by themselves|por ellos mismos]]', '[[by yourself|por ti mismo]]'], correctAnswer: 'by ourselves', acceptableAnswers: ['by ourselves'], explanation: '[[By ourselves|Por nosotros mismos]] = [[without help|sin ayuda]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g11', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[She|Ella]] [[looks|se mira]] ____ ____ ____ ____ [[in|en]] [[the|el]] [[mirror|espejo]].', options: ['[[at herself|a sí misma]]', '[[at himself|a sí mismo]]', '[[at itself|a sí misma]]'], correctAnswer: 'at herself', acceptableAnswers: ['at herself'], explanation: '[[Look at herself|Mirarse a sí misma]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g12', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Help|Sírvete]] ____ [[to|a]] [[some|algo]] [[food|comida]].', options: ['[[yourself|tú mismo]]', '[[myself|me a mí mismo]]', '[[himself|a sí mismo]]'], correctAnswer: 'yourself', acceptableAnswers: ['yourself'], explanation: '[[Help yourself|Sírvete tú mismo]] = [[imperative|imperativo]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g13', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[I|Yo]] [[found|me encontré]] ____ ____ ____ ____ [[in|en]] [[a|una]] [[difficult|difícil]] [[situation|situación]].', options: ['[[myself|a mí mismo]]', '[[yourself|a ti mismo]]', '[[themselves|a sí mismos]]'], correctAnswer: 'myself', acceptableAnswers: ['myself'], explanation: '[[Find myself|Encontrarme a mí mismo]] [[in unexpected situation|en situación inesperada]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g14', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[They|Ellos]] [[blame|se culpan]] ____ ____ ____ ____ [[for|por]] [[the|el]] [[mistake|error]].', options: ['[[themselves|a sí mismos]]', '[[ourselves|a nosotros mismos]]', '[[yourselves|a vosotros mismos]]'], correctAnswer: 'themselves', acceptableAnswers: ['themselves'], explanation: '[[Blame themselves|Culparse a sí mismos]].' }] }, topicName: 'Grammar' },
  { id: 'b1-u29-l1-g15', type: 'fill-blank', level: 'B1', topic: 'Reflexive pronouns', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[We|Nosotros]] [[need|necesitamos]] [[to|a]] [[relax|relajarnos]] ____.', options: ['[[ourselves|nosotros mismos]]', '[[themselves|ellos mismos]]', '[[yourself|tú mismo]]'], correctAnswer: 'ourselves', acceptableAnswers: ['ourselves'], explanation: '[[Relax ourselves|Relajarnos nosotros mismos]].' }] }, topicName: 'Grammar' },
];
