/**
 * Unidad 6 B1 — Lección 6: Expresión escrita (Future, Travel & transport)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Writing|Expresión escrita]]';

export const UNIT_6_LESSON_6_WRITING: Exercise[] = [
  { id: 'b1-u6-l6-w1', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre un viaje que planeas hacer (cuándo, dónde, cómo vas).', expressionHint: 'Puedes usar: [[I am going to|voy a]], [[I am flying|estoy volando]], [[next month|el próximo mes]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w2', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa la frase con la forma correcta.', questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[visit|visitar]] [[my|a mis]] [[parents|padres]] [[next|el próximo]] [[weekend|fin de semana]].', options: ['[[am going to|voy a]]', '[[will|will]]', '[[am visiting|estoy visitando]]'], correctAnswer: 'am going to', acceptableAnswers: ['am going to'], explanation: '[[Going to|Ir a]] [[for plans|para planes]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w3', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I think|Creo que]] [[it|]] ____ ____ ____ ____ [[rain|llover]] [[tomorrow|mañana]].', options: ['[[will|will]]', '[[is going to|va a]]', '[[is raining|está lloviendo]]'], correctAnswer: 'will', acceptableAnswers: ['will'], explanation: '[[Will|Will]] [[for predictions|para predicciones]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w4', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe la forma correcta.', questions: [{ question: '[[She|Ella]] ____ ____ ____ ____ [[meeting|reuniendo]] [[her|a su]] [[boss|jefe]] [[at|a las]] [[3|3]] [[PM|de la tarde]].', options: ['[[is|está]]', '[[will be|estará]]', '[[is going to be|va a estar]]'], correctAnswer: 'is', acceptableAnswers: ['is'], explanation: '[[Present continuous|Presente continuo]] [[for arrangements|para arreglos]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w5', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con "going to" (plan) y otra con "will" (predicción o promesa).', expressionHint: 'Puedes usar: [[I am going to|voy a]], [[I will|me]].', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w6', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[The|El]] [[plane|avión]] ____ ____ ____ ____ [[at|a las]] [[10|10]] [[AM|de la mañana]].', options: ['[[takes off|despega]]', '[[lands|aterriza]]', '[[departs|sale]]'], correctAnswer: 'takes off', acceptableAnswers: ['takes off', 'departs'], explanation: '[[Takes off|Despega]] [[for plane leaving|para avión saliendo]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w7', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[We|Nosotros]] ____ ____ ____ ____ [[flying|volando]] [[to|a]] [[Rome|Roma]] [[on|el]] [[Friday|viernes]].', options: ['[[are|estamos]]', '[[will be|estaremos]]', '[[are going to be|vamos a estar]]'], correctAnswer: 'are', acceptableAnswers: ['are'], explanation: '[[Present continuous|Presente continuo]] [[for fixed plans|para planes fijos]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w8', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I|Yo]] ____ ____ ____ ____ [[help|ayudar]] [[you|te]]. [[(spontaneous)|(espontáneo)]]', options: ['[[will|will]]', '[[am going to|voy a]]', '[[am helping|estoy ayudando]]'], correctAnswer: 'will', acceptableAnswers: ['will'], explanation: '[[Will|Will]] [[for spontaneous decision|para decisión espontánea]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w9', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos o tres frases sobre qué vas a hacer en tu próximo viaje.', expressionHint: 'Puedes usar: [[I am going to|voy a]], [[I will|me]], [[I am visiting|estoy visitando]].', targetLength: '2-3 frases' }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w10', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la palabra correcta.', questions: [{ question: '[[I|Yo]] [[need|necesito]] [[to|a]] ____ ____ ____ ____ [[at|en]] [[the airport|el aeropuerto]] [[two|dos]] [[hours|horas]] [[before|antes]].', options: ['[[check in|registrarme]]', '[[check out|salir]]', '[[book|reservar]]'], correctAnswer: 'check in', acceptableAnswers: ['check in'], explanation: '[[Check in|Registrarse]] [[at airport|en aeropuerto]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w11', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[I promise|Prometo]] [[I|yo]] ____ ____ ____ ____ [[call|llamar]] [[you|te]] [[when|cuando]] [[I|yo]] [[arrive|llegue]].', options: ['[[will|will]]', '[[am going to|voy a]]', '[[am calling|estoy llamando]]'], correctAnswer: 'will', acceptableAnswers: ['will'], explanation: '[[Will|Will]] [[for promises|para promesas]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w12', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe una frase usando "present continuous" para un arreglo futuro.', expressionHint: '[[I am|Estoy]] + [[verb -ing|verbo -ando]] + [[time|tiempo]].', targetLength: '1 frase' }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w13', type: 'fill-blank', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Completa con la forma correcta.', questions: [{ question: '[[Look at the clouds|Mira las nubes]]! [[It|]] ____ ____ ____ ____ [[rain|llover]].', options: ['[[is going to|va a]]', '[[will|will]]', '[[is raining|está lloviendo]]'], correctAnswer: 'is going to', acceptableAnswers: ['is going to'], explanation: '[[Going to|Ir a]] [[for prediction with evidence|para predicción con evidencia]].' }] }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w14', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe dos frases: una con "going to" (intención) y otra con "present continuous" (arreglo fijo).', expressionHint: 'Ejemplo: I am going to... I am meeting...', targetLength: '2 frases' }, topicName: 'Writing' },
  { id: 'b1-u6-l6-w15', type: 'writing', level: 'B1', topic: 'Travel & Transport', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escribe un párrafo corto (3-4 frases) sobre un viaje que planeas: cuándo vas, cómo viajas, qué has reservado y qué vas a hacer.', expressionHint: 'Puedes usar: [[I am going to|voy a]], [[I am flying|estoy volando]], [[I have booked|he reservado]], [[I will visit|visitaré]].', targetLength: '3-4 frases' }, topicName: 'Writing' },
];
