/**
 * Unidad 28 B1 — Lección 2: Vocabulario (Places: buildings)
 * 15 ejercicios
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Vocabulary|Vocabulario]]: [[Places: buildings|Lugares: edificios]]';
const INSTRUCTIONS = 'Elige la palabra o frase correcta.';

export const UNIT_28_LESSON_2_VOCABULARY: Exercise[] = [
  { id: 'b1-u28-l2-v1', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place where people live in flats|Un lugar donde la gente vive en pisos]]:', options: ['[[apartment block|bloque de apartamentos]]', '[[factory|fábrica]]', '[[warehouse|almacén]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v2', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where you borrow books|Donde pides libros prestados]]:', options: ['[[library|biblioteca]]', '[[bookshop|librería]]', '[[museum|museo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v3', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A tall building|Un edificio alto]]:', options: ['[[tower|torre]]', '[[cottage|casa de campo]]', '[[shed|cobertizo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v4', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where Christians worship|Donde los cristianos rezan]]:', options: ['[[church|iglesia]]', '[[mosque|mezquita]]', '[[temple|templo]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v5', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where you go when you are ill|Donde vas cuando estás enfermo]]:', options: ['[[hospital|hospital]]', '[[pharmacy|farmacia]]', '[[clinic|clínica]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v6', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where money is kept|Donde se guarda el dinero]]:', options: ['[[bank|banco]]', '[[shop|tienda]]', '[[post office|oficina de correos]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v7', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A large religious building|Un edificio religioso grande]]:', options: ['[[cathedral|catedral]]', '[[garage|garaje]]', '[[barn|granero]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v8', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where sports events happen|Donde ocurren eventos deportivos]]:', options: ['[[stadium|estadio]]', '[[theatre|teatro]]', '[[cinema|cine]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v9', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where people work in offices|Donde la gente trabaja en oficinas]]:', options: ['[[office block|bloque de oficinas]]', '[[warehouse|almacén]]', '[[factory|fábrica]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v10', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where you see old objects and art|Donde ves objetos antiguos y arte]]:', options: ['[[museum|museo]]', '[[gallery|galería]]', '[[exhibition|exposición]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v11', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where trains stop|Donde paran los trenes]]:', options: ['[[station|estación]]', '[[bus stop|parada de autobús]]', '[[airport|aeropuerto]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v12', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where criminals are kept|Donde se guardan los criminales]]:', options: ['[[prison|prisión]]', '[[court|tribunal]]', '[[police station|comisaría]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v13', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A place to stay when travelling|Un lugar para quedarse cuando viajas]]:', options: ['[[hotel|hotel]]', '[[hostel|hostal]]', '[[motel|motel]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v14', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[Where you buy and sell goods|Donde compras y vendes productos]]:', options: ['[[market|mercado]]', '[[mall|centro comercial]]', '[[supermarket|supermercado]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
  { id: 'b1-u28-l2-v15', type: 'multiple-choice', level: 'B1', topic: 'Places: buildings', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: INSTRUCTIONS, questions: [{ question: '[[A building with many shops|Un edificio con muchas tiendas]]:', options: ['[[shopping centre|centro comercial]]', '[[warehouse|almacén]]', '[[department store|grandes almacenes]]'], correctAnswer: 0 }] }, topicName: 'Vocabulary' },
];
