/**
 * Unidad 42 B1 — Lección 5: Expresión oral (Adjective + preposition, Feelings & attitudes)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_42_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u42-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[interested in|interesado en]] [[learning|aprender]] [[English|inglés]].', expectedResponse: 'I am interested in learning English.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[is|está]] [[afraid of|tiene miedo de]] [[spiders|las arañas]].', expectedResponse: 'She is afraid of spiders.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[He|Él]] [[is|es]] [[good at|bueno en]] [[maths|matemáticas]].', expectedResponse: 'He is good at maths.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[proud of|orgulloso de]] [[my son|mi hijo]].', expectedResponse: 'I am proud of my son.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[They|Ellos]] [[are|están]] [[famous for|famosos por]] [[their music|su música]].', expectedResponse: 'They are famous for their music.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[worried about|preocupado por]] [[the exam|el examen]].', expectedResponse: 'I am worried about the exam.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[is|está]] [[married to|casada con]] [[a doctor|un médico]].', expectedResponse: 'She is married to a doctor.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[tired of|cansado de]] [[waiting|esperar]].', expectedResponse: 'I am tired of waiting.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo de lo que estás orgulloso.', targetText: '[[I am proud of|Estoy orgulloso de]] ____ ____ ____.', expectedResponse: 'I am proud of [person/achievement].' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo de lo que tienes miedo.', targetText: '[[I am afraid of|Tengo miedo de]] ____ ____ ____.', expectedResponse: 'I am afraid of [thing].' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[are|estamos]] [[excited about|emocionados por]] [[the trip|el viaje]].', expectedResponse: 'We are excited about the trip.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[She|Ella]] [[is|es]] [[bad at|mala en]] [[cooking|cocinar]].', expectedResponse: 'She is bad at cooking.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[I|Yo]] [[am|estoy]] [[keen on|entusiasmado por]] [[sport|el deporte]].', expectedResponse: 'I am keen on sport.' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo de lo que estás emocionado.', targetText: '[[I am excited about|Estoy emocionado por]] ____ ____ ____.', expectedResponse: 'I am excited about [thing].' }, topicName: 'Speaking' },
  { id: 'b1-u42-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Feelings & Attitudes', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: describe tus sentimientos usando 3 adjetivos con preposición.', targetText: '____. ____. ____.', expectedResponse: 'I am interested in... I am good at... I am proud of...' }, topicName: 'Speaking' },
];
