/**
 * Unidad 46 B1 — Lección 5: Expresión oral (Had better, it's time, Advice)
 * 15 ejercicios de pronunciación
 */

import { Exercise } from '@/lib/exercise-generator';

const LESSON_TITLE = '[[Speaking|Expresión oral]]';

export const UNIT_46_LESSON_5_SPEAKING: Exercise[] = [
  { id: 'b1-u46-l5-s1', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha la frase y repítela en voz alta.', targetText: '[[You|Tú]] [[had better|más te vale]] [[see|ver]] [[a doctor|un médico]] [[soon|pronto]].', expectedResponse: 'You had better see a doctor soon.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s2', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It\'s time|Ya es hora]] [[to|de]] [[go|ir]] [[home|a casa]].', expectedResponse: 'It\'s time to go home.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s3', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[We|Nosotros]] [[had better|más nos vale]] [[leave|marcharnos]] [[now|ahora]].', expectedResponse: 'We had better leave now.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s4', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It\'s time|Ya es hora]] [[you|tú]] [[started|empezaras]] [[studying|estudiar]].', expectedResponse: 'It\'s time you started studying.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s5', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee la frase de abajo en voz alta.', targetText: '[[She|Ella]] [[had better|más le vale]] [[not|no]] [[tell|decir]] [[him|a él]] [[yet|todavía]].', expectedResponse: 'She had better not tell him yet.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s6', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It\'s high time|Ya es hora]] [[we|nosotros]] [[made|tomáramos]] [[a decision|una decisión]].', expectedResponse: 'It\'s high time we made a decision.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s7', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[I|Yo]] [[had better|más me vale]] [[apologise|disculparme]] [[before|antes de]] [[it\'s too late|sea demasiado tarde]].', expectedResponse: 'I had better apologise before it\'s too late.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s8', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[It\'s time|Ya es hora]] [[for|de]] [[lunch|almorzar]].', expectedResponse: 'It\'s time for lunch.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s9', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un consejo usando had better.', targetText: '[[You had better|Más te vale]] ____ ____ ____.', expectedResponse: 'You had better [verb] [object].' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s10', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: algo para lo que ya es hora usando it\'s time.', targetText: '[[It\'s time|Ya es hora]] ____ ____ ____.', expectedResponse: 'It\'s time to [verb] / It\'s time [subject] [past verb].' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s11', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[You|Tú]] [[had better|más te vale]] [[hurry|darte prisa]] [[or|o]] [[you\'ll be late|llegarás tarde]].', expectedResponse: 'You had better hurry or you\'ll be late.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s12', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Escucha y repite en voz alta.', targetText: '[[It\'s about time|Ya era hora]] [[he|él]] [[got|consiguiera]] [[a job|un trabajo]].', expectedResponse: 'It\'s about time he got a job.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s13', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Lee en voz alta.', targetText: '[[They|Ellos]] [[had better|más les vale]] [[check|revisar]] [[the schedule|el horario]] [[first|primero]].', expectedResponse: 'They had better check the schedule first.' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s14', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Di en voz alta: un consejo negativo usando had better not.', targetText: '[[You had better not|Más te vale no]] ____ ____ ____.', expectedResponse: 'You had better not [verb].' }, topicName: 'Speaking' },
  { id: 'b1-u46-l5-s15', type: 'pronunciation', level: 'B1', topic: 'Advice', difficulty: 'easy', content: { title: LESSON_TITLE, instructions: 'Habla en voz alta: da 2 consejos usando had better e it\'s time.', targetText: '____. ____.', expectedResponse: 'You had better... It\'s time to...' }, topicName: 'Speaking' },
];
