/**
 * C1 Unit 55 — Free Will and Determinism
 * Module 10: Philosophy, Ethics and the Future
 * Grammar: Advanced sentence variety — alternating simple, compound and complex structures for stylistic effect
 */

import { Exercise } from '@/lib/exercise-generator';

export const UNIT_TITLE = 'Free Will and Determinism';

export const UNIT_55_EXERCISES: Exercise[] = [
  {
    id: 'c1-u55-g1', type: 'multiple-choice', level: 'C1', topic: 'sentence-variety', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Varying Sentence Length for Effect|Variar la longitud de las oraciones para mayor efecto]]', instructions: 'Choose the passage that best uses sentence length variation for stylistic effect.',
      questions: [{ question: 'Which passage most effectively alternates sentence length and type for stylistic impact in philosophical prose?', options: ['[[The question of free will has occupied philosophers for millennia. At its core, it is simple: can human beings genuinely choose, or are their choices merely the inevitable products of prior causes — neurological, environmental, historical — over which they had no control? The answer is not simple. Compatibilists argue that freedom and determinism can coexist, that freedom consists not in being uncaused but in acting from one\'s own desires and reasoning without external compulsion. Hard determinists disagree. They hold that if every mental event is the effect of prior physical causes, the concept of genuine choice is an illusion — a reassuring story the brain tells itself about processes it neither controls nor understands.|La pregunta sobre el libre albedrío ha ocupado a los filósofos durante milenios. En su núcleo, es simple: ¿pueden los seres humanos elegir genuinamente, o sus elecciones son meramente los productos inevitables de causas previas sobre las que no tenían control? La respuesta no es simple.]]', '[[The question of free will has occupied philosophers for millennia because at its core it is a question about whether human beings can genuinely choose or whether their choices are merely the inevitable products of prior causes — neurological, environmental and historical — over which they had no control, which is why compatibilists argue that freedom and determinism can coexist while hard determinists hold that if every mental event is the effect of prior physical causes, the concept of genuine choice is an illusion.|La pregunta sobre el libre albedrío ha ocupado a los filósofos durante milenios porque en su núcleo es una pregunta sobre si los seres humanos pueden elegir genuinamente o si sus elecciones son meramente los productos inevitables de causas previas.]]', '[[Free will is complex. It is important. Many philosophers study it. They disagree. Some say choice is real. Others say it is not. The debate continues. It matters because of moral responsibility. People care about this issue.|El libre albedrío es complejo. Es importante. Muchos filósofos lo estudian.]]'], correctAnswer: 0, explanation: 'Option A alternates: medium sentence ("The question...millennia"), short sentence ("At its core, it is simple"), long complex sentence (the question), very short sentence ("The answer is not simple"), long compound-complex (Compatibilists), short simple ("Hard determinists disagree"), long complex (They hold). This creates rhythm and emphasis.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u55-g2', type: 'fill-blank', level: 'C1', topic: 'sentence-variety', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Short Sentences for Emphasis|Oraciones cortas para el énfasis]]', instructions: 'Complete with the most effective short sentence to create contrast.',
      questions: [{ question: 'Neuroscience has produced compelling evidence that conscious intentions arise after the neural processes that generate the corresponding behaviours have already begun — suggesting that the subjective experience of "deciding" may be a post-hoc narrative rather than a causal force. _______ The philosophical and legal implications are, however, profound: if our sense of authorship over our actions is systematically misleading, the foundations of moral responsibility and criminal justice require rethinking.', options: ['[[This is deeply unsettling.|Esto es profundamente inquietante.]]', '[[This finding, while contested by some researchers who argue that the experimental paradigm does not adequately capture the full range of human decision-making, remains influential.|Este hallazgo, aunque es cuestionado por algunos investigadores, sigue siendo influyente.]]', '[[Nevertheless, the question remains open and debated among philosophers and neuroscientists alike, with no clear consensus having been reached as yet.|Sin embargo, la pregunta sigue abierta y debatida entre filósofos y neurocientíficos por igual.]]'], correctAnswer: 0, explanation: 'A short, blunt sentence ("This is deeply unsettling.") creates maximum contrast after the long, measured preceding sentence — a key technique of stylistic sentence variety. The short sentence forces a pause and delivers the emotional/evaluative weight efficiently before the longer elaboration that follows.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u55-g3', type: 'multiple-choice', level: 'C1', topic: 'sentence-variety', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Compound Sentences for Balance|Oraciones compuestas para el equilibrio]]', instructions: 'Choose the compound sentence that most effectively balances opposing ideas.',
      questions: [{ question: 'Which sentence most effectively uses a compound structure to balance two philosophical positions?', options: ['[[Libertarians in the philosophical sense hold that human beings possess genuine, causally efficacious free will that is not reducible to prior physical events; hard incompatibilists, by contrast, accept the determinist premise but draw the opposite conclusion — not that we are free, but that the very concept of moral responsibility rests on a fiction.|Los libertarios en sentido filosófico sostienen que los seres humanos poseen un libre albedrío genuino y causalmente eficaz que no es reducible a eventos físicos previos; los incompatibilistas duros, por el contrario, aceptan la premisa determinista pero sacan la conclusión opuesta.]]', '[[Libertarians hold that free will exists and incompatibilists hold that it does not exist, and both positions have arguments for and against them, which means that the debate is ongoing and unresolved, as philosophers continue to disagree about this fundamental question.|Los libertarios sostienen que el libre albedrío existe y los incompatibilistas sostienen que no existe, y ambas posiciones tienen argumentos a favor y en contra.]]', '[[Some philosophers think free will is real. Other philosophers think it is not. They have different reasons. These reasons are complex. The debate is about what causes actions. It has not been resolved yet.|Algunos filósofos piensan que el libre albedrío es real. Otros filósofos piensan que no lo es.]]'], correctAnswer: 0, explanation: 'Option A uses a balanced compound structure with a semicolon (X; by contrast, Y) that precisely juxtaposes the two positions — libertarian and hard incompatibilist — with parallel syntax and a climactic "not X but Y" contrast. This is more elegant than "and...and" chains or choppy simple sentences.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u55-g4', type: 'fill-blank', level: 'C1', topic: 'sentence-variety', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Complex Sentences for Nuance|Oraciones complejas para el matiz]]', instructions: 'Complete the complex sentence.',
      questions: [{ question: 'Although the compatibilist position — that freedom is compatible with determinism _______ it is defined as acting from one\'s own desires without external coercion, rather than as the ability to have done otherwise — has attracted many distinguished defenders, including Hume, Kant and Frankfurt, it continues to strike some philosophers as a redefinition that saves the word "freedom" at the cost of abandoning what makes the concept philosophically significant.', options: ['[[provided that|siempre que]]', '[[despite|a pesar de]]', '[[however|sin embargo]]'], correctAnswer: 'provided that', acceptableAnswers: ['provided that', 'as long as', 'if'], explanation: '"Provided that" introduces a conditional clause specifying the exact condition under which the claim is true — here, the compatibilist definition of freedom. "Despite" requires a noun phrase. "However" is a conjunction that cannot introduce a conditional within a relative clause like this.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u55-g5', type: 'multiple-choice', level: 'C1', topic: 'sentence-variety', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Rhetorical Question + Short Answer for Effect|Pregunta retórica + respuesta corta para mayor efecto]]', instructions: 'Which passage most effectively uses a rhetorical question for emphasis?',
      questions: [{ question: 'Which passage uses a rhetorical question most effectively in philosophical prose?', options: ['[[Does it matter whether free will exists? In one sense, profoundly. If our actions are genuinely chosen, then praise, blame, punishment and moral admiration are appropriate responses to what people do. If they are not — if the murderer could no more have refrained from killing than the stone could have refrained from falling — then our entire practice of holding people responsible for their actions is, on this view, not justice but a sophisticated form of scapegoating.|¿Importa si el libre albedrío existe? En un sentido, profundamente. Si nuestras acciones son genuinamente elegidas, entonces el elogio, la culpa, el castigo y la admiración moral son respuestas apropiadas a lo que la gente hace.]]', '[[The question of whether free will matters is one that philosophers and others have debated for a long time and the answer to this question is complex because it depends on whether free will exists and if it does then things are different than if it does not, which is why the debate is important.|La pregunta de si el libre albedrío importa es una que los filósofos y otros han debatido por mucho tiempo.]]', '[[Free will matters a lot. Does it exist? Many people wonder. Philosophers debate it. The answer affects responsibility. If there is no free will, then responsibility is different. This is important. People should think about it.|El libre albedrío importa mucho. ¿Existe? Mucha gente se pregunta.]]'], correctAnswer: 0, explanation: 'Option A uses a two-word rhetorical question ("Does it matter?") followed by an even shorter answer ("In one sense, profoundly.") — creating impact through brevity — then elaborates in two complex parallel conditionals. This structure creates rhythm, emphasis and logical progression.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u55-v1', type: 'multiple-choice', level: 'C1', topic: 'philosophy-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Determinism and Free Will Terms|Términos de determinismo y libre albedrío]]', instructions: 'Choose the correct term.',
      questions: [{ question: 'The philosophical position that holds that freedom of the will is compatible with universal causal determinism — typically by redefining freedom as acting in accordance with one\'s own desires and reasoning without external compulsion, rather than as the ability to have acted otherwise — is known as _______.', options: ['[[compatibilism|compatibilismo]]', '[[libertarianism (philosophical)|libertarismo (filosófico)]]', '[[hard determinism|determinismo duro]]'], correctAnswer: 0, explanation: '"Compatibilism" = the view that free will and determinism are compatible; major defenders include Hume, Kant, Mill and Frankfurt. "Philosophical libertarianism" = free will exists and is incompatible with determinism (free will wins). "Hard determinism" = determinism is true and free will (understood as incompatible with determinism) does not exist.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u55-v2', type: 'fill-blank', level: 'C1', topic: 'philosophy-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Moral Responsibility|Responsabilidad moral]]', instructions: 'Complete the sentence.',
      questions: [{ question: 'The philosophical and psychological concept that a person is the genuine origin or source of their actions — rather than merely a conduit through which prior causes produce effects — and which is typically held to be a necessary condition for moral responsibility and the reactive attitudes of praise and blame, is called _______.', options: ['[[agency|agencia]]', '[[autonomy|autonomía]]', '[[intention|intención]]'], correctAnswer: 'agency', acceptableAnswers: ['agency'], explanation: '"Agency" = the capacity to act as a genuine causal origin of one\'s behaviour, not merely as an effect of prior causes. Distinguished from "autonomy" (self-governance, freedom from external control) and "intention" (the mental state with which an action is performed). Agency is the broader metaphysical concept.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u55-v3', type: 'multiple-choice', level: 'C1', topic: 'philosophy-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Causation and Necessity|Causalidad y necesidad]]', instructions: 'Choose the correct term.',
      questions: [{ question: 'The philosophical thesis that every event, including every human thought, decision and action, is the inevitable result of prior causes operating according to natural laws — such that, given the complete prior state of the universe and the laws of nature, no other outcome was ever possible — is known as _______.', options: ['[[causal determinism|determinismo causal]]', '[[fatalism|fatalismo]]', '[[predestination|predestinación]]'], correctAnswer: 0, explanation: '"Causal determinism" = every event is necessitated by prior causes + natural laws. "Fatalism" = the view that certain future events will occur regardless of what actions are taken (not the same as determinism). "Predestination" is a theological doctrine about divine foreordination, not a secular causal thesis.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u55-v4', type: 'fill-blank', level: 'C1', topic: 'philosophy-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Consciousness and Action|Conciencia y acción]]', instructions: 'Complete.',
      questions: [{ question: 'The philosophical term for the subjective, first-person character of conscious experience — "what it is like" to see red, feel pain or make a decision — which physicalists must either explain in terms of brain processes or accept as a fundamental non-physical feature of reality, is known as _______.', options: ['[[qualia|qualia / cualias]]', '[[cognition|cognición]]', '[[volition|volición]]'], correctAnswer: 'qualia', acceptableAnswers: ['qualia'], explanation: '"Qualia" (singular: quale) = the intrinsic, subjective, phenomenal properties of conscious experience — coined in modern philosophy by C.I. Lewis and popularised by Thomas Nagel and Frank Jackson. "Cognition" = mental processes of knowing and understanding (broader term). "Volition" = the faculty of making choices or decisions.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u55-v5', type: 'multiple-choice', level: 'C1', topic: 'philosophy-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Ethics and Responsibility|Ética y responsabilidad]]', instructions: 'Choose the correct term.',
      questions: [{ question: 'The stance that, because determinism is true and moral responsibility requires the ability to have done otherwise (which determinism rules out), moral praise and blame, punishment and reward are ultimately unjustified — and that a fully rational society would replace punitive responses to harmful behaviour with purely consequentialist interventions aimed at prevention — is associated with _______.', options: ['[[hard incompatibilism or free will scepticism|incompatibilismo duro o escepticismo sobre el libre albedrío]]', '[[moral relativism|relativismo moral]]', '[[ethical egoism|egoísmo ético]]'], correctAnswer: 0, explanation: '"Hard incompatibilism" (or "free will scepticism") = the position that free will is incompatible with determinism AND with indeterminism, so it does not exist, and therefore retributive moral responsibility is unjustified. Key defenders include Derk Pereboom and Gregg Caruso. "Moral relativism" concerns the cultural variation of moral norms. "Ethical egoism" is the view that self-interest is the basis of morality.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u55-r1', type: 'reading', level: 'C1', topic: 'philosophy-reading', difficulty: 'hard',
    content: { title: '[[Reading|Lectura]]: [[The Neuroscience of Choice|La neurociencia de la elección]]', instructions: 'Read and answer.',
      passage: 'The Libet experiments of the 1980s produced results that sent a tremor through the philosophy of mind. Benjamin Libet asked participants to flex their wrist at a moment of their own choosing whilst monitoring both their brain activity and their reported sense of when they had "decided" to move. The results were stark: a measurable electrical signal — the readiness potential — appeared in the brain up to 550 milliseconds before the participants reported becoming consciously aware of intending to move. Consciousness, it seemed, was arriving late to a party that had already started. Philosophers and scientists drew conflicting conclusions. Some took the experiments as compelling evidence that the experience of consciously deciding is a post-hoc rationalisation of processes already underway — that "we" do not initiate our actions so much as observe them. Others were more cautious, noting that the experiments measured only simple wrist movements under highly artificial laboratory conditions, and that the relationship between such micro-decisions and the complex, deliberative choices that matter morally — whether to keep a promise, whether to report a crime — is far from clear.',
      questions: [{ question: 'What conclusion did the more cautious interpreters of the Libet experiments draw?', options: ['[[That the experiments only measured simple wrist movements under artificial laboratory conditions, and that the relationship between such micro-decisions and the complex deliberative choices relevant to moral responsibility — keeping promises, reporting crimes — is far from clear, making broader conclusions premature.|Que los experimentos solo midieron movimientos simples de la muñeca en condiciones de laboratorio artificiales, y que la relación entre tales microdecisiones y las elecciones deliberativas complejas relevantes para la responsabilidad moral está lejos de ser clara.]]', '[[The cautious interpreters fully endorsed the conclusion that conscious decision-making is an illusion, but argued this finding supports compatibilism rather than hard determinism, since freedom does not require conscious initiation of action.|Los intérpretes cautelosos respaldaron plenamente la conclusión de que la toma de decisiones consciente es una ilusión, pero argumentaron que este hallazgo apoya el compatibilismo.]]', '[[The cautious interpreters argued that the readiness potential does not precede conscious awareness and that the experimental methodology was fundamentally flawed, requiring the entire dataset to be discarded and the experiments to be redesigned from scratch.|Los intérpretes cautelosos argumentaron que el potencial de preparación no precede a la conciencia y que la metodología experimental era fundamentalmente defectuosa.]]'], correctAnswer: 0, explanation: 'The text says: "Others were more cautious, noting that the experiments measured only simple wrist movements under highly artificial laboratory conditions, and that the relationship between such micro-decisions and the complex, deliberative choices that matter morally…is far from clear."' }] },
    topicName: 'Reading',
  },
  {
    id: 'c1-u55-r2', type: 'reading', level: 'C1', topic: 'philosophy-reading', difficulty: 'hard',
    content: { title: '[[Reading|Lectura]]: [[Moral Responsibility Without Free Will?|¿Responsabilidad moral sin libre albedrío?]]', instructions: 'Read and answer.',
      passage: 'If hard incompatibilists are correct and genuine moral responsibility requires a form of free will that we do not possess, it does not immediately follow that all practices of holding people responsible must be abandoned. The question is which practices can be justified on grounds that do not appeal to desert — the idea that people genuinely earn their punishments and rewards. Consequentialists have a straightforward answer: incapacitation, rehabilitation and deterrence are forward-looking justifications for intervention in response to harmful behaviour that do not require the metaphysical claim that the offender could have done otherwise. Retribution, on this view, is the one element of conventional criminal justice that cannot survive a hard incompatibilist critique, because retribution is precisely the claim that the offender deserves to suffer in proportion to the wrong committed — a claim that presupposes the kind of ultimate responsibility that hard incompatibilism denies. The emotional practices of resentment, indignation and moral praise may be harder to revise, since they appear to be deeply embedded in human social and psychological life; but hard incompatibilists argue that even these can be moderated, over time, by a clearer understanding of the causal histories behind behaviour.',
      questions: [{ question: 'According to the text, which element of criminal justice is most vulnerable to the hard incompatibilist critique, and why?', options: ['[[Retribution — because it is precisely the claim that an offender deserves to suffer in proportion to the wrong committed, which presupposes the kind of ultimate responsibility that hard incompatibilism denies. Forward-looking justifications such as incapacitation, rehabilitation and deterrence do not require this metaphysical claim.|La retribución, porque es precisamente la afirmación de que un delincuente merece sufrir en proporción al mal cometido, lo que presupone el tipo de responsabilidad última que el incompatibilismo duro niega.]]', '[[Deterrence is the most vulnerable element, because it requires the assumption that potential offenders are capable of responding rationally to threatened consequences — a form of deliberative agency that hard incompatibilism denies to human beings.|La disuasión es el elemento más vulnerable, porque requiere la suposición de que los posibles delincuentes son capaces de responder racionalmente a las consecuencias amenazadas.]]', '[[Rehabilitation is the most vulnerable element according to the text, because it assumes that people can be genuinely changed by experience — a form of self-improvement that presupposes the capacity for self-directed change incompatible with determinism.|La rehabilitación es el elemento más vulnerable según el texto, porque asume que las personas pueden ser genuinamente cambiadas por la experiencia.]]'], correctAnswer: 0, explanation: 'The text explicitly states: "Retribution, on this view, is the one element of conventional criminal justice that cannot survive a hard incompatibilist critique, because retribution is precisely the claim that the offender deserves to suffer in proportion to the wrong committed — a claim that presupposes the kind of ultimate responsibility that hard incompatibilism denies."' }] },
    topicName: 'Reading',
  },
  {
    id: 'c1-u55-l1', type: 'listening', level: 'C1', topic: 'philosophy-listening', difficulty: 'hard',
    content: { title: '[[Listening|Comprensión auditiva]]: [[A Philosophy Seminar on Free Will|Un seminario de filosofía sobre el libre albedrío]]', instructions: 'Read the transcript and answer.',
      passage: 'Professor: The compatibilist response to neuroscientific challenges to free will is, I think, more robust than it is often given credit for. Student A: But how can you say we are free if the brain has already initiated the action before we are consciously aware of deciding? Professor: Because freedom, on the compatibilist view, is not about the timing of neural processes — it is about the relationship between the action and the person. An action is free in the relevant sense if it flows from the agent\'s own desires, values and reasoning, even if those desires and that reasoning are themselves the products of prior causes. Student B: That seems like a redefinition that evacuates the concept of its content. If everything I want is determined, in what sense is it "mine"? Professor: That is precisely the question. And compatibilists have a response: your desires are "yours" in the sense that matters practically and morally — they are integrated into your character, responsive to reasons, and they constitute who you are. The stone has no desires that can be frustrated; the person does. That difference is real, even in a deterministic universe. Student A: So freedom is a matter of degree, not kind? Professor: On most compatibilist accounts, yes. And that, compatibilists argue, is how it should be — it accords with our intuitions about children, people under coercion and people acting from addiction versus people acting from reflective, reason-responsive agency.',
      questions: [{ question: 'How does the professor respond to Student B\'s challenge that determined desires cannot genuinely be "mine"?', options: ['[[The professor argues that desires are "yours" in the practically and morally relevant sense because they are integrated into your character, responsive to reasons and constitutive of who you are — a real difference between persons and stones that persists even in a deterministic universe.|El profesor argumenta que los deseos son "tuyos" en el sentido práctica y moralmente relevante porque están integrados en tu carácter, son sensibles a las razones y son constitutivos de quien eres, una diferencia real entre personas y piedras que persiste incluso en un universo determinista.]]', '[[The professor concedes that Student B has identified a genuine weakness in compatibilism and proposes a revised account in which freedom requires not only reason-responsiveness but also the ability to have formed different desires under different developmental conditions.|El profesor concede que el estudiante B ha identificado una debilidad genuina en el compatibilismo y propone una cuenta revisada.]]', '[[The professor dismisses the challenge as based on a misunderstanding of what "mine" means in ordinary language and argues that ordinary intuitions about ownership of desires are a reliable guide to the philosophically correct account of freedom.|El profesor descarta el desafío como basado en un malentendido de lo que "mío" significa en el lenguaje ordinario.]]'], correctAnswer: 0, explanation: 'The professor responds: "your desires are \'yours\' in the sense that matters practically and morally — they are integrated into your character, responsive to reasons, and they constitute who you are. The stone has no desires that can be frustrated; the person does. That difference is real, even in a deterministic universe."' }] },
    topicName: 'Listening',
  },
  {
    id: 'c1-u55-w1', type: 'writing', level: 'C1', topic: 'philosophy-writing', difficulty: 'hard',
    content: { title: '[[Writing|Escritura]]: [[Sentence Variety in Philosophical Argument|Variedad de oraciones en argumentación filosófica]]', instructions: 'Which response best demonstrates sentence variety in philosophical writing?',
      questions: [{ question: 'Task: Write a short paragraph (3-4 sentences) on why the free will debate matters, using varied sentence lengths.', options: ['[[The free will debate is not abstract. If determinism is true and genuine moral responsibility requires the ability to have acted otherwise, then every courtroom verdict, every act of praise or blame, every emotion of guilt and resentment rests on a presupposition that may be false — not occasionally and in edge cases, but systematically and in every instance. This is not a comfortable thought. It is, however, a thought that rigorous intellectual honesty may require us to take seriously, even if the practical consequences of widespread adoption of hard incompatibilism remain genuinely uncertain and potentially alarming.|El debate sobre el libre albedrío no es abstracto. Si el determinismo es verdadero y la responsabilidad moral genuina requiere la capacidad de haber actuado de otra manera, entonces cada veredicto judicial, cada acto de elogio o culpa, cada emoción de culpa y resentimiento descansa en una presuposición que puede ser falsa.]]', '[[The free will debate matters because it has implications for moral responsibility, which is a fundamental part of human social life, and if determinism is true and people could not have done otherwise, then it follows that our practices of holding people responsible for their actions are based on a mistaken presupposition, which means we need to reconsider how we think about punishment and blame.|El debate sobre el libre albedrío importa porque tiene implicaciones para la responsabilidad moral, que es una parte fundamental de la vida social humana.]]', '[[Free will is important. It affects responsibility. If we have no free will, punishment is wrong. This is a serious issue. Many people think about this. It changes how we see justice. The debate is ongoing.|El libre albedrío es importante. Afecta la responsabilidad.]]'], correctAnswer: 0, explanation: 'Option A uses three carefully varied sentences: short ("The free will debate is not abstract."), long complex ("If determinism is true…in every instance"), very short ("This is not a comfortable thought."), and medium complex ("It is, however, a thought…"). This creates philosophical gravitas through rhythm and contrast.' }] },
    topicName: 'Writing',
  },
  {
    id: 'c1-u55-s1', type: 'speaking', level: 'C1', topic: 'philosophy-speaking', difficulty: 'hard',
    content: { title: '[[Speaking|Expresión oral]]: [[Discussing Free Will|Hablar sobre el libre albedrío]]', instructions: 'Which response demonstrates the best C1 oral philosophical discussion?',
      questions: [{ question: 'Question: "Do you think people should be held morally responsible for their actions?"', options: ['[[My instinct is yes — and I think it is worth pausing on that word "instinct", because the compatibilist case is actually grounded in exactly that: the reactive attitudes of resentment, indignation and moral admiration that are so deeply embedded in human social life that imagining their wholesale revision is, as Strawson argued, not just practically difficult but conceptually incoherent. The question is not whether to hold people responsible, but how — and whether our practices of doing so, particularly in criminal justice, adequately track the considerations of capacity, understanding and compulsion that determine whether a given instance of responsibility attribution is genuinely appropriate.|Mi instinto es que sí, y creo que vale la pena detenerse en esa palabra "instinto", porque el argumento compatibilista se basa en exactamente eso: las actitudes reactivas de resentimiento, indignación y admiración moral que están tan profundamente arraigadas en la vida social humana que imaginar su revisión total es conceptualmente incoherente.]]', '[[Yes, I think people should be held responsible. It is important for society. If people were not responsible, there would be chaos. Laws depend on responsibility. The free will debate is complex but practically we must hold people responsible.|Sí, creo que las personas deben ser consideradas responsables. Es importante para la sociedad.]]', '[[People should be responsible for actions because this is what society is based on. Without responsibility there is no justice. Free will may or may not exist but we need responsibility anyway for practical purposes.|Las personas deben ser responsables de sus acciones porque esto es en lo que se basa la sociedad.]]'], correctAnswer: 0, explanation: 'Option A uses varied sentence length (short opening + long analytical development), references a specific philosopher (Strawson), distinguishes "whether" from "how" and introduces substantive nuance about the conditions of appropriate responsibility attribution — all markers of C1 oral philosophical discussion.' }] },
    topicName: 'Speaking',
  },
];
