/**
 * C1 Unit 24 — Oceans and Marine Life
 * Module 4: The Natural World — Consolidation
 * Grammar: Module 4 mixed review (relative clauses, absolute constructions, fronting, hedging, comment clauses)
 */

import { Exercise } from '@/lib/exercise-generator';

export const UNIT_TITLE = 'Oceans and Marine Life';

export const UNIT_24_EXERCISES: Exercise[] = [
  {
    id: 'c1-u24-g1', type: 'multiple-choice', level: 'C1', topic: 'mixed-module4', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Relative Clauses Review|Repaso de oraciones de relativo]]', instructions: 'Choose the sentence with the correct relative clause.',
      questions: [{ question: 'Which sentence correctly uses a non-defining relative clause with a preposition in formal English?', options: ['[[The deep ocean, about which scientists know less than about the surface of the moon, hosts ecosystems that have developed in complete isolation from sunlight for millions of years.|Del océano profundo, sobre el que los científicos saben menos que sobre la superficie de la luna, alberga ecosistemas que se han desarrollado en completo aislamiento de la luz solar.]]', '[[The deep ocean that scientists know less about than the surface of the moon hosts ecosystems developed in complete isolation from sunlight for millions of years.|El océano profundo del que los científicos saben menos que sobre la superficie de la luna alberga ecosistemas desarrollados en completo aislamiento de la luz solar.]]', '[[The deep ocean, which scientists know less about than the surface of the moon, hosts ecosystems that have developed in complete isolation from sunlight for millions of years.|El océano profundo, sobre el que los científicos saben menos que sobre la superficie de la luna, alberga ecosistemas que se han desarrollado en completo aislamiento de la luz solar.]]'], correctAnswer: 2, explanation: '"Which scientists know less about" (non-defining, informal) and "about which scientists know less" (non-defining, formal) are both correct. Option A misplaces the relative clause. Option C is grammatically correct.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u24-g2', type: 'fill-blank', level: 'C1', topic: 'mixed-module4', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Absolute Constructions|Construcciones absolutas]]', instructions: 'Complete with the correct absolute construction.',
      questions: [{ question: '_______ permitting, the deep-sea survey is scheduled to begin in April and should produce data that will significantly advance our understanding of hydrothermal vent ecosystems.', options: ['[[Weather|El tiempo]]', '[[Conditions|Las condiciones]]', '[[Circumstances|Las circunstancias]]'], correctAnswer: 'Weather', acceptableAnswers: ['Weather'], explanation: '"Weather permitting" = a fixed absolute construction meaning "if the weather allows it". It is a nominative absolute with an implied "being" or "is".' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u24-g3', type: 'multiple-choice', level: 'C1', topic: 'mixed-module4', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Hedging and Emphasis|Cobertura y énfasis]]', instructions: 'Choose the sentence that combines hedging with emphatic fronting correctly.',
      questions: [{ question: 'Which sentence correctly combines hedging with emphatic fronting?', options: ['[[Only rarely does the deep ocean appear to yield its secrets willingly — and even then, what emerges tends to challenge rather than confirm our existing theoretical models.|Solo raramente parece el océano profundo ceder sus secretos de buen grado — e incluso entonces, lo que emerge tiende a desafiar más que a confirmar nuestros modelos teóricos existentes.]]', '[[The deep ocean only rarely appears to be yielding its secrets willingly and when it does, what emerges is challenging our existing theoretical models significantly.|El océano profundo solo raramente parece ceder sus secretos de buen grado y cuando lo hace, lo que emerge está desafiando significativamente nuestros modelos teóricos existentes.]]', '[[Rarely, the deep ocean yields its secrets willingly, and what emerges tends to challenge rather than confirm existing theoretical models that scientists currently use.|Raramente, el océano profundo cede sus secretos de buen grado, y lo que emerge tiende a desafiar más que a confirmar los modelos teóricos existentes que usan los científicos.]]'], correctAnswer: 0, explanation: '"Only rarely + inverted auxiliary" = emphatic fronting. "Appears to yield" = hedging. "Tends to challenge" = hedging. All three structures are correctly combined in Option A.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u24-g4', type: 'fill-blank', level: 'C1', topic: 'mixed-module4', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Comment Clauses|Cláusulas de comentario]]', instructions: 'Complete the sentence.',
      questions: [{ question: 'Coral bleaching events are becoming more frequent and severe — _______, a direct consequence of rising ocean temperatures driven by climate change.', options: ['[[it must be said|hay que decirlo]]', '[[what is more|además]]', '[[needless to say|huelga decir]]'], correctAnswer: 'needless to say', acceptableAnswers: ['needless to say', 'it must be said'], explanation: '"Needless to say" = the link between bleaching events and ocean warming is widely known; the comment clause signals the speaker regards it as established fact.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u24-g5', type: 'multiple-choice', level: 'C1', topic: 'mixed-module4', difficulty: 'hard',
    content: { title: '[[Grammar|Gramática]]: [[Module 4 Mixed Review|Repaso mixto del módulo 4]]', instructions: 'Choose the most grammatically sophisticated sentence.',
      questions: [{ question: 'Which sentence best demonstrates a range of Module 4 C1 structures (relative clause, hedging, comment clause)?', options: ['[[Ocean acidification, which arguably poses as great a long-term threat to marine ecosystems as warming itself, would appear to be accelerating at a rate that, it must be said, few models had predicted a decade ago.|La acidificación del océano, que podría decirse que representa una amenaza a largo plazo para los ecosistemas marinos tan grande como el calentamiento en sí, parece estar acelerándose a un ritmo que, hay que decirlo, pocos modelos habían predicho hace una década.]]', '[[Ocean acidification is a very big problem that is getting worse and worse because of CO2 emissions which are very harmful to marine ecosystems including corals and shellfish.|La acidificación del océano es un problema muy grande que empeora cada vez más debido a las emisiones de CO2 que son muy dañinas para los ecosistemas marinos.]]', '[[Ocean acidification is accelerating faster than models predicted and this is a serious problem for marine ecosystems, it must be said, especially for corals.|La acidificación del océano se está acelerando más rápido de lo que predijeron los modelos y esto es un problema serio para los ecosistemas marinos, hay que decirlo, especialmente para los corales.]]'], correctAnswer: 0, explanation: 'Option A uses: "which" non-defining relative, "arguably" hedging, "would appear to be" modal hedge, "it must be said" comment clause — a sophisticated integration of Module 4 structures.' }] },
    topicName: 'Grammar',
  },
  {
    id: 'c1-u24-v1', type: 'multiple-choice', level: 'C1', topic: 'ocean-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Oceans and Marine Science|Océanos y ciencias marinas]]', instructions: 'Choose the correct word.',
      questions: [{ question: 'The _______ zone — the layer of ocean from the surface to a depth of approximately 200 metres where sunlight penetrates sufficiently for photosynthesis to occur — supports the vast majority of known marine life.', options: ['[[photic|fótica]]', '[[abyssal|abisal]]', '[[benthic|bentónica]]'], correctAnswer: 0, explanation: '"Photic zone" = the sunlit layer where photosynthesis occurs (0-200m). "Abyssal" refers to the deep ocean (2000-6000m). "Benthic" refers to the sea floor environment.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u24-v2', type: 'fill-blank', level: 'C1', topic: 'ocean-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Marine Conservation|Conservación marina]]', instructions: 'Complete the sentence.',
      questions: [{ question: 'The Great Barrier Reef, the world\'s largest coral _______ system, has experienced multiple mass bleaching events since 2016, with scientists warning that its long-term survival depends on limiting global warming to 1.5°C.', options: ['[[reef|arrecife]]', '[[atoll|atolón]]', '[[biome|bioma]]'], correctAnswer: 'reef', acceptableAnswers: ['reef'], explanation: '"Coral reef" = the correct term for the limestone structure built by coral polyps. An "atoll" is a ring-shaped reef; "biome" is a broader ecological category.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u24-v3', type: 'multiple-choice', level: 'C1', topic: 'ocean-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Marine Pollution|Contaminación marina]]', instructions: 'Choose the correct term.',
      questions: [{ question: 'Scientists have identified enormous accumulations of plastic waste in mid-ocean gyres — circulating current systems — creating what are known as ocean _______ patches, where plastic fragments outnumber marine organisms.', options: ['[[garbage|basura]]', '[[debris|escombros]]', '[[waste|residuos]]'], correctAnswer: 0, explanation: '"Ocean garbage patch" = the established term for ocean plastic accumulation zones. The "Great Pacific Garbage Patch" is the most well-known example.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u24-v4', type: 'multiple-choice', level: 'C1', topic: 'ocean-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Oceanography|Oceanografía]]', instructions: 'Choose the best word.',
      questions: [{ question: 'Ocean _______ — the sinking of cold, dense, saline water and the rising of warmer water — drives the global thermohaline circulation system that distributes heat around the planet and influences climate patterns on every continent.', options: ['[[thermohaline circulation|circulación termohalina]]', '[[tidal movement|movimiento de mareas]]', '[[upwelling|afloramiento]]'], correctAnswer: 0, explanation: '"Thermohaline circulation" (also called the "ocean conveyor belt") = the global circulation driven by temperature and salinity differences. "Upwelling" is the local rising of deep water; tides are lunar-driven.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u24-v5', type: 'fill-blank', level: 'C1', topic: 'ocean-vocabulary', difficulty: 'hard',
    content: { title: '[[Vocabulary|Vocabulario]]: [[Marine Biology|Biología marina]]', instructions: 'Complete with the correct word.',
      questions: [{ question: 'Bioluminescence — the production of light by living organisms — is _______ in the deep ocean, where it serves functions ranging from predator attraction to species recognition in an environment devoid of sunlight.', options: ['[[widespread|extendida]]', '[[common|común]]', '[[prevalent|prevalente]]'], correctAnswer: 'widespread', acceptableAnswers: ['widespread', 'prevalent', 'common'], explanation: '"Widespread" = common over a wide area; all three options are technically acceptable, but "widespread" is the most neutral and common collocation with bioluminescence.' }] },
    topicName: 'Vocabulary',
  },
  {
    id: 'c1-u24-r1', type: 'reading-comprehension', level: 'C1', topic: 'ocean-reading', difficulty: 'hard',
    content: { title: '[[Reading|Lectura]]: [[Marine Conservation|Conservación marina]]', instructions: 'Read and answer.',
      questions: [{ question: 'Text: "The high seas — ocean areas beyond national jurisdiction, covering some 60% of the world\'s ocean surface — were, until recently, effectively ungoverned. The 2023 High Seas Treaty represents the first binding international agreement to protect biodiversity in international waters, allowing for the creation of marine protected areas beyond national boundaries and establishing environmental impact assessment requirements for activities in the global commons."\n\nWhat does the text say about the High Seas Treaty?', options: ['[[The High Seas Treaty is a non-binding international agreement that encourages but does not require countries to protect biodiversity in international waters beyond their national boundaries.|El Tratado de Alta Mar es un acuerdo internacional no vinculante que anima pero no obliga a los países a proteger la biodiversidad en aguas internacionales.]]', '[[The 2023 High Seas Treaty is the first legally binding international agreement to protect biodiversity in international waters and enables the creation of marine protected areas beyond national jurisdiction.|El Tratado de Alta Mar de 2023 es el primer acuerdo internacional jurídicamente vinculante para proteger la biodiversidad en aguas internacionales y permite la creación de áreas marinas protegidas más allá de la jurisdicción nacional.]]', '[[The High Seas Treaty was established because existing national marine protected areas had proven completely ineffective at protecting biodiversity in international waters over the preceding decades.|El Tratado de Alta Mar se estableció porque las áreas marinas protegidas nacionales existentes habían demostrado ser completamente ineficaces para proteger la biodiversidad en aguas internacionales.]]'], correctAnswer: 1, explanation: 'The text explicitly calls it "the first binding international agreement" allowing marine protected areas beyond national boundaries — the key facts from the passage.' }] },
    topicName: 'Reading',
  },
  {
    id: 'c1-u24-r2', type: 'multiple-choice', level: 'C1', topic: 'ocean-reading', difficulty: 'hard',
    content: { title: '[[Reading|Lectura]]: [[Ocean Acidification|Acidificación del océano]]', instructions: 'Choose the best answer.',
      questions: [{ question: 'Text: "Ocean acidification — caused by the absorption of atmospheric CO₂, which forms carbonic acid in seawater — is proceeding at a rate ten times faster than any acidification event in the past 300 million years. For organisms that build calcium carbonate shells and skeletons, including corals, molluscs and many species of plankton, this represents an existential threat: as acidity rises, the very building blocks of their structures begin to dissolve."\n\nWhat makes ocean acidification particularly alarming, according to the text?', options: ['[[Ocean acidification is alarming primarily because it is directly causing mass coral bleaching events that have killed a significant proportion of the Great Barrier Reef since 2016.|La acidificación del océano es alarmante principalmente porque está causando directamente eventos de blanqueamiento masivo de corales que han matado una proporción significativa de la Gran Barrera de Coral desde 2016.]]', '[[Both its unprecedented rate compared to geological history and its direct threat to calcium carbonate-dependent organisms make it especially alarming.|Tanto su tasa sin precedentes en comparación con la historia geológica como su amenaza directa a los organismos dependientes del carbonato cálcico la hacen especialmente alarmante.]]', '[[Ocean acidification is alarming because it is caused by CO₂ absorption, which means it cannot be addressed without solving climate change first, making any specific ocean policy measures futile.|La acidificación del océano es alarmante porque es causada por la absorción de CO₂, lo que significa que no puede abordarse sin resolver primero el cambio climático, haciendo inútiles las medidas de política oceánica específicas.]]'], correctAnswer: 1, explanation: 'The text gives two reasons: unprecedented speed ("10 times faster than any event in 300 million years") AND direct dissolution threat to calcium carbonate organisms.' }] },
    topicName: 'Reading',
  },
  {
    id: 'c1-u24-l1', type: 'listening-comprehension', level: 'C1', topic: 'ocean-listening', difficulty: 'hard',
    content: { title: '[[Listening|Comprensión auditiva]]: [[Marine Policy Debate|Debate sobre política marina]]', instructions: 'Listen and choose the correct answer.',
      questions: [{ question: 'A marine biologist says: "What we tend to underestimate is the degree to which the ocean regulates conditions on land. Absorbing roughly a quarter of anthropogenic CO₂ and producing over half of the world\'s oxygen, the ocean is not merely an aquatic environment — it is an active, dynamic partner in maintaining the atmospheric conditions that make terrestrial life possible. Protecting it is not a matter of environmental sentiment; it is a matter of self-preservation."\n\nWhat argument does the biologist make about the ocean?', options: ['[[The ocean is primarily important as a source of food and economic resources, which is why protecting it from pollution and overfishing should be the main priority for marine conservation policy.|El océano es principalmente importante como fuente de alimentos y recursos económicos, por lo que protegerlo de la contaminación y la sobrepesca debería ser la principal prioridad.]]', '[[Ocean protection is not merely about preserving aquatic life but is fundamentally about maintaining the atmospheric systems that support all life on Earth, making it a matter of human self-interest.|La protección del océano no es solo sobre preservar la vida acuática, sino que se trata fundamentalmente de mantener los sistemas atmosféricos que sustentan toda la vida en la Tierra.]]', '[[Because the ocean produces more than half the world\'s oxygen, the main concern should be preventing eutrophication and algal blooms that could disrupt oxygen production in coastal waters.|Dado que el océano produce más de la mitad del oxígeno del mundo, la principal preocupación debería ser prevenir la eutrofización y las proliferaciones de algas.]]'], correctAnswer: 1, explanation: 'The biologist frames ocean protection as "self-preservation" for humans — the ocean regulates CO₂ and oxygen, making it an active partner in supporting all terrestrial life.' }] },
    topicName: 'Listening',
  },
  {
    id: 'c1-u24-w1', type: 'multiple-choice', level: 'C1', topic: 'academic-writing', difficulty: 'hard',
    content: { title: '[[Writing|Escritura]]: [[Mixed C1 Structures in Writing|Estructuras C1 mixtas en escritura]]', instructions: 'Choose the best paragraph demonstrating a range of C1 structures.',
      questions: [{ question: 'You are writing about threats to ocean health. Choose the paragraph that best demonstrates C1 writing quality:', options: ['[[What arguably threatens the long-term viability of marine ecosystems most profoundly is not any single stressor but the compounding interaction of multiple simultaneous pressures — warming, acidification, deoxygenation and overfishing — which, it must be said, no management framework currently in existence was designed to address in combination.|Lo que posiblemente amenaza más profundamente la viabilidad a largo plazo de los ecosistemas marinos no es ningún factor estresante individual, sino la interacción compuesta de múltiples presiones simultáneas — calentamiento, acidificación, desoxigenación y sobrepesca — que, hay que decirlo, ningún marco de gestión existente fue diseñado para abordar en combinación.]]', '[[There are many threats to the ocean. These include warming, acidification and overfishing. These problems are all happening at the same time and this makes them much worse. No management framework exists to deal with all of them together.|Hay muchas amenazas para el océano. Entre ellas se incluyen el calentamiento, la acidificación y la sobrepesca. Estos problemas ocurren al mismo tiempo y esto los hace mucho peores. No existe ningún marco de gestión para abordarlos todos juntos.]]', '[[The ocean faces serious threats from climate change, acidification and fishing. These threats are interacting with each other in complex ways that scientists are still trying to understand. Better policies are urgently needed to address all these threats together.|El océano enfrenta serias amenazas del cambio climático, la acidificación y la pesca. Estas amenazas interactúan entre sí de formas complejas que los científicos aún intentan comprender. Se necesitan urgentemente mejores políticas.]]'], correctAnswer: 0, explanation: 'Option A uses: pseudo-cleft fronting ("What threatens most"), "arguably" hedging, nominalisation ("compounding interaction"), listing, "which" non-defining relative, "it must be said" comment clause.' }] },
    topicName: 'Writing',
  },
  {
    id: 'c1-u24-s1', type: 'multiple-choice', level: 'C1', topic: 'speaking-oceans', difficulty: 'hard',
    content: { title: '[[Speaking|Expresión oral]]: [[Marine Conservation Discussion|Discusión sobre conservación marina]]', instructions: 'Choose the most appropriate C1 response.',
      questions: [{ question: 'The interviewer asks: "How important is it to protect the deep ocean, given how little we know about it?" Choose the best response:', options: [
        '[[Very important. The deep ocean is very mysterious and contains many unknown creatures. We need to protect it before scientists can explore it properly. It would be a shame to destroy it before we know what is in it.|Muy importante. El océano profundo es muy misterioso y contiene muchas criaturas desconocidas. Necesitamos protegerlo antes de que los científicos puedan explorarlo adecuadamente.]]',
        '[[There\'s a compelling case, I would argue, for applying the precautionary principle here: precisely because we know so little, the potential consequences of degrading deep-sea ecosystems are unpredictable. What is more, the argument that we cannot protect what we do not understand has it the wrong way round — it is arguably an additional reason for caution, not a justification for inaction.|Hay un argumento convincente, diría yo, para aplicar el principio de precaución aquí: precisamente porque sabemos tan poco, las consecuencias potenciales de degradar los ecosistemas de las profundidades marinas son impredecibles. Además, el argumento de que no podemos proteger lo que no entendemos tiene la lógica al revés.]]',
        '[[I don\'t think we need to worry too much about the deep ocean because it is so far from the surface that human activities cannot really reach it. The real problems are in shallow coastal waters where fishing and pollution cause most damage.|No creo que necesitemos preocuparnos demasiado por el océano profundo porque está tan lejos de la superficie que las actividades humanas realmente no pueden llegar a él. Los problemas reales están en las aguas costeras poco profundas.]]',
      ], correctAnswer: 1, explanation: 'Option B uses hedging ("I would argue"), applies an academic principle (precautionary principle), uses "What is more" comment clause, and sophisticatedly inverts the opposing argument.' }] },
    topicName: 'Speaking',
  },
];
